### ISSUE TITLE
[ASPagerNode] Proxy delegate methods like from UIScrollView are not called.

### ISSUE THREAD

**Issue by tomizimobile** [facebook/AsyncDisplayKit#1010]
This can easily be verified by modifying the "PagerNode" example project to assign `self` to the pagerNode delegate and implementing one of the delegate methods, such as `-scrollViewDidScroll:`.

**Comment by appleguy** [comment]
@tomizimobile thanks for the report!  I will fix this tomorrow morning before launching 1.9.4.  What delegate methods are not called?  Do the ASPagerNodeDataSource methods all get called, but none of the Delegate methods (at all?)  The proxy setup is new to ASPagerNode, so it may well be a simple error and should be easy to fix.

**Comment by tomizimobile** [comment]
@appleguy Seems like all of the `ASPagerNodeDataSource` methods are called. So far i've tried `-scrollViewDidScroll:`, `-collectionView:willDisplayNodeForItemAtIndexPath:`, and `-collectionView:didSelectItemAtIndexPath`, and none of them were called. I'd guess that there's just an error in the proxy setup.

**Comment by appleguy** [comment]
@tomizimobile Thanks again for the report - this saved the issue from going out in 1.9.4!  It is now fixed in master as of #1014.  It was indeed a simple one-line mistake in the -didLoad method, although that patch includes other cleanup refactoring.
