### ISSUE TITLE
The UIMenuController can not work for the NSTextNode

### ISSUE THREAD

**Issue by tuyuan2012** [facebook/AsyncDisplayKit#1017]
The UIMenuController can not work for the NSTextNode. Is there some good ways for function of coping or posting? Thank you....

**Comment by appleguy** [comment]
I think there is an old task about this - we should revive it, close this one, and talk in more detail there.  I think it is possible to hook up the UIMenuController, though it is not very flexible and so there was some discussion about whether it would be best to build a custom callout bubble (that style of button selector).  Are you wanting to use the full selection system with ASEditableTextNode, or just the menu controller with static ASTextNode ?  Do you need to be able to use the selection handles to select a range, or just copy all in a given block?  If you're able to upload an image of the case you're looking at in the UI that you'd like to implement, that would be a helpful guide for us to think through the possibilities (the two main branches being - integrate with UIKit's menu controller stuff, or instead just make something custom that is more flexible).

**Comment by appleguy** [comment]
Closed, now tracked by #11.  Let's keep the discussion going!

**Comment by tuyuan2012** [comment]
Thank you..Mine case is very simple. I just want to show a menu with 'Copy All' that copies the whole text when press the textNode long. I will try it with ASEditableTextNode. But ASEditableTextNode will register keyboard..

**Comment by tuyuan2012** [comment]
In my opinion, I will achieve it by building a custom callout bubble (that style of button selector) as you @appleguy suggest. Because the requirement of my case is very simple....Thank you
