### ISSUE TITLE
[ASTableView] Sometimes the main thread is stalled.

### ISSUE THREAD

**Issue by singno** [facebook/AsyncDisplayKit#1018]
![image](https://cloud.githubusercontent.com/assets/5654690/12051443/e980bb46-af3e-11e5-9c43-3cfa0a0ead91.png)

Sometimes my app is frozen by the ASTableView ,  I cann't do anything except killing the app. How can I solve this problem?

**Comment by appleguy** [comment]
@singno This should definitely be solvable and I'd like to work with you to make sure it is fixed.

- Can you confirm what version / commit you are using?  Please try using master (I'm about to launch 1.9.4, so if that's out by the time you read this, that would be fine to use).  A deadlock introduced in 1.9.3 has been resolved in master for a few weeks now.
- If the issue still occurs, please hit "pause" in the debugger and then expand the full backtrace for all threads, and select all of it to copy / paste here.  You can print it in LLDB by using "bt all"

**Comment by singno** [comment]
![image](https://cloud.githubusercontent.com/assets/5654690/12060243/414ec5a4-afa6-11e5-8fd1-db8b6337a164.png)

It seems the pod version still 1.9.3 ?

**Comment by appleguy** [comment]
@singno give it a try! https://github.com/facebook/AsyncDisplayKit/releases/tag/1.9.4

**Comment by singno** [comment]
Excellent! I have try the new version, from now on it have not happen again.  Thx for creating such a amazing framework!
