### ISSUE TITLE
[ASRangeControllerBeta] Must handle large scroll deltas where one runloop map contain totally disjoint set of indexPaths.

### ISSUE THREAD

**Issue by knopp** [facebook/AsyncDisplayKit#1034]
@appleguy, it seems that the way `ASRangeControllerBeta` works is that it takes union of FetchData, Display and Visible index paths and updates each node in the set. However when scrollToItemAtIndexPath is used, nodes that were previously visible might not be part of the set (because they are too far, and not even members of FetchData set) and thus retain old interface state, even though they are no longer visible.

I understand that the idea is that the range controller doesn't keep any unnecessary state, but it doesn't seem to be very reliable when jumping further than range tuning parameters for fetch data.

One possible solution would be to set _scrollDirection = 0 on collectionView when manually jumping to an offset (or using scrollToIndexPath, etc) and then refresh nodes at all existing indexPaths in `_updateVisibleNodeIndexPaths`.

**Comment by appleguy** [comment]
@knopp thanks for understanding this case.  With your explanation, I think you're right - and it is clearly something I neglected to consider.  Fortunately, i think the solution can be implemented in a way that is extremely efficient - scanning over the total set of nodes can be done by accessing the interfaceState ivar directly without even a method call, and in the majority of normal situations any action will be skipped as it will have passed through the other ranges.

This is very important to fix.  Do you have any suggestions for how to easily create a test case, say by modifying a sample app like VerticalWithinHorizontalScrolling or any other one?  I should be able to fix this tomorrow.

**Comment by knopp** [comment]
@appleguy, thanks, it does seem to report state correctly after the commit.

However now that you store indexPaths between `_updateVisibleNodeIndexPaths` invocations, it suffers from https://github.com/facebook/AsyncDisplayKit/issues/1028 as well. That happens because when adding inserting nodes / index paths the indexPaths in `_allPreviousIndexPaths` suddenly point to different or non existing nodes. In fact it can be reproduced by same test project https://github.com/facebook/AsyncDisplayKit/issues/1028 can (https://github.com/tomizimobile/ASDKSearchIssue).

The way I see it, there are two ways to fix it.

1) Update `allPreviousIndexPaths` when adding/removing nodes. This is how I fixed https://github.com/facebook/AsyncDisplayKit/issues/1028 in my fork. 
-or-
2) When `_rangeIsValid` is set to `NO`, forget `allPreviousIndexPaths` and fetch all possible index paths and iterate on them

The second one would be easier to implement, but there is currently no way for range controller to fetch  all index paths. I didn't want to modify interfaces so I went with 1) instead here https://github.com/knopp/AsyncDisplayKit/commit/f76fd58840c5706245ba4cc229892fcf8d554303

**Comment by knopp** [comment]
@appleguy, this will crash when you try inserting / removing nodes. You store indexPaths in `allPreviousIndexPaths` but they become obsolete when items are inserted/removed. https://github.com/knopp/AsyncDisplayKit/commit/f76fd58840c5706245ba4cc229892fcf8d554303 fixes this, but it's not the only option.

**Comment by knopp** [comment]
This probject can be used to reproduce the crash https://github.com/tomizimobile/ASDKSearchIssue
