### ISSUE TITLE
Custom Cells/UI using xib

### ISSUE THREAD

**Issue by ankitthakur** [facebook/AsyncDisplayKit#1041]
How we can bind dynamic custom tableview/collectionview cells or any customized UI, with nodes.

**Comment by appleguy** [comment]
@ankitthakur Hi there - unfortunately Interface Builder doesn't support any form of customization, so all the modern UI frameworks (incl. ComponentKit, React Native, and ASDK) cannot use it.  This is mentioned briefly near the end of most of my talks on ASDK.

Please feel free to file an issue or email me (asyncdisplaykit@gmail.com) if you have any questions about implementing UI programmatically.  Remember, big developers like Facebook, Instagram, and Pinterest actually ban using Interface Builder - it's a strong reason not to use it!
