### ISSUE TITLE
[Documentation] Interactive game for learning layout spec system

### ISSUE THREAD

**Issue by nguyenhuy** [facebook/AsyncDisplayKit#1043]
So last week I came across this CSS Flexbox game (http://flexboxfroggy.com/) and really liked the idea. I have some free time tonight and decided to port it to ASDK's layout system. After some hours of banging the keyboard (and trying to learn JS), I think the port is in a good shape. Please try it out here: http://nguyenhuy.github.io/froggy-asdk-layout/ and let me know what you think!

I know that @lappp9 is working on new documentation for the layout system, which is tremendously helpful and greatly appreciated. Hopefully this little game provides some value to the community and helps new developers to learn ASStackLayoutSpec faster!

I'm still not sure about whether I should make a PR to merge the whole game to ASDK's gh-pages branch, or to add a link somewhere in the documentation. Let me know your thoughts :)

![flexbox_froggy](https://cloud.githubusercontent.com/assets/587874/12157810/2f54bb1a-b4dd-11e5-9467-ad1e68b58a5a.png)

**Comment by lappp9** [comment]
Dude this is really cool! @nguyenhuy I know we were talking about having a resources page so maybe that would be a good place to have a link to this?

**Comment by nguyenhuy** [comment]
Yeah, a resource page sounds good. I'm having some more lessons/exercises in mind. Not sure when I will be able to implement them though. But let me assure that if the game attracts traffic, I will allocate my time to maintain it :)

**Comment by yxztj** [comment]
Really love the page! This should definitely ease the learning curve of layout specs. Maybe add swift as well?

**Comment by nguyenhuy** [comment]
Really glad to know :) Adding Swift shouldn't be difficult, but it will take me sometime to get to. Any help would be greatly appreciated.

**Comment by appleguy** [comment]
@nguyenhuy: Such a cool idea! I'm going to close this issue now that we have it linked to in the reference section on the website. I'll file a task in Ship to add Swift to it. 

cc @lappp9 @RuiAAPeres in case this would be useful to link to in your tutorial series.
