### ISSUE TITLE
[Question]where is USE_WORKING_WINDOW defined ?

### ISSUE THREAD

**Issue by cooljeffrey** [facebook/AsyncDisplayKit#1045]
I used to find the USE_WORKING_WINDOW define in previous releases, so that i can set it to NO to disable working window rendering, which would cause conflict with another third party component i am using ( its view cannot be presented when using working window). Once I upgraded to v1.9.4 using cocoapods, I suddenly cannot found the define. Is there something changed ? Thanks for the great work!

**Comment by cooljeffrey** [comment]
Or, anyone know about how to disable working window rendering with latest version ( 1.9.4 ) ?

**Comment by appleguy** [comment]
@cooljeffrey yes!  Import ASDisplayNode+Beta.h, and set [ASDisplayNode setShouldUseNewRenderRange:YES] in your earliest app initialization call.

**Comment by appleguy** [comment]
The new ASRangeControllerBeta implementation is working quite well, and we're using it for all internal development at Pinterest.  HOWEVER, please use the master branch - not 1.9.4 - as there are a couple known issues with this Beta feature in 1.9.4.  I am going to do another release (probably called 1.9.4.1) in the next 24hrs hopefully, and that would allow you to use a stable version number.

**Comment by cooljeffrey** [comment]
@appleguy Got it and thank you!
