### ISSUE TITLE
It crashes when a ASTableView deletes some cell in a section in the version 1.9.4

### ISSUE THREAD

**Issue by tuyuan2012** [facebook/AsyncDisplayKit#1047]
I use the pod version which is 1.9.4. It crashes when a ASTableView deletes some cell in a section. The url of a test case is https://github.com/tuyuan2012/TestDeleteRow.git. In the older version there is not such problem. 
Well, our app will be uploaded to apple store recently. So I am a little worrying. Then, how can pop the older version. Thank you @appleguy very much....
The follow image shows the crash log of mine project not the test case. 
![08642c85-d52a-42a8-9c5d-fd3028a2caf9](https://cloud.githubusercontent.com/assets/3121889/12193562/782eda30-b624-11e5-95dd-6509d51b1be5.png)

**Comment by knopp** [comment]
@tuyuan2012, have you tried these two patches? https://github.com/knopp/AsyncDisplayKit/commit/3c162ec03dcef00fe5170f49b4202caf9f66ffd2 https://github.com/knopp/AsyncDisplayKit/commit/c0c98c0cefaa99fa2f56892818567f0e7eb283c8

**Comment by tuyuan2012** [comment]
Can I pod the new code of knopp@c0c98c0 @knopp ? Thank you....

**Comment by tuyuan2012** [comment]
Thank you @knopp...With the knopp@3c162ec,  there is not such problem. How can I  to pod the new code of the ASRangeController.

**Comment by tuyuan2012** [comment]
Thank you @knopp...With the knopp@3c162ec, there is not such problem. How can I pod the new code of the ASRangeController.

**Comment by tuyuan2012** [comment]
@appleguy @knopp Thank you very much. I pod the sources with the latest commit, there is no such problem.

**Comment by knopp** [comment]
Don't close this issue. This is only fixed in my fork.

**Comment by tuyuan2012** [comment]
I am so sorry @knopp, I have reopened it.

**Comment by vitalybaev** [comment]
The same issue #1055

**Comment by appleguy** [comment]
@tuyuan2012 sorry, I really failed you guys here.  I've been so intensely absorbed in the Pinterest rewrite...the positive news for all of you is that we now have several great engineers at the company working on major continued improvements to ASDK, on top of what is being done by the community.  AND, http://raywenderlich.com is doing a full 2.0 tutorial, including for ASLayoutSpec!

Of course, none of that excuses bad bugs like this.  I am moving up the priority of a proper test harness for this component and will avoid any further changes to the Stable version until that is in place.  @tuyuan2012, your test app will be a start and is something I can integrate into my workflow for now.

I am going to release 1.9.4.1 tonight, but please build against master and test your apps to confirm you are not seeing this or any other issues, as a fix has landed.  Email me directly at asyncdisplaykit@gmail.com whenever you run into something this severe - although in ordinary circumstances, I'm checking Issues here more frequently than I have been in the last few days :(.

**Comment by tuyuan2012** [comment]
It does is a positive news! @appleguy thank you...I will try it tonight.
