### ISSUE TITLE
[AsyncDisplayKit.org] Optimize resources for website for improved SEO ranking.

### ISSUE THREAD

**Issue by ashishyadav311** [facebook/AsyncDisplayKit#1056]
because of this the page score has drastically decreased.
http://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly9zdGF0aWMueHguZmJjZG4ubmV0L3JzcmMucGhwL3YyL3lWL3IvamNoWnZHdU5TcTQuanM=

**Comment by appleguy** [comment]
@ashishyadav311 very interesting suggestion, I really appreciate it!  The link you provided is showing compressed, but are you saying a js file for AsyncDisplayKit.org is not compressed?

**Comment by ashishyadav311** [comment]
Is it showing,
Uncompressed Page Size: 317.1 KB
Compressed Page Size: 86.1 KB
Savings: 72.8%

**Comment by ashishyadav311** [comment]
you can open this link(https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.proptiger.com%2Fguide%2Fpost%2Fwhats-hot-4-tips-to-give-your-kitchen-that-awesome-look&tab=desktop)
how badly has this affected my page score.

**Comment by appleguy** [comment]
This is what I'm seeing.  It seems to say that it is compressed - I think the numbers it is providing are indicating how much value the compression is providing (huge indeed!)

Do you think the .js is uncompressed, even though this is saying it is?

<img width="600" alt="screen shot 2016-01-13 at 6 57 59 pm" src="https://cloud.githubusercontent.com/assets/565251/12314631/a096e114-ba27-11e5-837d-eace7e3caf24.png">

**Comment by ashishyadav311** [comment]
![screen shot 2016-01-14 at 9 55 54 am](https://cloud.githubusercontent.com/assets/7725704/12315806/25e507d8-baa5-11e5-923b-b7a3d2e0d4fe.png)


see on this page it is saying "Compressing https://static.xx.fbcdn.net/rsrc.php/v2/yL/r/WOcTjufR6MD.css could save 114.1KiB (88% reduction)"

can you explain this .

**Comment by ashishyadav311** [comment]
to open this link (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.proptiger.com%2Fguide%2Fpost%2Fwhats-hot-4-tips-to-give-your-kitchen-that-awesome-look&tab=desktop)

**Comment by appleguy** [comment]
@ashishyadav311 Thanks!  That's much more actionable.  The Google tool is showing that we could get some gains from optimizing the images, which makes sense, so we'll definitely do that.

I'm not seeing the same results as you posted above though.  What URL did you run it on?  I ran it on asyncdisplaykit.org.  Are you testing some other page, like one of the guides?

If you could just write a few more words in your comments about what you're thinking here, it would be much more clear.  I apologize for the back-and-forth, but you've been pointing to a couple separate tools and not really sharing the URLs being used or how you might suggest we improve.  Though I'm an expert in native app programming, I am not an expert in web optimization — I definitely have a lot of respect for the art of page speedup and am certainly glad you raised this to our attention, so thank you again for helping us understand fully.

@lappp9 could you check in the new, optimized images?  We could use pngcrush --brute, or Google appears to let you download optimized images directly from their tool, which is pretty great.

https://developers.google.com/speed/pagespeed/insights/?url=asyncdisplaykit.org

<img width="1119" alt="screen shot 2016-01-18 at 8 28 41 pm" src="https://cloud.githubusercontent.com/assets/565251/12409772/1873fed0-be22-11e5-8186-ba74394a7f7e.png">
<img width="1119" alt="screen shot 2016-01-18 at 8 28 41 pm" src="https://cloud.githubusercontent.com/assets/565251/12409773/1e2e26f2-be22-11e5-908d-37cc565ced98.png">

**Comment by ashishyadav311** [comment]
Thanks for you cooperation, I have asynchronously loaded my script file and issue seemed to disappeared or you might have optimized at your end.
the url i was trying to optimized through the code was 
(http://www.makaaniq.com/buy-sell-move-property/your-step-by-step-guide-to-buying-a-home)
thanks a lot.

**Comment by appleguy** [comment]
Thanks @ashishyadav311 !  Glad you were looking at this for us!
