### ISSUE TITLE
Any idea about vertical flexibleSpace ?

### ISSUE THREAD

**Issue by CodeEagle** [facebook/AsyncDisplayKit#1070]
Is there a way to create a layout spec like `UIBarButtonSystemItem.FlexibleSpace` that working on vertical?

**Comment by nguyenhuy** [comment]
There are `ASStackLayoutJustifyContentSpaceBetween` and `ASStackLayoutJustifyContentSpaceAround`. You can apply either of them on a vertical stack. Let us know if it is not what you want.

**Comment by CodeEagle** [comment]
@nguyenhuy Thanks, that's what I need

**Comment by nguyenhuy** [comment]
Great! Let's close this ticket then. Please feel free to open new ones if you need help or have feedbacks.
