### ISSUE TITLE
How to have label on opposite ends using layout spec

### ISSUE THREAD

**Issue by AtifKhan786** [facebook/AsyncDisplayKit#1073]
I want to have two labels, one on left most side and other on right most side.

Some thing like this, how can i achieve this
![screen shot 2016-01-18 at 3 43 28 pm](https://cloud.githubusercontent.com/assets/16757884/12390576/be04715e-bdfa-11e5-8437-6dcc31c9b5ff.png)

**Comment by nguyenhuy** [comment]
Try setting justifyContent property of your horizontal stack to ASStackLayoutJustifyContentSpaceBetween. Also make sure you horizontal stack is asked to fill the entire witdth. More detailed answer can be found [here](https://github.com/facebook/AsyncDisplayKit/issues/1071#issuecomment-172355989)

**Comment by appleguy** [comment]
@AtifKhan786 Thanks for asking, and thanks @nguyenhuy for coming in with the answer!  Please reopen or file a new issue if you have any trouble.
