### ISSUE TITLE
[Documentation] Questions on ASLayoutSpec -- I am a new to use this powerful framework!

### ISSUE THREAD

**Issue by Jsonmess** [facebook/AsyncDisplayKit#1075]
i am learning AsyncDisplayKit ，it work really well in my old project，but when use to layout new feature，i really confuse about ASLayout ，How it work ？i used to use autoLayout before。

is there some thought from docs  about ASLayout？？？thanks

**Comment by appleguy** [comment]
@RCacheaux do you have any really early material you might be able to share here?  @lappp9?

**Comment by appleguy** [comment]
@Jsonmess Full documentation is coming soon, but not yet available.  A quick overview is available here - it is worth watching the whole talk if you are going to get into ASDK :).

Please keep the questions coming!

https://www.youtube.com/watch?v=RY_X7l1g79Q

**Comment by hannahmbanana** [comment]
@Jsonmess Are you trying to achieve something in particular or just curious about the new ASLayout component? If you could provide a sketch of what you are trying to achieve, I could help you out until we better documentation is available.

**Comment by appleguy** [comment]
@Jsonmess: We finally have documentation on ASLayoutSpec on our website! http://asyncdisplaykit.org/docs/automatic-layout-basics.html

FYI: ASLayoutSpec is **NOT** the same as UIKit's autoLayout.
