### ISSUE TITLE
Text with headIndents is not rendered correctly

### ISSUE THREAD

**Issue by nvh** [facebook/AsyncDisplayKit#1076]
When specifying a `headIndent` and a `firstLineHeadIndent`, text is rendered incorrectly:

![simulator screen shot 19 jan 2016 10 56 34](https://cloud.githubusercontent.com/assets/248861/12417494/c15556f8-bea8-11e5-9608-c9285850e17f.png)

Initially the text is clipped on the right side of the node, but when rerendering after scrolling (the bottom half of the screenshot) the text is rendered inside the box on the left and right, but falls of the bottom.

A test project where this behaviour is displayed can be found [here](https://github.com/nvh/ASTextNodeTest)

**Comment by aaronschubert0** [comment]
Hi @nvh thanks for reporting this issue and providing an example project! Makes it a lot easier to debug.  The problem property is actually just `headIndent`, `firstLineHeadIndent` seems to be rendering properly. I'll put up a PR shortly that address this specific problem but a deeper inspection/fix may be needed.

**Comment by appleguy** [comment]
I believe this is fixed in master - @nvh, could you confirm that in your original use case it is handled?  I'm keeping this open because I want to better understand the issue and ensure this is covered in the expanded test cases we're starting to develop for the text stack.

**Comment by aaronschubert0** [comment]
Hey @appleguy, talking about expanded test cases, could you link me to some WIP (if there is any) I was planning to write some for nsattribrutedstring & ASTextNode soon. Just so we have complete coverage going forward and can better understand any issues (and prevent those!)

**Comment by appleguy** [comment]
This test project was essential to my detailed understanding of this code.  I'm very thankful for the excellent reports you have created over time, @nvh.  You have made a material difference in the project as a whole - really!

**Comment by nvh** [comment]
Thank you for looking into this @appleguy, I'm happy to help!
