### ISSUE TITLE
[Example Apps] Example app using UICollectionViewLayouts with header supplementary nodes

### ISSUE THREAD

**Issue by AttilaTheFun** [facebook/AsyncDisplayKit#1081]
I have been trying to get a pinterest-like layout working with ASCollectionView. I have been able to get it working without headers with each of these layouts:
https://github.com/ecerney/CollectionViewWaterfallLayout
https://github.com/openboy2012/DDCollectionViewFlowLayout
https://github.com/chiahsien/CHTCollectionViewWaterfallLayout

But the second I try to add headers to any of them I can never get them working. Has anyone had success with custom layouts and headers? I'm about ready to throw in the towel and make my own collection view and just add the nodes as subviews.

**Comment by lappp9** [comment]
Have you checked out this example project yet?  

https://github.com/facebook/AsyncDisplayKit/tree/master/examples/CustomCollectionView

It has a pinterest-like layout and headers, so maybe it would be helpful to look at?

**Comment by AttilaTheFun** [comment]
Thanks for the heads-up! Ill definitely give it a look tomorrow.

**Comment by appleguy** [comment]
@AttilaTheFun Do post any other questions!  @levi just started his first day at Pinterest working with me,and incidentally was the person who implemented / added support for supplementary nodes like headers in collections :)

**Comment by levi** [comment]
@AttilaTheFun it's definitely a little crazy to get supplementary nodes setup in a custom collection view layout, but definitely achievable if you want to invest a little bit of thought into it. This seems to be a question that comes up a lot, so I would like to ask if you had any questions that you feel like would answer gaps in your understanding of the supplementary node implementation. I would be able to answer them in a long form response that could be used as a starting point for documenting why things are structured like they are.

**Comment by kiennguyen07** [comment]
Hi I need you guy to help. I'm trying to implement CustomCollectionView sample in Swift. https://dl.dropboxusercontent.com/u/6255973/Test.zip this is the source (edited)

But I always got error: MosaicCollectionViewLayoutInspector didChangeCollectionViewDelegate:]: unrecognized selector sent to instance

**Comment by maicki** [comment]
@kiennguyen07 I fixed your example (http://cl.ly/1k1N0E1S143m):
- In `ViewController.swift` your `layoutInspector` needs to be a property
- In `MosaicCollectionViewLayoutInspector.m` we had to add `didChangeCollectionViewDelegate:` method that is called within `ASCollectionView` without checking if it's actually implemented from the delegate. This will change with a PR that I will open pretty soon

The next time please open a new issue for something like that.
