### ISSUE TITLE
[GitHub] Add CocoaPods download badges.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#1086]
ASDK has over 115,000 downloads and is used in almost 1,700 apps, including 515 unique apps that are actively developing with it enough to have used pod install with it this week.  Pretty awesome!

http://cocoapods.org/pods/AsyncDisplayKit

Let's add a badge to showcase this.  This is an old task and may not explain how to add the badges correctly, but we should check it out.  @aaronschubert0 have you ever looked at this?

https://github.com/CocoaPods/CocoaPods/issues/1092

**Comment by aaronschubert0** [comment]
@appleguy  Never done it before but seemed really straightforward!
