### ISSUE TITLE
IMPORTANT : IBDesignablesAgentCocoaTouch Error

### ISSUE THREAD

**Issue by xeonarno** [facebook/AsyncDisplayKit#1103]
Hi,

An important error appear with Async. I have added Async with Cocoapod.
Then I created a view with a Xib. When I get the preview to debug the IB design, I got an error. "the agent crashed" ! Impossible to debug the error, nothing in the view was bad. Until I found the crashlog file from Xcode. the _UILabelContentLayer asyncdisplaykit_node] is the problem.

But the problem is I didn't use any Async node in my project, just the projet compiled by pod.

Please find the crash log : 

Process:               IBDesignablesAgentCocoaTouch [26333]
Path:                  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Overlays/IBDesignablesAgentCocoaTouch
Identifier:            IBDesignablesAgentCocoaTouch
Version:               7.2 (9529)
Code Type:             X86-64 (Native)
Parent Process:        Xcode [24066]
Responsible:           IBDesignablesAgentCocoaTouch [26333]
User ID:               501

Date/Time:             2016-01-24 19:33:38.927 +0100
OS Version:            Mac OS X 10.11.1 (15B42)
Report Version:        11

Time Awake Since Boot: 160000 seconds
Time Since Wake:       13000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_UILabelContentLayer asyncdisplaykit_node]: unrecognized selector sent to instance 0x7fd3ba5a4fd0'
terminating with uncaught exception of type NSException
abort() called
CoreSimulator 201.3 - Device: IBSimDeviceTypeiPad1x - Runtime: iOS 9.2 (13C75) - DeviceType: IBSimDeviceTypeiPad1x

Application Specific Backtrace 1:
0   CoreFoundation                      0x0000000112bbbe65 __exceptionPreprocess + 165
1   libobjc.A.dylib                     0x0000000112634deb objc_exception_throw + 48
2   CoreFoundation                      0x0000000112bc448d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3   CoreFoundation                      0x0000000112b1190a ___forwarding___ + 970
4   CoreFoundation                      0x0000000112b114b8 _CF_forwarding_prep_0 + 120
5   CompositeVideo                      0x000000021e3a6d38 -[CALayer(AsyncDisplayKit) name] + 40
6   QuartzCore                          0x00000001120a3d59 -[CALayer(CALayerPrivate) _copyRenderLayer:layerFlags:commitFlags:] + 3019
7   QuartzCore                          0x0000000112089b1f _ZN2CA7Context12commit_layerEPNS_5LayerEjjPv + 103
8   QuartzCore                          0x000000011209630e _ZN2CA5Layer16commit_if_neededEPNS_11TransactionEPFvPS0_jjPvES4_ + 330
9   QuartzCore                          0x000000011209628e _ZN2CA5Layer16commit_if_neededEPNS_11TransactionEPFvPS0_jjPvES4_ + 202
10  QuartzCore                          0x00000001120d43ca x_hash_table_foreach + 65
11  QuartzCore                          0x00000001120b8927 _ZN2CA11Transaction12foreach_rootEPFvPNS_5LayerEPvES3_ + 41
12  QuartzCore                          0x000000011208a9e6 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 1670
13  QuartzCore                          0x00000001120b7c0a _ZN2CA11Transaction6commitEv + 486
14  QuartzCore                          0x00000001120b837c _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
15  CoreFoundation                      0x0000000112ae7367 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
16  CoreFoundation                      0x0000000112ae72d7 __CFRunLoopDoObservers + 391
17  CoreFoundation                      0x0000000112adc84c CFRunLoopRunSpecific + 524
18  Foundation                          0x00000001122212f1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267
19  IBFoundation                        0x0000000111e8b967 -[IBAbstractPlatformTool startServingReceiveChannel:] + 415
20  IBFoundation                        0x0000000111e8bb43 -[IBAbstractPlatformTool startServingWriteDescriptor:readDescriptor:] + 117
21  IBFoundation                        0x0000000111e8c64d +[IBAbstractPlatformTool main] + 1191
22  IBDesignablesAgentCocoaTouch        0x000000010fe6bbd7 main + 34
23  libdyld.dylib                       0x00000001168d292d start + 1

Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x0000000116c120ae __pthread_kill + 10
1   libsystem_c.dylib             	0x0000000116978cec abort + 129
2   libc++abi.dylib               	0x0000000116513051 abort_message + 257
3   libc++abi.dylib               	0x0000000116538ac9 default_terminate_handler() + 267
4   libobjc.A.dylib               	0x0000000112635046 _objc_terminate() + 103
5   libc++abi.dylib               	0x000000011653626e std::__terminate(void (*)()) + 8
6   libc++abi.dylib               	0x0000000116535ef9 __cxa_rethrow + 99
7   libobjc.A.dylib               	0x0000000112634f5e objc_exception_rethrow + 40
8   com.apple.CoreFoundation      	0x0000000112adc8e4 CFRunLoopRunSpecific + 676
9   com.apple.Foundation          	0x00000001122212f1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267
10  com.apple.dt.IBFoundation     	0x0000000111e8b967 -[IBAbstractPlatformTool startServingReceiveChannel:] + 415
11  com.apple.dt.IBFoundation     	0x0000000111e8bb43 -[IBAbstractPlatformTool startServingWriteDescriptor:readDescriptor:] + 117
12  com.apple.dt.IBFoundation     	0x0000000111e8c64d +[IBAbstractPlatformTool main] + 1191
13  IBDesignablesAgentCocoaTouch  	0x000000010fe6bbd7 main + 34
14  libdyld.dylib                 	0x00000001168d292d start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x0000000116c1308a kevent64 + 10
1   libdispatch.dylib             	0x000000011689365a _dispatch_mgr_thread + 54

Thread 2:
0   libsystem_kernel.dylib        	0x0000000116c1350a read + 10
1   com.apple.Foundation          	0x0000000112228ea9 -[NSConcreteFileHandle readDataOfLength:] + 481
2   com.apple.dt.IBFoundation     	0x0000000111e8b9bc __53-[IBAbstractPlatformTool startServingReceiveChannel:]_block_invoke + 31
3   libdispatch.dylib             	0x0000000116887d59 _dispatch_call_block_and_release + 12
4   libdispatch.dylib             	0x00000001168a34a7 _dispatch_client_callout + 8
5   libdispatch.dylib             	0x000000011688e4fd _dispatch_root_queue_drain + 890
6   libdispatch.dylib             	0x000000011688e17c _dispatch_worker_thread3 + 98
7   libsystem_pthread.dylib       	0x0000000116bd64f2 _pthread_wqthread + 1129
8   libsystem_pthread.dylib       	0x0000000116bd4375 start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x0000000116c0ccd2 semaphore_wait_trap + 10
1   libdispatch.dylib             	0x0000000116890b40 _dispatch_thread_semaphore_wait + 16
2   libdispatch.dylib             	0x000000011688bbc7 _dispatch_barrier_sync_f_slow + 570
3   com.apple.dt.IBFoundation     	0x0000000111eae2d0 -[IBMessageReceiveChannel runBlockingReceiveLoopNotifyingQueue:notifyingTarget:context:] + 1266
4   com.apple.dt.IBFoundation     	0x0000000111e8b5b2 -[IBAbstractPlatformTool runMessageChannel:] + 129
5   com.apple.Foundation          	0x00000001122bedfb __NSThread__start__ + 1198
6   libsystem_pthread.dylib       	0x0000000116bd69b1 _pthread_body + 131
7   libsystem_pthread.dylib       	0x0000000116bd692e _pthread_start + 168
8   libsystem_pthread.dylib       	0x0000000116bd4385 thread_start + 13

Thread 4:
0   libsystem_kernel.dylib        	0x0000000116c1278a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x0000000116bd4375 start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x0000000116c1278a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x0000000116bd4375 start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff4fd94258  rdx: 0x0000000000000000
  rdi: 0x0000000000000303  rsi: 0x0000000000000006  rbp: 0x00007fff4fd94280  rsp: 0x00007fff4fd94258
   r8: 0x0000000000000003   r9: 0x0000000116539aba  r10: 0x0000000008000000  r11: 0x0000000000000202
  r12: 0x00007fff4fd943e0  r13: 0x00007fd3ba50efb0  r14: 0x0000000116bdf000  r15: 0x00007fff4fd942c0
  rip: 0x0000000116c120ae  rfl: 0x0000000000000202  cr2: 0x0000000116bd9a5d
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Please find the pod file : 

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

pod "AFNetworking","~> 2.0"
pod "MagicalRecord/Shorthand","~> 2.2"
pod "Reachability","~> 3.1.1"
pod "CocoaLumberjack"
pod "MBProgressHUD","~> 0.8"
pod "KVOController"
pod "pop","~> 1.0"
pod "AGGeometryKit+POP","~> 0.1"
pod "Masonry"
pod "BBlock"
pod "PureLayout"
#pod "AsyncDisplayKit" #make Agent IB crashed....
pod "AWSiOSSDKv2"
pod "AWSCognito"
pod "XLForm"
pod "ISHPermissionKit"
pod "APOfflineReverseGeocoding"
pod "AGLocationDispatcher"
pod "VCTransitionsLibrary"
pod "LLSimpleCamera"
pod "CrittercismSDK"
pod "PubNub"

**Comment by appleguy** [comment]
@xeonarno AsyncDisplayKit doesn't support any aspect of InterfaceBuilder...it's banned from usage at Facebook, Instagram, Pinterest, and is not used by any of the more complex apps at Apple either.  IB does not offer APIs that would allow us to integrate ASDK, so it's not only that we don't really like it / find it too slow...it is just technically impossible to extend it in creative ways.

Let us know if you have any questions about the programmatic solutions!  Happy to help!  Sorry for the bad news :(

**Comment by xeonarno** [comment]
Thank's ! very clear know... but what GUI do you use to help you create an "nice" interface ?

For the records : it takes me 3 weeks to find that error ^^ !
