### ISSUE TITLE
[ASTableView] neverShowPlaceholders have no effect

### ISSUE THREAD

**Issue by zintus** [facebook/AsyncDisplayKit#1118]
Hi! Thanks for awesome framework again :)

Combination of scrolling and batch updates on table results in cells blinking. I've ran out of all hypothesis and i can't reproduce this on UITableView. Could you take a look on sample project?

[table.zip](https://github.com/facebook/AsyncDisplayKit/files/105341/table.zip)

**Comment by 1nput0utput** [comment]
@zintus weird enough, slowing down setContentOffset makes the ASTableView behave as it should.
```
 if (completed) {
  dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC));
  dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
    [self.table slk_scrollToBottomAnimated:YES];
  });
 }
```

**Comment by 1nput0utput** [comment]
@zintus could try setting ```table.automaticallyAdjustsContentOffset = YES;``` this should keep your tableView in place -- You'd not have to use slk_scrollToBottomAnimated:.

**Comment by zintus** [comment]
@1nput0utput huge thanks for pointing me in right direction!
Setting contentOffset before calling endUpdates on tableView helps indeed (that's what `automaticallyAdjustsContentOffset` doing behind the scenes)

**Comment by 1nput0utput** [comment]
@zintus I am glad it helped!

**Comment by appleguy** [comment]
@zintus thank you for filing the issue, and I'm really glad that the community could help!  Thanks @1nput0utput for beating me to the reply by several days :)

@zintus, are there any remaining issues you would like me to investigate? I want to make sure this option is working well for you if you are confident it is the right behavior for your application. I am going to close this task for now, but feel free to reopen it or file a new one if there are any other questions!

I am also a bit faster with email and love to hear from folks at asyncdisplaykit@gmail.com

**Comment by zintus** [comment]
@appleguy ASTableView display cells with blinking, while UITableView doing this ok. For ASTableView:
* no blinking: cells that were fully visible (wrt to contentSize and contentOffset, etc) before UIKit endUpdates: called;
* enabling content offset adjustments changes visible window before calling endUpdates: thus removing almost all blinking;
* cells moving out of visible window because of 'scroll down' animation, disappear right at animation start.

Sample project show only blinking problem, let's simplify to this problem first.
