### ISSUE TITLE
[ASTableView] Make ASTableViews and ASCollectionViews transform aware when tail fetching

### ISSUE THREAD

**Issue by samhsiung** [facebook/AsyncDisplayKit#1126]
Currently ASTableView only supports batch fetching when `scrollDirection =  ASScrollDirectionUp` due to only handling tail fetching. However when the scroll view is vertically inverted via transform we actually want to watch for `ASScrollDirectionDown` instead of `ASScrollDirectionUp` for tail fetching.

This will add support for libraries such as SLKTextViewController which invert the scroll view so that messages appear in ascending order based on time.

**Comment by samhsiung** [comment]
https://github.com/facebook/AsyncDisplayKit/pull/1143

**Comment by appleguy** [comment]
@samhsiung thanks for finding this, and the fix!
