### ISSUE TITLE
[ASVideoNode] Delegate for tapping on node

### ISSUE THREAD

**Issue by MarvinNazari** [facebook/AsyncDisplayKit#1149]
Hi, Right now when u tap on a video node it pauses the video, alternatively i want to be able to mute/unmute the video instead (like Instagram), we could have a delegate function that it calls when u tap so we could override this functionality.

**Comment by lappp9** [comment]
Hey @MarvinNazari, I've got a PR submitted to add this functionality so it should be available soon!

**Comment by MarvinNazari** [comment]
wow awesome! thanks @lappp9

**Comment by appleguy** [comment]
@MarvinNazari I merged Luke's diff, check it out and please do keep filing any issues you find with ASVideoNode!  Remember this is a Beta component and not even included in AsyncDisplayKit.h, so test carefully before using this component in a production app - you would be the first so far :)
