### ISSUE TITLE
[ASVideoNode] Size of video thumbnail don't respect gravity param

### ISSUE THREAD

**Issue by logicsb** [facebook/AsyncDisplayKit#1150]
Hi, I have the following problem: when the video shows thumbnail ASVideoNode ignores the gravity parameters. But when the video is tapped to play it is resizing accordantly the gravity parameters.

**Comment by lappp9** [comment]
@logicsb, yeah I noticed this and there's a PR open to fix it!  Should be fixed in the next release.

**Comment by logicsb** [comment]
Wow. Sorry. Thanks guy. :)

**Comment by appleguy** [comment]
@logicsb I merged Luke's diff, check it out and please do keep filing any issues you find with ASVideoNode!  Remember this is a Beta component and not even included in AsyncDisplayKit.h, so test carefully before using this component in a production app - you would be the first so far :)
