### ISSUE TITLE
Build Error When Used with CocoaPods 0.39.0 and use_frameworks! Option

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1153]
I recently tried to switch a Swift app over to using `279a04` (current tip of `master`) from `1.9.5` and I get a build error in `ASEqualityHashHelpers.h` at `#import <string>`: `'string' file not found`. Maybe theres some other alias to the same file we can use that it will recognize?

**Comment by MarvinNazari** [comment]
I'm having the same issue, any workaround?

**Comment by Adlai-Holler** [comment]
@MarvinNazari See if #1158 gets you back online.

**Comment by appleguy** [comment]
@MarvinNazari thx for chiming in.  Commented on the PR...

**Comment by Adlai-Holler** [comment]
This is resolved in #1160
