### ISSUE TITLE
[ASCollectionView] Interactively changing size of items

### ISSUE THREAD

**Issue by GitGadd** [facebook/AsyncDisplayKit#1164]
I'm attempting to implement interactive resizing of items using a custom collection view layout. Dragging the edge of an item in the collection view causes the collection view layout to apply a modification to the size when computing the layout attributes for that index path, and also triggers an invalidation of that specific index path.

This works great using UICollectionView, but I'm not sure how I would approach this using ASCollectionView since the sizes seem to be computed only when reloading data. Reloading the index path every frame seems too heavy to be done every frame.

Is there a way to have items in a collection view respect the layout attributes, including size?

Please let me know if this is the wrong forum for this kind of general question.

Best,
Fredrik

**Comment by appleguy** [comment]
@GitGadd this is a perfect form for this type of question. Sorry it took a week to get back to you, but I'm glad you asked.

In my opinion, in validating the collection review layout itself is too expensive to do every frame, although I know it is a relatively common practice. Once you were doing this, it is actually quite cheap in comparison to reload the item at the index Path being manipulated. Have you tried doing this?

Go ahead and also try calling -setNeedsLayout on the ASCellNode at that in next path. I believe this is set up to re-request the constrainedSizeForNodeAtIndexPath: from the data source.  cc @nguyenhuy who can correct me if this is wrong.

Definitely let me know the results you find, and this could make for a great example app or use case to discuss in one of the upcoming framework tutorials that are currently being written!

Also feel free to email me directly at asyncdisplaykit@gmail.com, any time.  I'll typically be able to reply more quickly, although it works best if you post here and give me a heads up in email with any other details you might not be able to share (such as code references from your app).  Sometimes other members of the community are able to reply more quickly.

**Comment by GitGadd** [comment]
Thanks for getting back to me!

I thought the constrained size provided by the data source was only for initial layout/sizing, and that the size/bounds properties of the layout attributes would be applied to the node during layout.

While ASCollectionNode seems great, I decided to roll my own collection management node to simplify these kinds of interactive gestures and animations.

Great to hear there are tutorials being written; I still find sizing and layout to be the hardest parts of ASDK to grasp.

**Comment by sstigler** [comment]
I'm running into this same issue with version 1.9.90. I tried inserting the following code into `applyLayoutAttributes`:

`if layoutAttributes.size != bounds.size {
            setNeedsLayout()
}`

However, that doesn't seem to be making a difference. @appleguy , is that what you meant for where to try applying this?
