### ISSUE TITLE
[ASScrollNode] Add capability to automatically set .contentSize based on .calculatedSize of -layoutSpecThatFits:

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/AsyncDisplayKit#1165]
This may just be a misunderstanding of how I would achieve this in ASDK but I'm having trouble rendering nodes as subnodes of a ASScrollNode. This is what I'm doing:
```
self.backgroundNode = [[ASScrollNode alloc] init];
///
[self addSubnode:self.backgroundNode];

//Layout Spec
```
Now coming from UIKit, I would imagine that I would have to add nodes as subnodes of self.backgroundNode. Like so
```
//titleNode is a ASTextNode
[self.backgroundNode addSubnode: self.titleNode];
```
This works, in the sense that I can validate that the nodes are added as sub nodes, the trouble is that nodes aren't being rendered, it just causes a blank screen. 

My initial suspicion is that the layoutSpec that I've defined for `self` isn't being used when my 'child' nodes are being added to the `ASScrollNode`, is this a possibility? If so how would I go about fixing this?

Has anyone got any ideas?
cc @appleguy  @nguyenhuy

**Comment by levi** [comment]
@aaronschubert0 your insertion logic is fine. It's likely how the scroll view content size is being calculated. Currently, if you're returning a layoutSpec in your scroll view it will size the defined nodes but not the contentSize itself. You can read more about this here if you feel that it aligns with your issue: https://github.com/facebook/AsyncDisplayKit/issues/780

Fixing this is on the roadmap and I'll likely be able to get to it next week. If you have any ideas on API design, I'd greatly appreciate the input.

**Comment by aaronschubert0** [comment]
Hey @levi awesome. Thanks for that. So I will have to subclass ASScrollNode and then return a layoutSpec inside that node. In terms of the contentSize, I will be setting it to the screen width by the MaxY of the furthest down node, would setting this manually in the layout method be appropriate?

In terms of API design, I'll have a think and let you know, definitely room for improvement on such a vital node :)

**Comment by levi** [comment]
Yeah, you'll have to set the contentSize manually at this point. A good place to do this in `layoutDidFinish`

**Comment by appleguy** [comment]
@aaronschubert0 were you able to solve this? We have several similar use cases that have been working fine, so feel free to ask on slack if you have encountered any issues.

Implementing the layout speck that fits method should be enough if you have a mechanism to also set the content size, for example in the layout did finish method is fine. I believe there is another open task to implement that automatically in the base class, which would be a great thing to investigate if you have time, but due to other priorities we don't plan to investigate it soon.

**Comment by aaronschubert0** [comment]
@appleguy Yeah I was thanks! Granted it worked since I was able to manually track where the end node was and set the content size from that, but overall hasn't been an issue.

**Comment by appleguy** [comment]
Duplicate issue, will continue to track in #780.

**Comment by skensell** [comment]
If anyone finds themselves on this thread, here's a copy-paste snippet you can use for an `ASScrollNode` subclass.

    @interface MXSingleSubviewScrollNode : ASScrollNode
    @end
    
    @implementation MXSingleSubviewScrollNode

    - (void)layoutDidFinish {
        [super layoutDidFinish];
        if (self.subnodes.count > 0) {
            self.view.contentSize = [self.subnodes firstObject].calculatedSize;
        }
    }

    - (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {
        ASDisplayNode* firstSubnode = [self.subnodes firstObject];
        firstSubnode.position = CGPointZero;
        firstSubnode.sizeRange = ASRelativeSizeRangeMake(ASRelativeSizeMakeWithCGSize(CGSizeZero), ASRelativeSizeMakeWithCGSize(CGSizeMake(constrainedSize.max.width, CGFLOAT_MAX)));
        return [ASStaticLayoutSpec staticLayoutSpecWithChildren:(firstSubnode ? @[firstSubnode] : @[])];
    }

    @end

**Comment by appleguy** [comment]
@skensell Thank you for sharing your solution!  It's not a bad one indeed.

@aaronschubert0 as well -- I'm really happy to say there's now a framework solution to this - https://github.com/facebook/AsyncDisplayKit/pull/2753 .  It should land quite soon.

Hopeful that you get some time to update to 2.0; if you disable the deprecation warnings, you'll find it's fully source compatible.  You might appreciate best that you don't need to use a static layout spec for sizeRange to take effect; instead, the .style.preferredSize and related height / width properties can all take effect without wrapping in a spec.

Please let me know if you hit any troubles after trying out the new ASScrollNode feature!

Anyway, tracking this here still: https://github.com/facebook/AsyncDisplayKit/issues/780
