### ISSUE TITLE
[ASCollectionNode] -insetForSectionAtIndex: affects ASCellNode constrained sizes.

### ISSUE THREAD

**Issue by rmls** [facebook/AsyncDisplayKit#1167]
When using an `ASCollectionNode` and implementing `-collectionView:layout:insetForSectionAtIndex:` from `ASCollectionViewDelegateFlowLayout` to return a valid `UIEdgeInsets`, instead of applying insets to the section of the collection view only (as UIKit does), it will apply the insets AND change the `constrainedSize` of each one of the cell nodes inside that section.

This is happening when `dataController:constrainedSizeForNodeAtIndexPath` considers the section insets to calculate the constrained size of a cell node (which seems wrong, since section insets shouldn't affect cell node sizes).

This is where the constrainedSize for a node will get modified based on the section inset:
https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASCollectionView.mm#L728

**Comment by appleguy** [comment]
@rmls thank you for filing this task, and for looking into the implementation to figure out where the calculation was going wrong. It sounds like this should be relatively relatively easy fix, as soon as someone in the community has a chance to look into it.

**Comment by Adlai-Holler** [comment]
Closed in #1301
