### ISSUE TITLE
[ASCollectionNode] Incorrect contentSize.height in 1.9.6

### ISSUE THREAD

**Issue by gugges** [facebook/AsyncDisplayKit#1175]
I am noticing that after upgrading from 1.9.5 to 1.9.6, the contentSize of my ASCollectionView is being misreported, despite the feed scrolling fine. The height value is 61pt in 1.9.6 and 10,133pt (correct) in 1.9.5 for the exact same content. I have been switching back and forth and can replicate every time. I've tried to look through the diffs between versions, but cannot immediately see what is causing the change. 

My setup mirrors the VerticalWithinHorizontalScrolling example project. I have an ASCollectionView with 3 ASCellNodes that each fill an entire screen and page horizontally. These ASCellNodes each contain an ASCollectionNode with vertical content and it's their view's vertical contentSize.height that is misreporting.  ***Interestingly, when I page horizontally to the third and final ASCellNode in my app, the vertical contentSize updates to the correct number for all feeds.

I'm happy to help investigate and submit a PR, but can someone please point me in the right direction as to what may be causing this? Thank you so much to all the contributors for making this awesome framework.

Best,
Jordan

**Comment by appleguy** [comment]
@gugges thank you for reporting this. If you can provide any form of reproduction case, including modifying the example app that you referenced, we will be able to get to the bottom of this quite quickly. I am actually really surprised to hear that you have consistently reproduced it between those two framework versions, but thanks for clarifying that you carefully checked this.

For your own use case, I highly recommend that you switch to adopt ASPagerNode at the top level. Although it is basically a collection, it sets default values for the preload ranges which we will be able to keep up-to-date and continually improving the behavior to optimize for this use case. It is conceivable that it will fix your issue as well, although if it does, I would be interested in figuring out why.

Certainly happy to work at any PR you put up, but I'm afraid without the little bit more detail or a reproduction case I don't yet have an idea for what would cause this.

**Comment by gugges** [comment]
@appleguy Thank you for the advice with the ASPagerNode! I just got that implemented.

Also, I figured out what is going on and why I am able to replicate consistently.

I discovered that I am logging the 3rd and final vertical collectionView's contentSize.height.

Despite having the same rangeTuningParameters of 2.0 leading, 1.0 trailing, that 3rd feed in 1.9.5 immediately knew its contentSize.height upon init of the "paging" collectionView. In 1.9.6, the 3rd vertical feed isn't aware of its contentSize until it is on-screen for the first time. 

I would think that with my range tuning parameters it would have known its size sooner than its first on-screen appearance. But let me know if that is the expected behavior. For what it's worth, I am also able to replicate with the ASPagerNode and its default range tuning.

Thanks again,
Jordan

**Comment by hannahmbanana** [comment]
@gugges: Were you able to figure out this issue? 

contentSize is not set until the ASCellNode is in the display range. You could confirm this by checking the cell node's interfaceState and seeing if the display bit is set.

**Comment by gugges** [comment]
@hannahmbanana Feel free to close this. The behavior changed so I wanted to raise the issue, but I am capturing contentSize at a better point in the view's lifecycle so this is no longer an issue. Thanks!

**Comment by appleguy** [comment]
@gugges thanks for reporting this!  As your helpful research concluded, the range tuning parameters would indeed control how soon this happens.  We dialed them back because they also have costs.

Try using displayStateDidChange:YES or better, visibleStateDidChange:YES to catch the right time.
