### ISSUE TITLE
Text Node userInteractionEnabled Behavior May Be Unexpected

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1177]
Being a subclass of `ASControlNode`, text nodes have `userInteractionEnabled = false` set in `didLoad` if they don't have any targets. But since ASTextNode has its own interaction reporting scheme (via its delegate) most users probably won't predict this. I'll put up a PR shortly to override the inherited behavior shortly.

**Comment by appleguy** [comment]
@Adlai-Holler we reverted to patch that recently change this behavior. Please send me a note for re-open this if that is not exactly what you mean, and if the behavior currently in master still has an issue along the lines of what you're referencing
