### ISSUE TITLE
[ASCollectionView] (Version Unknown, Awaiting Info) Crash when performing batch updates.

### ISSUE THREAD

**Issue by bevbomb** [facebook/AsyncDisplayKit#1180]
So i've been trying to perform batch updates of insert, delete and move for ASCollectionView and i'm continuously having it error out with the following error 
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Indexpath is out of range !'`

Any reason why this would be happening?

**Comment by appleguy** [comment]
@bevbomb thanks for reporting the; this is one of the most important types of issues for us to debug and fix. I am not actually aware of any bugs of this nature in the current code, so I am very interested in learning more about the case you have encountered.

Could you let me know what version of the framework you're using, such as with the git SHA?

Could you provide any other details about the issue, such as the full backtrace, or any edit operations you are performing?

Of course, ideally, if you can reproduce some of the situation in one of the example apps or provide another test app that triggers it, that would allow us to debug very quickly.

Definitely ensure that you are using the latest version of the framework (1.9.6), and if it doesn't fact occur there, please also try using master and let me know the results.  Feel free to email me directly at asyncdisplaykit@gmail.com when you've updated here so I can check as soon as possible.

**Comment by appleguy** [comment]
@bevbomb: were you able to resolve the issue? If you are still having the exception, I'd be happy to help debug it.

**Comment by bevbomb** [comment]
Hey, i haven't had this issue at all since i've updated my pods, i'm still unsure why this was ever a problem though! 
Thanks

**Comment by appleguy** [comment]
@bevbomb: Thank you for reporting back! I'm going to close this issue, but if you run into the problem again, please re-open this or file a new issue.
