### ISSUE TITLE
[ASDataController] Cancel node measurement after Table/Collection is deallocated

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1181]
This caused an assertion failure for me because the data controller was trying to layout nodes to fit constrained size of (0,0). It's also a potential performance hazard if your user opens a giant feed and then immediately closes it and tries to do something else.

I'm honestly too scared to try to touch this one myself. My instinct would be, in `_layoutNode:withConstrainedSize:` to return early if `_dataSource` is nil. @nguyenhuy Thoughts?

**Comment by appleguy** [comment]
@Adlai-Holler Great find, thanks for reporting this. Certainly makes sense to me, and should not be too hard to fix; I had just never thought about this case, even though it is relatively obvious.

@rahul-malik, @lkzhao this is also close to code that you have recently changed, so if you feel motivated, it would be nice to fix this one soon.

**Comment by appleguy** [comment]
cc @maicki this may also fit into your work.

**Comment by appleguy** [comment]
@Adlai-Holler: Let us know if the attached PR addresses this to your satisfaction. I'm not certain that it will prevent background CPU usage after navigating away from a view, but it should address the assertion failure.

**Comment by Adlai-Holler** [comment]
Yep! This is great stuff.
