### ISSUE TITLE
[ASTextNode] ASTextKitRenderer crashed on a certain string with special characters

### ISSUE THREAD

**Issue by samhsiung** [facebook/AsyncDisplayKit#1182]
![screen shot 2016-02-04 at 4 26 46 pm](https://cloud.githubusercontent.com/assets/194822/12834440/365fefd4-cb5c-11e5-8e67-d3f073eaf4fc.png)

String is @"mkortnik: “ ✨ ❇ | ᴘʜᴏᴛᴏɢʀᴀᴘʜᴇʀ | ᴛᴏ ᴛʜᴇ ᴜɴᴋɴᴏᴡɴ.”

**Comment by appleguy** [comment]
@samhsiung thanks a lot for reporting this!  Pretty strange, I wonder what's going on?  Was the crash reproducible?  Did you happen to try it with UILabel?  I assume it had some attributes too...

**Comment by samhsiung** [comment]
Haven't seen this issue pop up in a while so it may be fixed.

**Comment by maicki** [comment]
Thanks @samhsiung I will close that issue for now and we should reopen if we have more information or other cases / issues are showing up.

**Comment by samhsiung** [comment]
@maicki actually I was able to repro recently:

<img width="1399" alt="screen shot 2016-07-18 at 9 20 51 pm" src="https://cloud.githubusercontent.com/assets/194822/16938504/8a1ba2dc-4d2d-11e6-8eed-09a2ceb7b6e1.png">

`NSConcreteAttributedString * attributedString = @"♉ ♥ ⓐ®©ⓗⓘ ⒹⓔⓒⓄⓇ ♥(ˆ⌣ˆԅ)"	0x00007feb26ea0060`

and attributes:

`Printing description of attributedString->attributes:
Length 23 (2 blocks, 1 used, block 0 is at 0)
 23 0x7feb2615c320 {
    ASAttributedStringWordKerning = 0;
    NSColor = "UIDeviceWhiteColorSpace 0.333333 1";
    NSFont = "<UICTFont: 0x7feb2615c200> font-family: \"Helvetica Neue\"; font-weight: normal; font-style: normal; font-size: 11.00pt";
    NSKern = "-0.05000000074505806";
    NSParagraphStyle = "Alignment 0, LineSpacing -0.815, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}`
