### ISSUE TITLE
[ASDisplayNode] UIViewController transitions cause flickering of nodes due to hierarchy changes

### ISSUE THREAD

**Issue by Cabus** [facebook/AsyncDisplayKit#1190]
This may be heavily related to this issue. [https://github.com/facebook/AsyncDisplayKit/issues/37](url)
The comments state that this should be fixed by now.

My app uses AsyncDisplayKit throughout its entire UI. However, the navigation architecture is a plain old UITabBarController with UINavigationControllers in each tab.

When I perform push and pop operations I can still see the flickering of ASDisplayNodes described in the linked issue above.
Strangely, the flickering is only happening with nodes that are 'NOT' handled by an ASCollectionNode or ASTableNode.
So when I add a node to a ViewControllers view like this: `view.addSubview(node.view)` the flickering starts happening during navigation operations.
I suspect it has something to do with nodes calling `clearContents` when they exit the hierarchy.
Is there any way to prevent the flickering?

**Comment by Adlai-Holler** [comment]
Thanks for reporting this, I'm seeing it as well. My temporary workaround is to add a `shouldSuppressClearContents` property on my node class of interest (MultiplexImageNode) and override `clearContents` thusly:

```
override func clearContents() {
	if !shouldSuppressClearContents {
		super.clearContents()
	}
}
```

**Comment by Cabus** [comment]
Indeed! The workaround is helped getting rid of the flickering. Thank you so much :)

**Comment by garrettmoon** [comment]
@Cabus do you mind checking to see if this still exists in master?

**Comment by appleguy** [comment]
@Cabus specifically we're almost certain this is fixed - I remember a solution to this that went in during March.  So you should no longer need the workaround.

**Comment by appleguy** [comment]
@Cabus one more ping, thanks again for reporting this -- would love to confirm it's fixed.  I'm pretty confident it is, so we'll close out if we don't hear back.
