### ISSUE TITLE
[ASTextNode Link attribute touch target is incorrect when using NSTextAlignmentCenter

### ISSUE THREAD

**Issue by martin-gearzero** [facebook/AsyncDisplayKit#1195]
When using link attributes with ASTextNode inside ASCellNode (and potentially elsewhere?) it seems that the touch targets are shifted to the right, so much so that if the touch target is at the end of the string it never calls the delegate method textNode:tappedLinkAttribute:value:atPoint:textRange:

Here's a snippet of code to set up the problem:

`

	ASTextNode *myTextNode = [ASTextNode new];
	myTextNode.userInteractionEnabled = YES;
	myTextNode.linkAttributeNames = @[kMyLinkAttributeName];
	myTextNode.delegate = self;
	[self addSubnode:myTextNode];

	NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:@"Here's my link"];

	NSRange mentionRange = NSMakeRange(10, 4);
	[attributedString addAttribute:kMyLinkAttributeName value:kMyValue range:mentionRange];

	NSMutableParagraphStyle *paragraphStyle = [NSMutableParagraphStyle new];
	paragraphStyle.alignment = NSTextAlignmentCenter;
	[attributedString addAttribute:NSParagraphStyleAttributeName value:paragraphStyle range:NSMakeRange(0, attributedString.length)];
`

If I make the attributedString longer as below, then touching past the intended target (e.g. on "please") then the tappedLinkAttribute delegate method is called.

`
attributedString = [[NSMutableAttributedString alloc] initWithString:@"Here's my link please enjoy"];
`

I'm wondering if this is related to other recent problems with using NSTextAlignmentCenter in ASTextNode's like this one: https://github.com/facebook/AsyncDisplayKit/issues/1031

Please let me know if there's anything else I can provide to help track it down. Thanks!

**Comment by appleguy** [comment]
@martin-gearzero this is a great report; thank you very much!  Indeed, I have recently discovered from debugging that other issues that there can be many string attributes that affect how sizing and/or rendering occur that we need to ensure other components of the texting node API are aware of. This one might be an easy fix, or it might become quite complex.

Sorry for the trouble, please do update the task if you come up with even a temporary workaround, orother debugging findings as they may help the investigation. Of course, please do continue to report any issues you encounter with the framework, and feel welcome to ask any questions!

**Comment by appleguy** [comment]
@martin-gearzero several changes have been made and that may have fixed this. Could you please try the latest master, and report back here with the results? If you don't have an opportunity to check, and no worries, I will circle back when I have time. Feel free to close the task if it is working correctly. The fix is speculative, in that it was not designed specifically for this issue, but does fix other issues related to centered text.

**Comment by martin-gearzero** [comment]
@appleguy this issue does indeed seem to be fixed in master. Please let me know if you need help with any additional testing. Thanks!
