### ISSUE TITLE
[ASTextNode] doesn't render attributed string properly when NSTextAlignmentCenter is used.

### ISSUE THREAD

**Issue by gauravmnit07** [facebook/AsyncDisplayKit#1203]
Hi,
You guys have been doing fabulous work with this library. I am facing a issue with the ASTextNode when used as subnode in cell node of ASTableView. It renders text correctly for the first time but text starts moving to the right as soon it re-renders after scrolling up and down. It was working fine in 1.9.6 but this problem appears after updating to master. Any help will be very helpful.
Thanks in advance.

**Comment by appleguy** [comment]
@gauravmnit07 thank you for taking the time to report this! It is particularly important information that you have found this is happening in master, but not the last stable release. I believe that is the first time I've heard that.

Could you take a quick scan through the recently reported issues, looking at the ones related to text node and center alignment, and describe here if any of them are seemingly identical to what you are encountering? Would you be able to create a small test project, or modify one of the projects in the examples directory to reproduce this? I would like to fix this issue sometime in this coming week, and we are planning to do a release within a couple days of that fix landing.

**Comment by gauravmnit07** [comment]
[TestExample.zip](https://github.com/facebook/AsyncDisplayKit/files/123590/TestExample.zip)

@appleguy Thanks for the quick reply. Sometimes I wonder how one can be so enthusiastic and passionate about the open source. Loved your passion and your dedication. Kudos to you and AsyncDisplayKit community for being so awesome.
I have attached the sample project showcasing the issue. Please let me know if you need anything else from my side. Thanks again.

**Comment by gauravmnit07** [comment]
@appleguy Hey, have you got the chance to look at the sample project? Please let me know if I am doing anything wrong or I can provide anything else to debug the issue. 
Thanks.

**Comment by appleguy** [comment]
@gauravmnit07 several changes have been made and that may have fixed this. Could you please try thelatest master, and report back here with the results? If you don't have an opportunity to check, then no worries, I will circle back when I have time. Feel free to close the task if it is working correctly. The fix is speculative, in that it was not designed specifically for this issue, but does fix other issues related to centered text.

**Comment by hannahmbanana** [comment]
@gauravmnit07: Thanks for reporting this _and_ including a sample project! I confirmed the issue on AsyncDisplayKit 1.9.6 and that it is fixed on version 1.9.8. I will add this test case to our ASTextNodeTests set of cases to check for any regressions against.
