### ISSUE TITLE
[ASMultiplexImageNode] Will Not Clear Fetched Image if No Cache Is Present

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1205]
Are we sure this is the behavior we want? Ideally these images are compressed, so they don't consume as much memory as the layer contents but they could still add up. Also this behavior is probably not something most users are aware of.

```objectivec
- (BOOL)_shouldClearFetchedImageData {
  return _cache != nil;
}
```

**Comment by appleguy** [comment]
@Adlai-Holler lol!  @garrettmoon had just noticed / reported this behavior on Friday.

If either of you could put up a diff, (and fix that open brace too!), I definitely don't think this is a reasonable behavior.

Not that we should be optimizing for a no cache case, but the only reasonable thing I can imagine doing would be to expand the fetch data range so we keep Data a bit longer... But this is not something we should worry about right now,

**Comment by garrettmoon** [comment]
@Adlai-Holler @appleguy I can address as part of my PINRemoteImage PR coming soon.

**Comment by garrettmoon** [comment]
@Adlai-Holler I removed the method in my PR #1209

**Comment by Adlai-Holler** [comment]
Good deal!
