### ISSUE TITLE
[ASStackLayoutSpec] Add flex-wrap support (& back-port to ComponentKit or React Native?)

### ISSUE THREAD

**Issue by gauravmnit07** [facebook/AsyncDisplayKit#1213]
Hi,
Is there any way to achieve flex-wrap behaviour using existing stack layout spec?

**Comment by nguyenhuy** [comment]
The current spec doesn't support flex-wrap, sorry. It will be really great if you want to work on this :)

**Comment by appleguy** [comment]
Seems like this one might be difficult. I don't believe the other two big UI frameworks using flex box on iOS implement this either, unfortunately.

**Comment by nguyenhuy** [comment]
Yes, CK doesn't have this, there is a concern about the complexity of the stack component. Not sure about ReactNative.

**Comment by gauravmnit07** [comment]
@nguyenhuy Thanks for the clarification. Will look into it for sure. :)

**Comment by appleguy** [comment]
@gauravmnit07 @nguyenhuy how tough would it be to make a new ASLayoutSpec that incorporates refactored logic from an open source implementation of something like UICollectionViewFlowLayout?
