### ISSUE TITLE
[ASLayoutSpec] Write out philosophy and API direction of layout transition API

### ISSUE THREAD

**Issue by levi** [facebook/AsyncDisplayKit#1214]
Just landed #1183 as a preliminary API for animating between layout specs. Next week, I'll add some more info here about the general decisions behind the API and the areas in which we can improve it for public 2.0 consumption or in future 2.x releases.

**Comment by smyrgl** [comment]
This API looks like exactly what I need to replace a hodgepodge of animation methods I'm using currently...very much looking forward to your documentation as it's not entirely clear what the best practices are to use this.

**Comment by levi** [comment]
Glad to hear that, @smyrgl. Planning to put something together in the next day or two!

**Comment by levi** [comment]
Here's a living document on how to use the current iteration of the API: https://gist.github.com/levi/09c6442722c2c5a8d0b3

There's also a roadmap of possible next steps I would like to share once my plate clear up a bit.

**Comment by appleguy** [comment]
@levi: Thanks for this awesome addition to the framework! For anyone looking for more information, check out the documentation up on the website:

**Layout Transition API Overview**
The Layout Transition API is designed this API to make all animations with AsyncDisplayKit easy - even transforming an entire set of views into a completely different set of views!

With this system, you simply specify the desired layout and AsyncDisplayKit will do the work to figure out differences from the current layout. It will automatically and new elements, remove unneeded elements after the transiton and update the position of any existing elements.

There are also easy to use APIs that allow you to fully customize the starting position of newly introduced elements, as well as the ending position of removed elements.

http://asyncdisplaykit.org/docs/implicit-hierarchy-mgmt.html _**(beta, will become default ON soon)**_
http://asyncdisplaykit.org/docs/layout-transition-api.html
