### ISSUE TITLE
[ASScrollView] Scroll indicators flicker when scrolling during bounce

### ISSUE THREAD

**Issue by GitGadd** [facebook/AsyncDisplayKit#1217]
Dragging a scroll view while it's bouncing past the content area causes the scroll indicator views to be incorrectly sized to fill the entire length of the scroll view for 1 frame.

I'm attaching a sample project that logs every time this happens. My own attempts to debug it have failed terribly; I hope somebody with more knowledge of the layout system can figure it out.

To reproduce:
1. Scroll towards an edge and let go, causing the scroll view to decelerate and begin 'springing back' once past the content edge
2. While the scroll view is still bouncing back, begin scrolling.

[ASScrollView_IndicatorFlickerTester.zip](https://github.com/facebook/AsyncDisplayKit/files/126562/ASScrollView_IndicatorFlickerTester.zip)

**Comment by appleguy** [comment]
Interesting report… I tried out your test case and see the flicker.

Have you tried to reproduce this with UIScrollView?  As you can see if you look into ASScrollNode, there really isn't any magic behind the scenes. It is basically just a UIScrollView.

Definitely interested to figure this one out.

**Comment by appleguy** [comment]
Oh, that's funny, I did not see exactly what you did here.  You should use ASScrollNode instead of wrapping the scroll view manually.

**Comment by appleguy** [comment]
Well, that did not fix it either. I'm not sure what is going on here, but I bet you could reproduce it with a regular UIScrollView in an app that doesn't link AsyncDisplayKit...  If you try that out, and you can't reproduce, check if any of the sample apps can have this occur.

**Comment by GitGadd** [comment]
Wow you're right, it is a UIScrollView bug! That's crazy; I've never seen this before, but have noticed it every day for the last couple of months developing using ASDK. Probably just one of those things you notice more once you see it.

I will definitely make a workaround/hack to fix this, should I still just close this issue since it's unrelated?

**Comment by levi** [comment]
I see this in Message.app when I scroll to the bottom in 9.3 beta 3.

**Comment by appleguy** [comment]
@levi wow, that's funny! Thanks for chiming in.

@GitGadd I will go ahead and close. I know, sometimes it is really crazy the stuff that Apple has broken in their frameworks. Fortunately, although there are many unique issues that can happen with a framework like ASDK, ultimately it isn't super magic and is mostly a thin frontend for UIKit :)
