### ISSUE TITLE
[PINRemoteImage] Subspec with WebP support?

### ISSUE THREAD

**Issue by smyrgl** [facebook/AsyncDisplayKit#1227]
There is a subspec for PINRemoteImage which has WebP support and I'm wondering if it is possible to define a subspec of AsyncDisplayKit that can use that subspec (as we obviously shouldn't include WebP support for the small number of us that actually make use of WebP as it requires including the libwebp library).

**Comment by smyrgl** [comment]
Note that I would be glad to offer a PR for this but I wanted to ask if there was any issue with doing so before offering such a thing up.  I'm not super familiar with advanced Podspec definitions and whether there is a better way to handle this than doing a subspec on top of the AsyncDisplayKit podspec as opposed to some other way.

**Comment by appleguy** [comment]
@smyrgl, we would be glad to take this as long as it is off by default, because WebP adds a fairly significant amount to the compilation time in resulting binary size. My understanding is that a similar set up is already in place for FLAnimatedImage, in that it can be enabled but is off by default. @garrettmoon is the author of the PINRemoteImage framework and implementer of the integration with ASDK.

**Comment by smyrgl** [comment]
@appleguy Totally agree, WebP should not be a default option.  As long as we are good with the subspec options I'll create the PR.

**Comment by garrettmoon** [comment]
@smyrgl you should be able to create a subspec for ASDK which include PINRemoteImage/webp

**Comment by smyrgl** [comment]
@garrettmoon Done.

**Comment by smyrgl** [comment]
Ack, freaking Cocoapods.  For some reason the way the Podspec is written when I do a nested subspec it works fine installing PINRemoteImage with the WebP subspec but the ADK components installed only include the ASDealloc2MainObject subspec files and not the rest.  I think the pod spec needs to be generally reconfigured so that there is a core spec that can be used as a dependency.

**Comment by garrettmoon** [comment]
I was afraid that might be the case. If it helps, PINRemoteImage is set up that way, might be useful to crib.

**Comment by smyrgl** [comment]
Yeah RESTKit has a nice implementation of Core+Subspecs too, I'll see if I can borrow some ideas and come up with a better diff.

**Comment by smyrgl** [comment]
So I'm going to close this because I realized that this can be accomplished by doing this:

```Ruby
pod 'AsyncDisplayKit'
pod 'PINRemoteImage/WebP'
```

It's not the cleanest solution but its easy enough.
