### ISSUE TITLE
Keyboard editability for ASTextNode

### ISSUE THREAD

**Issue by grgcombs** [facebook/AsyncDisplayKit#123]
Any thoughts on how to best approach a variation of ASTextNode that would function like a UITextView when *editing*?  For most of my dynamically-sized form fields, they would benefit greatly from the asynchronous layout during read-only, but they still need to be editable when the form view controller says it's time to edit. My guess is the fastest approach would be to wait until editing is started, then fade in a hidden UITextView over the frame of the text node, then once we're exiting from editing, send the entered text back to the node and fade out. That way the layout/sizing calculation is still asynchronous and the keyboard entry is built-in. 

Thoughts, alternatives, boos, hisses?

**Comment by ocrickard** [comment]
@secretiverhyme ++

**Comment by secretiverhyme** [comment]
We've just open-sourced [ASEditableTextNode](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASEditableTextNode.h), which does exactly this.  It's now available in master if you'd like to try it, and will be included in the upcoming AsyncDisplayKit 1.2 release.  =]

**Comment by grgcombs** [comment]
Awesome!!!  I was having mixed success on my attempt, this is great news!
