### ISSUE TITLE
[Possibly Interface Builder?] Table background color is reset when returning to view controller.

### ISSUE THREAD

**Issue by zrhzhouronghui** [facebook/AsyncDisplayKit#1240]
i have a tablenode, tablenode's backgroundcolor is purple，and then i select a cell,i enter another viewcontroller named labelsviewcontroller ，it‘s color is redcolor，but when i back， tablenode become whitecolor，someone can help me？ i use release 1.9.6

**Comment by aaronschubert0** [comment]
@zrhzhouronghui If you could post some code, that'd be very useful.

**Comment by zrhzhouronghui** [comment]
hi， 
listViewController‘s viewDidLoad

` 
-(void)viewDidLoad {
    [super viewDidLoad];
    ViewControllerList * __weak weakSelf = self;
    [self addViewOnMainThread:^{
        weakSelf.tableNode = [[ASTableNode alloc] initWithLayoutId:@"table"];
        weakSelf.tableNode.dataSource = weakSelf;
        weakSelf.tableNode.delegate = weakSelf;
        [weakSelf.rootNode addSubnode:weakSelf.tableNode];
    }];
} 
`

` 
-(void)addViewOnMainThread:(dispatch_block_t)block {
    dispatch_async(_vcQueue, ^{
        block();
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.view addSubview:self.rootNode.view];
            [self directoryDidChange:nil];
        });
    });
} 
`

this is LabelsController’s viewDidLoad
` -(void)viewDidLoad {
    [super viewDidLoad];
    LabelsController * __weak weakSelf = self;
    [self addViewOnMainThread:^{
        weakSelf.node = [[ASTextNode alloc] initWithLayoutId:@"hello"];
        weakSelf.node.attributedString = [[NSAttributedString alloc] initWithString:@"hello!hello!hello!"
                                                                 attributes:@{NSFontAttributeName: [UIFont systemFontOfSize:18]}];
        [weakSelf.rootNode addSubnode:weakSelf.node];
    }];
} 
`
in `[self directoryDidChange:nil];` this method，i will load backgroundColor configuration files，and assign to node's backgroundColor， i also check if this is my code problem~

**Comment by appleguy** [comment]
@zrhzhouronghui what is initWithLayoutId?  This may be resulting in initialization not occurring properly.

Where is the color set?  Make sure you are not using Interface Builder, as it is not compatible with this framework (as documented on the website and in each tech talk).

**Comment by appleguy** [comment]
I can debug this for you very quickly if you are able to provide a simple test project that reproduces the issue.  Try modifying one of the existing projects in examples/.

**Comment by appleguy** [comment]
@zrhzhouronghui also, please update to version 1.9.7 and let me know the overall details.

**Comment by appleguy** [comment]
@zrhzhouronghui - were you able to test on 1.9.7?
