### ISSUE TITLE
ASNetworkImageNode fails when PIN_REMOTE_IMAGE is not defined

### ISSUE THREAD

**Issue by ItamarM** [facebook/AsyncDisplayKit#1241]
Run the Kittens example and drop the PIN_REMOTE_IMAGE macro flag from the project.
It will trigger the cache assert.

**Comment by appleguy** [comment]
@garrettmoon, could you investigate? I'd like to ship 1.9.7 tomorrow, so ideally we can fix this soon.

**Comment by garrettmoon** [comment]
Fixed in #1261

**Comment by appleguy** [comment]
@ItamarM thank you for reporting this!!

**Comment by ItamarM** [comment]
@appleguy  my pleasure. keep doing that great work :+1:
