### ISSUE TITLE
[ASTableView] Add Optional constrainedSizeForRowAtIndexPath: Data Source Method

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1242]
This would correspond to the `ASCollectionDataSource` method

```objectivec
- (ASSizeRange)collectionView:(ASCollectionView *)collectionView constrainedSizeForNodeAtIndexPath:(NSIndexPath *)indexPath;
```

The widths in the returned size range would be ignored. This would make it easy for the data source to specify min/max row heights.

- Add the optional selector to the ASTableDataSource protocol with documentation.
- Add a test that the returned size is enforced.
- Add a flag for whether the data source responds to the selector.
- In `-[ASTableView dataController:constrainedSizeForNodeAtIndexPath:]`, check that flag and consult the data source if possible otherwise use the current unconstrained values.

I can tackle this in the next couple days but if someone else has bandwidth go for it!

**Comment by levi** [comment]
We also need this for collection views if we are going to have the cells self-size before the layout accesses them.

**Comment by appleguy** [comment]
@levi it does exist for collection today, right?  just checking.

@Adlai-Holler thanks for filing this.  @nguyenhuy confirmed it would be easy to add after his recent refactor, so we should try to do this in the next month before 2.0GM.

**Comment by appleguy** [comment]
PR #1769 closes this issue.
