### ISSUE TITLE
this node should be sized but doesn't even exist

### ISSUE THREAD

**Issue by megakode** [facebook/AsyncDisplayKit#126]
I keep getting `*** Assertion failure in -[ASRangeController sizedNodeForIndexPath:]`

I have a UICollectionViewCell with a ASTableView inside, and thus reload the ASTableView pretty rapidly if the user scrolls really fast.

The assertion that is triggered is

`ASDisplayNodeAssert(sizedNode, @"this node should be sized but doesn't even exist");`

I made a little check:

 ```
NSIndexPath *nonMutableIndexPath = [NSIndexPath indexPathForRow:indexPath.row inSection:indexPath.section];
ASCellNode *sizedNode = _nodes[nonMutableIndexPath];
// the _nodes dictionary must be modified by another thread right here i guess?

if( !sizedNode ) {
    if( !_nodes[nonMutableIndexPath] )
        NSLog(@"not found in nodes");
    else
    NSLog(@"found in nodes");
}
```

It seems that even though the nonMutableIndexPath is not found in the nodes dictionary in the first line, it is somehow always found in the second check i added, hinting that the nodes dictionary must be updated from another thread in between the two checks.

Maybe i am the first one to trigger such rapid reloads of ASTableView, but shouldn't it be able to handle this, or is there anything i can do for a workaround?

**Comment by tanliboy** [comment]
The bug is fixed.
