### ISSUE TITLE
ASButtonNode issues with NSParagraphStyle

### ISSUE THREAD

**Issue by davidlawson** [facebook/AsyncDisplayKit#1289]
The following AppDelegate code:

```objc
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
  self.window.backgroundColor = [UIColor whiteColor];
  
  NSMutableParagraphStyle *paragraphStyle = [[NSParagraphStyle defaultParagraphStyle] mutableCopy];
  paragraphStyle.alignment = NSTextAlignmentCenter;
  
  NSAttributedString *string = [[NSAttributedString alloc] initWithString:@"one two\nthree four five six" attributes:@{
    NSParagraphStyleAttributeName: paragraphStyle
  }];
  
  ASButtonNode *buttonNode = [[ASButtonNode alloc] init];
  [buttonNode setAttributedTitle:string forState:ASControlStateNormal];
  
  self.window.rootViewController = [[ASViewController alloc] initWithNode:buttonNode];
  [self.window makeKeyAndVisible];
  return YES;
}

@end
```

produces the following screenshot:

![simulator screen shot 1 mar 2016 1 08 46 am](https://cloud.githubusercontent.com/assets/3368352/13396713/3e801b24-df4a-11e5-958c-5a03ae319f79.png)

However when you press the home button and re-open the app, this is now displayed:

![simulator screen shot 1 mar 2016 1 08 51 am](https://cloud.githubusercontent.com/assets/3368352/13396711/3e773c20-df4a-11e5-950e-67a1d5d4b3a5.png)

It appears that setting the ASButtonNode to non-layer-backed fixes the issue, but there's probably something underlying that is going wrong.

This also happens when pushing a view controller onto a navigation stack then popping back to the button.

**Comment by appleguy** [comment]
@davidlawson this is very, very strange — thank you for reporting it and providing the code!  I will try to investigate this soon.  The biggest problem in the text stack right now is a set of problems similar to this related specifically to the center alignment.  What exactly is the change to set to non-layer-backed — your code doesn't set it to layer-backed, do you mean setting the internal astextnode in the button which defaults to layer-backed?

**Comment by davidlawson** [comment]
Yeah sorry, I was setting the titleNode to non-layer-backed:

`buttonNode.titleNode.layerBacked = false;`

**Comment by appleguy** [comment]
@davidlawson several changes have been made and that may have fixed this. Could you please try the latest master, and report back here with the results? If you don't have an opportunity to check, then no worries, I will circle back when I have time. Feel free to close the task if it is working correctly. The fix is speculative, in that it was not designed specifically for this issue, but does fix other issues related to centered text.

**Comment by davidlawson** [comment]
@appleguy that seems to have done the trick! :)

The particular commit that fixed this issue was https://github.com/facebook/AsyncDisplayKit/commit/b6abb347e322d6acd001dd8770e9a8f4a0220887.

**Comment by appleguy** [comment]
Very awesome, thanks!  Sorry for the trouble :(  This was a lame bug, we had expected to be using self.constrainedSize and instead have _constrainedSize as a separately maintained ivar.  I will clean this up later for clarity / state reduction.
