### ISSUE TITLE
[ASDataController] Verify that constrainedSizeForNodeAtIndexPath: is always called on main.

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/AsyncDisplayKit#1298]
Hey @appleguy @nguyenhuy 6d463da has caused a regression on the issue I reported at the weekend.

Specifically the issue was that `- (ASSizeRange)collectionView:(ASCollectionView *)collectionView constrainedSizeForNodeAtIndexPath:(NSIndexPath *)indexPath;` was called concurrently. This commit seems to have re-introduced that behaviour. What can we do to fix this?

**Comment by appleguy** [comment]
@aaronschubert0 thanks for reporting, definitely a surprise to me.  The main point of introducing the node context was to fix the constrained size call point (In fact to move it to main, not just serial).  This should be fixed today.

**Comment by nguyenhuy** [comment]
@aaronschubert0 Do you have a stack trace or anything I can use to narrow down the cause? The commit you pointed out is a follow-up and I want to make sure the first commit does what it is supposed to be.

**Comment by nguyenhuy** [comment]
I added `ASDisplayNodeAssertMainThread();` to where ASDataController and ASCollectionDataController ask for constrained sizes ([here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Details/ASDataController.mm#L236) and [here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Details/ASCollectionDataController.mm#L206)). I tested with different apps and haven't got any assertions. Could you try the same and share a stack trace?

**Comment by appleguy** [comment]
@aaronschubert0 Definitely interested as well!  Keep testing latest master and let us know if you ever see this call off main - it should in fact not only be serial, but on main.

**Comment by aaronschubert0** [comment]
@nguyenhuy Yeah the commit I pointed to is when change in behaviour occurred. The commit before this operate as expected. I'll get a stack trace for you. @appleguy Will test against master again and see wha the results are.

**Comment by aaronschubert0** [comment]
@nguyenhuy @appleguy Bizarrely seems to work against master now. Called on main and serially. It's a bit worrying that it wasn't working against master initially and now it is but I'm happy to close this with the assurance of your top class work. Will keep an eye on it but going to close this. Thanks for taking the time to investigate.

**Comment by appleguy** [comment]
@aaronschubert0 really appreciate you testing this! Sometimes Xcode defies all logic and holds a stale version of something during the build, hopefully that was it. I think it is now constructed in such a way that it should not be possible to be called off main. This is a very important issue and so I am quite glad it is resolved.
