### ISSUE TITLE
[ASVideoNode] Video node does not support HLS video

### ISSUE THREAD

**Issue by gazreese** [facebook/AsyncDisplayKit#1321]
I've been playing around with the ASVideoNode functionality for a project and using it to replace the custom functionality I had prototyped. Unfortunately the current ASVideoNode API doesn't support HLS (HTTP live streaming) video.

I've been able to add this functionality in my own fork and I'm raising this issue to capture the change and to see if it can get integrated back into ASDK. I'm no ASDK expert, so you might have to bear with me a little :-)

To add support it would be necessary to initialise the ASVideoNode with either a URL or an AVAsset, analogous to the initialisation of an AVPlayerItem in UIKit. I'm proposing to change the API to make the initialisation with either method explicit:

```
// Mirror the construction of AVPlayerItem with the URL or AVAsset
- (instancetype)initWithURL:(NSURL*)url;
- (instancetype)initWithAsset:(AVAsset*)asset;
```

And in turn to make the current property-based initialisation read-only;

`@property (atomic, strong, readonly) AVAsset *asset;`

**Comment by appleguy** [comment]
@gazreese - I'm excited to see this in the framework! It's great that this is already in a PR and that we are committed to integrating this functionality!
