### ISSUE TITLE
Subclassing ASTextCellNode issue with Swift

### ISSUE THREAD

**Issue by cc-lam** [facebook/AsyncDisplayKit#1333]
Hello, thank you for this library.

I'm having an issue when subclassing ASTextCellNode with Swift.

```swift
class NodeText: ASTextCellNode {
  init(myText: String)
    super.init()
    self.text = myText
} 
```
The above code fails with: fatal error: use of unimplemented initializer 'init(attributes:insets:)' for class 'Swift_Example.NodeTest'

It looks as if the default empty initialiser `init()` doesn't work with swift ?

**Comment by 1nput0utput** [comment]
@cc-lam ```init(attributes:insets:)``` is the designated initializer in ASTextCellNode, whereas ```init()``` a convenience. You can use the ASTextCellNode init() method by marking your initializer as convenience.
```
class NodeText: ASTextCellNode {
  convenience init(myText: String)
    self.init()
    self.text = myText
} 
````

**Comment by cc-lam** [comment]
@1nput0utput Thanks for the clarification.
