### ISSUE TITLE
[ASLayoutSpec] documentation for ASLayout missing

### ISSUE THREAD

**Issue by MarvinNazari** [facebook/AsyncDisplayKit#1335]
There is no documentation for all these new fancy `ASLayout`s, would be awesome to have some sort of guide.

**Comment by fatuhoku** [comment]
:+1: besides documentation, can't really effectively work with it unless there's a clear tutorial for how it all works either.

**Comment by hannahmbanana** [comment]
@MarvinNazari: @fatuhoku: check out our new work-in-progress documentation:

http://asyncdisplaykit.org/docs/automatic-layout-basics.html
http://asyncdisplaykit.org/docs/automatic-layout-containers.html
http://asyncdisplaykit.org/docs/automatic-layout-examples.html
http://asyncdisplaykit.org/docs/automatic-layout-debugging.html

Beta (soon to be on by default):
http://asyncdisplaykit.org/docs/implicit-hierarchy-mgmt.html
http://asyncdisplaykit.org/docs/layout-transition-api.html

Submit any questions, compliments, errors, complaints, etc on the #documentation channel in Slack (#1582).
