### ISSUE TITLE
[_ASAsyncTransactionGroup] NSHashTable copy

### ISSUE THREAD

**Issue by daryl5** [facebook/AsyncDisplayKit#1342]
In `- (void)commit`, maybe you can use snippet below to avoid a copy
> //before
NSHashTable *containerLayersToCommit = [_containerLayers copy];
    [_containerLayers removeAllObjects];
//after
NSHashTable *containerLayersToCommit = _containerLayers;
    _containerLayers = [NSHashTable hashTableWithOptions:NSPointerFunctionsObjectPointerPersonality];

**Comment by levi** [comment]
@daryl5 thanks for the suggestion. Could you include this in a pull request?

**Comment by appleguy** [comment]
@daryl5 great suggestion, thanks!
