### ISSUE TITLE
Ensure valid frame is generated for ASCollectionNode (ASTableNode?) cells

### ISSUE THREAD

**Issue by eanagel** [facebook/AsyncDisplayKit#1345]
Currently if the layout system generates invalid values for the size of a cell, we blindly send that off to UICollectionView and it can hang in this case. In my use case we were sending a size of {INF, 0} which set UICollectionView into lala land. (This was because of a bug where we were sending an invalid constrainedSize under certain conditions - see #1344, but we should add sanity checks regardless.)

**Comment by hannahmbanana** [comment]
looks like we need to add this for ASTableView as well.

**Comment by hannahmbanana** [comment]
I heard another report of this on Slack recently. @Adlai-Holler - is this a quick fix?

**Comment by garrettmoon** [comment]
I believe this has been fixed, @eanagel can you confirm and reply if not?
