### ISSUE TITLE
[ASTextNode] Truncation token not visible when maximumNumberOfLines = 0

### ISSUE THREAD

**Issue by tomizimobile** [facebook/AsyncDisplayKit#1350]
I have an ASViewController that includes an ASTextNode (among other views) that initially has `maximumNumberOfLines` set to 4. When the truncation token is pressed, the `maximumNumberOfLines` is set to 0, and allows the whole text to be visible. The layoutSpec for the viewController node ensures that nothing gets pushed off the screen, so if the text is very long, it may still need truncation again (and if the truncation token is tapped again, I bring them to a different view). In this case, the truncation token doesn't appear - however, the area where it should appear _does_ respond to touches and shows highlights, so it seems that part of it works as expected. I believe the truncation token doesn't show because at the time `-_truncate()` is called in ASTextKitTailTruncater, the textContainer size is +Inf, so the visibleCharacterRange is the whole range. I am not familiar enough with this to come up with a good fix, but I'm betting that truncating after the size is constrained would fix this.

**Comment by hannahmbanana** [comment]
@tomizimobile: this is a bit complicated to understand in paragraph form. :)

Would it be possible to get a sample app (command + D on the project folder and strip out anything unnecessary)?

**Comment by tomizimobile** [comment]
@hannahmbanana I made a test project to show this off, and found that the issue is fixed in master. Turns out by commit 12d757a38d09efc62fd26ad706b8eeca96f1e3dd, it's working as expected, I think likely due to changes in https://github.com/facebook/AsyncDisplayKit/pull/1637

**Comment by hannahmbanana** [comment]
@tomizimobile: thanks for the quick reply and for checking it out on master. This is the best sort of update!

**Comment by tomizimobile** [comment]
@hannahmbanana I realized when getting another test project together that I still owed you this one - sorry for the delay

[asdk-issue-1350.zip](https://github.com/facebook/AsyncDisplayKit/files/418035/asdk-issue-1350.zip)
