### ISSUE TITLE
[ASRangeController] Collection was mutated while being enumerated.

### ISSUE THREAD

**Issue by yichungwang** [facebook/AsyncDisplayKit#1360]
Hi,
Thanks for creating such a good framework. I received an error when trying to enter background / foreground. Below is the crash log.

Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <NSConcreteMapTable: 0x7fb38b41fb80> was mutated while being enumerated.'

1	CoreFoundation	__exceptionPreprocess + 124
2	libobjc.A.dylib	objc_exception_throw + 52
3	CoreFoundation	__NSFastEnumerationMutationHandler + 128
4	Foundation	-[NSConcreteMapTable countByEnumeratingWithState:objects:count:] + 76
5	MapMyBeauty	+[ASRangeController didEnterBackground:] (ASRangeController.mm:470)
6	CoreFoundation	__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 16
7	CoreFoundation	_CFXRegistrationPost + 392
8	CoreFoundation	___CFXNotificationPost_block_invoke + 56
9	CoreFoundation	-[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1528
10	CoreFoundation	_CFXNotificationPost + 364
11	Foundation	-[NSNotificationCenter postNotificationName:object:userInfo:] + 64
12	UIKit	__47-[UIApplication _applicationDidEnterBackground]_block_invoke + 316
13	UIKit	+[UIViewController _performWithoutDeferringTransitions:] + 124
14	UIKit	-[UIApplication _applicationDidEnterBackground] + 96
15	UIKit	-[UIApplication _handleApplicationDeactivationWithScene:shouldForceExit:transitionContext:completion:] + 696
16	UIKit	-[UIApplication workspaceShouldExit:] + 148
17	FrontBoardServices	-[FBSSerialQueue _performNext] + 180
18	FrontBoardServices	-[FBSSerialQueue _performNextFromRunLoopSource] + 52
19	CoreFoundation	__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 20
20	CoreFoundation	__CFRunLoopDoSources0 + 536
21	CoreFoundation	__CFRunLoopRun + 720
22	CoreFoundation	CFRunLoopRunSpecific + 380
23	GraphicsServices	GSEventRunModal + 176
24	UIKit	UIApplicationMain + 200
25	MapMyBeauty	main (main.m:14)
26	???	0x0 + 0

**Comment by appleguy** [comment]
@yichungwang - thanks for reporting this bug! 

Could you try out the latest master? PR #1363 should fix crash on suspend. Let me know either way - if it works or doesn't.

**Comment by mapmybeauty** [comment]
Thanks @appleguy, everything works great now.

**Comment by yichungwang** [comment]
Thanks @appleguy ! Everything works great now.
