### ISSUE TITLE
How to use ASOverlayLayoutSpec more efficiently

### ISSUE THREAD

**Issue by tungvoduc** [facebook/AsyncDisplayKit#1374]
I want to put everything on top of a backgroundNode and here is how I do it:

` override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        
        var children : [ASLayoutable] = [profileImageNode, labelNode]
        let horizontalStack = ASStackLayoutSpec(direction: ASStackLayoutDirection.Horizontal, spacing: kHorizontalContentSpacing, justifyContent: ASStackLayoutJustifyContent.Start, alignItems: ASStackLayoutAlignItems.Center, children: children)
    
        let calculatedSize = horizontalStack.measureWithSizeRange(constrainedSize).size
        backgroundNode.preferredFrameSize = CGSize(width: calculatedSize.width, height: calculatedSize.height + kBackgroundVerticalInset*2)
        
        let insetSpec = ASInsetLayoutSpec(insets: UIEdgeInsets(top: kContentVerticalInset, left: kContentHorizontalInset, bottom: kContentVerticalInset, right: kContentHorizontalInset), child: horizontalStack)
        let overlaySpec =  ASOverlayLayoutSpec(child: backgroundNode, overlay: insetSpec)
        
        return ASInsetLayoutSpec(insets: UIEdgeInsets(top: kBackgroundVerticalInset, left: kBackgroundHorizontalInset, bottom: kBackgroundVerticalInset, right: kBackgroundHorizontalInset), child: overlaySpec)
    }`

Because there is no way to know what should be the exact size of the background, so I put two lines here:
` let calculatedSize = horizontalStack.measureWithSizeRange(constrainedSize).size
        backgroundNode.preferredFrameSize = CGSize(width: calculatedSize.width, height: calculatedSize.height + kBackgroundVerticalInset*2)`

I think it is not an optimal way of doing that. Is there any better solution in this case?

**Comment by aaronschubert0** [comment]
@tungvoduc If the background node is a type of image node, then this is the way to do it. You shouldn't have to call `let calculatedSize = horizontalStack.measureWithSizeRange(constrainedSize).size` but you do need to set the `preferredFrameSize`. On the other hand if it's a known ratio, then you can make the background node be the child of  a ASRatioLayoutSpec.
