### ISSUE TITLE
ASTextNode truncation

### ISSUE THREAD

**Issue by MarvinNazari** [facebook/AsyncDisplayKit#1376]
The `maximumNumberOfLines` dosent work in `ASTextNode` and the string goes of the view, [here is my cell source code](https://gist.github.com/MarvinNazari/f73fff3b6d687af9cf88), i want the text to be truncated if its longer than the width of screen.

It gets like this:
![Image](https://i.imgsafe.org/18c8325.png)

This is an example with a shorter text.
![Image](https://i.imgsafe.org/979bde3.png)

**Comment by yury** [comment]
Try to add `flexShrink` on textNode

**Comment by MarvinNazari** [comment]
already tested it, it dosen't work @yury

**Comment by hannahmbanana** [comment]
@MarvinNazari I noticed #1295 could be a related issue and there appears to have been a recent fix for it. Are you on the master branch? Have you tried setting truncationAttributedString as a work around?

**Comment by appleguy** [comment]
@MarvinNazari make sure you are setting properties on the text node itself, not on any containing inset or other layout specification. Please reopen this task if you have not been able to Address the problem! 

As you would imagine, this is meant to be simple and reliable, but we are working on documentation right now. In fact, documentation is the primary reason the framework has not gone to version number 2.0, but expect a three-part tutorial series on Ray Wenderlich.com in the next month. It will also cover layout specifications in detail.

https://github.com/facebook/AsyncDisplayKit/issues/1396
