### ISSUE TITLE
[ASLayoutSpec] Side by side ASNetworkImageNode was overlapped until you scroll

### ISSUE THREAD

**Issue by hebertialmeida** [facebook/AsyncDisplayKit#1380]
I have a `ASCellNode` with two photos, they are aligned Horizontally and when it loads it was overlapped, until you scroll down and the tableView calls `tableView(tableView: ASTableView, willBeginBatchFetchWithContext context: ASBatchContext)`, the new cell loads normally.

Initial load:
![fullsizerender](https://cloud.githubusercontent.com/assets/103670/13780723/75d37282-ea9f-11e5-9313-ae59987b975b.jpg)

After scroll:
![fullsizerender 2](https://cloud.githubusercontent.com/assets/103670/13780756/9253579c-ea9f-11e5-8bfe-276362635e2d.jpg)

On `PhotoCardNode` I implement the `ASNetworkImageNodeDelegate` to `self.setNeedsLayout()` when the image finish loading, if I don't call `self.setNeedsLayout()` it works but the image ratio is wrong.
![fullsizerender 3](https://cloud.githubusercontent.com/assets/103670/13780818/c66c04ca-ea9f-11e5-8652-ff5882ba585b.jpg)

This is my full class if it helps.
```swift
final class PhotoCardNode: ASControlNode, ASNetworkImageNodeDelegate {
    var imageOne: ASNetworkImageNode!
    var imageTwo: ASNetworkImageNode!

    init(withURLs: [String]) {
        super.init()
        
        imageOne = createImageNode(imageWithURL: withURLs[0])
        imageTwo = createImageNode(imageWithURL: withURLs[1])
    }
    
    override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        super.layoutSpecThatFits(constrainedSize)
        
        let imageOneSpec = imageRatio(imageOne)
        let imageTwoSpec = imageRatio(imageTwo)
        imageOneSpec.flexBasis = ASRelativeDimensionMakeWithPercent(0.5)
        imageTwoSpec.flexBasis = ASRelativeDimensionMakeWithPercent(0.5)
        
        return ASStackLayoutSpec(
            direction: .Horizontal,
            spacing: 5,
            justifyContent: .Start,
            alignItems: .Stretch,
            children: [imageOneSpec, imageTwoSpec])
    }
    
    // MARK: - ASNetworkImageNodeDelegate
    
    func imageNode(imageNode: ASNetworkImageNode, didLoadImage image: UIImage) {
        self.setNeedsLayout()
    }

    // MARK: - Node functions

    func createImageNode(imageWithURL URL: String) -> ASNetworkImageNode {
        let image = ASNetworkImageNode()
        image.backgroundColor = ASDisplayNodeDefaultPlaceholderColor()
        image.delegate = self
        image.URL = NSURL(string: URL)
        addSubnode(image)
        return image
    }
    
    func imageRatio(imageNode: ASNetworkImageNode) -> ASRatioLayoutSpec {
        if let image = imageNode.image {
            let imageSize = image.size
            return ASRatioLayoutSpec(ratio: imageSize.height / imageSize.width, child: imageNode)
        }
        return ASRatioLayoutSpec(ratio: 0.5, child: imageNode)
    }
}
```

I have tried issue #718 and #1232 but I can't fix the problem. Also, I have tried delegate image load to ViewController and call `beginUpdates()` and `endUpdates()`
```swift
let tableView = tableNode.view
tableView.beginUpdates()
tableView.endUpdates()
```
Without success.

Thanks

**Comment by hannahmbanana** [comment]
@hebertialmeida - would it be possible to put together a small sample project with the PhotoCardNode tableView?

**Comment by hebertialmeida** [comment]
I have used fixed using ratio for image. Thanks
