### ISSUE TITLE
[Help] Transition between two controllers with ASCollectionView

### ISSUE THREAD

**Issue by Baevra** [facebook/AsyncDisplayKit#1395]
Hello, i'm a big fun of this kit and I need help. I'm trying to create animated zoom transition (looks like Pinterest transition) between two controllers with the same dataSource that contains 1k+ items. with UIKit the second controller is setup and scrolled to the selected index path before transition end, but with ASDK the second controller takes time to prepare (It depends on the amount of items in dataSource) and transition not works correctly. How can i improve the prepare speed of the second controller or what logic i should to use in this case?
Thank you very much for your awesome work !

**Comment by hannahmbanana** [comment]
@Baevra - Would it be possible to include some code, or better yet, a small sample project to help understand how you are implementing the zoom transition? It sounds like you might not be using ASDK in the most optimal way.

**Comment by hannahmbanana** [comment]
@Baevra - Let me know if you've figured out the issue, otherwise I'd be happy to try to help you out.

**Comment by Baevra** [comment]
@hannahmbanana I haven't solved the problem. The problem is that datasource has more than 1000 items when creating the controller and it takes a long time to display items

**Comment by hannahmbanana** [comment]
@Baevra: 1k+ items in your dataSource shouldn't be a problem for ASDK depending on how you've implemented it in your app. 

Could you provide some code here so that we can help you out? Or a sample project would be most ideal. Alternatively, you can email @appleguy at AsyncDisplayKit@gmail.com if your project is more sensitive.

**Comment by Baevra** [comment]
@hannahmbanana Here is an example https://github.com/Baevra/ASDKTest
thank you so much for your help

**Comment by Baevra** [comment]
@hannahmbanana I have updated the project and added UIKit for compare
