### ISSUE TITLE
Using insertRowsAtIndexPaths is loosing contentOffset position

### ISSUE THREAD

**Issue by alibasta** [facebook/AsyncDisplayKit#1411]
Hi,

I want to use insertRowsAtIndexPaths to add cells at the top of a ASTableView. When I scroll to the middle of the TableView and calling the following code, my current scrolling position is not the same as before.

```objective-c
        NSLog(@"before tableView.contentOffset.y: %f", _tableView.contentOffset.y);
        NSLog(@"before height: %f", _tableView.contentSize.height);
        [_tableView beginUpdates];
        [self addMoreObjectsToDataSource];
        [_tableView insertRowsAtIndexPaths:@[[NSIndexPath indexPathForRow:0 inSection:0], [NSIndexPath indexPathForRow:1 inSection:0], [NSIndexPath indexPathForRow:2 inSection:0]] withRowAnimation:UITableViewRowAnimationNone];
        [_tableView endUpdatesAnimated:NO completion:(void (^)(BOOL)) ^{
            NSLog(@"tableView.contentOffset.y: %f", _tableView.contentOffset.y);
            NSLog(@"height: %f", _tableView.contentSize.height);
        }];
```

I'm also not able to calculate the new offset because the height of the tableView in the "endUpdatesAnimated:" completion is the same as before.

Best

Alex

**Comment by hannahmbanana** [comment]
@alibasta: If you have time, could you check out PR #1139 and let us know if it resolves your case here? It would be extremely helpful to us!

**Comment by hannahmbanana** [comment]
@alibasta: it's ak! :)

**Comment by appleguy** [comment]
@alibasta if that PR does resolve your issue, it would actually be really great to know, because I have not landed it only due to the lack of a test case the team has to verify the change.  So your verification would allow us to land it :).  @maicki could you please watch for this, and if it doesn't work, look at another way to verify 1139 is correct / ready for merge?

**Comment by alibasta** [comment]
@hannahmbanana @appleguy PR #1139 seems to fix it. Just wrote a sample and can not reproduce it anymore. Sorry that I'm not able to test it with my code from March but I'm travelling right now.

Best

Alex Köhn aka ak ;-)

**Comment by hannahmbanana** [comment]
@alibasta: Thank you so much for checking for us! We will get this PR merged soon.
