### ISSUE TITLE
[PINRemoteImage] Question on build versions.

### ISSUE THREAD

**Issue by ForrestAlfred** [facebook/AsyncDisplayKit#1423]
in ASPINRemoteImageDownloader, 

- (UIImage *)synchronouslyFetchedCachedImageWithURL:(NSURL *)URL
{
  NSString *key = [[PINRemoteImageManager sharedImageManager] cacheKeyForURL:URL processorKey:nil];
  PINRemoteImageManagerResult *result = [[PINRemoteImageManager sharedImageManager] synchronousImageFromCacheWithCacheKey:key options:PINRemoteImageManagerDownloadOptionsSkipDecode];
  return result.image;
}

synchronousImageFromCacheWithCacheKey:options: can not be found in PINRemoteImageManager!

**Comment by appleguy** [comment]
@ForrestAlfred it certainly should be in the latest version of PINRemoteImage!  Can your make sure your podfile isn't explicitly requiring an older version?

Try updating to ASDK 1.9.7.1, which requires PINRemoteImage 2.1.2 (this is specified in the .podspec).

**Comment by ForrestAlfred** [comment]
Thanks, I will do it.

**Comment by hannahmbanana** [comment]
@ForrestAlfred - did updating to the latest version solve your issue?

**Comment by ForrestAlfred** [comment]
Yeah,  I update to 1.9.7.1, problem solved. Thanks!

**Comment by appleguy** [comment]
@ForrestAlfred - great! Thanks for reporting the issue!
