### ISSUE TITLE
[ASOverlayLayoutSpec] OverlayLayout should warn user if overlay node is not explicitly above child node in the node hierarchy

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#1425]
e.g. I'm using the CustomCollectionView project to try some relatively complex layouting. I want my avatar image view to appear on top and over the recipe image.

```objc
        // init...
        _avatarImageNode = [[ASNetworkImageNode alloc] init];
        _avatarImageNode.backgroundColor = [UIColor orangeColor];
        _avatarImageNode.preferredFrameSize = avatarRoundelSize;
        _avatarImageNode.cornerRadius = avatarRoundelSize.width / 2;
      _avatarImageNode.URL = link;
        [self addSubnode:_avatarImageNode];
        _avatarImageNode.zPosition = 2; // !!!!!
        _avatarImageNode.delegate = self;

        _recipeImageNode = [[ASImageNode alloc] init];
        _recipeImageNode.image = image;
        [self addSubnode:_recipeImageNode];

// ...

- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {

    UIImage *image = _recipeImageNode.image;

    CGFloat imageRatio = (CGFloat) (image != nil ? image.size.height / image.size.width : 0.5);

    ASRatioLayoutSpec *aspectBoundImage = [ASRatioLayoutSpec ratioLayoutSpecWithRatio:imageRatio child:_recipeImageNode];
    ASInsetLayoutSpec *insetAspectBoundImage = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 0, 20, 0) child:aspectBoundImage];

    ASRelativeLayoutSpec *avatarAtLowerLeft = [ASRelativeLayoutSpec relativePositionLayoutSpecWithHorizontalPosition:ASRelativeLayoutSpecPositionStart verticalPosition:ASRelativeLayoutSpecPositionEnd sizingOption:ASRelativeLayoutSpecSizingOptionMinimumSize child:_avatarImageNode];
    ASOverlayLayoutSpec *recipeImageOverlaidWithAvatar = [ASOverlayLayoutSpec overlayLayoutSpecWithChild:insetAspectBoundImage overlay:avatarAtLowerLeft];

    return recipeImageOverlaidWithAvatar;
}
```

Without `zPosition = 2`:
![2016-03-24 17 35 45](https://cloud.githubusercontent.com/assets/430233/14026627/a952de88-f1eb-11e5-9955-c26ed30eed94.png)

With `zPosition = 2`:
![2016-03-24 18 07 16](https://cloud.githubusercontent.com/assets/430233/14026854/bb51870a-f1ec-11e5-81ad-f4935e8101cf.png)

**Comment by fatuhoku** [comment]
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {

    UIImage *image = _recipeImageNode.image;

    CGFloat imageRatio = (CGFloat) (image != nil ? image.size.height / image.size.width : 0.5);

    ASRatioLayoutSpec *aspectBoundImage = [ASRatioLayoutSpec ratioLayoutSpecWithRatio:imageRatio child:_recipeImageNode];
    ASInsetLayoutSpec *insetAspectBoundImage = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 0, 20, 0) child:aspectBoundImage];

    ASRelativeLayoutSpec *avatarAtLowerLeft = [ASRelativeLayoutSpec relativePositionLayoutSpecWithHorizontalPosition:ASRelativeLayoutSpecPositionStart verticalPosition:ASRelativeLayoutSpecPositionEnd sizingOption:ASRelativeLayoutSpecSizingOptionMinimumSize child:_avatarImageNode];

    ASOverlayLayoutSpec *recipeImageOverlaidWithAvatar = [ASOverlayLayoutSpec overlayLayoutSpecWithChild:insetAspectBoundImage overlay:avatarAtLowerLeft];

    return recipeImageOverlaidWithAvatar;

}

**Comment by hannahmbanana** [comment]
@fatuhoku - Thanks for including code and images! It makes debugging this issue so much easier.

ASLayoutSpecs are relatively new and it looks like `ASOverlayLayoutSpec` isn't yet configured to override the order in which you call `addSubnode:`  This is definitely a bug.

Here are several ways to get around this until the bug is fixed:
- use `zPosition` as you have done. Just a warning: zPosition will not affect event handling, so it's okay if you don't have touches, but if you do have touches, don't use it. 
- use `addSubnode:` in the correct order (`_recipeImageNode` and then `_avatarImageNode`)
- use [self.view bringSubviewToFront:_avatarImageNode.view];

**Comment by fatuhoku** [comment]
@hannahmbanana Great tips! I'm used thinking about UI in a declarative way and forgot that UIKit cares very much what order children are placed.

Hmmm. Though thinking about it, should `ASOverlayLayout` really be manipulating the ordering of `subnodes` array?  Sounds like it might be doing a bit too much. `ASBackgroundLayout` would also require the same behaviour.

What might be more useful is if the layout could spit out a warning, saying that "ASDK is trying to overlay A over B but node B is before A in pecking order. This will cause A to appear beneath B (given they have identical `zPosition`). Make sure you have [self addSubnode:A] before [self addSubnode:B]. ".

**Comment by appleguy** [comment]
@fatuhoku: This warning is a reasonable suggestion and I will make note of in our roadmap tracker. 

When Implicit Node Hierarchy Management becomes default (it is currently beta), adding SubNodes will be used almost exclusively for manually overriding the default ordering of the nodes that is defined in the layoutSpec. So, if there were no addSubnode calls, as will be the most common case, overlaySpec will ensure that the ordering is correct. 

For Info on Implicit Node Hierarchy Management: http://asyncdisplaykit.org/docs/implicit-hierarchy-mgmt.html

@hannahmbanana: could you make a note of this warning in our documentation?
