### ISSUE TITLE
[ASStackLayoutSpec] Omit subnodes that are marked .hidden (similar to UIStackView).

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#1431]
Hi,  In using ASDK's layout I should not to caculate size of a cellNode's subNode,Just like I use autolayout,When I use UIStackView,I set a stackView's contrain or hidden, the stackView will also change frame, So , if I set a cellNode's subNode hidden,can cellNode change in the same time?

**Comment by appleguy** [comment]
@wy19901227 thank you for filing this issue. Is a good suggestion to automatically leave out children in a stack that are marked as hidden.  Was not aware that the new IOS 9 stack component has similar behavior.

For now, there is a good way to accomplish this. We are going to enabled by default (soon / before 2.0) a new framework feature called implicit hierarchy management. You can turn this on for your own node now, and it allows controlling the children in a stack automatically based on what you would turn in the layout spec.

It does not look at the hidden property, but rather automatically adds or removes sub nodes for you according to what is actually in the layout specification.

**Comment by hannahmbanana** [comment]
@wy19901227 - To enable implicit hierarchy management, do the following 3 things:
- `#import "ASDisplayNode+Beta.h"`
- add `self.usesImplicitHierarchyManagement = YES;` to your `init:` method
- any `addSubnode:` calls are no longer needed when using this option, unless you need to manually position the node in `layout` and cannot position the node in `layoutSpecThatFits:`

The file below demonstrates this. `_playgroundNode` is added using implicitHierarchyManagement (no call to `addSubnode:`) while `_resizeHandle` is manually laid out in `layout` and so requires a call to `addSubnode:`

[PlaygroundContainerNode copy.txt](https://github.com/facebook/AsyncDisplayKit/files/190601/PlaygroundContainerNode.copy.txt)

**Comment by wy19901227** [comment]
can offer a demo about this?

**Comment by hannahmbanana** [comment]
@wy19901227 - do you mean offer a demo about implicit hierarchy management? If so, checkout out PR #1457 - it uses implicit hierarchy management in the PhotoCellNode.m file. An official tutorial is coming soon.

Was your question answered? If so, shall we close this issue?

**Comment by wy19901227** [comment]
of course. thank you.
