### ISSUE TITLE
[ASDisplayNode] Possible Crash when Responding to Visibility Events Triggered by Dealloc

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1436]
In `-[ASDisplayNode dealloc]` we clear the visibility interface state. Updating that interface state will eventually call into client code, which may cause crashes if the client attempts to establish a reference to the deallocating node. 

In my case, ASCellNode deallocated, which sent .Invisible through the cell node callback, where my code called `setNeedsLayout`, which caused a crash inside ASDK when it attempted to establish a new reference to the node. As a workaround I no longer call `setNeedsLayout` on `.Invisible`. 

I don't really know the fix here, but I know it seems weird to clear that bit during dealloc, since before the node is deallocated it must have been removed from its hierarchy, right? How could a node that's visible be deallocated?

**Comment by appleguy** [comment]
Thanks for reporting!  https://github.com/facebook/AsyncDisplayKit/pull/1441
