### ISSUE TITLE
[Cocoapods] Debugging error output with Beta version of Cocoapods.

### ISSUE THREAD

**Issue by lengain** [facebook/AsyncDisplayKit#1445]
when I download the project and  run 'pod install',it throw error.
the release version of cocoaPods is 1.0.0.beta.4,it's rule has changed.here is the guide https://guides.cocoapods.org/using/the-podfile.html.

**Comment by appleguy** [comment]
@lengain please include the full error output. This does not happen on my machine. What is your version of cocoapods?

1.0.0beta6 is out, I believe, but there are many dozens of developers at Pinterest using the "production" version 0.39.

I appreciate you reporting this possible issue, but please also realize that it is not possible for me to make a change to fix this without having some concrete information, such as the actual error output from running the command more information about your configuration.

I suggest that you also try deleting the Pods directory, Podfile.lock, and the .xcworkspace file as I have noticed it is fairly common for Cocoapods to get into a corrupt state and require clearing these temporary caches (everyone of them is automatically regenerated by pod install).

**Comment by lengain** [comment]
@appleguy Thanks for you remind.I re-install my cocoaPods,it's works well.the version is 0.39. the podfile error was disappear.
I remember that I run the 'gem install cocoapods --pre'  in my teminal,then the cocoapods version is 1.0.0.beta.4  it is the reason I got into trouble.

**Comment by appleguy** [comment]
@lengain - I'm glad it is working for you now!
