### ISSUE TITLE
[ASCellNode] placeholderImage is not always staying onscreen long enough for my cell type

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#1448]
I have an `ASCellNode` subclass with overriden method:

```objc
- (UIImage *)placeholderImage {
    return [self imageWithColor:[UIColor redColor]]; // creates 1px UIImage of red.
}
```

In init:
```objc
        self.placeholderEnabled = YES;
        self.placeholderFadeDuration = 3;
```

As the nodes load, I still see my subnodes partially drawn. I expected to see a big red placeholder across the bounds of the cell.

**Comment by appleguy** [comment]
@fatuhoku this should be solvable. It sounds like there is likely an issue with the configuration of your node hierarchy or the mechanism you use to put it on screen. What version of the framework are you using, and can you share a variety of details about the rest of the configuration of the hierarchy such as some review debugging output and in initialization code? Feel free to attempt to reproduce this in any one of the example apps, as it will either show that it is easy to reproduce and allow the team to debug, or it will indicate that Application behavior may be related.

I would be eager to make any changes to the framework that ensure it behaves correctly with your current configuration, but until we understand what differences are required for it to operate, I have no way to produce a fix.

**Comment by hannahmbanana** [comment]
@fatuhoku - were you able to resolve this placeholder issue?

**Comment by fatuhoku** [comment]
@appleguy @hannahmbanana hmmm I no longer work on that part of the code... so I'm happy to close it until someone runs into this issue again :P cheers!
