### ISSUE TITLE
ASLayoutRangeType has no header documentation

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#1450]
I'm trying to configure `ASRangeController` behaviour as mentioned by @appleguy in his talks at NSLondon.  I come upon `ASCollectionView.setTuningParameters:forRangeMode:rangeType:` and I was thoroughly confused by `rangeType`. `rangeMode` I understand as various system-driven modes that hook up to whether the app is active, inactive or received memory warnings. I get that.

But this...

```objc
typedef NS_ENUM(NSInteger, ASLayoutRangeType) {
  ASLayoutRangeTypeDisplay,
  ASLayoutRangeTypeFetchData,
  ASLayoutRangeTypeCount
};
```

confuses me.

I remember from the NSLondon/NSSpain there's different working ranges — a 'display' range, a 'pre-render' range and a 'network' range. How does this map?

By intuition...

 - display range = `ASLayoutRangeTypeDisplay`
 - pre-render range = ?!?#?@#
 - network range = `ASLayoutRangeTypeFetchData`

Also, does ASDK set any sensible tuning parameter defaults for these types / modes? I must assume that everything's set to zero at the minute.

Would really appreciate it if someone could help me understand this.
Meanwhile I'll go experiment... Thanks!

EDIT: !!!!!!!!  I had no idea that setting the last element of an enum as a count of all the elements in the enum a convention... for the longest time I thought `ASLayoutRangeTypeCount` was actually a `RangeType`...

**Comment by hannahmbanana** [comment]
@fatuhoku - 
ASLayoutRangeTypeDisplay = render text, decode images
ASLayoutRangeTypeFetchData = download data - fetch is initiated in the `fetchData:` method of ASDisplayNode

Defaults are set in ASAbstractLayoutController.m

I'll make a note to update this in the 2.0 Documentation coming out soon. :)

**Comment by appleguy** [comment]
@fatuhoku: Thanks for asking this question. I believe that @lappp9 and @hannahmbanana have update the website docs to explain ASRangeController / Intelligent Preloading http://asyncdisplaykit.org/docs/intelligent-preloading.html

I'm going to close this issue, but feel free to reopen it, start another issue or ping us on slack if there is a way to improve the website documentation.
