### ISSUE TITLE
[ASCollectionView] tuningParameters doesn't appear to work

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#1451]
I'm using the following code in the hope to ensure a seamless scrolling experience but it's not quite working.

```objc
- (void)viewDidLoad {
    [super viewDidLoad];

    ASRangeTuningParameters tuningParametersForDisplay = (ASRangeTuningParameters) {
            .leadingBufferScreenfuls = 4.0,
            .trailingBufferScreenfuls = 2.0,
    };

    ASRangeTuningParameters tuningParametersForDataFetching = (ASRangeTuningParameters) {
            .leadingBufferScreenfuls = 6.0,
            .trailingBufferScreenfuls = 3.0,
    };

    [self.collectionView setTuningParameters:tuningParametersForDisplay forRangeType:ASLayoutRangeTypeDisplay];
    [self.collectionView setTuningParameters:tuningParametersForDataFetching forRangeType:ASLayoutRangeTypeFetchData];
}
```

I'm on an iPad 2.
Whenever I scroll down on my `ASCollectionView` (accessing the `leadingBuffer`, so to speak), the cells have clearly not been pre-rendered. Text appears a whole second afterwards (`asyncDisplay` is YES). Same story scrolling back up, to access the `trailingBuffer`.

What's going on?!

**Comment by appleguy** [comment]
@fatuhoku What version of ASDK are you using?  Can you print out a) the [[UIWindow keyWindow] recursiveDescription] for your app and attach a text file, and b) consider locally linking against this PR and screen-capturing the results in the simulator?

You might also try the newer API in +Beta, which specifies rangeMode.  Try setting the ranges for the Full modes.  cc @maicki

**Comment by fatuhoku** [comment]
I found that using `PINRemoteImage` with generous trailing and leading screenful values for `ASLayoutRangeTypeDisplay` does fetch and render cells in time — really good fun scrolling around trying to catch ASDK out actually!

The thing I want to know is, what really is `ASLayoutRangeTypeFetchData`?  Does entering this working range trigger downloads of network images?

**Comment by hannahmbanana** [comment]
@fatuhoku: Were you able to get an answer on this?

**Comment by appleguy** [comment]
@fatuhoku: are you still seeing an issue here? We have not seen any other reports of this or been able to reproduce it so we would appreciate any additional info.

**Comment by fatuhoku** [comment]
@appleguy Happy to close. No longer requiring this use case

**Comment by maicki** [comment]
Will close now, please reopen if necessary.
