### ISSUE TITLE
[ASCellNode] Possible Assertion Failure when Deleting Row While Onscreen

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1453]
I've hit an assertion failure when deleting rows from a table node that while they're visible: the assertion failure in `[ASDisplayNode didExitHierarchy]`. Note these cells are very very basic – they just have some static rasterized content. See stacktraces below:

<img width="2284" alt="screen shot 2016-03-28 at 3 06 11 pm" src="https://cloud.githubusercontent.com/assets/2466893/14091772/17e776c0-f4f7-11e5-84b0-87461196281f.png">
<img width="2284" alt="screen shot 2016-03-28 at 3 06 06 pm" src="https://cloud.githubusercontent.com/assets/2466893/14091774/185a7fbc-f4f7-11e5-9184-697b2ffcc8dc.png">
<img width="2284" alt="screen shot 2016-03-28 at 3 06 02 pm" src="https://cloud.githubusercontent.com/assets/2466893/14091773/18546d02-f4f7-11e5-922f-36c57e57cc8a.png">

**Comment by appleguy** [comment]
@Adlai-Holler I am fairly sure this was addressed with a subsequent change, but I may have not updated the git tag.  Can you make sure that it is resolved in master, and close this out if so? I can update the tag if the fix is complete.

**Comment by binchensjtu** [comment]
I also hit Assert failure in https://github.com/facebook/AsyncDisplayKit/blob/1.9.7.1/AsyncDisplayKit/ASDisplayNode.mm#L341

**Comment by Adlai-Holler** [comment]
I'm still observing this on the latest master =/

**Comment by Adlai-Holler** [comment]
Nope, I spoke too soon. Time really does fly around here! I believe you fixed it @appleguy

**Comment by Adlai-Holler** [comment]
@binchensjtu Do you also hit the assertion failure on the latest `master`?

**Comment by binchensjtu** [comment]
@Adlai-Holler I just update to master and have a try to verify this but turn out to be crashed in staticLayout when trying to set sizeRange with ASRelativeSizeRangeMakeWithExactCGSize... It is to later in my time. I will verify the assertion tomorrow.

**Comment by hannahmbanana** [comment]
@Adlai-Holler - are you observing it again? or did you reopen the issue to make sure it was resolved for @binchensjtu as well?

**Comment by binchensjtu** [comment]
@hannahmbanana I just update to latest master. The assertion failure and static layout crash has gone. It works fine for me now~thanks~

**Comment by Adlai-Holler** [comment]
The latter!
