### ISSUE TITLE
ASRenderingEngineDidDisplayScheduledNodes notification posted, but another ASTableView catches it

### ISSUE THREAD

**Issue by aphylotus** [facebook/AsyncDisplayKit#1460]
Hello,

  I have a ViewController containing an ASTableView, which is on top of the stack. Working fine. When poping this ViewController, it is not deallocated instantly (later by the autoreleasepool), need to figure out why.

  But during this, I have the upfront ASTableView, but also still the not-yet dealloacted ASTableView behind. Scrolling will post the ASRenderingEngineDidDisplayScheduledNodes notification to the default NotificationCenter, where then both ViewControllers will catch them.
  One TableView has 1 section, the other more. So sometimes the wrong one gets the wrong amount of sections, which will cause a crash -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0] in the ASFlowLayoutController findIndexPathAtDistance:fromIndexPath:] + 226.

  Any ideas ? 2 pop in my mind, add the reference to the table in the notification, so it may check if it is actually the needed receiver. Or a way to cancel the notification listener from the outside?

  Hope my case it is not too strange

  Thanks
  Tom

**Comment by appleguy** [comment]
We definitely need to fix this, and have planned improvements here for a while now.  Thank you for reporting!

Can someone tag Huy for his thoughts on the simplest initial fix?

**Comment by appleguy** [comment]
@aphylotus this use case is definitely not too strange, and I greatly appreciate the level of detail you were able to include in your report. The way this particular system is implemented is not up to the standard of the rest of the framework, but fortunately it should be pretty easy to improve and address this issue now that you have done the hard work of identifying it.

This will be a priority for the next release. as long as we can reproduce (necessary to be able to test).  If you have the time to do so, it would be helpful to try reproducing this in one of the many apps like examples/ASCollectionView that support pushing additional controllers to test lifecycle things such as this.  But we will investigate either way.

cc @nguyenhuy, @maicki

**Comment by appleguy** [comment]
This is being tracked by Ship task number 91.
