### ISSUE TITLE
[ASVideoNode] Mute only works if accessing through to the underlying .player object.

### ISSUE THREAD

**Issue by klivin** [facebook/AsyncDisplayKit#1468]
Hi there, incredible work guys!  I would like to use the muted boolean on ASVideoNode to mute and unmute an already playing video.

Muted only seems to be respected on initialization, but does not work if set while the video is already playing.

**Comment by MarvinNazari** [comment]
yeah this is a bug, a workaround is to change the `muted` property on player itself
```swift
videoNode.player.muted = true
```

**Comment by klivin** [comment]
Thank you!  Works like a charm :)

**Comment by appleguy** [comment]
@klivin @MarvinNazari @lappp9 thanks for the report and workaround! Does anyone have time to create a small PR to address the bug?

**Comment by lappp9** [comment]
Yeah I can look at it tonight or tomorrow!

**Comment by lappp9** [comment]
@klivin put in a PR for this today!

**Comment by appleguy** [comment]
@lappp9 - thanks for the PR!
@klivin - please try out the fix on master and let us know if you have any issues with it.
