### ISSUE TITLE
[Question] Getting acquainted with the layout APIs

### ISSUE THREAD

**Issue by tungvoduc** [facebook/AsyncDisplayKit#1470]
I created a node class which subclass ASScrollNode. If I initialize view controller using this custom node, it works fine, but if I replace it with an normal ASDisplayNode and then add the custom node into view controller's node, it does not work. This is how the code looks like:

```
customNode.frame = self.node.bounds
customNode.measureWithSizeRange(ASSizeRange(min: self.node.bounds.size, max: self.node.bounds.size))
customNode.backgroundColor = UIColor.redColor()
self.node.addSubnode(customNode)
```

I can see the red background color but when I log all subnodes' frames, they are all zeros. Does anyone know what is wrong here?

**Comment by appleguy** [comment]
@tungvoduc yes, it is necessary that your implementation provide a layout spec that fits which includes the sub node. Without this, there is no way for the sub node to understand what its size constraint is, so it cannot perform measurement.

If you think about how regular layout with UIKit works, it is the same thing. If you add a view as a sub view, but do not do anything with it in layoutSubviews, nothing will happen.

Let us know if you don't solve the issue, and please share additional details if you have trouble. Also please feel free to try out some of the example applications and compare them to your code. If you send me an email, I can invite you to the slack channel where many people can help.

**Comment by tungvoduc** [comment]
@appleguy I already provide a layout spec how to layout the subnodes by implementing function layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec

I managed to fix it, I just need to add customNode to view controller's node before doing anything else.
