### ISSUE TITLE
[Releases] Push new framework version to deploy fix in -[_ASDisplayView willMoveToSuperview:]

### ISSUE THREAD

**Issue by Mark-Henderson** [facebook/AsyncDisplayKit#1471]
The problem is this:

1. I load up values in an ASTableView
2. I then filter out some loaded values (via keyboard search) and reloadData() on the ASTableView
3. -[ASRangeController - (void)configureContentView:(UIView *)contentView forCellNode:(ASCellNode *)node] is called to setup the tableViewCell with the new node which subsequently calls -[_ASDisplayView willMoveToSuperview:] to remove filtered out _ASDisplayViews attached to the tableViewCell. Here self.keepalive_node = nil; is exectued causing -[ASDisplayNode dealloc] to execute. At that point the interfaceState of the node still has a the ASInterfaceStateVisible bit set so ASDisplayNodeAssert(_flags.synchronous || !ASInterfaceStateIncludesVisible(_interfaceState), @"Node should always be marked invisible before deallocating; interfaceState: %lu, %@", (unsigned long)_interfaceState, self); fails.

As a test I inserted [self.keepalive_node exitInterfaceState:ASInterfaceStateVisible]; in -[_ASDisplayView willMoveToSuperview:] as follows:

    - (void)willMoveToSuperview:(UIView *)newSuperview
    {
      // Keep the node alive while the view is in a view hierarchy.  This helps ensure that async-drawing views can always
      // display their contents as long as they are visible somewhere, and aids in lifecycle management because the
      // lifecycle of the node can be treated as the same as the lifecycle of the view (let the view hierarchy own the
      // view).
          UIView *currentSuperview = self.superview;
          if (!currentSuperview && newSuperview) {
                self.keepalive_node = _node;
          }
          else if (currentSuperview && !newSuperview) {
                [self.keepalive_node exitInterfaceState:ASInterfaceStateVisible];
                self.keepalive_node = nil;
          }
  
        ...

RESULT -> the crash no longer happens.

So it appears that that visible state needs to be reset somehow... not sure my test fix is the correct solution but it verified my suspicions. 

Cheers

**Comment by maicki** [comment]
@Mark-Henderson Hey, do you use version 1.9.7.1 or the latest master? Can you try it with the latest on master if this still happening.

**Comment by appleguy** [comment]
@Mark-Henderson sorry about this bug, I agree that it is an issue and I am nearly certain that the change you recommended here is already in master as of a week or so ago. We have not pushed out a new release, in part because there is an ambitious change that is still stabilizing in master. If you look at the revision that added the change to that file, pointing to that for now should be a very safe option

**Comment by Mark-Henderson** [comment]
@appleguy No need to apologize :) . I love what you guys have done with ASDK.... makes my life a bit more enjoyable.

@maicki I'll verify that this has been fixed within the next week. I've been blindsided by other priorities this week.

Thanks for the quick response and turnaround. 

Cheers,
...Mark

**Comment by Mark-Henderson** [comment]
@appleguy @maicki Hi Guys, your fix appears to do the trick.

Cheers,
...Mark
