### ISSUE TITLE
[ASCellNode] Is it possible to get the root UITableViewCell?

### ISSUE THREAD

**Issue by Arko4576** [facebook/AsyncDisplayKit#1487]
So for the last week I've been trying to port [MCSwipeTableViewCell](https://github.com/alikaragoz/MCSwipeTableViewCell) over to asyncdisplaykit. Now mcswipetableviewcell is a subclass of UITableViewCell that allows swiping of the UITableviewcell in a switch like manner. What I'm trying to do is switch it from being a subclass of UITableViewCell to a subclass of ASCellNode but consistently get errors of unrecognized selector sent to instance which I believe to be problem with UIAnimateWithDuration. To fix this I think reaching UITableViewCell through the ASCellNode may fix this problem does Asyncdisplaykit allow for this?

**Comment by appleguy** [comment]
@Arko4576 could you share the code that you were working on? Or at least the errors you're getting, such as the selector in question?

The API intentionally does not provide access to the underlying cell, although there has actually not ever been a report from the community that has required access to the cell, so it would be very interesting to me if you have discovered a case where it is necessary. In that event, I would be happy to consider adding it to the API. As you can imagine, it would not be a difficult addition

**Comment by Arko4576** [comment]
@appleguy I was able to simply use the view of the cell to get it working, thanks for everything only problem is that now you can't scroll when the gesture recognizer is active. See the library adds a `UIPanGestureRecognizer` to each cell for the swiping and when this is added it doesn't let you scroll the ASTableView is their away around this, maybe adding the gesture to a different part of the node? 

Also if anyone wants the working MCSwipetableViewCell for ASTableView I can post it.

**Comment by appleguy** [comment]
If you can post the code, it would definitely help me make the most useful suggestion on how you can insure scrolling works properly. You should be able to set up a failure requirement between the recognizer's, and especially the recognizer in your cell should be set up to fail if the amount of distance moved in the vertical direction is greater than a certain threshold, This threshold is often based on the distance traveled in the horizontal direction so that the total amount allowed vertically is increased as the travel horizontally is increased

**Comment by Arko4576** [comment]
[MCSwipeTableViewCell.m](https://gist.github.com/Arko4576/4e6b2f45501de4ac349f9a891948820a)
[MCSwipeTableViewCell.h](https://gist.github.com/Arko4576/d30a4b63177501e6f20f865f99c3645c)

So I posted them as Gists as not much is changed other a few calls to a UIView, I'll update the example project then upload the whole project as a proper branch when I get the chance. The library is a subclass of ASCellNode, the initialization of the Pan Gesture Recognizer happens in `initializer` other than that the only other useful function for you to look at `gestureRecognizerShouldBegin` where I receive the pan gesture. 

I've also tried setting a requiredToFail on the pan pan gesture but I don't think I'm accessing the right super node(you can see my attempt commented out inside `initializer`)

**Comment by benjaminhorner** [comment]
@appleguy : Hi. I HAVE come up with a case where I would like to access the underlying `UITableViewCell`. Although this will probably very rarely come up, it can come in handy when working with `UITableViewRowAction` and wanting to customize the appearance of it using something like:

```
for subview in self.UNDERLYING_CELL_VIEW.subviews {

        for subview2 in subview.subviews {

            if (String(subview2).rangeOfString("UITableViewCellActionButton") != nil) {

                for view in subview2.subviews {

                    if (String(view).rangeOfString("UIButtonLabel") != nil) {

                        if let label = view as? UILabel {

                            label.textColor = YOUR COLOUR
                        }

                    }
                }
            }
        }
    }
```
