### ISSUE TITLE
[GET HELP LIVE] Join ASDK's Slack channel!

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#1488]
We've just launched an ASDK slack channel so that you can chat live with other developers, get help on your layout, hear the latest announcements, etc. 

Email AsyncDisplayKit@gmail.com for an invite!

**Comment by CavalcanteLeo** [comment]
can you add me pls? 
leonardo@kiddolabs.com

I also will send you an email.

thank you

**Comment by appleguy** [comment]
The ASDK Slack channel is going strong. Email the above address for an invite!
