### ISSUE TITLE
UISwitch rendering

### ISSUE THREAD

**Issue by bradhouse** [facebook/AsyncDisplayKit#149]
I've been attempting to add a UISwitch to an ASDisplayNode, and it works correctly in the simulator but not on any of my devices (running either iOS 7.1.2 or 8.1.2)

The background of the switch is entirely black when rending on a device.

![cell](https://cloud.githubusercontent.com/assets/95760/5386736/3d7020be-811b-11e4-8ca2-6a7288208745.png)

During init:

    self.switchNode = [[SettingsSwitchNode alloc] initWithViewClass:[UISwitch class]];
    self.switchNode.backgroundColor = [UIColor whiteColor];

Of note, this happens during the construction of an ASCellNode. The SettingsSwitchNode is merely an ASDisplayNode subclass with an implementation of calculateSizeThatFits.

Currently at the conclusion of a layout pass (because I'm not sure where else in the workflow to currently put this):

    dispatch_async(dispatch_get_main_queue(), ^{
        UISwitch *s = (UISwitch *) self.switchNode.view;

        s.on = self.model.enabled;
        s.onTintColor = brand.theme.primaryColor;
        s.backgroundColor = [UIColor whiteColor];
    });

The setting clipsToBounds has no effect on device and neither does setting the background color for either the ASDisplayNode or the UISwitch itself.

So the first question is, am I correct setting up the ASDisplayNode to contain a UISwitch? 

And as a general question, where in the workflow for the display of an ASCellNode should interactions with the .view property of an ASDisplayNode take place?

I did try replacing UISwitch with a third-party component designed replicate UISwitch behaviour, and the same rendering effect occurs.

**Comment by iOSUser110** [comment]
please share the working UISwitch using ASDK code snippet
