### ISSUE TITLE
automaticallyAdjustsContentOffset does not offset at top

### ISSUE THREAD

**Issue by atainter** [facebook/AsyncDisplayKit#1491]
I've been working off the swift example project to develop my own prefetch at the head of an ASTableView. The content loads properly when I scroll up and the offset is adjusted accordingly. However, if I scroll to the top while content is still loading, after it finishes loading the content it jumps to the top as if the automaticallyAdjustsContentOffset=true property did not correctly offset for the change in data. 

Can anyone help?
Thanks,
Aaron

**Comment by hannahmbanana** [comment]
@atainter - thanks for reporting this! Could you try PR#1139 and share any other details? Like a screen video?

**Comment by atainter** [comment]
Sure, no problem. In this example I'm prepending the total number of items at the time they were created to the the text in each cell so that you can see when and where the cells are loaded for each fetch. 

Here you can see the content offset working as expected. The batch fetch happens while scrolling up,  adds data to the head, content is loaded in the bg, etc. ![](http://imgur.com/kJOdLo4)

In this example I hit the top of the list while it is still fetching. Content gets loaded at the head, but the tableview jumps to the top of the list. ![](http://imgur.com/13cpy7s)

**Comment by hannahmbanana** [comment]
@atainter: Very sorry for the delay in response! It's been an incredibly busy month for ASDK.

Were you able to figure out this issue? If not, would it be possible to put together a quick sample project demonstrating the bug? That would be the best bet for a quick response. :) That or posting on our Slack Channel (#1582).

**Comment by hannahmbanana** [comment]
@atainter: would you be willing to share the sample project so that I could take a look at this?

**Comment by atainter** [comment]
Hi @hannahmbanana , I figured out the issue awhile ago. Closing.

**Comment by appleguy** [comment]
@atainter thanks!  Was it ultimately a framework issue you patched around / used the PR mentioned?  Or something that was just reimplemented manually at the app level?  Mainly asking to know if we should land that PR, since I don't have a test case for it yet.  If you had tried it out, it would give me confidence to land it.

**Comment by atainter** [comment]
@appleguy I implemented it at app level. My priorities have shifted focus since then, so I haven't touched that code since late April. From what I remember I don't think I used that PR. I changed something in my implementation that solved the issue.
