### ISSUE TITLE
How does one get a player head or some sort of NSNotification regarding how far into a video a user is?

### ISSUE THREAD

**Issue by fresh83** [facebook/AsyncDisplayKit#1498]
The technical name escapes me, but im interested in adding a read only( as in the user will NOT be able to touch it or interfere with it)  player head below my videos ...something like whats on the bottom of youtube videos that shows you how much video you have left to watch via a bar that fills as you watch. 

I had such a thing prior to using this lib and while the improvements of using this lib are very clear, im a bit intimidated by it/unsure how to even begin to go about adding such a view.

**Comment by Eke** [comment]
@fresh83  ASVideoNode does not have such ability at this moment. if you are in AsyncDisplayKit slack channel, find me (emeskhi). I can give you my implementation of video player in ASCellNode

**Comment by hannahmbanana** [comment]
@fresh83 - come join us on Slack! To join, email AsyncDisplayKit@gmail.com asking for an invite.

**Comment by appleguy** [comment]
It would be great to support this bill team, but I believe you can implemented using the same techniques that you would if integrating with AVfoundation directly. Have you found that any of the necessary Apple APIs are obscured by the video node?

If that is the case, in other words if it blocks implementing it using whatever standard technique would be if  you were using the player layer directly, that is a definite problem that I would like to you resolved even before adding support for a convenience implementation.

**Comment by hannahmbanana** [comment]
@fresh83 - It appears this issue was resolved, if not feel free to re-open it.
