### ISSUE TITLE
Click on platform badge on README get directed to 404 not found on Github

### ISSUE THREAD

**Issue by devBrian** [facebook/AsyncDisplayKit#1500]

**Comment by appleguy** [comment]
@lappp9 , @hannahmbanana

**Comment by hannahmbanana** [comment]
@devBrian - thanks for pointing out the broken link. Where do you think it would be reasonable to point to? I updated it to go to AsyncDisplayKit.org, but if you have a better idea, I can change it.

**Comment by appleguy** [comment]
Appreciate the heads up!  Fixed in https://github.com/facebook/AsyncDisplayKit/pull/1502

**Comment by appleguy** [comment]
![screen shot 2016-04-10 at 12 25 08 am](https://cloud.githubusercontent.com/assets/565251/14408652/b5bbf9a6-feb2-11e5-87fd-40f591cd12b9.png)
