### ISSUE TITLE
[ASCellNode] Assertion on cell deallocation due visibility not being cleared

### ISSUE THREAD

**Issue by tomizimobile** [facebook/AsyncDisplayKit#1512]
Using my trusty test project (https://github.com/tomizimobile/ASDKSearchIssue) on the latest master (a6e66fa5d758d6675ddee982c128762e8a86a31a) I've managed to track down and find an issue with cell deallocation under a very specific circumstance, similar to https://github.com/facebook/AsyncDisplayKit/issues/1436. What I've found is when the tableView is deallocated when there's a section header only partially visible at the bottom of the table, it will crash. To reproduce, just go into the details page of the test project until you see a layout as described, and go back before scrolling. The test project generates random data each time the search view controller is loaded.

Here's a screenshot of an example layout that will cause a crash:

![screen shot 2016-04-11 at 4 57 09 pm](https://cloud.githubusercontent.com/assets/7967500/14442336/239f22ae-0007-11e6-8920-1fc2bc7c8278.png)

**Comment by appleguy** [comment]
@tomizimobile I was able to reproduce by typing, but I cannot get to the screenshot you are showing that has a back button.  Tapping the cells does nothing...

It would be much easier to debug with a one-shot reproduction like you describe, any tips?  cc @maicki FYI

**Comment by tomizimobile** [comment]
@appleguy Maybe you're using an older version of that sample project? The app now starts with a screen that just has a button to push a view controller. To reproduce I would just go back and forth until the UI is set up like that, it happens pretty quickly. I did forget to mention this was on an iPhone 6 - I'm sure with other devices, the UI layout might be harder to get randomly, so maybe playing around with hardcoding the data could yield this UI.

**Comment by tomizimobile** [comment]
@appleguy I updated my test project to use static data, and now the crash should be reproducible every time on an iPhone 6 device/simulator. All you need to do is press the button to push the view controller of names, and then press the back button.

**Comment by maicki** [comment]
@tomizimobile @appleguy Just yesterday we discovered what I think is the same problem and we should fix soon. I will add a link to the issue in here: #1569

As @tomizimobile it is 100% reproducible on an iPhone 6 simulator with the sample app in this issue or in #1569
