### ISSUE TITLE
[ASBatchContext] Regression: fetching will continually trigger in a loop after reaching end of content

### ISSUE THREAD

**Issue by smyrgl** [facebook/AsyncDisplayKit#1515]
I found this on 1701c47761a3e274b82cc0c77e6294cfa69612f6 (latest pull from master).

When scrolling an ASCollectionView in the batch fetching range when there are not any more results to pull I noticed that it will continue batch fetching in a continuous loop.  This is new behavior (previous versions always seem to have logic to know when a user was actually trying to rescroll the page down) but now just sitting there at the bottom of the page will cause it to loop and continually call for another batch fetch.

**Comment by appleguy** [comment]
@smyrgl thanks for the report - this is no doubt caused by the large recent change to this code, which we have an improvement for coming tomorrow.  However, I wasn't aware it was causing any bugs, so I will bump 1.9.7.2 to a version that doesn't include this commit.  You can rely on that for the time being.

cc @maicki

**Comment by appleguy** [comment]
@smyrgl ok, new 1.9.7.2 tag is up. Branch is 1.9.7.2_branch if you want to use that.

Sorry for the inconvenience, and thanks for the quick report.  We will fix-forward in master.

**Comment by smyrgl** [comment]
Thanks and I will be glad to use it...as soon as the Podspec version is fixed so I can submit it. :)

**Comment by smyrgl** [comment]
Ok so @maicki and I discussed this and I think we may want to hold off reverting this.  Yes this change causes a break with existing behavior but @maicki has sound reasoning for this change and I agree with the logic.  I would hold off on merging this in master until we've had a chance to explore it a bit further.

**Comment by appleguy** [comment]
It looks like this was comprehensively addressed. Great opportunity to close out this issue, thank you for making it possible @maicki !
