### ISSUE TITLE
[ASVideoNode] Even when muted - pauses external music player

### ISSUE THREAD

**Issue by mamalat** [facebook/AsyncDisplayKit#1516]
Should I use something like 
`AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryAmbient)`
as workaround, or should I make a PR and implement it into ASVideoNode?

**Comment by hannahmbanana** [comment]
@mamalat: Are you on the ASDK Slack channel? There are a couple of people actively working on ASVideoNode right now. It might be good to ask them if they've run into this problem.

**Comment by smyrgl** [comment]
I use the .MixWithOthers option and it works fine.

```Swift
        // Set to mix the shared audio session
        do {
           try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, withOptions: AVAudioSessionCategoryOptions.MixWithOthers)
        } catch {
            DDLogWarn("Failed to configure shared AVAudioSession")
        }

```

**Comment by hebertialmeida** [comment]
@smyrgl This fixes partially. Using `.MixWithOthers` will not stop secondary audio when do you unmute the video.

**Comment by hannahmbanana** [comment]
@hebertialmeida: is this expected behavior? For tracking purposes, I'm trying to figure out if this is a bug or a community question.

**Comment by hebertialmeida** [comment]
@hannahmbanana At list for me the expected behaviour is to keep a music playing when the video on ASVideo node is muted, only stop the secondary music when unmute the video.

**Comment by appleguy** [comment]
@mamalat: Thanks for posing this question! @hebertialmeida @smyrgl @hannahmbanana: Thanks for chiming in!

It seems that ASVideoNode shouldn’t make assumptions about the audio session needed and that it should be left up to the developer. I'm going to close out this issue, however, I encourage you to continue the discussion on the #asvideonode channel on ASDK's Slack (#1582).
