### ISSUE TITLE
Crash with ASVideoNode

### ISSUE THREAD

**Issue by CavalcanteLeo** [facebook/AsyncDisplayKit#1517]
Each cell of a tableview has an ASVideoNode, and this tableview has many cells.

All the time I scroll the  tableView, my app crashes and only shows this error:

*** -[ASVideoNode setAsset:]: message sent to deallocated instance 0x12d99d400

Looks like the app crashes after I request more data from the server, and reload the table view

**Comment by Eke** [comment]
@CavalcanteLeo can you share your implementation code?

**Comment by CavalcanteLeo** [comment]
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
               _videoNode = [[ASVideoNode alloc] init];
               _videoNode.delegate = self;
               _videoNode.frame = self.bounds;
               _videoNode.shouldAutoplay = YES;
               _videoNode.shouldAutorepeat = YES;
               _videoNode.backgroundColor = [UIColor clearColor];
               _videoNode.asset = [AVAsset assetWithURL:urlVideo];
               _videoNode.muted = YES;
        
               soundIndicator = [VYPlayIndicator new];
               soundIndicator.frame = CGRectMake(10.f, self.bounds.size.height - 30.f, 20.f, 20.f);
               soundIndicator.color = [UIColor whiteColor];
               [soundIndicator animatePlayback];
    
               dispatch_async(dispatch_get_main_queue(), ^{
                   [_videoView addSubnode:_videoNode];
                   [_videoView.layer addSublayer: soundIndicator];
               });
           });

**Comment by CavalcanteLeo** [comment]
The crash happens when i change the array, reload tableView and scroll the tableview

**Comment by Eke** [comment]
i don't think it is AsyncDisplayKit issue, you are trying to set asset of ASVideoNode which is not in memory anymore, so maybe it's problem in your code logic.

It is hard for me to think about what is causing this without seeing whole logic of your ViewController

**Comment by appleguy** [comment]
Thanks for reporting this. Unfortunately it does appear like your code is calling a method that is not defined on the video node, which typically will only happen if there is some other memory management error that is allowing the memory address that you're calling on to be a different object than you expect.

Try using instruments with the "Zombie" option -- it should help you find a bug like this.
