### ISSUE TITLE
Crashes with ASDisplayLayer

### ISSUE THREAD

**Issue by tungvoduc** [facebook/AsyncDisplayKit#1520]
I have a lot crashes with ASDisplayLayer when pushing to another view controller which has ASCollectionNode or ASTableNode. Here is the stack trace:
![stack](https://cloud.githubusercontent.com/assets/6437873/14469689/9fe02772-00ee-11e6-81f1-2b59965c24b8.png)

**Comment by maicki** [comment]
@tungvoduc Would you be able to provide some sample that would help to figure out the problem?

**Comment by appleguy** [comment]
Have never seen one like this.  What version of the framework are you using?  Please try with 1.9.7.2.

If you can also grab the full "bt all" in the debugger and post that, it would be appreciated.

**Comment by tungvoduc** [comment]
It happens only 2% of the time. But I already managed to fix by deleting some observer in the view controller which is not related to AsyncDisplayKit.
