### ISSUE TITLE
Podfile is missing target for Samples

### ISSUE THREAD

**Issue by MatheusGodinho** [facebook/AsyncDisplayKit#1531]
All podfiles from examples directory projects are missing the target to install and I get that error.

> [!] The dependency `AsyncDisplayKit (from `../..`)` is not used in any concrete target.

**Comment by hannahmbanana** [comment]
@MatheusGodinho - if you use a stable version of Cocoapods, does that fix your issue?

I believe I saw this being discussed on the ASDK Slack today. If you want to join the discussion over there, email AsyncDisplayKit@gmail.com for an invite.
