### ISSUE TITLE
[ASTextNode] truncationAttributedString does not work in 1.9.7.2

### ISSUE THREAD

**Issue by munch1324** [facebook/AsyncDisplayKit#1533]
I tested by running examples/Kittens, and adjusting the _textNode with the following:

```
  _textNode.truncationAttributedString = [[NSAttributedString alloc] initWithString:@"--- ---" attributes:nil];
  _textNode.maximumNumberOfLines = 2;
```

I was able to find the last working SHA: 1ec1957b44456b93034390cff4f42c29ce165e2a. 

The current bug is that the truncationAttributedString is not shown at all, and instead the text is clipped.

**Comment by gudjao** [comment]
+1

**Comment by maicki** [comment]
@munch1324 @gudjao Hey, this issue seems to be fixed on master. I will close this issue for now and please reopen in case it's not fixed for you.
