### ISSUE TITLE
Hi, i want a Demo.

### ISSUE THREAD

**Issue by WildDylan** [facebook/AsyncDisplayKit#1542]
Hi, i want a demo for `ASMultiplexImageNode`, i want use it but too many problems. can you help me?  or  who can give me a demo for use it . thanks.

**Comment by appleguy** [comment]
@WildDylan I would love to help! Send me a quick email, and you can also join our slack room.  asyncdisplaykit@gmail.com

The network image node is more powerful than it looks, supporting things like Progressive JPEG and also animated GIF.  So, it is actually quite rare to find a user that needs the multiplex node, but if you do there are several people in the community who have a lot of experience with it.

**Comment by WildDylan** [comment]
@appleguy  thx, my email, 13301051937@163.com. i love the `AsyncDisplayKit` framework, can i be the members?

**Comment by appleguy** [comment]
Sent you an invite, hope the sign-up process for slack goes smoothly!

**Comment by WildDylan** [comment]
@appleguy ok. thx.
