### ISSUE TITLE
setShouldRasterizeDescendant = YES and it's background is black

### ISSUE THREAD

**Issue by yufenglv** [facebook/AsyncDisplayKit#155]
Hello, when I set Node's shouldRasterizeDescendant equals to YES, and later set Node's frame and it's origin is not (0, 0), for example, the frame of the node is  (10, 10, width, height), then the offset area is black.

**Comment by bensarz** [comment]
@yufenglv I'm experiencing the same problem, have you found a solution to this (except setting `shouldRasterizeDescendant` to `NO`?

**Comment by appleguy** [comment]
@yufenglv & @bensarz , the offset issue is fixed.  I've tested this feature and haven't found a bug in the master version — so please do file a new task if you encounter an issue.  It would be very helpful to the project!
