### ISSUE TITLE
ASTableNode crash -[ASDisplayNode dealloc]

### ISSUE THREAD

**Issue by hebertialmeida** [facebook/AsyncDisplayKit#1569]
I have a ASViewController with ASTableNode, when navigating back to previous controller the app crashes.
![screen shot 2016-04-20 at 9 47 16 am](https://cloud.githubusercontent.com/assets/103670/14679405/19fc9674-06f0-11e6-97fd-7df76cdf14ba.png)

Here is a sample project:
https://github.com/hebertialmeida/ASDKCrash

Open the project > Tap on Settings > Back to profile and Crash.

Any help would be nice.

------

**Update:** @maicki Found that the problem is related to `ASViewController`.

------

**Update2:** The problem only happen when the ASTableNode is defined with Style Grouped `ASTableNode(style: .Grouped)`, probably not related to `ASViewController `.

**Comment by yichungwang** [comment]
I'm having the same issue too, for now I just remove ASTableView from superview in viewwilldisappear.

**Comment by maicki** [comment]
@hebertialmeida @yichungwang Can you two please verify if you have that problem on the latest master?

**Comment by hebertialmeida** [comment]
@maicki Yes, seems that it fixed for me.
