### ISSUE TITLE
[ASCellNode] didRelayoutFromOldSize:toNewSize: Doesn't Use Correct Values When Layed Out Off-Main

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1574]
Looks like the sweet auto-table-row-height update behavior may have suffered a regression =/. It used to work very well, but in 1.9.7.2 it's stopped working.

To reproduce on current master dd4853b, use the Kittens sample app. Replace `-[KittenNode toggleImageEnlargement]` implementation:

```objectivec
- (void)toggleImageEnlargement
{
  _isImageEnlarged = !_isImageEnlarged;
  [self setNeedsLayout];
}
```

with

```objectivec
- (void)toggleImageEnlargement
{
  _isImageEnlarged = !_isImageEnlarged;
  dispatch_async(dispatch_get_global_queue(QOS_CLASS_DEFAULT, 0), ^{
    [self setNeedsLayout];
  });
}
```

Within 1-3 taps I'll usually see the cell fail to update its height to match the new layout. Instead of calling `- didRelayoutFromOldSize:toNewSize:` just once, with the old and new values, the cell node will call it twice, first with the old value twice, then with the new value twice, so `sizeChanged` is never determined as true.

**Comment by hebertialmeida** [comment]
Same is happening for me on ASCollectionNode, the some Items are overlapping. 

The issue only seemed to affect ASCollectionViews that had cells that needed to change size after an image was loaded.

It happen specifically on Items that I have a ASNetworkImage with a ratio 0.5, when the image is loaded I call `self.setNeedsLayout()` from ASNetworkImage delegate `imageNode(imageNode: ASNetworkImageNode, didLoadImage image: UIImage)`

Seems that `self.setNeedsLayout()` update the collection item but not recalculate other Items position.

**Comment by Adlai-Holler** [comment]
@hebertialmeida If you have time, could you see if using the PR branch fixes the issue?

**Comment by appleguy** [comment]
@hebertialmeida let us know!

**Comment by hebertialmeida** [comment]
@appleguy It is working for me on last master. Thanks 👍
