### ISSUE TITLE
[GET HELP LIVE] Join ASDK's Slack channel!

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#1582]
Bumping this back up to the top. :)

Join 200+ AsyncDisplayKit developers on Slack for real-time debugging, the latest updates, and asynchronous banter. 

Signup at http://asdk-slack-auto-invite.herokuapp.com or email AsyncDisplayKit(at)gmail.com to get an invite!

**Comment by clooth** [comment]
Just a thought, but why not have a slack invite bot hosted on heroku for example?

**Comment by hannahmbanana** [comment]
@clooth - thanks for the idea! I have it up and running now with a badge on the README.md. :)

**Comment by hannahmbanana** [comment]
http://asyncdisplaykit.org/slack.html
