### ISSUE TITLE
[Question] about the website documentation on using ASCollectionNode inside ASViewController

### ISSUE THREAD

**Issue by nickvelloff** [facebook/AsyncDisplayKit#1588]
In http://asyncdisplaykit.org/docs/containers-ascollectionnode.html#replace-uicollectionviewcontroller-with-asviewcontroller

The following can't be correct (as I'm learning this system)t:
<img width="686" alt="screenshot 2016-04-25 02 34 58" src="https://cloud.githubusercontent.com/assets/885369/14779730/6579d020-0a8e-11e6-8b36-a1dd60ee624c.png">

**Comment by hannahmbanana** [comment]
@nickvelloff: thanks for reviewing our new documentation! It is still a work in progress, so expect a few hiccups. :)

The sentence before the code looks correct. I could probably make it more clear that `initWithNode:` is the ASViewController's designated initializer. This is the strategy for using an ASCollectionNode with an ASViewController, but it is also possible to use an ASCollectionNode without managing it with an ASViewController. 

Is it an issue with the Swift code? I am not familiar with Swift syntax. cc: @lappp9

**Comment by appleguy** [comment]
@nickvelloff - happy to help, could you clarify your question?  The designated initializer for ASVC is initWithNode - the code you have looks largely correct, but I'm not sure how to call that initializer in Swift.  Wouldn't it be super.initWithNode(node: collectionNode) ?

cc @nguyenhuy, if you want to check my Swift here.

If you're not on our Slack yet, please join and we'd love to collaborate with you live!  Just email me at asyncdisplaykit@gmail.com - to request an invite.

**Comment by maicki** [comment]
@appleguy It's should be this way:

```swift
init(coordinates: CLLocationsCoordinate2D) {
        let flowLayout     = UICollectionViewFlowLayout()
        let collectionNode = ASCollectionNode(collectionViewLayout: flowLayout)
        
        super.init(node: collectionNode)
        
        flowLayout.minimumInteritemSpacing  = 1
        flowLayout.minimumLineSpacing       = 1
}
```

**Comment by lappp9** [comment]
@maicki Isn't the first version what the docs has?

And yeah, the initializer should be `super.init(node: whateverNode)`  

Which is actually pretty cool, considering the objc version is `[super initWithNode:whateverNode]`

**Comment by lappp9** [comment]
Oh! The `func initWithCoordinates(...)` part is wrong! My bad, i'll update it real quick.

**Comment by appleguy** [comment]
Landed https://github.com/facebook/AsyncDisplayKit/pull/1589, @nickvelloff thanks!  Let us know if this looks better.

**Comment by nickvelloff** [comment]
@lappp9 That is the part I'm referencing 👍 
Thanks all! 
I'm trying to migrate my UICollectionView to ASDK entirely (parts use it, but want to go full hierarchy). Some things in the docs referenced a file in an example project "ASDKgram" that no longer exists.

Is there somewhere you could point me to an example of the best way to handle this with the latest ASDK? If not I'll just continue to read the docs, just making sure I'm not missing something. 

Thanks all!

**Comment by nickvelloff** [comment]
@appleguy Looks great, very clear. Thanks.
I'm checking out `ASCollectionView` as an example project. 
Just wrapping my head around the differences in `UICollectionView` and `ASCollectionNode`. 

I'll log more issues if see anything in the docs (or issue a PR if I'm feeling confident 😄 )

**Comment by appleguy** [comment]
@nickvelloff: PRs are always welcome. :)
