### ISSUE TITLE
[ASMultiplexImageNode] skip image identifiers that cause an error

### ISSUE THREAD

**Issue by andyscott** [facebook/AsyncDisplayKit#159]
Can we add a flag to ASMultiplexImageNode so that it skips image identifiers that cause a download error? The default behavior is for the loading to completely stop.

To get around this, I do the following in my delegate:

    public func multiplexImageNode(imageNode: ASMultiplexImageNode!, didFinishDownloadingImageWithIdentifier imageIdentifier: AnyObject!, error: NSError!) {
        if error != nil {
            imageNode.imageIdentifiers = imageNode.imageIdentifiers.filter { (_imageIdentifier) -> Bool in
                return !_imageIdentifier.isEqual(imageIdentifier)
            }
        }
    }

It seems like this might be better handled in ASMultiplexImageNode's `_finishedLoadingImage`.

**Comment by andyscott** [comment]
I'm reopening this since it introduced another bug and the merge has been reverted in #302. I'll get around to fixing the new bug and issue a new PR.

**Comment by appleguy** [comment]
@andyscott thank you for proactively reporting this and reopening the issue. It is been quite some time, and we now have a completely new image library available, which does work with Multiplex if you initialize it with a simple alloc/init.

I believe it should resolve this issue, but if you were still an active user of the framework, please check it out when you have a chance. Send me an email with your results, and I can also send you an invite to are slack channel if you would like! One of the members of the channel is the author of both the image library itself and its integration with ASDK :)

**Comment by andyscott** [comment]
@appleguy No worries!

I'm not actively doing any iOS development, at least for the time being. That being said, I still follow this project (even encouraging others at a Scala conference in Philly to give it a whirl). If the Slack channel invitation stands, I'll take you up on it.
