### ISSUE TITLE
[ASPagerNode] Is there a correct way to access the child view controllers?

### ISSUE THREAD

**Issue by dermotos** [facebook/AsyncDisplayKit#1598]
All in the title really.

    ASCellNode *cellNode = [ASCellNode alloc] initWithViewControllerBlock:^UIViewController * _Nonnull{
        UIViewController *myViewController = [UIViewController new];
        return myViewController;
    } didLoadBlock:nil];

How does one access `myViewController` from the parent ASPagerNode, in the example above?

**Comment by hannahmbanana** [comment]
@dermotos: Great question!

There isn't currently an API to access the child view controller. There are a few ways to get around this - for example, using a delegate - depending on what you are trying to do. If you are able to share more details or give an example from another app, I'm sure we can figure out a simple solution that doesn't require changing your app design. 

Alternatively, the authors of the framework are usually happy to consider adding accessors if you can give them a good enough reason to. :)

Have you joined the ASDK Slack channel? Might be a good to see what other developers there do.

**Comment by dermotos** [comment]
Haven't joined the channel, but I will! 
I'm implementing new view controllers that require this, I'm sure i'll figure out a reasonably elegant solution, just wanted to be sure I didn't miss any undocumented official approach!
