### ISSUE TITLE
[ASTextNode] placeholderImage throws invalid context if calculatedSize is CGSizeZero

### ISSUE THREAD

**Issue by weibel** [facebook/AsyncDisplayKit#1601]
We have had a situation where placeholderImage would be called when calculatedSize is zero. In this case it throws a lot of invalid context errors.

**Comment by hannahmbanana** [comment]
@weibel: Thanks for reporting this! I'm sorry it took us so long for us to reply. Have you joined our Slack Channel (#1582)? We're usually able to respond more quickly over there. :)

Would it be possible to include a stack trace?

**Comment by pixel4** [comment]
@hannahmbanana I have a stack trace for this. I've been seeing the same thing in my project while debugging a crash not related to this
![Invalid context + crash with visibleRanges](https://cloud.githubusercontent.com/assets/38343/15133706/40c9f006-161a-11e6-9908-7ec7c996a131.png)

**Comment by hannahmbanana** [comment]
@weibel: @pixel4: Thank you both for reporting this! Levi added a check for this last month. Please let us know if you see this again.
