### ISSUE TITLE
[ASStackLayoutSpec] Baseline Alignment + Space Between Justification Does Not Space Correctly

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#1604]
When using a stack layout spec, when `.BaselineFirst` alignment is used in combination with `.SpaceBetween` justification, the spacing isn't correct – the justification is instead like `.Start`. 

Here's a reduced case: https://github.com/Adlai-Holler/ASDKBaselineSpaceBetweenIssue

| .SpaceBetween + .Start | .SpaceBetween + .BaselineFirst |
| --- | --- |
| ![img_1537](https://cloud.githubusercontent.com/assets/2466893/14872164/8b36f164-0c9e-11e6-9a8d-9a69b9a68d3e.PNG) | ![img_1536](https://cloud.githubusercontent.com/assets/2466893/14872165/902f1c00-0c9e-11e6-9d10-98dc2a804b51.PNG) |

**Comment by appleguy** [comment]
cc @rcancro

**Comment by hannahmbanana** [comment]
This issue will be resolved by #2892.
