### ISSUE TITLE
Static Layout Spec, ASSizeRanges and other layout related thoughts

### ISSUE THREAD

**Issue by lappp9** [facebook/AsyncDisplayKit#1609]
Right now, to constrain a certain text node to a containing area of 1/3rd the height of the screen you have to do something like this:

```
CGFloat height = [UIScreen mainScreen].bounds.size.height/3.0;
ASStaticLayoutSpec *staticLayoutSpec = [ASStaticLayoutSpec staticLayoutSpecWithChildren:@[descriptionTextInsetSpec]];
  
descriptionTextInsetSpec.sizeRange = ASRelativeSizeRangeMake(
                                                ASRelativeSizeMake(
                                                        ASRelativeDimensionMake(ASRelativeDimensionTypePercent, 1.0),
                                                        ASRelativeDimensionMake(ASRelativeDimensionTypePoints, height)),
                                                ASRelativeSizeMake(
                                                        ASRelativeDimensionMake(ASRelativeDimensionTypePercent, 1.0),
                                                        ASRelativeDimensionMake(ASRelativeDimensionTypePoints, height)));

```

1) What if you could set the max and min sizes separately on these static layout specs?  Either a method like `-setMaxSize:` and `-setMinSize:` or a property so people can just alter one of them?  I don’t know how easy that would be, but it seems like it would be a lot less tedious to deal with.

2) What if we just used CGSizes for these size ranges and then used ASRelativeSizeRange and ASRelativeSize internally if necessary? I feel like it would feel a lot more approachable in general.

3) What if the "relative dimensions" were only used when we actually wanted something to be "relative" to something else?  Maybe we could do this using functions for individual widths and heights that takes a percentage instead of having to explicitly say which thing you're dealing with.

So instead of the whole ASRelativeSizeRangeMake deal shown above we could do.

```
descriptionTextInsetSpec.maxSize = CGSizeMake(ASRelativeWidth(1.0), height);
``` 

I don't know if that ASRelativeWidth would have all the info it would need to return the correct width, but if so, it seems like this provides about the same amount of information but feels quite a bit more accessible?  Like I said, I don't know much about the layout system under the hood so maybe this is impossible?

**Comment by appleguy** [comment]
@lappp9 we do have a Ship task filed to revisit ASDimension, as well as both sizeRange and preferredFrameSize, as blocking elements of 2.0.  The main problem is staffing, which we've needed to allocate to shorter term urgencies rather than these improvements (despite their very high importance and relatively modest scope).

cc @maicki, @nguyenhuy, @levi, @rcancro I think it is important for our work at Pinterest - and by extension, the entire community - to address this in the next few weeks.  It also affects the tutorial that @lappp9 is writing, and has held the launch of in order to wait for us to make these API revisions.

**Comment by hannahmbanana** [comment]
@lappp9: @maicki is currently working creating a new & improved Layout API for the 2.0 release that was specifically designed to address the top 5 "pain points" of the current Layout API, one of which is the ASRelativeDimension confusion. :) 

I believe Michael is currently considering something similar to this line of thought. Once he has a PR up, I'm sure he'd appreciate your feedback.
