### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sushilthe** [facebook/AsyncDisplayKit#1614]
The link to http://asyncdisplaykit.org/docs/automatic-layout.html referenced from http://asyncdisplaykit.org/docs/philosophy.html is broken. The link is under the **Asynchronous Performance Gains Section** and can be visited by clicking the **correctly** link.

**Comment by sushilthe** [comment]
The link to http://asyncdisplaykit.org/docs/automatic-layout.html referenced from http://asyncdisplaykit.org/docs/philosophy.html is broken. The link is under the **Asynchronous Performance Gains Section** and can be visited by clicking the **examples/ASDKgram** text.

**Comment by sushilthe** [comment]
The link to http://asyncdisplaykit.org/docs/automatic-layout.html referenced from http://asyncdisplaykit.org/docs/philosophy.html is broken. The link is under the **A Great App Experience for All Users** sub-section **A Great Developer Experience** and can be visited by clicking the **examples/ASDKgram** link.

**Comment by maicki** [comment]
cc @hannahmbanana
