### ISSUE TITLE
addSubnode not working in ASCellNode

### ISSUE THREAD

**Issue by mengheangrat** [facebook/AsyncDisplayKit#1615]
`let node = ASTextCellNode()
 let text = ASTextNode()
 node.addSubnode(text)`

**Comment by maicki** [comment]
@mengheangrat Can you please provide a sample project what is not working or at least write some more information about that. Thanks!

**Comment by mengheangrat** [comment]
` func tableView(tableView: ASTableView, nodeForRowAtIndexPath indexPath: NSIndexPath) -> ASCellNode {
        // Should read the row count directly from table view but
        // https://github.com/facebook/AsyncDisplayKit/issues/1159
        let rowCount = self.tableView(tableView, numberOfRowsInSection: 0)
        
        if state.fetchingMore && indexPath.row == rowCount - 1 {
            return TailLoadingCellNode()
        }
        
        let node = ASTextCellNode()
        let text = ASTextNode()
        //    node.textAttributes =
        //        node. = textDetail[indexPath.row]
        text.attributedString = readDataHtml("<p>ជារឿងមិនគួរអោយជឿដែរថាតួសម្តែងប្រុសក្នុងខ្សែភាពយន្តធំៗជំនាន់ឆ្នាំ 90 មានសម្រស់ស្រស់ស្អាតដែលបានធ្វើអោយនារីៗមួយចំនួនទូទាំងពិភពលោកបាក់ចិត្តទៅលើ ទោះបីជាមកដល់ជំនាន់ឥលូវក៏មានសម្រស់មិនចាញ់កាលពីក្មេងដែរ។ ជាក់ស្តែងយើងទៅមើលរូបភាពខាងក្រោមនេះ គឺរូបភាពជាតួសម្តែងទាំងប្រុសទាំង 12 រូប ដែលលើកយកមកប្រៀបធៀបកាលពីជំនាន់ឆ្នាំ 90 និងមកដល់បច្ចុប្បន្ននេះ ប៉ុន្តែមានតារាខ្លះខ្ញុំជឿថាលោកអ្នកប្រាកដជាមិនសូវស្គាល់នោះទេ ហើយបើនិយាយពីមុនតារាមុនដំបូងគេវិញគឺលោក <span style=\"font-weight: 700; text-align: center; line-height: 1.42857;\">Leonardo DiCaprio </span><span style=\"text-align: center; line-height: 1.42857;\">ដែលលោកអ្នកស្គាល់គាត់ភាគច្រើនជាតួឯកក្នុងរឿង កប៉ាល់ទីតានិក </span><span style=\"line-height: 1.42857;\">៖ </span></p><p style=\"text-align: center; \"><br><font color=\"#FA870D\">Leonardo DiCaprio</font><br></p><p style=\"text-align: center; \">")
//        text.text = "pppppppppppppp"
//        node.textAttributes = "ddd"
//        node.addSubnode(text)
        
        //            String(format: "<p>ជារឿងមិនគួរអោយជឿដែរថាតួសម្តែងប្រុសក្នុងខ្សែភាពយន្តធំៗជំនាន់ឆ្នាំ 90 មានសម្រស់ស្រស់ស្អាតដែលបានធ្វើអោយនារីៗមួយចំនួនទូទាំងពិភពលោកបាក់ចិត្តទៅលើ ទោះបីជាមកដល់ជំនាន់ឥលូវក៏មានសម្រស់មិនចាញ់កាលពីក្មេងដែរ។ ជាក់ស្តែងយើងទៅមើលរូបភាពខាងក្រោមនេះ គឺរូបភាពជាតួសម្តែងទាំងប្រុសទាំង 12 រូប ដែលលើកយកមកប្រៀបធៀបកាលពីជំនាន់ឆ្នាំ 90 និងមកដល់បច្ចុប្បន្ននេះ ប៉ុន្តែមានតារាខ្លះខ្ញុំជឿថាលោកអ្នកប្រាកដជាមិនសូវស្គាល់នោះទេ ហើយបើនិយាយពីមុនតារាមុនដំបូងគេវិញគឺលោក <span style=\"font-weight: 700; text-align: center; line-height: 1.42857;\">Leonardo DiCaprio </span><span style=\"text-align: center; line-height: 1.42857;\">ដែលលោកអ្នកស្គាល់គាត់ភាគច្រើនជាតួឯកក្នុងរឿង កប៉ាល់ទីតានិក </span><span style=\"line-height: 1.42857;\">៖ </span></p><p style=\"text-align: center; \"><br><font color=\"#FA870D\">Leonardo DiCaprio</font><br></p><p style=\"text-align: center; \">", indexPath.section, indexPath.row)
        node.addSubnode(text)
        
        return node
    }
`

**Comment by mengheangrat** [comment]
` func tableView(tableView: ASTableView, nodeForRowAtIndexPath indexPath: NSIndexPath) -> ASCellNode {
        let rowCount = self.tableView(tableView, numberOfRowsInSection: 0)
        if state.fetchingMore && indexPath.row == rowCount - 1 {
            return TailLoadingCellNode()
        }
        let node = ASTextCellNode()
        let text = ASTextNode()
        text.attributedString = readDataHtml("<p>ជារឿងមិនគួរអោយជឿដែរថាតួសម្តែងប្រុសក្នុងខ្សែភាពយន្តធំៗជំនាន់ឆ្នាំ 90 មានសម្រស់ស្រស់ស្អាតដែលបានធ្វើអោយនារីៗមួយចំនួនទូទាំងពិភពលោកបាក់ចិត្តទៅលើ ទោះបីជាមកដល់ជំនាន់ឥលូវក៏មានសម្រស់មិនចាញ់កាលពីក្មេងដែរ។ ជាក់ស្តែងយើងទៅមើលរូបភាពខាងក្រោមនេះ គឺរូបភាពជាតួសម្តែងទាំងប្រុសទាំង 12 រូប ដែលលើកយកមកប្រៀបធៀបកាលពីជំនាន់ឆ្នាំ 90 និងមកដល់បច្ចុប្បន្ននេះ ប៉ុន្តែមានតារាខ្លះខ្ញុំជឿថាលោកអ្នកប្រាកដជាមិនសូវស្គាល់នោះទេ ហើយបើនិយាយពីមុនតារាមុនដំបូងគេវិញគឺលោក <span style=\"font-weight: 700; text-align: center; line-height: 1.42857;\">Leonardo DiCaprio </span><span style=\"text-align: center; line-height: 1.42857;\">ដែលលោកអ្នកស្គាល់គាត់ភាគច្រើនជាតួឯកក្នុងរឿង កប៉ាល់ទីតានិក </span><span style=\"line-height: 1.42857;\">៖ </span></p><p style=\"text-align: center; \"><br><font color=\"#FA870D\">Leonardo DiCaprio</font><br></p><p style=\"text-align: center; \">")
        node.addSubnode(text)
        return node
    }
`

**Comment by mengheangrat** [comment]
I want to add textview using ASTextNode() add ASTextNode()

**Comment by maicki** [comment]
@mengheangrat Just use the ASTextCellNode directly you don't need to add an ASTextNode into ASTextCellNode:

```swift
func tableView(tableView: ASTableView, nodeForRowAtIndexPath indexPath: NSIndexPath) -> ASCellNode {
  let node = ASTextCellNode()
  node.text = "Some Text"
  return node
}
```

**Comment by mengheangrat** [comment]
I need to use attributedString but ASTextCellNode() does not have that property coz I have to render html .

**Comment by maicki** [comment]
@mengheangrat It does ... just set the `textAttributes` on the ASTextCellNode otherwise as said add the ASTextNode to a ASCellNode and layout the ASTextNode within the ASCellNode

**Comment by mengheangrat** [comment]
Could you give a sample? 
Thx for you kindness :)

**Comment by mengheangrat** [comment]
`        node.textAttributes = readDataHtml("<p>ជារឿងមិនគួរអោយជឿដែរថាតួសម្តែងប្រុសក្នុងខ្សែភាពយន្តធំៗជំនាន់ឆ្នាំ 90 មានសម្រស់ស្រស់ស្អាតដែលបានធ្វើអោយនារីៗមួយចំនួនទូទាំងពិភពលោកបាក់ចិត្តទៅលើ ទោះបីជាមកដល់ជំនាន់ឥលូវក៏មានសម្រស់មិនចាញ់កាលពីក្មេងដែរ។ ជាក់ស្តែងយើងទៅមើលរូបភាពខាងក្រោមនេះ គឺរូបភាពជាតួសម្តែងទាំងប្រុសទាំង 12 រូប ដែលលើកយកមកប្រៀបធៀបកាលពីជំនាន់ឆ្នាំ 90 និងមកដល់បច្ចុប្បន្ននេះ ប៉ុន្តែមានតារាខ្លះខ្ញុំជឿថាលោកអ្នកប្រាកដជាមិនសូវស្គាល់នោះទេ ហើយបើនិយាយពីមុនតារាមុនដំបូងគេវិញគឺលោក <span style=\"font-weight: 700; text-align: center; line-height: 1.42857;\">Leonardo DiCaprio </span><span style=\"text-align: center; line-height: 1.42857;\">ដែលលោកអ្នកស្គាល់គាត់ភាគច្រើនជាតួឯកក្នុងរឿង កប៉ាល់ទីតានិក </span><span style=\"line-height: 1.42857;\">៖ </span></p><p style=\"text-align: center; \"><br><font color=\"#FA870D\">Leonardo DiCaprio</font><br></p><p style=\"text-align: center; \">")`
When I set like this got error "Cannot assign value of type 'NSAttributedString" to type '[NSObject:AnyObject]'

**Comment by maicki** [comment]
@mengheangrat What do yo actually return from `readDatatHtml()`? You cannot assign a full attributed string to the `textAttributes` property. This is for attributes of the text you set via `text` to the ASTextCell.

I guess you have to go the other route (adding a ASTextNode to a ASTextCell and layout in ASTextCell) if you want to set an attributed text that you get from readDatatHtml()

**Comment by mengheangrat** [comment]
`    func readDataHtml(htmlText: String)->NSAttributedString{
        var textDetail = NSAttributedString()
        do {
            let text = htmlText.replace("<br></p><p><br></p>",replacement: "")
            let encodedData = text.dataUsingEncoding(NSUTF8StringEncoding)!
            let attributedOptions : [String : AnyObject] = [
                NSDocumentTypeDocumentAttribute : NSHTMLTextDocumentType,
                NSCharacterEncodingDocumentAttribute: NSUTF8StringEncoding,
                ]
            do {
                let attributedString = try NSAttributedString(data: encodedData, options: attributedOptions, documentAttributes: nil)
                textDetail = attributedString
            } catch let error as NSError {
                print(error.localizedDescription)
            }
        }
        return textDetail
    }`

**Comment by maicki** [comment]
Yeah this is not supported in connection with ASTextCellNode. Wrap a ASTextNode in a ASCellNode and layout within ASCellNode. There are plenty of examples of that in the "examples" folder if you look at the ASDK repo: https://github.com/facebook/AsyncDisplayKit/tree/master/examples

I would recommend start there.

**Comment by mengheangrat** [comment]
Thank For your help 
But I am blind with Objective-C.

**Comment by maicki** [comment]
@mengheangrat We also have some examples in Swift on our site: http://asyncdisplaykit.org/docs/getting-started.html
