### ISSUE TITLE
[AsTabelView]Why tableView reloadDataImmediately will directly to the top

### ISSUE THREAD

**Issue by asd2189155** [facebook/AsyncDisplayKit#1625]
Why tableView reloadDataImmediately will directly to the top

**Comment by aaronschubert0** [comment]
@asd2189155 This is the standard behaviour when you force a full reload on ASTableView. If you want to keep your scroll position then it's best to use inserts/deletes.

**Comment by appleguy** [comment]
@asd2189155 curious what you're using -reloadDataImmediately for?  In general this is not a great method, and you should use the other editing methods whenever possible.

**Comment by hannahmbanana** [comment]
@asd2189155: If you join our slack channel, we'd be happy to help you out with any ASDK architecture questions you have. To join ASDK's slack, see directions at #1582.

**Comment by appleguy** [comment]
@asd2189155 - thank you for contributing to the AsyncDisplayKit community by asking your question here! Let me know if you have any follow up questions, either by reopening this issue, or contacting any of us on Slack (#1582).
