### ISSUE TITLE
[ASTextNode] layer animation gets stopped when going to next cell

### ISSUE THREAD

**Issue by ShaunakP** [facebook/AsyncDisplayKit#1626]
In my main page I have ASCollectionView with Images in each cell. In the ImageNode, I have a label (I am using fontello font) of loading mask which I want to spin forever when the image is downloading. Rotation is started for the first cell, but when I swipe to next cell, it gets stopped. Is there any issue of CABasicAnimation when cell is updated? Or am I doing something wrong?

ImageContainer.m

```
- (ASCellNode*)collectionView:(ASCollectionView *)collectionView nodeForItemAtIndexPath:(NSIndexPath *)indexPath {
    ImageNode *elementNode = [[ImageNode alloc] initWithImageNode:nil];
    return elementNode;
}

```

ImageNode.m
```
@interface ImageNode () <ASNetworkImageNodeDelegate>
@property (nonatomic, strong) ASNetworkImageNode *networkImageNode;
@property (nonatomic, strong) ASImageNode *spinnerImage;
@property (nonatomic, strong) ASTextNode *spinnerLabel;
@end

@implementation ImageNode

- (instancetype)initWithImageNode:(id)listingData {
    self = [super init];
    if (self != nil) {
        self.spinnerImage = [ASImageNode new];
        self.spinnerImage.image = [UIImage imageNamed:@"gridPlaceholder2.png"];
        self.spinnerImage.userInteractionEnabled = NO;
        [self addSubnode:self.spinnerImage];
        self.spinnerImage.sizeRange = ASRelativeSizeRangeMake(ASRelativeSizeMake(ASRelativeDimensionMakeWithPoints(290.0), ASRelativeDimensionMakeWithPoints(145.0)), ASRelativeSizeMake(ASRelativeDimensionMakeWithPoints(290.0), ASRelativeDimensionMakeWithPoints(145.0)));

        
        self.spinnerLabel = [ASTextNode new];
        self.spinnerLabel.layerBacked = NO;
        self.spinnerLabel.sizeRange = ASRelativeSizeRangeMake(ASRelativeSizeMake(ASRelativeDimensionMakeWithPoints(40.0), ASRelativeDimensionMakeWithPoints(40.0)), ASRelativeSizeMake(ASRelativeDimensionMakeWithPoints(40.0), ASRelativeDimensionMakeWithPoints(40.0)));
        
        self.spinnerLabel.userInteractionEnabled = NO;
        [self addSubnode:self.spinnerLabel];
        self.spinnerLabel.attributedString = [[NSAttributedString alloc] initWithString:@"\ue82a" attributes:[AppUtility spinnerTextAttributes]];
        
        self.networkImageNode = [ASNetworkImageNode new];
        self.networkImageNode.backgroundColor = [UIColor clearColor];
        self.networkImageNode.delegate = self;
        [self.networkImageNode setURL:[NSURL URLWithString:@"http://images.indianexpress.com/2015/09/cars-759.jpg"] resetToDefault:NO];
        [self addSubnode:self.networkImageNode];

        [self showLoadingView];
     
    }
    return self;
}

- (void) showLoadingView {
    self.spinnerLabel.hidden = NO;
   
    self.spinnerImage.image = [UIImage imageNamed:@"gridPlaceholder.png"];    

    CABasicAnimation *rotation;
    rotation = [CABasicAnimation animationWithKeyPath:@"transform.rotation"];
    rotation.fromValue = [NSNumber numberWithFloat:0];
    rotation.toValue = [NSNumber numberWithFloat:(2*M_PI)];
    rotation.duration = 1.5; // Speed
    rotation.repeatCount = HUGE_VALF; // Repeat forever. Can be a finite number.
    [ self.spinnerLabel.layer addAnimation:rotation forKey:@"Spin"];
    [self.spinnerLabel.layer MB_setCurrentAnimationsPersistent]; 
}
```

**Comment by hannahmbanana** [comment]
@ShaunakP: Before addressing the specifics of this question, I'm curious if you've looked into ASNetworkImageNode's placeholder property (`.defaultImage`)? 

The modern UI style for loading images in apps seems to be a static grey or default image background. For example, Pinterest's home feed uses solid color "images" as placeholders to represent images that are still downloading.

If this style would work for your app, you can save TONS of code using ASNetworkImageNode's built in .defaultImage property. You just have to subclass the ASNetworkImageNode to return the placeholder image that you would like to show. ASDK will do the rest - displaying the default image and removing it when the real image finishes downloading and rendering.   

Let me know if you've already heard of this, or are still interested in making the spinner work. I would happy to help debugging your original issue.

**Comment by ShaunakP** [comment]
@hannahmbanana  Thanks for the suggestion. However, our requirement is such that we need to show a infinitely rotating spinner when the image is downloading. It would be helpful if we can look into the issue.

**Comment by Adlai-Holler** [comment]
@ShaunakP I believe that CoreAnimation cancels animations when a layer exits a window. Your node could override `interfaceStateDidChange:fromState:`, and if newState includes visible, and oldState doesn't include visible, and the content's still loading, show the loading animation. Hope that helps!

**Comment by lucabecchetti** [comment]
ShaunakP how did you solve it?
