### ISSUE TITLE
[ASLayout] Implement property similar to Android `gone` property.

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#1640]
Guys i hate Android developers for view.gone property. We must add some like that if we haven't it.
>This view is invisible, and it doesn't take any space for layout purposes.

it means if we have nodes and LayoutSpecs for it, then  gone = false removed nodes from supernode, and invalidate all ASLayoutSpecs to up by hierarchy. If gone = true its add node to superview and add all ASLayoutSpecs described in `layoutSpecThatFits:` method.

**Comment by hannahmbanana** [comment]
@bimawa: As discussed on Slack, does Implicit Node Hierarchy Management suffice? Or is there some other functionality that is desired?

http://asyncdisplaykit.org/docs/implicit-hierarchy-mgmt.html

This is a beta feature developed by @levi that will soon be on by default. When enabled, Implicit Node Hierarchy Management means that your nodes no longer require addSubnode: or removeFromSupernode method calls. The presence or absence of the INHM node and its subnodes are determined in the layoutSpecThatFits: method.

**Comment by bimawa** [comment]
@hannahmbanana @levi yes a little bit another functional i want. What we have today:
```
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
  NSMutableArray *mainNodes = [NSMutableArray new];
  ASStackLayoutSpec *firstPriceStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:0
                                                                        justifyContent:ASStackLayoutJustifyContentSpaceBetween alignItems:ASStackLayoutAlignItemsCenter
                                                                              children:@[self.priceOfOrderTitle, self.priceByRowsTotalTextNode]];
  self.checkoutOrderButton.flexBasis = ASRelativeDimensionMakeWithPoints(48);
  ASInsetLayoutSpec *firstStackInsets = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(16, 0, 0, 0) child:firstPriceStack];
  [mainNodes addObject:firstStackInsets];
  if(self.isVisibleDeliverPriceNodes)
  {
    ASStackLayoutSpec *deliverStack       = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:0
                                                                             justifyContent:ASStackLayoutJustifyContentSpaceBetween alignItems:ASStackLayoutAlignItemsCenter
                                                                                   children:@[self.deliverTitleTextNode, self.deliverTypeTextNode]];
    ASInsetLayoutSpec *deliverStackInsets = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(8, 0, 0, 0) child:deliverStack];
    [mainNodes addObject:deliverStackInsets];
  }

  ASInsetLayoutSpec *separatorInsetLayoutSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(16, 0, 14, 0) child:self.separatorViewNode];
  separatorInsetLayoutSpec.flexBasis = ASRelativeDimensionMakeWithPoints(31);
  [mainNodes addObject:separatorInsetLayoutSpec];

  if(self.isTotalPriceNodes))
  {
  ASStackLayoutSpec *totalPriceStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:0
                                                                        justifyContent:ASStackLayoutJustifyContentSpaceBetween alignItems:ASStackLayoutAlignItemsCenter
                                                                              children:@[self.totalPriceTextNode, self.countTotalWithDeliverPriceTextNode]];
   ASInsetLayoutSpec *totalPriceInset = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 0, 18, 0) child:totalPriceStack];
   [mainNodes addObject:totalPriceInset];
  }

  [mainNodes addObject:self.checkoutOrderButton];
  ASStackLayoutSpec *mainVerticalStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:0
                                                                            justifyContent:ASStackLayoutJustifyContentStart alignItems:ASStackLayoutAlignItemsStretch
                                                                                  children:mainNodes.copy];
  ASInsetLayoutSpec *mainInsets        = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 16, 16, 16) child:mainVerticalStack];
  return mainInsets;
}
```
its epic hard to understanding and overkill at first time with additional `if` cases. What i need for simple disable/enable layoutSpec;

```
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
  ASStackLayoutSpec *firstPriceStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:0
                                                                        justifyContent:ASStackLayoutJustifyContentSpaceBetween alignItems:ASStackLayoutAlignItemsCenter
                                                                              children:@[self.priceOfOrderTitle, self.priceByRowsTotalTextNode]];
  self.checkoutOrderButton.flexBasis = ASRelativeDimensionMakeWithPoints(48);
  ASInsetLayoutSpec *firstStackInsets = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(16, 0, 0, 0) child:firstPriceStack];
  ASStackLayoutSpec *deliverStack       = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:0
                                                                           justifyContent:ASStackLayoutJustifyContentSpaceBetween alignItems:ASStackLayoutAlignItemsCenter
                                                                                 children:@[self.deliverTitleTextNode, self.deliverTypeTextNode]];
  ASInsetLayoutSpec *deliverStackInsets = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(8, 0, 0, 0) child:deliverStack];
  deliverStackInsets.gone = self.isVisibleDeliverPriceNodes; //or similar
  
  ASInsetLayoutSpec *separatorInsetLayoutSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(16, 0, 14, 0) child:self.separatorViewNode];
  separatorInsetLayoutSpec.flexBasis = ASRelativeDimensionMakeWithPoints(31);

  ASStackLayoutSpec *totalPriceStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:0
                                                                        justifyContent:ASStackLayoutJustifyContentSpaceBetween alignItems:ASStackLayoutAlignItemsCenter
                                                                              children:@[self.totalPriceTextNode, self.countTotalWithDeliverPriceTextNode]];
  ASInsetLayoutSpec *totalPriceInset = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 0, 18, 0) child:totalPriceStack];
  totalPriceInset.gone = self.isTotalPriceNodes; //or similar 
  ASStackLayoutSpec *mainVerticalStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:0
                                                                            justifyContent:ASStackLayoutJustifyContentStart alignItems:ASStackLayoutAlignItemsStretch
                                                                                  children:@[firstStackInsets, deliverStackInsets,separatorInsetLayoutSpec,totalPriceInset,self.checkoutOrderButton]];
  ASInsetLayoutSpec *mainInsets        = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 16, 16, 16) child:mainVerticalStack];
  return mainInsets;
}
```

Pretty cool? more usefull, and clear for understand?

**Comment by bimawa** [comment]
Add 2 screenshots what its do. Maybe it help for understand.
Before gone =  true;
![iphone 6 - iphone 6 _ ios 9 3 13e230 2016-05-10 17-40-52](https://cloud.githubusercontent.com/assets/1393809/15173531/007ae57a-1776-11e6-8dd8-62eabb6cea0a.png)

and if gone = false;

![iphone 6 - iphone 6 _ ios 9 3 13e230 2016-05-10 17-49-48](https://cloud.githubusercontent.com/assets/1393809/15173546/1275347e-1776-11e6-8c97-2408d0ee6cc2.png)

**Comment by levi** [comment]
@bimawa you're on to something here. Would you have time to put together a pull request with a general implementation for a gone property? I'd be more than happy to provide assistance on areas of the framework you are not familiar with.

**Comment by hannahmbanana** [comment]
Here's the summary from the Slack conversation: 

- @nguyenhuy: Very cool idea! I imagine this `gone` property can be used to simplify layout code in many cases. One minor downside of it is that it makes the layout system a bit less declarative. do you have any thoughts about its implementation?

- @bimawa: I have only one idea its add property to ASLayoutSpec class. But maybe community can invent better ideas? but like u spot its make a bit less declarative. But from another side its property like `flexShrink` similar props. We can try add this to `ASLayoutable.h` protocol. Call it like `flexVisible` with default propery `YES` and if this property is `NO` skip Spec from calculation in layouts.

- @nguyenhuy: that’s one good approach. The thing I’m concerning is how this implementation would affect other properties, especially stack related ones. I need a bit more time to think about this. Could you explore this option and perhaps put up a PR? It will definitely help us to have a better idea and open detailed discussions

**Comment by bimawa** [comment]
@levi i start reserach and implement this feature on the weekends. Thanks for ready to help :)

**Comment by bimawa** [comment]
@levi what is the best a branch for fork?

**Comment by levi** [comment]
@bimawa master is the best

**Comment by bimawa** [comment]
@levi  i try it, Must I make pullRequest? or u can help in my repository? 
For use if u want hide ASLayoutSpec just set flexGone property to YES;

**Comment by hannahmbanana** [comment]
@bimawa: When you ready, you can make a pull request to this repository.

**Comment by bimawa** [comment]
@hannahmbanana  yea ty, community have a questions with new name of param. I can make PR now, or refactor property name before.

**Comment by appleguy** [comment]
I am not sure what a better name is. I would recommend you put up a pull request now, and the discussion will lead us to any naming improvements, which there might not be any required.

It is very easy to update a pull request; you can simply push new commits to your branch that you created it from, and those will automatically affect the PR.  Opening a PR basically just points to one of your branches, so it's very similar to what you have now.

**Comment by bimawa** [comment]
@appleguy  ok Scott, Thanks a lot for help. I go do it.

**Comment by hannahmbanana** [comment]
@bimawa: I am happy to help you with putting up the PR if you run into any trouble.

**Comment by bimawa** [comment]
@hannahmbanana No problems Hnna, I know how to make PR  thank you :) I need a little bit time just every days is deadline >:)

**Comment by appleguy** [comment]
Closing this thread. Let's continue the conversation over in the PR (#1715)!
