### ISSUE TITLE
In Swift an ASViewController with ASCollectionDataSource also requires ASCollectionDataSource

### ISSUE THREAD

**Issue by benjaminhorner** [facebook/AsyncDisplayKit#1651]
I have an ASViewController 

  `class VideoPlayerViewController: ASViewController, ASPagerNodeDataSource`…

with the following init method.

```
 init() {
    let layout = ASPagerFlowLayout()
    pagerNode = ASPagerNode(collectionViewLayout: layout)
    super.init(node: pagerNode)
    pagerNode.delegate = self
 }
```

As such I get the following error: 

> Cannot assign value of type VideoPlayerViewController to type ASCollectionDataSource

The error disappears if I implement the ASCollectionDataSource. However, I then also have to implement the ASCollectionDataSource delegate methods.

The ASPagerNodeDataSource still take precendent, but I do find it weird that I must implement two useless methods and ASCollectionDataSource which should be the superclass of ASCollectionDataSource.

**Comment by maicki** [comment]
@benjaminhorner You have to set the `dataSource` property to `self`. Currently you set the `delegate` property to `self` so you have to implement the `ASPagerDelegate` protocol.

If this is not the problem and you assign `self` to `dataSource` the `ASPagerDataSource` protocol does not inherit from any other protocol so you only would have to implement the required methods of the  `ASPagerDataSource` protocol

**Comment by hannahmbanana** [comment]
@benjaminhorner: were you able to resolve your issue? If not, I'd be happy to help you out on here or on ASDK's Slack channel (#1582). 

FYI - there are several examples that use the ASPagerNode, such as the HorizontalWithinVertical example app.

**Comment by appleguy** [comment]
Also, make sure you're using the latest version of the framework (at least 1.9.74 - master is good right now, as 1.9.8 is about to go out).

If you still have this issue, let us know, but it should not be difficult to work around by conforming to the collection data source in the short term.  I really want to know if you are seeing that, though.  Example projects like VerticalWithinHorizontalScrolling use ASPagerNode (as does Pinterest in many places) and I don't recall this being necessary.

**Comment by appleguy** [comment]
@benjaminhorner - I'm going to close this issue given the length of time since the thread has been active. However, if you have any questions, don't hesitate to reopen this issue or start a new one! We're also available over on the ASDK Slack channel.
