### ISSUE TITLE
[ASTableView and ASCellNode] Important memory leak 

### ISSUE THREAD

**Issue by gonzo-oin** [facebook/AsyncDisplayKit#1654]
Hello, I'm using AsyncDisplayKit in an application like twitter with complex cells. Performance is good but after 10 minutes of using the app on an iPhone 5, the drawing of cells become so slow that I can see it and Xcode show me memory that always goes up even if I leave the view controller. 

I'm using a UIViewController that contain an ASTableView and despite the fact that the viewController is released (`deinit` called), the memory is not going down and when I come back on the ViewController, the memory is going up again. I have tried many things in the `deinit` of the UIViewController :
- delete sections
- delete all rows 
- remove tableview from view 
- iterate on every ASCellNodes and call `recursivelyClearContents()`, `removeFromSupernode()` and even the deprecated `reclaimMemory()` method

I also tried to replace UIViewController by an ASViewController and ASTableView by an ASTableNode and tried calling `removeFromSupernode`, `recursivelyClearContents` and `recursivelyClearFetchedData`.

None of these solutions have worked, I've tracked memory usage in Xcode and allocations in Instruments.

In instruments, I see the subnodes (ASTextNode, etc…) of ASCellNodes continuously going up. 
![leak](https://cloud.githubusercontent.com/assets/1376242/15210432/c96ca0c0-1836-11e6-9bbe-0b247fa8f8de.png)

My questions: 
- Is there something I've missed from the documentation that allow nodes to be released?
- Is there a bug in my implementation? If so, could someone post me an example where memory is dropping when a viewController with a populated ASTableView is deinit.
- If not, how to force the release of all created nodes?

**Comment by maicki** [comment]
@gonzo-oin Based on the Instruments log there is only one ASCellNode but a lot more ASTextNode, ASImageNode and ASButtonNode. How do you setup the whole node hierarchy? Would you mind providing some sample project / code?

For me it looks like a retain cycle is happening somewhere.

**Comment by gonzo-oin** [comment]
@maicki Hello, you were right.
