### ISSUE TITLE
Question: proper way of updating ASTextNode Size

### ISSUE THREAD

**Issue by ziyuanliu** [facebook/AsyncDisplayKit#1657]
quick questions, I'm using an ASTextNode to keep score for my app. Whenever, the score increases from single character to double characters, only the first character is showing (but the full string shows after updating the newly 2 character string to another 2 character string). Where is the most appropriate method to update the width of ASTextNode?

**Comment by maicki** [comment]
@ziyuanliu Do you embed the ASTextNode in some other node? Would it be possible to provide some sample project / code?

**Comment by ziyuanliu** [comment]
Yep it is enclose in another node. 
`override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        let stack = ASStackLayoutSpec(direction: .Vertical, spacing: 0, justifyContent: .SpaceAround , alignItems: .Center , children: [upvoteBtn, scoreLabel, downvoteBtn])
        stack.sizeRange = ASRelativeSizeRange(min: ASRelativeSize(width: ASRelativeDimensionMakeWithPoints(30) , height: ASRelativeDimensionMakeWithPoints(20)), max: ASRelativeSize(width: ASRelativeDimensionMakeWithPoints(40), height: ASRelativeDimensionMakeWithPoints(20)))
        stack.flexGrow = true
        return stack
   }`

Now the upvote and downvote buttons all have a preferredFrameSize of 20 x 20.

**Comment by maicki** [comment]
@ziyuanliu Can you try to call `[self setNeedsLayout]` within the node that specifies the `layoutSpecThatFits:` that you posed after the value of the score label was updated.

**Comment by hannahmbanana** [comment]
@ziyuanliu: Did maicki's suggestion resolve your issue?

**Comment by maicki** [comment]
@hannahmbanana I think we had that issue on our Slack channel and it will be resolved by calling `setNeedsLayout`. Good to close in my opinion.

<img width="650" alt="screen shot 2016-06-09 at 1 08 29 pm" src="https://cloud.githubusercontent.com/assets/25288/15944623/4b625b3e-2e43-11e6-8ada-40c9ebaef9e7.png">

**Comment by appleguy** [comment]
@ziyuanliu - Thank you  for asking this question and contributing to the AsyncDisplayKit community! Feel free to reopen this issue if you are still having issues, but it appears to me that we have resolved this for you.
