### ISSUE TITLE
[ASStackLayoutSpec] affect the layout

### ISSUE THREAD

**Issue by Serlight** [facebook/AsyncDisplayKit#1678]
First i use below layout get the result like 
![image](https://cloud.githubusercontent.com/assets/1770057/15354480/6e8252e2-1d20-11e6-8559-44d39f1d776a.png)

    NSMutableArray *anchorChildren = [@[_anchorAvatarNode, _anchorNameNode] mutableCopy];
    [anchorChildren addObjectsFromArray:_liveTagss];
    
    ASStackLayoutSpec *anchorLayout = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal
                                                                              spacing:5
                                                                       justifyContent:ASStackLayoutJustifyContentStart
                                                                           alignItems:ASStackLayoutAlignItemsCenter
                                                                             children:anchorChildren];
    
    ASStackLayoutSpec *bottomLayout = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal
                                                                              spacing:5
                                                                       justifyContent:ASStackLayoutJustifyContentSpaceBetween
                                                                           alignItems:ASStackLayoutAlignItemsCenter
                                                                             children:@[anchorLayout, spacer, _followAnchorButtonNode]];
    bottomLayout.alignSelf = ASStackLayoutAlignSelfStretch;
    
    ASStackLayoutSpec *bottomMainLayout = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                  spacing:10
                                                                           justifyContent:ASStackLayoutJustifyContentStart
                                                                               alignItems:ASStackLayoutAlignItemsStart
                                                                                 children:@[_liveTitleNode, bottomLayout]];
    
    
    ASInsetLayoutSpec *bottomInsetLayout = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 15, 0, 15)
                                                                                  child:bottomMainLayout];
    return bottomInsetLayout;

But when i add a stack layout at the end like below:
  
    ASStackLayoutSpec *liveItemLayout = [ASStackLayoutSpec   stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                 spacing:10
                                                                         justifyContent:ASStackLayoutJustifyContentSpaceAround
                                                                             alignItems:ASStackLayoutAlignItemsStart
                                                                               children:@[_livePreViewImageNode, bottomInsetLayout]];
     return  liveItemLayout;

get the reulst like below:
![image](https://cloud.githubusercontent.com/assets/1770057/15354561/e4131e38-1d20-11e6-9629-37eae424bcb8.png)

  

i want the follow button align to right baseline, how can i change the layout

Thx in advance!

**Comment by maicki** [comment]
@Serlight You have to set the `sizeRange` for the the layout spec were the follow button is included to 100% width. Change the `alignSelf` of the follow button spec to `ASStackLayoutAlignSelfEnd`

Otherwise would be great if you can provide a small sample project so I can dive deeper into it and tell you the fix with actual code.

**Comment by Serlight** [comment]
@maicki  thx your reply, i fixed it with set the last stack layout spec's alignItems : ASStackLayoutAlignItemsStretch

    ASStackLayoutSpec *liveItemLayout = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                spacing:0
                                                                         justifyContent:ASStackLayoutJustifyContentSpaceAround
                                                                             alignItems:ASStackLayoutAlignItemsStretch
                                                                               children:@[_divider ,_livePreViewImageNode, bottomInsetLayout]];

**Comment by hovox** [comment]
@Serlight thank you, I was straggling for hours
