### ISSUE TITLE
ASButtonNode size is not set per the preferredFrameSize

### ISSUE THREAD

**Issue by bozouser** [facebook/AsyncDisplayKit#1694]
Hi I am new to AsyncDisplayKit and I am having difficulty understanding how the ASLayoutSpec works. I am trying to create a node which consists of ASNetworkImage and a ASButtonNode.

    override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        

        let imageSize = CGSize(width: 257.0, height: 200.0)
        let buttonSize = CGSize(width: 257.0, height: 100)
        
        self.image.preferredFrameSize = imageSize
        
        let tileStack = ASStackLayoutSpec()
        tileStack.direction = .Vertical
        
        self.swipeButton.preferredFrameSize = buttonSize
        self.swipeButton.alignSelf = .Stretch
        
        tileStack.setChildren([self.image,self.swipeButton])
        
        return tileStack
        
    }

The resulting view looks like this the button size is about 14.5 and not 100 as declared in my buttonSize.
<img width="250" alt="screen shot 2016-05-23 at 6 09 18 pm" src="https://cloud.githubusercontent.com/assets/2401277/15489097/96b6dcd4-2111-11e6-8cb1-0e5b79d8e061.png">

**Comment by flovouin** [comment]
Hi, I don't know if you've solved your problem by now, but the trick is to put each node inside a `ASStaticLayoutSpec`, and then add these specs to the stack. It will make the stack layout stick to the `preferredFrameSize`s you specified.
Something like:
`tileStack.setChildren([ASStaticLayoutSpec(children: [self.image]), ASStaticLayoutSpec(children: [self.swipeButton])])`

I don't know whether this is the expected way to use these, but it works. I hope it does too in your case.

**Comment by bozouser** [comment]
thanks..got it to work.
