### ISSUE TITLE
[Layout Question] must provide preferredFrameSize: for ASTextNodes

### ISSUE THREAD

**Issue by minhthuc251** [facebook/AsyncDisplayKit#1698]
I met this error. How can i fix it ?
![screen shot 2016-05-27 at 2 06 39 pm 2](https://cloud.githubusercontent.com/assets/5000594/15600539/bc803f18-2414-11e6-8f42-108153d60562.png)

**Comment by appleguy** [comment]
What is your layoutSpecThatFits: method(s) ?

**Comment by minhthuc251** [comment]
My layoutSpecThatFits method in my listproductcell . I copy from ASCollectionView in example but it not working
![screen shot 2016-05-27 at 3 49 04 pm](https://cloud.githubusercontent.com/assets/5000594/15603046/c46b9cfa-2422-11e6-965b-7197e0b74ecb.png)

**Comment by appleguy** [comment]
Could you please share the crash backtrace?  It is not possible to debug / fix a crash without the backtrace or at least an exception message, if one exists.

**Comment by appleguy** [comment]
Hmm ok I see a partial log in the other email.

Your layout must be underspecified.  Try setting a preferredFrameSize on the node, or if you can use constrainedSizeForNodeAtIndexPath: in the delegate, this should fix.

You can use the debugger to look at the value that is getting through, and I'm pretty confident you will find some kind of infinite value is not being bounded.

**Comment by hannahmbanana** [comment]
@minhthuc251: were you able to fix your layoutSpecThatFits: method? If not, I can help you either here or on our ASDK Slack channel. Signup at http://asdk-slack-auto-invite.herokuapp.com or email asyncdisplaykit@gmail.com to get a Slack invite.

**Comment by hannahmbanana** [comment]
@minhthuc251: Thanks for reporting this issue! We plan on improving our layout documentation on AsyncDisplayKit.org very soon since it is a bit vague right now. Check back in a few weeks for better documentation.

I'm going to close this issue since it appears that it has been resolved, however, feel free to reopen it if you are still having troubles.
