### ISSUE TITLE
[ASTextKitContext, ASTextView] Crash reports using ASDK 1.9.73

### ISSUE THREAD

**Issue by klivin** [facebook/AsyncDisplayKit#1703]
Posting here as a response to conversation started in Slack channel with @maicki and @appleguy about sharing relevant crashes.

Here's a handful of crashes we are getting that all seem to be somewhat related to the ASTextKitContext in our production app.  They are very hard to reproduce, as I have not yet reproduced any of them.

http://crashes.to/s/57615585859

http://crashes.to/s/78e5fd29225

http://crashes.to/s/bc12fcdb09d

http://crashes.to/s/f52975e6375

http://crashes.to/s/7f34274b048

http://crashes.to/s/d4f445cb196

http://crashes.to/s/521acd4737b

http://crashes.to/s/3c246834890

http://crashes.to/s/ac645e3d425

http://crashes.to/s/adfc74114fa

**Comment by levi** [comment]
Related: #1739

**Comment by maicki** [comment]
@klivin We did a total assessment around locking in `ASTextNode` that got merge today (#1749) and we think the lack of locking in ASTextNode is responsible for the majority of this crashes

I will close this issue for now, please reopen or open a new issue if you run into further crashes. Thanks again for providing all of the crashlogs they definitely helped to figure out problems on our side!
