### ISSUE TITLE
[ASPagerNode] Incorrect page frame

### ISSUE THREAD

**Issue by Jauzee** [facebook/AsyncDisplayKit#1714]
I'm fully migrated my new project to `AsyncDisplayKit` and find it very useful & flex

Current view hierarchy looks like this:
`ContentsViewController` – `ASTableNode` –> pushes to `PagerVC`
`PagerViewController` – `ASPagerNode` –> pushes to `DetailVC` (init with viewControllerBlock)
`DetailViewController` – `ASTableNode`

In `DetailViewController` I'm faced a problem:
If `UINavigationBar` `translucent` property set to `true` the tableNode `frame` is incorrect, and if this property set to `false` frame is correct, but after unpleasant bouncing.

I created a sample project: [ASTableViewBounce.zip](https://github.com/facebook/AsyncDisplayKit/files/299475/ASTableViewBounce.zip)

**Comment by appleguy** [comment]
@Jauzee very glad to hear that the framework is been useful to you! Would you be able to quickly test if this issue affects a regular UITableView / View Controller?

Based on your description, I am nearly certain that it would be a behavior of UIKit.  I'm not particularly familiar with the subtle behaviors of the navigation bar, as most apps I have worked on use custom classes to implement this behavior.

That said, if if you can confirm that it does not occur using basic UIKit classes, we'll take a look at the test project soon!  Please join our slack channel if you have not already, as many people are often online and happy to help.

**Comment by Jauzee** [comment]
@appleguy I'm created subclass of `UIViewController` that based on standard `UITableView` & bug is here, view is bounces after loading.  
<details> 
  <summary>Maked some GIFs:</summary>
   <p>![nav_bar_ translucent](https://cloud.githubusercontent.com/assets/7991920/15833964/bded6220-2c31-11e6-92cd-2da8dea08279.gif)
![nav_bar_translucent]
(https://cloud.githubusercontent.com/assets/7991920/15833965/bdf58f7c-2c31-11e6-8928-0edbe8c9411e.gif)</p>
</details>

Then I've been changed `PagerViewController` to subclass `UIViewController` and added `ASPagerNode` as `subnode` to `view`. Now I have correct behaviour (with my `DetailViewController`).

Solution in my case is: make `PagerViewController` not subclassing from `ASViewController`

Thank you for response. My problem is solved, but if you have a time, would be good to know what I'm doing wrong.

**Comment by hannahmbanana** [comment]
@Jauzee - awesome, glad to hear the issue is gone! Let us know if you run into any issues with the new 1.9.8 release.
