### ISSUE TITLE
[Question] Layout two ASTextNode's with priority for one of them

### ISSUE THREAD

**Issue by Raikerian** [facebook/AsyncDisplayKit#1720]
Hi,

First of all thank you for the great component.
I have a problem with layouting two ASTextNode's in ASDisplayNode with priority for one of them.
Basically, this is what am i trying to achieve:

![screenshot 2016-06-07 11 25 46](https://cloud.githubusercontent.com/assets/8850270/15850801/9cce07fe-2ca2-11e6-804f-470e54cea781.png)

This is my first label (it should be shrinked):

``` objectivec
        _titleNode = [[ASTextNode alloc] init];
        _titleNode.backgroundColor = [UIColor clearColor];
        _titleNode.flexShrink = YES;
        _titleNode.truncationMode = NSLineBreakByTruncatingTail;
        _titleNode.maximumNumberOfLines = 1;
        _titleNode.layerBacked = YES;
```

This is my second label (this one should have priority):

``` objectivec
        _statusNode = [[ASTextNode alloc] init];
        _statusNode.backgroundColor = [UIColor clearColor];
        _statusNode.truncationMode = NSLineBreakByTruncatingTail;
        _statusNode.maximumNumberOfLines = 1;
        _statusNode.layerBacked = YES;
```

This is my `layoutSpecThatFits:` layout code right now:

``` objectivec
        ASStackLayoutSpec *hStack = [ASStackLayoutSpec
                                     stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal
                                     spacing:6.0f
                                     justifyContent:ASStackLayoutJustifyContentStart
                                     alignItems:ASStackLayoutAlignItemsEnd
                                     children:@[self.titleNode, self.statusNode]];

        hStack.alignSelf = ASStackLayoutAlignSelfStretch;

        return [ASStaticLayoutSpec staticLayoutSpecWithChildren:@[hStack]];
```

For some reason it is not working for me now, and I'm getting this:

![screenshot 2016-06-07 11 34 02](https://cloud.githubusercontent.com/assets/8850270/15851026/c076db80-2ca3-11e6-9423-b117c2c82cdf.png)

Also I wonder, is it possible to make a maximum shrink width for first text node, so when the second text node is long enough it would shrink too, like this:

![screenshot 2016-06-07 11 33 04](https://cloud.githubusercontent.com/assets/8850270/15851016/b31440ae-2ca3-11e6-87e7-9e5753e7615d.png)

When i'm setting flexShrink for second text node it is loosing its priority over the fist text node.

Thank you for any of your suggestions.

P.S. What am I doing is adding the view of this ASDisplayNode to the title of navigation item.

**Comment by maicki** [comment]
@Raikerian Please try this and let me know if this is the result you had in mind:

In `layoutSpecThatFits:`:
```Objc
self.titleNode.flexShrink = YES;
// Define max width for title node. you can also use points: ASRelativeDimensionMakeWithPoints
self.titleNode.flexBasis = ASRelativeDimensionMakeWithPercent(0.2);

self.statusNode.flexShrink = YES;

ASStackLayoutSpec *hStack = [ASStackLayoutSpec
                                     stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal
                                     spacing:6.0f
                                     justifyContent:ASStackLayoutJustifyContentStart
                                     alignItems:ASStackLayoutAlignItemsStretch
                                     children:@[self.titleNode, self.statusNode]];
hStack.flexBasis = ASRelativeDimensionMakeWithPercent(1.0);
return hStack
```

**Comment by Raikerian** [comment]
@maicki thanks for the solution, it is working for long text nodes indeed, however with similar ones (medium-long) it is shrinking first label even though there is more space to go:

![screenshot 2016-06-08 18 19 19](https://cloud.githubusercontent.com/assets/8850270/15899777/8b997faa-2da5-11e6-90f8-d47fe3bb9dd4.png)

Maybe I'm doing relayout in a wrong way?
Here is my relayout code for display node:

```objc
[self invalidateCalculatedLayout];
[self setNeedsLayout];
    
CGFloat maxContainerWidth = CGRectGetWidth([UIScreen mainScreen].bounds) - 40.0f;
    
CGSize containerSize = CGSizeMake(maxContainerWidth, CGFLOAT_MAX);
    
CGSize size = [self measure:containerSize];
self.bounds = (CGRect) { CGPointZero, size };
```
 Also tried calling first two lines at the end of method, same result.
Because your layout is working fine for short text nodes and long ones, but not for medium-long (like screenshot).

**Comment by garrettmoon** [comment]
Hi @Raikerian we're trying to clean up our issues. Can you bring this question to the [slack](http://asdk-slack-auto-invite.herokuapp.com/) community in the #general channel? Thanks!
