### ISSUE TITLE
[ASNetworkImageNode] Limits of animated Gif support

### ISSUE THREAD

**Issue by boreys** [facebook/AsyncDisplayKit#1731]
I modified the example code from ASDKgram to display animated gif image as a comment. The issue is that the gif image do not always works. When scrolling the feed up and down, the gif image show up randomly. Most of the time there is no gif image. Here is the code I used:

in PhotoCellNode.m I changed this line:
from
_photoCommentsView.shouldRasterizeDescendants = YES:

to
_photoCommentsView.shouldRasterizeDescendants = NO;

then 
CommentsNode.h

`
#import <AsyncDisplayKit/AsyncDisplayKit.h>
#import "CommentFeedModel.h"

@interface CommentsNode : ASDisplayNode<ASNetworkImageNodeDelegate>

- (void)updateWithCommentFeedModel:(CommentFeedModel *)feed;

@end
`

CommentsNode.m

`
#import "CommentsNode.h"

#define INTER_COMMENT_SPACING 5
#define NUM_COMMENTS_TO_SHOW  3

@implementation CommentsNode
{
  CommentFeedModel              *_commentFeed;
  NSMutableArray <ASTextNode *> *_commentNodes;
  ASNetworkImageNode * mediaNode;
}

#pragma mark - Lifecycle

- (instancetype)init
{
  self = [super init];
  if (self) {
    _commentNodes = [[NSMutableArray alloc] init];
    mediaNode =  [[ASNetworkImageNode alloc] init];
    mediaNode.backgroundColor = ASDisplayNodeDefaultPlaceholderColor();
    mediaNode.URL = [NSURL URLWithString:@"https://media0.giphy.com/media/mr2i6zWar7TEY/200.gif"];
    mediaNode.delegate = self;
    mediaNode.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    mediaNode.contentMode = UIViewContentModeScaleAspectFit;
    [self addSubnode:mediaNode];
  }
  return self;
}

- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
  ASStackLayoutSpec *verticalStack = [ASStackLayoutSpec verticalStackLayoutSpec];
  verticalStack.spacing            = INTER_COMMENT_SPACING;
  [verticalStack setChildren:_commentNodes];
  ASStackLayoutSpec * mainStack = [ASStackLayoutSpec verticalStackLayoutSpec];
  mainStack.spacing = INTER_COMMENT_SPACING;
  NSMutableArray * arr = [[NSMutableArray alloc] init];
  [arr addObjectsFromArray:_commentNodes];
  [arr addObject:mediaNode];
  [mainStack setChildren:arr];
  return mainStack;
}

#pragma mark - Instance Methods

- (void)updateWithCommentFeedModel:(CommentFeedModel *)feed
{
  _commentFeed = feed;
  [self removeCommentLabels];
  
  if (_commentFeed) {
    [self createCommentLabels];
    
    BOOL addViewAllCommentsLabel = [feed numberOfCommentsForPhotoExceedsInteger:NUM_COMMENTS_TO_SHOW];
    NSAttributedString *commentLabelString;
    int labelsIndex = 0;
    
    if (addViewAllCommentsLabel) {
      commentLabelString         = [_commentFeed viewAllCommentsAttributedString];
      [[_commentNodes objectAtIndex:labelsIndex] setAttributedString:commentLabelString];
      labelsIndex++;
    }
    
    NSUInteger numCommentsInFeed = [_commentFeed numberOfItemsInFeed];
    
    for (int feedIndex = 0; feedIndex < numCommentsInFeed; feedIndex++) {
      commentLabelString         = [[_commentFeed objectAtIndex:feedIndex] commentAttributedString];
      [[_commentNodes objectAtIndex:labelsIndex] setAttributedString:commentLabelString];
      labelsIndex++;
    }
    
    [self setNeedsLayout];
  }
}
#pragma mark - ASNetworkImageNodeDelegate methods.
- (void)imageNode:(ASNetworkImageNode *)imageNode didLoadImage:(UIImage *)image
{
  [self setNeedsLayout];
}
- (void)imageNodeDidFinishDecoding:(ASNetworkImageNode *)imageNode{
  [self setNeedsLayout];
}
#pragma mark - Helper Methods

- (void)removeCommentLabels
{
  for (ASTextNode *commentLabel in _commentNodes) {
    [commentLabel removeFromSupernode];
  }
  
  [_commentNodes removeAllObjects];
}

- (void)createCommentLabels
{
  BOOL addViewAllCommentsLabel = [_commentFeed numberOfCommentsForPhotoExceedsInteger:NUM_COMMENTS_TO_SHOW];
  NSUInteger numCommentsInFeed = [_commentFeed numberOfItemsInFeed];
  
  NSUInteger numLabelsToAdd    = (addViewAllCommentsLabel) ? numCommentsInFeed + 1 : numCommentsInFeed;
  
  for (NSUInteger i = 0; i < numLabelsToAdd; i++) {
    
    ASTextNode *commentLabel   = [[ASTextNode alloc] init];
    commentLabel.maximumNumberOfLines = 3;
    
    [_commentNodes addObject:commentLabel];
    [self addSubnode:commentLabel];
  }
}

@end
`

Anything wrong with the code above?

thank you.

**Comment by boreys** [comment]
I'm using the latest example and AsyncDisplayKit (1.9.80)

**Comment by boreys** [comment]
By the way, it works great with png image:
mediaNode.URL = [NSURL URLWithString:@"https://market.viber.com/stickers/static/images/product/stickers.58900/thumb.png"];

**Comment by hannahmbanana** [comment]
@boreys: Great question! There are two issues at play here: (1) the limits of ASDK's gif support and (2) the fact that a size is required to layout all ASDK image nodes. 

I believe that ASNeworkImageNode's gif support was not designed to support a large number of gifs. Depending on the size of the gifs (resolution, length), it could take a significant amount of memory and disk space to decode them, especially with many in a scrolling view. @garrettmoon: could you provide some insight on the limits of gif support?

If your goal is to show small (~20x20) gifs embedded in the text of the comments, I believe I have seen this done using a node as an attachment to the attributed string provided to the ASTextNode.

Comments on your code:

1. You can delete the imageNodeDidFinishDecoding: method. It is not needed in this use case. 

2. Your layoutSpecThatFits code is very close to working. However for image nodes specifically, you will need to specify the size of the node. This is confusing and not very well documented so I apologize. One way to do this is using the mediaNode.preferredFrameSize property. You could set this either in layoutSpecThatFits or in the imageNode:didLoadImage: method. 

3. FYI - layoutSpecs and nodes both conform to the ASLayoutable protocol, which means that you can mix and match them in the setChildren method. A more clean (and extensible) way to implement the layout you have would be to do something like below. Check out how the mediaNode is vertically stacked with the commentsNode inside the mainStack. 

 it could be cleaned up  has an issue. 
```
-(ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
  ASStackLayoutSpec *verticalStack = [ASStackLayoutSpec verticalStackLayoutSpec];
  verticalStack.spacing = INTER_COMMENT_SPACING;
  [verticalStack setChildren:_commentNodes];
  
  mediaNode.preferredFrameSize = CGSizeMake(20,20);
  ASStackLayoutSpec * mainStack = [ASStackLayoutSpec verticalStackLayoutSpec];
  mainStack.spacing = INTER_COMMENT_SPACING;
  [mainStack setChildren:@[verticalStack, mediaNode]];
  return mainStack;
}
```

**Comment by hannahmbanana** [comment]
@boreys: there's a related PR (#1723) open that says that animated images are paused while scrolling currently, so you may have been seeing some of that.

**Comment by boreys** [comment]
It works!... thank you @hannahmbanana

**Comment by hannahmbanana** [comment]
@boreys: glad it works! Let me know if you run into any other issues. 

Also, feel free to join our slack channel (#1582) for more help.
