### ISSUE TITLE
ASMapNode does not show map, mapView nil

### ISSUE THREAD

**Issue by borut-t** [facebook/AsyncDisplayKit#1736]
Adding ASMapNode() to a view does not show map at all. There is just one gray rectangle presented.
Since there is no documentation about its usage, could you please direct me how to properly integrate ASMapNode to show map view?

Here is the initialization code.
```Swift
private lazy var mapNode: ASMapNode = {
	let node = ASMapNode()
	node.liveMap = true
	node.mapDelegate = self
	node.preferredFrameSize = CGSize(width: 300, height: 300)
	
	let coord = CLLocationCoordinate2DMake(37.7749, -122.4194);
	node.region = MKCoordinateRegionMakeWithDistance(coord, 20000, 20000);
	
	node.mapView?.mapType = MKMapType.Standard
	node.mapView?.showsUserLocation = true
	
	//self.contentView.addSubview(node.view)
    self.contentView.addSubnode(node)
	return node
}()
```

**Comment by maicki** [comment]
@borut-t How do you set the size / layout the map node?

Look into the `AsyncDisplayKitOverview` example for a basic implementation that shows a part of San Francisco:

```objc
// San Francisco
CLLocationCoordinate2D coord = CLLocationCoordinate2DMake(37.7749, -122.4194);
mapNode.region = MKCoordinateRegionMakeWithDistance(coord, 20000, 20000);
```

**Comment by borut-t** [comment]
@maicki I've updated init code, but I still get empty gray box.
I layout node by setting its frame

```Swift
mapNode.frame = CGRect ...
```

This is the rectangle node I get:
![screen shot 2016-06-10 at 08 04 49](https://cloud.githubusercontent.com/assets/677166/15955512/1f5816e2-2ee2-11e6-9b20-a8c56a3f631f.png)

**Comment by appleguy** [comment]
mapView should indeed be nil unless you need to turn on .liveMap (this is inefficient so avoid it unless not in a scrollable view and the user must interact with the map).

Can you go in the debugger and do "po [[UIWindow keyWindow] recursiveDescription]", then include the full results here?  What rectangle are you setting?  What about the way the node is added to its parent?

		-- Scott

**Comment by borut-t** [comment]
It looks like MKMapView frame is not set. Is this intended?

```
<MyApp.ReportMapCell: 0x7fd40087b000; baseClass = UITableViewCell; frame = (0 478; 320 245); autoresize = W; layer = <CALayer: 0x7fd40246ba00>>
   | <UITableViewCellContentView: 0x7fd40246c800; frame = (10 0; 300 245); gestureRecognizers = <NSArray: 0x7fd4024847c0>; layer = <CALayer: 0x7fd400674680>>
   |    | <UILabel: 0x7fd4024b71c0; frame = (5 15; 310 30); userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fd4024b73d0>>
   |    | <<ASMapNode: 0x7fd400877a00>, view = <_ASDisplayView: 0x7fd4022b8350; frame = (0 45; 300 160); clipsToBounds = YES; layer = <<ASMapNode: 0x7fd400877a00>, layer = <_ASDisplayLayer: 0x7fd4022b7e90>>>>
   |    |    | <MKMapView: 0x7fd4022b87f0; frame = (0 0; 0 0); clipsToBounds = YES; layer = <CALayer: 0x7fd4022ca5c0>>
   |    |    |    | <_MKMapContentView: 0x7fd4007cf1f0; frame = (0 0; 0 0); clipsToBounds = YES; autoresizesSubviews = NO; gestureRecognizers = <NSArray: 0x7fd4022d9970>; layer = <CALayer: 0x7fd4007caaf0>>
   |    |    |    |    | <MKBasicMapView: 0x7fd4007d0040; frame = (0 0; 0 0); clipsToBounds = YES; layer = <CALayer: 0x7fd40077f3e0>>
   |    |    |    |    |    | <_MKMapLayerHostingView: 0x7fd4007d07a0; frame = (0 0; 0 0); layer = <_MKMapLayerHostingLayer: 0x7fd4007641d0>>
   |    |    |    |    |    |    | <VKMapView: 0x7fd4007d1530> (layer)
   |    |    |    |    |    |    |    | <GGLLayer: 0x7fd4007d4fc0> (layer)
   |    |    |    |    | <MKScrollContainerView: 0x7fd4022d5730; frame = (0 0; 2.68435e+08 2.68435e+08); autoresizesSubviews = NO; layer = <CALayer: 0x7fd4022d5b20>>
   |    |    |    | <MKNewAnnotationContainerView: 0x7fd4022d5e50; frame = (0 0; 0 0); autoresize = W+H; autoresizesSubviews = NO; layer = <CALayer: 0x7fd4022d6310>>
   |    |    | <MKAttributionLabel: 0x7fd4022e0e50; baseClass = UILabel; frame = (11 -20; 25 11); text = 'Legal'; alpha = 0.5; autoresize = RM+TM; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fd4022e1070>>
```

**Comment by aaronschubert0** [comment]
@borut-t @appleguy I was under the assumption that `measure` has to be called on a node if it's added to UIView manually?

**Comment by borut-t** [comment]
@aaronschubert0 You are correct. I've added call for this method and now it shows correctly. Thanks!

**Comment by borut-t** [comment]
Ok, now after we've managed to get things running I still question myself why to use ASMapNode at all if I need user interaction on maps? There is no benefit using this (performance wise) instead of MKMapView. But this is probably matter of another discussion.

**Comment by maicki** [comment]
1. For the initial discussion, if this PR lands: #1725 than it's not necessary to call `measure:` anymore, setting the frame and adding it to the view should be enough
2. In terms of why you should use `ASMapNode`. In terms of performance wise that I think that's true if you want to show a live map that there are no benefits, but it's way easier to use it in a node hierarchy where you use nodes from the top to bottom anyway than use a `MKMapView` and wrap it in a `ASDisplayNode`.

**Comment by borut-t** [comment]
@maicki Thanks for clarification.

**Comment by appleguy** [comment]
@borut-t one benefit is that you can include it in an ASLayoutSpec tree, allowing other elements in the layout to react to the map's presence.

If there is literally no need for the map other than in the interactive state, the performance benefits are limited.  However, if for example it is in a scrolling view and the user can tap the map to take it fullscreen (a very common case), there are tremendous performance benefits - not just from the snapshotter, but automatic management of preloading the map, memory cleanup, transitioning to and from the live map, etc.

If your only use case is to go directly from a screen that has no map, to a screen that has an interactive map, and the map is not in a scrollable area, then there's no big win.  There isn't a measurable overhead either though, so from an API consistency perspective it can fit in nicely with other ASDK code.
