### ISSUE TITLE
[ASTextNode] Thread safety issues

### ISSUE THREAD

**Issue by ocrickard** [facebook/AsyncDisplayKit#1739]
Did a quick audit for unprotected ivar access on the mutable ASTextNode instance:

https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L159 (description, if only used in debugging probably doesn't matter, but may as well lock).

https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L288 accesses _renderer outside of the mutex. You must use the property accessor to have safe atomic access. This can crash due to another thread changing _renderer in the middle of your access.

Same https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L294, https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L309, https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L347

Probably obvious, but https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L368 isn't threadsafe.

https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L403

I'm not going to call out all the other properties that aren't threadsafe. I'm assuming that the threading model by the owning callsites/frameworks makes them OK?

In the renderer:

All of these lazy attributes are definitely not safe:

https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/TextKit/ASTextKitRenderer.mm#L58

https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/TextKit/ASTextKitRenderer.mm#L70

https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/TextKit/ASTextKitRenderer.mm#L95

If you're going to move these things to be lazily generated, don't we also have to stop directly using the ivars? https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/TextKit/ASTextKitRenderer.mm#L181

**Comment by appleguy** [comment]
@ocrickard thanks for auditing this!  Yes, we recently discovered that the many recent changes to ASTextNode have broken the threading model.  This is urgent to fix.

Those changes included new features like text resizing, but many issues were introduced by moving to the instance method drawing + perhaps especially some general refactoring that altered the initialization codepath.

@ocrickard let us know if you are planning anything else here — no worries, we can pick up from here if you are moving on.  This is a generous contribution!  I want to make sure the fixes for this stuff don't collide between multiple engineers.

**Comment by ocrickard** [comment]
Sweet, yeah, I probably don't have time to fix this myself right now, especially if it's urgent for you folks. Happy to help review diffs though!

**Comment by hannahmbanana** [comment]
@ocrickard: If you have time, it would be great if you could review what landed and let us know if there are any other issues you see.

**Comment by appleguy** [comment]
@ocrickard I think we're in pretty good shape here now.  Let us know if you notice any other clear issues and we'll prioritize them.

@shannonma FYI ^.  Interested on how your version upgrade goes!  We do plan to refactor / improve the architecture of ASTextNode in the next 2 months, but it will probably be August or September.
