### ISSUE TITLE
Documentation next button returns 404

### ISSUE THREAD

**Issue by FranciscoAmado** [facebook/AsyncDisplayKit#1745]
Hi guys,

Small thing, I've noticed in the ["Getting Started" Documentation page](http://asyncdisplaykit.org/docs/getting-started.html) the "Next ->" Button is broken, leading to a 404 Page, as are the other next buttons in the remaining topics.
This is misleading. I suggest linking it to the next topic ["Philosophy"](http://asyncdisplaykit.org/docs/philosophy.html) and so on?!

**Comment by maicki** [comment]
cc @hannahmbanana

**Comment by hannahmbanana** [comment]
@FranciscoAmado: thanks for the heads up! It should be fixed now.
