### ISSUE TITLE
[ASMapNode] Toggling liveMap on does not enable touches

### ISSUE THREAD

**Issue by george-gw** [facebook/AsyncDisplayKit#1753]
Scenario:
1- Create `ASMapNode`
2- At some point during the app, toggle `liveMap = true`
3- Map does not receive touches
Solution:
when you set `liveMap = true`, set `mapNode.userInteractionEnabled = true`

Looking at the code, I saw that `self.userInteractionEnabled = YES` is only enabled in `didLoad` of `ASMapNode` when the node is created with `liveMap = true`, was there a reason for it to be that way rather than enabling and disabling it in `addLiveMap` and `removeLiveMap` respectively?

**Comment by hannahmbanana** [comment]
@george-gw: Great question - thanks for watching out for the consistency of ASDK's API!

@aaronschubert0: It looks like you were the original author of this feature. Could you weigh in on this? Was this the intended behavior?

**Comment by hannahmbanana** [comment]
@george-gw: I just checked out the code and this does seem to be an oversight rather than a feature. Do you feel confident putting up a pull request for this?

**Comment by hannahmbanana** [comment]
@george-gw: I tested this and userInteraction _is_ enabled after setting liveMap=YES (sometime after creating the map node). However, it seems that the mapNode is capturing the touch events.

**Comment by aaronschubert0** [comment]
@hannahmbanana @george-gw Yeah seems to be an oversight, strange it wasn't flag earlier. @george-gw happy for you to submit a PR for this if you wish (so you can test on your specific scenario), otherwise I can fix it.

**Comment by george-gw** [comment]
@hannahmbanana I have added an Example in the pull request, I don't know if this should be there, but it's a way for you to test out the different solutions, you can actually take that code and run it on the old version (without my changes) to see the differences.
I have also NSLoged the userInteractionEnabled variable so you can see its value as you tap the toggle button to switch liveMap on and off.
