### ISSUE TITLE
[ASMapNode] Setting region on ASMapNode doesn't work when liveMap = false

### ISSUE THREAD

**Issue by george-gw** [facebook/AsyncDisplayKit#1754]
Scenario:
1- Create `ASMapNode`
2- Set region with `mapNode.region = /* new region */`

Expected result: snapshot shows the map at region
Actual result: snapshot shows the world map

Workaround:
1- Create new: `MKMapSnapshotOptions`, let's call it `newOptions`
2- Set same options as `mapNode.options` to it // for consistency's sake
3- Change `newOptions.region = /* new region */`
4- Set new options: `mapNode.options = newOptions`

**Comment by hannahmbanana** [comment]
@george-gw: this also looks like it is a bug. I'll go ahead and submit a PR to fix it.
