### ISSUE TITLE
ASImageNode+Animated: set default run loop mode to common?

### ISSUE THREAD

**Issue by eanagel** [facebook/AsyncDisplayKit#1770]
I noticed that @ejensen has made the run loop configurable for animated images (in #1723, thanks!) and that's probably because he encountered the same issue as I did. With the default run loop mode we use (`NSDefaultRunLoop`) animated images pause while they are scrolling if they are in a scroll view. Thanks to @ejensen that can now be fixed by setting `animatedImageRunLoopMode` to `NSRunLoopCommonModes`.

I suspect most users would expect an animated image to continue animating while scrolling. While there is a fix (set `imageNode.animatedImageRunLoopMode = NSRunLoopCommonModes` on any nodes that are in a scroll view), it's not the default functionality and it's not obvious what needs to be done without some research.

I think it makes more sense to make `NSRunLoopCommonModes` the default and send the developer what wants animated images to pause while scrolling digging for the answer (they will likely be thinking about performance tuning, hopefully they would find it quickly.) This would be a breaking change technically, but I think it would be a good one to make pre-2.0.

In looking at the PR comments, @koheku had a really interesting [suggestion](https://github.com/facebook/AsyncDisplayKit/pull/1723#issuecomment-224858795) from FLAnimated image. Maybe this is an even better overall solution.

Thoughts? @ejensen @appleguy @garrettmoon @koheku

**Comment by appleguy** [comment]
In one of the other threads, we'd actually made a decision to change the default.  @eanagel @ejensen could one of you submit a PR?

**Comment by eanagel** [comment]
I'll submit the PR, thanks!

**Comment by maicki** [comment]
Closing this issue as the PR was merged. Thanks @eanagel again!
