### ISSUE TITLE
[ASCollectionView] Add support for supplementary nodes to the range controller

### ISSUE THREAD

**Issue by levi** [facebook/AsyncDisplayKit#1774]
The range controller currently only intelegently preloads nodes in a collection view. We can actually hook into supplementary view visibility events to provide robust preloading support.

**Comment by hannahmbanana** [comment]
I'm going to move this to our internal feature tracking tool to investigate for the 2.0 release. 

If anyone from the community would like to work on this, let us know and we'd be happy to help you!
