### ISSUE TITLE
[ASLayoutable] about flexBasis question

### ISSUE THREAD

**Issue by Coramo** [facebook/AsyncDisplayKit#1775]
Hi all,

My code:

````

for i in 0 ... 2 {
    let rowStack = ASStackLayoutSpec()
    func createImageSpec(node:ASDisplayNode) -> ASLayoutable {
        let spec = ASRatioLayoutSpec(ratio: 1, child: node)
        spec.flexBasis = ASRelativeDimensionMakeWithPercent(0.3333333)
        return spec
    }
    
    rowStack.spacing = 0
    rowStack.setChildren([
        createImageSpec(contentImages[i*3]),
        createImageSpec(contentImages[i*3+1]),
        createImageSpec(contentImages[i*3+2])
        ])
    contentChildren.append(rowStack)
    
}

````
And screenshot : 

![screenshot](https://raw.githubusercontent.com/Coramo/Resources/master/QQ20160619-0%402x.png)

Then, I change the my code : 
````
rowStack.spacing = 0
````
to
````
rowStack.spacing = 8
````
![screenshot](https://raw.githubusercontent.com/Coramo/Resources/master/QQ20160619-1%402x.png)

The image width is wrong.

Why `ASStackLayoutSpec` calculate not like this ? : 
````
( width-(space * (itemCount-1) ) ) / percent
````

Or how can i fix it?

**Comment by hannahmbanana** [comment]
@Coramo: Would it be possible to attach a sample project? Command + D on any project folder to duplicate the folder. Then you can strip out any unnecessary code. Thanks!

**Comment by appleguy** [comment]
This should definitely be fixable, let us know if you have any challenges with providing a sample project based on any existing app in examples/.  Although this is a bit inconvenient to prepare, it would allow us to iterate and answer your questions much more quickly!

**Comment by Coramo** [comment]
Hi, @appleguy  @hannahmbanana 
Sample project is in here .

https://github.com/Coramo/ASDKSample

Hope this can help you.

**Comment by maicki** [comment]
@Coramo Looked into your Sample Project. You have to set the `ASRatioLayoutSpec` to flexShrink = true:

```
func createImageSpec(node:ASDisplayNode) -> ASLayoutable {
    let spec = ASRatioLayoutSpec(ratio: 1, child: node)
    
    spec.flexBasis = ASRelativeDimensionMakeWithPercent(0.33333)
    spec.flexShrink = true
    return spec
}
```

**Comment by Coramo** [comment]
@maicki  Thank you. this is working.
