### ISSUE TITLE
PinRemoteImage only supported via CocoaPods

### ISSUE THREAD

**Issue by nickvelloff** [facebook/AsyncDisplayKit#1780]
Issue 1:
ASDK uses preprocessor macros to declare `PIN_REMOTE_IMAGE` that are defined in the Podspec, thus only available to CocoaPods build.

Issue 2:
`PinRemoteImage` must be forked and example projects removed to actually build cleanly. Really old issue for this repo, here: https://github.com/pinterest/PINRemoteImage/issues/25#issuecomment-227062812

Basically every attempt to resolve this leads to a fork. 

@hannahmbanana Thanks!

**Comment by nickvelloff** [comment]
BTW it's perfectly reasonable to say "only supported via CocoaPods"... 
Personally I was just trying to avoid CocoaPods, but rather that than maintain a fork on a rapidly changing framework.

**Comment by nickvelloff** [comment]
Example using manually added dynamic framework:
https://github.com/nickvelloff/ASDK-DynamicLib.git

Example using Carthage build, with PinRemoteImage fork to resolve build issue:
https://github.com/nickvelloff/ASDK-DynamicLib/commit/83b5e4c81411493e05d8023bd710cb9661bd4765

**Comment by hannahmbanana** [comment]
Similar issue at #1464.

**Comment by hannahmbanana** [comment]
Update:  With the addition of the cartfile + work around for the PIN_REMOTE_IMAGE flag for non-Cocoapod users, **AsyncDisplayKit now support the standard way to use Carthage**:

_The standard way to use Carthage is by having a Cartfile listing the dependencies, and then running carthage update to download them in the Cathage/Checkouts folder, and build each of those into frameworks located in the Carthage/Build folder, and finally the developer has to manually integrate in the project._

AsyncDisplayKit does not yet support the lighter way of using Carthage, in which you manually add the project files.
http://www.mokacoding.com/blog/carthage-no-build/

**Comment by maicki** [comment]
![happy](https://cloud.githubusercontent.com/assets/25288/16288883/288fc22e-38a5-11e6-821d-49b0dcce8794.gif)

**Comment by nickvelloff** [comment]
@hannahmbanana woohoo! 🚀 🎸 👍

**Comment by hannahmbanana** [comment]
...but I wasn't done? Still not ready to give up on the "lighter Carthage method" :)
