### ISSUE TITLE
[ASVideoNode] Placeholder images are replaced by a blank placeholder

### ISSUE THREAD

**Issue by gazreese** [facebook/AsyncDisplayKit#1782]
I need to use placeholder images in my project, so I've been using the HEAD code to get hold of the functionality. It appears that even though I'm setting the placeholder via the .URL property, this quickly gets overwritten with a generated placeholder. This generated placeholder takes just as long as the video to load however, and in the mean time has a blank image that overrides the supplied one in .URL. The result of this is that the user sees, in this order:

- The placeholder image
- A blank box
- The video-derived placeholder
- The video then starts to play

I'll attach a suggested change / pull request that seems to fix this behaviour, along with changes to the Video example app to add an HLS video and placeholder. It's difficult to show the problem in the example app, but if you swap out the HLS video URL for something higher bitrate it's easier to see.

There are a lot of HLS example URLs here:
http://stackoverflow.com/questions/10104301/hls-streaming-video-url-need-for-testing

Not a lot of these URLs work inside ASDK however, which may be indicative of other problems. I'm not sure. The links work fine in QuickTime on a Mac.

**Comment by gazreese** [comment]
The first commit had some project file changes in it that seemed to be caused by a difference in Cocoapods versions. I've done a second branch and pull request https://github.com/facebook/AsyncDisplayKit/pull/1788 that covers the changes cleaned up.

There also appeared to be old versions of the ASVideoNode source files inside the Video example. Didn't look like they were supposed to be there but I've not removed them in this change just in case.

**Comment by Adlai-Holler** [comment]
Closed via #1788.
