### ISSUE TITLE
[ASEditableTextNode]: no shouldReturn method?

### ISSUE THREAD

**Issue by benjaminhorner** [facebook/AsyncDisplayKit#1784]
ASEditableTextNode does not seem to have a shouldReturn method. As the view of an ASEditableTextNode is NOT a UITextField but a UITextView, so there doesn't seem to be a way to capture when a user hits the return key on the keyboard…

As most users have gotten used to hitting it to go to the next field or "submit" an action, this would be a very handy method to have.

**Comment by maicki** [comment]
@benjaminhorner You can use `- (BOOL)editableTextNode:(ASEditableTextNode *)editableTextNode shouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text;` delegate method of the `ASEditableTextNode` and check if the text is the return key something like that:

```Objc
- (BOOL)editableTextNode:(ASEditableTextNode *)editableTextNode shouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text
{
    if( [text rangeOfCharacterFromSet:[NSCharacterSet newlineCharacterSet]].location == NSNotFound ) {
        return YES;
    }

    [editableTextNode.textView resignFirstResponder];
    return NO;
}
```

**Comment by benjaminhorner** [comment]
@maicki Thanks! I was just about to edit my question and say I had come up with a solution (the exact same one as yours. Can be closed I guess…
Thanks for the quick response
