### ISSUE TITLE
[Question] How to received touch inputs

### ISSUE THREAD

**Issue by modLX4** [facebook/AsyncDisplayKit#1789]
![img_0318](https://cloud.githubusercontent.com/assets/12533332/16226260/3de20f02-37c8-11e6-8499-6356913752b7.PNG)

I want to add an IBAction-kind touch up inside call back when user touches on the image view (ASNetworkImageNode). 

I just started learning ADK 2 days ago. 
@Scott Goodson -- This is FFFFINGG Awesome man.
Thanks.

**Comment by hannahmbanana** [comment]
@modLX4: Glad you like the framework! AsyncDisplayKit does not support Interface Builder (or UIKit's autolayout). You can get touch events on any one of the ASControlNodes - ASButtonNode, ASImageNode, ASNetworkImageNode, ASTextNode, ASMapNode - with the `addTarget:action:forControlEvents:` method. 

See more here: http://asyncdisplaykit.org/docs/control-node.html

Check out the ASDKgram sample app! It's a great example showing a social media feed with the UIKit implementation and a parallel ASDK implementation.

**Comment by modLX4** [comment]
@hannahmbanana - Thank you. Are there any support group or communities ?

**Comment by hannahmbanana** [comment]
@modLX4: Check out our Slack channel! See #1582 for directions to join.

**Comment by Ghana93** [comment]
I added this code in likeNode, but buttonTapped is not getting called, can you help?
  
    [self addTarget:self action:@selector(buttonPressed:) forControlEvents:ASControlNodeEventTouchUpInside];

    -(void)buttonPressed:(id)sender {
         NSLog(@"Like Button Pressed");
    }
