### ISSUE TITLE
cornerRadius not work properly

### ISSUE THREAD

**Issue by tangbl93** [facebook/AsyncDisplayKit#1799]
in my cell node,i have set the cornerRadius property, but the effect is not my want.
the left && right bottom corner no effetc.

![simulator screen shot 2016 6 22 6 03 44](https://cloud.githubusercontent.com/assets/13956214/16262770/aef0fe0c-38a3-11e6-9b51-f653001ff756.png)

the code is here,the `self.contentNode` cornerRadius seems useless.tks
```
- (instancetype)init {
	self = [super init];
	
	if (self) {
		
		self.backgroundColor = [UIColor tt_magicColor:@"d2d2d2"];
		self.selectionStyle = UITableViewCellSelectionStyleNone;
		
		self.contentNode = [[ASDisplayNode alloc] init];
		self.contentNode.backgroundColor = [UIColor whiteColor];
		
		self.contentNode.layer.cornerRadius = 15;
		self.contentNode.layer.masksToBounds = YES;
		[self addSubnode:self.contentNode];
		
		/// 用户信息
		self.uInfoNode = [[ASImageNode alloc] init];
		self.uInfoNode.image = gswImage;
		[self.contentNode addSubnode:self.uInfoNode];
		
		self.uAvastarNode = [[ASNetworkImageNode alloc] init];
		self.uAvastarNode.defaultImage = gswImage;
		self.uAvastarNode.layer.cornerRadius = 25;
		self.uAvastarNode.layer.masksToBounds = YES;
		[self.uInfoNode addSubnode:self.uAvastarNode];
		
		self.uNameNode = [[ASTextNode alloc] init];
		self.uNameNode.maximumNumberOfLines = 1;
		self.uNameNode.truncationMode = NSLineBreakByTruncatingTail;
		[self.uInfoNode addSubnode:self.uNameNode];
		
		self.uMsgNode = [[ASTextNode alloc] init];
		self.uMsgNode.maximumNumberOfLines = 1;
		self.uMsgNode.truncationMode = NSLineBreakByTruncatingTail;
		[self.uInfoNode addSubnode:self.uMsgNode];
		
		
		
		
		/// 游戏信息
		self.gInfoNode = [[ASDisplayNode alloc] init];
		self.gInfoNode.backgroundColor = [UIColor whiteColor];
		[self.contentNode addSubnode:self.gInfoNode];
	}
	
	return self;
}
```

**Comment by EviluS** [comment]
Is there any chance that the contentNode is bigger than the cell?

**Comment by maicki** [comment]
@tangbl93 Try set `self.contentNode.clipsToBounds = YES;`

**Comment by tangbl93** [comment]
@EviluS thk,u are right
@maicki thk you too, is there any different between `layer.cornerRadius` and `cornerRadius`,i only know it is a uiviewbridge property

**Comment by appleguy** [comment]
Curious what the solution was here.  Note that cornerRadius on CALayer is very inefficient and should be avoided if at all possible…

**Comment by maicki** [comment]
cc @tangbl93 Can you please give a bit more information how you solved this issue? There are different ways to achieve rounded corners and as @appleguy mentioned setting a `cornerRadius` on CALayer is not the most efficient one.
