### ISSUE TITLE
[ASViewController] Modal presented ASViewController don't rotate on iOS 8.3

### ISSUE THREAD

**Issue by stephenkopylov** [facebook/AsyncDisplayKit#1810]
Hi all!
Minimum supported ios version in my project is 8.3 and I use a lot of AsyncDisplayKit features in it. 
But some time ago I faced this strange problem: modal presented ASViewController don't rotate after changing interface orientation. In version > 9.0 it works perfectly, but not in 8.3.

What I tried (and it doesn't help): 

```objectiveC
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    return YES;
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations
{
    return UIInterfaceOrientationMaskAll;
}
```

Screenshots:
![img_0049](https://cloud.githubusercontent.com/assets/5202281/16346400/cb0b8c08-3a4f-11e6-8daa-e1d763f0f4b6.jpg)
![img_00491](https://cloud.githubusercontent.com/assets/5202281/16346401/ce4e7448-3a4f-11e6-8342-1c773a19f31d.jpg)

Sample project:
[ModalASViewController.zip](https://github.com/facebook/AsyncDisplayKit/files/332274/ModalASViewController.zip)

**Comment by hannahmbanana** [comment]
@stephenkopylov: Thanks for the sample project & clear diagram. We will check this out and get back to you soon!

**Comment by appleguy** [comment]
Levi has the best knowledge of rotation at the moment, but he is away for another week or so.

**Comment by maicki** [comment]
I looked into that briefly and that is what we get when we call `self.view.bounds` in `viewWillLayoutSubviews:`

```
iOS 8
(ASSizeRange) $3 = (min = (width = 375, height = 667), max = (width = 375, height = 667))

iOS 9
(ASSizeRange) $0 = (min = (width = 667, height = 375), max = (width = 667, height = 375))
```

**Comment by hannahmbanana** [comment]
@stephenkopylov: @maicki posted a PR for your issue! Try it out and let him know if it worked.

**Comment by stephenkopylov** [comment]
@hannahmbanana 
Big thanks to @maicki! Now it works absolutely perfect!
And it would be nice to push this fix to cocoapods... how long it can takes? =)

**Comment by hannahmbanana** [comment]
@stephenkopylov: Thanks for reporting back! We plan on doing the 1.9.81 release soon. This should hopefully make it into that release.
