### ISSUE TITLE
[Swift] ASPINRemoteImageDownloader and PINCache public access

### ISSUE THREAD

**Issue by peymayesh** [facebook/AsyncDisplayKit#1815]
Is there anyway I can access to `PINRemoteImageManager` and `PINCache` that I included in `ASDK` in my project? How can I make it public?

Also I need to use PINCache inside my project for other purposes, now I have to duplicate `import PINCache`, one in `ASDK` and other in my project, and handling the cache is a nightmare for me.
I would be pleased to know how can I manage this situation?
Thanks! :)

**Comment by appleguy** [comment]
Have you tried expressions such as:

[[[[ASPINRemoteImageDownloader sharedDownloader] sharedPINRemoteImageManager] cache] diskCache]  ?

**Comment by peymayesh** [comment]
I'm using Swift and I'm using `ASDK` as `Embedded Binary` (using `import AsyncDisplayKit`, not bridgingHeader).

**Comment by peymayesh** [comment]
The problem is that `ASPINRemoteImageDownloader.h` is in project headers and is not public.

**Comment by appleguy** [comment]
@Adlai-Holler: This seems important to expose this, but what are the implications if PINRemoteImage isn't linked and someone were to call into it? Do we need to add a runtime check to make sure nil isn't returned?

**Comment by Adlai-Holler** [comment]
@appleguy I think this would be safe to expose, since that entire header is wrapped in `#if PIN_REMOTE_IMAGE` so nothing will be compiled unless they're using it. I've confirmed that the behavior is correct in Swift after making the change @peymayesh suggested.

@peymayesh I've linked a PR that publicizes that header. Is it a winner?

**Comment by maicki** [comment]
@Adlai-Holler What if other projects have PINRemoteImage as an explicit dependency?

**Comment by Adlai-Holler** [comment]
No they won't clash – although if they want to use a different version of PINRemoteImage then they must use our Core subspec to avoid conflicts in CocoaPods.

**Comment by maicki** [comment]
I'm not pretty sure if it's good to expose it to be honest. I'm pretty sure people will run into CocoaPods issues due to that.
