### ISSUE TITLE
[Swift] NSIndexSet+ASHelpers.m is missing for Swift users, can cause a crash

### ISSUE THREAD

**Issue by CR34L** [facebook/AsyncDisplayKit#1826]
to reproduce: running on SWIFT XCode Version 7.3.1 (7D1014)
`let set = NSIndexSet(index: self.sectionLocationNode);
self.mainView.performBatchUpdates({
  self.mainView.reloadSections(set);
  }, completion: { finished in
  // do nothing
  });`

temp workaround:

`let path = NSIndexPath(forItem: 0, inSection: self.sectionLocationNode);
        self.mainView.reloadItemsAtIndexPaths([path]);`

stack trace:
-[_NSCachedIndexSet as_indexesByMapping:]: unrecognized selector sent to instance 0x7f878148e790
2016-06-28 21:53:36.320 qwuut[91877:46318156] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_NSCachedIndexSet as_indexesByMapping:]: unrecognized selector sent to instance 0x7f878148e790'

So maybe I am doing something wrong?

All updates are on mainthread context.

**Comment by CR34L** [comment]
Going on: Error thrown in _ASHierarchyChangeSet.m, - (void)_sortAndCoalesceChangeArrays, Line Number 213

**Comment by hannahmbanana** [comment]
@CR34L: What version of AsyncDisplayKit are you using? Did this previously work for you?

**Comment by CR34L** [comment]
@hannahmbanana: latest checkout 1812 from yesterday (28.07.), Previously it worked fine without any problems.

**Comment by Adlai-Holler** [comment]
@CR34L Sorry about this issue, and thanks for providing a complete report! We'll get it sorted out.

I created a simple Swift project to reproduce this but no dice – the call that is throwing an exception `-[_NSCachedIndexSet as_indexesByMapping:]` is working correctly:

![screen shot 2016-06-29 at 10 02 42 am](https://cloud.githubusercontent.com/assets/2466893/16461405/41ad5d2a-3de1-11e6-9f02-69e1bf041d8f.png)

#1812 added in a new file, which it seems is not being compiled in your case. A couple questions so I can hopefully get this fixed:
- How are you importing AsyncDisplayKit? If CocoaPods/Carthage, what version are you using?
- Does the file `NSIndexSet+ASHelpers.h/.m` exist in Xcode?
- Does "Clean Build Folder" (Alt+Shift+Cmd+K) in Xcode fix the issue?
- Would you try this reduced case and see if it works?
[SwiftIssueDemo.zip](https://github.com/facebook/AsyncDisplayKit/files/339802/SwiftIssueDemo.zip)

I'm glad you've got a workaround for the time being, and we'll get this sorted out ASAP.

**Comment by CR34L** [comment]
Going to try it. Give me a couple of minutes to do this. 

I dont use CocoaPods/Carthage - all is done manually using GitHub Desktop. I check out needed repos directly into my vendors folder which is imported in any of my projects. So you mentioned a new file - may be it is not imported in my case (but then I have to wonder how the stuff is compiled...)

- "Clean Build Folder" is always done after checking out

**Comment by CR34L** [comment]
@Adlai-Holler: Got some news...

SwiftIssueDemo.zip - unpack, changed pod stuff to local framework copy, imported "AsyncDisplayKit.xcodeproj", embedded binaries setup, run on fresh cleaned Simulator Device (Reset Settings) and:

2016-06-30 12:58:40.919 SwiftIssueDemo[62253:52096394] -[_NSCachedIndexSet as_indexesByMapping:]: unrecognized selector sent to instance 0x7f8b13e22620
2016-06-30 12:58:40.935 SwiftIssueDemo[62253:52096394] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_NSCachedIndexSet as_indexesByMapping:]: unrecognized selector sent to instance 0x7f8b13e22620'

Same issue. 

Checked for the File: NSIndexSet+ASHelpers.m found in /Details/Transactions/

**Comment by CR34L** [comment]
@Adlai-Holler: Found the solution.

--> AsyncDisplayKit.xcodeproj --> AsyncDisplayKit-iOS --> Build Phases --> Compile Sources (115 items) --> NSIndexSet+ASHelpers.m was **missing** there.

Manually added and cleaned and compiled again. AsyncDisplayKit is working now as expected. 

![screen shot 2016-06-30 at 14 40 31](https://cloud.githubusercontent.com/assets/3614596/16488419/bb3b2506-3ed0-11e6-9895-3cb91147675a.png)

**Comment by Adlai-Holler** [comment]
@CR34L Thanks for finding the fix! Could you try latest master and see if it's fixed?

**Comment by CR34L** [comment]
@Adlai-Holler: Tried without luck. Have you put the missing file into Project Settings --> AsyncDisplayKit-iOS Framework Target --> Compile Sources and select the NSIndexSet+ASHelpers.m File? 

In my latest checkout I could not find such an entry.

**Comment by Adlai-Holler** [comment]
@CR34L Oh my mistake! This issue was actually fixed in #1831. Could you try latest master once more and see if it's fixed?
