### ISSUE TITLE
Deadlock in ASDisplayNodeScreenScale()

### ISSUE THREAD

**Issue by secretiverhyme** [facebook/AsyncDisplayKit#183]
Instantiating an ASDisplayNode on the main queue and on a background queue simultaneously can deadlock.  Specifically:

1. Background queue node enters the `dispatch_once()` in `ASDisplayNodeScreenScale()`, locking the once-token, and `dispatch_sync()`s to the main queue.
2. Main queue node enters `ASDisplayNodeScreenScale()` before background node's `dispatch_sync()` starts to execute, but can't pass the `dispatch_once()` until background node returns.
3. Deadlock.

**Comment by rnystrom** [comment]
For anyone curious on this fix, [this blog post](http://benalpert.com/2014/04/02/dispatch-once-initialization-on-the-main-thread.html) has a great writeup on the race condition that we were experiencing as well as the fix.
