### ISSUE TITLE
Approach to ASCollectionView interactive percentage based layout transition

### ISSUE THREAD

**Issue by nickvelloff** [facebook/AsyncDisplayKit#1855]
I want to improve performance with my ASCollectionView, interactive percentage based transition driven by pinch gesture. 

First approach was to expose a new method `relayoutItems` in ASCollectionView which just calls `[_dataController relayoutAllNodes];` .. 

This didn’t (and we knew it wouldn’t) perform very well, but it was a first attempt in allowing a transition between layout classes. It _worked_, but not smoothly.

Next attempt was in my `UICollectionViewTransitionLayout` in `invalidateLayout` get only `visibleNodes` and apply `ASSizeRange` with a calculated `itemSize` based on `transitionProgress` and call `node.measureWithSizeRange(sizeRange).size` and set the `frame`

Again, worked but pretty laggy. So onward to the question:

Would it make sense to explore using the Transition API to size the nodes (presumably visible only) with something like

```
node.transitionLayoutWithSizeRange(
                sizeRange,
                animated: false,
                shouldMeasureAsync: false,
                measurementCompletion: .None
            )
```

in `invalidateLayout` in the same way in `UICollectionViewTransitionLayout` as above?
In the cell node, set the frame in coordination with this as so: 

```
override func animateLayoutTransition(context: ASContextTransitioning) {
        let size0 = context.constrainedSizeForKey(ASTransitionContextToLayoutKey).max
        self.frame = CGRect(origin: self.frame.origin, size: size0)
        context.completeTransition(true)
    }
```

Initial tests seem like better performance, but it seems like it is fighting with scroll position, or something else, not sure.

If not, any other ideas to get this to perform a bit better?

**Comment by hannahmbanana** [comment]
@levi: I know you're super busy with other things, but could you check this out when you have time?

**Comment by appleguy** [comment]
@Adlai-Holler, I think it is possible that your recently landed change would significantly help Nick's use case here.  I think you're the right person to take a look rather than @levi since this is related to collections, not the ASLayoutSpec transitions.

**Comment by Adlai-Holler** [comment]
@nickvelloff Hey I'm glad to help with this! It should be possible to achieve this using only the collection view layout API, without manually setting frames or using the layout transition API.

Would you be willing to upload some sample code so I can see the transition layout you're using etc?

**Comment by nickvelloff** [comment]
@Adlai-Holler Wonderful!
This was created to demonstrate an ASTextNode bug, but has exactly what we need to discuss this as well.
https://github.com/the-grid/TruncationBug-AsyncDisplayKitPlayground

1. The best way to demonstrate this run the playground, press the zoom button.
2. Comment out the hacky way I force the nodes to size during transition: https://github.com/the-grid/TruncationBug-AsyncDisplayKitPlayground/blob/master/Reproduce.playground/Contents.swift#L26-L37
3. zoom again to see the default behavior.

Thanks!!

**Comment by nickvelloff** [comment]
@Adlai-Holler Just for a little more info:
That example is just a snapshot of many different approaches/attempts to size the cells. The _actual_ implementation of this uses the pinch gesture, but that is unrelated to the issue so left out of the example. 
That said, pinch gesture events are super _hot_, so it really thrashes to keep up in anything I have tried.

**Comment by garrettmoon** [comment]
@nickvelloff If this is still an issue, do you mind converting to Swift 3? Sorry we didn't get to this, we're trying to be better about not dropping issues.

**Comment by nickvelloff** [comment]
@garrettmoon Hi. We moved away from the pinch/zoom as it was just not supported well and we are 100% on the ASDK stack with this version of our app. Some time down the road this kind of support would be nice, and I am happy to help if you guys decided to make it a priority.

**Comment by garrettmoon** [comment]
Thanks @nickvelloff !
