### ISSUE TITLE
Assigning to 'BOOL(^__strong)(ASDisplayNode *__strong)'from incompatible type 'bool (^)(ASDisplayNode *__strong)'

### ISSUE THREAD

**Issue by eggswift** [facebook/AsyncDisplayKit#1856]
- iPhone5C
 - iOS8.3(12F70) 
 - Xcode 7.3.1
 - Deployment Target 8.0
 - Base SDK Latest iOS (iOS9.3)

![8297ab4b-cb3a-4fbc-a5a6-045a78664579](https://cloud.githubusercontent.com/assets/15206466/16649150/12563b8e-446a-11e6-9f2a-f6f912c0f080.png)

Can fix with this:
```swift
dispatch_once(&onceToken, ^{
      shouldNotAnimateBlock = ^(ASDisplayNode *node) {
             return (BOOL)(node.shouldAnimateSizeChanges == NO);
      };
});
```

**Comment by BeetLab** [comment]
same problem

**Comment by BeetLab** [comment]
thanks for fix reciept, @eggswift

**Comment by maicki** [comment]
@Adlai-Holler Seems like a regression on master
