### ISSUE TITLE
[ASNetworkImageNodeDelegate] image has no data when image is gif

### ISSUE THREAD

**Issue by dukeow94** [facebook/AsyncDisplayKit#1857]
Hi guys, I'm using version 1.9.80 and I made custom ASCellNode which conforms to ASNetworkImageNodeDelegate.
What I wanted to is to present image from url fully stretched to view's width with maintaining own ratio.
So I made some codes that using ``imageNode.preferredFrameSize`` in 
``
 func imageNode(imageNode: ASNetworkImageNode, didLoadImage image: UIImage) {}
 ``.
It works well if image is not gif. If image is gif, ``image`` has no data.
I tried to achieve same result as jpg or png when image is gif, by using ``imageNode.animatedImage`` or something, but nothing worked.

How can I get gif image's size or ratio correctly?

**Comment by hannahmbanana** [comment]
This looks similar to #1763.

**Comment by hannahmbanana** [comment]
@dukeow94: I'm having trouble understanding your issue. Would it be possible to provide a sample project?

**Comment by dukeow94** [comment]
[Here](https://github.com/dukeow94/ASDK_Sample.git)
I uploaded sample. Use that after ``pod install``.

**Comment by maicki** [comment]
@dukeow94 In the callback you have to check for the `animatedImage` property of the `ASNetworkImageNode` in case you fetch a gif. I changed the code in your sample app so you can see how this is working:

```swift
// MARK: -Not crash but doens't show gif image
if let animatedImage = imageNode.animatedImage {
    animatedImage.coverImageReadyCallback = {(image) in
        let width = animatedImage.coverImage.size.width
        let ratio = UIScreen.mainScreen().bounds.width / width
        imageNode.preferredFrameSize = CGSize(width: UIScreen.mainScreen().bounds.width, height: image.size.height * ratio)
        self.setNeedsLayout()
    }
}
```

So the right way would be to first check if an image is returned and handle it if so otherwise check if an animated image is available and handle that.

cc @garrettmoon Can you take a quick look if this answer covers the issue?

**Comment by garrettmoon** [comment]
@maicki yeah, that's the best solution currently. It might be a good idea to add animated image to the delegate in the future.

**Comment by maicki** [comment]
@dukeow94 I will close that issue for now. Please reopen in case this will not give you the expected result. Thank you!
