### ISSUE TITLE
reloadData, reloadSections:, reloadRowsAtIndexPaths: for ASTableView should mimic UITableView

### ISSUE THREAD

**Issue by cxa** [facebook/AsyncDisplayKit#186]
Curren implementation relies on deleting old cells and inserting new cells, which drives some odd UI effects, e.g. all header titles will be collapsed for a while after calling `reloadData`.

The unexpected collapsed headers:
![Odd] (https://cloud.githubusercontent.com/assets/32127/5502877/32019e10-87ab-11e4-8c7b-3ad61f0c9037.png)

The expected behavior after reloadData, should be displayed immediately:
![Expected](https://cloud.githubusercontent.com/assets/32127/5502880/3e198212-87ab-11e4-93d5-233ea6cd04d0.png)

**Comment by tanliboy** [comment]
I added the batch animation branch, which will resolve your problem by calling beginUpdate & endUpdate.

**Comment by secretiverhyme** [comment]
Closing — #211 has been merged.
