### ISSUE TITLE
[ASVideoPlayerNode] Add support for picture in picture with AVPictureInPictureController

### ISSUE THREAD

**Issue by maxsz** [facebook/AsyncDisplayKit#1866]
Hi all, great work on AsyncDisplayKit, love it :)

As the title suggests: It's currently not possible to use picture in picture on an iPad with ASVideoPlayerNode or ASVideoNode. This is, because  `AVPictureInPictureController` expects a `AVPlayerLayer`, which is currently not exposed.

I'd love to create a pull request for this, but first I wanted to start a discussion on if/how this should be done. I can come up with two options: Expose the `AVPlayerLayer` to `ASVideoNode` (and possibly to `ASVideoPlayerNode`) or handle the `AVPictureInPictureController` setup inside one of those classes and simply add properties and delegate methods to start/stop picture in picture.

Thoughts?

Thanks and best regards,
Max

**Comment by hannahmbanana** [comment]
@maxsz: Are you a part of our AsyncDisplayKit Slack group (#1582)? 

The #asvideonode channel is pretty active with discussion between developers who use ASVideoNode/PlayerNode. That's probably the best place to ask.

**Comment by hannahmbanana** [comment]
Thanks for contributing to the ASDK community with your PR @maxsz!
