### ISSUE TITLE
ASStackLayoutSpec() not in full width

### ISSUE THREAD

**Issue by cdiscla** [facebook/AsyncDisplayKit#1882]
I'm using AsyncDisplayKit to have a more responsive CollectionView.
I have problems showing ASCollectionView header.
I would like to have headers in full width of the collection view to right align the "Lorem ipsum" label but the result is attached and is not good; i would need the red background in the full width and the label on the right.
<img width="314" alt="screen shot 2016-07-11 at 02 05 50" src="https://cloud.githubusercontent.com/assets/1819860/16716993/76a0fecc-470c-11e6-8dad-d8064c332765.png">

I've declared
`    func collectionView(collectionView: ASCollectionView, constrainedSizeForNodeAtIndexPath indexPath: NSIndexPath) -> ASSizeRange {
        let width = collectionView.bounds.size.width
        return ASSizeRangeMake(CGSizeMake(width, 50), CGSizeMake(width, 50)) // Always fill the collection view width
    }
`

and 
`    override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        let headerStack=ASStackLayoutSpec()
        headerStack.justifyContent=ASStackLayoutJustifyContent.End
        headerStack.setChildren([TitleTime!])        
        return headerStack
}`
where TitleTime is the simple LoremIpsum ASTextNode() in the image
What am i doing wrong?

Thanks in advance and thanks for this great library, i'm developing a complex project with videos in collectionViews that need non-laggy interfaces.

**Comment by hannahmbanana** [comment]
@cdiscla: could you provide a sample project (cmd + D on the project folder)? 

It's much easier to debug layoutSpecs with actual code in front of me. :)

**Comment by maicki** [comment]
@cdiscla Your `headerStack` currently shrink to the size of the `TitleTime` node. You have to set a `preferredFrameSize` to the `TitleTime` or set a `sizeRange` for the `headerStack` with `size = constrainedSize.max`

**Comment by cdiscla** [comment]
@maicki thanks for your message, i've tried with the two suggestions but the result is still the same, there must something wrong somewhere.
@hannahmbanana thank you, i attach the two files where i have the problem (ASCollectionView and ReusableView), the whole project is too big.
Thanks in advance !

[Archive.zip](https://github.com/facebook/AsyncDisplayKit/files/356285/Archive.zip)

**Comment by appleguy** [comment]
Michael - preferredFrameSize should not be required for right-alignment, correct?

We'll try to take a look at the sample project soon - thanks for sending it!  Join us on Slack if you aren't already, might be faster to coordinate :)

**Comment by maicki** [comment]
@scottg it is necessary I guess as the header stack will shrink to the size of the text node and so you can set it to align right but it does nothing.

@cdiscla did you wrap the stack in a static layout spec?

**Comment by maicki** [comment]
@cdiscla Just confirmed that's the code you want to have:

```swift
class HeaderNode: ASDisplayNode {
    
    let textNode = ASTextNode()
    
    override init() {
        super.init()
        
        textNode.attributedText = NSAttributedString(string: "Some String")
        textNode.backgroundColor = .redColor()
        self.addSubnode(textNode)
    }
    
    override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        let headerStack = ASStackLayoutSpec()
        headerStack.justifyContent = ASStackLayoutJustifyContent.End
        headerStack.setChildren([textNode])
        headerStack.sizeRange = ASRelativeSizeRangeMake(ASRelativeSizeMakeWithCGSize(CGSizeMake(constrainedSize.max.width, 0)),
                                    ASRelativeSizeMakeWithCGSize(constrainedSize.max))
        headerStack.setChildren([textNode])
        return ASStaticLayoutSpec(children: [headerStack])
    }
}
```

**Comment by cdiscla** [comment]
Great @maicki , it runs fine !
Thank you very much, guys!

**Comment by BKRApps** [comment]
for the latest versions, use the below code snippet.
```
let horizontalStack = ASStackLayoutSpec()
horizontalStack.direction = .horizontal
horizontalStack.style.minSize = CGSize(width: 375, height: 0) // 375 max width // UIScreen.main.bounds.size.width
horizontalStack.style.maxSize = CGSize(width: 375, height: 200) // 200 or  max height according to requirement
horizontalStack.children = [nameNode, addressNode]

```
