### ISSUE TITLE
[Question] Scrolling NavBar like Facebook App on UIViewController with ASTableView

### ISSUE THREAD

**Issue by robmontesinos** [facebook/AsyncDisplayKit#1898]
I am trying to implement a scrolling NavBar using the library TLYShyNavBar (or any other that would work). It doesn't work on my viewController with an ASTableView.

```ObjectiveC
/* Library code */
    self.shyNavBarManager.scrollView = self.tableView;
```

I get the following crash message when the view controller loads:
***** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'ASTableView uses asyncDelegate, not UITableView's delegate property.'**

Can you guys recommend a way to have the scrollView.delegate refer to asyncDelegate?

The library's setScrollview

```ObjectiveC
- (void)setScrollView:(UIScrollView *)scrollView
{
    NSLog(@"class: %@", NSStringFromClass([scrollView class]));
    
    [_scrollView removeObserver:self forKeyPath:@"contentSize" context:kTLYShyNavBarManagerKVOContext];

    if (_scrollView.delegate == self.delegateProxy)
    {
        _scrollView.delegate = self.delegateProxy.originalDelegate;
    }

    _scrollView = scrollView;
    self.scrollViewController.scrollView = scrollView;

    NSUInteger index = [scrollView.subviews indexOfObjectPassingTest:^BOOL (id obj, NSUInteger idx, BOOL *stop) {
        return [obj isKindOfClass:[UIRefreshControl class]];
    }];

    if (index != NSNotFound) {
        self.scrollViewController.refreshControl = [scrollView.subviews objectAtIndex:index];
    }

    if (_scrollView.delegate != self.delegateProxy)
    {
        self.delegateProxy.originalDelegate = _scrollView.delegate;
        _scrollView.delegate = (id)self.delegateProxy;
    }

    [self cleanup];
    [self layoutViews];

    [_scrollView addObserver:self forKeyPath:@"contentSize" options:0 context:kTLYShyNavBarManagerKVOContext];
}

```
Thank you in advance

**Comment by maicki** [comment]
@robmontesinos Checkout the `ASDKGram` example in the `examples/` folder for an implementation of this without having to use a third party component.

**Comment by robmontesinos** [comment]
Thanks @maicki - I see how it works - I'm going to see if I can make the library work one more time else I'll go this route. Salud!!

**Comment by maicki** [comment]
@robmontesinos Hey, I will close this issue as it seems like to be resolved. Please reopen otherwise. Thanks!
