### ISSUE TITLE
[Question] the method @selector(imageNode:didLoadImage:) in ASNetworkImageNodeDelegate is required

### ISSUE THREAD

**Issue by l1002k** [facebook/AsyncDisplayKit#1901]
// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// AsyncDisplayKit version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

I find a little issue about ASNetworkImageNodeDelegate. The method @selector(imageNode:didLoadImage:) is required in ASNetworkImageNode line 532.
But it declared with option.

**Comment by appleguy** [comment]
We may need to fix this.  I made the method optional recently because ASVideoNode now subclasses this for placeholder support.  I may have failed to fix the implementation.  Could you post a PR?

**Comment by maicki** [comment]
@I100k, Hey, this was recently fixed by #1783. Will close this issue, please reopen if you think it's not. Thank you for reporting the issue!
