### ISSUE TITLE
[ASViewController] iOS 8 + UIWindow rotation problem

### ISSUE THREAD

**Issue by stephenkopylov** [facebook/AsyncDisplayKit#1905]
Hi all!
The problem is really similar with this one: https://github.com/facebook/AsyncDisplayKit/issues/1810 (thanks for fixing it!)

Now issue appears with custom UIWindow with ASViewController as "rootViewController" and interface rotation - it not rotates again =)

Screens: 
![img_7375_2](https://cloud.githubusercontent.com/assets/5202281/16781912/6e0b06bc-488e-11e6-96bd-9c641646fff6.jpg)
![img_7375](https://cloud.githubusercontent.com/assets/5202281/16781918/71c6ad10-488e-11e6-922c-845f4a0c5442.jpg)

Sample project:
[UIWindow+AsyncVC.zip](https://github.com/facebook/AsyncDisplayKit/files/360187/UIWindow.AsyncVC.zip)

**Comment by hannahmbanana** [comment]
@stephenkopylov: thanks for reporting! I will look into this today.

**Comment by hannahmbanana** [comment]
@stephenkopylov: I had to call in the expert. @maicki should have a fix for you submitted as a PR in the next day!

**Comment by stephenkopylov** [comment]
@hannahmbanana thank you!
Cant wait for fix =)

**Comment by hannahmbanana** [comment]
@stephenkopylov: PR #1917 (will be merged to master by EOD) should fix this issue. I'm going to close the issue, but please reopen it if it doesn't resolve your issue. 

Thanks for reporting this and please let us know if you find any other bugs in the future!
