### ISSUE TITLE
Is there a way to encrypt the image before it store to the cache?

### ISSUE THREAD

**Issue by sainttail** [facebook/AsyncDisplayKit#1912]
#I want every one of downloaded images encrypted before save them to cache but I cannot find a way to do so.

[`ASImageProtocol.h`](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Details/ASImageProtocols.h) only provide a custom way to download from web or fetch from cache but no way to customise the way to save the downloaded image into cache.

Are there any way to do this?

Thanks.

**Comment by appleguy** [comment]
@sainttail I don't think there is with PINRemoteImage...you'd probably need to go to a custom ASImageDownloader, which is supported with creating a network image node via -initWithDownloader:cache:
