### ISSUE TITLE
ASNetworkImageNode imageModificationBlock() not working with GIF in a UITableVIew

### ISSUE THREAD

**Issue by dssheng** [facebook/AsyncDisplayKit#1913]
I'v used 
`extern asimagenode_modification_block_t ASImageNodeRoundBorderModificationBlock(CGFloat borderWidth, UIColor *borderColor)`
but the GIF still show as a rect.

**Comment by appleguy** [comment]
What effect are you trying to achieve?  This block may not be efficient enough to use with an animating content area.  If you'd like to have rounded corners, I have some suggestions on that.  Is the background area behind the image a single opaque color?

**Comment by dssheng** [comment]
@appleguy 
I need a rounded avatar, and then may add a little flag-icon on it.
The background is single opaque color.

**Comment by maicki** [comment]
@dssheng Hey, your question is very important for us and very common so we created a whole section for rounding corners at our site: http://asyncdisplaykit.org/docs/corner-rounding.html

I think you will find your answer in there and so I will close this issue, please reopen if you still have problems. Thanks!
