### ISSUE TITLE
[Implicit Hierarchy Management] Layout within layoutSpecBlock not showing up

### ISSUE THREAD

**Issue by jellenbogen** [facebook/AsyncDisplayKit#1916]
What I'm trying to do:

I have a node with a scrollNode inside of it. And inside that scrollNode I want to have a scrolling list of buttons. The buttons are in a vertical stack layout. I’m trying to play around with the implicitHierarchyManagement here and the only way I can tell to have the buttons show up within the scrollNode using IHM is by setting the scrollNode.layoutSpecBlock to return the vertical stack containing the buttons.

However when I do this and the layoutSpecThatFits method is called on my node I only see the scrollNode I dont see the buttons.

If I turn off IHM and add the buttons to the scrollNode, while keeping the scrollNode.layoutSpecBlock returning the stack layout to layout the buttons within the scroll node that works.

I think what I'm getting kind of hung up on is how IHM works with nodes within nodes, without making tons of different node classes which deal solely with their direct subnodes. I think the answer is either you need to do that or you can set the layoutSpecBlock like I have in my code, but what the best practice in that case? how deep should / can you go with that?

Here is the code I'm using:

I've left every thing uncommented for the sake of pasting it here but there are 2 set ups, one works and the buttons are visible, the other doesn't and the buttons are not visible.
#### Setup 1: (Buttons are visible)

---

Commented out
- usesImplicitHierarchyManagement = true

Uncommented
- scrollNode.addSubnode(aMenuItem)
- addSubnode(scrollNode)
#### Setup 2: (Buttons are not visible)

---

Commented out
- scrollNode.addSubnode(aMenuItem)
- addSubnode(scrollNode)

Uncommented
- usesImplicitHierarchyManagement = true

``` swift
//  Created by Jonathan Ellenbogen on 7/13/16.
//  Copyright © 2016 Jonathan Ellenbogen. All rights reserved.

import AsyncDisplayKit
import pop

class FeedHeaderNode: ASDisplayNode {

    enum State {
        case Closed, Open
    }

    var menuItems = [ASButtonNode]()
    let menuItemsData: [[String: String]]
    var selectedMenuItem: ASButtonNode!
    var scrollNode = ASScrollNode()
    var state: State = .Closed

    init(menuItemsData: [[String: String]]) {
        self.menuItemsData = menuItemsData

        super.init()

        usesImplicitHierarchyManagement = true

        for menuItemData in self.menuItemsData {
            guard let buttonTitleString = menuItemData["title"] else {
                continue
            }
            let aMenuItem = ASButtonNode()
            aMenuItem.setTitle(buttonTitleString, withFont: UIFont.appFont(20), withColor: UIColor.appDarkBlueColor(), forState: .Normal)
            aMenuItem.contentEdgeInsets = UIEdgeInsets(top: 5, left: 10, bottom: 5, right: 10)
            aMenuItem.backgroundColor = UIColor.appLightGrayColor()
            menuItems.append(aMenuItem)
            scrollNode.addSubnode(aMenuItem)

            if menuItemData == self.menuItemsData.first! {
                selectedMenuItem = aMenuItem
                selectedMenuItem.selected = true
            }
        }

        backgroundColor = UIColor.redColor()
        scrollNode.backgroundColor = UIColor.blueColor()
        scrollNode.layoutSpecBlock = {(node: ASDisplayNode, constrainedSize: ASSizeRange) -> ASLayoutSpec in
            let menuItemsLayout = ASStackLayoutSpec()
            menuItemsLayout.direction = .Vertical
            menuItemsLayout.alignSelf = .Stretch

            if self.state == .Closed {
                menuItemsLayout.setChild(self.selectedMenuItem)
            } else {
                menuItemsLayout.setChildren(self.menuItems)
            }
            return menuItemsLayout
        }
        addSubnode(scrollNode)
    }

    override func didLoad() {
        scrollNode.view.alwaysBounceVertical = true
    }

    override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        let finalLayout = ASStackLayoutSpec()
        finalLayout.direction = .Vertical
        finalLayout.alignSelf = .Stretch

        scrollNode.flexBasis = ASRelativeDimensionMakeWithPercent(0.5)
        let menuContainerSpec = ASStackLayoutSpec(direction: .Horizontal,
                                                  spacing: 0, justifyContent: .Start, alignItems: .Center, children: [scrollNode])

        finalLayout.setChild(menuContainerSpec)
        return finalLayout
    }
}

```

**Comment by Adlai-Holler** [comment]
@jellenbogen Sorry this one slipped through the cracks last summer.

I believe that to get the behavior you want, you should set `scrollNode.automaticallyManagesSubnodes = true` and `self.automaticallyManagesSubnodes = true` and then remove all explicit calls to `addSubnode`, just ensuring that your scroll node's `layoutSpecBlock` returns a layout spec that includes the buttons, and that your `layoutSpecThatFits` returns a layout spec that includes the scroll node (it does).
