### ISSUE TITLE
[AsyncDisplayKit.org] Broken links

### ISSUE THREAD

**Issue by qiushi0908** [facebook/AsyncDisplayKit#1926]
I find some broken link: (http://asyncdisplaykit.org/static/layout-example-1.png)、(http://asyncdisplaykit.org/static/layout-example-2.png)...
When i was reading docs. Most of broken link is image example.

**Comment by maicki** [comment]
@qiushi0908 Hey, Can please also point us to the URL where the images appear broken? Thanks!

**Comment by hannahmbanana** [comment]
Apologies about the website! 

I believe these two pages are hidden (but still available if you know the url) while undergoing changes.

**Comment by qiushi0908** [comment]
@maicki http://asyncdisplaykit.org/docs/automatic-layout-examples.html. I find the correct image URL is http://asyncdisplaykit.org/static/images/layout-example-1.png.

**Comment by maicki** [comment]
@qiushi0908 Awesome, thank you for providing us the URLs! @hannahmbanana will take care and fix this or remove the not used pages.
