### ISSUE TITLE
[ASCollectionView] Cells don't swap while reordering, after update to 1.9.81

### ISSUE THREAD

**Issue by kohol** [facebook/AsyncDisplayKit#1945]
Hi everyone!

I had reordering cells feature working well with ASCollectionView in my project. After upgrade to 1.9.81 it had stopped working. 

What I do is:
- Add UIPanGestureRecognizer to ASCollectionView
- on UIPanGestureRecognizer.state == UIGestureRecognizerStateChanged (when user is reordering cells) I make some calculations, change layout attributes a little bit and use ASCollectionView.performBatchUpdates:completion: with empty block to trigger relayout with animation.
```
    [self.collectionView performBatchUpdates:^{} completion:^(BOOL finished) {}];
```
- Result: Cells don't switch positions as they used to with previous version. :(

I checked commits that may cause this issue and found out that this is the one: https://github.com/facebook/AsyncDisplayKit/commit/c62a4d3e79e6a5cdaf4cf5ba14300ed3bdbf9fa9

I also checked if `invalidateLayout` method would work and it works, but there is no animation (as always). 

@Adlai-Holler and others: Do you have any idea how can I fix this and still use latest ASDK version? 
Thank you a lot!

**Comment by Adlai-Holler** [comment]
Hey @kohol sorry to hear this is broken.  Let's figure out why.  A couple questions to get started:

- Do the cells still switch position but no longer animate, or do they just stay where they are until something else happens?
- Are you using flow layout or a custom layout?
- Could you be more specific on what you do when the gesture recognizer updates? Which layout attributes do you change and how?
- Have you tried reverting c62a4d3 ? Does that fix the issue?
- Could you try calling `invalidateLayout` and then `[UIView animateWithDuration:^{ [collectionView layoutIfNeeded]; }]`?
- Could you make a sample project that reproduces this?

**Comment by kohol** [comment]
Thank you @Adlai-Holler for being interested in this.

- _Do the cells still switch position but no longer animate, or do they just stay where they are until something else happens?_

When I use `performBatchUpdates:completion:` nothing happens,  they stay at their positions. When I use `invalidateLayout` they switch positions but no animation.


- _ Are you using flow layout or a custom layout?_

I use layout that inherits from UICollectionViewFlowLayout and introduces some changes that make cells swap.


- _Could you be more specific on what you do when the gesture recognizer updates? Which layout attributes do you change and how?_

It updates indexPath, hidden attribute and center of cells. This would be hard to describe it all. I will send you project example.


- _Have you tried reverting c62a4d3 ? Does that fix the issue?_

Yes, every commit before this one works fine.


- _Could you try calling invalidateLayout and then [UIView animateWithDuration:^{ [collectionView layoutIfNeeded]; }]?_

When I use this code, animation is different and performance is poor. Cell disappear in one place and shows at another, but what I need it to do is slide from one place to another.


-  _Could you make a sample project that reproduces this?_

Yes, I think that would be the best idea. Please see attachment, especially:
Podfile, 
LSCollectionViewHelper.warpToIndexPath:


[ASDKExample.zip](https://github.com/facebook/AsyncDisplayKit/files/370989/ASDKExample.zip)

**Comment by Adlai-Holler** [comment]
Awesome, thanks for the comprehensive answer and the sample project. I'll investigate and update this issue today.

**Comment by Adlai-Holler** [comment]
@kohol This one's on me. After that commit, we ignore empty batch update blocks in ASCollectionView. But we should forward them up so that the collection view can do animated updates like these ones. With that change, the app behaves correctly for me. Could you confirm?

**Comment by kohol** [comment]
Yes, that works! 
Thank you very much for your time and commitment.
