### ISSUE TITLE
Image is not set sometimes when scrolling cells in collection view

### ISSUE THREAD

**Issue by zats** [facebook/AsyncDisplayKit#1953]
Hi, it seems like there are some cases when local image is not being set on the ASImageNode.

![screen-shot-2016-07-19-at-11 48 05-am](https://cloud.githubusercontent.com/assets/2688806/16969361/2583f9f4-4dc9-11e6-94de-534cdc12c981.jpg)
1. No discount
2. Certain discount, e.g. "50% OFF"
3. Up to certain discount, e.g. "up to 50% OFF"
4. Bug

CollectionViewCell hierarchy is following:

```
UICollectionViewCell
+- StoreCardNode
  +- LogoNode (ASImageNode)
  +- DiscountNode (ASDisplayNode)
    +- UpTo (ASImageNode)
    +- DiscountTextNode (ASTextNode)
```

Possible view model values are 

``` swift
enum Discount {
  case None
  case Precise(value: String)
  case UpTo(value: String)
}
```

Layout of the red ribbon is a horizontal stack with two children (`up to` and the `discount text`).

I see that layout sizes red ribbon and its children correctly always.

Sometimes, `up to` image is not drawing the local static image coming from xcassets ("up to" text is an image). For development purpose I changed its background color to blue and, as you can see it is always correctly drawn, the problem is the image itself. 

Please let me know if any more information is needed to get to the bottom of this

An additional information, with `[ASImageNode setShouldShowImageScalingOverlay:YES];` I see following in place of missing image node:

<img width="231" alt="screen shot 2016-07-19 at 4 35 03 pm" src="https://cloud.githubusercontent.com/assets/2688806/16970150/e7ca8f00-4dce-11e6-8b20-7ba84c91f5d4.png">
Text node shows `"infx"` which, I'm, guessing `infinity x`

```
AsyncDisplayKit 1.9.74
```

**Comment by hannahmbanana** [comment]
Discussed this with @zats on Slack. He'll try using `imageWithContentsOfFile:` instead of `imageNamed:` and report back. imageNamed: is not thread safe and will potentially cause issues with nodeBlocks which are initialized off the main thread.

**Comment by hannahmbanana** [comment]
@zats: could you provide a sample project?

**Comment by zats** [comment]
I tried to preserve original way of wiring things up as much as possible so excuse questionable software design.
To reproduce bug, I ran it on iPhone 5, please see the screenshot in the repo.
https://github.com/zats/AsynDisplayKit-ASImageNode-bug
I'm looking forward to discover the root of this issue

**Comment by zats** [comment]
Hi I wanted to follow up to see if I can provide any more information to help resolve figure out this issue. 
Thanks!

**Comment by hannahmbanana** [comment]
@zats: A few comments on your code:

- you should try using an `ASCollectionNode` instead of `UICollectionView` (and `ASCellNode` instead of `UICollectionViewCell` for performance 
- I believe what is happening is that because you are not using a node container (e.g. an `ASCollectionNode`, nothing is calling `layoutSpecThatFits:`.  (This bug has recently been fixed on `master` I believe). Try calling `measureWithSizeRange:` rather than `measure:` on the `StoreNode` (line 104)

**Comment by zats** [comment]
Thank you very much for your suggestions, I'll give it a shot! In our case we are not quite ready to switch to `ASCollectionNode` though.
I'm not too familiar with AsyncDisplayKit release process - when you mentioned that fix has landed to master, does it mean it should be available though cocoapods too or are those unrelated?
Thanks!

**Comment by zats** [comment]
from my setup, it doesn't seem like calling `measureWithSizeRange:` directly solves the problem

```diff
- node.measure(contentView.bounds.size)
+ node.measureWithSizeRange(ASSizeRange(min: contentView.bounds.size, max: contentView.bounds.size))
```

**Comment by Adlai-Holler** [comment]
Hi @zats it's possible that what was happening was, the image node was scheduled for display when it was still at zero bounds, so we didn't draw anything.

I believe it was resolved https://github.com/facebook/AsyncDisplayKit/pull/2149 . If this is still an issue, please feel free to reopen this or join us on Slack http://asyncdisplaykit.org/slack . Cheers!
