### ISSUE TITLE
Error compiling as a dynamic framework (CocoaPods 0.36)

### ISSUE THREAD

**Issue by ide** [facebook/AsyncDisplayKit#198]
This is sort of an implementation detail with CocoaPods but if a lot of people use ASDK as a pod then it could be an issue. The [next release of CocoaPods](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) adds support for dynamic frameworks but using them triggers a compiler error in ASDK:

```objc
typedef struct {
  NSTextStorage *textStorage;  // ARC forbids Objective-C objects in struct
  NSTextContainer *textContainer;
  NSLayoutManager *layoutManager;
  UITextView *textView;
} ASTextKitComponents;
```
 There might be more issues but I haven't poked further.

**Comment by ide** [comment]
@rnystrom I set up a new project for a basic iOS app in Xcode and added a simple Podfile. The key is that one of the Pods needs to be written in Swift (probably why you couldn't repro. sorry about that). A Swift dependency makes CocoaPods use frameworks instead of static libraries.
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AsyncDisplayKit', '~> 1.1'
pod 'Synchronized', '~> 1.0'
```

Then in AppDelegate.swift of the sample project I added `import AsyncDisplayKit` and got the error when building the app (also got a similar error when adding `@import AsyncDisplayKit;` to an Obj-C file). Importing the Synchronized framework works fine.

**Comment by tberman** [comment]
Any movement on merging this?

**Comment by secretiverhyme** [comment]
I didn't want to pull this in until I had time to open-source [ASEditableTextNode](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASEditableTextNode.h), which is also affected by this change.  Let me see about updating it now.

**Comment by wyxy2005** [comment]
I have encountered this problem, and exactly the same @ide 's error, my Xcode  version 6.1.1(6A2008a)

**Comment by ide** [comment]
@wyxy2005 It should be fixed in master but hasn't been published yet. You can reference the git repo in the Podfile if you want CocoaPods to use master.

**Comment by wyxy2005** [comment]
@ide  I'm first reference the git repo in the Podfile is ok,but run command:"pods update" will reproduction this error message.
