### ISSUE TITLE
[ASTextNode] placeholder image context fails for zero width size

### ISSUE THREAD

**Issue by srikanthraju** [facebook/AsyncDisplayKit#1986]
CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable

      Jul 26 15:18:02  BroEx[6115] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. Backtrace:
	  <CGContextSetFillColorWithColor+66>
	   <-[UIDeviceWhiteColor setFill]+55>
	    <-[ASTextNode placeholderImage]+357>
	     <-[ASDisplayNode _completeLayoutCalculation]+558>
	      <-[ASDisplayNode measureWithSizeRange:]+794>
	       <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	        <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objec
	         <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_EEEEZL46layoutChildrenA
	          <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_obje
	           <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS0_9allo
	            <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	          Jul 26 15:18:02  BroEx[6115] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. Backtrace:
	  <CGContextSetFillColorWithColor+66>
	   <-[UIDeviceWhiteColor setFill]+55>
	    <-[ASTextNode placeholderImage]+357>
	     <-[ASDisplayNode _completeLayoutCalculation]+558>
	      <-[ASDisplayNode measureWithSizeRange:]+794>
	       <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	        <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objec
	         <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_EEEEZL46layoutChildrenA
	          <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_obje
	           <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS0_9allo
	            <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	             <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	              <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc
	               <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_EEEEZL46layoutChi
	                <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11obj
	                 <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS0
	                  <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                   <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	                    <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable
	                     <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_ob   <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	              <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc
	               <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_EEEEZL46layoutChi
	                <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11obj
	                 <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS0
	                  <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                   <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	                    <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable
	                     <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_EEEEZL46lay
	                      <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutabl
	                       <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_obj
	                        <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                         <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                          <-[ASDisplayNode calculateLayoutThatFits:]+1262>
	                           <-[ASDisplayNode measureWithSizeRange:]+321>
	                            <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                             <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	                              <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12AS
	                               <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11Jul 26 15:18:02  BroEx[6115] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. Backtrace:
	  <CGContextSetFillColorWithColor+66>
	   <-[UIDeviceWhiteColor setFill]+55>
	    <-[ASTextNode placeholderImage]+357>
	     <-[ASDisplayNode _completeLayoutCalculation]+558>
	      <-[ASDisplayNode measureWithSizeRange:]+794>
	       <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	        <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objec
	         <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_EEEEZL46layoutChildrenA
	          <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_obje
	           <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS0_9allo
	            <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	             <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	              <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc
	               <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_EEEEZL46layoutChi
	                <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11obj
	                 <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS0
	                  <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                   <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	                    <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable
	                     <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_EEEEZL46lay
	                      <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutabl
	                       <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_obj
	                        <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                         <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                          <-[ASDisplayNode calculateLayoutThatFits:]+1262>
	                           <-[ASDisplayNode measureWithSizeRange:]+321>
	                            <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                             <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	                              <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12AS
	                               <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_E
	                                <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12A
	                                 <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable
	                                  <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                                   <-[ASBackgroundLayoutSpec measureWithSizeRange:]+152>
	                                    <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                                     <-[ASDisplayNode calculateLayoutThatFits:]+1262>
	                                      <-[ASDisplayNode measureWithSizeRange:]+321>
	                                       <-[ASDataController _layoutNode:withConstrainedSize:]+161>
	                                        <-[ASDataController _layoutNodes:fromContexts:atIndexesOfRange:ofKind:]+1287>
	                                         <__63-[ASDataController _layoutNodesFromContexts:ofKind:completion:]_block_invoke.121+
	                                          <_dispatch_call_block_and_release+15>
	                                           <_dispatch_client_callout+14>
	                                            <_dispatch_root_queue_drain+1008>
	                                             <_dispatch_worker_thread3+115>
	                                              <_pthread_wqthread+1050>
    objc_objectNS1_9allocatorIS5_E
	                                <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12A
	                                 <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable
	                                  <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                                   <-[ASBackgroundLayoutSpec measureWithSizeRange:]+152>
	                                    <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                                     <-[ASDisplayNode calculateLayoutThatFits:]+1262>
	                                      <-[ASDisplayNode measureWithSizeRange:]+321>
	                                       <-[ASDataController _layoutNode:withConstrainedSize:]+161>
	                                        <-[ASDataController _layoutNodes:fromContexts:atIndexesOfRange:ofKind:]+1287>
	                                         <__63-[ASDataController _layoutNodesFromContexts:ofKind:completion:]_block_invoke.121+
	                                          <_dispatch_call_block_and_release+15>
	                                           <_dispatch_client_callout+14>
	                                            <_dispatch_root_queue_drain+1008>
	                                             <_dispatch_worker_thread3+115>
	                                              <_pthread_wqthread+1050>
     jectNS1_9allocatorIS5_EEEEZL46lay
	                      <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutabl
	                       <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_obj
	                        <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                         <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                          <-[ASDisplayNode calculateLayoutThatFits:]+1262>
	                           <-[ASDisplayNode measureWithSizeRange:]+321>
	                            <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                             <_ZL16crossChildLayoutPU23objcproto12ASLayoutable11objc_object22ASStackLayoutSpecStyleffff+372>
	                              <_ZZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12AS
	                               <_ZN2AS3mapINSt3__16vectorIU8__strongPU23objcproto12ASLayoutable11objc_objectNS1_9allocatorIS5_E
	                                <_ZL46layoutChildrenAlongUnconstrainedStackDimensionRKNSt3__16vectorIU8__strongPU23objcproto12A
	                                 <_ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorIU8__strongPU23objcproto12ASLayoutable
	                                  <-[ASStackLayoutSpec measureWithSizeRange:]+1644>
	                                   <-[ASBackgroundLayoutSpec measureWithSizeRange:]+152>
	                                    <-[ASInsetLayoutSpec measureWithSizeRange:]+1741>
	                                     <-[ASDisplayNode calculateLayoutThatFits:]+1262>
	                                      <-[ASDisplayNode measureWithSizeRange:]+321>
	                                       <-[ASDataController _layoutNode:withConstrainedSize:]+161>
	                                        <-[ASDataController _layoutNodes:fromContexts:atIndexesOfRange:ofKind:]+1287>
	                                         <__63-[ASDataController _layoutNodesFromContexts:ofKind:completion:]_block_invoke.121+
	                                          <_dispatch_call_block_and_release+15>
	                                           <_dispatch_client_callout+14>
	                                            <_dispatch_root_queue_drain+1008>
	                                             <_dispatch_worker_thread3+115>
	                                              <_pthread_wqthread+1050>

**Comment by maicki** [comment]
Hey srikanthraju, this not really helpful for us. We would appreciate if you provide more information what is actually going on, when this happened or a sample app where we can reproduce it. Thanks!

**Comment by srikanthpandeti** [comment]
i'm setting tint color for ASButtonNode

      button1 = ASButtonNode()
      button1.setTitle(buttonNode.title, withFont: UIFont.systemFontOfSize(16), withColor: UIColor.blueColor(), forState: .Normal)
      button1.setImage(UIImage(named: buttonNode.imagename), forState: .Normal)
      button1.addTarget(self, action: #selector(button1ActionTriggered), forControlEvents: .TouchUpInside)
      button1.titleNode.layerBacked = true
      button1.imageNode.displaysAsynchronously = true
      button1.contentSpacing = 1.0

      addSubnode(button1)

      button1.tintColor = UIColor.grayColor()
and i'm updating color of title and image 

    extension ASButtonNode {

        public override func tintColorDidChange() {
           super.tintColorDidChange()

          let tintImage = self.imageForState(.Normal)?.setTintColor(tintColor)

          self.setImage(tintImage, forState: .Normal)
          self.setTitle((self.titleNode.attributedString?.string)!, withFont: UIFont.systemFontOfSize(16), withColor: tintColor, forState: .Normal)
        }
    }


    public extension UIImage {

        func setTintColor(color: UIColor) -> UIImage {

           var newImage = self.imageWithRenderingMode(.AlwaysTemplate)
           UIGraphicsBeginImageContextWithOptions(self.size, false, newImage.scale);
           color.set()
           newImage.drawInRect(CGRectMake(0, 0, self.size.width, newImage.size.height))
           newImage = UIGraphicsGetImageFromCurrentImageContext();
           UIGraphicsEndImageContext();

          return newImage
        }
    }


CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by hannahmbanana** [comment]
@srikanthpandeti: would it be possible to provide us a sample project? It is much faster for us to help if a project is already created.

It's possible that self.size is zero, causing UIGraphicsBeginImageContextWithOptions to fail in a way that doesn't return an error until you try to draw in the context that you weren't able to create.

**Comment by srikanthpandeti** [comment]
@hannahmbanana : i have checked that size, it was non-zero. i have attached the sample project.


[Sample.zip](https://github.com/facebook/AsyncDisplayKit/files/400194/Sample.zip)

**Comment by hannahmbanana** [comment]
@srikanthraju: Thanks for reporting this!
@srikanthpandeti: thanks for providing a sample project! The UI on your project looks really great. We don't currently have any Swift ASDK examples, so let me know if you'd be interested in sharing this (or something similar) in our examples folder. 

The `-placeholderImage` for the `ASTextNode` is getting zero width (the case in which I observed was when its `.attributedText = @""`. I'll put up a PR to change the `-placeholderImage` to check for zero **area** rather than **`CGSizeZero`**?

<img width="1301" alt="screen shot 2016-08-14 at 12 08 13 pm" src="https://cloud.githubusercontent.com/assets/3419380/17651290/a24ce91a-6218-11e6-90ee-03721c5bfd72.png">

**Comment by srikanthraju** [comment]
@hannahmbanana  Thanks for your reply and I appreciate that you looked into this issue.
I will be pleased to share a similar code for the sample. so I'll post that up when I get a chance.

**Comment by Adlai-Holler** [comment]
@srikanthpandeti I believe @hannahmbanana saved the day in #2069. Could you try latest master and confirm it's working?

**Comment by srikanthraju** [comment]
@hannahmbanana and @Adlai-Holler issue has been fixed. You really saved my time.

**Comment by srikanthraju** [comment]
@hannahmbanana I have updated the sample and removed unwanted code. let me know if you need anything else.
[Sample.zip](https://github.com/facebook/AsyncDisplayKit/files/426801/Sample.zip)
