### ISSUE TITLE
ASButtonNode does not show the title

### ISSUE THREAD

**Issue by peace-v** [facebook/AsyncDisplayKit#1989]
I was using AsyncDisplayKit (1.9.7.2) to create the demo. When create a button like this, the title wasn't showing as expected.
```
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let button = ASButtonNode()
        button.frame = CGRect(x: (self.view.frame.size.width-100)/2, y: (self.view.frame.size.height-44)/2, width: 100, height: 44)
        button.setTitle("Click me", withFont: UIFont.systemFontOfSize(17), withColor: UIColor.whiteColor(), forState: .Normal)
        button.backgroundColor = UIColor.blackColor()
        
//        button.titleNode.frame = CGRect(x: 0, y: 0, width: 100, height: 44)
//        button.addSubnode(button.titleNode)
        
        self.view.addSubnode(button)
    }
```
![simulator screen shot 2016 7 27 2 43 52](https://cloud.githubusercontent.com/assets/8011890/17166298/a818f7f8-5408-11e6-8479-85da70d2ab3d.png)
But when I uncommented above two lines, it showed.
![simulator screen shot 2016 7 27 2 43 43](https://cloud.githubusercontent.com/assets/8011890/17166329/dc4836b0-5408-11e6-9a44-0aafbede8e68.png)
So which is the right way to create a button with a title? Thanks.

**Comment by hannahmbanana** [comment]
@peace-v: If you can, I highly recommend upgrading to 1.9.81 or using master. Lots of improvements have been made to the framework since 1.9.7.2 :)

Which are you trying to use, a UIViewController or an  [ASViewController](http://asyncdisplaykit.org/docs/containers-asviewcontroller.html)?

**Comment by peace-v** [comment]
@hannahmbanana I was using UIViewController. Thanks for your reply, I will try to upgrade to 1.9.81.

**Comment by maicki** [comment]
@peace-v You have to call `measure` before adding the button node to the view:

```swift
...
button.measure(CGRect(x: (self.view.frame.size.width-100)/2, y: (self.view.frame.size.height-44)/2, width: 100, height: 44))
...
self.view.addSubnode(button)
```

**Comment by peace-v** [comment]
@maicki After call `measure` the titleNode did show, but how can I center the title? Calling `contentHorizontalAlignment` and `contentVerticalAlignment` is not working.
```
let button = ASButtonNode()
button.frame = CGRect(x: (self.view.frame.size.width-100)/2, y: (self.view.frame.size.height-44)/2, width: 100, height: 44)
button.setTitle("Click me", withFont: UIFont.systemFontOfSize(17), withColor: UIColor.whiteColor(), forState: .Normal)
button.backgroundColor = UIColor.blackColor()
button.contentHorizontalAlignment = ASHorizontalAlignment.AlignmentMiddle
button.contentVerticalAlignment = ASVerticalAlignment.AlignmentCenter
button.measure(CGSizeMake(100, 44))
self.view.addSubnode(button)
```

**Comment by maicki** [comment]
@peace-v Apologies, change `button.measure()` to 
```
button.measureWithSizeRange(ASSizeRangeMakeWithExactCGSize(CGSizeMake(100, 44)));
```

This should give you the effect you would like to have.

**Comment by peace-v** [comment]
@maicki It works! Thanks.
