### ISSUE TITLE
Preload of ASCollectionView doesn't work.

### ISSUE THREAD

**Issue by evgenyst** [facebook/AsyncDisplayKit#1990]
Hi!

I'm trying to load ASCollectionView then page is not visible yet. 
The problem is that in my custom cell fetchData method not called. Custom cell contains ASNetworkImageNode instance but setURL also not called because self.interfaceState is ASInterfaceStateNone.

For ASTableView everything works as expected.

v. 1.9.81

Thanks!

**Comment by maicki** [comment]
@evgenyst Hey, would it be possible to provide an example app so we can reproduce the issue. Thanks!

**Comment by evgenyst** [comment]
[Swift.zip](https://github.com/facebook/AsyncDisplayKit/files/386459/Swift.zip)

**Comment by evgenyst** [comment]
Hey! Thanks for getting back to me!
I was unable to reproduce the initial problem with small sample, but reproduced in the sample above one is the reason the  initial one.

In the sample you see a tabbarcontroller with 3 view controller. 1-st one is a view controller with collection view, second is empty one, 3-rd is a view controller with table view. Every time second view controller appears we reload collection and table view. Also before setting root view controller we preloading 1-st and 3-rd:

    tabbarVC.viewControllers![0].preloadView() //Extenstions folder
    tabbarVC.viewControllers![2].preloadView()
    
    
    window.rootViewController = tabbarVC

Collection uses ImageCellNode as ASCellNode. Table uses ImageCellNodeForTable.
if you take a look in console after Test view controller appears on the screen you will see that fetch for ImageCellNodeForTable was called and didLoadImage was triggered.
Nothing was called for the collection. Even if you put self.loadImage() into setupImage() image, method didLoadImage will not be called. I believe this is because  self.interfaceState is ASInterfaceStateNone.

Please let me know if you need any more info.

**Comment by evgenyst** [comment]
@maicki Hey, where you been able to reproduce the problem?

**Comment by DavidSchechter** [comment]
@evgenyst I am having issues wrapping my head around the topics of Intelligent Preloading.

**Comment by hannahmbanana** [comment]
@DavidSchechter - check out http://asyncdisplaykit.org/docs/intelligent-preloading.html.

**Comment by Adlai-Holler** [comment]
Hey @evgenyst The difference in behavior here is expected, and is a consequence of how `UITableView` and `UICollectionView` load their data differently.

`UICollectionView` waits to load its initial data until `layoutSubviews`, while `UITableView` does not. If you want to force your collection view to load its data while it's offscreen, modify your `Extension.swift:preloadView` method like so:

```swift
  func preloadView() {
    let _ = view
    view.layoutIfNeeded()
  }
```

If you make that change, you'll see that the table & collection both load their nodes.

If you have any further questions, please reach out. Cheers!
