### ISSUE TITLE
All nodes are initialized and measured when ASRangeController is setup

### ISSUE THREAD

**Issue by rnystrom** [facebook/AsyncDisplayKit#200]
- Open the Kittens example
- Change the [litterSize](https://github.com/facebook/AsyncDisplayKit/blob/master/examples/Kittens/Sample/ViewController.m#L19) to something large (1000 works)
- Observe very long startup (iPhone 4 takes ~30 seconds)

On the Kittens demo, it appears that we are calling [-measure:](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L357) on every single node. The `measure:` method also sets up and renders the placeholder. When there is text involved, this spins up an `ASTextNodeRenderer` per node (1000 in this above case).

The issue with `ASRangeControllers` is that it waits for *every single node* to init and measure in the [-insertNodes:](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Details/ASDataController.mm#L306-345) method before displaying anything. With a large data set this is problematic.

**Comment by rnystrom** [comment]
@tanliboy would you mind taking a peak at this and seeing if its something we can optimize w/ the way we insert nodes? Either in batches or something. We can jam on some ideas, just grab me :smiley:

**Comment by tanliboy** [comment]
Yeah, we should use the batch update here. I will fix it.

**Comment by tanliboy** [comment]
Fixed in the pending pull request

**Comment by rnystrom** [comment]
:clap: thanks @tanliboy
