### ISSUE TITLE
[Question] how to layout a parent node

### ISSUE THREAD

**Issue by raphaels17** [facebook/AsyncDisplayKit#2001]
Hi 
I may have misunderstood a part of the doc but I can't seem to be able to specify the layout for the 'parent' node.
I am trying to give a min size in relative, a max in absotule to the parent node.
I found a work around which is to create a 'display node' to encapsule the rest, but I am not sure this is the way to go.  Does anyone have an advice?

` {override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        self.sizeRange = ASRelativeSizeRangeMakeWithExactCGSize(CGSizeMake(constrainedSize.max.width, 0.5))
        let mainStackLayoutSpec = ASStackLayoutSpec(direction:.Vertical, spacing: 1, justifyContent:.Start, alignItems: .Start, children: [self])
 return mainStackLayoutSpec
    } `

**Comment by hannahmbanana** [comment]
@raphaels17: `-layoutSpecThatFits:` is used to specify the layout of a node's subnodes. The parent's layout is set by the grandparent's node's `-layoutSpecThatFits`. 

What type is your parent node? A collection or table node? If you use an ASViewController and `-initWithNode:_collectionNode` then the collectionNode will inherit the bounds of the ASViewController. If you use a UIViewController you will need to specify the bounds manually. 

Also, `.sizeRange` will not apply to children of a `ASStackLayoutSpec`:
http://asyncdisplaykit.org/docs/layout-api-debugging.html#am-i-the-child-of-an-asstacklayoutspec-or-an-asstaticlayoutspec

**Comment by raphaels17** [comment]
Thanks ! the tip .sizeRange really have been useful. I have set my stackLayout in a Static layout and that did the trick ;)

However while tweaking my code I added constrainedSize.max.height as the height. my nodes are in a ASCollectionView. I expected the height to be be that of the screen minus the header and saw while debugging a enormous number (3 *10^18)

**Comment by maicki** [comment]
@raphaels17 This `enormous` number just means that the node should return the intrinsic height of itself based on (calculated from) it's size + all of it's subnodes sizes. It's the same as calling `sizeThatFits:` on a UIView with a large number (usually `CGFLOAT_MAX` / `INFINITY`) to let the `UIView` calculate the size that fits

**Comment by raphaels17** [comment]
Thanks I got it. Closing. this project works, i'll some more intricate in the next few days.

**Comment by hannahmbanana** [comment]
@raphaels17: I'm going to close this because it appears we answered your question. If not, feel free to reopen.
