### ISSUE TITLE
[ASLayoutable]: unable to position overlapping nodes

### ISSUE THREAD

**Issue by benjaminhorner** [facebook/AsyncDisplayKit#2003]
Hi,

I am trying to achieve the following layout. This seems extremely simple… However, I am unable to position the "plus" icon in the top right corner, over the avatar (grey square) node.

I have tried multiple things, including re-positionning it in the `layoutDidFinish()` method. However, despite this solution rendering correctly, I get a glitch as the node is re-positionned…

I took a look at the kittens example, but I cannot find a way to overlap two nodes like in this design. This seems like something that should be really easy to achieve…

Any help much appreciated!

```
override func layoutDidFinish() {
        super.layoutDidFinish()
        
        dispatch_async(dispatch_get_main_queue()) {
            
            let x = self.userAvatar.frame.origin.x + self.userAvatar.frame.width - UserProfileLayout.CircularButtonPreferedSize.width/2
            let y = self.userAvatar.frame.origin.y - UserProfileLayout.CircularButtonPreferedSize.height/2
            
            self.roundButton.frame.origin.x = x
            self.roundButton.frame.origin.y = y
            
            self.roundButton.alpha = 1
        }
    }
```

<img width="623" alt="capture d ecran 2016-07-28 a 16 57 17" src="https://cloud.githubusercontent.com/assets/3463436/17217412/8d18a624-54e4-11e6-9d9d-331c9ba9572d.png">

**Comment by maicki** [comment]
@benjaminhorner Look into `ASStaticLayoutSpec`. It's kind of absolute positioning within a layout spec. You can set an absolute `layoutPosition` and a `sizeRange` for all of it's children. So I would create a new node e.g. `AvatarNode` with avatar and plus sign as subsides and in `layoutSpecThatFits:` put the avatar image and the plus sign in a static layout spec and lay them out absolute. Than put the `AvatarNode` in a vertical stack spec with the other nodes (e.g. the "Sign Up" button)

Hope that's a good starting point.

**Comment by benjaminhorner** [comment]
@maicki: thanks!
Here is what I ended up doing:
```
let x = UserProfileLayout.AvatarPreferedSize().width
        let y = -(UserProfileLayout.CircularButtonPreferedSize.height/2)
        roundButton.layoutPosition = CGPointMake(x, y)
        
        userAvatar.layoutPosition = CGPointMake(UserProfileLayout.CircularButtonPreferedSize.width/2, 0)
        
        let staticLayoutable: [ASStaticLayoutable] = [userAvatar, roundButton]
        let staticLayoutSpec = ASStaticLayoutSpec(children: staticLayoutable)
        
        var mainChildren: [ASLayoutable] = [spacer, staticLayoutSpec, userNameTextnode, locationAndFollowersSpec, userDescription]
```

Note that unlike what I initially attempted, you cannot just position the plus sign but also the avatar if you want the avatar to stay centered and the Plus sign offset to the right.
