### ISSUE TITLE
[Xcode 8] compatibility question

### ISSUE THREAD

**Issue by Serlight** [facebook/AsyncDisplayKit#2010]
when use AsyncDisplayKit in Xcode8, get below Error:

`Pods/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:479:21: Assigning to 'id<CALayerDelegate> _Nullable' from incompatible type 'ASDisplayNode *const __strong'`

could you patch, fix this

**Comment by hannahmbanana** [comment]
What version are you using? I believe we fixed this when the first xcode 8 beta came out. 

Can you try master or 1.9.81 or releases/p6.9?

**Comment by hannahmbanana** [comment]
@Serlight

**Comment by Serlight** [comment]
@hannahmbanana  thx， there is 1.9.80. Ok i will update my Podfile.

**Comment by hannahmbanana** [comment]
@Serlight: I'm going to close this issue. Feel free to re-open the issue if upgrading versions did not resolve this issue for you.

**Comment by GreatLiyi** [comment]
But， on cocoapod  the latest version is 1.9.74 @hannahmbanana
