### ISSUE TITLE
[ASCollectionView] reloadData: Node should always be marked invisible before deallocating 

### ISSUE THREAD

**Issue by cdiscla** [facebook/AsyncDisplayKit#2011]
Hello,
i have a problem with my ASCollectionView; when the user taps a button that makes the _collectionView.reloadData() i get the
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Node should always be marked invisible before deallocating; interfaceState: 15, <ASImageNode: 0x7ffb8a07a600>'
` error

I simply get fresh data and do a reloadData() . How can i solve it?
It seems similar to #1466 but this time is for ASCollectionView.
I'm using 1.9.81 version.
Can anyone help me please?
Thanks in advance and greetings
Cris

**Comment by cdiscla** [comment]
I have temporary "solved" the problem commenting the line
` ASDisplayNodeAssert(_flags.synchronous || !ASInterfaceStateIncludesVisible(_interfaceState), @"Node should always be marked invisible before deallocating; interfaceState: %lu, %@", (unsigned long)_interfaceState, self);`   in (void)dealloc  but i hope there mest a better way to solve it.
Thanks and greetings

**Comment by aforkalyuk** [comment]
I have the same issue, but only when collection view has a supplementary view.

**Comment by george-gw** [comment]
I've been getting the same problem recently with supplementary views, and I just wanted to check with you guys to see if it can be solved the same way.

@aforkalyuk and @cdiscla do you guys have anything layerBacked in your supplementary view?
If so, could you please disable the layer backing and see if it still crashes?

**Comment by cdiscla** [comment]
@george-gw you're right; i had layerBacked=true for an image in my supplementary view; if i comment it the app does not crash.
Thank you for your info !

**Comment by jadsonlourenco** [comment]
@george-gw in my case I don't have **supplementary view**, and no **layerBacked** on the cell children nodes. I'm using `reloadRowsAtIndexPaths` to update my table.

**Comment by george-gw** [comment]
@cdiscla thanks, at least this way we know it's consistent :)
@jadsonlourenco last you mentioned you were using 1.9.81, does the crash still appear on the latest version/master?

**Comment by jadsonlourenco** [comment]
@george-gw yes, I'm using the latest master and crash.

**Comment by aforkalyuk** [comment]
@george-gw Yeah, I have layerBacked for ASTextNode and ASImageNode there. If I set it to NO it doesn't crash any more. Thanks.

**Comment by george-gw** [comment]
@aforkalyuk @cdiscla I just did some more tests because the main problem is the deletion of the header node. I wanted to keep using layerBacking without me personally having to hold the node as a member node, so I found out that you can get things to work while keeping your `layerBack = true/YES` like this:

```
func collectionView(collectionView: ASCollectionView, nodeForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> ASCellNode {

    var headerNode = collectionView.supplementaryNodeForElementKind(UICollectionElementKindSectionHeader, // or whatever your supplementary element kind is
                                                                    atIndexPath: indexPath) as? MySupplementaryNode
    if headerNode == nil {
      headerNode = MySupplementaryNode()
    }

    return headerNode!

  }
```

Basically use it as if you're dequeuing your supplementary node, I'm not sure if this is how you're supposed to use it though. @Adlai-Holler maybe you can weigh in on this? If that is the case, @hannahmbanana maybe we should add some sort of documentation regarding this ?

@jadsonlourenco I think you might be having a different issue than us, as we're using ASCollectionNode/ASCollectionView and we're using supplementary nodes, could you share a test project with your crash?

**Comment by Adlai-Holler** [comment]
I'm currently investigating this, attempting to reproduce the issue in a reduced form. I should have an update soon folks, hang tight!

**Comment by salesawagner** [comment]
I've been getting the same problem recently with `ASCollectionView.deleteItemsAtIndexPaths` method. In the first time, the method works perfectly, but in the second time crash!

**Comment by Adlai-Holler** [comment]
@cdiscla @george-gw @jadsonlourenco @aforkalyuk Thanks for your patience folks! If possible, can you try building against that diff and see if it resolves the issue?

**Comment by jadsonlourenco** [comment]
@Adlai-Holler no, in my case I'm using an `ASButtonNode` (with an image) inside my **ASCellNode** when I need remove/insert my cell get this error (crash):
```
2016-08-31 16:59:09.891 chessboardradio[43699:519842] *** Assertion failure in -[ASImageNode dealloc], /Users/jadson/Development/chessboard-radio-ios/Pods/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:393
2016-08-31 16:59:09.902 chessboardradio[43699:519842] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Node should always be marked invisible before deallocating; interfaceState: 15, <ASImageNode: 0x7ff7dc86c600>'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107e3fd85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000109dacdeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107e3fbea +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010837fd5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   AsyncDisplayKit                     0x000000010578a921 -[ASDisplayNode dealloc] + 897
	5   AsyncDisplayKit                     0x00000001057cf29c -[ASImageNode dealloc] + 76
	6   AsyncDisplayKit                     0x000000010576d225 -[ASDealloc2MainObject release] + 197
	7   AsyncDisplayKit                     0x000000010573411e -[ASButtonNode .cxx_destruct] + 78
	8   libobjc.A.dylib                     0x0000000109dab7bb _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	9   libobjc.A.dylib                     0x0000000109db6332 objc_destructInstance + 93
	10  libobjc.A.dylib                     0x0000000109db6365 object_dispose + 22
	11  AsyncDisplayKit                     0x000000010578adf9 -[ASDisplayNode dealloc] + 2137
	12  AsyncDisplayKit                     0x000000010576d225 -[ASDealloc2MainObject release] + 197
	13  chessboardradio                     0x000000010543bbf2 _TToFC15chessboardradio17SongsListItemCellE + 242
	14  libobjc.A.dylib                     0x0000000109dab7bb _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	15  libobjc.A.dylib                     0x0000000109db6332 objc_destructInstance + 93
	16  libobjc.A.dylib                     0x0000000109db6365 object_dispose + 22
	17  AsyncDisplayKit                     0x000000010578adf9 -[ASDisplayNode dealloc] + 2137
	18  AsyncDisplayKit                     0x000000010576d225 -[ASDealloc2MainObject release] + 197
	19  AsyncDisplayKit                     0x00000001057a4b2d __destroy_helper_block_.640 + 29
	20  libsystem_blocks.dylib              0x000000010b0b66b1 _Block_release + 128
	21  libdispatch.dylib                   0x000000010b03f3eb _dispatch_client_callout + 8
	22  libdispatch.dylib                   0x000000010b0271ef _dispatch_main_queue_callback_4CF + 1738
	23  CoreFoundation                      0x0000000107d990f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	24  CoreFoundation                      0x0000000107d5ab99 __CFRunLoopRun + 2073
	25  CoreFoundation                      0x0000000107d5a0f8 CFRunLoopRunSpecific + 488
	26  GraphicsServices                    0x000000010cd4cad2 GSEventRunModal + 161
	27  UIKit                               0x0000000108830f09 UIApplicationMain + 171
	28  chessboardradio                     0x000000010534c432 main + 114
	29  libdyld.dylib                       0x000000010b07392d start + 1
	30  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

**Comment by Adlai-Holler** [comment]
@jadsonlourenco Did you get that error when you pointed your Podfile like this:

`pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit', :branch => 'AHFixNodeMustBeMarkedInvisibleIssue'`?

If so, could you share some sample code that reproduces the issue?

**Comment by jadsonlourenco** [comment]
@Adlai-Holler yes.

**Comment by george-gw** [comment]
@Adlai-Holler it solved the crash that I was facing with the supplementary header nodes 👍

**Comment by Adlai-Holler** [comment]
@jadsonlourenco I'd like to help, but I can't reproduce the issue you're having. Could you provide some sample code that demonstrates the issue, or details about how your cell node is built?

**Comment by jadsonlourenco** [comment]
@Adlai-Holler thank you! But don't worry, my issue is solved.

I created a simple project to test (demo: http://sendvid.com/wxee33cv code: https://github.com/jadsonlourenco/ASCellDemo) and all works fine, I don't know why in my real app I have few issues with AsyncDisplaykit - cell animation when load; crash when reload a cell; etc. - but is something in my app, I will figure out.

**Comment by Adlai-Holler** [comment]
Let's move discussion of this over to #2252
