### ISSUE TITLE
[Crash] ASDealloc2MainObject

### ISSUE THREAD

**Issue by yufenglv** [facebook/AsyncDisplayKit#2016]
hi,@hannahmbanana, the ASDK version is 1.9.81, the crashes take up 5 percent. It always crash at this line -- result = [self displayWithParameters:drawParameters isCancelled:isCancelledBlock]; 
fileName:ASDisplayNode+AsyncDisplay.mm lineNumber:250
This line is getting image for ASImageNode, and crashing when _ASAsyncTransaction is doing this: operation._block = nil; (number: 241 fileName:_ASAsyncTransaction.mm)

I think something is wrong when releasing the displayBlock.

![crash1](https://cloud.githubusercontent.com/assets/1837609/17281166/c5d6c7ee-57cc-11e6-9257-0bf876ce1df0.png)
![crash2](https://cloud.githubusercontent.com/assets/1837609/17281167/c619b0d6-57cc-11e6-801e-1d561f86a5f8.png)

Crash log as follow:
Thread 35 Crashed: 0 Tmall4iPhone 0x0000000101a1b67c -[ASDealloc2MainObject release] ASDealloc2MainObject.m:29 (in Tmall4iPhone) 1 Tmall4iPhone 0x0000000101a3f390 __destroy_helper_block_ ASDisplayNode+AsyncDisplay.mm:251 (in Tmall4iPhone) 2 libsystem_blocks.dylib 0x0000000198c59910 __Block_release :256 (in libsystem_blocks.dylib) 3 libsystem_blocks.dylib 0x0000000198c59910 __Block_release :256 (in libsystem_blocks.dylib) 4 Tmall4iPhone 0x0000000101a2a430 ___ZN23ASAsyncTransactionQueue9GroupImpl8scheduleElPU28objcproto17OS_dispatch_queue8NSObjectU13block_pointerFvvE_block_invoke _ASAsyncTransaction.mm:241 (in Tmall4iPhone) 5 libdispatch.dylib 0x0000000198c053ac __dispatch_call_block_and_release :24 (in libdispatch.dylib) 6 libdispatch.dylib 0x0000000198c0536c __dispatch_client_callout :16 (in libdispatch.dylib) 7 libdispatch.dylib 0x0000000198c0df90 __dispatch_async_redirect_invoke :692 (in libdispatch.dylib) 8 libdispatch.dylib 0x0000000198c0536c __dispatch_client_callout :16 (in libdispatch.dylib) 9 libdispatch.dylib 0x0000000198c1140c __dispatch_root_queue_drain :1152 (in libdispatch.dylib) 10 libdispatch.dylib 0x0000000198c1275c __dispatch_worker_thread3 :108 (in libdispatch.dylib) 11 libsystem_pthread.dylib 0x0000000198de12e4 0x0000000198de0000 + 4836 12 libsystem_pthread.dylib 0x0000000198de0fa8 0x0000000198de0000 + 4008

**Comment by hannahmbanana** [comment]
@yufenglv: Thanks for reporting this. Could you capture the full backtrace for us using `bt all` in the console?

**Comment by yufenglv** [comment]
Sorry, I cannot reproduce the crash and it has no any other trends. It crash at all kinds of devices and operating systems.

**Comment by appleguy** [comment]
@yufenglv we've made several changes in master, and Pinterest has seen that the volume of this crash has fallen off.  There are some API changes in master, but if you roll back the change landed late last week for the updated Layout API, it wouldn't be difficult to update and ship your next version with this.

We don't have a pod version deployed for this, but the easiest option would be to ship from the releases/p6.11 branch (which is what Pinterest is using currently).  If you can only use full pod versions, be sure to update to at least 1.9.90 (which is older than p6.11)

I'm going to close this out for now, but please continue to update us (or reopen the issue) if you learn additional information.
