### ISSUE TITLE
[ASCellNode] Deprecation of highlight/selection breaking in swift

### ISSUE THREAD

**Issue by GitGadd** [facebook/AsyncDisplayKit#2025]
ASCellNode used to have setHighlighted/highlighted style properties, which have now been updated to setHighlighted/isHighlighted to match common objective-c style, with the old non-is style getters having been deprecated.

Swift no longer uses custom named getters, even if objective-c specifies a custom name for it. This results in the swift property's getter being deprecated, which in turn resulted in the entire property being hidden and only the getter method ( func highlighted() ) being exposed.

Can we lift this deprecation to support ASCellNode in Swift?

**Comment by hannahmbanana** [comment]
@maicki: do you remember what the resolution of this was? I believe you fixed this shortly after 1.9.80?

**Comment by maicki** [comment]
@hannahmbanana I fixed it in this PR: #1909 unfortunately we didn't release a new version with that change yet

@GitGadd Can you please point your ASDK either to master or to the 1.9.90 branch. There this should be fixed. Please let me know if not ...

**Comment by GitGadd** [comment]
@maicki Thanks, glad to hear this is already fixed. I'm using cocoapods but I'll google around to see if I can configure that in the podspec.

**Comment by maicki** [comment]
@GitGadd I will close this issue for now as it should be fixed at least with 2.0. Please let us know if this is not the case. Thanks!
