### ISSUE TITLE
[ASTableViewCellNode/ASTextNode]: ASTableViewCellNode/ASTextNode not resizing correctly

### ISSUE THREAD

**Issue by benjaminhorner** [facebook/AsyncDisplayKit#2032]
Hi,

I have a "rather complex" architecture for a view:
an ASCollectionNode with 3 ASCellNodes each containing an ASTableNode with N ASCellNodes. It all works great except for one little detail: the ASTextNodes in my ASCellNodes at the last level, seem to ignore completely resizing correctly to manage multiple lines.

I have set` maximumNumberOfLines = 0` && `truncationMode = NSLineBreakMode.ByWordWrapping` on these ASTextNodes, however, they simple span forever on a single line.

My first thought was the constrained size in the` layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec` method was incorrect. But I logged it and the size is that of the cell… if all ASTextNodes had only one single line.

Here is what I have:

 ```
questionNode = ASTextNode()
if let question = model?.name {
            questionNode.attributedText = NSAttributedString(string: question, attributes: NotificationCenterTypography.DetailCellQuestionAttributes)
}
        
questionNode.maximumNumberOfLines = 0
questionNode.truncationMode = .ByWordWrapping
questionNode.layerBacked = true
questionNode.backgroundColor = UIColor.blueColor()

[...]



override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        
         let textChildren: [ASLayoutable] = [userNameNode, totalPeopleWantToknowNode, questionNode]
         
         let textSpec = ASStackLayoutSpec(direction: .Vertical, spacing: 0, justifyContent: ASStackLayoutJustifyContent.Start, alignItems: .Start, children: textChildren)
         textSpec.alignSelf = .Stretch
         
         let mainSpec = ASStackLayoutSpec(direction: .Horizontal, spacing: 15, justifyContent: .Start, alignItems: .Start, children: [avatarnode, textSpec])
         
         mainSpec.alignSelf = .Stretch
         
         let spec = ASInsetLayoutSpec(insets: UIEdgeInsetsMake(15, 15, 15, 15), child: mainSpec)
         
         return spec
     }
```

Any ideas where this could come from ?

Below are two screenshots of what happens…
![img_7094 2](https://cloud.githubusercontent.com/assets/3463436/17408950/76d627a4-5a6d-11e6-8684-9b3c471833a6.PNG)
![img_7094](https://cloud.githubusercontent.com/assets/3463436/17408951/76e2815c-5a6d-11e6-8d29-cb8b842c6901.PNG)

**Comment by maicki** [comment]
@benjaminhorner Set the `flexShrink` property to `true` for the text node

**Comment by benjaminhorner** [comment]
@maicki : Thanks for the suggestion, but it doesn't change anything. I still get the same result.

**Comment by benjaminhorner** [comment]
@maicki : finally figured it out. I did indeed have to use **flexShrink = true** but not on the ASTextNodes but on the ASStackLayoutSpec (textSpec in my code).

**Comment by maicki** [comment]
@benjaminhorner Ah ... you have to set it on the `textSpec`
