### ISSUE TITLE
[ASVideoNode] ASTableView with ASVideoNodes scrolling hiccups 

### ISSUE THREAD

**Issue by logicsb** [facebook/AsyncDisplayKit#2043]
I have some problems with hiccups when scrolling the feed containing videos. So, I download the ASDK example (VideoTableView) and that example seems to have an even worse problem with hiccups. Is anyone having the same problem? Does anyone know how to solve this? I would like a smooth  feed containing videos as Instagram does.

Thanks

**Comment by hannahmbanana** [comment]
@logicsb: you should join our AsyncDisplayKit Slack (http://asdk-slack-auto-invite.herokuapp.com/) and check out the discussion in the #asvideonode channel.

**Comment by HTKT** [comment]
@logicsb : Have you find out the solution? I also need to improve the performance scrolling for UICollectionVIew contains AVPlayer.

**Comment by logicsb** [comment]
@HTKT i'm studying some cases. For now what i think more interesting is using VTDecompressionSession to decoder video and display it on AAPLEAGLLayer.
[here](https://github.com/Hearnseu/iOSHWCodec) an example of this logic
