### ISSUE TITLE
[ASControlNode] subnode (another ASControlNode) requires explicit enabling of userInteractionEnabled

### ISSUE THREAD

**Issue by skensell** [facebook/AsyncDisplayKit#2044]
This is honestly a small issue, but I'm submitting it because it doesn't seem like this should be default behavior.

I have an ASControlNode subclass which has as a subnode another ASControlNode. Both the parent and the child have some target-actions set in its `-init` which based on what I've read in previous issues should automatically set `userInteractionEnabled` to `YES` for each node.  Well, the child node would only receive touch events when I explicitly set `userInteractionEnbabled` to `YES` in its `didLoad`.  Is this a bug?

**Comment by skensell** [comment]
I'm on 1.9.81.

**Comment by hannahmbanana** [comment]
@skensell: No issue is too small - thanks for asking this question! You are correct that setting a target-action pair on an `ASControlNode` should set `userInteractionEnabled` to `YES` for that node. 

Would you be able to provide a sample project? I created a sample project of my own, but wasn't able to duplicate the issue.

**Comment by skensell** [comment]
I created a sample project, but it's prob not worth sharing cuz I figured out my issue. I had a chain of several `ASControlNode`s, say outer -> inner -> leaf. The inner one did not have a target-action pair while the outer and the leaf did. So this is why I had to explicitly say `userInteractionEnabled` on the inner one. I guess the default `NO` for`userInteractionEnabled` just confused me because it's `YES` in UIKit.

**Comment by hannahmbanana** [comment]
@skensell: This is a great report - I appreciate the detailed explanation! I think we should definitely fix this to have automatic user interaction enabled for the case in which only the subnode enables. And this is very straightforward to do with our [ASEnvironment](http://asyncdisplaykit.org/docs/asenvironment.html) feature. 

@Adlai-Holler @chrisdanford: I think this will be important for your layer backing optimization.
