### ISSUE TITLE
[Question] Why is NSArray+Diffing not public?

### ISSUE THREAD

**Issue by skensell** [facebook/AsyncDisplayKit#2064]
I just stumbled upon `NSArray+Diffing.[hm]` which seems to provide exactly the methods I was looking for. Very useful for producing the insertion and deletion operations necessary for a tableView update block.  Is there a reason it's not publicly accessible?

**Comment by hannahmbanana** [comment]
@Adlai-Holler - any reason we shouldn't make this file public?

**Comment by maicki** [comment]
I think we should not expose these kind of classes / files that provide internal functionality, but basically does not really has something to do with what ASDK stands for.
It is for internal usage only and it would make it tremendously harder for us to change in the future, if we would expose all kinds of "helper" functionality publicly, e.g. we would have to be careful that we would not break any API from the past for this functions or if we don't have need internally anymore we cannot remove it etc.

@levi @Adlai-Holler @appleguy Thoughts?

**Comment by hannahmbanana** [comment]
cc @garrettmoon

**Comment by garrettmoon** [comment]
I concur with @maicki

**Comment by hannahmbanana** [comment]
@skensell: Unfortunately, we've reached consensus that we won't be making NSArray+Diffing.[hm] publicly accessible.

**Comment by garrettmoon** [comment]
@skensell but there's nothing stopping you from copying, pasting and renaming the function to use yourself!

**Comment by skensell** [comment]
Yeah, I copy-pasted it already.

I get that it's not part of the core functionality, however, here's a few reasons maybe it's worth reconsidering:

1. Since `ASCellNode`s do not implement reuse, if we want a non-flashing `ASTableView` then we have to avoid `reloadData` like the plague. With UIKit there are some cheap tricks I (and I'm sure others) used to employ which allowed us to inexpensively call `reloadData` (e.g. when reusing a `UITableViewCell` whose backing model didn't change, then no need to relayout).  With `ASTableView` however, we are forced to carefully insert and delete rows and sections.  A helper method like this is kind of like the least amount of help you can offer.

2. While the implementation of such a method may change, I can't imagine this one changing, nor its interface really needing a change.

3. You have less helpful categories already made public (see `NSMutableAttributedString+TextKitAdditions.h`)

Anyways, I'm fine with my copy-paste solution, I just think others may appreciate not having to copy-paste it into their own projects.

**Comment by Adlai-Holler** [comment]
@skensell I agree. We will silently make the files available – we will not document them or make any guarantees about their API stability, but if an enterprising developer wants to use them, then we'll give them the choice. We're all in this together! #2078

**Comment by skensell** [comment]
@Adlai-Holler Awesome, thanks! 👍
