### ISSUE TITLE
[ASNetworkImageNode] Download Progress Callback

### ISSUE THREAD

**Issue by stapleup** [facebook/AsyncDisplayKit#2068]
Hi, Thank you for the Awesome library (*Insert thumbs up here*), is it possible for us to get callback on how much image is downloaded so that we could show the progress in some sort of progress bar, the `PINRemoteImage` Library does support this functionality but its instance created in `ASNetworkImageNode` is private, so I was hoping may be some sort of way we could get progress without actually modifying the library.

Thanks

**Comment by hannahmbanana** [comment]
@stapleup: thanks for reporting this! I was under the impression that there was some way to do this, but it does look like this functionality is currently missing.  

@garrettmoon: do you know of a way to do this with the current framework? Should I add this to our 2.1 milestone?

**Comment by garrettmoon** [comment]
It looks like it's piped through part of the way (to ASPINRemoteImageDownloader), but none of the nodes are taking advantage of it. So yeah, we could add support to ASNetworkImageNode and ASMultiplexImageNode. 2.1 seems like the right call.

**Comment by hannahmbanana** [comment]
@stapleup: Feel free to post a PR if you'd like to add support for this soon. Otherwise, we'll add it to our roadmap for the September / October time frame.

**Comment by stapleup** [comment]
Ok, Thanks for your response :)

**Comment by stapleup** [comment]
@hannahmbanana I just wanted to suggest 2 more features, if you could include them with your upcoming release than that would be great 👍 

1. UIProgressNode: an AsyncDisplayKit wrapper around UIProgressView
2. UIRemoteImageNode: Ability to fade-in the image once it has been downloaded

I think UIProgressNode can be done easily by using the way UIScrollNode is implemented (as a simple wrapper around UIScrollView), but it would be helpful to have it included in the library.

Thanks

**Comment by stapleup** [comment]
@hannahmbanana can you please tell me if this feature has been added yet?

**Comment by garrettmoon** [comment]
@stapleup for progressively rendered images you can get the `renderedImageQuality` from the ASNetworkImageNode. That's not *exactly* what you're looking for likely but it may suffice?

In addition, you could wire up the downloadProgress block on ASImageProtocols to ASNetworkImageNode and put up a PR.

**Comment by garrettmoon** [comment]
@stapleup FYI though, this repo is archived, all future development is at https://github.com/texturegroup/texture
