### ISSUE TITLE
Create an image node that supports animated GIFs

### ISSUE THREAD

**Issue by geoffmacd** [facebook/AsyncDisplayKit#207]
ASImageNode and ASMultiplexImageNode do not support animated images.

**Comment by MrReN** [comment]
Hi,you can user ASNetImageNode delegate
 -(void)imageNodeDidFinishDecoding:(ASNetworkImageNode *)imageNode{
    }

**Comment by secretiverhyme** [comment]
@geoffmacd, do you mean animated images in general, or something like setting an animated GIF as the `.image` property on ASImageNode and having it just work?

**Comment by geoffmacd** [comment]
Yes, animated GIFS

**Comment by debug29** [comment]
It could be good to have also NSArray of image like actual UIImageView, for
building pulltorefreshcontrol or loading elements.

2015-01-15 5:59 GMT+01:00 Geoff MacDonald <notifications@github.com>:

> Yes, animated GIFS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/AsyncDisplayKit/issues/207#issuecomment-70040105>
> .
>



-- 
Florian COULON
Développeur iOS/Android/WindowsPhone :  Linkea/Zi-Apps
Fondateur SoundFi / MyNetShare / BrainConnection
Tel Perso : 06.76.48.50.53
E-mail : f.m.coulon@gmail.com

**Comment by RuiAAPeres** [comment]
@secretiverhyme any update on this? :heart:

**Comment by martin-gearzero** [comment]
+1 for this feature please

**Comment by appleguy** [comment]
@martin-gearzero @RuiAAPeres thanks for weighing in / upvoting this one :).  I would eagerly accept a contribution that implements this.  However, I won't have a chance to build it myself for quite some time.

**Comment by appleguy** [comment]
@geoffmacd @MrReN @debug29 @RuiAAPeres @martin-gearzero 

Great news! @garrettmoon has implemented this recently and is planning to merge it upstream later this coming week. The integration should be quite seamless for most apps. Look for the pull request and feel free to start using it against the master branch when it lands. Expect it to be included in the 1.9.8 release (this is release is several weeks out however).

**Comment by hannahmbanana** [comment]
@geoffmacd @MrReN @debug29 @RuiAAPeres @martin-gearzero - check out PR #1485
