### ISSUE TITLE
[ASTextNode] Text node size changes when the attributed text is set rather than auto-scaling to fixed text node size via pointSizeScaleFactors

### ISSUE THREAD

**Issue by klivin** [facebook/AsyncDisplayKit#2077]
I want to have an ASTextNode using auto-scale text that stays in a FIXED SIZE ASTextNode like UILabel, and this is seeming way too difficult to achieve something so simple.  Side note, I am not using ASDK collection view for these cells, but I have need for a custom one as there are way too many changes to achieve what I need without substantial re-write. I do make sure to call measure, then needs display on ContentNode after adding it...

Anyway, for more detail: 
I am setting the attributed text node in a ContentNode with variable length text, and am trying to use the pointSizeScaleFactors to achieve an auto-scale of the text.  I am seeing that the text node size changes, I want the size of the text node to STAY FIXED and the text to grow/shrink to fit.  I am trying using layoutSpecThatFits to specify the text node size, even still, the text node size appears to be determined by the text length when laying out, not the layout spec.  What results is something that randomly sizes the text node depending on previously set strings.  It only occurs when the containing cell is re-used (ie. the contentNode already exists and we are just setting the text)

The content node with the auto shrink text:
`class ContentNode : ASDisplayNode {

    init(frame: CGRect, primaryText : NSAttributedString, secondaryText : NSAttributedString?) {
        super.init()
        self.layerBacked = true
        self.primaryAttributedString = primaryText
        self.secondaryAttributedString = secondaryText
        self.addPrimaryText(frame)
        self.addSecondaryText(frame)
    }

    var primaryAttributedString : NSAttributedString? {
        didSet {
            if let node = primaryTextNode {
                node.attributedString = primaryAttributedString
            }
        }
    }
    
    var secondaryAttributedString : NSAttributedString? {
        didSet {
            if let node = secondaryTextNode, secondaryText = secondaryAttributedString {
                node.attributedString = secondaryText
            }
        }
    }
    
    private var primaryTextNode : ASTextNode?
    private var secondaryTextNode : ASTextNode?
    
    private func addPrimaryText(inFrame : CGRect) {
        let node = ASTextNode()
        node.maximumNumberOfLines = 1;
        node.attributedString = self.primaryAttributedString
        node.flexShrink = false
        node.flexGrow = false
        node.layerBacked = true

        self.addSubnode(node)
        
        node.pointSizeScaleFactors = [0.9, 0.8, 0.7]
        self.primaryTextNode = node
    }
    
    private func addSecondaryText(inFrame : CGRect) {
        guard let secondaryAttributedString = self.secondaryAttributedString else {
            return
        }
        let node = ASTextNode()
        node.maximumNumberOfLines = 1;
        node.attributedString = secondaryAttributedString
        node.flexShrink = false
        node.flexGrow = false

        node.layerBacked = true
        self.addSubnode(node)
        node.pointSizeScaleFactors = [0.9, 0.8, 0.7]
        self.secondaryTextNode = node
    }
    
    override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        var mainStackContent = [ASLayoutable]()
        
        if let primaryNode = primaryTextNode {
            let inset = ASInsetLayoutSpec(insets: UIEdgeInsetsMake(0, self.frame.width/4.2, 0, self.frame.width/4.2), child: primaryNode)

            mainStackContent.append(inset)
        }
        if let secondaryNode = secondaryTextNode {
            let inset = ASInsetLayoutSpec(insets: UIEdgeInsetsMake(0, self.frame.width/4, 0, self.frame.width/4), child: secondaryNode)

            mainStackContent.append(inset)
        }
        
        let contentSpec = ASStackLayoutSpec(direction: .Vertical, spacing: 2, justifyContent: .Center, alignItems: .Center, children: mainStackContent)

        let vertical = ASCenterLayoutSpec(centeringOptions: .XY, sizingOptions: .Default, child: contentSpec)
        let inset = ASInsetLayoutSpec(insets: UIEdgeInsetsMake(0, 0, 7*deviceScale, 0), child: vertical)

        return inset
    }
    
}`

Where i set the attributed text dynamically:
`   
func setContentText(primaryText : String, secondaryText : String?) {
        let shrinkRatio = self.bounds.size.width/300 < 1 && self.bounds.size.width/300 > 0 ? self.bounds.size.width/300 : 1.0
        let contentPercent = secondaryText == nil ? CellConstants.defaultFillPercent : CellConstants.doubleLineFillPercent
        let contentFrame = self.bounds.bottomFillFrame(contentPercent)

        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
            let font = UIFont(name: KLIMediumFont, size: 23 * deviceScale * shrinkRatio)!
            let primary = NSAttributedString.centeredAttributedString(primaryText, font: font, color: UIColor.whiteColor())
            var secondary : NSAttributedString?
            if let text = secondaryText {
                let font = UIFont(name: KLIMediumFont, size: 14 * deviceScale * shrinkRatio)!
                secondary = NSAttributedString.centeredAttributedString(text, font: font, color: UIColor.whiteColor())
            }
            if let node = self.contentNode {
               // THIS BLOCK IS WHERE TEXT SIZES USE THE ORIGINAL INSTANTIATED SIZE OF THE TEXT NODE, rather than autoscaling text to fixed size text node.
                node.primaryAttributedString = primary
                node.secondaryAttributedString = secondary
                dispatch_async_main() {
                    self.setNeedsLayout()
                }

            } else if let fillNodeShowing = self.fillNode {
                dispatch_async_main() {
                    let node = ContentNode(frame: contentFrame, primaryText: primary, secondaryText: secondary)
                    self.contentNode = node

                    fillNodeShowing.addSubnode(self.contentNode!)
                    node.measure(contentFrame.size)

                    self.setNeedsLayout()
                }
            }
        }
    }
`

**Comment by hannahmbanana** [comment]
@maicki @garrettmoon: This is a known issue with the current way that ASTextNode sizes itself, correct? I believe that we are fixing this for 2.0, but do we have a current work around?

**Comment by hannahmbanana** [comment]
@klivin: could you wrap the textNode in a static spec and set a .sizeRange on the textNode that provides a fixed size?

**Comment by klivin** [comment]
Using a sizeRange with fixed point size worked!!  Thanks!
