### ISSUE TITLE
Add newline at the end of all source files that miss that.

### ISSUE THREAD

**Issue by Yue-Wang-Google** [facebook/AsyncDisplayKit#2080]
-Wnewline-eof  will complain while compiling code that include ASDK headers. It more readable if we can add new lines to each of those files. Especially, to the following files:
/AsyncDisplayKit/ASMapNode.h
/AsyncDisplayKit/ASRunLoopQueue.h
/AsyncDisplayKit/ASViewController.h
/AsyncDisplayKit/Details/ASEnvironment.h
/AsyncDisplayKit/Details/ASMutableAttributedStringBuilder.h
/AsyncDisplayKit/Details/ASPhotosFrameworkImageRequest.h
/AsyncDisplayKit/Details/ASRangeController.h
/AsyncDisplayKit/Details/NSMutableAttributedString+TextKitAdditions.h
/AsyncDisplayKit/Details/UICollectionViewLayout+ASConvenience.h
/AsyncDisplayKit/Layout/ASStackLayoutSpec.h
(the list is based on an old ASDK cut, so it's not meant to be updated/complete)

**Comment by hannahmbanana** [comment]
Thanks @Yue-Wang-Google for alerting us to this issue!
