### ISSUE TITLE
ASViewController does not resize when contained in a Container View

### ISSUE THREAD

**Issue by dmcrodrigues** [facebook/AsyncDisplayKit#2085]
This seems similar/related to #1959 but this happens consistently in both iOS 8 and 9. I also tested with both 1.9.80, 1.9.81 and master and the issue happens consistently.

An `ASViewController` added as child view controller in a simple `UIViewController` which also is a child view controller but contained in a Container View is not resized at all, it keeps the original dimensions of the size class.

A workaround to force the resize is overriding this methods in the parent view controller and tweak the instance of `ASViewController`.

``` swift
override func traitCollectionDidChange(previousTraitCollection: UITraitCollection?) {
     super.traitCollectionDidChange(previousTraitCollection)
     viewController.traitCollectionDidChange(previousTraitCollection)
}

override func viewDidLayoutSubviews() {
     super.viewDidLayoutSubviews()
     viewController.view.frame = view.frame
     viewController.view.setNeedsLayout()
}
```

I'm attaching a sample project where the issue can be observed, the red view controller (`ASViewController`) should overlap completely his parent, the green one, but it doesn't.

![simulator screen shot 17 aug 2016 13 01 53](https://cloud.githubusercontent.com/assets/1098602/17735556/cab4a9d8-647a-11e6-8c80-74d81aef18e9.png)

If we set `ContainedViewController` as the _Initial View Controller_ in the Storyboard, and that way removing the Container View from the equation, the red view controller (`ASViewController`) is properly resized to match the size of the parent.

The sample project can be found here:
[StoryboardContainedEmbed.zip](https://github.com/facebook/AsyncDisplayKit/files/422505/StoryboardContainedEmbed.zip)

**Comment by tungvoduc** [comment]
I have the same problem. I have a custom view controller container that contains two ASViewController instances as child view controllers. Changing child view controllers' frames in viewWillLayoutSubviews used to work but not anymore after version 2.0-beta.1.

**Comment by hannahmbanana** [comment]
This may be resolved by #2736.

**Comment by maicki** [comment]
I just tested this with `master` and it appears to be fixed with the recent changes we did around `ASViewController` and the layout based on the bounds.

I will close this issue for now please reopen if you think it's not fixed in your case.

**Comment by hannahmbanana** [comment]
cc @dmcrodrigues
