### ISSUE TITLE
Help! ASTableView reloadData then A white View appeared!

### ISSUE THREAD

**Issue by qq644531343** [facebook/AsyncDisplayKit#2098]
Simple Description:
1, I add ASTableView ; 2, I request Data and then reload ASTableView 3, I request Other Datas ，and reload Section 0。  Then the white View appeared some times。

The ShortScreen below:
https://github.com/qq644531343/GaoDeMap/blob/master/pics/1.png
https://github.com/qq644531343/GaoDeMap/blob/master/pics/2.jpg
https://github.com/qq644531343/GaoDeMap/blob/master/pics/3.png
https://raw.githubusercontent.com/qq644531343/GaoDeMap/master/pics/4.png

> There is my code
> https://github.com/qq644531343/cppsrc/blob/master/c/FreshTabViewController.txt

**Comment by hannahmbanana** [comment]
@qq644531343 - sorry it took us so long to reply, our small team was busy building ASDK 2.0 this fall. Were you able to get around this issue? If not, could you provide a video? I don't understand / see the "white view" you are talking about.

**Comment by hannahmbanana** [comment]
@qq644531343 - Due to the length of time since this thread was active, I'm going to close this issue. However, if you have any updates for us, please re-open this issue or file a new one and we'd be happy to help you out!
