### ISSUE TITLE
ASTextNode support exclusion paths like UITextView

### ISSUE THREAD

**Issue by wangshengjia** [facebook/AsyncDisplayKit#210]
That would be great if ASTextNode can support also exclusion paths like UITextView. Do you have a plan about that ?

Thanks.

**Comment by secretiverhyme** [comment]
ASTextNode uses exclusion paths internally to support truncation — check out `ASTextNodeRenderer.mm` to see how it works.  We don't have any plans to add exclusion paths to the ASTextNode API, but pull requests are always welcome!  =]

**Comment by wangshengjia** [comment]
Ok, cool. Thanks for reply. I will check it out and try : ]
