### ISSUE TITLE
[Memory issue] Using ASCollectionNode with 10000 above items

### ISSUE THREAD

**Issue by roytang121** [facebook/AsyncDisplayKit#2114]
I am trying to integrate ASCollectionNode into my current project for creating a Photo Viewer.
When I first trying to create 10000 items for the ASCollectionNode, it seems to be creating all the ASCellNode when viewDidLoad. The memory goes up to >500MB.

I understand that Nodes are not being reused in AsyncDisplayKit, but having 10000 items creating when viewDidLoad just crashed the whole app. 
Am I possibly doing something wrong or it's a limitation with AsyncDisplayKit ?

**Comment by zdenektopic** [comment]
Isnt issue that you are holding those images in your model in memory?

**Comment by roytang121** [comment]
@zdenektopic thank you for the reply . 
Nope , just simply creat a ASCollectionNode with 10000 items （use node block) , it already used up few hundreds MB memory.

**Comment by Adlai-Holler** [comment]
@roytang121 Are you accessing node.view or node.layer during your init/creation code? It's important to avoid that, and ensure the view/layer is only created by ASDK when you scroll to an item.

**Comment by roytang121** [comment]
@Adlai-Holler Thanks for the reply. Actually by just creating 10000 ASCellNode (using nodeBlock) it will used up ~600MB memories. Add up to 100_000 will even crashed the app.

here is a very simple project regenerating the issue.
https://github.com/roytang121/ASDK-issue

**Comment by Adlai-Holler** [comment]
At this time, we don't have direct support for creating a collection with that many nodes.

Your best bet is to provide a smaller initial set of nodes, maybe 300, and use the batch fetching API to load more as the user scrolls.

**Comment by roytang121** [comment]
@Adlai-Holler Thanks !

**Comment by Adlai-Holler** [comment]
@roytang121 We've got it marked as a feature in our internal issue tracker, stay tuned 🙂

**Comment by tokumaryogesh** [comment]
Any update ?

**Comment by BryanJBryce** [comment]
Bump

**Comment by nguyenhuy** [comment]
Hi, if you're creating a ton of items with the same size, like a photo gallery or view pager, check out the new ASCollectionGalleryLayoutDelegate In our new [repo](https://github.com/TextureGroup/Texture). Also check out the ASCollectionView example (examples/ASCollectionView) for how to use it. Finally, hit us up on Slack if you have questions/issues.
