### ISSUE TITLE
[Question] How does this work with UIDynamics?

### ISSUE THREAD

**Issue by jyounus** [facebook/AsyncDisplayKit#2116]
Hey there,

I haven't worked with ASDK yet, but I'm considering it for my next project. I was wondering how this integrates with UIDynamics? 

Here's an example of something I'd like to implement. Please scroll down to see a gif animation of a collection view:

```
https://www.objc.io/issues/5-ios7/collection-views-and-uidynamics/
```

Would this be possible? I obviously want to take advantage of doing as little work on the main thread as possible.

Thanks!

**Comment by hannahmbanana** [comment]
Theoretically AsyncDisplayKit should work with UIDynamics, but I haven't personally tried it out. I'd be interested to hear if anyone else has tried this.
