### ISSUE TITLE
ASNetworkImageNode+SDWebImage causing dead lock

### ISSUE THREAD

**Issue by IvanChan** [facebook/AsyncDisplayKit#2138]
I use ASNetworkImageNode+SDWebImage for image-display in a tableView

A dead lock occurred when I scroll the tableview (a lot image node display).

It looks like happened when cached return nil & start to download image, I tried comment the completion-block-calling in download, the dead lock disappear.

here is the stack & code
(what is more, why the last image show my local path? I build a static library(.a) & put it into my app, this path shows up when in other computer)

![1](https://cloud.githubusercontent.com/assets/3829585/17962643/60980462-6ae4-11e6-96a7-1052c65a8369.png)
![2](https://cloud.githubusercontent.com/assets/3829585/17962645/61286c3c-6ae4-11e6-8ec6-56553e1a87f4.png)
![3](https://cloud.githubusercontent.com/assets/3829585/17962644/61275a86-6ae4-11e6-846e-0434c5c4cd09.png)

[Archive.zip](https://github.com/facebook/AsyncDisplayKit/files/436503/Archive.zip)

**Comment by IvanChan** [comment]
It's not always locking-wait in "contentScale", sometimes in [ASNetworkImageNode _lazilyLoadImageIfNecessary]

**Comment by IvanChan** [comment]
I find out that I forgot to enable webp for SDWebImage  which leading the download to be fail (actually is image-decoding fail)

But I think there is still problem with ASDK?  Is it something I shouldn't do to call completionBlock with (nil, error, identifier) when SDWebImage fail ? just like code below?
--------------------------------
- (nullable id)downloadImageWithURL:(NSURL *)URL
                      callbackQueue:(dispatch_queue_t)callbackQueue
                   downloadProgress:(nullable ASImageDownloaderProgress)downloadProgress
                         completion:(ASImageDownloaderCompletion)completion
{
    
    id downloadIdentifier = [self.webImageManager downloadImageWithURL:URL
                                                               options:0
                                                              progress:^(NSInteger receivedSize, NSInteger expectedSize) {
                                                                  
                                                                  if (downloadProgress)
                                                                  {
                                                                      dispatch_async(callbackQueue ?: dispatch_get_main_queue(), ^{
                                                                          
                                                                          downloadProgress((CGFloat)receivedSize / expectedSize);
                                                                      });
                                                                  }
                                                              }
                                                             completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
                                                                 
                                                                 if (finished)
                                                                 {
                                                                     dispatch_async(callbackQueue ?: dispatch_get_main_queue(), ^{
                                                                         
                                                                         completion([ASImageWrap wrapImage:image], error, downloadIdentifier);
                                                                     });
                                                                 }
                                                                 
                                                             }];
    return downloadIdentifier;

}

**Comment by luohui8891** [comment]
Hi where did you get `ASNetworkImageNode+SDWebImage`?
I can't find it in current version.

**Comment by IvanChan** [comment]
@luohui8891 that would be my code

this crash recently disappear for a while
