### ISSUE TITLE
ASDisplayNode resize API & ASTableView+ASCollectionView integration

### ISSUE THREAD

**Issue by kylehickinson** [facebook/AsyncDisplayKit#214]
Interested in the challenges that this brings (re-layout & re-render too expensive?).  Currently changing the frame of a `ASTableView` or `ASCollectionView` doesn't do anything without also reloading the data (which then doesn't reposition to your previous visible rect).

**Comment by secretiverhyme** [comment]
We'd already like to add support for per-node ASTableView / ASCollectionView cell resizes — e.g., animating a height change to accommodate expanding text in an ASTableView cell node.  This will probably require a new subclass hook or two in the base ASDisplayNode class.  That same hook could probably be used for rotation support.

A couple of interesting points to think about in building this:
* measure-time support for multiple layouts — e.g., a cell that expands to show more text should compute both text node frames at once
* (optionally) having ASTableView / ASCollectionView pre-compute all layout information for orientation changes
* synchronously performing layout and rendering for visible nodes at rotation time, then tying into the working range system for remaining nodes

**Comment by secretiverhyme** [comment]
Come to think of it, let's consolidate this into #225.
