### ISSUE TITLE
Committing Appstore rejected by non-public API

### ISSUE THREAD

**Issue by IvanChan** [facebook/AsyncDisplayKit#2144]
FYI

![c27d2943-c17d-4538-9b3a-c6c8c18f338a](https://cloud.githubusercontent.com/assets/3829585/17991492/cd4f62fc-6b71-11e6-8e4d-4f423b9a148c.png)

**Comment by Adlai-Holler** [comment]
What!? Thanks for raising this issue, those are naming collisions between our APIs and Apples. We will resolve this soon @IvanChan

**Comment by IvanChan** [comment]
You can dump all system headers, scan to compare those api before commit a release version.😃

**Comment by hannahmbanana** [comment]
@IvanChan: Are you sure that this is due to ASDK? I'm just confused why we haven't had this problem with any of our Pinterest submissions (or heard from anybody else in the community about this).

**Comment by IvanChan** [comment]
@hannahmbanana Aye, I am sure about that. Maybe because I use ASDK as static Library, and  Apple has different audit strength for different apps.

I changed that APIs with adding prefix "as_" & resubmit my app, Apple just approved that recently.

Anyway, it's best for us to avoid using APIs that looks like some sensitive APIs from Apple.

**Comment by hannahmbanana** [comment]
@Adlai-Holler @maicki: should we consider renaming these for 2.0?

**Comment by Adlai-Holler** [comment]
Yeah. It’ll be a bit of a hassle because PINRemoteImage actually sets those names in class PINAnimatedImage and we mirror them in protocol ASAnimatedImage.

It’ll be wacky but we’ll need to use other names. Unfortunately deprecating the current ones probably won’t be enough – we’ll have to remove them. 

ship://Problems/210

**Comment by GitGadd** [comment]
I just got the same rejection but with two additional non-public API references in the list. Unfortunately, I did not think of screenshotting it right away and the resolution center ticket has now been removed.

The build that got rejected was built using a fork based on master as of yesterday (14 sept -16), the latest commit being 025af5d594eb894480b30a963b8ece4dc3e0a729.

(Including that in case this was considered fixed, not sure from reading the issue)

**Comment by IvanChan** [comment]
@GitGadd The admin account will receive a mail about the rejection, you can check the mail if possible.

**Comment by Skyna** [comment]
What can i do until it will be fixed in 2.0?

**Comment by GitGadd** [comment]
@IvanChan The rejection email doesn't state the reasons, it just links to resolution center (in which the ticket has been removed). @Skyna I passed two App Store reviews and 1 beta review now, if you don't find a fix in time I would suggest just trying to convince the review team by linking to this issue. No guarantees though, depends so much on the review team in question...

**Comment by kharmabum** [comment]
`totalDuration` also needs to go on the chopping block.
![screen shot 2016-09-26 at 12 05 53 pm](https://cloud.githubusercontent.com/assets/783557/18848096/a8c2ba3c-83e1-11e6-8e54-00b0702f17ec.png)

**Comment by garrettmoon** [comment]
I'm worried that we can't know what will be next. It looks like people have had success simply resubmitting the same binary with only a version number bump: https://pspdfkit.com/guides/ios/current/announcements/private-api-rejections/

**Comment by gazreese** [comment]
The page from the above link now has the following text at the top:

_Update: Various sources report that Apple fixed this issue internally and updated their internal filter list to remove "obvious" names that likely clash. The last report about this issue was in late September 2016._

Maybe this is something we just need to monitor for a while?

**Comment by IvanChan** [comment]
I recently use pod for ASDK+PINCache, apple did not reject my app for those api. (Before, I pack ASDK as static library without PINCache.)

I found that if you are using APIs that declared in your project without implementation, apple will take that as private APIs if they looks like apple's method.

If you implement them, whatever, it works. 

I think that is the reason for my case. Hope it will be help.

**Comment by maicki** [comment]
Based on the update for the blogpost on PSPDFKit and feedback from @IvanChan it seems like Apple did some adjustments and will not reject apps so easily. I will close this issue for now, but I agree with @gazreese we should monitor that for a while and in case it reappears reopen this issue.

Thanks to all for helping out!
