### ISSUE TITLE
Confusion with layout specs - adding a layout spec is making nodes disappear

### ISSUE THREAD

**Issue by ProjectDent** [facebook/AsyncDisplayKit#2154]
I'm attempting to adopt ASyncDisplayKit for a table view of data. I'm struggling with the layout for the cell, which is a subclass of ASCellNode. What I want is to have a content node, which contains a text node.

I have this initialised like so:

```
override init() {
    super.init()

    self.addSubnode(self.contentNode)
    self.contentNode.addSubnode(self.textNode)
}
```

And then I give them both a colour so I can see them:

```
override func layout() {
    super.layout()

    self.contentNode.backgroundColor = UIColor.greenColor()
    self.textNode.backgroundColor = UIColor.blueColor()
    self.textNode.attributedString = ConversationTextNode.attributedString(self.text)
}
```

When it comes to the layout, if I only apply layout to the content node, it appears as expected, sans the label:

```
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
    self.contentNode.preferredFrameSize = self.contentNodeSize(constrainedSize: constrainedSize)
    let contentNodeInsets = self.contentNodeInsets(constrainedSize: constrainedSize)
    let insetLayoutSpec = ASInsetLayoutSpec(insets: contentNodeInsets, child: self.contentNode)

    return insetLayoutSpec
}
```

It looks like this:

[![enter image description here](http://i.stack.imgur.com/SyxMs.png)](http://i.stack.imgur.com/SyxMs.png)

And the ascii art for that looks like this:

```
-ASInsetLayoutSpec-
|  ASDisplayNode  |
-------------------
```

So then I want to display the text node inside the content node. I change the `layoutSpecThatFits` function to this:

```
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
    self.contentNode.preferredFrameSize = self.contentNodeSize(constrainedSize: constrainedSize)
    let contentNodeInsets = self.contentNodeInsets(constrainedSize: constrainedSize)
    let insetLayoutSpec = ASInsetLayoutSpec(insets: contentNodeInsets, child: self.contentNode)

    let attributedString = ConversationTextNode.attributedString(self.text)
    self.textNode.preferredFrameSize = ConversationTextNode.attributedStringSize(attributedString, cellWidth: constrainedSize.max.width)
    //Result of preferredFrameSize is width 80, height 20.
    let textLayout = ASInsetLayoutSpec(insets: ConversationTextNode.textInsetFromBubble(), child: self.textNode)

    insetLayoutSpec.setChild(textLayout)

    return insetLayoutSpec
}
```

The result now looks like this:

[![enter image description here](http://i.stack.imgur.com/rNuXk.png)](http://i.stack.imgur.com/rNuXk.png)

The cell loses all height, I can no longer see the content node, and the text node can't be seen either. The ascii art looks like this:

```
-----ASInsetLayoutSpec-----
|  --ASInsetLayoutSpec--  |
|  |     ASTextNode    |  |
|  ---------------------  |
---------------------------
```

I've tried this a number of different ways, using various different layout specs, but it all comes up the same.

I'm very confused about this. Any help is really appreciated.

**Comment by ay8s** [comment]
@ProjectDent It looks like you're simply overwriting the child for insetLayoutSpec. You'd need to add another spec to add the text to the insetLayoutSpec. I don't quite have a Swift AsyncDisplayKit setup right now to give you an example. 

Feel free to post an example and I can help you out if you can't figure it out.

**Comment by maicki** [comment]
@ProjectDent you should structure it a bit different. In your content node add the text node in there and add a `layoutSpecThatFits:` that returns and inset spec for the text node:

```Swift
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
    let attributedString = ConversationTextNode.attributedString(self.text)
    self.textNode.preferredFrameSize = ConversationTextNode.attributedStringSize(attributedString, cellWidth: constrainedSize.max.width)
    return ASInsetLayoutSpec(insets: ConversationTextNode.textInsetFromBubble(), child: self.textNode)
}
```

Within the cell node add an inset to the content node:
```Swift
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
  self.contentNode.preferredFrameSize = self.contentNodeSize(constrainedSize: constrainedSize)
  let contentNodeInsets = self.contentNodeInsets(constrainedSize: constrainedSize)
  return ASInsetLayoutSpec(insets: contentNodeInsets, child: contentNodeInsets)
}
```

Let me know if this helps ...

**Comment by hannahmbanana** [comment]
@ProjectDent - Given the length of time since this issue was active, I'm going to close it. Feel free to reopen it if you're still having issues!
