### ISSUE TITLE
Always crashing in insert rows of ASDataController in 1.9.90

### ISSUE THREAD

**Issue by jaichaudhry** [facebook/AsyncDisplayKit#2175]
I am trying to execute the following command:
[self.tableView insertRowsAtIndexPaths:indexPaths withRowAnimation:UITableViewRowAnimationNone];

and getting crash in - (void)_layoutNodesFromContexts:(NSArray<ASIndexedNodeContext *

> *)contexts ofKind:(NSString *)kind completion:(ASDataControllerCompletionBlock)completionBlock
> of ASDataController this is happening as soon as as I try to insert rows, this was working perfectly fine in 1.9.81.

[Backtrace.txt](https://github.com/facebook/AsyncDisplayKit/files/448944/Backtrace.txt)

**Comment by hannahmbanana** [comment]
@jaichaudhry: thanks for including the backtrace!

@Adlai-Holler: any recent changes that might have caused this? If you have a few minutes this week to educate me, we should document best practices for updating tables / collections.

**Comment by jaichaudhry** [comment]
@hannahmbanana 
To make this more clear I get one more thing on terminal which as follows:
*** Assertion failure in -[ASNetworkImageNode _displaysAsynchronously], /Users/jc/Roposo/redApple/Pods/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:928

But this was working perfectly in previous version.

**Comment by hannahmbanana** [comment]
@jaichaudhry: could you run this on the latest master and see if it's still an issue? If not, could we see more code? This backtrace, unfortunately, didn't provide much info.

**Comment by jaichaudhry** [comment]
@hannahmbanana Tried it on master. Still no luck.
Attaching the crash report. If that can be of help.
[com.roposo.iosroposo_issue_92_crash_18dbe957b848468b8b8074436d239907.txt](https://github.com/facebook/AsyncDisplayKit/files/458726/com.roposo.iosroposo_issue_92_crash_18dbe957b848468b8b8074436d239907.txt)

Also the only thing happening in code is as follows:
`NSUInteger newTotalNumberOfBlocks = tableBlocks.count;
        NSUInteger row;
        for (row = oldBlocksCount; row < newTotalNumberOfBlocks; row++) {
            NSIndexPath *path = [NSIndexPath indexPathForRow:row inSection:section];
            [indexPaths addObject:path];
        }
        
        
        ASCellNode *cellNode = [_tableView nodeForRowAtIndexPath:[NSIndexPath indexPathForRow:oldBlocksCount inSection:0]];
        if (cellNode && [cellNode isKindOfClass:[RPSCellLoaderNode class]] && !_failedURLPath) {
            [_tableView deleteRowsAtIndexPaths:@[[NSIndexPath indexPathForRow:oldBlocksCount inSection:0]] withRowAnimation:UITableViewRowAnimationNone];
        }
        
        if ([self showLoaderForViewControllerType:viewControllerType] && !_failedURLPath) {
            // Checking cell node here so that to ensure that it is present in table view while deleting.
            [indexPaths addObject:[NSIndexPath indexPathForRow:row inSection:0]];
        }
        
        [self.tableView insertRowsAtIndexPaths:indexPaths withRowAnimation:UITableViewRowAnimationNone];
        
        // This is to ensure that failedUrlPath check works for the deletion of loader node.
        _failedURLPath = nil;`

**Comment by jaichaudhry** [comment]
@hannahmbanana @Adlai-Holler any updates on this ?

**Comment by hannahmbanana** [comment]
@jaichaudhry - sorry for the delay in response, we've been busy getting the [2.0 release](http://asyncdisplaykit.org/docs/adoption-guide-2-0-beta1.html) ready. Are you still having issues with this? I'd recommend updating to the 2.0 API in which all table delegate / data source methods are called on the tableNode rather than the tableView.

**Comment by jaichaudhry** [comment]
@hannahmbanana I was still facing this issue with the previous updates. I will revert back once I shift to 2.0. Will do it next week.

**Comment by jaichaudhry** [comment]
@hannahmbanana @Adlai-Holler this has been fixed in 2.0. Thanks a lot :)

**Comment by jaichaudhry** [comment]
But now I am stuck with this issue : https://github.com/facebook/AsyncDisplayKit/pull/2651.
Is it safe to use master branch in my project ?

**Comment by hannahmbanana** [comment]
@jaichaudhry - I'm going to close this issue since it looks like it's been resolved. Master (2.0 Beta 3) is very safe, we very close to cutting the official 2.0 release.
