### ISSUE TITLE
[Question] Is v2.0 production ready for an app with release in October'16?

### ISSUE THREAD

**Issue by zubko** [facebook/AsyncDisplayKit#2181]
Hi! 

I'm considering using AsyncDisplayKit for a new app with a lot of UI animations/transitions.
The timeframe is very narrow, almost like 1 month to make it, so it's important to have less surprises/debugging of the framework in the process.

Do you think it's good to use 2.0 already or is it safer to use 1.9 still?

**Comment by hannahmbanana** [comment]
@zubko: the majority of the 2.0 features - including the [Layout Transition API](http://asyncdisplaykit.org/docs/layout-transition-api.html) and [automatic subnode management](http://asyncdisplaykit.org/docs/implicit-hierarchy-mgmt.html) - have been robustly tested by Pinterest's iOS app. The main changes remaining have to do with a refactoring of the Layout API. Most of the changes are designed to make the API more user friendly and aren't changes of the main functionality.

**Comment by hannahmbanana** [comment]
@zubko: I'm going to close this issue, but feel free to re-open it if you have any specific questions.
