### ISSUE TITLE
ASTextNode misaligned when screen scale is 3.0

### ISSUE THREAD

**Issue by Jercik** [facebook/AsyncDisplayKit#219]
I've found bug in ASTextNode when running on iPhone 6 Plus simulator. For some strings calculatedSize is slightly too large, which causes view to stretch. This results in blurry text and (probably) performance decrease.

Here is example project which demonstrates issue: https://github.com/Jercik/ASTextStretch. After enabling "Color Misaligned Images" you can see that first text node is stretched: 

![iphone6plus](https://cloud.githubusercontent.com/assets/154902/5743481/d4ec7578-9c19-11e4-9b66-e32d9959dbf9.png)
calculatedSize returned by first node is: {286.33334350585938, 45.666667938232422}. 
Second node's size was set manually to correct value which is: {286.33333333333331, 45.666666666666664}.

**Comment by ocrickard** [comment]
Nice find!  My guess is that we're getting some float math here: https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L68.  Most likely we need a more accurate way of computing the pixel values.

**Comment by Jercik** [comment]
I've found the issue. There is fminf() function used which causes double > float > double conversion (on 64 bit architecture) here: https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L199
