### ISSUE TITLE
sentence truncate too short in ASTextNode using `maximumNumberOfLines = 1;`

### ISSUE THREAD

**Issue by Jasonbroker** [facebook/AsyncDisplayKit#2194]
Hi~
I am green handed in ASDK.
I made a cell like this:
<img width="525" alt="qq20160905-0 2x" src="https://cloud.githubusercontent.com/assets/7604558/18239466/2232d872-7378-11e6-9c9b-693de3091919.png">

in picture:
![img_0038](https://cloud.githubusercontent.com/assets/7604558/18239140/ca4b701c-7375-11e6-9fe0-674e5202bc21.jpg)
![img_0039](https://cloud.githubusercontent.com/assets/7604558/18239152/d66ebdf4-7375-11e6-8123-58fcd676cc01.jpg)
code:
`    // overall
    ASStackLayoutSpec *stack = [ASStackLayoutSpec horizontalStackLayoutSpec];
    stack.direction = ASStackLayoutDirectionHorizontal;

```
_titleImageNode.spacingAfter = 15.f;

ASStackLayoutSpec *verticalLayout = [ASStackLayoutSpec verticalStackLayoutSpec];
verticalLayout.flexShrink = YES;

_cnTitleTextNode.maximumNumberOfLines = 1;
_enTitleTextNode.spacingBefore = 10;

verticalLayout.children = @[_cnTitleTextNode, _enTitleTextNode];

stack.children = @[_titleImageNode, verticalLayout];

ASInsetLayoutSpec *insetsLayout = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(8, 8, 8, 8) child:stack];


ASBackgroundLayoutSpec *backLayout = [ASBackgroundLayoutSpec backgroundLayoutSpecWithChild:insetsLayout background:self.backGroundNode];

ASInsetLayoutSpec *finalLayout = [ASInsetLayoutSpec insetLayoutSpecWithInsets:self.contentViewInsets child:backLayout];
return finalLayout;`
```

It seems the second textnode works good. BUT when setting the first textnode `xxxx.maximumNumberOfLines = 1;` and the string is more than 1 line(works perfect when the string is no more than 1 line) the textnode truncate itself too fast before reaching the end of the line(see the second label's ending point).

How could I fix it?

**Comment by hannahmbanana** [comment]
@Jasonbroker - I apologize for the delay in responding to your question. This is a known issue (see #2105) that is currently being worked on. There should be a fix on master in the next week or so.
