### ISSUE TITLE
Unable to subclass ASMultiplexImageNode in Swift

### ISSUE THREAD

**Issue by andyscott** [facebook/AsyncDisplayKit#220]
When subclassing `ASMultiplexImageNode` in Swift, I always get the following error:

    cannot override 'init' which has been marked unavailable

I believe you need to subclass in order to add a placeholder to a node, so this makes it impossible to add a placeholder to ASMultiplexImageNode in swift. I don't know how to work around it, but the culprit is the `NS_UNAVAILABLE` on ASMultiplexImageNode's default init. The error is odd since I'm never calling that initializer directly.

Sample subclass:

    private class FooBarImageNode : ASMultiplexImageNode {
        override init!(cache: ASImageCacheProtocol!, downloader: ASImageDownloaderProtocol!) {
            super.init(cache: cache, downloader: downloader)
        }
    }

**Comment by rnystrom** [comment]
Ah interesting. Looks like the strictness of Swift initializers is causing the issue here. We throw an assert if you use `-init` in Objective-C, so simply using the `NS_DESIGNATED_INITIALIZER` should do the trick here.

**Comment by andyscott** [comment]
Great! Thanks.
