### ISSUE TITLE
[Question] calling super.layoutSpecThatFits(constrainedSize) causes exception

### ISSUE THREAD

**Issue by benjaminhorner** [facebook/AsyncDisplayKit#2200]
Until now, I was always calling `super.layoutSpecThatFits(constrainedSize)` in my **layoutSpecThatFits** override.

However, since the update to 1.9.90, I get the following error when running:

```
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
    super.layoutSpecThatFits(constrainedSize)
    ...
    return spec
}
```
**ERROR**: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[ASDisplayNode layoutSpecThatFits:] should never fall through to return empty value'

An easy way to get round it is to delete the `super.layoutSpecThatFits(constrainedSize)` call. But might that not cause other issues?

**Comment by maicki** [comment]
@benjaminhorner As merging of `ASLayoutSpec`s was officially not supported it is not save to call super's `layoutSpecThatFits:`. Starting with 1.9.90 we throw an assertion to let the developer know that, so it is safe to delete `super.layoutSpecThatFits(constrainedSize)` for now.

We are currently looking into how to support merging of `ASLayoutSpec`s and we will update it accordingly as well as the documentation than.

**Comment by hannahmbanana** [comment]
@maicki: should I change this assertion to say "-layoutSpecThatFits: should never return an empty value. One way this is caused is by calling -[super layoutSpecThatFits:] which is not currently supported."

**Comment by maicki** [comment]
@hannahmbanana Sounds good. Having better error message is always great!

**Comment by hannahmbanana** [comment]
@benjaminhorner: thanks for notifying us of this confusion! It is indeed a bit odd that this subclass override doesn't allow calls to super.  I'm going to close this issue, but feel free to re-open if we didn't answer your question fully.
