### ISSUE TITLE
[ASCollectionView] prepareLayout not called on custom UICollectionViewLayout subclass

### ISSUE THREAD

**Issue by skensell** [facebook/AsyncDisplayKit#2211]
I copied and extended the `MosaicCollectionViewLayout` and the `MosaicCollectionViewLayoutInspector` classes from the CustomCollectionView example app.  I'm using it basically the same way as the example app.  The problem I'm experiencing is that the `prepareLayout` of the `MosaicCollectionViewLayout` is not called prior to the `ASDataController constrainedSizeForNodeAtIndexPath:` method which occurs during a layout pass. Is this a bug?

I'm on 1.9.81 and here's a screenshot of an exception I raise when `prepareLayout` has not been called.
<img width="476" alt="screen shot 2016-09-08 at 11 23 14 am" src="https://cloud.githubusercontent.com/assets/3983827/18344221/ab740e18-75b6-11e6-839d-89be7b24b956.png">

**Comment by hannahmbanana** [comment]
@skensell: Could you check this on `master` for us? I know that there have been several major improvements to that area since then.

**Comment by hannahmbanana** [comment]
Need to verify if this is still an issue on master. Many things have changed since 1.9.81.

**Comment by Adlai-Holler** [comment]
Hey @skensell there's no guarantee that `prepareLayout` will be called before `constrainedSizeForNodeAtIndexPath:`. `prepareLayout` is called by UIKit, `constrainedSizeForNodeAtIndexPath:` is called by ASDK when it starts measuring nodes asynchronously, before they're passed into UIKit.

Stay tuned to #2980, as we're soon unifying the UIKit-side and ASDK-side of collection view layout.
