### ISSUE TITLE
[ASViewController] Regression causing layout issues when presenting a portrait-only view controller while in landscape

### ISSUE THREAD

**Issue by GitGadd** [facebook/AsyncDisplayKit#2213]
Presenting a portrait-only view controller while in landscape causes incorrect frames for both the presented and the presenting view controller.

It seems the view controllers are being laid out in the orientation/bounds of the other view controller, causing the portrait view controller to be laid out in landscape and vice versa.

This regression was introduced sometime after 1.9.6.

Attaching videos of presenting in 1.9.81 (the bug) as well as 1.9.6 as reference for the expected behavior. Also attaching a demo project reproducing the issue.

Steps to reproduce:
1. Add a rotatable view controller as the root view controller of the window
~~~~
 func supportedInterfaceOrientations() -> UIInterfaceOrientationMask { return .All } 
~~~~
2. Rotate the device to landscape
3. Present a portrait-only view controller over the root view controller
~~~~ 
func supportedInterfaceOrientations() -> UIInterfaceOrientationMask { return [.Portrait] }
 ~~~~

Expected: The presented view controller slides up from the portrait bottom of the device (home button). When dismissed, it slides towards the physical bottom of the device (left or right edge of the screen, depending on home button positioning)

Result: The presented view controller has an incorrect (landscape) frame with the window showing behind it due to not covering the entire screen. When dismissed, the presented view controller also has an incorrect (portrait) frame.

[ASRotatedPresentation.zip](https://github.com/facebook/AsyncDisplayKit/files/461654/ASRotatedPresentation.zip)

[ASDKRotationVideos.zip](https://github.com/facebook/AsyncDisplayKit/files/461658/ASDKRotationVideos.zip)

**Comment by GitGadd** [comment]
Confirmed fixed on master! That's great news, thank you. I'll make sure to test on master before posting future issues.

**Comment by hannahmbanana** [comment]
@GitGadd: no worries! I will use your examples to add unit tests to prevent future regressions. 

FYI - there have been a few breaking API changes on master so far that are [listed here](http://asyncdisplaykit.org/docs/upgrading.html)

**Comment by GitGadd** [comment]
This just happened to me again while building against master.

It only happens in a very specific case where I am overlaying the presenting view controller's node with two nodes at the same time.

The layout spec of the presenting ASViewController's node:

~~~~
override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
		var mainSpec:ASLayoutSpec = ASCenterLayoutSpec(centeringOptions: .XY, sizingOptions: [], child: collectionNode)
		mainSpec = ASOverlayLayoutSpec(child: mainSpec, overlay: ASOverlayLayoutSpec(child: arrangementPresentationNode, overlay: soundSettingsPresentationNode))
		
		let arrangementButtonSpec = ASStackLayoutSpec(direction: .horizontal, spacing: 0, justifyContent: .end, alignItems: .center, children: [
			arrangementButton, ASLayoutSpec.fixedSpacer(AXTheme.smallMargin)
			])
		return ASOverlayLayoutSpec(child: mainSpec, overlay: arrangementButtonSpec)
	}
~~~~

The layout spec of the 'soundSettingsPresentationNode'
~~~~
ASInsetLayoutSpec(insets: contentInset, child: ASCenterLayoutSpec(centeringOptions: .XY, sizingOptions: .minimumY, child: presentedNode))
~~~~

The layout spec of the 'arrangementPresentationNode'
~~~~
ASInsetLayoutSpec(insets: UIEdgeInsets.zero, child: presentedNode)
~~~~
