### ISSUE TITLE
Problem try custom transition animation use pop

### ISSUE THREAD

**Issue by smalllixin** [facebook/AsyncDisplayKit#2219]
I'm trying to use POP animation work with the latest AsyncDisplayKit (2.0 beta).
So enable automaticallyManagesSubnodes and override animateLayoutTransition: . And write the animation their.
I found things goes correct if use [UIView animationWithDuration:]. But the POP animation will get a unexpected flash. 
The example upload to https://github.com/smalllixin/aspop_transition
Hope get help. Thanks in advance.

**Comment by hannahmbanana** [comment]
@smalllixin: Does the pop not happen if `.automaticallyManagesSubnodes = NO`?

**Comment by smalllixin** [comment]
Hi @hannahmbanana . Thanks for your replying.
I record a video show the problem. The flying block directly appear to the final position on frame.
https://youtu.be/ceiJaMA3T8g 

Besides, preferredFrameSize is deprecated. Should I replace with node.size(ASLayoutableSize) ?

**Comment by ArEnSc** [comment]
@smalllixin I believe that flashing animation is a pop bug, I have seen it many times before

**Comment by hannahmbanana** [comment]
Closing this for now, if you have more info, please reply back!
