### ISSUE TITLE
[ASTableView] Crash. Attempt to manually add subnode to node with automaticallyManagesSubnodes=YES

### ISSUE THREAD

**Issue by mikhailmulyar** [facebook/AsyncDisplayKit#2222]
Just got this crash after updating to latest version. "addSubnode" is called from  -[_ASDisplayView willMoveToSuperview:] line 130. I do not use anywhere  addSubnode in my code.

**Comment by hannahmbanana** [comment]
@mikhailmulyar: thanks for catching this!  @maicki has created PR #2224 to fix this.

**Comment by mikhailmulyar** [comment]
Latest version seems to be fixed
