### ISSUE TITLE
[ASTableNode] separator style

### ISSUE THREAD

**Issue by GreatLiyi** [facebook/AsyncDisplayKit#2225]
I want to get rid of the separate of ASTableNode just like UITableView 's UITableViewCellSeparatorStyleNone,How to do

**Comment by hannahmbanana** [comment]
@GreatLiyi - have you tried `myTableNode.tableView.separatorStyle = UITableViewCellSeparatorStyleNone`?

Make sure to set this in `didLoad` (on the main thread), rather than in `init:` (background thread). For more on subclassing nodes, read:

http://asyncdisplaykit.org/docs/subclassing.html

**Comment by hannahmbanana** [comment]
Looks like this issue was resolved, if not, let me know.

**Comment by GreatLiyi** [comment]
Thanks! It works.

**Comment by GreatLiyi** [comment]
Thancks! It works.@hannahmbanana
