### ISSUE TITLE
Crash in -[ASDealloc2MainObject retain]

### ISSUE THREAD

**Issue by GitGadd** [facebook/AsyncDisplayKit#2229]
After updating to master, I'm getting a crash in -[ASDealloc2MainObject Retain] every time I reload a certain screen. The object being deallocated is a subclass of ASDisplayNode written in Swift with nothing special going on. I'm not doing any manual retains/releases.

The exception is 'EXC_BREAKPOINT' and the line being hit is

```
_OBJC_SUPPORTED_INLINE_REFCNT_WITH_DEALLOC2MAIN
```

Attaching a screenshot of the trace, though it is unfortunately very short and uninformative.

Device is running the latest beta of iOS 10 as of now, which is 10.0.1 (14A403).
Using Xcode Version 8.0 (8A218a) (=the GM)

I would love to help in any way I can, but I have way too little knowledge of how ASDK manages references to even begin investigating. Any help is greatly appreciated as I cannot revert to using the stable 1.9.x version because of another bug that was fixed in the 2.x betas.

![screen shot 2016-09-12 at 16 57 16](https://cloud.githubusercontent.com/assets/3338062/18440775/adc35014-790a-11e6-9da0-a6eb3a3d6a0a.png)

**Comment by hannahmbanana** [comment]
@GitGadd: thanks including all of the relevant details here! @Adlai-Holler is currently working to isolate and resolve the underlying cause of the issue. We don't yet have a 100% easy repro case, so it would be awesome if we could see some of your code. I'll send you a message on Slack. 

@Adlai-Holler @appleguy

**Comment by khashish** [comment]
FWIW, this issue happens on the ASDKgram example when scrolling down then up quickly
