### ISSUE TITLE
ASVideoNode does not implement the designated initializer of its super class -> Crash

### ISSUE THREAD

**Issue by skensell** [facebook/AsyncDisplayKit#2230]
I have an `ASVideoNode` subclass which calls the designated initializer of its super class `ASNetworkImageNode`.  This is important because I use a different imageCache and downloader.  The problem, however, is that it crashes because `ASVideoNode` implements important stuff in its implicit designated initializer `init`. Namely, not having this line:  

```
 _periodicTimeObserverTimescale = 10000;
```

Will make the VideoNode crash.
I could make a PR for it, but I don't have tons of time. I may eventually.

**Comment by Adlai-Holler** [comment]
@skensell good point! PR opened.
