### ISSUE TITLE
ASButton in ASControl eat all touch event for it's area

### ISSUE THREAD

**Issue by IvanChan** [facebook/AsyncDisplayKit#2234]
I have a ASButton as a subview of ASControl.

I have a TouchUpInside event for ASControl
And ASButton has no event , or hidden, or userInteraction = NO,

but I got no event-callback for ASControll when touch in area of ASButton.

**Comment by hannahmbanana** [comment]
@IvanChan: The ASButtonNode has userInteraction = NO, correct?

**Comment by IvanChan** [comment]
I ran my test code again, here is the case.

ASButton *myBtn = [ASButton new];
[myBtn setAttributeTitle: forState: **Normal** ]
[myBtn setAttributeTitle: forState: **Disabled** ]

myBtn.enabled = NO;

Then, the button will eat the touch.


if I make it like this,  it works well~!
[myBtn setAttributeTitle: forState: **Normal** ]
[myBtn setAttributeTitle: forState: **Selected** ]

myBtn.selected = YES;
myBtn.enabled = NO;

Hidden & userInteraction works well, my bad

**Comment by hannahmbanana** [comment]
@IvanChan - It looks like this wasn't a bug after all? 

I'm going to assume this wasn't a bug and close the issue, however if it _is_ a bug, please re-open it. :smiley

**Comment by maicki** [comment]
@IvanChan Could you provide a small example project. Thank you!

**Comment by IvanChan** [comment]
[TestAS.zip](https://github.com/facebook/AsyncDisplayKit/files/833081/TestAS.zip)

@maicki

**Comment by maicki** [comment]
@IvanChan Can you try out: #3161 this should resolve your issue. Please let us know. Thanks!
