### ISSUE TITLE
[Question] Is there any way to make ASTextNode vertical center in a large rect?

### ISSUE THREAD

**Issue by IvanChan** [facebook/AsyncDisplayKit#2236]
I am not talking about layout spec here, just ASTextNode itself.

If I create a ASTextNode with font=12, frame ={0, 0, 100, 50}, it will looks like below
```
—— — — — — — — — — — —
|    Hello there !~   |
|                     |
|                     |
—— — — — — — — — — — —

expected:
—— — — — — — — — — — —
|                     |
|    Hello there !~   |
|                     |
—— — — — — — — — — — —
The text will always being draw in the first line. Is it possible to make it vertical center?

I have try paragraphStyle.alignment = center, no luck.

**Comment by remirobert** [comment]
Hello, 

This is how I handle that, with layout : 
So you can use a **ASCenterLayoutSpec**, it will do the job just fine !!

```objective-c
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {
    ASCenterLayoutSpec *centerLayout = [ASCenterLayoutSpec new];
    [centerLayout setChild:self.titleNode];
    centerLayout.centeringOptions = ASCenterLayoutSpecCenteringX | ASCenterLayoutSpecCenteringY;
    return centerLayout;
}
```

**Comment by IvanChan** [comment]
@remirobert I am not talking put ASTextNode inside a container, just ASTextNode itself. Thanks anyway.

And is it possible to put **ASCenterLayoutSpec** inside **StaticSpec**  which has a large rect for text node to achieve this?

**Comment by hannahmbanana** [comment]
@IvanChan: I don't believe it is possible to do this with ASTextNode itself. @remirobert's suggestion above, is the best suggestion. 

Yes, it is possible to put an `ASCenterLayoutSpec` inside an `ASStaticLayoutSpec`.

**Comment by hannahmbanana** [comment]
@IvanChan: Thanks for contributing to the community by asking this question! I'm going to close this issue since it looks like we have answered it, but feel free to reopen this issue if not.

**Comment by zubko** [comment]
It would be much easier if `ASTextNode` support vertical alignment without being contained into `ASCenterLayoutSpec`. Sometimes I'm not using `ASLayoutSpec` and doing old-school manual layout.
Hacking into `ASTextKitRenderer`'s `- (void)drawInContext:(CGContextRef)context bounds:(CGRect)bounds`, to switch all drawing to centered vertically, was as easy as changing
```
    [layoutManager drawBackgroundForGlyphRange:glyphRange atPoint:shadowInsetBounds.origin];
    [layoutManager drawGlyphsForGlyphRange:glyphRange atPoint:shadowInsetBounds.origin];
```
to:
```
    CGPoint drawOrigin = shadowInsetBounds.origin;
    drawOrigin.y += (shadowInsetBounds.size.height - _calculatedSize.height) / 2;
    [layoutManager drawBackgroundForGlyphRange:glyphRange atPoint:drawOrigin];
    [layoutManager drawGlyphsForGlyphRange:glyphRange atPoint:drawOrigin];
```
Of course maybe there are some corner cases which i'm not aware about, this is kind of a blind man change, not knowing much about framework's internals, but i need this in a super simple way for now and it works my app. 
If I fork and add `verticalAlignment` properties to `ASTextNode` and `ASTextKitRenderer` to change drawing origin in case if verticalAlignment isn't `top` (default one), any chance it will be merged into the framework? (Using my own fork can be a temporary solution, but on the long run it would be much better to link against mainstream AsyncDisplayKit).

**Comment by zubko** [comment]
Hacking was easy, but making it a configurable parameter considering AsyncDisplayKit's internals and multi-threading wasn't a breeze.
So for now it was easier for me just to wrap `ASTextNode` into a subclass of `ASDisplayNode` which forwards styling to `ASTextNode` and lays it out with different vertical alignment in mind.

**Comment by xtcel** [comment]
I use ASButtonNode, let text vertical center of background.

**Comment by ikousik** [comment]
Use **textContainerInset**

 textNode.textContainerInset = UIEdgeInsets(top: 4, left: 6, bottom: 4, right: 6)

**Comment by appleguy** [comment]
Use ASCenterLayoutSpec in the parent’s layoutSpecThatFits.

Please do come on over to texturegroup.org, as that’s where the active ASDK
repository has been for about 3 years now :)
