### ISSUE TITLE
ASCollectionView crashing after calling "reloadItemsAtIndexPaths"

### ISSUE THREAD

**Issue by CR34L** [facebook/AsyncDisplayKit#2237]
ASCollectionView crashes when changing items onto an collection and calling reloadItemsAtIndexPaths after that. 
Common use is to hide a loader node or a "load more comments node" and so on.

crash log: Assertion failure in -[_ASHierarchyChangeSet _validateUpdate]_ASHierarchyChangeSet.mm:457 
'NSInternalInconsistencyException', reason: 'Invalid number of items in section 3. The number of items after the update (0) must be equal to the number of items before the update (10) plus or minus the number of items inserted or deleted (0 inserted, 0 deleted).'

So if that is a wanted case what is the correct use of reloading a section if the section has been changed?

**Comment by aliasnoa** [comment]
I have having this problem too

**Comment by maicki** [comment]
@CR34L @aliasnoa Hey this usually means that your `ASCollectionView` is not in sync with the data source. It seems like you want to hide certain items, in other words you are removing items which where there before. In that case, replace `reloadItemsAtIndexPaths:` with `deleteItemsAtIndexPaths:`. Also consider using `performBatchUpdates:completion:` to batch multiple insertions, deletions.

I will close this issue fro now. Please reopen if you think this will not resolve your issue and would be great to provide a sample project that will illustrate the issue and we will take a look.

Thanks!

**Comment by CR34L** [comment]
Thats ok. I was able to track the crash reason:

If you call: reloadItemsAtIndexPaths the whole datasource is checked - and not only the itemcount in the desired section. So if another thread is changing the itemcount of an other section the app crashes.

///
