### ISSUE TITLE
Nice way to animate a layer (layerBacked view)?

### ISSUE THREAD

**Issue by MaximusMcCann** [facebook/AsyncDisplayKit#2239]
With UIView it's nice to be able to call `finalFrameForNode()`.  Is there something similar for CALayer?

Would like to avoid setting up `CABasicAnimation`s everywhere.

My attempts

``````
override func animateLayoutTransition(context: ASContextTransitioning) {
    UIView.animateWithDuration(3.0, delay: 0.5, options: .CurveEaseIn, animations: {
      self.titleLbl.frame = context.finalFrameForNode(self.titleLbl)
      self.titleLbl2.frame = context.finalFrameForNode(self.titleLbl2)
      self.titleLbl2.layer.frame = context.finalFrameForNode(self.titleLbl2)

      // Attempts...
      //      self.titleLbl2.layer.setNeedsLayout()
      //      self.titleLbl2.layer.setNeedsDisplay()
      //      self.titleLbl2.layer.position = CGPointMake(10, 10)
      //      print(self.titleLbl2.layer.animationForKey("position"))
      //      print(self.titleLbl2.layer.animationForKey("bounds"))
      //      print(self.titleLbl2.actionForLayer(self.titleLbl2.layer, forKey: "position"))

      }, completion: { (didComplete: Bool) in
        context.completeTransition(didComplete)
    })
  }```
``````

**Comment by MaximusMcCann** [comment]
Demo playground
[AsyncDisplayKitPlayground.zip](https://github.com/facebook/AsyncDisplayKit/files/470335/AsyncDisplayKitPlayground.zip)

**Comment by hannahmbanana** [comment]
@MaximusMcCann - Sorry for the delay on getting back to you. Have you tried our [layout transition API](http://asyncdisplaykit.org/docs/layout-transition-api.html)? It is very powerful and animates layer backed views, just as well as it does view-backed ones. It also requires very little code to try out if you are using layout specs. [basic example project](https://github.com/facebook/AsyncDisplayKit/tree/master/examples/ASDKLayoutTransition)

@maicki - could you share the link to your _awesome_ layout transition app? I didn't see it under your repositories.

**Comment by hannahmbanana** [comment]
@MaximusMcCann - Due length of time since this thread was active, I'm going to close it. If you have any updates, please feel free to re-open this issue or file a new one. We hope you've enjoyed the framework!
