### ISSUE TITLE
[ASVideoNode] No audio while phone in silent mode.

### ISSUE THREAD

**Issue by skensell** [facebook/AsyncDisplayKit#2246]
It took me _way_ longer than it should've to figure out why I wasn't hearing any audio from my `ASVideoNode`.  Turned out my phone was in vibrate mode.

Now, it may seem like bad UX to allow audio while in silent mode, but I think there are a lot of people like me who always keep their phones in vibrate/silent mode, and we've come to expect videos to play sound when you tap a play button.  You can check and most other apps do ignore the silent mode of the device when an explicitly user-initiated action starts the audio.

Any plans to implement this feature?

B.T.W. Love this library! Thanks a ton.

**Comment by hannahmbanana** [comment]
@skensell: We don't have any plans to implement this feature, but we'd be happy to evaluate a pull request. I'd suggest chatting with the ASVideoNode experts in the #asvideonode channel of our ASDK Slack (#1582) to get feedback on the idea.

**Comment by hannahmbanana** [comment]
@skensell: I'm going to close this issue since we don't have plans to support this, but if you or anyone would like to implement this, we'd welcome a PR! :)
