### ISSUE TITLE
Is it at all possible to animate an ASScrollView height given layout transitions of subnodes?

### ISSUE THREAD

**Issue by renegare** [facebook/AsyncDisplayKit#2254]
Hey,  I have a subnode within ASScrollView. I'm using Layout Transitions to trigger off the following animation:

```
    override func animateLayoutTransition(context: ASContextTransitioning) {
        
        let final = context.finalFrameForNode(self.contentContainer)
        let initial = context.initialFrameForNode(self.contentContainer)
        
        if self.detailVisible == true {
            self.contentContainer.frame = initial
            self.someContent.alpha = 0
            UIView.animateWithDuration(4, animations: {
                self.contentContainer.frame = final
                self.someContent.alpha = 1
                self.setNeedsLayout()
                }, completion: {
                    finished in
                    context.completeTransition(true)
            })
        } else {
            self.contentContainer.frame = initial
            self.someContent.alpha = 1
            UIView.animateWithDuration(4, animations: {
                self.contentContainer.frame = final
                self.someContent.alpha = 0
                self.setNeedsLayout()
                }, completion: {
                    finished in
                    context.completeTransition(true)
            })
        }
    }
```

Now the animation on the actual subnodes ```contentContainer``` and ```someContent``` works as expected with a duration of ```4s```.

However siblings in the parent ASScrollView and the view itself fails to animate and simply snaps because I'm using ```setNeedsLayout```.

I'm sure its something simple / obvious I am missing but this is not clear and the example in the docs is simplistic example that does not require a subnodes parent/siblings to animate.

I'm using v1.9.9

Best,

M.

**Comment by levi** [comment]
@renegare try using layoutIfNeeded, which will cause a layout pass in the same animation block. There is likely a case that it won't do anything, so mark you scroll view needing layout before calling it.

**Comment by renegare** [comment]
Hey @levi, Thanks for getting back. Here is a simplified version of my code:

```        
        UIView.animate(withDuration: 4, animations: {
            self.contentContainer.frame.size = final.size
            self.view.layoutIfNeeded()
            print("super node \(self.supernode!.view)")
            self.supernode!.view.setNeedsLayout()
            }, completion: {
                context.completeTransition($0)
        })
```

(Note: I'm aware that explicitly unwrapping is bad; but I want to get the animation working and understand why it did not work in the first place 🙃)

Have I applied correctly what you described? And if so ... then it does not work 🙈

The super node above is the ASScrollView which wraps the UIView. Also the method layoutIfNeeded, only exists on UIView and not on a node. 

Whats your thoughts on this?

**Comment by renegare** [comment]
there is another ticket which is most likely a duplicate of this one #2228 

Whilst I am still experiencing this issue, best we close this and use the other ticket to track progress?

(feel free to open)
