### ISSUE TITLE
[ASTableView] Moving cells with the reorder control does not work

### ISSUE THREAD

**Issue by skensell** [facebook/AsyncDisplayKit#2258]
Trying to move cells around with the reorder control by calling `[self.tableNode.view setEditing:YES];` in `viewDidLoad` and then implementing

    - (BOOL)tableView:(UITableView *)tableView canMoveRowAtIndexPath:(NSIndexPath *)indexPath {
        return YES;
    }
    - (void)tableView:(UITableView *)tableView moveRowAtIndexPath:(NSIndexPath *)sourceIndexPath toIndexPath:(NSIndexPath *)destinationIndexPath {
        // modify backing data
    }
does not seem to work. I'm following <a href="https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/TableView_iPhone/ManageReorderRow/ManageReorderRow.html">Apple's docs</a>.

The row animates to the correct location, however, if I scroll down and scroll back up again the rows are back in their original locations.  I guess this is because `ASTableView`'s internal `ASDataController` has not been notified of the move.

The only workaround I have is calling reload on every cell between the source and destination (which results in a flash and is quite ugly).

**Comment by hannahmbanana** [comment]
@skensell: I believe support for this was just added to master (#2221). Does this work for you?

**Comment by skensell** [comment]
Wow, nice timing!  As far as I can tell, I can only integrate master if I'm using Carthage, is that right?  I'm using Cocoapods and it seems 1.9.90 is the latest there. Does that include the change?

**Comment by skensell** [comment]
Also, is there an E.T.A. for 2.0? Just curious :)

**Comment by hannahmbanana** [comment]
@skensell: I'm not sure about Carthage, but you are correct that 1.9.90 is the latest on Cocoapods which does not include this recent change.  

2.0 is coming soon...within the next few weeks. :)
