### ISSUE TITLE
ASTableView starts with cells at height of 0; stalls the device if there are 1000s of cells

### ISSUE THREAD

**Issue by ProjectDent** [facebook/AsyncDisplayKit#2262]
I have a table view that has thousands of unique cells, so I've decided to use AsyncDisplayKit to display them.

A problem I'm running into right now is that when the table view is first loaded, all cells seemingly start at height 0, and thus it gets the information for every cell there is. With just 20 cells, this is fine, but with thousands it just stalls the app.

Is there a way that I can make cells take their correct size initially, so that it doesn't attempt loading in any cell that doesn't need to be onscreen?

**Comment by ArEnSc** [comment]
Can you provide some code ?

**Comment by hannahmbanana** [comment]
Closing this for now, please reply back if you have more info!
