### ISSUE TITLE
When is the best time to auto-scroll ASTableView when CellNode's height has changed?

### ISSUE THREAD

**Issue by Gocy015** [facebook/AsyncDisplayKit#2273]
Hi ,
I have a custom ASCellNode , which has a ASNetworkImageNode in it , and this networkImageNode will only be displayed when a button inside the cellNode is tapped.

My problem is , when the image download is complete ,and i call `[self setNeedsLayout]` in the cellNode to layout the networkImageNode , and then i notify the ASTableView to auto-scroll by overriding the cellNode's `-(void)layoutDidFinish` , i'm doing this because after the image is downloaded and displayed , the height of the current cellNode will change and the tableView may need to scroll in order to see the whole cell .But it seems that when i try to scroll **the last few indexes** of the tableView ,  it doesn't work . After a few tests , **It seems that the tableView's contentSize isn't correct** , it's hard to describe , may be if you can see [my code](https://github.com/Gocy015/POICharacterList) and find out where i did wrong ?

Thank you very much !

**Comment by hannahmbanana** [comment]
@Gocy015 - what version of AsyncDisplayKit are you using? If you [update to 2.0](http://asyncdisplaykit.org/docs/adoption-guide-2-0-beta1.html), and move everything to the table node, this may resolve itself? @Adlai-Holler

**Comment by Gocy015** [comment]
I've update [my project](https://github.com/Gocy015/POICharacterList) to the latest version of ASDK (2.0 beta-1) ,and the auto - scrolling is still incorrect.
My call stack looks like this:

<pre>
<code>
#0 -[ViewController cellNode:didExpand:] 
#1 -[InfoCellNode layoutDidFinish]
#2:: -[ASDisplayNode __layout]()
#3:: -[_ASDisplayLayer layoutSublayers]() 

</code>
</pre>

and inside `[cellNode: didExpand:]` , i try to scroll the tableNode:

<pre>
<code>
if (expand) { 
        NSIndexPath *idx = [_tableNode indexPathForNode:cellNode];
        CGRect rect = [_tableNode rectForRowAtIndexPath:idx];
        if (!CGRectContainsRect(self.tableNode.bounds, rect)) {
            NSLog(@"Scroll %lu",idx.row);
            [self.tableNode invalidateCalculatedLayout];

            [self.tableNode scrollToRowAtIndexPath:idx atScrollPosition:UITableViewScrollPositionBottom animated:YES];
        }
    }
</code>
</pre>

It's not working when the last few indexPaths expand.

**Comment by EviluS** [comment]
@Gocy015 Calling `scrollToRowAtIndexPath:atScrollPosition:animated` right after the `invalidateCalculatedLayout` will have no effect because the cells will probably have the same layout. 
Try wrapping the `scrollToRowAtIndexPath:` call inside a `dispatch_async(dispatch_get_main_queue()`

```
// workaround
dispatch_async(dispatch_get_main_queue(), ^{
    [self.tableNode scrollToRowAtIndexPath:idx atScrollPosition:UITableViewScrollPositionBottom animated:YES];
});
```

**Comment by Gocy015** [comment]
@EviluS  Thx ! This solved my problem ,but i'm still a little confused .
I dug into the source code to see what` [ASDisplayNode invalidateCalculatedLayout]` does , and it simply marked the current layout dirty.

I wonder why wrapping `scrollToRoAtIndexPath:` inside an async method **GUARANTEES** that the calculation of the new layout will happen before the scrolling method ,since ASDK do background calculations only when the current runloop is "waiting" , what if the current loop is so busy ,that ASDK cannot finish all the calculations between "before waiting" and "after waiting", and in the next loop, when the scrolling method is called , will the scrolling still behave correctly  ?

**Comment by EviluS** [comment]
@Gocy015 This is definitely not a 100% guarantee. The cleanest way is to know when all the layout is done and then call the `scrollToRoAtIndexPath:` method.

**Comment by Gocy015** [comment]
@EviluS , So the best way is to subclass ASTableNode ,override `layoutDidFinish` , and then try to scroll the table node ?

**Comment by EviluS** [comment]
@Gocy015 You can try it :)

**Comment by Gocy015** [comment]
@EviluS  , Ok, i'll give it a shot , thx for the help 👍  :)
