### ISSUE TITLE
asyncdisplaykit.org can't be opened

### ISSUE THREAD

**Issue by liuxuan30** [facebook/AsyncDisplayKit#2276]
asyncdisplaykit.org can't be opened

**Comment by jeffdav** [comment]
http://www.downforeveryoneorjustme.com/asyncdisplaykit.org

**Comment by maicki** [comment]
Hey, https://asyncdisplaykit.org is loading fine for me. Will close this issue.

**Comment by liuxuan30** [comment]
Jesus then why can't I open it?
