### ISSUE TITLE
When ASTableView calls the method of insertRowsAtIndexPaths with UITableViewRowAnimationNone, but it does have animation

### ISSUE THREAD

**Issue by tuyuan2012** [facebook/AsyncDisplayKit#2277]
When ASTableView calls the method of insertRowsAtIndexPaths with UITableViewRowAnimationNone, but it does have animation.
Thanks!

**Comment by cincas** [comment]
had a same problem, is there any solution for this?

Cheers

**Comment by eddydas** [comment]
Not exactly sure what "animation" you are referring to. But try 
```
[UIView setAnimationEnabled:NO];
// Do your reload
[UIView setAnimationEnabled:YES]; 
```

**Comment by Adlai-Holler** [comment]
Hi @tuyuan2012 This is part of `UITableView` behavior. With `ASTableView` you can avoid the animation like this:

```objectivec
[tableView beginUpdates];
[tableView insertRowsAtIndexPaths:indexPaths];
[tableView endUpdatesAnimated:NO completion:nil];
```

Please let us know whether that works for you!
