### ISSUE TITLE
[ASDisplayNode] Using intrinsically sized UIViews in an ASDisplayNode subclass

### ISSUE THREAD

**Issue by ide** [facebook/AsyncDisplayKit#229]
I'm writing a custom ASDisplayNode that contains a UIButton (my reason for this being that system UIButtons come with a bunch of established behaviors Apple has implemented) and am trying to figure out when to measure the UIButton with `sizeToFit` or `sizeThatFits:`.

The tricky part is that the UIButton's intrinsic size affects my ASDisplayNode's calculated size, so the UIButton needs to be measured before `calculateSizeThatFits:` returns. Right now I'm just sizing the UIButton in `calculateSizeThatFits:`, but from the ASDK source it looks like that code could be running on a background queue. In practice it seems to be fine but I'd prefer to use UIKit mostly on the main queue.

Is there a good approach here? One solution I can think of is to make `calculateSizeThatFits:` take a callback so that it can dispatch to the main queue, measure UIKit components, and then invoke the callback. (This would also allow node subclasses to call `measure:` on several subnodes for parallel layout.) The other solution would be to call `measure:` on the root node from the main queue but it kind of sucks that one UIView would make the whole node hierarchy layout on the main thread.

**Comment by ide** [comment]
I ran into a trickier case just now trying to add a UITextView to the custom ASDisplayNode (it's a form component, so it doesn't look like I can use ASTextNode). The UITextView needs to be dynamically sized since its height grows as text is entered and that needs to happen on the main thread. Looking at Paper, the post composer is sort of similar to what I want. Maybe I'm not seeing something...

**Comment by andyscott** [comment]
I'm also very interested in a growing UITextView in a custom ASDisplayNode.

**Comment by secretiverhyme** [comment]
I'm actually not sure off the top of my head whether there's an elegant way to handle intrinsically-sized UIViews in node hierarchies — synchronous nodes are mostly useful for things like wrapping UIScrollView or UITextView, where UIKit's functionality is desirable but layout can still be handled asynchronously.  @appleguy might have some thoughts here.

**Comment by secretiverhyme** [comment]
> it's a form component, so it doesn't look like I can use ASTextNode

&

> I'm also very interested in a growing UITextView in a custom ASDisplayNode.

[ASEditableTextNode](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASEditableTextNode.h) is now available in master if you'd like to try it, and will be included in the upcoming AsyncDisplayKit 1.2 release.  =]

**Comment by ide** [comment]
That's great to see. I'll have to give it a try some time and I like that it supports placeholders. I really like that ASDK fills in a lot of things you want in a typical app that are missing from UIKit (ASNetworkImage, text views with placeholders, etc).

**Comment by appleguy** [comment]
@ide @andyscott - I am internally tracking improvements to synchronous node wrapping that will call sizeToFit: on these elements automatically. I am also investigating if it makes sense to integrate with preferredFrameSize. Note that with the ASLayoutSpec system, there are a variety of new options for controlling layout. 

Please open a new issue if you have any layout related problems or feature requests. Overall, I would not expect a perfectly smooth experience integrating synchronous elements with non-trivial layout that you cannot express in terms of layoutSpecs.
