### ISSUE TITLE
How to create mask on [ASDisplayNode]

### ISSUE THREAD

**Issue by Jauzee** [facebook/AsyncDisplayKit#2297]
I try to create `ASCellNode` with blurred mask on left side as on screenshot below:

<details> 
  <summary>

Screenshot </summary>

![iphone 7](https://cloud.githubusercontent.com/assets/7991920/18815369/546bbc36-8337-11e6-97b9-72afbba9d771.png)
</details>
### What I'm currently do

I created `ASCellNode` with hierarchy:
– `ContainerNode`
    – `BackgroundImageNode`
    – `BlurredImageNode`
    – `ASTextNode` (title)

I am used same image for each node, but for blurred one enabled `imageModificationBlock` which blurs image and crops it by `UIBerzierPath` that i passed in.

``` Swift
blurredImageNode.imageModificationBlock = { image in
    var blurredImage: UIImage!

    UIGraphicsBeginImageContextWithOptions(image.size, false, UIScreen.main.scale)

    let blurRegionPath = UIBezierPath()
    blurRegionPath.move(to: CGPoint(x: 0, y: height))
    blurRegionPath.addLine(to: CGPoint(x: bottomPoint, y: height))
    blurRegionPath.addLine(to: CGPoint(x: topPoint, y: 0))
    blurRegionPath.addLine(to: CGPoint(x: 0, y: 0))
    blurRegionPath.addLine(to: CGPoint(x: 0, y: height))
    blurRegionPath.close()
    blurRegionPath.addClip()
    self.maskLayer.path = blurRegionPath.cgPath

    image.draw(in: drawRect)
    blurredImage = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()

    blurredImage = blurredImage.applyBlurWithRadius(blurRadius: 20,
                                                         tintColor: UIColor.tintLight.withAlphaComponent(0.3),
                                                         saturationDeltaFactor: 1,
                                                         maskImage: nil)

    return blurredImage ?? image
}
```
### Problem

The problem is that blurred image node overlays background image node with colors of blur.
### What I'm tried else

I'm tried to create mask `CAShapeLayer` and assign it to `BlurredImageNode` and then refresh it's path in `layout()`.

**Comment by garrettmoon** [comment]
@Jauzee can you provide a screenshot of the problem?

**Comment by hannahmbanana** [comment]
Closing this for now, if you have more info, please reply back!
