### ISSUE TITLE
ASTableView not selecting nodes

### ISSUE THREAD

**Issue by ulfie22** [facebook/AsyncDisplayKit#230]
Is there some magic to getting an ASTableView to select rows? 

I added

```
-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    NSLog(@"didSelectRowAtIndexPath %@", indexPath);
}
```

to the Kittens example in ViewController.m (which is the asyncDelegate) and it is never called when tapping on rows.

**Comment by kylehickinson** [comment]
I believe in the Kittens example they have the delegate method `tableView:shouldHighlightRowForIndexPath` (I think thats the name of it) returning `NO`, which disables selection.

**Comment by ulfie22** [comment]
That's it. Thanks, Kyle!!
