### ISSUE TITLE
XCode8 PINCache beta3 issue

### ISSUE THREAD

**Issue by ikbenben** [facebook/AsyncDisplayKit#2300]
Hi there,

We have been migrating our project to XCode 8 and had it an issue about incompatible point type. The issue that was reported here at https://github.com/facebook/AsyncDisplayKit/issues/2010.

As a result, I updated our Podfile to build the latest version of AsyncDisplayKit. This was fine until I went to upload our app to TestFlight. Apple won't allow us to upload it due to PINCache info.plist using an invalid version number (3.0.1-beta). Looking at the AsyncDisplayKit podspec, it is specifying this version :

    pin.dependency 'PINRemoteImage/iOS', '>= 3.0.0-beta.2'

I'm now kind of circular dependancy which I'm not sure how to resolve. I'm unable to rollback to a previous version of AsyncDisplayKit as it won't build on XCode8 and I'm unable to submit an app with the latest version of AsyncDisplayKit

Any suggestions on how I can resolve this?

thanks
Ben

**Comment by garrettmoon** [comment]
Hey @ikbenben this is fixed in CocoaPods 1.0. You can see workarounds here: https://github.com/CocoaPods/CocoaPods/issues/4421

**Comment by ikbenben** [comment]
@garrettmoon thanks for the quick response. So first things. upgrading cocoapods. I've run the gem install with --pre flag and it says cocoapods 1.1.0 rc2 is installed but when i run pod --version i get 0.39.0 . This seems strange 

    MacBook-Pro:fitmo brooney$ gem install cocoapods --pre
    Successfully installed cocoapods-1.1.0.rc.2
    1 gem installed
    MacBook-Pro:fitmo brooney$ pod --version
    0.39.0

Next, looking at the bug you referenced. Do I need to put in the post_install hook still or does Cocoapod 1.0 does this automatically now?

Again, thanks for the feedback

**Comment by ikbenben** [comment]
@garrettmoon great. any thoughts as to why version is 0.39.0 after saying 1.1.0 has been installed?

**Comment by ikbenben** [comment]
@garrettmoon never mind.. looks like i have it sorted. had 2 versions installed. running gem uninstall cocoapods allowed me to uninstall the 0.39 version (for anyone else who comes across this)
