### ISSUE TITLE
[ASTableView] how to only load one screen CellNode rather than all 2000 CellNode。

### ISSUE THREAD

**Issue by leece** [facebook/AsyncDisplayKit#2301]
now my ASTableView numberOfRowsInSection = 2000, and all data on my memory had prepare all ready, then the astableview load all 2000 cellnode into memory block my userinterface(may be main thread may be not, but screen is block),  i need wait for many seconds (4s or 5s or more....) to show my ASTableView on screen. if i use UIKIT uitableview, is only load one screen cell, so show fast!  Is there have method to only load one screen or two screen cell for show quikly for my ASTableview?

**Comment by garrettmoon** [comment]
Have you tried using `tableView:nodeBlockForRowAtIndexPath:` instead of `tableView:nodeForRowAtIndexPath:`? That allows ASDK to avoid loading nodes on the main thread.

**Comment by leece** [comment]
@garrettmoon  thanks your reply. I had tried using `tableView:nodeBlockForRowAtIndexPath:` but nothing improved to my situation.   
like this : 
`ableView:nodeBlockForRowAtIndexPath: `
`{`
     `.....`
    `return` ^{
        `NSLog(@"%@", (indexPath.row));`
        `return [[ASCellNode` alloc] init];
   `}`
`}`
I still see the result 1. block my screen 2. Console print "1""2""3"......'2000" waiting for 5,6seconds,   3. then the ASTableView is showing.   

Even  I  try the "examples" "ASViewController",  i modify "[DetailRootNode.m](https://github.com/facebook/AsyncDisplayKit/blob/master/examples/ASViewController/Sample/DetailRootNode.m)"  `- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section`  return 2000,   then when i press any of first level cell @"abstract", @"animals", @"business", @"cats", @"city",.... into  second level ViewController ,  i always  waiting long time to load  beacause  the ASTableview loaded all cell into memory.   like the matter  i  see   Console print "1""2""3"......'2000".    and i  indeed sure  the "slow" reason is that.   

So did any method or suggest  to improved my situation。 I really want to improved my app from AS and I already used AS in many part of my app, but this situation I can't resolved, I am so puzzled.

I even google many old issue like [#540](https://github.com/facebook/AsyncDisplayKit/issues/540)
, in this issue, the "question titile" is so same as my Q, is only the title,  the 
discuss not concentrated on the load all 2000 cell and enter slow slow slow.    so  not have a  clear resolution.   

can help me even more.

**Comment by maicki** [comment]
@leece Instead of loading all 2000 rows at once try to batch fetch them. Please look into the batch fetching documentation: http://asyncdisplaykit.org/docs/batch-fetching-api.html as well as the `ASDKGram` documentation

**Comment by xquezme** [comment]
> AsyncDisplayKit does not use cell reuse, for a number of specific reasons, one side effect of this is that it eliminates the large class of bugs associated with cell reuse.

**Comment by maicki** [comment]
I will close this issue, please reopen if you think further discussion is needed.
