### ISSUE TITLE
[ASImageNode] wrong image representation after kPOPViewFrame animation

### ISSUE THREAD

**Issue by iwheelbuy** [facebook/AsyncDisplayKit#2302]
We want to make a small photo viewer using ASDK. But we are unable to correctly animate frame of `ASImageNode`. Btw, all `UIImageView` and `ASImageNode` have contentMode **AspectFill**

- AsyncDisplayKit **679f68e16942f87a19d15674ddfb7c35536728c1**
- pop **1.0.9**
- Swift **3**

We take **image**(`UIImage`) and **frame**(`CGRect`) from some **imageView**(`UIImageView`) that we want to go fullscreen. Top left corner is our **imageView**.

<img width="300" alt="2016-09-27 0 29 44" src="https://cloud.githubusercontent.com/assets/2524584/18845019/1abc73a4-844a-11e6-8c7f-a8966b54b111.png">

Then we create **imageNode**(`ASImageNode`) with our **image**+**frame**, add as a subnode to `UIWindow` above our current **imageView** and animate its frame using `pop`+`kPOPViewFrame`. After animation we expect to see...

<img width="300" alt="2016-09-27 0 29 02" src="https://cloud.githubusercontent.com/assets/2524584/18845114/8cdef79a-844a-11e6-8efe-dd706901fc28.png">

...but we see..

<img width="300" alt="2016-09-27 0 29 21" src="https://cloud.githubusercontent.com/assets/2524584/18845266/3f9dceb0-844b-11e6-87ab-1c23b321509e.png">

Any suggestions?
To reproduce just paste the code below on some button action

```
func touch() {
    
    guard let window1 = UIApplication.shared.delegate?.window else { return }
    guard let window = window1 else { return }
    
    // lets imagine we have some image on our UIWindow
    let originalImageView = UIImageView(image:UIImage(named:"swift.jpg"))
    guard let image = originalImageView.image else { return }
    originalImageView.contentMode = .scaleAspectFill
    originalImageView.clipsToBounds = true
    originalImageView.frame = CGRect(origin:CGPoint.init(x:0, y:0), size:CGSize(width:200,height:100))
    window.addSubview(originalImageView)
    
    // full screen show calculations
    let frame = window.frame
    let imageRatio = image.size.width / image.size.height
    let frameRatio = frame.size.width / frame.size.height
    let finalSize = imageRatio > frameRatio ? CGSize(width:frame.size.width, height:frame.size.width * imageRatio) : CGSize(width:frame.size.height / imageRatio, height:frame.size.height)
    
    // original image fades away
    originalImageView.alpha = 0.0
    
    // show fake image fullscreen instead of original image
    let ASDK = true // ASDK or UIKit?
    switch ASDK {
    case true:
        let newImageNode = ASImageNode()
        newImageNode.image = image
        newImageNode.contentMode = .scaleAspectFill
        newImageNode.isLayerBacked = false // btw, when TRUE node is not visible...
        newImageNode.clipsToBounds = true
        newImageNode.frame = originalImageView.frame
        window.addSubnode(newImageNode)
        let animation = POPBasicAnimation(propertyNamed:kPOPViewFrame)
        animation?.duration = 1
        animation?.toValue = NSValue.init(cgRect:CGRect(origin:CGPoint.init(x:0, y:0), size:finalSize))
        animation?.completionBlock = { [weak newImageNode] _ in
            newImageNode?.removeFromSupernode()
        }
        newImageNode.pop_add(animation, forKey:"viewImageLogoShow")
    case false:
        let newImageView = UIImageView(image:image)
        newImageView.contentMode = .scaleAspectFill
        newImageView.clipsToBounds = true
        newImageView.frame = originalImageView.frame
        window.addSubview(newImageView)
        let animation = POPBasicAnimation(propertyNamed:kPOPViewFrame)
        animation?.duration = 1
        animation?.toValue = NSValue.init(cgRect:CGRect(origin:CGPoint.init(x:0, y:0), size:finalSize))
        animation?.completionBlock = { [weak newImageView] _ in
            newImageView?.removeFromSuperview()
        }
        newImageView.pop_add(animation, forKey:"viewImageLogoShow")
    }
}
```

**Comment by garrettmoon** [comment]
@iwheelbuy I believe this has to do with the fact that the image is being rendered once for the initial target size and contentMode. Can you try using the forcedSize property on ASImageNode? I think if you set it to the final size *before* it's rendered for the first time, it should work.
