### ISSUE TITLE
Emojis getting cutoff in ASTextNode

### ISSUE THREAD

**Issue by xigtk** [facebook/AsyncDisplayKit#2304]
I seem to be having a problem with ASTextNodes cutting off emojis

Using the Swift demo, Xcode 8, iOS 10 and replacing
`node.text = String(format: "[%ld.%ld] says hello!", (indexPath as NSIndexPath).section, (indexPath as NSIndexPath).row)`
with
`node.text = String(format: "😗🙄🤑🤓😶", (indexPath as NSIndexPath).section, (indexPath as NSIndexPath).row)`

I am consistently getting the following result:
![screen shot 2016-09-26 at 12 28 19 pm](https://cloud.githubusercontent.com/assets/22456984/18849055/fcbf7784-83e5-11e6-97aa-95afb66619ce.png)

However, if I add text the string as well, the text does not get cutoff:
![screen shot 2016-09-26 at 12 41 26 pm](https://cloud.githubusercontent.com/assets/22456984/18849209/bba1d606-83e6-11e6-8db4-681c9b5cb6a5.png)

**Comment by garrettmoon** [comment]
I checked and this doesn't appear to be an issue with UILabel :( So it's likely that usedRectForTextContainer is returning this.

@xigtk Can you use `textContainerInset` (in ASTextNode+Beta.h) to work around this?

**Comment by garrettmoon** [comment]
@xigtk can you provide a demo project showing this?

**Comment by xigtk** [comment]
I'm using the Swift demo project in the examples.

https://github.com/xigtk/AsyncDisplayKit/commit/361468f43674ddd5d0df5a0af71c4b280e3144f0

**Comment by xigtk** [comment]
This seems to be a problem with the apple emoji font that is selected by NSTextStorage. 

If I remove the attributes in updateAttributedText in ASTextCellNode
`_textNode.attributedText = [[NSAttributedString alloc] initWithString:self.text attributes:nil];`
The problem no longer occurs.

Or, in a more general way, I can replace the "AppleColorEmojiUI" font with the "Apple Color Emoji" font in the textStorage.
https://github.com/xigtk/AsyncDisplayKit/commit/ab5be023641db872b6e93f5a2eee85517f6cb028

**Comment by master-nevi** [comment]
This project demonstrates the bug in the ". AppleColorEmojiUI" font in general and is what we're going to send to Apple.

https://github.com/master-nevi/ClippedEmoji

It appears that when an attributed string contains ONLY the . AppleColorEmojiUI font, the height iOS reports for the attributed string (using `[NSAttributedString boundingRectWithSize:options:context:]`) is too short, and therefore the bounding box generated for the string will clip the bottom. 

As soon as a string segment with a taller font is added, done by appending any non-emoji character, the bounding box calculation is corrected.

**Comment by master-nevi** [comment]
https://openradar.appspot.com/radar?id=4998540401049600

**Comment by garrettmoon** [comment]
Awesome, thank you both!

**Comment by halvini** [comment]
So how do we avoid this bug in JSQ?

**Comment by master-nevi** [comment]
Apple has acknowledged the bug, however could not recommend a workaround at this time. 😞

**Comment by garrettmoon** [comment]
Going to close this for now since it appears to be an Apple bug :(

**Comment by master-nevi** [comment]
Apple notified me that this has been fixed in iOS 10.2 beta.

**Comment by danielrhodes** [comment]
Ran into this today.

As an update, [Apple has fixed this issue in 10.2](https://openradar.appspot.com/radar?id=4998540401049600#ag9zfm9wZW5yYWRhci1ocmRyFAsSB0NvbW1lbnQYgICAyPX0_AkM), but if you are still looking for a quick workaround I recommend the following:

Detect an Emoji-only string using [this Stackoverflow post](http://stackoverflow.com/a/39425959/1218761).
(Note: Before you copy and paste, on every iOS release, the [unicode ranges](http://unicode.org/emoji/charts/full-emoji-list.html) which detect emojis will change as they add more, so it's a rather blunt method of detection.).

Then just add a single space character to the string. The height should then be detected properly as the correct font is used.
