### ISSUE TITLE
possible UISplitViewController issues

### ISSUE THREAD

**Issue by frankenthumbs** [facebook/AsyncDisplayKit#2308]
hey ya'll,

on iPad, with 1.9.90, I have a UISplitViewController and the master view is an ASViewController with a ASCollectionNode as its underlying node. 
What i'm observing happening is the collection cells get measured with the full dimensions of the UISplitViewController but never get re-measured with the dimensions of the master view.

I've made a sample project with what i believe is the same issue i am seeing on my project. https://github.com/frankenthumbs/ASDK-pagerNode/blob/master/Podfile

any insight into why this might be happening?

Thank you in advance,
Joon Son

**Comment by hannahmbanana** [comment]
@frankenthumbs: do you know if this an issue on `master` as well?

**Comment by frankenthumbs** [comment]
@hannahmbanana nice~~ its not happening on master! that leap to 2.0 will be fun :D

**Comment by hannahmbanana** [comment]
@frankenthumbs: let us know if you have any other issues with UISplitViewController. @rcancro
