### ISSUE TITLE
ASCollectionView and ASTableView ignore working range if asyncDelegate is not set

### ISSUE THREAD

**Issue by ide** [facebook/AsyncDisplayKit#231]
ASCollectionView recalculates the visible nodes and working range when `willDisplayCell:`/`didEndDisplayingCell:` are called on the UICollectionViewDelegate, but this delegate is set to the proxy only when asyncDelegate is set. It looks like ASTableView has the same problem too.

**Comment by secretiverhyme** [comment]
Thanks for the report — this is a bug we haven't gotten around to fixing yet.

**Comment by secretiverhyme** [comment]
@cxa and @aleclarson put up a couple of pull requests to fix this (#150, #151) but it looks like I never had a chance to manually merge them after the ASRangeController rewrite landed.  @rnystrom, want to grab this one?
