### ISSUE TITLE
[ASLayoutable] flexShrink is not available

### ISSUE THREAD

**Issue by iwheelbuy** [facebook/AsyncDisplayKit#2314]
Hello.  I believe I'm using ASDK 2.0 (version 37d9d401b30334548f1b4375394f6ddf832377a4 atm)

I'm stuck because I can't use flexShrink and preferredFrameSize is deprecated. Any ideas what am I doing wrong?
![img_2016-09-28 22 51 17](https://cloud.githubusercontent.com/assets/2524584/18921531/515a78d0-85cf-11e6-9d62-852ab8986c2b.jpg)
![img_2016-09-28 22 51 26](https://cloud.githubusercontent.com/assets/2524584/18921533/51c11ffe-85cf-11e6-9829-917db3d853bb.jpg)

**Comment by maicki** [comment]
@iwheelbuy Instead of `preferredFrameSize` use `node.style.width` or `node.style.height` and for `flexShrink` use `spacer.style.flexShrink = 1`
