### ISSUE TITLE
ASNetworkImageNode how to use cache

### ISSUE THREAD

**Issue by fanly** [facebook/AsyncDisplayKit#232]

**Comment by secretiverhyme** [comment]
Check out [ASImageProtocols.h](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Details/ASImageProtocols.h), in particular the ASImageCacheProtocol definition and docblock.  You can use ASNetworkImageNode and ASMultiplexImageNode without a cache — just pass nil — but if you require a custom cacheing strategy or a disk cache, this is the way to go.

**Comment by sharanshodhan** [comment]
Was anyone able to solve this? Please help! I am trying to do something very similar.

**Comment by secretiverhyme** [comment]
@sharanshodhan, do you need help implementing a cache, or just using an existing one?  If the former, you might want to read up on [NSCache](http://nshipster.com/nscache/) and [NSURLCache](http://nshipster.com/nsurlcache/).  Otherwise, it's very easy:  you only need to wire up one method (`-fetchCachedImageWithURL:callbackQueue:completion:`) to query your existing "get this object from cache" interface.

Note that NSURLSession, which is used by ASBasicImageDownloader, already uses a shared NSURLCache by default; you don't need to implement ASImageCacheProtocol unless you need custom behaviour.

**Comment by ide** [comment]
I published an ASImageCacheProtocol and ASImageDownloaderProtocol implementation called [WebASDKImageManager](https://github.com/ide/WebASDKImageManager) that uses [SDWebImage](https://github.com/rs/SDWebImage) as the underlying implementation. SDWebImage is designed for both downloading and caching images so I believe it's a good fit.

You can get it through CocoaPods with `pod 'WebASDKImageManager', '~> 1.0'` and use it like:
```objc
ASNetworkImageNode *node = [[ASNetworkImageNode alloc] initWithWebImage];
// Use the node as usual
node.URL = imageURL;
```

If you want to use another downloader/cache, you could look at how WebASDKImageManager is implemented (it's small) and modify it to use FastImageCache, NSURLCache, Haneke, TMCache, etc.

**Comment by sharanshodhan** [comment]
Thanks a lot @ide ! It worked well for me. One question I had was that does it also clear the cache from memory if it exceeds some limit?

**Comment by ide** [comment]
I believe it clears the cache when there's a memory warning. You could ask the developers of SDWebImage or browse their code to make sure.

**Comment by fanly** [comment]
Thanks a lot @ide ! It worked well for me!

**Comment by tettoffensive** [comment]
Thanks @ide! This is awesome

**Comment by psk239** [comment]
I found that I preferred a category implementation on `SDWebImageManager`. Here is the code to share! 

####  `SDWebImageManager+AsyncDisplayKit.h`
```objective-c
#import <SDWebImage/UIImageView+WebCache.h>
#import <AsyncDisplayKit/AsyncDisplayKit.h>

/**
 * Heavily borrows from https://github.com/ide/WebASDKImageManager
 * Allows SDWebImage to be used as the cache for AsyncDisplayKit
 */
@interface SDWebImageManager (AsyncDisplayKit) <ASImageCacheProtocol, ASImageDownloaderProtocol>

@end
```

####  `SDWebImageManager+AsyncDisplayKit.m`
```objective-c
#import "SDWebImageManager+AsyncDisplayKit.h"

@implementation SDWebImageManager (AsyncDisplayKit)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#pragma mark - ASImageCacheProtocol
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

- (void)cachedImageWithURL:(NSURL *)URL callbackQueue:(dispatch_queue_t)callbackQueue completion:(void (^)(CGImageRef imageFromCache))completion {
    
    if (!URL) {
        completion(nil);
        return;
    }
    
    NSString *cacheKey = [self cacheKeyForURL:URL];
    [self.imageCache queryDiskCacheForKey:cacheKey done:^(UIImage *image, SDImageCacheType cacheType) {
        dispatch_async(callbackQueue ?: dispatch_get_main_queue(), ^{
            completion(image.CGImage);
        });
    }];
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#pragma mark - ASImageDownloaderProtocol
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

- (id)downloadImageWithURL:(NSURL *)URL callbackQueue:(dispatch_queue_t)callbackQueue downloadProgress:(void (^)(CGFloat progress))downloadProgressBlock completion:(void (^)(CGImageRef image, NSError *error))completion {
    
    if (!URL) {
        NSString *domain = [NSBundle bundleForClass:[self class]].bundleIdentifier;
        NSString *description = @"The URL of the image to download is unspecified";
        completion(nil, [NSError errorWithDomain:domain code:0 userInfo:@{NSLocalizedDescriptionKey: description}]);
        return nil;
    }
    
    return [self downloadImageWithURL:URL options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
        if (downloadProgressBlock) {
            dispatch_async(callbackQueue ?: dispatch_get_main_queue(), ^{
                downloadProgressBlock((CGFloat)receivedSize / expectedSize);
            });
        }
    } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
        if (!finished) {
            return;
        }
        
        dispatch_async(callbackQueue ?: dispatch_get_main_queue(), ^{
            completion(image.CGImage, error);
        });
    }];
}

- (void)cancelImageDownloadForIdentifier:(id)downloadIdentifier {
    
    if (!downloadIdentifier) {
        return;
    }
    
    NSAssert([[downloadIdentifier class] conformsToProtocol:@protocol(SDWebImageOperation)], @"Unexpected image download identifier");
    id<SDWebImageOperation> downloadOperation = downloadIdentifier;
    [downloadOperation cancel];
}


@end
```
