### ISSUE TITLE
Counterintuitive requirement for ASTableView to use calculated node heights

### ISSUE THREAD

**Issue by nolanw** [facebook/AsyncDisplayKit#233]
Hello! I found it counterintuitive that `ASTableView` requires its `asyncDelegate` to be set in order for each cell to take on its node's height. If you never set `asyncDelegate`, the rows just take on their default `UITableView` heights. I guess this requirement could be documented somewhere, but ideally the table view would Just Work even if I never muck with its delegate.

The issue stems from the table view only setting `super.delegate` in its `asyncDelegate` setter, and even then only in the non-`nil` branch. One fix might be to initialize `super.delegate` to be `self`, and to set `super.delegate = self` whenever `asyncDelegate` is `nil`.

**Comment by aleclarson** [comment]
:+1:

**Comment by secretiverhyme** [comment]
Tracking in #231.  Thanks!  =]

**Comment by nolanw** [comment]
Oh, my apologies! I'll take a closer look for duplicates next time.

**Comment by secretiverhyme** [comment]
No worries!  Fix landed ^_^
