### ISSUE TITLE
setContentOffset of ASCollectionView  cause the cells to re fade

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#2331]
I have created a custom container, which uses ASCollectionView with UIViewController as cells.

![fade](https://cloud.githubusercontent.com/assets/3206748/19015871/9329fa46-8819-11e6-99b4-b16302fd7a5e.gif)

but problem is when I tap on title sliders to switch viewControllers via changing `contentOffset` of `ASCollecionView`, layoutSubViews gets called on `ASCollectionView` and all cell relayouted and re fade again, which is unwanted behavior. but when I swipe manually, this fading won't happen.

how can I encounter this problem?

**Comment by hannahmbanana** [comment]
@hashemp206: could you put together a sample project showing this?

**Comment by hannahmbanana** [comment]
Closing this for now, please reply if you have more info!

**Comment by hashemp206** [comment]
sorry for delay, as soon as I could take time to redevelop the component, I will post it here and open the issue
