### ISSUE TITLE
ASTableViewStressTest [ObjC] doesn't support [[ASTableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain asyncDataFetching:YES]

### ISSUE THREAD

**Issue by weichencoder** [facebook/AsyncDisplayKit#2341]
![2016-10-04 20 54 13](https://cloud.githubusercontent.com/assets/5242184/19074870/f4cceabc-8a74-11e6-96bb-a62af22562fc.png)

**Comment by maicki** [comment]
@weichencoder Hey, our API is currently in flux so it can be that the extra samples are not updated yet. For now just remove the `asyncDataFetching:` parameter from the initializer. We will update all examples soon though.

cc @hannahmbanana
