### ISSUE TITLE
Supplementary node layout issue

### ISSUE THREAD

**Issue by MarvinNazari** [facebook/AsyncDisplayKit#2345]
Supplementary node dosent stretch to full width, but when i use the same cell for a row it works
[here is a sample project](https://github.com/MarvinNazari/ASDKHeaderIssue)

![screen shot 2016-10-05 at 14 37 41](https://cloud.githubusercontent.com/assets/926772/19113419/c823aefc-8b09-11e6-9309-815c341a564b.jpg)

**Comment by hannahmbanana** [comment]
@MarvinNazari: is this a regression when updating to master? We're currently making some [changes to the Layout API](http://asyncdisplaykit.org/docs/layout2-conversion-guide.html) so it would be helpful to know if this is a regression or not. 

cc @maicki

**Comment by MarvinNazari** [comment]
@hannahmbanana:  just tested on 1.9.90, i solved the problem by using  `constrainedSizeForSupplementaryNodeOfKind` inside `ASCollectionViewLayoutInspecting`

**Comment by hannahmbanana** [comment]
@MarvinNazari: Glad to hear the issue is resolved. Thank you for reporting back!
