### ISSUE TITLE
[ASViewController] Subclassing in Swift.

### ISSUE THREAD

**Issue by mikhailmulyar** [facebook/AsyncDisplayKit#2355]
When you subclass ASViewController in Swift and want to add some custom initialiser to it, you need to override initializer 'init(coder:) because it is marked as 'required' for NSCoding in Swift. However in ASViewController it is marked as 'unavailable', so it many situations compiler finishes with error if you try to override it. And in that case you will get either of both errors.
'required' initializer 'init(coder:)' must be provided by subclass of 'ASViewController'
or
cannot override 'init' which has been marked unavailable
I should say that at the moment second error is not always happens when you override 'init(coder:)', but sometimes it does and it is really annoying when it does. For me it looks like compiler bug that it do not gives error all the time, but only under certain circumstances, i think it should do that all the time according to errors description.
So if it will give this error all the time than ASViewController will become really unusable in Swift, without the ability to subclass it properly.

**Comment by hannahmbanana** [comment]
Anyone else run into this?

**Comment by ArEnSc** [comment]
@mikhailmulyar I am using 1.9.9.0

this is how I subclassed it

```swift
class ViewController: ASViewController  {
    
    var tableNode:ASTableNode?
    override init(node: ASDisplayNode) {
        super.init(node: node)
        
        self.tableNode = ASTableNode.init()
        
        if let tableNode = self.tableNode {
            tableNode.frame = UIScreen.mainScreen().bounds
            tableNode.dataSource = self
            tableNode.delegate = self
            self.node.addSubnode(tableNode)
        }
    }

}
    
    required init?(coder aDecoder: NSCoder) {
        super.init(node: ASDisplayNode.init())
    }

```

**Comment by mikhailmulyar** [comment]
Yes, as a general solution it works.  However my situation happens sometimes. But on other thought it seems more like a compiler error. It should not require override for unavailable methods. I've checked it in pure swift code and if required method marked as unavailable compiler do not ask to implement it in subclass. So i will try to find more suitable case for it and fill radar for this issue later.
