### ISSUE TITLE
[Cocoapods] Problem with use_frameworks! modulemap & double definitions

### ISSUE THREAD

**Issue by weibel** [facebook/AsyncDisplayKit#2359]
We have a very large ObjC project where we have started using Swift for new parts. Hence it would be a good time to convert our Cocoapods installation to use_frameworks! We use Cocoapods 1.0.1

For most of our pods this has been fairly easy, but we have spent a long time with an issue on AsyncDisplayKit where Clang would complain about duplicate interfaces, protocols and properties

> [redacted]/Pods/AsyncDisplayKit/AsyncDisplayKit/ASCollectionView.h:38:1: Duplicate interface definition for class 'ASCollectionView'
> 
> [redacted]/Pods/AsyncDisplayKit/AsyncDisplayKit/ASCollectionView.h:49:57: Property has a previous declaration

After a lot of digging I concluded that the contents of the umbrella header (AsyncDisplayKit-umbrella.h) which Cocoapods autogenerates is included twice. It is included by the AsyncDisplayKit.modulemap which looks like 

```
framework module AsyncDisplayKit {
  umbrella header "AsyncDisplayKit-umbrella.h"

  export *
  module * { export * }
}
```

I have managed to hack my way through it by basically removing the contents of the modulemap in the  Podfile post_install step.

```
framework module AsyncDisplayKit {

}
```

I include ASKD with `#import <AsyncDisplayKit/AsyncDisplayKit.h>`. Writing `@include AsyncDisplayKit` has the same effect. 

I would like to know if anyone else have had this issue. Please note that we don't use ASDK for any of the Swift parts of the project hence it has not been included in our bridging header or anything like that.

**Comment by garrettmoon** [comment]
@hannahmbanana are you interested in taking this one on?

**Comment by hannahmbanana** [comment]
@weibel - I'm having difficulties reproducing this. Would it be possible to provide us with a sample project that demonstrates this issue?
