### ISSUE TITLE
reloadRows result in wrong scroll position sometimes

### ISSUE THREAD

**Issue by eddydas** [facebook/AsyncDisplayKit#2360]
1) Open ASDKgram example project on either 1.9 or 2.0 branch
2) Add this to PhotoFeedNodeController.m:

```
- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent *)event {
  NSUInteger n = [_photoFeed numberOfItemsInFeed];
  NSMutableArray *a = [NSMutableArray new];
  for (NSUInteger i = 0; i < n; i++){
    [a addObject:[NSIndexPath indexPathForRow:i inSection:0]];
  }
  [_tableNode.view reloadRowsAtIndexPaths:a withRowAnimation:UITableViewRowAnimationNone];
}
```

3) Launch ASDKgram on either device or simulator
4) Scroll to a random post and shake the device

Expected: the scroll position doesn't change
Actual : the scroll position changes.

Additional info: 
a) Doesn't happen when I'm on top of the scroll view. Happens to some scroll position but not some other scroll position.

b) When you shake a second time afterwards, usually it doesn't change the scroll position. But if you set .automaticallyAdjustsContentOffset=YES, then shaking a second time (or even a third time) will result in further shift of the scroll position.

**Comment by eddydas** [comment]
The more I look at it, it seems that whenever we try to reload a row that is partially visible on the top edge, it would trigger a slip in contentOffset.

i.e. Using the below code, whenever you make the 4th row (rowIdx = 3) partially visible, shaking your device would cause the table view to shift.
```
- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent *)event {
 [_tableNode.view reloadRowsAtIndexPaths:@[[NSIndexPath indexPathForRow:3 inSection:0]] withRowAnimation:UITableViewRowAnimationNone];
}
```


The same behaviour isn't present in UIKit's version of ASDKgram:
```
- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent *)event {
  NSMutableArray *a = [NSMutableArray new];
  for (NSUInteger i = 3; i < 4; i++){
    [a addObject:[NSIndexPath indexPathForRow:i inSection:0]];
  }
  [_tableView beginUpdates];
  [_tableView deleteRowsAtIndexPaths:a withRowAnimation:UITableViewRowAnimationNone];
  [_tableView insertRowsAtIndexPaths:a withRowAnimation:UITableViewRowAnimationNone];
  [_tableView endUpdates];
}
```

**Comment by maicki** [comment]
@eddydas Hey, can you try this again with current master? Is this issue still present. I cannot see any content offset drop. What I can see is that the cell is reanimating because it's reloading, but that's expected based on the example. Thanks!

**Comment by garrettmoon** [comment]
@eddydas going to close this for now, if you have more info please reply and we'll open it back up!
