### ISSUE TITLE
[ASControlNode] ASControlNodeEventValueChanged doesn't exist

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#2361]
I have created a custom `ASControlNode` which acts like `UIStepper`. so when I tap on minus or plus button, I want to trigger `UIControlEventValueChanged`. but it seems `ASControlNodeEvent` doesn't have such event! 
why? and how can I handle such scenario?

<img width="118" alt="screen shot 2016-10-07 at 3 13 03 pm" src="https://cloud.githubusercontent.com/assets/3206748/19188730/9a72fa4c-8ca0-11e6-9f3b-3b12d4e474cc.png">

**Comment by hannahmbanana** [comment]
@hashemp206: Interesting. I wonder if it wasn't included because ASDK doesn't provide any controls that would use it (sliders or switch).

Your use case seems like something that would be very reasonable to support. We would love to accept a PR if you could implement this.

**Comment by hashemp206** [comment]
@hannahmbanana ok I need to take time, if encounter any issue I will post here
