### ISSUE TITLE
Is their anyway i can Define ASCellNode layout in a nib file?

### ISSUE THREAD

**Issue by NSAryan12** [facebook/AsyncDisplayKit#2379]
Hi i am trying to define a layout for a ASCellNode in a ASTableView but i want to define the layout of ASCellNode in a nib file is it possible....?

**Comment by Adlai-Holler** [comment]
@NSAryan12 Hi, thanks for posting! Sorry to say, nibs and AsyncDisplayKit don't play well together. Here's a link with more info about AsyncDisplayKit and interface builder: http://asyncdisplaykit.org/docs/faq.html#asyncdisplaykit-does-not-support-uikit-auto-layout-or-interfacebuilder
