### ISSUE TITLE
ASNetworkImageNode _delegate is not weak reference.

### ISSUE THREAD

**Issue by pjs7678** [facebook/AsyncDisplayKit#239]
Once I set ASNetworkImageNode's delegate, unless I unset ASNetworkImageNode's delete to nil, it will not be deallocated.

**Comment by rnystrom** [comment]
Hmm. It looks like we are [declaring](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASNetworkImageNode.h#L46) the delegate as an `atomic, weak` property, but are actually backing it with a simple [ivar](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASNetworkImageNode.mm#L23) and manually [locking/unlocking](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASNetworkImageNode.mm#L114-124). 

We also might have a retain cycle passing `self` in as the imageNode in [this](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASNetworkImageNode.mm#L216) completion block.

Let me dive into this issue a little more and come up with a fix. Really great find here!
