### ISSUE TITLE
ASDKgram example crashes when scrolling up and down

### ISSUE THREAD

**Issue by khashish** [facebook/AsyncDisplayKit#2396]
Testing ASDKgram example on IPhone 6 simulator iOS 10 if you scroll up and down quickly, the sample will crash with the following log:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Node should always be marked invisible before deallocating. Node: ASTextNode: 0x7fa18d496e00; text = "View all 8 comments"

It can be easily reproduced by scrolling down quickly and then scrolling up quickly.

This happens with AsyncDisplayKit version 2.0-beta.1

**Comment by hannahmbanana** [comment]
@khashish - thank you for reporting this and including all of the relevant details. I am able to reproduce this bug following your directions on both iOS 9.3 & 10. I put together that example, so I'll investigate it. :)

**Comment by hannahmbanana** [comment]
@maicki pointed out that it doesn't crash if you disable `.shouldRasterizeDescendants` it works. 

![image](https://cloud.githubusercontent.com/assets/3419380/19421810/736d75c4-93be-11e6-9a1c-16add840e532.png)

**Comment by Adlai-Holler** [comment]
cc #2205

**Comment by maicki** [comment]
Without looking into it deeper today I guess that the propagation of interface states is not working correctly if a node has `. shouldRasterizeDescendants` enabled.

**Comment by Adlai-Holler** [comment]
Hi @khashish as Michael mentioned, this is an issue where nodes with `shouldRasterizeDescendants=YES` do not get interface state updates under some conditions. The issue is tracked at #2205, so stay tuned for a fix!
