### ISSUE TITLE
Memory leak on ASCollectionView

### ISSUE THREAD

**Issue by raphaeloliveira** [facebook/AsyncDisplayKit#2400]
Hi guys, I might be wrong but I think there is a memory leak on `layoutInspector` property of `ASCollectionView.mm`.

Even though the property `@property (nonatomic, weak) id<ASCollectionViewLayoutInspecting> layoutInspector;` is declared as weak, it's backed up by a non weak iVar:

```
@interface ASCollectionView () <ASRangeControllerDataSource, ASRangeControllerDelegate, ASCollectionDataControllerSource, ASCellNodeInteractionDelegate, ASDelegateProxyInterceptor, ASBatchFetchingScrollView, ASDataControllerEnvironmentDelegate, ASCALayerExtendedDelegate> {
  ASCollectionViewProxy *_proxyDataSource;
  ASCollectionViewProxy *_proxyDelegate;
  
  id<ASCollectionViewLayoutInspecting> _layoutInspector;   <---- strong iVar
...
```
so on the overridden setter we are actually retaining it:
```
- (void)setLayoutInspector:(id<ASCollectionViewLayoutInspecting>)layoutInspector
{
  _layoutInspector = layoutInspector;  <--- this is retaining a supposed to be weak variable
  
  _layoutInspectorFlags.layoutInspectorDidChangeCollectionViewDataSource = [_layoutInspector respondsToSelector:@selector(didChangeCollectionViewDataSource:)];
  _layoutInspectorFlags.layoutInspectorDidChangeCollectionViewDelegate = [_layoutInspector respondsToSelector:@selector(didChangeCollectionViewDelegate:)];
}
```
This was causing a retain cycle where my view controller was setting itself as the layout inspector and never being deallocated.
```
self.collectionNode.view.layoutInspector = self;
```

After changing the iVar declaration to `__weak id<ASCollectionViewLayoutInspecting> _layoutInspector;` the problem disappeared.

If that's a valid issue, maybe there are other places with the same issue as well?

**Comment by hannahmbanana** [comment]
@raphaeloliveira: thank you for the very detailed investigation & writeup!
