### ISSUE TITLE
ASButtonNode stays highlighted

### ISSUE THREAD

**Issue by modLX4** [facebook/AsyncDisplayKit#2401]
Button Node stays highlighted on touch up inside. I have used **Blocks** to handle button action.

Code in controller for tableView:(ASTableView *)tableView nodeBlockForRowAtIndexPath:(NSIndexPath *)indexPath

<img width="1020" alt="cd" src="https://cloud.githubusercontent.com/assets/12533332/19433071/db1580e0-947c-11e6-9a04-27198ead699d.png">

![untitled-2](https://cloud.githubusercontent.com/assets/12533332/19433010/9ce39b72-947c-11e6-909f-376c19dd73ef.jpg)

_Version Info :
- AsyncDisplayKit (1.9.90):
  - AsyncDisplayKit/PINRemoteImage (= 1.9.90)
- AsyncDisplayKit/ASDealloc2MainObject (1.9.90)
- AsyncDisplayKit/Core (1.9.90):
  - AsyncDisplayKit/ASDealloc2MainObject
- AsyncDisplayKit/PINRemoteImage (1.9.90):
  - AsyncDisplayKit/Core
  - PINRemoteImage/iOS (>= 3.0.0-beta.3)_

**Comment by ArEnSc** [comment]
Can get a sample project for this ?

**Comment by modLX4** [comment]
Sorry for the delay. Here it is.

[ASDKTest.zip](https://github.com/facebook/AsyncDisplayKit/files/549922/ASDKTest.zip)

**Comment by EviluS** [comment]
@modLX4 There is something strange happening when presenting the segue immediately. The `setHighlighted:` method is called once with `YES` and after that with `NO` but the state is not updated. 

The workaround is to wrap the `[self handleFeedCellButtonAction:modelAtIndexPath buttonIndex:buttonIndex];` in `dispatch_after` block with 0.01 delay (I tested it with that delay). Not the pretties solution but .. it works.

**Comment by maicki** [comment]
@modLX4 Agree with @EviluS ... I just looked into it briefly and the highlighted state get's updated property on the `ASButtonNode` just the display is not happening.

For now the workaround from @EviluS makes sense.

**Comment by modLX4** [comment]
dispatch_after() does the job but bad UX.

**Comment by modLX4** [comment]
Temporary Solution 

- (void)handleFeedCellButtonAction:(TempModel*)model buttonIndex:(NSUInteger)buttonIndex{
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 0.1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
        
        [self performSegueWithIdentifier:@"toDetailView" sender:NULL];
        
    });
    
}

**Comment by appleguy** [comment]
@modLX4 AsyncDisplayKit isn't compatible with Interface Builder, so take care with how you're creating ASDK elements to make sure they are never specified in .xib files.

Thanks for posting about this and bringing the details to help arrive at a workaround - let us know if you find any other issues that look like they could be framework problems!  Happy to help in Slack too :)

**Comment by skensell** [comment]
I have this same issue: my `ASButtonNode` does not finish redisplaying before I push a new view controller onto my nav stack.  The result is that when you navigate back, the `ASButtonNode` is in some permanent in-between state (the background image updated but not the title text).

I could only resolve this by setting `displaysAsynchronously` to `NO` which is pretty unfortunate.  I don't like the temporary `dispatch_after` solution, and I hope you guys consider reopening this issue.

I don't have time to make a demo project, but all you would need is an `ASButtonNode` with different background image and attributed title colors for the states Highlighted and Normal, and when the button is tapped a new VC should be pushed on the navigation stack.
