### ISSUE TITLE
[Layout Transition API] ASContextTransitioning will complete transitions for other active contexts other than itself

### ISSUE THREAD

**Issue by master-nevi** [facebook/AsyncDisplayKit#2407]
Layout API doesn't keep track of the changes between concurrent layout transitions.

 Scenario:
- Node-A is added with a transition-animation-A and a duration of 3 seconds.
- 1 second later (during transition animation-A) Node-B is removed with a transition-animation-B duration 3 seconds again.
- Transition-animation-A completes so `[ASContextTransitioning completeTransition:]` is called. Because node-B was removed, `[ASContextTransitioning completeTransition:]` will remove node-B in  transition-animation-A's transition completion. This interrupts the transition-animation-B and makes for some odd looking transitions.

To work around this problem I'm queuing up the calls to `[ASContextTransitioning completeTransition:]` in a suspended NSOperationQueue if there are pending animated transitions. After the last animation is completed, I'll unsuspened the operation queue, which allows all the calls to  `[ASContextTransitioning completeTransition:]` to complete.

Let me know if you need a sample to go with this issue.

**Comment by maicki** [comment]
I moved this issue to 2.1 as it's on our roadmap to dive a bit deeper into the layout transition anyway after 2.0.

**Comment by master-nevi** [comment]
Awesome! While you're at it, I found that this limitation was a huge bummer in my mind as well:

> @"Can't start a transition when one of the supernodes is performing one."

https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L845

**Comment by Adlai-Holler** [comment]
This is an important issue – now that it's linked to the overarching task of improving the layout transition system, let's move all discussion over to that ticket.
