### ISSUE TITLE
The CIs are Failing Spuriously

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#2418]
Currently we are running two CIs, Travis (public) and Jenkins (on a Pinterest server).

They both use Xcode 8, and they are both [failing](https://travis-ci.org/facebook/AsyncDisplayKit/builds/168663807) [spuriously](https://travis-ci.org/facebook/AsyncDisplayKit/jobs/168392736). Relevant issues are https://github.com/travis-ci/travis-ci/issues/6422 and https://github.com/travis-ci/travis-ci/issues/6675 and https://github.com/travis-ci/travis-ci/issues/6251.

I think we should revert to Xcode 7 in .travis.yml and potentially disable Jenkins or update our build servers to support Xcode 7 as well.

@appleguy Are you willing to take this on?

**Comment by hannahmbanana** [comment]
They do support paid-tier access for open source repos, but the lowest tier is $500/mo.

**Comment by Adlai-Holler** [comment]
I'm satisfied with Jenkins for the time being.
