### ISSUE TITLE
EXC_BAD_ACCESS on ASCollectionView insertItemsAtIndexPaths:

### ISSUE THREAD

**Issue by aleclarson** [facebook/AsyncDisplayKit#242]
[ASFlowLayoutController.mm - line 45](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Details/ASFlowLayoutController.mm#L45)

Getting an `EXC_BAD_ACCESS` runtime error when `v.begin()` is called in the code linked above.

This occurs in a call to `[ASCollectionView insertItemsAtIndexPaths:]`.

Are there any obvious causes for behavior like this?

**Comment by aleclarson** [comment]
The `indexPath.row` equals `0` when the crash occurs.

**Comment by tanliboy** [comment]
It happened in the case we didn't have the section before inserting items. try to insert section before insert items may fix it

**Comment by aleclarson** [comment]
Yeah that's what I did (forgot to update this).

I've implemented `func numberOfSectionsInCollectionView (collectionView: UICollectionView!) -> Int` successfully before (without inserting any sections). I must've been using an earlier version when I did that. 

Maybe this was a regression? :sweat_smile:

**Comment by secretiverhyme** [comment]
@tanliboy, can you add an assertion / graceful failure here?

**Comment by secretiverhyme** [comment]
…whoops, wrong button!

**Comment by tanliboy** [comment]
Added in https://github.com/facebook/AsyncDisplayKit/pull/311

**Comment by aleclarson** [comment]
:+1:
