### ISSUE TITLE
Use __deprecated_msg Macro to Provide a Message from Compiler

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#2421]
Currently we use `__attribute__((deprecated))` which is nice because it's very broadly supported. But it doesn't allow for a deprecation message.

The `__deprecated_msg("Use performBatchUpdates:completion: instead.")` specifier is supported by enough compilers – I don't know the specifics but Xcode 7 and 8 for sure – and it might ease the transition significantly.

This would also replace our use of the `@deprecated` documentation comment specifier, which is not supported outside of Apple. I'm pretty sure that `__deprecated_msg` will show up in the documentation if you set it.

We could migrate piecemeal, having a series of diffs to add messages to chunks of deprecations at a time.

Thoughts @garrettmoon @maicki @appleguy ?

**Comment by maicki** [comment]
We should actually use the one with the comment and provide a comment as if you currently use asdk on a newly setup project you get warnings that no deprecation message is provided.

**Comment by hannahmbanana** [comment]
Done!
