### ISSUE TITLE
[UPDATE TO 1.9.91] - Fix for PINCache.h build error.

### ISSUE THREAD

**Issue by boai** [facebook/AsyncDisplayKit#2424]
Pod update no PINCache this library! Only Sending stats
       - AsyncDisplayKit, 1.9.90
       - PINRemoteImage, 3.0.0-beta.4
These two libraries, how do?

**Comment by albetjanuar** [comment]
I got the same error which is saying "PINCache/PINCache.h file not found".

**Comment by jeremiahgage** [comment]
I am also getting the error:

> /Pods/AsyncDisplayKit/AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m:30:9: 'PINCache/PINCache.h' file not found

**Comment by appleguy** [comment]
@boai @albetjanuar @jeremiahgage hey everyone - thank you for reporting this.  I sincerely apologize for the issue; there was a mistake in the podfile configuration that allowed the referenced version to drift, introducing an issue.

We will have a fix to this published tomorrow.  It's our #1 priority to resolve.

Feel free to coordinate live with us on Slack.  http://asyncdisplaykit.org/slack.html

**Comment by albetjanuar** [comment]
@appleguy can you suggest which version is without error via cocoapods?

**Comment by boai** [comment]
@albetjanuar the latest version!

**Comment by appleguy** [comment]
@albetjanuar you can point to branch releases/p6.13 for the most up to date version of the framework that doesn't have major API changes (but, a few).  Pinterest is now using releases/p6.14, which is effectively master branch (note the Buffer app, >1 million users, is also using the master branch).  We are preparing a 2.0 Cocoapod version for first-half December final bits.

However, running on the latest framework is not for everyone, and if 1.9.90 is working and you've run into this error - you can now update to 1.9.91.  It doesn't have any other changes except setting the podspec to a fixed version of PINRemoteImage, which it should have done (but was a one-character mistake in the ASDK .podspec config :( ).

1.9.91 is finished and the branch (same name) is available on Github.  You can point to that using :branch => in the Podfile.  The version is currently pushing to cocoapods as a public / current stable version; however this takes ~30 minutes, and it might hit a push failure, but I'll make sure it is working tomorrow.

**Comment by albetjanuar** [comment]
thanks @appleguy ! can't wait to integrate ADK to my project.

**Comment by garrettmoon** [comment]
As a workaround, you can specify the version of PINRemoteImage directly in your podfile:
`pod 'PINRemoteImage', '3.0.0-beta.3'`

**Comment by ay8s** [comment]
@albetjanuar Just a note theres a new PINRemoteImage beta with... 
`pod 'PINRemoteImage', '3.0.0-beta.4'`

**Comment by garrettmoon** [comment]
@ay8s that's actually the issue in this case, 1.9.90 hasn't been updated to the new beta-4 and beyond API.

**Comment by boai** [comment]
@garrettmoon new version?

**Comment by baby03201** [comment]
I have same issue few days ago, but solved with adding `pod 'PINRemoteImage', '3.0.0-beta.3'`.
now I've updated AysncDisplayKit to latest, 1.9.91, and the problem is solved.

Thanks! @appleguy

**Comment by appleguy** [comment]
Thanks everyone for your understanding.

Sadly we may have to do this again with a 1.9.92 because PINRemoteImage had the same issue, so as soon as PINCache has an updated release, 1.9.91's PINRemoteImage will again drift and pull in the new PINCache when it shouldn't :(.

We will deploy a public beta of 2.0 by this weekend.  Anyone interested in getting ahead of this will benefit a lot from updating to point to one of our release branches that we've shipped Pinterest with, as they're very close to master (e.g. releases/p6.14).
