### ISSUE TITLE
ASControlNode does not call actions in the same order as they were added

### ISSUE THREAD

**Issue by tamaskarai** [facebook/AsyncDisplayKit#2428]
Hi,

I recently discovered that the ASControlNode class stores the target actions pairs associated with an event in an NSSet structure. Iterating through a NSSet won't guarantee that the selectors will be called in the same order as they were added.
### Use case

I'd like to make sure to call an event handler that logs analytics before all other event handlers are called. UIControl stores the target action pairs in an NSArray, so it is possible to manipulate the order of event handlers.

If you agree with this then I'm happy to implement the changes needed to store target action pairs in an array rather then a set.
### How to test
1. Download example app: https://github.com/tamaskarai/AsyncDisplayKitTestApp
2. Run pod install
3. Run UI tests
4. Check tests: `testUIKitOrder` test will pass, the `testAsyncDisplayKitOrder` will fail, although the actions are added in the same order
### Versions

AsyncDisplayKit 1.9.91

Thanks,
Tamas

**Comment by Adlai-Holler** [comment]
@tamaskarai Thanks for a thorough, clean issue report! We'd be glad if you implemented this change, and ideally added a unit test to ASControlNode to ensure the behavior stays fixed.

Obviously it's important that the targets are not retained – our best bet may be to follow `UIControl`'s model and create e.g. [ASControlTargetAction](https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/UIKit.framework/UIControlTargetAction.h) objects.

**Comment by tamaskarai** [comment]
Hi @Adlai-Holler ,

Thank you for confirming this issue. I'll create a pull request and link this issue report once I'm ready with the implementation. Also, thanks for the implementation tips!

Tamas

**Comment by Adlai-Holler** [comment]
Closed in #2456.
