### ISSUE TITLE
[ASDisplayNode] Implementing deinit subclass crashes on dealloc in Swift 3

### ISSUE THREAD

**Issue by tomizimobile** [facebook/AsyncDisplayKit#2431]
Seems to be something in `[ASDealloc2MainObject retain]` that causes the issue.

Using abd80494c7ea5b0b470a8306fdc3089c40070fc1
[bt all.txt](https://github.com/facebook/AsyncDisplayKit/files/539751/bt.all.txt)

**Comment by Adlai-Holler** [comment]
@tomizimobile This is pretty serious! Is it possible that code inside your `deinit` implementation calls `retain` on self? Does the issue occur with a trivial or empty implementation of `deinit`?

**Comment by tomizimobile** [comment]
@Adlai-Holler The issue occurs with something as trivial as `print("deinit")` - although an empty implementation is ok

**Comment by Adlai-Holler** [comment]
@tomizimobile Yep just confirmed it. Sample project:

[NodeSwiftDeallocTest.zip](https://github.com/facebook/AsyncDisplayKit/files/539933/NodeSwiftDeallocTest.zip)

I can't investigate it immediately but cc #2223 @johnepinterest @appleguy for the time being.

**Comment by appleguy** [comment]
@Adlai-Holler I don't think we can address this for 2.0, but if you could run a quick test to see if it's possible to create a workaround for this, that would be helpful.

If you can't think of a workaround to try, punt to 2.1 and we will all be better off when we land #2223 :).  It feels a bit risky to take that diff for 2.0, but if you'd like to shoot for it, let's discuss in the next team meeting!

**Comment by Eke** [comment]
I have same problem with Swift 3

**Comment by appleguy** [comment]
@Adlai-Holler should be fixed by 2223, right?

**Comment by Adlai-Holler** [comment]
@appleguy Yep @tomizimobile could you check post-#2223 and let us know how it performs?

**Comment by tomizimobile** [comment]
@Adlai-Holler looks good to me
