### ISSUE TITLE
ASLayoutElement Naming Convention Thoughts

### ISSUE THREAD

**Issue by lappp9** [facebook/AsyncDisplayKit#2465]
In regards to the change from `ASLayoutable` to `ASLayoutElement`, I was thinking that the old name was actually more in line with Apple's naming conventions regarding protocols in the Swift standard library.  (I also thought it was more expressive but that could just be me.)

It seems the standard library protocols follow one of three patterns:
1) Hashable, Equatable, Comparable etc imply a conforming objects acts a certain way
2) CollectionType, IntegerType, BooleanType imply an object is in a certain family of types
3) FloatLiteralConvertible, ArrayLiteralConvertible etc imply an object can be converted to or from a certain type.

To me that this protocol falls into the -able category in that it describes objects that can act a certain way.

Of course, conforming to this convention may not be a priority for ASDK, but it seems like it might be nice for at least public facing protocols to be in line with Swifty stuff unless there was a reason not to.

Let me know what you guys think! Just figured I'd throw it out there.
@appleguy @maicki

**Comment by hannahmbanana** [comment]
You make a great point @lappp9. 

The ASDK team really (and I mean _REALLY_) cares about naming conventions, but we got pretty side-tracked with debating the naming of this element just last week and I'm not sure anyone has the heart to do it again. :D 

cc @garrettmoon @Adlai-Holler

**Comment by appleguy** [comment]
@lappp9 this is a very thoughtful consideration, and could have been a valuable input to the discussion!  That said, I think we're locked on this particular name.

It has the advantage of being more concrete and understandable to developers; a "Layoutable" is a pretty abstract and funny-sounding thing, whereas a "LayoutElement" can more readily be understood as an individual object that relates to a layout.

This was one of the toughest names to choose in the API, and I think there are compromises for both, so in this case we'll forge ahead with the benefits and detriments to ASLayoutElement.

**Comment by lappp9** [comment]
@appleguy gotcha, that reasoning definitely makes sense!
