### ISSUE TITLE
Better Table / Collection Update History

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#2486]
I think there are a couple easy wins we could get for collection/table debugging.
- Make `_ASHierarchyChangeSet` generate much shorter, more readable descriptions. `<ASHierarchyChangeSet 0xFFFFFFF: insertedSections={0,1}; deletedSections={2}; reloadedItems={(0 0), (0 3), (0 5-8), (1 0)}>` would be reasonable. Later on we could add the name from the section context object. See `ASObjectDescriptionHelpers.h` and the function `ASGetDescriptionValueString` to see how to create custom descriptions and to specify how we create tiny strings from objects.
- Use `ASDisplayNodeLogEvent` to log when each changeset is submitted (in `[ASChangeSetDataController endUpdates]`) and when it is finished (when that method calls super, add the log into the completion block).
- Make `ASTableNode` and `ASCollectionNode` print their data sources & delegates in their debug descriptions.

**Comment by nguyenhuy** [comment]
@Adlai-Holler: I can take this if you don't mind.

**Comment by Adlai-Holler** [comment]
Awesome, thanks @nguyenhuy !
