### ISSUE TITLE
[1.9.91] Images sometimes don't load (ASImageNode).

### ISSUE THREAD

**Issue by bevbomb** [facebook/AsyncDisplayKit#2488]
ASImageNode's sometimes don't load images but are sized correctly inside a ASCellNode.
If i scroll away and scroll the node back so that its visible that seems to fix them.

Version: AsyncDisplayKit (1.9.91)

![screenshot 2016-10-27 18 04 27](https://cloud.githubusercontent.com/assets/7086909/19757698/f8675eca-9c6f-11e6-8a2c-67cb382b8445.png)
![img_5309](https://cloud.githubusercontent.com/assets/7086909/19757754/445a60ca-9c70-11e6-95e0-bdb9dac5bb4a.PNG)

**Comment by appleguy** [comment]
@bevbomb Hey there - thank you for reporting this!  I have good news and bad news:

- Good news: Pinterest is an app full of images, and we are not seeing this issue with the current version of the framework.
- Bad news: 1.9.91 is now pretty outdated, and it would be hard to tell if there is a bug in this version.

I'd suggest updating to master (or releases/p6.13 if you want a more stable target that we've shipped a Pinterest release with).  Please let us know if you see any loading issues with this version.  You should find performance of image loading to be improved as well.

**Comment by appleguy** [comment]
Also:
- Are you using ASNetworkImageNode, or just ASImageNode?
- Are you including PINRemoteImage and PINCache with your app and using the default functionality they provide, or initializing with a custom cache / downloader instead?

**Comment by bevbomb** [comment]
Hi, thanks for your reply! 
I'll do an update today to see if it fixes the issue 😊
I'm using the default ASImageNode with static images loaded from the assets library

**Comment by bevbomb** [comment]
@appleguy Everything is working really great after the update! Images are loading first go and everything else is loading quick too! Thank you !
