### ISSUE TITLE
ASInsetLayoutSpec in swift

### ISSUE THREAD

**Issue by lsnpatryks** [facebook/AsyncDisplayKit#2490]
Hello,
I am trying to create example from http://asyncdisplaykit.org/docs/automatic-layout-examples-2.html (with text stick to bottom overlay node) in swift (the examples have only objective-c code), but I have a problem with `INFINITY` value (it does not exists as is in swift). I am using 1.9.91 version of AsyncDisplayKit

my code:
```
    override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
        let width: CGFloat = constrainedSize.max.width
        photoNode.preferredFrameSize = CGSize(width: width, height: width)
        
        let backgroundImageStaticSpec = ASStaticLayoutSpec(children: [photoNode])
        let insets = UIEdgeInsetsMake(CGFloat.greatestFiniteMagnitude, 10.0, 10.0, 10.0)
        let textInsetSpec = ASInsetLayoutSpec(insets: insets, child: nameNode)
        let textOverlaySpec = ASOverlayLayoutSpec(child: backgroundImageStaticSpec, overlay: textInsetSpec)
        return textOverlaySpec
    }
```

it unfortunately fails on assertion (`ASLayout.mm:211`)
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Layout has an invalid position'
```

What value should I use for top edge inset? Or maybe there is some other way to accomplish this task? You guys do an awesome job with the library by the way 👍

**Comment by george-gw** [comment]
You can use `CGFloat.infinity ` as Swift's version of `ÌNFINITY`

You can take a look at: https://github.com/george-gw/AsyncDisplayKit/blob/Playground-Swift/examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Pages/PhotoWithInsetTextOverlay.xcplaygroundpage/Contents.swift

For the swift code of the corresponding Objective C code for an example.

**Comment by lsnpatryks** [comment]
@george-gw thanks 👍  good work with the examples - to be honest I wasn't aware of `CGFloat.infinity`
