### ISSUE TITLE
ASDK website blocked in China due to Facebook DNS server

### ISSUE THREAD

**Issue by Draveness** [facebook/AsyncDisplayKit#2499]
Am I the only person who cannot open the home page for ASDK? Many people arounds me cann't open http://asyncdisplaykit.org this website. Is there any possibilities that we are in China?

Sorry for posting this problem in an issue.

**Comment by Draveness** [comment]
Sorry for this..

**Comment by maicki** [comment]
@Draveness Hey, asyncdisplaykit.org is hosted on Github, can you get to other pages that are hosted on Github pages?

**Comment by Draveness** [comment]
I have already solve this problem which is caused by some blocking resources that can't access in China. Sorry for interruption again....

Regards,
Draveness

**Comment by maicki** [comment]
Thanks @Draveness - That's good to know as maybe other developers from China are not be able to see the page.

cc @Adlai-Holler @hannahmbanana

**Comment by hannahmbanana** [comment]
Hmmm...maybe we should produce a pdf of the website content?
![image](https://cloud.githubusercontent.com/assets/3419380/20047067/64ca296a-a465-11e6-94c5-b9f8acb82444.png)

**Comment by Draveness** [comment]
If this website is hosted on GitHub, it wouldn't be blocked from China, except some resources like css or js files is blocked and causing the whole website unaccessible in China.

**Comment by maicki** [comment]
This website is hosted on Github. The main problem is not the website though it's the DNS server for the domain name. It seems like the main DNS server is `A.NS.FACEBOOK.COM`. Unfortunately Facebook is blocked within China so if you would like to open the website the DNS never get's resolved to an IP address as the name server is not reachable.

**Comment by garrettmoon** [comment]
@appleguy can you provide any guidance on how we could resolve this?

**Comment by hannahmbanana** [comment]
Moving this issue to the documentation repo - AsyncDisplayKit/Documentation/issues/79
