### ISSUE TITLE
How to add ASDK to UIViews? 

### ISSUE THREAD

**Issue by alexvbush** [facebook/AsyncDisplayKit#2502]
Hi, amazing library! We are converting our newsfeed to use ASDK and it's going incredibly well! It's going so well that I'd like to start using ASDK with other parts of the application just for the sake of having simple and easy layout process. And that is what I'm struggling with currently - how do I actually add a view created and sized by a node as a subview to another view that is not using ASDK?

**Comment by maicki** [comment]
@alexvbush Hey Alex! Look for `[view addSubnode:node]`.

**Comment by codeOfRobin** [comment]
@maicki How do you layout a subnode after adding it to the view?

**Comment by maicki** [comment]
@codeOfRobin The same way you would do it within UIKit. Either in an `UIView` subclass in `layoutSubviews` or in an `UIViewController` subclass in `viewDidLayoutSubviews`.

**Comment by codeOfRobin** [comment]
@maicki Thanks! 
So, I'll write down what I think is the _"canonical"_ way of setting up ASDK nodes inside UIViewControllers.

1. Add an `ASDisplayNode` to your `UIView`. Typically, setting it's bounds = view.bounds in the `viewDidLayoutSubviews` method is useful for most cases
2. Add subnodes to the aforementioned `ASDisplayNode`
3. Profit ??
