### ISSUE TITLE
Help debugging possible memory leak 

### ISSUE THREAD

**Issue by nhatlee** [facebook/AsyncDisplayKit#2508]
Hi
My app write by Swift 3. I use version 1.9.90 and when use Debug Memory Graph in Xcode 8. I got the memories leaks `3 node circle -> CFString`. But don't know how to fix.Please view the image for detail. Please help me to fix it.
![screen shot 2016-10-30 at 6 08 11 pm](https://cloud.githubusercontent.com/assets/7148482/19836238/6d6647e6-9ecc-11e6-9eaa-c52fff3268ba.png)

**Comment by hannahmbanana** [comment]
@nhatlee - could you open the "3-node cycle" icon and post a screenshot of that? This currently isn't enough information for us to understand what is going one. 

Also, note that in Apple's memory graph, the word "node" is a generic term for any NSObject object in memory (a "node" in a tree). It could be an AsyncDisplayKit node or a UIViewController, etc.

**Comment by nhatlee** [comment]
Hi @hannahmbanana,
Thanks for your information about the meaning of the word `node` in Apple's memory graph. Please view the image detail of the `3-node cycle`
![screen shot 2016-10-31 at 10 22 13 am](https://cloud.githubusercontent.com/assets/7148482/19843441/018c44a6-9f55-11e6-8722-06bed0686865.png)

**Comment by Adlai-Holler** [comment]
It looks like the retain cycle is a UIViewController issue. The reference on the right side of that cycle is `_externalObjectsTableForViewLoading`, a private property of UIViewController. I'm not sure what that field is for, but it looks like it's related to the interface builder. Does that seem reasonable?

**Comment by appleguy** [comment]
@nhatlee I think you have a configuration issue in Interface Builder that has created a circular reference.  Note that AsyncDisplayKit doesn't support Interface Builder, so you may have issues here as well.

Please come online to our Slack room if you have any additional information that we can help you in debugging this or other issues!  http://asyncdisplaykit.org/slack.html
