### ISSUE TITLE
[ASDisplayNode] _displaysAsynchronously is not safe to call off the main thread

### ISSUE THREAD

**Issue by garrettmoon** [facebook/AsyncDisplayKit#2517]
We're seeing an assertion in `_displaysAsynchronously` for calling it off the main thread. I believe the assertion is incorrect and we should instead be holding the `__instanceLock__`. Currently, `_pendingLayoutTransitionDidComplete` calls it and that method should be able to run off the main thread I believe.

**Comment by maicki** [comment]
@garrettmoon Thanks for reporting. I will look into it.
