### ISSUE TITLE
ASTableView  insertRowsAtIndexPaths:withRowAnimation:   beginUpdates/endUpdates Exception  

### ISSUE THREAD

**Issue by duxinfeng** [facebook/AsyncDisplayKit#252]
Hello,wen i used to insertRowsAtIndexPaths exception

NSMutableArray *indexPaths = [NSMutableArray array];
    NSInteger currentCount = _dataarray.count;
    for (int i = 0; i < array.count; i++) {
        [indexPaths addObject:[NSIndexPath indexPathForRow:currentCount+i inSection:0]];
    }
    [_dataarray addObjectsFromArray:array];
    [_tableView beginUpdates];
    [_tableView insertRowsAtIndexPaths:indexPaths withRowAnimation:UITableViewRowAnimationBottom];
    [_tableView endUpdates];

*** Terminating app due to uncaught exception 'UnimplementedException', reason: 'ASTableView's grouped updates aren't currently supported yet, please call the insert/delete function directly.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c5ed495 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010c34499e objc_exception_throw + 43
	2   CoreFoundation                      0x000000010c671919 -[NSException raise] + 9
	3   PowerDaily                          0x000000010adb43eb -[ASTableView throwUnimplementedException] + 91
	4   PowerDaily                          0x000000010adb444b -[ASTableView beginUpdates] + 43
	5   PowerDaily                          0x000000010acfb64b __41-[PDMainViewController insertRowAtBottom]_block_invoke + 475
	6   PowerDaily                          0x000000010acf0596 __52+[PDAPIManager requestHistoryMoreItemData:response:]_block_invoke + 998
	7   PowerDaily                          0x000000010ad14581 __84-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:success:failure:]_block_invoke87 + 241
	8   PowerDaily                          0x000000010ad37ceb __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_272 + 203
	9   libdispatch.dylib                   0x000000010daea851 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000010dafd72d _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010daed3fc _dispatch_main_queue_callback_4CF + 354
	12  CoreFoundation                      0x000000010c64b289 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x000000010c598854 __CFRunLoopRun + 1764
	14  CoreFoundation                      0x000000010c597d83 CFRunLoopRunSpecific + 467
	15  GraphicsServices                    0x000000010e887f04 GSEventRunModal + 161
	16  UIKit                               0x000000010c9fee33 UIApplicationMain + 1010
	17  PowerDaily                          0x000000010acf12d3 main + 115
	18  libdyld.dylib                       0x000000010dd8b5c9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by kylehickinson** [comment]
As the assertion says, batch updates aren't supported yet, so remove the `beginUpdates` and `endUpdates` calls.

**Comment by secretiverhyme** [comment]
@kylehickinson is correct.  @tanliboy is working on adding support for explicit update batches — for now, you should simply call `-insertRowsAtIndexPaths:…` directly.

**Comment by duxinfeng** [comment]
thanks !  @secretiverhyme  @kylehickinson

**Comment by toulouse** [comment]
cc @nolanw ^
