### ISSUE TITLE
[Examples] CustomCollectionView - constrainedSizeForNodeAtIndexPath is not called while rotation

### ISSUE THREAD

**Issue by Baevra** [facebook/AsyncDisplayKit#2540]
I'm trying to use custom collectionViewLayout with layoutInspector like in sample app i have similar rotation problem, after two rotation constrainedSizeForNodeAtIndexPath not called in portrait mode
ASDK 2.0 beta 1

**Comment by hannahmbanana** [comment]
@maicki: In case it wasn't clear, the example project collectionViewLayout shows this bug.

**Comment by hannahmbanana** [comment]
@Baevra - Great catch! See the linked PR for an explanation of the issue.

You can resolve the issue by having your layoutInspector implement `- (ASScrollDirection)scrollableDirections`.

**Comment by Baevra** [comment]
@hannahmbanana It works great with scrollableDirections! As always thanks for efficiency!!!
