### ISSUE TITLE
[ASPagerNodeDataSource] require pagerNode:nodeAtIndex:

### ISSUE THREAD

**Issue by hannahmbanana** [facebook/AsyncDisplayKit#2544]
@rurza - could we get you to implement this? :)

**Comment by maicki** [comment]
This is kind of tricky to do. As we currently have two different data source methods that can be implemented: `[ASPagerNodeDataSource pagerNode:nodeAtIndex:]` or `[ASPagerNodeDataSource pagerNode:nodeBlockAtIndex:]`. That's the reason we cannot require one or the other. We already throw an assertion if not at least one of them is implemented though.

**Comment by Adlai-Holler** [comment]
Yep unfortunately we can't do this.
