### ISSUE TITLE
[AutomaticSubnodeMgmt] node ordering issue when using ASBackgroundLayoutSpec/ASOverlayLayoutSpec

### ISSUE THREAD

**Issue by mikhailmulyar** [facebook/AsyncDisplayKit#2549]
I have node which has automaticallyManagesSubnodes=true. I have this spec in my code which works as intended.
`ASBackgroundLayoutSpec(child: self.tableNode, background: self.switchNode)`
It puts switch node behind table node. But if i change it like that.
`ASBackgroundLayoutSpec(child: self.tableNode, background: ASInsetLayoutSpec(insets: UIEdgeInsetsMake(1,1,1,1), child: self.switchNode))`
Then table node is behind switch node. Same issue happens if i use ASOverlayLayoutSpec.
I use 2.0 beta.

**Comment by hannahmbanana** [comment]
@mikhailmulyar - this is a known issue with `. automaticallyManagesSubnodes` that we have plans to resolve in the near future. For now, you can work around the issue by manually adding the subnodes.

**Comment by Adlai-Holler** [comment]
@mikhailmulyar Hi! We've resolved this issue on master and we're excited to bring it into the next beta release for 2.0. If you have any issues, please don't hesitate to reach out and let us know!
