### ISSUE TITLE
Convert layout example project to Swift

### ISSUE THREAD

**Issue by hannahmbanana** [facebook/AsyncDisplayKit#2552]
It would be awesome if someone could duplicate the example project in #2551 in Swift.

**Comment by rajeevwhiz** [comment]
@hannahmbanana  I converted one layout to swift. Code is in https://github.com/facebook/AsyncDisplayKit/issues/2548. 

Let me know if this helps. thanks

**Comment by hannahmbanana** [comment]
@rajeevwhiz - would you be interested in cleaning up the project and submitting it as a Pull Request? I think others would find your work very valuable since we only have 1 or 2 Swift examples. Let me know if you aren't interested and I can work getting the project ready to submit.

**Comment by rajeevwhiz** [comment]
Yes, I would love to.

**Comment by hannahmbanana** [comment]
@rajeevwhiz - that would be awesome! 

A few requests:
- name the project `CustomCollectionView-Swift`
- usually we recommend that you take a example project (e.g. the `Swift` example) and copy in your files to preserve the project settings & project name ("Sample")
- include legal header comments at the top of each file
- also, make sure you use 2 spaces (instead of tabs) :)

**Comment by rajeevwhiz** [comment]
@hannahmbanana I am getting HTTP error 403 when I try to push the code to new branch "CustomCollectionView-Swift"

**Comment by maicki** [comment]
@rajeevwhiz Hey, did you fork the ASDK project and created a PR from your fork. You cannot push to a branch to the facebook/AsyncDisplayKit project directly.

**Comment by rajeevwhiz** [comment]
@maicki my apologies. I just submitted the PR from the fork. Let me know if everything looks okay.

**Comment by maicki** [comment]
@rajeevwhiz Thanks!

PR: #2591

**Comment by hannahmbanana** [comment]
I'm going to close this issue, but if anyone else would like to convert one of our existing [example projects] to Swift, we'd happily take your PR.
