### ISSUE TITLE
[Documentation] Missing header comments in a few classes.

### ISSUE THREAD

**Issue by hannahmbanana** [facebook/AsyncDisplayKit#2556]
Warnings for missing documentation when running appledocs:
[Ouput log (includes warnings).txt](https://github.com/AsyncDisplayKit/Documentation/files/573629/Ouput.log.includes.warnings.txt)

**Comment by garrettmoon** [comment]
Can you take a look at this one @hannahmbanana ?

**Comment by hannahmbanana** [comment]
Much of this was already added.
