### ISSUE TITLE
didSelectItemAt conflicts with nodeForItemAt in ASCollectionDelegate 

### ISSUE THREAD

**Issue by rajeevwhiz** [facebook/AsyncDisplayKit#2558]
Trying to implement select item in ASCollectionDelegate 
```
func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
}
```
but getting this warning. 

![screen shot 2016-11-05 at 10 26 14 pm](https://cloud.githubusercontent.com/assets/20877749/20035557/09097892-a3a7-11e6-8d86-cfa6eff31f80.jpg)

I am not sure how to take care of the warning. If I make the function private or add @nonobjc, function is not called when a node is selected.

**Comment by CR34L** [comment]
If you want to use AS Components such ASCollectionView or ASCollectionNode you should implement the AS Delegates:

```
public func collectionNode(_ collectionNode: ASCollectionNode, didSelectItemAt indexPath: IndexPath)
    {
        // do something
    }
```

**Comment by maicki** [comment]
Hi @rajeevwhiz, what version of ASDK do you use? If you use ASDK 2.0 the direct use of `ASCollectionView` is not suggested anymore and in fact methods are now deprecated. Please try to use `ASColllectionNode` instead.

**Comment by rajeevwhiz** [comment]
Moved to 2.0 and this is not an issue anymore
