### ISSUE TITLE
[Layout Question] Inset text overlay

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#2559]
so here is what I'm looking for:
I have an textNode with dynamic height that is over an imageNode

![rectangle](https://cloud.githubusercontent.com/assets/3206748/20037709/fcef8c88-a43a-11e6-8e8b-ccab7a7028e0.jpg)

I want to statically position textNode left , and bottom with inset of 8 over `ASImageNode`. 
so in `layoutSpecThatFits(:)`

``` swift
let inset: CGFloat = 8
textNode.minHeight = ASDimensionMake(kOutOfStockNodeMinHeight)
textNode.maxWidth = ASDimensionMake(150)

outOfStockNode.layoutPosition = CGPoint(x: inset , y: coverImageHeight - (textNode.height) - inset)

 let textNodeStaticPosition = ASStaticLayoutSpec(children: [textNodeNode])
   let textNodeOverImage = ASOverlayLayoutSpec(child: coverImageLayoutSpec, overlay: textNodeStaticPosition)
```

problem is that in `layoutSpecThatFits(:)` textNode size has not been measured yet!!

what if `layoutPosition` had `bottom` property and I just assigned that with inset. so later textNode could position correctly?

any idea to solve this layout?

**Comment by hannahmbanana** [comment]
@hashemp206 - I believe you could use an `ASInsetLayoutSpec` with `INFINITY` for the top and right `UIEdgeInset` values, then put that in the `ASOverlayLayoutSpec`. 

This concept is show in this example (example code in the `examples/LayoutSpecExamples` project): http://asyncdisplaykit.org/docs/automatic-layout-examples-2.html#photo-with-inset-text-overlay

**Comment by hashemp206** [comment]
thanks for your help. and pointing to example.  what I did:

``` swift
let inset = ASInsetLayoutSpec(insets: UIEdgeInsetsMake(CGFloat(Double.infinity), 8, 8, CGFloat(Double.infinity)), child: outOfStockNode)
let outOfStockOverImage = ASOverlayLayoutSpec(child: coverImageLayoutSpec, overlay: inset)
```

**Comment by hannahmbanana** [comment]
@hashemp206 - awesome! Thank you for reporting back so that the community can see what worked!
