### ISSUE TITLE
Explore fixed node sizes in ASTableView and ASCollectionView

### ISSUE THREAD

**Issue by rnystrom** [facebook/AsyncDisplayKit#256]
We could save some cycles by not having to initialize every node immediately in order to have the size/height of the table or collection view.

**Comment by secretiverhyme** [comment]
Discussed offline — this is basically a subset of #258.  Fixed-size cells are more or less the ideal usecase for UITableView and UICollectionView, and are certainly an edge case in AsyncDisplayKit-based code, so we should focus on the general solution.
