### ISSUE TITLE
ASDisplayNode still keep alive

### ISSUE THREAD

**Issue by dungnc** [facebook/AsyncDisplayKit#2587]
Hi @appleguy, @nguyenhuy 

I face a big issue, it's make my app crash for memory issue!

**There is my demo app**: [https://github.com/caophong94/alivecellnode](url)

**Description**: 
- When i dismiss a view controller with default transition, the nodes on this view controller are gone, but if i use custom transition, the node still keep alive, because _ASDisplayView not receive the event willMoveToSuperview:(UIView *)newSuperview
- Work well with default iOS transition

Anybody can help? 
Thanks & Best regards

**Comment by maicki** [comment]
Hey @dungnc it is the exact same problem I described within this issue yesterday: #2339 . In your project you have a retain cycle you should fix. Please look into the mentioned issue for more details. Thanks!
