### ISSUE TITLE
ASMultiplexImageNode Multiple Issues

### ISSUE THREAD

**Issue by rajeevwhiz** [facebook/AsyncDisplayKit#2588]
Hi @appleguy @maicki @Adlai-Holler,

Attached is the  Sample project that replicate following issues:

-- **Issue 1**: ImageCellNode uses ASMultiplexImageNode. urlForImageIdentifier is being called but Images are not showing up in the ASCollectionNode
-- **Issue 2**: ASMultiplexImageNode also does not show placeholder image. placeholderImage() method is in place but the image is being ignored. However, ASDisplayNodeDefaultPlaceholderColor() is working
-- **Issue 3**: Images are being loaded from Photo Library using PHPhotoLibraryChangeObserver and also showing up in the Collection. However, urlForImageIdentifier is being called for every image identifier, thereby loading image of all sizes and increasing memory use exponentially!

I would really appreciate any tips or workarounds. 
Thanks,
Rajeev

[CustomCollectionView.zip](https://github.com/facebook/AsyncDisplayKit/files/581576/CustomCollectionView.zip)

**Comment by rajeevwhiz** [comment]
Refer to  [#2578](https://github.com/facebook/AsyncDisplayKit/issues/2578) for more details

**Comment by rajeevwhiz** [comment]
Fixed Issue#1 by removing ASImageDownloaderProtocol. Issue#2 is not critical. 

However, Issue#3 is puzzling.. it's happening irrespective of whether I download image from URL or from local cache or from Photo Library. 

How does the framework know which image identifier to use when? That's the missing link, I think.. I don't see I am establishing this linkage anywhere...

**Comment by rajeevwhiz** [comment]
Regarding Issue#3, I have **imageNode?.downloadsIntermediateImages = false** but I still see images of all sizes being downloaded.

**Comment by rajeevwhiz** [comment]
Some clarification Questions: 

-- Does ASMultiplexImageNode use caching by default or do I have to implement ASImageCacheProtocol?
-- What's the use case where I may be required to implement ASImageDownloaderProtocol?

**Comment by rajeevwhiz** [comment]
@appleguy , @maicki , @Adlai-Holler -- attached is the sample project that reproduces Issue3
[CustomCollectionView.zip](https://github.com/facebook/AsyncDisplayKit/files/586121/CustomCollectionView.zip)

**Comment by garrettmoon** [comment]
Hi @rajeevwhiz we rely on Github issues to track work being done on ASDK. It's really important that each issue describe one problem. Would you mind updating this issue to just one of the issues you're describing and opening two more each with their own? You can still use the same sample project of course!

**Comment by rajeevwhiz** [comment]
looks like I misinterpreted the purpose of DidUpdate... that's called everytime a node refreshes... but it doesn't mean the image is being downloaded. I implemented progressUpdate and that's only called once per image!!  

I am closing this as it's not an issue.
