### ISSUE TITLE
[ASNetworkImageNodeDelegate] non-animated gif confusion

### ISSUE THREAD

**Issue by tomizimobile** [facebook/AsyncDisplayKit#2590]
When I set the `url` of an ASNetworkImageNode to a non-animated gif, and implement ASNetworkImageNodeDelegate, things get confusing. The delegate method `-imageNode:didLoadImage:` is called with `nil` for the `image`, and the `imageNode` has the `animatedImage` set. This was very unexpected, and tough to track down when trying to use it. I think it'd be more clear if non-animated gifs were set to the `image` property, or if there was another delegate method for when an animated image is loaded.

Using current master (171cc2f5272a39cc7c695a26aacdb8c97d256d1b)

**Comment by garrettmoon** [comment]
@tomizimobile can you provide more info? For example, the URL you were loading or a small sample project? The behavior you're describing is definitely not correct!

**Comment by tomizimobile** [comment]
@garrettmoon try out this URL: http://ak-cache.legacy.net/legacy/images/fhlogo/7630fhlogo.gif

**Comment by garrettmoon** [comment]
@tomizimobile This is actually an issue with PINRemoteImage, not ASDK. Do you mind opening up an issue there: https://github.com/pinterest/PINRemoteImage ?

**Comment by garrettmoon** [comment]
Thanks @tomizimobile going to close this one here, will continue over on PINRemoteImage :)
