### ISSUE TITLE
[ASImageNode] Does not redraw if width or height of bounds are the same on bounds change

### ISSUE THREAD

**Issue by maicki** [facebook/AsyncDisplayKit#2595]
`ASImageNode` does not trigger a redisplay if the frame is changed and the `width` or the `height` is the same as before.

Use this code as base:
```objc
self.imageNode.frame = CGRectMake(50, 70, 100, 100);
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
  self.imageNode.frame = CGRectMake(50, 70, 50, 100);
  //[self.imageNode setNeedsDisplay];
});
```

With commented out code of the explicit `setNeedsDisplay` the call order will be:
<img width="888" alt="screen shot 2016-11-11 at 9 59 26 am" src="https://cloud.githubusercontent.com/assets/25288/20224987/e8a6faf4-a7f5-11e6-9699-7d9513e7d6b9.png">

With uncommented code of `setNeedsDisplay` the drawing method for `ASImageNode` will be called:
<img width="886" alt="screen shot 2016-11-11 at 9 57 54 am" src="https://cloud.githubusercontent.com/assets/25288/20225018/07f87072-a7f6-11e6-8860-a61e08fe5cdb.png">

**Comment by maicki** [comment]
Setting `needsDisplayOnBoundsChange` will actually resolve this issue. That said this is different than `UIKit` is working and we may think of enabling `needsDisplayOnBoundsChange` by default.

**Comment by Adlai-Holler** [comment]
@maicki What's the motivation to change this? I think we should leave this as-is, with the following rationale:

- UIKit doesn't do this – UIImageView only draws once (although it draws the image full-size, whereas we draw the image at bounds-size).
- This will break animated/continuous image node size changes.

**Comment by maicki** [comment]
Yes, after diving into that a bit more, I agree and understand the reasoning behind it. Let's close it.
