### ISSUE TITLE
Crash in ASCollectionNode with custom ASCollectionViewLayoutInspector deallocated

### ISSUE THREAD

**Issue by tungvoduc** [facebook/AsyncDisplayKit#2598]
It is very easy to reproduce this crash in 2.0 beta.1
- Start with example CustomCollectionView, set UINavigationController as rootViewController of the window. 
- Push to another instance of ViewController
- Pop back --> Crash the app

**Comment by appleguy** [comment]
@tungvoduc ha, thanks a lot for reporting this and the steps!  We just recently made changes in this area, so it should be pretty quick to track down the regression.

**Comment by Adlai-Holler** [comment]
Hey @tungvoduc I can't yet reproduce this. I made this branch following your instructions – could you pull down branch [`AHCrash2598`](https://github.com/facebook/AsyncDisplayKit/tree/AHCrash2598) and give it a try?

**Comment by tungvoduc** [comment]
@appleguy @Adlai-Holler : Sorry! I forgot to mention that I got exception _OBJC_SUPPORTED_INLINE_REFCNT_WITH_DEALLOC2MAIN when I tried to remove observer in deinit of ASDisplayNode, commenting it works fine though. So I tried the branch AHNaturalDealloc, it fixed the problem but I got another exception "layoutInspector object must implement -scrollableDirections".

**Comment by garrettmoon** [comment]
This looks to be the same issue as https://github.com/facebook/AsyncDisplayKit/issues/2598

If not, please feel free to reply here.
