### ISSUE TITLE
[ASLayoutSpec] Subnode ordering when using Overlay/Background with ASM

### ISSUE THREAD

**Issue by hannahmbanana** [facebook/AsyncDisplayKit#2603]
Subnode ordering is sometimes incorrect when using the overlay / background spec with automatic subnode management. 

@maicki - should this be in the `2.0` or the `2.0.1` milestone?

**Comment by Adlai-Holler** [comment]
I believe this was addressed in https://github.com/facebook/AsyncDisplayKit/pull/2589 . Feel free to reopen if not.
