### ISSUE TITLE
[Community Debugging] Data source assertion when inserting rows.

### ISSUE THREAD

**Issue by lizhaojie001** [facebook/AsyncDisplayKit#2606]
-[NSWYViewController insertNewRowsInTableNode:]_block_invoke_2
2016-11-14 17:32:08.981741 Sample[782:148439] Invalid number of items in section 0. The number of items after the update (210) must be equal to the number of items before the update (210) plus or minus the number of items

**Comment by garrettmoon** [comment]
@lizhaojie001 can you put up a project which reproduces this issue? This usually indicates that there's a mistake in your code using the table node, possibly in the datasource.

**Comment by appleguy** [comment]
@lizhaojie001 Garrett's correct - these are the same data integrity assertions you see with UIKit, so the issue should exist if you tried pointing your project towards UICollectionView.

A Slack DM would be more private if you can share some of the code.  If you double check what insertion / deletion calls you're making, and are confident the data source methods are reflecting numbers that exactly match, then it should be fixed.  If you do resolve, please close out the task.

Thanks for filing an issue, hope the framework is useful and maybe see you around asking questions with the Slack community :)  http://asyncdisplaykit.org/slack.html
