### ISSUE TITLE
[ASTextNode] truncationStyle text overlapping, reproduction case included.

### ISSUE THREAD

**Issue by wockerwalker** [facebook/AsyncDisplayKit#261]
setting the `truncationStyle` of ASTextNode doesn't result in truncation. I've repro'd with `NSLineBreakByTruncatingHead/Tail/Clipping`. When set to `NSLineBreakByTruncatingTail`, the text runs to the end and then the final words (which should be truncated) stack on top of one another. Additionally, the `textNode.isTruncated` bool is `NO` when checked after sizing.

**Comment by secretiverhyme** [comment]
Thanks for the report!

**Comment by rnystrom** [comment]
For records sake, here's a screenshot of the repro. Good find :)

![kitten](https://cloud.githubusercontent.com/assets/739696/5925012/648092a0-a615-11e4-8e68-a252837d9682.png)

**Comment by lxcid** [comment]
I'm not sure if this help, it seems that if the last character in the truncated line end with a space character, the rendering goes haywire. In my own project, I get overlapping character like the screenshot above, but in the kittens sample project, The text sometimes truncate too early just by adding a space character behind each new line. The screenshots come with a visual of the diff.

__No space character added at the end of each new line:__
![screenshot 2015-02-25 23 04 07](https://cloud.githubusercontent.com/assets/297156/6372996/be78edfe-bd42-11e4-99b2-69ec636f9b77.png)

__One space character added at the end of each new line:__
![screenshot 2015-02-25 23 03 41](https://cloud.githubusercontent.com/assets/297156/6373014/e3d32b96-bd42-11e4-8f95-81c9955bb50e.png)

**Comment by appleguy** [comment]
I confirmed this is still happening.  Attached a diff.

An easy workaround is to use NSParagraphStyle to set the .lineBreakMode.  Still, this bug is very strange.

@ocrickard, I'm not sure if there is a comparable API in component kit to directly set the truncation mode separate from the paragraph style, or if there are any other known bugs with truncation in the renderer, but please let me know if so!

[TruncationOverlap.txt](https://github.com/facebook/AsyncDisplayKit/files/120540/TruncationOverlap.txt)

![simulator screen shot feb 6 2016 6 19 10 pm](https://cloud.githubusercontent.com/assets/565251/12870528/2a3abdc6-ccfe-11e5-8754-fadba007976c.png)
![simulator screen shot feb 6 2016 6 18 21 pm](https://cloud.githubusercontent.com/assets/565251/12870529/2a5c2b3c-ccfe-11e5-97fe-a63e5753ab98.png)

**Comment by ocrickard** [comment]
Yeah @appleguy I've got no idea. I haven't been working on this stuff for quite awhile.

**Comment by appleguy** [comment]
@wockerwalker @lxcid - I fixed an issue with tail truncation a couple days ago and it significantly improved the behavior of this issue as well. It seems like there is still a change in rendering after scrolling down and after scrolling back when the #define in my .txt above is enabled. I would appreciate if either of you have time to try this out in any of your application that may have encountered the original issue and let me know if the behavior is resolved.

**Comment by hannahmbanana** [comment]
It appears that the two cases above (text overlap & space character after newline) are fixed on the latest master. I believe that we can close out this issue now.

**Comment by appleguy** [comment]
@hannahmbanana: thanks for confirming!

**Comment by ocrickard** [comment]
Yay!

**Comment by appleguy** [comment]
:-D indeed it seems like the fixes from a couple months ago had done the trick, so fortunately users have been benefitting from the improvements for a few releases now.

**Comment by Sethmr** [comment]
@appleguy I just ran into this bug on Texture2.7. I attempted it with paragraphStyle doing the lineBreakMode instead and had the same issue.
![img_1673](https://user-images.githubusercontent.com/10062416/42903973-707ebba8-8aa1-11e8-9181-7518844b4209.png)


`override func didLoad() {
        super.didLoad()
        textView.autocorrectionType = .default
        textView.textView.textContainer.maximumNumberOfLines = 1
        textView.textView.textContainer.lineBreakMode = .byTruncatingHead
    }

    lazy var textView: ASEditableTextNode = {
        let node = ASEditableTextNode()
        node.attributedPlaceholderText = NSAttributedString(
            "Write Reply".localize(),
            font: .systemFont(ofSize: 16.adjustToScreenSize()),
            color: .grey196
        )
        node.typingAttributes = [
            NSAttributedStringKey.foregroundColor.rawValue: UIColor.vimvestBlack,
            NSAttributedStringKey.font.rawValue: UIFont.systemFont(ofSize: 16.adjustToScreenSize())
        ]
        let image = WidgetTextNode.gradientImageForTint(height: 16.adjustToScreenSize())
        node.tintColor = UIColor(patternImage: image)
        node.style.flexGrow = 1
        node.delegate = self
        return node
    }()`
