### ISSUE TITLE
[Polish] Update comments and internal implementation from Fetch Data -> Preload terminology.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2611]
@nguyenhuy, could you rename anything that isn't being used to support the deprecated method?  We can probably leave the ASViewController internal call as it is for now as we don't have a recursive Preload method.

![screen shot 2016-11-14 at 7 03 34 pm](https://cloud.githubusercontent.com/assets/565251/20291755/4d5cbff2-aa9d-11e6-933f-cdcc55c2827c.png)
![screen shot 2016-11-14 at 7 03 14 pm](https://cloud.githubusercontent.com/assets/565251/20291756/4d7a4810-aa9d-11e6-9b16-7268b57e2b73.png)

**Comment by hannahmbanana** [comment]
@appleguy - I think there was a question as to whether we can deprecate the old methods or not. Deprecating them would be fastest.

**Comment by garrettmoon** [comment]
Addressed by https://github.com/facebook/AsyncDisplayKit/pull/2689
