### ISSUE TITLE
[ASCellNode] implement a .viewController property

### ISSUE THREAD

**Issue by MarvinNazari** [facebook/AsyncDisplayKit#2615]
When using `ASCellNode(viewControllerBlock:` there is no way to access the `viewcontroller` afterwards, we use it in some places specially with `ASPagerNode`
this is how i do it right now
```swift
extension ASCellNode {
    var viewController: UIViewController? {
        return valueForKey("_viewController") as? UIViewController
    }
}
```

**Comment by hannahmbanana** [comment]
@MarvinNazari - This is possible to implement, but has yet to happen. It would require some logic to make sure that the view controller is only accessed from the main thread. If you'd be interested in submitting a PR for this, we'd be happy to merge it.

**Comment by Adlai-Holler** [comment]
Thanks for building this @MarvinNazari! Hope to see you around more!
