### ISSUE TITLE
[ASCollectionNode] Example app can crash in Dealloc2Main.

### ISSUE THREAD

**Issue by muukii** [facebook/AsyncDisplayKit#2617]
on 2.0 beta 1
When reloading the ASCollectionNode, the following error occurs.
`AsyncDisplayKit was compiled with optimization - stepping may behave oddly; variables may not be available.`

Is this a known problem?

![image](https://cloud.githubusercontent.com/assets/1888355/20356788/fd1b9f36-ac68-11e6-8fd5-1ba8f93eb408.png)

**Comment by hannahmbanana** [comment]
@muukii - I haven't seen this issue before. Did you create your Swift project using our Swift example project? Are you using Cocoapods? 

Did you try any of the tips in this post? http://stackoverflow.com/questions/32772573/project-name-was-compiled-with-optimization-stepping-may-behave-oddly-varia

**Comment by muukii** [comment]
@hannahmbanana 
I am using Carthage to build with DebugConfiguration.
`carthage update --platform --configuration Debug`

**Comment by muukii** [comment]
I will try it in the sample project.

**Comment by appleguy** [comment]
@muukii thanks for filing an issue!  Please see Slack discussion:


> appleguy	[9:31 PM]  
> @hannah yes that would be likely because Garrett put up a .zip of the framework for the latest version, which is precompiled, and he would've used release compilation
> 
> [9:31]  
> that would reduce debugging flexibility because it optimizes out certain instructions
> 
> garrett	[9:32 PM]  
> Sounds right to me. Carthage is a bit strange.
> 
> appleguy	[9:33 PM]  
> not sure if Carthage folks prefer if it just doesn't have the .zip - I bet their Cartfile can specify if they want to check it out from source and have it built with their project, though.  That would allow it to mirror if they are using DEBUG, RELEASE, etc locally.
> 
> I've heard some Carthage users like that it is precompiled; however for ASDK specifically, the ability to step into the framework is much more commonly useful than most third party libraries, so maybe we should only offer the source one / default ppl to it by not having the .zip.  All very weird! (edited)
> 
>

**Comment by appleguy** [comment]
Let us know if specifying to build from source in your Cartfile fixes the problem.  We'll skip uploading the .zip for Beta 2 which is going out in ~3 days.

**Comment by muukii** [comment]
oh, I did not notice there was a zip in the release tag.
I will build with --no-use-binaries.

**Comment by muukii** [comment]
@appleguy 
hmm, I tried building with the following command, but an error occurs.

`carthage update AsyncDisplayKit --platform iOS --configuration Debug --no-use-binaries`

error log
```
*** Checking out PINCache at "3.0.1-beta.2"
*** Checking out PINRemoteImage at "3.0.0-beta.6"
*** Checking out AsyncDisplayKit at "2.0-beta.1"
*** xcodebuild output can be found in /var/folders/34/rm4y6jh13cz8nnmd4_6z0svr0000gn/T/carthage-xcodebuild.702iMj.log
*** Building scheme "iOS" in PINCache.xcodeproj
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/muukii/Develop/pairs-gl-tmp/Carthage/Checkouts/PINRemoteImage/Example-Mac/PINRemoteImage.xcworkspace -scheme PINRemoteImage -configuration Debug CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme PINRemoteImage is not currently configured for the clean action.
```

**Comment by muukii** [comment]
I tried building on AsyncDisplayKit
An error also occurred here...
```
❯ muukii ❯ muukiis-mbp ❯ ~/Develop/AsyncDisplayKit
❯ (HEAD detached at 2.0-beta.1) carthage build --no-skip-current --configuration Debug
*** xcodebuild output can be found in /var/folders/34/rm4y6jh13cz8nnmd4_6z0svr0000gn/T/carthage-xcodebuild.xjWYCQ.log
*** Building scheme "AsyncDisplayKit-iOS" in AsyncDisplayKit.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/muukii/Library/Developer/Xcode/DerivedData/AsyncDisplayKit-bkrhgaurukwtcwebpepcrpdiszds/Build/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/ASCollectionViewFlowLayoutInspector.o AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit/ASContextTransitioning.h:23:11: warning: duplicate protocol definition of 'ASContextTransitioning' is ignored
/Users/muukii/Library/Developer/Xcode/DerivedData/AsyncDisplayKit-bkrhgaurukwtcwebpepcrpdiszds/Build/Products/Debug-iphonesimulator/include/AsyncDisplayKit/ASContextTransitioning.h:23:11: warning: duplicate protocol definition of 'ASContextTransitioning' is ignored
/Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit/ASContextTransitioning.h:23:11: warning: duplicate protocol definition of 'ASContextTransitioning' is ignored
/Users/muukii/Library/Developer/Xcode/DerivedData/AsyncDisplayKit-bkrhgaurukwtcwebpepcrpdiszds/Build/Products/Debug-iphonesimulator/include/AsyncDisplayKit/ASCollectionViewFlowLayoutInspector.h:23:11: warning: duplicate protocol definition of 'ASCollectionViewLayoutInspecting' is ignored
/Users/muukii/Library/Developer/Xcode/DerivedData/AsyncDisplayKit-bkrhgaurukwtcwebpepcrpdiszds/Build/Products/Debug-iphonesimulator/include/AsyncDisplayKit/ASCollectionViewFlowLayoutInspector.h:78:1: error: duplicate interface definition for class 'ASCollectionViewLayoutInspector'
/Users/muukii/Library/Developer/Xcode/DerivedData/AsyncDisplayKit-bkrhgaurukwtcwebpepcrpdiszds/Build/Products/Debug-iphonesimulator/include/AsyncDisplayKit/ASCollectionViewFlowLayoutInspector.h:88:1: error: duplicate interface definition for class 'ASCollectionViewFlowLayoutInspector'
/Users/muukii/Library/Developer/Xcode/DerivedData/AsyncDisplayKit-bkrhgaurukwtcwebpepcrpdiszds/Build/Products/Debug-iphonesimulator/include/AsyncDisplayKit/ASCollectionViewFlowLayoutInspector.h:90:67: error: property has a previous declaration
/Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h:17:29: error: redefinition of 'ASAsyncTransactionContainerState'
/Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h:22:3: error: redefinition of enumerator 'ASAsyncTransactionContainerStateNoTransactions'
/Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h:27:3: error: redefinition of enumerator 'ASAsyncTransactionContainerStatePendingTransactions'
/Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h:30:11: warning: duplicate protocol definition of 'ASAsyncTransactionContainer' is ignored
/Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h:54:21: warning: duplicate definition of category 'ASAsyncTransactionContainer' on interface 'CALayer'
/Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h:69:20: warning: duplicate definition of category 'ASAsyncTransactionContainer' on interface 'UIView'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/muukii/Develop/AsyncDisplayKit/AsyncDisplayKit.xcworkspace -scheme AsyncDisplayKit-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,id=BC53BCA3-3BF7-4A2A-87DC-7CA48FD6B929" -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **
```

**Comment by muukii** [comment]
I ran it using AsyncDisplayKit.framework that I built Debug with Xcode, but it was a similar error.
However, the following error log was not output.
AsyncDisplayKit was compiled with optimization - stepping may behave oddly; variables may not be available

```
AsyncDisplayKit was compiled with optimization - stepping may behave oddly; variables may not be available
```

<img width="1440" alt="screen shot 2016-11-17 at 16 05 18" src="https://cloud.githubusercontent.com/assets/1888355/20379447/aec00760-acdf-11e6-8974-a5aed22860ec.png">

**Comment by muukii** [comment]
@appleguy 
I installed ASDK with CocoaPods, but it did not change...

Do not call `ASCollectionNode.reloadData` more than once?

<img width="1118" alt="screen shot 2016-11-18 at 1 06 01" src="https://cloud.githubusercontent.com/assets/1888355/20397017/79c7be26-ad2b-11e6-99b7-cd29249b1f09.png">

<img width="1440" alt="screen shot 2016-11-18 at 1 06 39" src="https://cloud.githubusercontent.com/assets/1888355/20397019/7af1b892-ad2b-11e6-9bb0-6a06e1a18ac6.png">

**Comment by muukii** [comment]
Well, no problem when trying the same thing in another project.
Is it a problem with the project's build settings?

**Comment by muukii** [comment]
@appleguy 

OMG

I was writing deinit in ASCellNode to output logs,
It solved it by erasing it!

**Comment by muukii** [comment]
I uploaded a project to reproduce the crash.

[AsyncDataSources.zip](https://github.com/facebook/AsyncDisplayKit/files/598830/AsyncDataSources.zip)

**Comment by appleguy** [comment]
@Adlai-Holler Can you test to verify you can repro the crash, and then test against your Dealloc2Main removal diff to verify it fixes it?

**Comment by Adlai-Holler** [comment]
@appleguy Yep, confirmed it was broken before and it's working on master! @muukii Thank you very much for bringing this to our attention. We are planning to release a 2nd beta of 2.0 very soon, and you can likely use `master` in the mean time if needed. Also feel free to reopen this issue if needed. Cheers!
