### ISSUE TITLE
[ASCollectionView] Layout Inspector needs to fail earlier if not set up; ideally be provided by Layout object.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2634]
On some closeup views in Pinterest, we are hitting this assertion.  It's due to recent changes to require that scrollableDirections be overridden for any collection with a custom layout.  We do have a custom layout inspector in Pinterest but it seems it may not always be set.

Question is, why would we create this base class object at all if we know it will hit an assertion?  Can we throw the assertion at an earlier stage that is easier to debug, like maybe if a collection becomes visible without its layout inspector?

Two possible directions for improving how layoutInspector is set:

1. Instead of waiting for an external user to set the layoutInspector, can we take in a class name for it at initialization time?  In Pinterest, we have several places that set the .layoutInspector property but it seems easy to forget this line.

2. If a custom layout inspector always needs to be used for a particular custom layout, can we make it a category method on UICollectionViewLayout, and in the method check for class FlowLayout to create a default one + allow overrides in subclasses to return their custom one like Masonry needs to?

```
    } else {
      // Register the default layout inspector delegate for custom collection view layouts
      _defaultLayoutInspector = [[ASCollectionViewLayoutInspector alloc] initWithCollectionView:self];
    }

```
![screen shot 2016-11-19 at 2 01 58 pm](https://cloud.githubusercontent.com/assets/565251/20458712/c93686f0-ae60-11e6-819a-a53b2815e44b.png)

**Comment by garrettmoon** [comment]
I believe it's valid to setup a collectionView without a layout inspector, correct me if I'm wrong @Adlai-Holler ?

**Comment by Adlai-Holler** [comment]
The current layout inspector API requires a collection _view_. We can either modify the API to target collection _node_ or leave things as they are. Now that that assertion is removed and functionality is restored, we should focus on the rest of the 2.0 milestone and replace the layout inspector with a node-based async layout object afterwards.

**Comment by Adlai-Holler** [comment]
Phew. Finally done in #3003
