### ISSUE TITLE
[ASCellNode] didExitVisibleState is not called when a visible cell is deleted

### ISSUE THREAD

**Issue by flovouin** [facebook/AsyncDisplayKit#2658]
Hi guys,

I've had an issue for some time now. I recently upgraded to `master`, but the problem is still here: `didExistVisibleState` (and the previous visibility method for < 2.0) is not called on a visible `ASCellNode` when it is deleted using the `ASCollectionNode` (and previously `ASCollectionView`) method `deleteItemsAtIndexPaths`.
When scrolling, the visibility methods are called correctly. When presenting / pushing another controller, the behaviour is also correct. It only happens when deleting visible cells. Please note that no other data management method is called either (e.g. `clearFetchedData`). As the cell nodes in my application are pretty heavy, I would very much like to be notified when they are permanently deleted.

I made a simple test project that demonstrates the issue: https://github.com/flovouin/ASDK-CellVisibleState
Running the code should output in the console:
```
Adding lots of cells
Removing cells
Showing another controller
Goodbye from cell at index 0!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
```
The visibility method for the removed cells is only called once the whole collection disappears. I would expect the following output:
```
Adding lots of cells
Removing cells
Goodbye from cell at index 0!
Goodbye from cell at index 1!
Goodbye from cell at index 2!
Goodbye from cell at index 3!
Goodbye from cell at index 4!
Goodbye from cell at index 5!
Showing another controller
Goodbye from cell at index 0!
```

If you need anything else, don't hesitate to ask.

Cheers,

Flo

**Comment by appleguy** [comment]
@garrettmoon this seems very important to fix, because we rely on these calls for accurate logging.  This would probably be P1 if we had more time.

We may need to punt 2.0.1, but do you think we should spend an hour or two investigating a minimal fix before making this call?

**Comment by hannahmbanana** [comment]
ASRangeControllerLogging:

```
2016-11-27 15:07:18.623 VisibleStateTest[42768:1989050] <ASCollectionNode: 0x7f82b2e027b0> - visible: YES
Adding lots of cells
2016-11-27 15:07:25.345 VisibleStateTest[42768:1989050] Range update complete; modifiedIndexPaths: <ASRangeController: 0x60000009abd0>  allPreviousIndexPaths:
indexPath <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}, Visible: 1, Display: 1, Preload: 1
indexPath <NSIndexPath: 0xc000000000200016> {length = 2, path = 0 - 1}, Visible: 1, Display: 1, Preload: 1
indexPath <NSIndexPath: 0xc000000000400016> {length = 2, path = 0 - 2}, Visible: 1, Display: 1, Preload: 1
indexPath <NSIndexPath: 0xc000000000600016> {length = 2, path = 0 - 3}, Visible: 1, Display: 1, Preload: 1
indexPath <NSIndexPath: 0xc000000000800016> {length = 2, path = 0 - 4}, Visible: 1, Display: 1, Preload: 1
indexPath <NSIndexPath: 0xc000000000a00016> {length = 2, path = 0 - 5}, Visible: 1, Display: 1, Preload: 1
2016-11-27 15:07:25.347 VisibleStateTest[42768:1989050] Range update complete; modifiedIndexPaths: <ASRangeController: 0x60000009abd0>  allPreviousIndexPaths:
Removing cells
2016-11-27 15:07:27.322 VisibleStateTest[42768:1989050] Range update complete; modifiedIndexPaths: <ASRangeController: 0x60000009abd0>  allPreviousIndexPaths:
indexPath <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}, Visible: 1, Display: 1, Preload: 1
2016-11-27 15:07:27.624 VisibleStateTest[42768:1989050] Range update complete; modifiedIndexPaths: <ASRangeController: 0x60000009abd0>  allPreviousIndexPaths:
Showing another controller
2016-11-27 15:07:30.019 VisibleStateTest[42768:1989050] <ASCollectionNode: 0x7f82b2e027b0> - visible: NO
Goodbye from cell at index 0!
2016-11-27 15:07:30.019 VisibleStateTest[42768:1989050] Range update complete; modifiedIndexPaths: <ASRangeController: 0x60000009abd0>  allPreviousIndexPaths:
indexPath <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}, Visible: 0, Display: 1, Preload: 1
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection
```

**Comment by hannahmbanana** [comment]
![image](https://cloud.githubusercontent.com/assets/3419380/20653164/882668d4-b4bd-11e6-9e02-6ba9d667ac9b.png)

Weirdly, ASDisplayNode isn't hitting either the (1) dealloc method or (2) the dealloc while visible assertion.

**Comment by garrettmoon** [comment]
I think this will sadly need to be punted to 2.0.1

**Comment by flovouin** [comment]
Any workaround in the mean time? In my use case this bug implies not pausing / invalidating a `CADisplayLink`, which in turn keeps drawing on a `GLKView` that is no longer on screen, and decoding video frames. This results in a noticeable performance drop.

**Comment by garrettmoon** [comment]
@flovouin we pulled this out of the milestone (trying to be realistic about what we can get done), but it's actively being investigated!

**Comment by flovouin** [comment]
Thanks for the update, and good luck with the release! :-)

**Comment by garrettmoon** [comment]
Bummer, we're *almost* there, but because we don't understand the test case yet, it's going to have to go into 2.0.1

**Comment by Adlai-Holler** [comment]
Hey @flovouin unfortunately we've got to kick this back. Removing the view from the cell was a band-aid that we shouldn't roll with, and it caused other issues. There is a cluster of related table-cell-visibility issues (all linked to 2800 above) that I hope to solve our existing range controller architecture rather than depending on the hierarchy teardown to do it.

**Comment by flovouin** [comment]
Hi @Adlai-Holler 
Could you please update me on the status of this issue?
I tried both the test project mentioned above and my app with `master` and it seems that the problem is solved. #2805 also seems to indicate that this is no longer an issue.
Should I close this or are you still investigating related problems?
Anyways, thanks for fixing this, as `master` works like a charm for me :-)
Cheers,
Flo

**Comment by Adlai-Holler** [comment]
@flovouin Ah! Yeah the issue's fixed. Cheers mate!
