### ISSUE TITLE
Size of Visible Cell Node Does Not Update when Cell Size Changes

### ISSUE THREAD

**Issue by iwheelbuy** [facebook/AsyncDisplayKit#2659]
I have a custom layout which generate frames of different sizes!

<img width="100" alt="2016-11-26 0 27 02" src="https://cloud.githubusercontent.com/assets/2524584/20632307/25593da2-b36f-11e6-8c86-5f3ad75892bd.png">
<img width="100" alt="2016-11-26 0 27 24" src="https://cloud.githubusercontent.com/assets/2524584/20632309/289335ea-b36f-11e6-8fb1-a8bfff432bcf.png">
<img width="100" alt="2016-11-26 0 18 06" src="https://cloud.githubusercontent.com/assets/2524584/20632211/81a6adca-b36e-11e6-8a72-a343b8eca368.png">
<img width="100" alt="2016-11-26 0 25 38" src="https://cloud.githubusercontent.com/assets/2524584/20632280/e7a4a1d6-b36e-11e6-82a6-11b4ef8647dd.png">

That is the example collection view that has 1, 2, 3, 4... objects at start.
We can also add an object with (+) button. We add an object and update our collection with animation through batch update.

If we add one more object when there is only one object in collection
<img width="100" alt="2016-11-26 0 27 02" src="https://cloud.githubusercontent.com/assets/2524584/20632307/25593da2-b36f-11e6-8c86-5f3ad75892bd.png">
we expect the first cell to shrink from big size to small size. The new big one will go to a place where our previous big cell was situated. The shrinked object will move to a new place
<img width="100" alt="2016-11-26 0 27 24" src="https://cloud.githubusercontent.com/assets/2524584/20632309/289335ea-b36f-11e6-8fb1-a8bfff432bcf.png">
But the previous one doesn't change its frame and we see
<img width="100" alt="2016-11-26 0 37 40" src="https://cloud.githubusercontent.com/assets/2524584/20632500/94b78c16-b370-11e6-85ed-1b051bc16109.png">

I have implemented the `ASCollectionViewLayoutInspecting` protocol so I can see all the generated sizes.

```
extension SquareMosaicLayout: ASCollectionViewLayoutInspecting {
    
    func collectionView(_ collectionView: ASCollectionView, constrainedSizeForNodeAt indexPath: IndexPath) -> ASSizeRange {
        guard let layout = collectionView.collectionViewLayout as? SquareMosaicLayout else {
            return ASSizeRange(min: .zero, max: .zero)
        }
        debugPrint("--->", layout.size(indexPath))
        return ASSizeRange(min: .zero, max: layout.size(indexPath))
    }
    
    func scrollableDirections() -> ASScrollDirection {
        return ASScrollDirectionVerticalDirections
    }
}
```

But it turned out that it asks for the size only when the cell was first shown. So it doesn't ask for the updated size of the cell so that the cell can be shrinked...

**AsyncDisplayKit** '2.0-beta.2'
**Sample Project:** https://github.com/iwheelbuy/layout

P.S. I have a feeling that i miss something... Please, help me to figure it out

P.S. If you use `TripleSquareMosaicPattern` instead of `SnakeSquareMosaicPattern` in project it will show that nodes of same size do work correctly during animated updates

**Comment by iwheelbuy** [comment]
Hey, iwheelbuy, we have not time to look through your stupid code...

**Comment by Adlai-Holler** [comment]
Thanks for reporting this @iwheelbuy and providing the sample code. I'm still working through the issues we got over Christmas so bear with me! 

This is an issue that we should fix by setting `cellNode.frame = contentView.bounds; cellNode.autoresizingMask = .flexibleWidth, .flexibleHeight`. I'm testing a patch that does that, but it raises other interesting issues that I need to fix before landing.

**Comment by iwheelbuy** [comment]
Thanks for reply. Btw, sample code should be used from **master** branch
