### ISSUE TITLE
[ASLayoutTransition] ASDKLayoutTransition example broken when USE_CUSTOM_LAYOUT_TRANSITION = 1

### ISSUE THREAD

**Issue by garrettmoon** [facebook/AsyncDisplayKit#2663]
To reproduce, open the ASDKLayoutTransition example.
Change USE_CUSTOM_LAYOUT_TRANSITION to 1
Run the example and press 'Start Layout Transition'
The example will crash trying to access the first element in removedSubnodes of the layout context.

It appears that the example is using a flag to designate pre / post transition. I'm not sure if this is correct, but second stage layout is occurring *before* the post layout is created for animateLayoutTransition. This results in the pre and post layouts being the same and inserted / removed subsides being empty.

**Comment by maicki** [comment]
@garrettmoon Quick update on that. I already worked on that and will have a broader fix for layout transition in general (this will also fix this issue)

**Comment by garrettmoon** [comment]
@maicki Nice!

**Comment by maicki** [comment]
Should be fixed with #2657
