### ISSUE TITLE
Examples Build Issue

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#2665]
http://jenkinsmaster-vpc-007.ec2.pin220.com/job/AsyncDisplayKit/350/console

`xcodebuild: error: The workspace named "Sample" does not contain a scheme named "Sample". The "-list" option can be used to find the names of the schemes in the workspace.`

Could you take a look?

**Comment by hannahmbanana** [comment]
Fixed!
