### ISSUE TITLE
registerSupplementaryNodeOfKind: Error on CustomCollectionView example

### ISSUE THREAD

**Issue by gurhub** [facebook/AsyncDisplayKit#2666]
I use cocoapods to install few examples today, here i sharing my pod file for CustomCollectionView example : 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
target 'Sample' do
        pod 'AsyncDisplayKit'
end
```

I'm getting error in ViewController.m file at line 67 : 

`[_collectionNode registerSupplementaryNodeOfKind:UICollectionElementKindSectionHeader];`

Full Error message is : 

```
ARC Semantic Issue : /Users/****/AsyncDisplayKit/examples/CustomCollectionView/Sample/ViewController.m:67:20: 
No visible @interface for 'ASCollectionNode' declares the selector 'registerSupplementaryNodeOfKind:'
```

Few other examples not working for other reasons too..

Best regards.

**Comment by hannahmbanana** [comment]
@gurhub - This is most likely the same issue as #2667. :)

**Comment by gurhub** [comment]
Thank you @hannahmbanana, I'll follow that. FYI, I'm getting same error in many other examples. Probably all will be fixed with 1 simple fix :)
