### ISSUE TITLE
ARC semantic issue in ASCollectionView example

### ISSUE THREAD

**Issue by gurhub** [facebook/AsyncDisplayKit#2668]
here is the error message in ViewController at line 63 :

`/Users/g/***/AsyncDisplayKit/examples/ASCollectionView/Sample/ViewController.m:62:24: No visible @interface for 'ASCollectionNode' declares the selector 'registerSupplementaryNodeOfKind:'`

here is my pod file : 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
target 'Sample' do
        pod 'AsyncDisplayKit'
end
```

**Comment by Adlai-Holler** [comment]
This appears to be the same issue as #2667 , let's keep digging in over there.

**Comment by gurhub** [comment]
Thank you @Adlai-Holler, I'll follow that.
