### ISSUE TITLE
[Layout Transition] When creating a new node in layoutSpecThatFits:, an animated transition may crash if no reference held to it.

### ISSUE THREAD

**Issue by ay8s** [facebook/AsyncDisplayKit#2673]
While not recommended if you setup a node within layoutSpecThatFits: within a ASTableNode ASCellNode the project with crash with an assertion ('A flattened layout must consist exclusively of node sublayouts').

Removing the ASImageNode within the Sample to be setup before layoutSpecThatFits: resolves the issue. Other cases where this may be done is with hairline separators within cell nodes.

Scott suggested a relatively small change like making a strong retain in one of the transition objects should fix this up.

Sample Project: https://cl.ly/3m3p07361V2Z

**Comment by garrettmoon** [comment]
We have a good idea for fixing this, but it's not going to make 2.0, moving to 2.0.1
