### ISSUE TITLE
ASCollectionView nodes not rendering when nested in ASTableView nodes

### ISSUE THREAD

**Issue by ryanfitz** [facebook/AsyncDisplayKit#271]
I have an `ASTableView` where each row's node contains an `ASCollectionView`. The collection view is using a horizontal scroll layout, where each cell node contains an `ASNetworkImageNode`. 

Initially when scrolling vertically through the different table rows, the collection view nodes render as expected. When scrolling back to previously seen rows the image nodes in the collection view don't always appear. However, if I attempt to horizontally scroll on the collection view that isn't appearing, the images will immediately display. 

Right now I've only tested this setup with 25 rows, with each collection view has somewhere between 2 - 5 image nodes. With this setup it usually happens on about 2 or 3 out of the 25 rows.

**Comment by secretiverhyme** [comment]
ASCollectionView and ASTableView are intended to bridge the view → node gap, but right now they don't work correctly when nested.  We're tracking this in #133.
