### ISSUE TITLE
[Images] Open-source pi_imageNamed: as asdk_imageNamed:

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2717]
imageNamed is still very slow on UIImage and has a variety of problems.  It's annoying for individual developers to work around this.

Let's expose a new asdk_imageNamed: method to implement the caching behavior we use in Pinterest.

This is not urgent and would be fine to punt from 2.0.1, but it would be a small change and a nice win for our community.

**Comment by hannahmbanana** [comment]
Resolved by #2859
