### ISSUE TITLE
Documentation for ASRatioLayoutSpec has display issues.

### ISSUE THREAD

**Issue by jeffdav** [facebook/AsyncDisplayKit#2730]
My guess is the ascii art is wreaking havoc with whatever markup engine you're using.

http://asyncdisplaykit.org/appledoc/Classes/ASRatioLayoutSpec.html

<img width="959" alt="screen shot 2016-12-07 at 4 51 48 pm" src="https://cloud.githubusercontent.com/assets/2266946/20993192/7e22507c-bc9d-11e6-9f05-49104de53f97.png">

**Comment by hannahmbanana** [comment]
Moving this issue to our documentation repo. Thanks for reporting this! 

https://github.com/AsyncDisplayKit/Documentation/issues/40
