### ISSUE TITLE
Using with Firebase 

### ISSUE THREAD

**Issue by jennibunny** [facebook/AsyncDisplayKit#2737]
I have a quick question. 
Is it possible to use asyncDisplayKit with the Firebase? 
Waiting for your answer.

**Comment by smyrgl** [comment]
So I accidentally had firebase added to my code (reference to an old GoogleLogin pod brought it in before I could kill it) and yes it is possible but it crashes unless you set FirebaseAutomaticScreenReportingEnabled=FALSE in your info.plist.

**Comment by ArEnSc** [comment]
@jennibunny as far as I remember firebase is a paas, library that has sync built in, where as async displaykit is a front end iOS framework. How I would approach this is to startoff using UIKit then slowly replace UIKit with Async Display Kit. If you run into problems let us know =)

**Comment by ay8s** [comment]
Started a Swift project over the weekend using ASDK and Firebase and had no troubles at all with using the two together @jennibunny.

**Comment by hannahmbanana** [comment]
Thanks everyone for the crowd sourced answers!
