### ISSUE TITLE
[ASCollectionNode] Insert new cell cause freeze of Main thread.

### ISSUE THREAD

**Issue by novacom34** [facebook/AsyncDisplayKit#2739]
Hi to all.
I'm trying to insert new cell to collection node and after this operation, Main thread freezes. During code investigation I noticed that issue happens after the cell is received notification about image status: Image downloaded. Image loading are processing in ImageModel  method  -(void)performLoading{}.
This issue happened only in case I'm inserting new row. (insertRowAtIndexPath).

This is a simple project that demonstrates this issue. https://github.com/novacom34/AsyncDisplayKitBUG
Uncomment line 52 ImageModel and all works fine.
Why main thread freezes ?

**Comment by EviluS** [comment]
@novacom34 Is there a reason you are downloading/loading images manually and not using `ASNetworkImageNode`'s automatic downloading and caching?

**Comment by hannahmbanana** [comment]
@novacom34 - were you able to make any progress on your issue?

**Comment by hannahmbanana** [comment]
@novacom34 - Given the length of time since this issue was active, I'm going to close it. Feel free to re-open the issue or create another if the problem arises again. Thanks!
