### ISSUE TITLE
Social App Layout: flexGrow does not propagate upwards as advertised

### ISSUE THREAD

**Issue by plm75** [facebook/AsyncDisplayKit#2741]
In the Social App Layout example app, it says in the layoutSpecThatFits section:

    // NOTE: This inset is not actually required by the layout, but is an example of the upward propogation of layoutable
    // properties.  Specifically, .flexGrow from the child is transferred to the inset spec so they can expand together.
    // Without this capability, it would be required to set insetSpacer.flexGrow = 1.0;

However, this is not the case.  When running the app, the space between the `usernameNode` and the `viaNode/timeNode` does not expand.

To achieve the expected behaviour, one must add `insetSpacer.style.flexGrow = 1.0`, which means that the spacer's flexGrow property is not correctly propagated to its containing layoutSpec.

**Comment by maicki** [comment]
@plm75 Yes, currently propagation is not supported. We will remove this comment. Thanks!

**Comment by plm75** [comment]
In the same section, I guess the following line should also be simplified ? (ternary operation is never false)

```
 if (_mediaNode.image != nil) {
            CGFloat imageRatio = (_mediaNode.image != nil ? _mediaNode.image.size.height / _mediaNode.image.size.width : 0.5);
```
