### ISSUE TITLE
[ASBackgroundLayoutSpec] Fix to not allow a nil node

### ISSUE THREAD

**Issue by master-nevi** [facebook/AsyncDisplayKit#2747]
Running into this assertion https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Layout/ASLayoutSpec+Subclasses.mm#L101 when setting nil as the background element in an ASBackgroundLayoutSpec. 

The documentation says background is allowed to be nil: https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.h#L29

I assume `ASOverlayLayoutSpec` has the same issue.

If the background element shouldn't be nil, the method signature should be updated to take in only nonnull values for background and the initializer should also assert from receiving a nil value same as the child param.

**Comment by hannahmbanana** [comment]
What's the use case for an ASBackgroundLayoutSpec with a nil background? I wonder if this was before the days of `ASWrapperLayoutSpec`.

**Comment by master-nevi** [comment]
For us it was just convenience. The background layout was coming from a method that returned a nullable node depending on whether there should be a background or not. From the discussion on the slack channel this may be an outdated feature. Since then I've patch my end to only create a background spec when there's actually a background node present.

**Comment by master-nevi** [comment]
Say the word and I can open a PR for this change: https://github.com/facebook/AsyncDisplayKit/compare/master...master-nevi:dr/nonnull-background-overlay?expand=1

**Comment by hannahmbanana** [comment]
@maicki is the expert in this area, so I'll defer to his judgement on whether this functionality should exist.

**Comment by maicki** [comment]
I think we should  change the documentation and not allow a nil node for the background node. I don't see any situation when you want to have this situation.

**Comment by hannahmbanana** [comment]
@maicki - I agree with your call.

**Comment by hannahmbanana** [comment]
@master-nevi - thanks for pointing out this inconsistency! We decided to remove the legacy functionality.

**Comment by master-nevi** [comment]
Your welcome @hannahmbanana ! Glad I could help.
