### ISSUE TITLE
Error when migrate to ASDK 2.0

### ISSUE THREAD

**Issue by minhthuc251** [facebook/AsyncDisplayKit#2748]
I have an error when migrate from 1.9.92 to 2.0. But i dont know how to debug and fix it.
![screen shot 2016-12-10 at 5 22 58 pm 2](https://cloud.githubusercontent.com/assets/5000594/21072691/90682a38-befd-11e6-8a40-75435bf1ad80.png)

**Comment by 8ofproject** [comment]
@minhthuc251 can you copy-paste full log of errors from the console log along with **constrainedSize** property values?

**Comment by hannahmbanana** [comment]
@minhthuc251 - were you able to resolve this issue? 

For more information on the 2.0 Layout changes, see the "Deprecation of -[ASLayoutElement measureWithSizeRange:]" section of the [Upgrading to ASDK Layout 2.0 Guide](http://asyncdisplaykit.org/docs/layout2-conversion-guide.html).

**Comment by hannahmbanana** [comment]
@minhthuc251 - Due to the length of time that has passed since this issue was active, I'm going to close this. Please re-open if you are still having issues. I hope you've enjoyed the framework.
