### ISSUE TITLE
Setting ASNetworkImageNodeDelegate after setting URL causing images to not load

### ISSUE THREAD

**Issue by ryanfitz** [facebook/AsyncDisplayKit#2749]
I'm working on migrating to 2.0 and found an issue where setting the delegate on an `ASNetworkImageNode` after setting the URL intermittently causes images to not load. I have an `ASCollectionNode`, where each cell node contains a `ASNetworkImageNode`. On iPhone I have no issues with image loading, however, on iPad I experience issues. I found that once I set the delegate property before setting the url then all image loading works as expected.

**Comment by maicki** [comment]
@ryanfitz This an be the case if you trigger a re-display / re-layout in the delegate method and the image is already cached the delegate method will be called before you actually set the delegate. We could push this to the next runloop and expect the delegate will be set than.

@garrettmoon Thoughts?

**Comment by garrettmoon** [comment]
@ryanfitz can you tell us exactly what you're doing in the delegate callbacks?

**Comment by ryanfitz** [comment]
@garrettmoon I actually removed all logic in my delegate methods and still experienced this issue.  Here is what my delegate was doing:

```swift
 func imageNode(imageNode: ASNetworkImageNode, didLoadImage image: UIImage) {
    let transition = CATransition()
    transition.duration = 0.25
    transition.timingFunction = CAMediaTimingFunction(name: kCAMediaTimingFunctionEaseInEaseOut)
    transition.type = kCATransitionFade
    imageNode.layer.addAnimation(transition, forKey: "fadingTransition")
    imageNode.layer.opacity = 1
  }
```

**Comment by garrettmoon** [comment]
You still experienced the issue without doing anything in your delegate methods? That's pretty strange and would indicate some kind of race condition because the delegate methods don't affect the behavior of the network image node as far as I can tell. Would you be willing to put up a sample project?

**Comment by garrettmoon** [comment]
I'm going to close this since there's been no response.
