### ISSUE TITLE
Documentation inaccuracy

### ISSUE THREAD

**Issue by haritowa** [facebook/AsyncDisplayKit#2750]
Documentation have some problems with code examples(mostly swift examples absence):

- [x] http://asyncdisplaykit.org/docs/subclassing.html ASViewController section, sample code doesn’t have syntax highlighting & swift example
- [x] http://asyncdisplaykit.org/docs/control-node.html none example have swift version
- [x] http://asyncdisplaykit.org/docs/editable-text-node.html ASEditableTextNode Delegate examples
- [x] http://asyncdisplaykit.org/docs/layout-api-sizing.html syntax highlighting & swift version
- [x] http://asyncdisplaykit.org/docs/layout-transition-api.html swift version
- [x] http://asyncdisplaykit.org/docs/batch-fetching-api.html  next page link is broken
- [ ] http://asyncdisplaykit.org/docs/automatic-subnode-mgmt.html swift version
- [x] http://asyncdisplaykit.org/docs/debug-tool-hit-test-visualization.html http://asyncdisplaykit.org/docs/debug-tool-pixel-scaling.html http://asyncdisplaykit.org/docs/debug-tool-ASRangeController.html  usage instruction code sample don’t have syntax highlighting (DONE) & swift version
- [x] http://asyncdisplaykit.org/docs/automatic-layout-containers.html image too big

**Comment by appleguy** [comment]
@hannahmbanana can you please prioritize all of these fixes except the Swift examples, and then we can prioritize the Swift examples in a bigger sweep?

Go ahead and edit the post so it has checkboxes :)

**Comment by haritowa** [comment]
As far as i understand
> http://asyncdisplaykit.org/docs/batch-fetching-api.html next page link is broken
is fixed

**Comment by hannahmbanana** [comment]
@haritowa - would you be willing to put checkmarks next to the tasks that you completed so we can see which ones remain? Thanks!

**Comment by haritowa** [comment]
@hannahmbanana as soon as PR will be reviewed :)

**Comment by hannahmbanana** [comment]
@haritowa - I merged your PR. Thank you so much!

**Comment by haritowa** [comment]
@hannahmbanana cool, that PR contains layout fixes for http://asyncdisplaykit.org/docs/automatic-layout-containers.html too, so "image too big" fixed too

**Comment by hannahmbanana** [comment]
@haritowa - Great, thanks! Looks like one task remains.

**Comment by hannahmbanana** [comment]
Moved the one remaining task to the Documentation repo: AsyncDisplayKit/Documentation/issues/81
