### ISSUE TITLE
[ASDimension] Public header has a lot of definitions around ASLayoutElementSize (internal-only)

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2752]
ASDimension.h is a much longer header than it should be for such a core, simple type.  At the least, we should move down any less-crucial definitions below the basics.  I'd say these are the basics, along with a few of their helper functions:

```
typedef NS_ENUM(NSInteger, ASDimensionUnit) {
  /** This indicates "I have no opinion" and may be resolved in whatever way makes most sense given the circumstances. */
  ASDimensionUnitAuto,
  /** Just a number. It will always resolve to exactly this amount. This is the default type. */
  ASDimensionUnitPoints,
  /** Multiplied to a provided parent amount to resolve a final amount. */
  ASDimensionUnitFraction,
};

typedef struct {
  ASDimensionUnit unit;
  CGFloat value;
} ASDimension;

/**
 * Expresses an inclusive range of sizes. Used to provide a simple constraint to layout.
 */
typedef struct {
  CGSize min;
  CGSize max;
} ASSizeRange;
```

But then, even before you get to a function about how to create any of these, we also see the much larger ASLayoutElementSize.  This is a very elegant struct and works ideally for internal purposes for now, but shouldn't be exposed yet, particularly because we don't have good documentation for what it's for.

```
/**
 * A struct specifying a ASLayoutElement's size. Example:
 *
 *  ASLayoutElementSize size = (ASLayoutElementSize){
 *    .width = ASDimensionMakeWithFraction(0.25),
 *    .maxWidth = ASDimensionMakeWithPoints(200),
 *    .minHeight = ASDimensionMakeWithFraction(0.50)
 *  };
 *
 *  Description: <ASLayoutElementSize: exact={25%, Auto}, min={Auto, 50%}, max={200pt, Auto}>
 *
 */
typedef struct {
  ASDimension width;
  ASDimension height;
  ASDimension minWidth;
  ASDimension maxWidth;
  ASDimension minHeight;
  ASDimension maxHeight;
} ASLayoutElementSize;
```

Lastly, these methods at the top are unclear in their differences.  one uses CGFLOAT and the other FLT, but it's unclear what the practical differences are of that, especially from names that are only Size vs Layout.  They are currently the very first thing listed in the header, which also seems a bit too prominent for these declarations, but if they were reduced to 2 (and should be) -- then keeping them relatively prominent somewhere in the file is worthwhile to encourage their usage.

```
ASDISPLAYNODE_INLINE BOOL AS_WARN_UNUSED_RESULT ASPointsValidForLayout(CGFloat points)
{
  return ((isnormal(points) || points == 0.0) && points >= 0.0 && points < (CGFLOAT_MAX / 2.0));
}

ASDISPLAYNODE_INLINE BOOL AS_WARN_UNUSED_RESULT ASIsCGSizeValidForLayout(CGSize size)
{
  return (ASPointsValidForLayout(size.width) && ASPointsValidForLayout(size.height));
}

ASDISPLAYNODE_INLINE BOOL AS_WARN_UNUSED_RESULT ASPointsValidForSize(CGFloat points)
{
  return ((isnormal(points) || points == 0.0) && points >= 0.0 && points < (FLT_MAX / 2.0));
}

ASDISPLAYNODE_INLINE BOOL AS_WARN_UNUSED_RESULT ASIsCGSizeValidForSize(CGSize size)
{
  return (ASPointsValidForSize(size.width) && ASPointsValidForSize(size.height));

```}

**Comment by appleguy** [comment]
@nguyenhuy @garrettmoon I put this in 2.0.1 because it shouldn't take long to make an improvement in this header, and it's one of our very most important ones.  However, *please punt this issue* if there is any concern about the 2.0.1 schedule and another specific task has to take its place.

Especially with how many people are trying out layout specs for the first time with 2.0, we should prioritize any small improvements we can make to keep the API accessible.  Have a read over the current ASDimension.h from the perspective of a new external dev and weigh in here with any ideas on how we should refine it.

**Comment by maicki** [comment]
@appleguy Give #2794 a look

**Comment by appleguy** [comment]
@maicki very thankful for you taking this on for me!  I missed my expected deadline for this task so you saved it for 2.0.1 :).

**Comment by garrettmoon** [comment]
Since @maicki is sick, this has to be punted :(
