### ISSUE TITLE
Some images are lower resolution (recent regression)

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2756]
In Pinterest, when in Closeup using latest ASDK master, some images are lower resolution.  It reproduces 100%.

@garrettmoon to investigate.

**Comment by appleguy** [comment]
It is conceivable this is related to:

"Hey guys, I was on `4355f4d` and tried upgrading to `2.0`, but it looks like https://github.com/facebook/AsyncDisplayKit/commit/5b80a641afae4cee6dcf0e4cf5a829dffeb1e8d6 messes with `UIView drawViewHierarchyInRect` and turns my view screenshots to black. (edited)

[12:07]  
(As I am only 3 commits away from `2.0`, one being only comments, and one being an example project, `5b80a6` looks like the ideal suspect)
"

**Comment by garrettmoon** [comment]
Welp! Turns out it wasn't ASDK after all!

**Comment by garrettmoon** [comment]
Ok, turns out it was us *and* ASDK.
