### ISSUE TITLE
[Possible Regression] Preloading of next-up view in ASPagerNode isn't working on latest version.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2757]
See this Pinterest bug for details.  Adlai offered to investigate -- we may need to punt another issue from 2.0.1 to make space, but this one is important. https://jira.pinadmin.com/browse/CXIOS-921

**Comment by Adlai-Holler** [comment]
I've confirmed the preloading behavior is working correctly (modulo #2825) and modified the Pinterest code in https://phabricator.pinadmin.com/D141264, and the preloading is working reliably! Tested on iPod touch 5G and iPad 3 😱
