### ISSUE TITLE
ASButton not displays the title

### ISSUE THREAD

**Issue by Luccifer** [facebook/AsyncDisplayKit#2758]
Hello! 
I am using the cocoapods version of ASDK

- ASViewController with ASDisplayNode as  #init is using

```
    private var viewNode: ASDisplayNode?
    private var downloadButton: ASButtonNode?
    
    init(){
        self.viewNode = ASDisplayNode()
        super.init(node: viewNode!)
 
        self.downloadButton = ASButtonNode()
    }

override internal func viewDidLoad() {
        super.viewDidLoad()
        self.viewNode?.addSubnode(self.downloadButton!)
        self.makeConstraints()
    }

override func viewWillAppear(_ animated: Bool) {
super.viewWillAppear(true)
        self.downloadButton?.layoutThatFits(ASSizeRange(min: CGSize(width: 160.0, height: 40.0) , max: CGSize(width: 160.0, height: 40.0)))
        self.downloadButton?.setAttributedTitle(buttonTitle, for: .highlighted)
//        self.downloadButton?.titleNode.attributedText = buttonTitle
//        self.downloadButton?.titleNode.frame = CGRect(x: 0, y: 0, width: 160, height: 40)
//        self.downloadButton?.addSubnode(self.downloadButton!.titleNode)
        self.downloadButton?.contentVerticalAlignment = .alignmentCenter
        self.downloadButton?.contentHorizontalAlignment = .alignmentMiddle
}
```

Actually when uncommenting lines the title is shown, I tried to play with many variations of titleNode, attributedText, setTitle, etc.. Nothing else worked...

The measure method deprecated... I tried to use layoutThatFits... What is wrong? Why so difficult to make a simple title?
![screen shot 2016-12-13 at 02 15 27](https://cloud.githubusercontent.com/assets/1053009/21120777/0e94069c-c0da-11e6-9904-d2eb208f3a8b.png)

**Comment by EviluS** [comment]
@Luccifer I have recreated your case and I noticed few issues.

- move your setup code from `viewWillAppear` to the `init` method or in the `viewDidLoad`
- override the `viewWillLayoutSubviews` or `viewDidLayoutSubviews` method
- in one of them create a `CGRect` and set its `size` property from the button's already `calculatedSize`
- set the `frame` of the button

**Comment by Luccifer** [comment]
@EviluS, Thanks for your clues!
There is no normal state for ASControlState..
![screen shot 2016-12-16 at 17 05 00](https://cloud.githubusercontent.com/assets/1053009/21265287/cc336ca4-c3b1-11e6-9b32-c1bdd7610c41.png)

Then I tried to make viewWillLayoutSubviews with new rect and moved code to viewDidLoad.. Nothing worked

**Comment by EviluS** [comment]
@Luccifer Strange, there should be `normal` state. Try setting `0` since `ASControlStateNormal       = 0,` if Swift allows setting integer values in that argument.

**Comment by Luccifer** [comment]
ASControlState.init(rawValue: 0) actually helped me, thanks for the clue! 
Now its worked1

**Comment by EviluS** [comment]
@Luccifer Happy to hear that. The problem was that there is actually a title but not for the current state and that was the reason for not showing anything.

**Comment by maicki** [comment]
@Luccifer @EviluS Awesome @EviluS, it seems like you helped out @Luccifer and the issue seems like to be fixed? I will close the issue for now, please reopen if it's not fully resolved.
