### ISSUE TITLE
[ASViewController] Add unit test or sample app that uses an ASVC without self.node, using .view manually.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2760]
Because Objective-C and Swift only support Single Inheritance, it's critical that ASViewController can be used as a BASE class in apps that have only partial usage of ASDK.

Most apps have some base VC class, like PIBaseViewController, so the only way to adopt ASVC is to make their base VC inherit from it.  This means that it is crucial that ASVC work with:

-initWithCoder / nib
-manual / regular usage of the .view property

This should be possibly to achieve by simply gating any ASVC behaviors to do nothing at all if self.node == nil.  Then we should make sure the documentation highlights that this is safe and supported.

**Comment by hannahmbanana** [comment]
@appleguy @nguyenhuy - closing this issue since Huy has a PR up.
