### ISSUE TITLE
UIAXDelegateClearer Deallocating Off-Main Causes Crash in Production

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2767]
This is necessary, because in addition to ivars, associated objects may also reference UIKit or other non-threadsafe object types.

E.g.:

https://fabric.io/pinterest6/ios/apps/pinterest/issues/5761fc0bffcdc042505bed8d/sessions/a7874f480ee94e9280789970aa097999_69c983cec93d43df944ccea216356c5e_0_v1

![pasted image at 2016_12_13 06_26 pm](https://cloud.githubusercontent.com/assets/565251/21167587/599066b2-c162-11e6-8877-18c92f3c70f3.png)

**Comment by Adlai-Holler** [comment]
Assigning to @nguyenhuy since he is investigating the best approach.

**Comment by appleguy** [comment]
```
Object registering association:
<PISearchAutoCompleteNode: 0x1602e4e20; frameInWindow = (0 84; 414 652); frame = (0 84; 414 652); interfaceState = { MeasureLayout | Preload | Display | Visible }; view = <_ASDisplayView: 0x15efa6aa0>>

Key being used to register:
(unsigned long) $3457 = 3438913594744559001
<UIAXDelegateClearer: 0x170e27c60>

```

**Comment by Adlai-Holler** [comment]
Since there's no way to scan associated objects, I've retitled this issue to limit the scope.
