### ISSUE TITLE
`infoCompletion` callback not invoked for animated gifs in ASDK 2.0.

### ISSUE THREAD

**Issue by jeffdav** [facebook/AsyncDisplayKit#2790]
Here is a link to a small sample app that reproduces the issue: https://github.com/jeffdav/ASDKTestApp/tree/animated-gif-bug

Here is the meat of the code:
```
- (instancetype)initWithURL:(NSString *)url {
  if (self = [super init]) {
    CGFloat ratio = 0.666666666666667;
    self.ratio = ratio;

    ASNetworkImageNode *imageNode = [[ASNetworkImageNode alloc] init];

    self.imageNode = imageNode;
    self.imageNode.URL = [NSURL URLWithString:url];
    self.imageNode.shouldCacheImage = NO;
    self.imageNode.layerBacked = YES;
    self.imageNode.zPosition = 1;
    self.imageNode.delegate = self;  // <-- If you comment out this line, animated GIF still doesn't load.
    self.imageNode.style.width = ASDimensionMakeWithFraction(1.0);

    self.automaticallyManagesSubnodes = YES;
  }
  return self;
}

- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {
  ASRatioLayoutSpec *imageLayoutSpec = [ASRatioLayoutSpec ratioLayoutSpecWithRatio:self.ratio child:self.imageNode];
  imageLayoutSpec.style.width = ASDimensionMakeWithFraction(1.0);
  return imageLayoutSpec;
}

- (void)imageNode:(ASNetworkImageNode *)imageNode didLoadImage:(UIImage *)image {
  if (image) {
    self.ratio = image.size.height / image.size.width;
    [self.imageNode setNeedsLayout];
  } else if (imageNode.animatedImage) {
    if (imageNode.animatedImage.coverImageReady) {
      image = imageNode.animatedImage.coverImage;
      self.ratio = image.size.height / image.size.width;
      [self.imageNode setNeedsLayout];
    } else if ([imageNode.animatedImage isKindOfClass:[PINAnimatedImage class]]) {
      PINAnimatedImage *animatedImage = (PINAnimatedImage *)imageNode.animatedImage;
      animatedImage.infoCompletion = ^(PINImage *coverImage) {
        self.ratio = coverImage.size.height / coverImage.size.width;  // <-- This callback never invoked.
        [self.imageNode setNeedsLayout];
      };
    }
  }
```

Even with this simple layout, I cannot get animated gifs to load whether or not I use the `infoCompletion` callback or just hardcode the aspect ratio.  

Nor do I get the `infoCompletion` callback.

**Comment by jeffdav** [comment]
I'm not sure if https://github.com/facebook/AsyncDisplayKit/issues/2769 is related.

**Comment by xiaomaogong** [comment]
@jeffdav How did you solve the gif overlap issue in old version of ASDK? 
I mean if the gif is not the same ratio as the frame of ASNetworkImageNode , the gif will overlap the image node. Or you just kept the same ratios?

**Comment by jeffdav** [comment]
What is the overlap issue?  If I overlay a frame I put them both in the same aspect ratio layout spec.  I worked around an issue with inset specs by wrapping the gif in a wrapper node with clips to bounds set (and having the same ratio).  But that's all irrelevant to this issue.

**Comment by xiaomaogong** [comment]
@jeffdav So in your case , you will have dynamic height for both normal image and gif that wrapped by an ASNetworkImageNode?
My case is that having fixed height for the image and gif . The normal image clipped correctly but the gif will overflow the wrapper node.
So looks like i can only solve this overflow issue with the way like you did?

**Comment by jeffdav** [comment]
Yes.  The actual images are arbitrary size.  I scale them to 100% width of the screen and maintain aspect ratio.  I'm not certain.  You may try asking about layout issues in the slack.

**Comment by maundytime** [comment]
@jeffdav did you fix this problem? My gif doesn't load too.

**Comment by jeffdav** [comment]
The issue persists.

**Comment by garrettmoon** [comment]
Hey @jeffdav GIFs are sadly broken in 2.0 :( However the issue has been fixed in PINRemoteImage master. As soon as I'm able I'll be pushing a new release of both PINRemoteImage and ASDK to fix this.

**Comment by xiaomaogong** [comment]
@garrettmoon  , any idea when we can get the fixed release version?
