### ISSUE TITLE
ASScrollNode doesn't get visibility events

### ISSUE THREAD

**Issue by hannahmbanana** [facebook/AsyncDisplayKit#2791]
Scott: "the reason for this is that the view of the node is a UIScrollView and not an _ASDisplayView.  That's the case even though the +layerClass is specially overridden to provide _ASDisplayLayer, but the _ASDisplayView is apparently the only thing driving the visibility callbacks.

[thinks for a bit] :)

I think the right fix is to make ASScrollNode behave as though it were a layer-backed node inside ASDisplayNode.  There is a way that layerBacked nodes work with this, which is the CALayer "actionForKey:" orderIn/orderOut calls."

**Comment by hannahmbanana** [comment]
I'm not sure how much of the view hierarchy is necessary, but here's a small chunk of it:

```
<UIViewControllerWrapperView: 0x7f844af9fe70; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x608000630f60>>
   |    |    |    |    |    |    |    | <ASScrollView: 0x7f844b112000; baseClass = UIScrollView; frame = (0 0; 375 667); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x6000008436f0>; layer = <PIAddressFormNode-Layer: 0x600000158aa0; node = <PIAddressFormNode: 0x7f8452b183e0>>; contentOffset: {0, -84}; contentSize: {375, 609}>
   |    |    |    |    |    |    |    |    | <PIFormTextFieldNode-View: 0x7f844acfb870; node = <PIFormTextFieldNode: 0x7f844ace4390>; frame = (0 0; 375 62)>
   |    |    |    |    |    |    |    |    |    | <PITextNode-View: 0x7f844d3cfb90; node = <PITextNode: 0x7f844b2e4200; text = "First name">; frame = (20 8; 340 16.5); userInteractionEnabled = NO>
   |    |    |    |    |    |    |    |    |    | <PITextField: 0x7f844ace5dc0; baseClass = UITextField; frame = (20 28.5; 340 25.5); text = 'Hannah'; opaque = NO; gestureRecognizers = <NSArray: 0x618000658c30>; layer = <CALayer: 0x60000062c340>>
   |    |    |    |    |    |    |    |    |    |    | <UITextFieldLabel: 0x7f844ace66b0; frame = (0 0; 340 25.5); text = 'Hannah'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x60000089c520>>
```

It's a stack of nodes in a ASScrollNode subclass. Its subnodes receive the `-didEnterVisible` call, but the ASScrollNode subclass does not.

**Comment by hannahmbanana** [comment]
If anybody else runs into this, the workaround I'm using for now is to manually call `-didEnterVisibleState` on the scrollNode in `ASViewController`'s `-viewWillAppear:`

```
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
 
    // note that this is a workaround for the fact that visibility calls do not work on
    // ASScrollNode currently https://github.com/facebook/AsyncDisplayKit/issues/2791
    [self.node didEnterVisibleState];
}
```

**Comment by hannahmbanana** [comment]
Not sure if this is 2.1 or 2.0.1 - but I'll leave it here until @garrettmoon makes a call on it. :)

**Comment by garrettmoon** [comment]
Too late for 2.0.1 but we should definitely investigate for 2.0.2

**Comment by hannahmbanana** [comment]
Thanks to @nguyenhuy for resolving this in #2799!
