### ISSUE TITLE
Range Controller Should Default to Down/Right Before User Scrolls

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#2806]
Currently the logic inside `ASDirectionalScreenfulBufferVertical` means that if the user isn't scrolling, we will point the leading range upward which is wacky.

What we would do ideally is to use the "last-known scroll direction" for the user, with a default of down/right, so that ranges point in the same direction until the user actually scrolls in some other direction.

**Comment by hannahmbanana** [comment]
@garrettmoon - when this syncs to Pinterest, could you let Bill know? Thanks!
