### ISSUE TITLE
Add ability to 'assert' in production

### ISSUE THREAD

**Issue by garrettmoon** [facebook/AsyncDisplayKit#2807]
Currently there are cases where we assert in debug and avoid crashing in production, however, this can lead to losing visibility on issues such as layout (see #2773). As @appleguy has suggested, we could have the ability to, in certain cases, offer the developer the ability to crash in production or produce some logging for the developer to pipe the failure somewhere, i.e. +[ASDisplayNode setNonfatalHandlerBlock:].

**Comment by garrettmoon** [comment]
Marking this as a P2 because I think there's significant value to tooling such as this and it will allow us to more confidently avoid crashing in production for the default case.

**Comment by rmls** [comment]
@garrettmoon I think we can close this issue now.

**Comment by maicki** [comment]
@rmls Awesome work on that! Will close.
