### ISSUE TITLE
how to use the ASCollectionView  ?

### ISSUE THREAD

**Issue by KimBin** [facebook/AsyncDisplayKit#281]
our preject use the collectionView before, now we want to change the collecionView to ASCollectionView. i want to ask how to use the
" - (ASCellNode *)collectionView:(ASCollectionView *)collectionView nodeForItemAtIndexPath:(NSIndexPath *)indexPath "  method  

thanks very much

**Comment by KimBin** [comment]
i also want to ask is there  a demo of ASCollectionView which written by Objective-C .  thanks very much

**Comment by tanliboy** [comment]
There is a demo project in examples/ASCollectionView.

**Comment by KimBin** [comment]
thanks secretivehyme   , i am in china ,the  url "http://asyncdisplaykit.org/guide/" i can't open, and i try many method to open it, but failue.  is there also way to look the guide?

**Comment by rnystrom** [comment]
@KimBin You can view the markdown files of the guide [here](https://github.com/facebook/AsyncDisplayKit/tree/master/docs/guide) which are the same thing on the site. Hope that helps!
