### ISSUE TITLE
performBatchAnimated + device orientation

### ISSUE THREAD

**Issue by stephenkopylov** [facebook/AsyncDisplayKit#2811]
Sometimes my app crashes with: 
> Node should always be marked invisible before deallocating.

It happens when I do a lot of batch updates (for example every second) and rotate the device.

Sample code:
``` objectiveC
[self.tableNode performBatchAnimated:YES updates:^{
                [self.tableNode deleteRowsAtIndexPaths:[change deletionsInSection:0] withRowAnimation:UITableViewRowAnimationFade];
                
                [self.tableNode insertRowsAtIndexPaths:[change insertionsInSection:0] withRowAnimation:UITableViewRowAnimationFade];
                
                [self.tableNode reloadRowsAtIndexPaths:[change modificationsInSection:0] withRowAnimation:UITableViewRowAnimationNone];
            } completion:nil];
```

In ASDK 1.9.x batch updates between beginUpdates and endUpdates have worked well for me.

**Comment by garrettmoon** [comment]
@Adlai-Holler should this be fixed by #2805?

**Comment by hannahmbanana** [comment]
Also potentially #2815?

**Comment by Adlai-Holler** [comment]
@stephenkopylov Feel free to reopen this if you're still seeing it in latest!
