### ISSUE TITLE
Bug: setting cornerRadius on ASEditableTextNode has no visible result with a backgroundColor

### ISSUE THREAD

**Issue by aaronash** [facebook/AsyncDisplayKit#2822]
Hey, first bug report from me for ASDK, please let me know if I should do any style/formatting differently. This is my Podfile line: `pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :branch => '2.0.1'`

With `UITextView`, I'm used to being able to set a `.backgroundColor` and then `.layer.cornerRadius` to get rounded corners on a text view.

I have a `ASEditableTextNode` on which I'm setting the `.cornerRadius` to a reasonable value, like `8.0`, and also a `backgroundColor` that should be visible, like purple. I see the purple background, however, the corners are not round. I'm doing this inside of a `viewDidLoad` method on an `ASViewController` subclass. In the VC's `init`, I'm calling `initWithNode:` with a standard `ASDisplayNode`.

I decided to investigate the view heirarchy of the `ASEditableTextNode`'s view, it looks something like this:

```
cy# f.view.recursiveDescription
@"<ASEditableTextNode-View: 0x7fd6a0621110; node = <ASEditableTextNode: 0x7fd6a2896a00>; frame = (43.5 171; 233 44)>
   | <UITextView: 0x7fd6a18a4000; frame = (0 0; 233 44); text = ''; clipsToBounds = YES; hidden = YES; userInteractionEnabled = NO; gestureRecognizers = <NSArray: 0x608000243f90>; layer = <CALayer: 0x60800003b9a0>; contentOffset: {0, 0}; contentSize: {233, 36}>
   |    | <<_UITextContainerView: 0x7fd6a0621f00; frame = (0 0; 233 36); layer = <_UITextTiledLayer: 0x6080000badc0>> minSize = {0, 0}, maxSize = {1.7976931348623157e+308, 1.7976931348623157e+308}, textContainer = <NSTextContainer: 0x600000113a70 size = (211.000000,340282346638528859811704183484516925440.000000); widthTracksTextView = YES; heightTracksTextView = NO>; exclusionPaths = 0x608000011600; lineBreakMode = 0>
   |    |    | <_UITileLayer: 0x60800003c980> (layer)
   |    | <UIImageView: 0x7fd6a041a500; frame = (3 38.5; 227 2.5); alpha = 0; opaque = NO; autoresize = TM; userInteractionEnabled = NO; layer = <CALayer: 0x61800002dd60>>
   |    | <UIImageView: 0x7fd6a041a6e0; frame = (227.5 11; 2.5 30); alpha = 0; opaque = NO; autoresize = LM; userInteractionEnabled = NO; layer = <CALayer: 0x61800002c640>>
   | <ASPanningOverriddenUITextView: 0x7fd6a188d200; baseClass = UITextView; frame = (0 0; 233 44); text = 'Username'; clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6080002451c0>; layer = <CALayer: 0x60800003bf40>; contentOffset: {0, 0}; contentSize: {233, 45}>
   |    | <<_UITextContainerView: 0x7fd6a06244e0; frame = (0 0; 233 45); layer = <_UITextTiledLayer: 0x6080000bad00>> minSize = {0, 0}, maxSize = {1.7976931348623157e+308, 1.7976931348623157e+308}, textContainer = <NSTextContainer: 0x610000113f80 size = (211.000000,340282346638528859811704183484516925440.000000); widthTracksTextView = YES; heightTracksTextView = NO>; exclusionPaths = 0x608000011600; lineBreakMode = 0>
   |    |    | <_UITileLayer: 0x60800003bb60> (layer)
   |    | <UIImageView: 0x7fd6a041a9e0; frame = (3 38.5; 227 2.5); alpha = 0; opaque = NO; autoresize = TM; userInteractionEnabled = NO; layer = <CALayer: 0x61800002de40>>
   |    | <UIImageView: 0x7fd6a041abc0; frame = (227.5 3; 2.5 37); alpha = 0; opaque = NO; autoresize = LM; userInteractionEnabled = NO; layer = <CALayer: 0x61800002dc00>>"
```

The `cornerRadius` of the `ASEditableTextNode-View` is 8. The `ASPanningOverriddenUITextView`, which appears to be the actual `UITextView` I'm seeing on screen, has a `cornerRadius` of 0. When I set it to 8, I see the result on screen as expected.

So, it seems to me that in this case, we'd prefer the node's `cornerRadius` to actually set the corner radius of the `ASPanningOverriddenUITextView`'s `layer`. Am I on the right track? I'd be happy to submit a pull request with a little guidance on the best way of going about doing this.

**Comment by maicki** [comment]
@aaronash I have this in a sample project setup and works fine:

<img width="307" alt="screen shot 2016-12-21 at 8 31 38 pm" src="https://cloud.githubusercontent.com/assets/25288/21403348/b410ccfc-c7bc-11e6-9eb1-2bda8ce3e2e0.png">


You have to set the `masksToBounds` to `YES` too.

```Objc
    // Set initial state
    _editableTextNode.backgroundColor = [UIColor lightGrayColor];
    _editableTextNode.textView.textColor = [UIColor whiteColor];
    _editableTextNode.textContainerInset = UIEdgeInsetsMake(5.0, 5.0, 5.0, 5.0);
    
    // I know :(
    _editableTextNode.layer.cornerRadius = 6.0;
    _editableTextNode.layer.masksToBounds = YES;
```

**Comment by aaronash** [comment]
@maicki you are absolutely right, this fixed my issue. I should've realized that. Thanks!
