### ISSUE TITLE
[Documentation] Batch fetching: docs should describe 180º transform trick (to fetch upwards).

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2824]
This is *very* commonly useful, for any app that has scrolling similar to a messaging app where content loads upwards instead of downwards.

> sainttail [9:49 AM]  
> doesn’t batch fetching support only one direction right now. which is scrolling from top to bottom. For bottom to top (load history) it isn’t support yet?
> 
> appleguy [9:51 AM]  
> yeah, that's why I mentioned that you can rely on it for the first load, but not after that .  There isn't support for fetching from the other direction right now.  I think we may have a task filed, but because the team has many high priority work areas for the next 3 months, we're not likely to implement it for the next major feature release (2.1).  However, we'd welcome any PRs that extend the ASBatchFetching system to include a Head fetch type / context.  There are some docs on the website that explain the existing system and it should be easy to speculate how it could be extended.
> 
> [9:51]  
> note that there are a lot of apps that flip the direction, though
> 
> [9:51]  
> so if you only need loading in one direction, but just need that direction to be upwards, that is possible to do with a double-transform trick (transform the table / collection 180º, then also transform each cell 180º; this is actually efficient)
> 
> [9:52]  
> so for messaging apps it usually works perfeclty
> 
> sainttail [9:52 AM]  
> Oh! Flip direction!!! Thanks
> 
> appleguy [9:53 AM]  
> Sweet, glad to hear that would be helpful.  We should add it to the docs page for batch fetching, if anyone had time the docs are open to edits!  Ideally we'd have a simple example using that technique...I'm not sure we do.

**Comment by FengDeng** [comment]
hi, @hannahmbanana ,
sometimes  flip 180º  is good.
when tablenode just has one message in messageAPP.That message is on bottom.
