### ISSUE TITLE
Automatic memory management

### ISSUE THREAD

**Issue by jennibunny** [facebook/AsyncDisplayKit#2829]
Hello,

I want to know if ASScrollNode, ASCollectionNode, and ASPagerNode automatically manage memory when the view is not visible to user and even when pagingenabled is true for ASScrollNode.

Waiting for your reply

**Comment by garrettmoon** [comment]
@jennibunny yes, it does! There's even a demo app that might help explain how it works. Get more info here: http://asyncdisplaykit.org/docs/debug-tool-ASRangeController.html
