### ISSUE TITLE
[Question - ASCollectionNode] insertItems without animation

### ISSUE THREAD

**Issue by leotumwattana** [facebook/AsyncDisplayKit#2830]
I've been trying to figure out a way to insert items without the `default fade animation` on an ASCollectionNode.

Without ASDK, this is what I would do:

```
UIView.performWithoutAnimation { [weak self] in
  self?.collectionView.insertItems(at: [indexPath])
}
```

However it seems the equivalent does not work, meaning:
```
// This will still perform a fade animation
UIView.performWithoutAnimation { [weak self] in
  self?.collectionNode.insertItems(at: [indexPath])
}
``` 

The only way I've been able to bypass animations is via `reloadData:` but obviously this is really bad for performance.

Is there a way to handle this case? Thanks in advance.

**Comment by EviluS** [comment]
@leotumwattana You should wrap your `insert/delete/reload` methods in `performBatchAnimated:updates:completion` method.

**Example:**

```
[self.collectionNode performBatchAnimated:NO updates:^{
    [self.collectionNode insertItemsAtIndexPaths:items];
} completion:^(BOOL finished) {
    // Completion
}];
```

**Comment by leotumwattana** [comment]
@EviluS Thanks. How did I totally miss that. Closing this issue now. 👍
