### ISSUE TITLE
Sample project AnimatedGIF not load gif on device, but works fine on simulator.

### ISSUE THREAD

**Issue by maundytime** [facebook/AsyncDisplayKit#2831]
ASDK: 2.0.1
My device iOS: 10.2(14C92)
Xcode: 8.2.1

I tried to run ASDK sample project "AnimatedGIF" on my iPhone 7 Plus, but gif couldn't be loaded. Even though it could load gif very few times, at most of times, gif couldn't be loaded.

But this sample did work fine on simulator. I tried iPhone SE simulator and iPhone 7 Plus simulator, the gif would show in both cases. 

I could also visit that gif in safari on my device.

Maybe it's related with differences between device and simulator?

**Comment by garrettmoon** [comment]
@maundytime are there any logs on the device? Also, how much free space does your device have?

**Comment by maundytime** [comment]
My device free space is 80.78GB. I also could find the gif image in my device app container like image below. But gif image not loaded.
<img width="1282" alt="2017-01-07 1 49 21" src="https://cloud.githubusercontent.com/assets/3490007/21739777/2d60f818-d4e0-11e6-8cbf-e4baa1a12637.png">

If I comment code like the image below, Gif would be displayed.
<img width="1350" alt="2017-01-07 2 10 53" src="https://cloud.githubusercontent.com/assets/3490007/21739892/23018178-d4e3-11e6-9877-86f7dfbe9371.png">

But when I display many gif in ASTableNode and scroll fast, I would get crash, like image below.
<img width="1440" alt="2017-01-07 2 08 00" src="https://cloud.githubusercontent.com/assets/3490007/21739881/e9542386-d4e2-11e6-834e-430605436870.png">

**Comment by garrettmoon** [comment]
@maundytime this appears to be the same race condition that is reported here: https://github.com/pinterest/PINRemoteImage/issues/298. Going to close this as it's not an ASDK issue. Please follow along over there!
