### ISSUE TITLE
Sometimes deadlock in ASCollectionNode

### ISSUE THREAD

**Issue by muukii** [facebook/AsyncDisplayKit#2833]
Sometimes deadlock in ASCollectionNode.
Am I misunderstanding how to use ASCollectionNode?

<img width="1439" alt="screen shot 2016-12-23 at 23 08 15" src="https://cloud.githubusercontent.com/assets/1888355/21455591/d588fc98-c964-11e6-9146-84e4e70ab6f1.png">

**Comment by garrettmoon** [comment]
@muukii can you provide screenshots of what the other threads are doing as well? Is it easy to reproduce with a sample project?

**Comment by muukii** [comment]
@garrettmoon 
It has become quite difficult to reproduce.
Upload screenshots of all threads when reproduced.

**Comment by hannahmbanana** [comment]
@muukii - we really appreciate this report! I'm going to close this issue until you can provide us with more information (use "> bt all" to get get the full backtrace). The next time you can reproduce this, please re-open the issue and we'll take a look. Thanks!
