### ISSUE TITLE
ASVideoNode can't play

### ISSUE THREAD

**Issue by bawn** [facebook/AsyncDisplayKit#2835]
iOS Version: 10.2
AsyncDisplayKit Version: 2.0.0

follow code
```- (ASVideoNode *)nicCageVideoNode;
{
  ASVideoNode *nicCageVideoNode = [[ASVideoNode alloc] init];
  nicCageVideoNode.delegate = self;
  nicCageVideoNode.asset = [AVAsset assetWithURL:[NSURL URLWithString:@"http://images.apple.com/media/cn/macbook-pro/2016/b4a9efaa_6fe5_4075_a9d0_8e4592d6146c/films/design/macbook-pro-design-tft-cn-20161026_1536x640h.mp4"]];
  nicCageVideoNode.gravity = AVLayerVideoGravityResize;
  nicCageVideoNode.backgroundColor = [UIColor lightGrayColor];
  nicCageVideoNode.shouldAutorepeat = YES;
  nicCageVideoNode.shouldAutoplay = YES;
  nicCageVideoNode.muted = YES;
  nicCageVideoNode.delegate = self;
  return nicCageVideoNode;
}
```

When loading a video on a poor network,  Even if `videoNodeDidFinishInitialLoading` delegate method is called, The video does not start playing .

Detail info: [Demo](https://github.com/bawn/ASVideoNode), Do not forget to run`pod update`.Must be tested on 2 Mbps ISDN / DSL NetWork or worse

**Comment by garrettmoon** [comment]
Thanks for the demo app!

**Comment by nguyenhuy** [comment]
@bawn Please test your sample project against my diff proposed in #2876. No changes are required in your code. Thanks!

**Comment by hannahmbanana** [comment]
@bawn - I'm going to close this issue since we believe the problem has been fixed by Huy's patch. However, if you find that the patch does not fix your bug, please reopen this issue. Thanks!
