### ISSUE TITLE
[Table / Collection] Add BOOL option to flip everything for "upward-loading" apps.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2837]
This has become one of the most commonly-asked questions on Slack.  In addition to the benefit from having a simple answer / documentation callout for the feature, the complexity is low enough to provide this kind of BOOL.  The use case common enough — all comment / messaging views — that it makes sense to do if we can implement it with ~20 lines of code or less.

All this option would do:
- Provide BOOL on Table or Collection
- When enabled, it flips 180º every ASCellNode that is returned (by applying a transform to it.  It also sets its own transform to flip 180º.
- That's it!  It would be reasonable to assert / not allow changing the property after content has started to load (or even, when the node's view exists).  The 90% value is captured in this case.  Any more dynamic cases should be handled by apps directly.

> Hello, I’m just new to this trying explore ASDK. I have some questions about `head fetching` which got closed - https://github.com/facebook/AsyncDisplayKit/pull/1141
> 
> Is ASDK currently doesn’t support head fetching out of the box?
> If we want that functionality is there any suggestion on how to build it on top of ASDK? (edited)
> 
> appleguy [9:46 AM]  
> @sangbill what kind of UI were you thinking about?  Pull to refresh, or automatic?
> 
> sainttail [9:46 AM]  
> automatic like chat
> 
> appleguy [9:47 AM]  
> well, the first fetch will be automatic if you just use batch fetching
> 
> [9:47]  
> beyond that though, you'd need some kind of polling system or a server push system (persistent connection), which you have to manage yourself at the network layer in your app
> 
> [9:47]  
> but it's always nice to rely on batch fetching for both scrolling back in history (Pagination), as well as the first load of a screen as you're arriving at it
> 
> [9:48]  
> so it's only updating with new content while the user is currently on a screen that you need to handle manually
> 
> sainttail [9:49 AM]  
> doesn’t batch fetching support only one direction right now. which is scrolling from top to bottom. For bottom to top (load history) it isn’t support yet?
> 
> appleguy [9:51 AM]  
> yeah, that's why I mentioned that you can rely on it for the first load, but not after that .  There isn't support for fetching from the other direction right now.  I think we may have a task filed, but because the team has many high priority work areas for the next 3 months, we're not likely to implement it for the next major feature release (2.1).  However, we'd welcome any PRs that extend the ASBatchFetching system to include a Head fetch type / context.  There are some docs on the website that explain the existing system and it should be easy to speculate how it could be extended.
> 
> [9:51]  
> note that there are a lot of apps that flip the direction, though
> 
> [9:51]  
> so if you only need loading in one direction, but just need that direction to be upwards, that is possible to do with a double-transform trick (transform the table / collection 180º, then also transform each cell 180º; this is actually efficient)
> 
> [9:52]  
> so for messaging apps it usually works perfeclty
> 
> sainttail [9:52 AM]  
> Oh! Flip direction!!! Thanks
> 
> appleguy [9:53 AM]  
> Sweet, glad to hear that would be helpful.  We should add it to the docs page for batch fetching, if anyone had time the docs are open to edits!  Ideally we'd have a simple example using that technique...I'm not sure we do.
> 
> [9:55]  
> filed this for docs upgrades https://github.com/facebook/AsyncDisplayKit/issues/2824
> 
>

**Comment by hannahmbanana** [comment]
Many thanks to @aaronschubert0 for implementing this commonly requested feature!
