### ISSUE TITLE
-tableNode:willSelectRowAtIndexPath: does not allow returning nil

### ISSUE THREAD

**Issue by rewandy** [facebook/AsyncDisplayKit#2840]
If you implement `-tableNode:willSelectRowAtIndexPath:` and return `nil`, the first cell node (index path 0,0) ends up being selected, instead of preventing selection from occurring.

This doesn't match the expected UITableView behavior, where the [docs](https://developer.apple.com/reference/uikit/uitableviewdelegate/1614943-tableview?language=objc) state:

> Return `nil` if you don't want the row selected.

Stepping through the debugger shows that `ASTableView`:
1. [Asks the asyncDelegate to return an `indexPath`](https://github.com/facebook/AsyncDisplayKit/blob/e264d94dde78d9bfe98cb71be55ef14356f4a7f2/AsyncDisplayKit/ASTableView.mm#L913) - in my case this `result` is sometimes `nil`.
2. [Immediately converts the possibly-nil index path](https://github.com/facebook/AsyncDisplayKit/blob/e264d94dde78d9bfe98cb71be55ef14356f4a7f2/AsyncDisplayKit/ASTableView.mm#L914) - due to implementation details, this now comes back with a non-nil `result` pointing to index path 0,0.
3. [Table view is told to select index path 0,0](https://github.com/facebook/AsyncDisplayKit/blob/e264d94dde78d9bfe98cb71be55ef14356f4a7f2/AsyncDisplayKit/ASTableView.mm#L915).

The simplest fix would probably be to make `ASTableView` return `nil` immediately, in cases where [the call](https://github.com/facebook/AsyncDisplayKit/blob/e264d94dde78d9bfe98cb71be55ef14356f4a7f2/AsyncDisplayKit/ASTableView.mm#L913) to the `asyncDelegate` returned `nil`. In other words, keep `nil` as `nil` and return it to UIKit as-is.

### Example

I'm attempting to prevent an already-selected row from being selected again (and subsequently calling the `didSelect` delegate method).

```objc
- (NSIndexPath *)tableNode:(ASTableNode *)tableNode willSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    // Check if this indexPath is already selected.
    if ([tableNode.indexPathsForSelectedRows containsObject:indexPath]) {
        return nil; // Don't allow re-selecting the same index path
    }
    return indexPath;
}
```

Issue in action:

![table-reselect](https://cloud.githubusercontent.com/assets/4761768/21510490/f40009be-cc48-11e6-96b4-9a05a314f9d0.gif)

Note how attempting to re-select Jim ends up selecting Meghan, instead of doing nothing.

### Workaround

Until this is fixed, I've implemented `-tableView:willSelectRowAtIndexPath:` instead, which doesn't have this issue but **is** marked as deprecated.

**Comment by Adlai-Holler** [comment]
Resolved in #2856.
