### ISSUE TITLE
custom Layout Transition doesn't change node size

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#2841]
I have created a custom `ASDisplayNode` wich  displays some tags and their descriptions. for layout transition I have used Layout Transition API. using version `2.0-beta.1`
when user selects a tag, selected tag grows and it displays tags description.

![taglistold](https://cloud.githubusercontent.com/assets/3206748/21520812/babe6960-cd0c-11e6-845c-7c33b70c847e.gif)

now I have updated ASyncDisplayKit to `2.0.1` but resulting behavior is corrupted: (for simplicity I have hidden to description text node)

<img width="479" alt="screen shot 2016-12-28 at 3 31 23 pm" src="https://cloud.githubusercontent.com/assets/3206748/21521511/daec14de-cd12-11e6-9bdd-04ba1cefb845.png">

![taglistanimated](https://cloud.githubusercontent.com/assets/3206748/21520837/e95efe2e-cd0c-11e6-9e83-56244ee79ee8.gif)
node hierarchy: AScellNode -> TagListNode -> TagNode
<img width="619" alt="screen shot 2016-12-28 at 3 18 14 pm" src="https://cloud.githubusercontent.com/assets/3206748/21521289/e85f7e6e-cd10-11e6-9e70-1de1c6b4b9af.png">

for the below one by selecting a tag, I just call `setNeedsLayout()` on tags container node and it behaves correctly with no animation:
![taglist](https://cloud.githubusercontent.com/assets/3206748/21520935/9b7c5e12-cd0d-11e6-8eba-b0c674cac429.gif)

TagNode Layout Spec:

``` swift
override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {  
        var children: [ASLayoutElement] = [imageNode]
        if open {
            descriptionNode.isHidden = false
            children.insert(descriptionNode, at: 0)
        } else{
            descriptionNode.isHidden = true
        }
        
        descriptionNode.style.spacingAfter = inset
        let horizontalStack = ASStackLayoutSpec(direction: .horizontal, spacing: 0, justifyContent: .center, alignItems: .center, children: children)
        
        let insetNode = ASInsetLayoutSpec(insets: UIEdgeInsetsMake(0, inset, 0, inset), child: horizontalStack)
        return insetNode;
    }
```

by tapping a tag,  tagNode `onStateChangeBlock` gets called in TagListNode:

``` swift
node.onStateChangeBlock = { [unowned self] in
                self.selectedTagNode = node
                self.open = !self.open
              self.transitionLayout(withAnimation: true, shouldMeasureAsync: false, measurementCompletion: nil)
            }
```

``` swift
override func animateLayoutTransition(_ context: ASContextTransitioning) {
UIView.animate(withDuration: 0.25, delay: 0, options: .curveEaseOut, animations: {
            
            if self.open {

// for simplicity I just change to an arbitrary frame
                self.frame = CGRect(x: 100, y: 0, width: 250, height: 60)
        
            } else {
            }
        }) { (finished: Bool) in
            context.completeTransition(finished)
        }
}
```

I wonder why node container frame change doesn't animate correctly?

thanks in advance

**Comment by ArEnSc** [comment]
I have this exact issue

**Comment by hannahmbanana** [comment]
@ArEnSc @hashemp206 - thank you for reporting this! Would it be possible to create a sample project showing this?

**Comment by hashemp206** [comment]
@hannahmbanana sample project: https://github.com/hashemp206/TagListNode/tree/master

**Comment by nguyenhuy** [comment]
@hannahmbanana Please close this ticket. Since this is not a framework bug, discussions will be carried out in the sample repo.
