### ISSUE TITLE
How `leadingScreensForBatching` work if I have horizontal scrolling?

### ISSUE THREAD

**Issue by chika-kasymov** [facebook/AsyncDisplayKit#2850]
I have horizontal `UICollectionNode` and want to prefetch data. Every cell in collection has size of full screen and paging is enabled. I want to fetch new data when there are 10 cells remain.

Is it ok if I will just specify it like this `collectionView.view.leadingScreensForBatching = 10`?

**Comment by garrettmoon** [comment]
That sounds correct to me!
