### ISSUE TITLE
ASScrollNode automaticallyManagesContentSize

### ISSUE THREAD

**Issue by mikhailmulyar** [facebook/AsyncDisplayKit#2853]
I'm trying to use automaticallyManagesContentSize enabled in one of my scroll nodes with layoutSpecBlock containing simple vertical stack. However resulted contentSize is always limited to constrainedSize(parent size) of node. How can i achieve content size to be bigger than scroll node size? I'm using 2.0.1.

**Comment by jennibunny** [comment]
I faced same issue.

**Comment by hashemp206** [comment]
@mikhailmulyar please provide a sample project

**Comment by 8ofproject** [comment]
Posted example project in https://github.com/facebook/AsyncDisplayKit/issues/2851

**Comment by hannahmbanana** [comment]
@mikhailmulyar @jennibunny @hashemp206 @8ofproject - does this PR address your bug? 
https://github.com/facebook/AsyncDisplayKit/commit/e264d94dde78d9bfe98cb71be55ef14356f4a7f2

**Comment by hannahmbanana** [comment]
This is a duplicate of #2853.
