### ISSUE TITLE
ASDisplayNode dealloc performance

### ISSUE THREAD

**Issue by mikhailmulyar** [facebook/AsyncDisplayKit#2854]
I have very long table node with around 2k cells. When i'm trying to reload this table or closing screen i have pretty long lag for around 3-5 seconds. According to profile the reason of it is dealloc of all nodes which blocks main thread. I'm using 2.0.1.
<img width="1023" alt="screen shot 2017-01-03 at 22 41 04" src="https://cloud.githubusercontent.com/assets/2234720/21620527/d4b7f7d4-d205-11e6-97c0-e74746d9aed5.png">

**Comment by Adlai-Holler** [comment]
@mikhailmulyar Looking at the stack trace, it seems like the vast majority of the time is in disposing of that `ActionDisposable`, as part of releasing that `Atomic`. I wonder what code ReactiveASDK is running there, that is taking 2.85 seconds. In the mean time, I'll try and figure out why that deallocation is occurring on the main thread – it would be great to see the stack trace between `main` and `-[ASDisplayNode dealloc]`.

**Comment by mikhailmulyar** [comment]
Thanks, it seems problem have been not really in ASDK. After removing Reactive code dealloc time felt down to reasonable value for 2k elements.

**Comment by mikhailmulyar** [comment]
Here is the stack between main and -[ASDisplayNode dealloc] incase you still need it.
<img width="1024" alt="screen shot 2017-01-04 at 02 22 05" src="https://cloud.githubusercontent.com/assets/2234720/21626844/ad8a32ca-d224-11e6-8a76-5d1f8d14b69a.png">

**Comment by Adlai-Holler** [comment]
Cool, thanks.
