### ISSUE TITLE
[Question] Placing objects on the left and right edges using layout specs

### ISSUE THREAD

**Issue by jennibunny** [facebook/AsyncDisplayKit#2858]
Hello,

I want to place objects on the left and right edges of ASDisplayNode like this 

| OBJECT        OBJECT |

I used `ASStackLayoutSpec` with horizontal direction and `.justifyContent = ASStackLayoutJustifyContentStart` with 50 spacing. 

However, the problem is that if the displayNode width size increases, the object on the right edge does not stay in the same place.

**Comment by hannahmbanana** [comment]
@jennibunny - does `.justifyContent = ASStackLayoutJustifyContentEnd` work?

**Comment by jennibunny** [comment]
`ASStackLayoutJustifyContentEnd` moves all the objects to the right edge of the `ASDisplayNode`. Therefore, when `ASDisplayNode width size` changes, the object on the left edge doesn't stay in the same place :(

**Comment by hashemp206** [comment]
@jennibunny you mean right object edge goes out of bound of container node? please provide a sample screen shot of initial and final state of parent node.

**Comment by hannahmbanana** [comment]
@jennibunny - if you could share your `layoutSpecThatFits:` method, I'm sure @maicki - our layout spec expert could point out the issue.

**Comment by Adlai-Holler** [comment]
@jennibunny You might be looking for `ASStackLayoutJustifyContentSpaceBetween`?
