### ISSUE TITLE
"ASDisplayNode+FrameworkSubclasses.h" not found?

### ISSUE THREAD

**Issue by CoderJee** [facebook/AsyncDisplayKit#2860]
I use cocoapods (`pod 'AsyncDisplayKit'` ) to install ASDisplayKit , but it remind me some compile errors when  i compile the project.
cocoapods verison is `1.1.1`
![wechatimg409](https://cloud.githubusercontent.com/assets/7976210/21647955/4d2589a8-d2d7-11e6-831d-616321f31738.jpeg)
![wechatimg1](https://cloud.githubusercontent.com/assets/7976210/21648046/8f68ad54-d2d7-11e6-857f-b147ddf4b978.jpeg)

**Comment by hannahmbanana** [comment]
@CoderJee - that's a private framework file. What reason do you need to import it for? Try importing the framework header instead of individual classes:

`#import <AsyncDisplayKit/AsyncDisplayKit.h>`

**Comment by CoderJee** [comment]
@hannahmbanana i didn't import it by myself, that's the source code,when i use cocoapods to install it.

**Comment by hannahmbanana** [comment]
@CoderJee - I apologize for the misunderstanding. I'm not currently able to reproduce this issue. Could you give me a little more information?

When you pod install, what version of AsyncDisplayKit is installed? 
![image](https://cloud.githubusercontent.com/assets/3419380/21905252/a11562d8-d8bb-11e6-9702-cc65770ef6af.png)

Could you post the contents of your Podfile?

Thanks!

**Comment by hannahmbanana** [comment]
This file was added pretty recently so it's very possibly a mistake on our end! :)

**Comment by hannahmbanana** [comment]
@CoderJee - We recently landed some changes to our framework setup. Our compiler should now catch this if it is a problem going forward. Please re-open this issue or file a new one if you (or anyone else reading this) runs into this in the future!
