### ISSUE TITLE
[ASImageNode] No longer uses placeholderColor

### ISSUE THREAD

**Issue by master-nevi** [facebook/AsyncDisplayKit#2865]
Version with issue: ASDK v2+ to master

Original thread from Slack channel: https://asyncdisplaykit.slack.com/archives/general/p1483578622003990

This prevents the placeholder API (`[ASDisplayNode placeholderEnabled/placeholderFadeDuration/placeholderImage]`) from being used to fade in remote images from a solid color after the download is finished. When looking at the `ASImageNode` it appears that `placeholderColor` is no longer used anywhere in the implementation.

**Comment by Adlai-Holler** [comment]
Resolved in #2866. Thanks for the issue report and building the fix @master-nevi !
