### ISSUE TITLE
ASHighlightOverlayLayer: rect out of bounds

### ISSUE THREAD

**Issue by ArmandsB** [facebook/AsyncDisplayKit#2869]
ASTextNode uses ASHighlightOverlayLayer for drawing highlight layer when user taps/long press it.
But there is a bug, when link text is at ASTextNode edge and the highlight layer is clipping.

![screenshot at jan 06 10-18-36](https://cloud.githubusercontent.com/assets/3258393/21711784/85511e82-d3f9-11e6-9e05-9f448fa01538.png)

As you can see - highlight area is clipped and not rounded at left edge.

The drawing path starting value (minX) is **-4**.
The main problem I think is that ASHighlightOverlayLayer is using "**drawInContext**", which does not allow drawing paths out of boundes.

P.S. I checked all clipping,maskToBounds parent properties - all is set to false.

**Comment by Adlai-Holler** [comment]
@ArmandsB In order to work around this, you should set `as_allowsHighlightDrawing=YES` on a layer that is big enough not to result in clipping. For example, you might set it on the entire cell node in that example. Does that make sense @ArmandsB ?

**Comment by ArmandsB** [comment]
Thanks for your replay. Setting `as_allowsHighlightDrawing=YES` to entire cell did the trick.
