### ISSUE TITLE
Drag the AsyncDisplayKit into My project wihtout Pod has a lot of problem

### ISSUE THREAD

**Issue by KimBin** [facebook/AsyncDisplayKit#287]
there a lot of tips which tip the header file can't find,such as \<AsyncDisplayKit/ASCollectionView \>.  so i merge all the file in a folder that named AsyncDisplayKit . and Drag the folder into preject.  and change the  import  \<AsyncDisplayKit/ASCollectionView.h\>    ->  import "ASCollectionView.h". but a new problem was coming.   at the ASThread.h   line:113 (the code :  
struct Mutex
  {
    /// Constructs a non-recursive mutex (the default).
    Mutex () : Mutex (false) {}
   ........
) 
there is a tip:  that delegating constructors are permitted only in c++ 11    

i think that the AsyncDisplayKit maybe a  great tool ,but the feel to use is bad

**Comment by rnystrom** [comment]
Make sure you have `libAsyncDisplayKit.a` in "Link Binary With Libraries" and that you have `-lc++ -ObjC` in your project linker flags. It sounds like you're missing linkers to C++.

**Comment by secretiverhyme** [comment]
Imports that use `<>` are for external frameworks, while `""` imports are for files in your project.

We recommend using AsyncDisplayKit as a framework, which you can do using CocoaPods.  If you can't or don't want to use CocoaPods, you can still use AsyncDisplayKit as a framework with Xcode.  This requires you to use a *workspace*, not a project.  Try creating a workspace for your project, then dragging the `AsyncDisplayKit.xcodeproj` file into that workspace.

**Comment by jjjjjeffrey** [comment]
Is there any way to use it in my project without CocoaPods or creating a workspace?
