### ISSUE TITLE
ASTabBarController content blink on tab change

### ISSUE THREAD

**Issue by 8ofproject** [facebook/AsyncDisplayKit#2873]
Controllers content blink on tab change, but not every time.

Steps to reproduce:
1. Tap on tab bar items one by one from left to right and then in reverse order
2. Sometimes you need to make it 2-5 times

Blink happens not every time.
Sometimes blink only happens when switching between only two controllers (random ones).

layoutSpecBlock does not get called during that blink times.
The issue also appears when we have different controllers.

ASDK 2.0.1 (the same for 2.0 and 2.0 rc-builds)
iOS 10+ Simulator and real device
Example code when all tab bar children are the same class controllers:
https://github.com/8ofproject/ask-example-tababr/
_TabBarViewController.swift_ - TabBar controller
_ContactUsViewController.swift_ class - children controllers

**Comment by hashemp206** [comment]
I had same issue, but using `UITabBarController`. and this happened only after updating to iOS 10. 
I resolved this issue by animating view controller changes

**Comment by Adlai-Holler** [comment]
@8ofproject Yes unfortunately this is an issue with UITabBarController. ASDK doesn't interfere with the tab drawing behavior.

**Comment by 8ofproject** [comment]
Here is the example with UITabBarController with the same layout without ASDK.
Content doesn't blink.
@Adlai-Holler Maybe we should investigate it further?


[TabBarExample.zip](https://github.com/facebook/AsyncDisplayKit/files/695631/TabBarExample.zip)
