### ISSUE TITLE
ASCollectionInvalidUpdateException 

### ISSUE THREAD

**Issue by modLX4** [facebook/AsyncDisplayKit#2907]
*** Terminating app due to uncaught exception 'ASCollectionInvalidUpdateException', reason: 'PulseViewController: Invalid number of items in section 0. The number of items after the update (7) must be equal to the number of items before the update (7) plus or minus the number of items inserted or deleted (7 inserted, 0 deleted).'

- Can't understand whats going on
- Datasource logic is working fine - Tested with UITableView

**Comment by Adlai-Holler** [comment]
Hey @modLX4 , could you share some sample code that reproduces?

**Comment by hannahmbanana** [comment]
@modLX4 - Any updates? We'd be interested to hear if you figured out a solution to the problem.
