### ISSUE TITLE
ASTableview automaticallyAdjustsContentOffset incorrect when inserting sections with headers/footers

### ISSUE THREAD

**Issue by ArmandsB** [facebook/AsyncDisplayKit#2908]
Hello. I noticed that `automaticallyAdjustsContentOffset` on ASTableView is not working correctly, when inserting sections with headers/footers.

I have created a test project for this. https://github.com/ArmandsB/AsyncDisplayKitTest
Basically, when inserting new sections at top, which have header/footers - offset is being calculated incorrectly. When manually add that extra offset, everything is fine.

**Comment by hannahmbanana** [comment]
@ArmandsB - thank you for including a sample project! 
@Adlai-Holler - could you triage this?

**Comment by Adlai-Holler** [comment]
The documentation says that `automaticallyAdjustsContentOffset` doesn't support section operations, but the linked PR adds that capability. Let me know what you think of it @ArmandsB !

**Comment by ArmandsB** [comment]
Thank you. Looks good ;)
