### ISSUE TITLE
[Crash] ASAsyncTransactionQueue::GroupImpl::schedule

### ISSUE THREAD

**Issue by dssheng** [facebook/AsyncDisplayKit#2909]
ASDK 2.0.1, Random crash.
![jietu20170118-195718](https://cloud.githubusercontent.com/assets/2062938/22063197/7a3d0d26-ddb8-11e6-930c-b93e857aff16.jpg)

**Comment by hannahmbanana** [comment]
@dssheng - is this reproducible? If it is, could you provide the full backtrace (`bt all`)?

**Comment by dssheng** [comment]
Crash random, report by XCode, 
I have no reproduce path.

**Comment by hannahmbanana** [comment]
@dssheng - Given that we have no way of reproducing this, I'm going to close this issue. However, if you run into this again, please re-open this issue or a new issue with the full backtrace. Thanks!
