### ISSUE TITLE
API for Swift (Generics)

### ISSUE THREAD

**Issue by muukii** [facebook/AsyncDisplayKit#2918]
I am using ASDK at Swift. Thank you.

I want some APIs that correspond to generics.

For example `ASDisplayNode.onDidLoad ()`

`` `Swift
Let collectionNode = ASCollectionNode
collectionNode.onDidLoad { (node: ASDisplayNode) in // <- 🤔
}
`` `

Currently the closure argument becomes superclass.
When used with Swift, the closure argument should also be ASCollectionNode.

This correspondence may be difficult with the Objective-C bridge.
Like Realm,
How about developing Realm module and RealmSwift module separately?

**Comment by hannahmbanana** [comment]
@muukii - Improving our Swift developer experience is an area of focus on our long term roadmap, but don't have a timeline for this yet. We'd be happy to accept a PR from anyone with expertise in this area.
