### ISSUE TITLE
[Announcement] iOS 7 support will be dropped in ASDK version 2.2

### ISSUE THREAD

**Issue by hannahmbanana** [facebook/AsyncDisplayKit#2928]
Please let us know if you have any questions or concerns.

**Comment by TanderZA** [comment]
Why is there a need to drop support for iOS7? Just out of curiosity.

**Comment by hannahmbanana** [comment]
@TanderZA - A few reasons:
- As far as we know, very few apps still support iOS 7.
- Our core team of developers supporting ASDK (most of whom are also responsible for developing the Pinterest app), would prefer not to spend our limited bandwidth on supporting iOS 7.
- iOS 7 does not support dynamic .framework libraries (only static). This will help us improve our the ASDK project setup.

**Comment by TanderZA** [comment]
@hannahmbanana Thanks for that. We dropped support in our app (Bidorbuy) last year as we also felt it was not worth the extra effort to keep it supported. Seems like we made the right decision as we have recently incorporated ASDK into our latest build.

**Comment by Adlai-Holler** [comment]
OK folks! Adios iOS 7 – you were way ahead of your time! 

![](https://i.ytimg.com/vi/tm7lhCY2fck/maxresdefault.jpg)

**Comment by Adlai-Holler** [comment]
Well I guess we'll leave this open until the release drops 😛

**Comment by hannahmbanana** [comment]
Closing this since it has landed to master.
