### ISSUE TITLE
Cell nodes in processing may miss trait collection changes

### ISSUE THREAD

**Issue by garrettmoon** [facebook/AsyncDisplayKit#2959]
https://pinterest.slack.com/archives/ios-help/p1485795980000343

From @rcancro:

> I have a question surrounding ASTableNode, its data controller and when _completedNodes in the data controller is populated. On iPad when we bring up the save dialog and tap on "New Board” we push a new VC onto the modal’s nav controller. The nav controller (since it is in a modal on iPad) has a width of 520. However, the VC doesn’t realize this until `viewWillAppear`. I’m seeing the following happen:
> 1. The VC is created with a width of 768
> 2. The VC’s tableNode creates its cells with a 768 width (I can put a breakpoint in the `nodeBlockForRowAtIndexPath` and see it being hit)
> 3. The VC gets resized to 520. This causes `asyncTraitCollectionDidChange` to be called on the table node
> 4. In `asyncTraitCollectionDidChange` the tableNode asks for its completed nodes via `[self.view.dataController completedNodes]` so it can propagate the new container size. However, `[self.view.dataController completedNodes]` returns an empty array.
> Shouldn't I expect the cell that i saw being created when my breakpoint hit to be in `_completeNodes`?

**Comment by Adlai-Holler** [comment]
My initial response on slack was:

> - `completedNodes` gets updated after each batch of nodes is measured and inserted, along with our UIKit update call.
> - The initial environment is propagated down when each individual node is allocated and measured (in ASIndexedNodeContext) so before that
> 
> I'm not an expert on this environment system but it seems like there's this gap that we need to fill, where a node misses a trait collection change that happens after the initial environment is stored (in _populateContexts) but before its batch is added to `_completedNodes`
> 
> One thing we could do as a semi-permanent solution is to go through all the node _contexts_ in `asyncTraitCollectionDidChange` and update their environments (as well as their nodes, as needed).
> 
> The node contexts arrays always contain the most up-to-date representation of the table's content that exists.

**Comment by rcancro** [comment]
This doesn't fix the issue, but is something that seemed incorrect when I was debugging the issue:
https://github.com/facebook/AsyncDisplayKit/pull/2963

**Comment by hannahmbanana** [comment]
@maicki - Do you have any updates to this issue in light of your recent trait collection updates?

**Comment by nguyenhuy** [comment]
Since I'm more familiar with the new implementation of `ASDataController`, I'm gonna steal this task from @maicki.
