### ISSUE TITLE
nodeForItemAtIndexPath: May Return Unexpected Node

### ISSUE THREAD

**Issue by garrettmoon** [facebook/AsyncDisplayKit#2960]
https://pinterest.slack.com/archives/ios-help/p1485811621000355

> Pull to refresh can result in deletions and insertions in the grid (as opposed to a clear or reload). What I’m seeing is the following:
> 1. Several items are deleted from the CV
> 2. the batch update ends
> 3. Masonry invalidates and lays itself out.
> 4. In masonry we ask for the size of a cell given an index path. The way we compute this is to ask the collectionNode for its `cellNodeAtIndexPath:`
> 5. I’m seeing a cellNode come back for the model of an object that was deleted in step 1. In other words, I’m seeing this in the `sizeForItemAtIndexPath` method:
> 
> It appears that the `completedNodes` in the data controller are not updated on a delete? What would be the best way to determine the size of a cell if calling `cellNodeAtIndexPath` can return an out of date cell?

**Comment by rcancro** [comment]
This was user error :)

**Comment by Adlai-Holler** [comment]
Yay! I mean, y'know. Bummer.
