### ISSUE TITLE
Recommended way to draw rounded rect around words in ASTextNode?

### ISSUE THREAD

**Issue by christianselig** [facebook/AsyncDisplayKit#2965]
I'm looking to add a rounded rect around specific words in an `ASTextNode`, and curious to how this would best be done/advised. 

You can add **non**-rounded rects around words using `NSBackgroundColorAttributeName` obviously, but adding rounded variants is a little trickier. 

![image](https://cloud.githubusercontent.com/assets/4311814/22514543/05036780-e876-11e6-8600-cda814b96396.png)

It's nice in situations like on GitHub where you want to "label" certain words (or even in this body of text where inline code is shown):

![image](https://cloud.githubusercontent.com/assets/4311814/22514565/181c9fbc-e876-11e6-865b-fc65f9879945.png)

One option would be to subclass `NSLayoutManager` (well, `ASLayoutManager`) and override `fillBackgroundRectArray(_:count:forCharacterRange:color:)`, but as far as I can tell `ASTextNode` doesn't expose its TextKit stack (for good reason I'm sure). An issue with this (as seen in the first screenshot) is that it doesn't add padding to either side of the word which would be nice, but I'm not sure how to overcome this other than manually adding spaces.

However this leads me to wonder how something like this would be possible. Perhaps adding it as a core function of `ASTextNode` would be one option, but if a user wanted to draw it on their own, perhaps by subclassing `ASTextNode` and using a custom `NSAttributedString` attribute, they would need access to `NSLayoutManager`'s `boundingRect(forGlyphRange glyphRange: NSRange, in container: NSTextContainer)` in order to know where to draw, correct? (Which again isn't exposed.)

*EDIT: Nevermind, subclass drawing [isn't supported](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L159).*

I guess after all this rambling I'm curious how you smart people would recommend tackling this? If it's as simple as adding a property on `ASTextNode` that `ASLayoutManager` could observe to implement the rounding in `fillBackgroundRectArray`, I'd be happy to add that as a PR, but I'd like to know if that's advisable first, or if this feature is a bad idea all together, that's okay too. 😛

**Comment by christianselig** [comment]
Perhaps allowing their customization [as in this PR](https://github.com/facebook/AsyncDisplayKit/pull/1437) would be an answer.

**Comment by christianselig** [comment]
Would perhaps allowing users to pass an `NSLayoutManager` subclass to `ASTextNode` be an appropriate solution to this problem? It could be part of `ASTextKitAttributes` and allow users to implement a custom layout manager to achieve the above rounding (among other things).

**Comment by christianselig** [comment]
Proposal: https://github.com/facebook/AsyncDisplayKit/pull/3008

**Comment by Adlai-Holler** [comment]
We've decided to roll with the `didDisplayNodeContentWithContext` mechanism on `ASDisplayNode` in the linked issue.
