### ISSUE TITLE
[Layout Transition] Layout flickers to final state before transition starts

### ISSUE THREAD

**Issue by jellenbogen** [facebook/AsyncDisplayKit#2971]
Hey Guys,

So I'm seeing this while animating a layout transition (the flicker right before the animation)

![animation-flickering](https://cloud.githubusercontent.com/assets/1269011/22542284/f12a49e4-e8df-11e6-8fe9-db3735e1ec2d.gif)

I've been really scratching my head on this one. I have a node using the layout transition api, and noticed that right before the animations i'm performing start I see the final state flicker in before my animations begin. 

So while debugging and digging around these are the method calls I see happening in order:

1. I call `transitionLayout(withAnimation: true, shouldMeasureAsync: false, measurementCompletion: nil) `
2. `animateLayoutTransition(_ context: ASContextTransitioning)` gets called from 

```
transitionLayoutWithSizeRange:(ASSizeRange)constrainedSize
                             animated:(BOOL)animated
                   shouldMeasureAsync:(BOOL)shouldMeasureAsync
                measurementCompletion:(void(^)())completion
```

3. Immediately after  `animateLayoutTransition` gets called  `[self _finishOrCancelTransition]` gets called which sets `_transitionInProgress = NO;`
4. Then before the animations start `__layout` gets called and sets the frames to their final position.

The issue is that in looking at __layout I see this check
```
  // If a current layout transition is in progress there is no need to do a measurement and layout pass in here as
  // this is supposed to happen within the layout transition process
  if ([self _isTransitionInProgress]) {
    return;
  }
```
Which looks great except for the fact that the only place `_isTransitionInProgress` is set to `NO` is immediately after the call to animate transition, which doesn't allow for the transition animation to actually finish.

I could definitely be missing something here, but It seems like the call to `_finishOrCancelTransition` should happen some where around or in 
```
- (void)transitionContext:(_ASTransitionContext *)context didComplete:(BOOL)didComplete
```

I've also been logging out the frame changes on the animating node and I can see that it gets set to the final frame and then starts animating from the "fromFrame" taken from the `ASContextTransitioning` during the layout transition.

> Frame changed from (355.0, 0.0, 1000.0, 355.0) to (355.0, 0.0, 1000.0, 355.0)
> Frame changed from (355.0, 0.0, 1000.0, 355.0) to (0.0, 0.0, 1000.0, 355.0)
> Frame changed from (0.0, 0.0, 1000.0, 355.0) to (355.0, 0.0, 1000.0, 355.0)
> Frame changed from (355.0, 0.0, 1000.0, 355.0) to (354.800298881396, 0.0, 1000.0, 355.0)

Any help would be great.

**Comment by hannahmbanana** [comment]
@nguyenhuy @maicki - could one of you triage this? I'm less familiar with the Transition API

**Comment by jellenbogen** [comment]
Hey guys any thoughts on this?

**Comment by nguyenhuy** [comment]
@jellenbogen Do you still see this problem? To be honest, the current layout and transition code paths are a bit messy that these kind of problems can easily occur. We have a plan to improve the current situation using a transactional layout system (#2977). Stay tuned!
