### ISSUE TITLE
ASImageNode rendering black background by default

### ISSUE THREAD

**Issue by kylehickinson** [facebook/AsyncDisplayKit#298]
Just a side-effect of #286: The default value of `opaque` is `YES` ([ASImageNode.mm:L90](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASImageNode.mm#L90)) which is causing images to be rendered with a black background.

Example:
![](http://cl.ly/image/2R440F3k1z45/Image%202015-02-09%20at%2012.16.46%20AM.png)

**Comment by secretiverhyme** [comment]
Nice catch!  I wondered whether that might break something.
