### ISSUE TITLE
UIVisualEffectView-like Node

### ISSUE THREAD

**Issue by christianselig** [facebook/AsyncDisplayKit#2984]
With images and whatnot, dynamically blurring is quite easily done thanks to ASDK's concurrency, but simply adding a blurred view/node that resides atop other views (such as [Control Center](http://i.imgur.com/McNN2JK.png) that is pulled up from the bottom) isn't as easy. 

You could capture the content behind it, then blur that, then add it as a subnode, but that's an arduous process compared to how easy `UIVisualEffectView` makes it. 

I was unable to find any discussion of the possibility of such a node in AsyncDisplayKit, and I'd certainly find it very useful, so I thought I'd inquire about it the possibility of `ASVisualEffectNode`. 😄

**Comment by garrettmoon** [comment]
@christianselig my feeling is that unless there's a reason to create it beyond being a node version, that I would defer to UIKit and just wrap it in a node via the viewBlock API. If there are other reasons to make a node specific version I'd love to hear them!

**Comment by christianselig** [comment]
@garrettmoon Fair enough! I'll look into that, I don't think I've dug deep enough yet.
