### ISSUE TITLE
Remove unused visualizing layout spec code

### ISSUE THREAD

**Issue by maicki** [facebook/AsyncDisplayKit#2990]
Currently we have code around visualizing layout spec code that is not used, but needs to be considered somehow on every change we would like to do.

I would to start a discussion and propose to go on with cleaning up the code base by removing the visualizing code.

This does not mean this is the death of this feature as we would like to find a better way to integrate it that would not interfere so deeply with how the framework is working internally.

Related PR: #2991

**Comment by hannahmbanana** [comment]
Two comments from me on this:
- I think the ability to "visualize" layout specs is still very badly needed by the community (as well as Pinterest). However, my attempt to create a layout visualization feature is only half-baked and not ready for prime-time. I don't think I can bring the ideal feature to fruition, but maybe you or @nguyenhuy could do so now, or in the future. 
- I understand your concern around maintaining a system that isn't actively used and support removing this for now and revisiting with a new / modified approach later on.

**Comment by hannahmbanana** [comment]
I'm going to close this issue and move my comments to the PR.
