### ISSUE TITLE
Not setting ASTableView asyncDelegate causes cell's calculatedSize to be ignored

### ISSUE THREAD

**Issue by mtitolo** [facebook/AsyncDisplayKit#300]
When I create a new ASTableView, if I don't set the asyncDelegate, the size returned from `calculateSizeThatFits:` in a cell is ignored, and the entire table is drawn at the default row height. Setting the delegate (even if it's not being used) fixes the problem.

The tableview should respect the cellnode's calculatedSize regardless of an asyncDelegate being set.

Gist to reproduce: https://gist.github.com/mtitolo/f07460dfa0c7d1b52982
Screenshot:
![ios simulator screen shot feb 9 2015 3 59 57 pm](https://cloud.githubusercontent.com/assets/763698/6118748/adaeb3e8-b075-11e4-989b-a93e52b6b7fb.png)

**Comment by secretiverhyme** [comment]
Thanks for the report! This was fixed in #237, which will be included in the upcoming 1.2 release.
