### ISSUE TITLE
Question: Re-sizing and layout ASTableView without reloading data

### ISSUE THREAD

**Issue by annieso-ck** [facebook/AsyncDisplayKit#301]
I have an ASTableView with cells that contain an ASNetworkImage. I do not know the size of the image until it's downloaded. 

I use the ASNetworkImage delegate method imageNode:didLoadImage to get the height of the image. I then force the cell to re-calculate it's size and layout again.

This all works, however, I now need the ASTableView to re-layout the table to account for the change in size of the particular cell. (I don't want to reload the data, only re-calculate the "row heights" and re-layout).

For UITableView cell, doing

[tableView beginUpdates];
[tableView endUpdates];

would call tableView:heightForRowAtIndexPath and relayout the UITableView without actually reloading any cells. Is there a way to do this for ASTableView?

**Comment by annieso-ck** [comment]
http://stackoverflow.com/questions/28419321/re-layout-astableview-from-asyncdisplaykit-after-downloading-images-using-asnetw

**Comment by secretiverhyme** [comment]
Not yet, unfortunately, though this is something we'd like to add!  ASTableView only sizes cell nodes once and bypasses the standard "height for row at index path" UITableView machinery.  We'd like to build full-featured async resize support, which will likely require new subclass hooks on ASDisplayNode itself (see also #214; cc @rnystrom and @tanliboy).

**Comment by annieso-ck** [comment]
Thanks for the reply! I actually was kind of able to do it by calling 

[asyncTable beginUpdates];
[asyncTable endUpdates];

from the newest changes that were added. 

I noticed that there are a lot of changes being made currently (such as support for beginUpdates and endUpdates) since version 1.1.1. 

When will the new version be released via cocoa pods?

**Comment by secretiverhyme** [comment]
Oh, cool!  Glad that worked, I didn't realise that had already been wired up.

I'm hoping to release AsyncDisplayKit 1.2 in the next week or two.  We have some other major changes in the wings (check out the pull requests tab — we do all ASDK development on GitHub) that we're waiting on.  =]
