### ISSUE TITLE
Please stop highlighting me all the time

### ISSUE THREAD

**Issue by adlai** [facebook/AsyncDisplayKit#3010]
@Adlai-Holler please teach your team to use GitHub properly. I didn't delete my facebook account so I could enjoy daily reminders of its existence.

**Comment by adlai** [comment]
@garrettmoon You are the repeat offender.

**Comment by adlai** [comment]
@Adlai-Holler That was a quick close. I hope @garrettmoon reads this, though.

**Comment by Adlai-Holler** [comment]
Garrett just read that comment. Your hope is fulfilled, friend.

**Comment by maicki** [comment]
@adlai Thanks for reporting!
