### ISSUE TITLE
ASCellNode problem with layout

### ISSUE THREAD

**Issue by kamvoick** [facebook/AsyncDisplayKit#3011]
Hello, i got problem with layout on ascellnode within collectionView. So basically every cell has a size of screen minus top and bottom bar (screenshots are without these bars), every cell has (gray) rectangle - viewUnderImages, and on top there is a stack (wholeStack) contains 2 photos in other stack and user profile image centered through .X axis. And my problem is that I want to hook top of wholeStack to top of viewUnderImages, and i don't know why it's not working, for me it seems like stack do not see viewUnderImages cause also i can't stretch stack with two photos(placeholders) along with width of viewUnderImages. I've been trying to do this for a while now, and got no clue, so hope you help me. Thanks 

here is code of ascellnode:
'class ASMainCell : ASCellNode {
    
    let viewUnderImages : ASDisplayNode = {
        let node = ASDisplayNode()
        node.backgroundColor = whiteColor
        node.cornerRadius = 20
        return node
    }()
    let leftImageNode = ASNetworkImageNode()
    let rightImageNode = ASNetworkImageNode()
    
    let userProfileImage = ASNetworkImageNode()
    
    override init() {
        super.init()

        self.addSubnode(viewUnderImages)
        self.addSubnode(leftImageNode)
        self.addSubnode(rightImageNode)
        
        leftImageNode.defaultImage = CameraPlaceholder.imageOfCameraPlaceholder()
        rightImageNode.defaultImage = CameraPlaceholder.imageOfCameraPlaceholder()
        
        self.addSubnode(userProfileImage)
        userProfileImage.defaultImage = UserProfileImage.imageOfUserProfileImage()
        
    }
    
    override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
        viewUnderImages.style.preferredSize = CGSize(width: constrainedSize.max.width, height: constrainedSize.max.width)
        
        let viewUnderImagesPlace = ASCenterLayoutSpec()
        viewUnderImagesPlace.centeringOptions = .XY
        viewUnderImagesPlace.child = viewUnderImages
        
        let stackLayout = ASStackLayoutSpec.horizontal()
        stackLayout.alignItems = .center
        stackLayout.justifyContent = .center
        stackLayout.spacing = 5
        stackLayout.children = [leftImageNode, rightImageNode]
        
        userProfileImage.style.preferredSize = CGSize(width: 50, height: 50)
        
        let userProfile = ASCenterLayoutSpec()
        userProfile.centeringOptions = .X
        userProfile.child = userProfileImage
        
        let wholeStack = ASStackLayoutSpec.vertical()
        wholeStack.alignItems = .center
        wholeStack.spacing = 10
        wholeStack.children = [userProfile, stackLayout]
        wholeStack.style.alignSelf = .start

        let overlay = ASOverlayLayoutSpec(child: viewUnderImagesPlace, overlay: wholeStack)
    
        return overlay
    }
    
}
'

![zrzut ekranu 2017-02-10 o 15 27 01](https://cloud.githubusercontent.com/assets/19606025/22831126/79d952c4-efa9-11e6-834e-c815f869282b.png)

**Comment by EviluS** [comment]
I replicated your code with Objective C, here is the result with some modifications.

```
#import "Test2Node.h"

@interface Test2Node ()

@property (nonatomic, strong) ASDisplayNode *viewUnderImages;
@property (nonatomic, strong) ASDisplayNode *leftImageNode;
@property (nonatomic, strong) ASDisplayNode *rightImageNode;
@property (nonatomic, strong) ASDisplayNode *userProfileImageNode;

- (void)initializeNodesInNode:(ASDisplayNode *)node;

@end

@implementation Test2Node

#pragma mark - Initialization

- (instancetype)init {
    self = [super init];
    if (self) {
        [self initializeNodesInNode:self];
    }
    return self;
}

#pragma mark - Override

- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {
    CGSize imageSize = CGSizeMake(90, 90);
    [_leftImageNode.style setPreferredSize:imageSize];
    [_rightImageNode.style setPreferredSize:imageSize];
    
    [_userProfileImageNode.style setPreferredSize:CGSizeMake(50, 50)];
    
    ASStackLayoutSpec *imagesStackSpec = [ASStackLayoutSpec horizontalStackLayoutSpec];
    [imagesStackSpec setJustifyContent:ASStackLayoutJustifyContentSpaceBetween];
    [imagesStackSpec setAlignItems:ASStackLayoutAlignItemsCenter];
    [imagesStackSpec setSpacing:5];
    [imagesStackSpec setChildren:@[_leftImageNode, _rightImageNode]];
    
    ASStackLayoutSpec *stackSpec = [ASStackLayoutSpec verticalStackLayoutSpec];
    [stackSpec setJustifyContent:ASStackLayoutJustifyContentSpaceBetween];
    [stackSpec setAlignItems:ASStackLayoutAlignItemsCenter];
    [stackSpec setSpacing:10];
    [stackSpec setChildren:@[_userProfileImageNode, imagesStackSpec]];
    
    ASBackgroundLayoutSpec *backgroundSpec = [ASBackgroundLayoutSpec backgroundLayoutSpecWithChild:stackSpec
                                                                                        background:_viewUnderImages];
    
    return [ASCenterLayoutSpec centerLayoutSpecWithCenteringOptions:ASCenterLayoutSpecCenteringXY
                                                      sizingOptions:ASCenterLayoutSpecSizingOptionDefault
                                                              child:backgroundSpec];
}

#pragma mark - Private Methods

- (void)initializeNodesInNode:(ASDisplayNode *)node {
    [node setAutomaticallyManagesSubnodes:YES];
    
    ASDisplayNode *(^CreateRandomDisplayNode)(void) = ^ASDisplayNode *(void) {
        int red = ((arc4random() % 255) + 1);
        int green = ((arc4random() % 255) + 1);
        int blue = ((arc4random() % 255) + 1);
        
        UIColor *randomColor = [UIColor colorWithRed:red/255.0 green:green/255.0 blue:blue/255.0 alpha:1.0];
        
        ASDisplayNode *randomNode = [[ASDisplayNode alloc] init];
        [randomNode setBackgroundColor:randomColor];

        return randomNode;
    };
    
    _viewUnderImages = CreateRandomDisplayNode();
    _leftImageNode = CreateRandomDisplayNode();
    _rightImageNode = CreateRandomDisplayNode();
    _userProfileImageNode = CreateRandomDisplayNode();
}

#pragma mark - Public Methods

#pragma mark - Delegate

#pragma mark - Properties

@end

```

![alt tag](http://i.imgur.com/ury0AVk.png)

**Comment by kamvoick** [comment]
the same in swift ...
![zrzut ekranu 2017-02-10 o 17 44 22](https://cloud.githubusercontent.com/assets/19606025/22835346/a2fb45ea-efb8-11e6-92c5-524dc77ae1af.png)

but anyway, the idea was to placed these photos and user image based on the size of this gray rectangle, that's why i made it by overlay and though it'll stretch it out

**Comment by kamvoick** [comment]
i don't know how but today everything working good, so i'm closing the issue and provide some code which works for me on a screensize cellnode
   
```
override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
        viewUnderImages.style.preferredSize = CGSize(width: constrainedSize.max.width - 10, height: constrainedSize.max.width - 10)
        
        leftImageNode.style.preferredSize = CGSize(width: constrainedSize.max.width/2 - 12.5, height: constrainedSize.max.width/2 - 12.5)
        rightImageNode.style.preferredSize = CGSize(width: constrainedSize.max.width/2 - 12.5, height: constrainedSize.max.width/2 - 12.5)
        
        let stackLayout = ASStackLayoutSpec.horizontal()
        stackLayout.alignItems = .center
        stackLayout.justifyContent = .center
        stackLayout.spacing = 5
        stackLayout.children = [leftImageNode, rightImageNode]
        
        userProfileImage.style.preferredSize = CGSize(width: 50, height: 50)
        
        let wholeStack = ASStackLayoutSpec.vertical()
        wholeStack.justifyContent = .start
        wholeStack.alignItems = .center
        wholeStack.spacing = 10
        wholeStack.children = [userProfileImage, stackLayout]
        
        let wholeStackInset = ASInsetLayoutSpec(insets: UIEdgeInsetsMake(10, 5, 10, 5), child: wholeStack)

        let overlay = ASOverlayLayoutSpec(child: viewUnderImages, overlay: wholeStackInset)
        
        let wholeSpecCentered = ASCenterLayoutSpec()
        wholeSpecCentered.centeringOptions = .XY
        wholeSpecCentered.child = overlay
    
        return wholeSpecCentered
    }
```
