### ISSUE TITLE
Changing node's supernode unexpected behaviour.

### ISSUE THREAD

**Issue by Kuluum** [facebook/AsyncDisplayKit#3019]
ASDK v2.2 (also tested on 2.1, 2.0, 2.0.1, 2.0.2)
Should be tested on iPhone.

Case: Trying to show different layout in portrait and landscape. In landscape image placed on root node, but in portrait it placed on proxy node that placed on root node.

Ascii pic for better understanding:

Portrait:

```
 ----ASStackLayoutSpec-----
|   ---ASDisplayNode---    |
|  |   ASImageNode     |   |
|  |    ASTextNode     |   |
|   --------------------   |
---------------------------
```

Landscape:

```
-------------ASStackLayoutSpec-----------
|                ---ASDisplayNode---    |
| ASImageNode   |   ASTextNode      |   |
|                -------------------    |
-----------------------------------------
```

Q: Why you use that proxy node? It has no sense there.
A: The real case was that proxy node was ASScrollNode or ASTableNode. So in portrait all content was scrollable but in landscape only text was scrollable, image had fixed position. In ascii pic and sample project I use simple ASDisplayNode for more clarity.

After that case was implemented I see such a problem - image node visible only in portrait. I suspect it is because of parent changing while layout, but I could be wrong.

Sample project: https://github.com/Kuluum/ASDKParrentChangingIssueSample

**Comment by Kuluum** [comment]
Upd: Reproduced on 2.2

**Comment by maicki** [comment]
@Kuluum Hey! Could you take me a favor and check if the linked PR will resolve your issue. It did on my side testing with your sample project, what was very valuable! Thanks!

**Comment by Kuluum** [comment]
@maicki Ok, will check it ASAP :)

**Comment by Kuluum** [comment]
@maicki Checked this fix in production code with real case that I have. It seems to be worked fine now! Great!
