### ISSUE TITLE
ASCollectionNode scroll stop after insertItemsAtIndexPaths completeBatchFetching 

### ISSUE THREAD

**Issue by ebrahimsavadinejad** [facebook/AsyncDisplayKit#3020]
Hi ,
I'm create ASCollectionNode and begin to fetch data in willBeginBatchFetchWithContext :

`- (void) collectionNode:(ASCollectionNode *)collectionNode willBeginBatchFetchWithContext:(ASBatchContext *)context
{
    [self getTagsWithCompletion:^(BOOL finished) {
        [context completeBatchFetching:YES];
    }];
}`

and when data is coming i use below code to insert item in to collectionNode:

`dispatch_async(dispatch_get_main_queue(), ^{
        [_collectionNode performBatchAnimated:YES updates:^{
            [_collectionNode insertItemsAtIndexPaths:indexPaths];
        } completion:completion];
    });`

every thing's is okey but scrolling stop strangely after cell was inserted and user not have a good experience and most scroll down again.
how can i fix this behavior?

**Comment by QuynhNguyen** [comment]
I am seeing the same issue when doing the following. It seems like the collectionView doesn't account for the new item or using `estimatedHeight` instead of the cell `intrinsicContentSize`

```
            self.collectionNode.reloadData()
            self.collectionNode.performBatchUpdates({}, completion: { finished in
                DispatchQueue.main.async {
                    if let index = self.comments?.index(of: comment) {
                        self.collectionNode.scrollToItem(at: IndexPath(row: index, section: 0), at: .top, animated: true)
                    }
                }
            })
```

**Comment by QuynhNguyen** [comment]
This issue seems to be related to https://github.com/facebook/AsyncDisplayKit/issues/2546

**Comment by ebrahimsavadinejad** [comment]
@QuynhNguyen tanx
