### ISSUE TITLE
More example for swift 3 :D

### ISSUE THREAD

**Issue by buiminhhuy** [facebook/AsyncDisplayKit#3027]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack

// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// AsyncDisplayKit version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

**Comment by MarvinNazari** [comment]
@buiminhhuy: All examples have been updated to Swift 3

**Comment by buiminhhuy** [comment]
@MarvinNazari, yes I saw, but if can help me convert all example objective-c to swift 3. I am difficult when implement base on Objective-C example

**Comment by MarvinNazari** [comment]
@buiminhhuy is there anything special that you need help with?

**Comment by buiminhhuy** [comment]
Ok I will verify later, I am attend convert my project to use AsyncDisplayKit.
