### ISSUE TITLE
LayoutSpecThatFits returns 0 constrained size depending on subnodes

### ISSUE THREAD

**Issue by fruitcoder** [facebook/AsyncDisplayKit#3034]
I have a cell node with an `ASNetworkImageNode` and some `ASTextNode`s. The image node is sized based on the available width and the ratio is 16/9.
It looked somewhat like this:
```
 override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
    let width = constrainedSize.min.width
    imageNode.style.width = ASDimension(unit: .points, value: width)
    imageNode.style.height = ASDimension(unit: .points, value: 9.0/16.0 * width)

    let verticalLayout = ASStackLayoutSpec()
    verticalLayout.direction = .vertical
    verticalLayout.justifyContent = .start
    verticalLayout.alignItems = .stretch
    verticalLayout.spacing = 8.0
    verticalLayout.children = [imageNode, textNode1, textNode2]

    return verticalLayout 
}
```

This all worked without any issues, but now I want to have the image in an extra cell node (for different reasons). I thought I could just do something like this:

```
class ImageNode: ASCellNode {
  let imageNode: ASNetworkImageNode
  
  init(imageUrl: URL) {
    
    imageNode = ASNetworkImageNode()
    imageNode.url = imageUrl
    imageNode.isLayerBacked = true
    imageNode.contentMode = .scaleAspectFit
    
    super.init()
    
    automaticallyManagesSubnodes = true
    selectionStyle = .none
  }
  
  override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
    let width = constrainedSize.min.width
    imageNode.style.width = ASDimension(unit: .points, value: width)
    imageNode.style.height = ASDimension(unit: .points, value: 9.0/16.0 * width)
    return ASInsetLayoutSpec(insets: .zero, child: imageNode))
  }
}
```

The problem is that `width` is always `0`. When comparing the cells calls to `layoutSpecThatFits:constrainedSize:` I noticed that both cells had two calls with `constrainedSize.min.width = 0`. But the original cell node had one more call which looked like this:
 
![screen shot 2017-02-15 at 14 15 42](https://cloud.githubusercontent.com/assets/5515849/22977647/d1716cee-f38f-11e6-81be-06acee2e87f3.png)

This resulted in the correct width from the `tableNode`. When rotating the device everything works well, but the initial load just produces a zero sized cell node.
Any ideas what might be the issue?

**Comment by EviluS** [comment]
@fruitcoder I may be completely wrong but isn't `constrainedSize.min` supposed to be CGSizeZero. You could try using the `max.width` for your layout.

**Comment by fruitcoder** [comment]
I have a "pure" ASViewController which calls `super.init` with the `ASTableNode` and the `ImageNode` is returned inside the `tableNode:nodeBlockForRowAt:` block, so there is no intermediate cell node.

**Comment by fruitcoder** [comment]
I get this from the `constrainedSize`
![screen shot 2017-02-15 at 22 11 41](https://cloud.githubusercontent.com/assets/5515849/22995709/3b503834-f3cc-11e6-8ada-1b6a261885b9.png)

**Comment by EviluS** [comment]
@fruitcoder This is strange. I recreated your case and it works fine. Here is my implementation.

`Implementation of ASViewController Subclass`
```
#import "TableTestViewController.h"
#import "TestTableCell.h"

@interface TableTestViewController () <ASTableDelegate, ASTableDataSource>

@property (nonatomic, readonly) ASTableNode *tableNode;

@end

@implementation TableTestViewController

#pragma mark - Initialization

- (instancetype)init {
    ASTableNode *tableNode = [[ASTableNode alloc] initWithStyle:UITableViewStylePlain];
    
    self = [super initWithNode:tableNode];
    if (self) {
        [self.tableNode setDelegate:self];
        [self.tableNode setDataSource:self];
    }
    return self;
}

#pragma mark - Override

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma ASTableDataSource

- (NSInteger)tableNode:(ASTableNode *)tableNode numberOfRowsInSection:(NSInteger)section {
    return 5;
}

- (ASCellNodeBlock)tableNode:(ASTableNode *)tableNode nodeBlockForRowAtIndexPath:(NSIndexPath *)indexPath {
    ASCellNodeBlock nodeBlock = ^ASCellNode * _Nonnull{
        TestTableCell *cell = [[TestTableCell alloc] init];
        [cell setBackgroundColor:[UIColor yellowColor]];
        
        return cell;
    };
    
    return nodeBlock;
}

#pragma mark - Properties

- (ASTableNode *)tableNode {
    return (ASTableNode *)self.node;
}

@end
```

`Implementation of ASCellNode subclass`

```
#import "TestTableCell.h"

@interface TestTableCell ()

@property (nonatomic, strong) ASNetworkImageNode *imageNode;
@property (nonatomic, strong) ASTextNode *textNode1;
@property (nonatomic, strong) ASTextNode *textNode2;

@end

@implementation TestTableCell

#pragma mark - Initialization

- (instancetype)init {
    self = [super init];
    if (self) {
        [self setAutomaticallyManagesSubnodes:YES];
        
        _imageNode = [[ASNetworkImageNode alloc] init];
        [_imageNode setContentMode:UIViewContentModeScaleAspectFit];
        [_imageNode setLayerBacked:YES];
        [_imageNode setURL:[NSURL URLWithString:@"https://pbs.twimg.com/media/Cz80ljNUQAADbnC.jpg"]];
        
        ASTextNode *(^CreateTextNodeWithText)(NSString *) = ^ASTextNode *(NSString *text) {
            UIFont *font = [UIFont fontWithName:@"HelveticaNeue" size:12];
            UIColor *textColor = [UIColor redColor];
            
            NSDictionary *attrs = @{NSFontAttributeName : font,
                                    NSForegroundColorAttributeName : textColor};
            
            NSAttributedString *attrString = [[NSAttributedString alloc] initWithString:text attributes:attrs];
            
            ASTextNode *textNode = [[ASTextNode alloc] init];
            [textNode setAttributedText:attrString];
            [textNode setMaximumNumberOfLines:0];
            
            return textNode;
        };
        
        _textNode1 = CreateTextNodeWithText(@"First Text Node");
        _textNode2 = CreateTextNodeWithText(@"Second Text Node\nSecond line");
    }
    return self;
}

#pragma mark - Override

- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {
    CGFloat width = constrainedSize.min.width;
    
//    _imageNode.style.width = ASDimensionMake(width);
//    _imageNode.style.height = ASDimensionMake(9.0/16.0 * width);
    
    ASRatioLayoutSpec *ratioSpec = [ASRatioLayoutSpec ratioLayoutSpecWithRatio:16.0/9.0 child:_imageNode];
    [ratioSpec.style setMaxHeight:ASDimensionMake((9.0/16.0) * width)];
    
    ASInsetLayoutSpec *(^InsetSepcForNode)(ASDisplayNode *) = ^ASInsetLayoutSpec *(ASDisplayNode *insetNode) {
        return [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 14, 0, 14)
                                                      child:insetNode];
    };
    
    ASStackLayoutSpec *stackSpec = [ASStackLayoutSpec verticalStackLayoutSpec];
    [stackSpec setJustifyContent:ASStackLayoutJustifyContentStart];
    [stackSpec setAlignItems:ASStackLayoutAlignItemsStretch];
    [stackSpec setSpacing:8];
    [stackSpec setChildren:@[ratioSpec, InsetSepcForNode(_textNode1), InsetSepcForNode(_textNode2)]];
    
    return [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 0, 8, 0) child:stackSpec];
}

@end

```
![simulator screen shot feb 16 2017 11 31 02 am](https://cloud.githubusercontent.com/assets/749280/23015471/a149afca-f43b-11e6-8596-6b72d6d3111a.png)

**Comment by fruitcoder** [comment]
Yeah, that worked for me too, but try separating the image node into its own cell node! So you have an image cell node and a text cell node

**Comment by EviluS** [comment]
@fruitcoder I updated my last comment with the changes and it still works the same as expected.

**Comment by fruitcoder** [comment]
Thanks for checking that out, I'll whether there is anything different in my setup.

**Comment by EviluS** [comment]
No problem I will be happy if this helps solving the problem :)

**Comment by fruitcoder** [comment]
I thought it's because I push the view controller in a navigation controller but this bare project doesn't work as well :/

https://www.dropbox.com/s/8u2u7cjw4zo0exw/ASDK_ImageNode.zip?dl=0

**Comment by EviluS** [comment]
@fruitcoder I found the problem. You are calling `node.reloadData()` in `viewDidLoad()`. There is no need to call `reloadData()` for the initial load of the table node.

**Comment by fruitcoder** [comment]
What the ... Thank you SO MUCH! But is that a bug? Calling `reloadData()` should never be destructive, just a small performance hit right? (that's what I'm used to in UIKit)

**Comment by EviluS** [comment]
Actually no it is different from the `UIKit` version.

```
/**
 * Reload everything from scratch, destroying the working range and all cached nodes.
 *
 * @warning This method is substantially more expensive than UITableView's version.
 */
- (void)reloadData;
```

**Comment by fruitcoder** [comment]
Thanks for pointing that out... The reason why I called `reloadData()` in `viewDidLoad` was that I want a transition from a previous viewcontroller's image view to the image node, so before pushing the view controller I call `loadViewIfNeeded()` to make sure the cell node with the image node is visible and has a valid frame. As you pointed out, this causes the image node to have a `.zero` frame. Is there any way I can force an `ASViewController` to layout its views (synchronously) or give a callback when it's finished so I can start the transition?

**Comment by EviluS** [comment]
What do you want to achieve, something with `UIViewControllerAnimatedTransitioning` API?

**Comment by fruitcoder** [comment]
Exactly 👍

**Comment by fruitcoder** [comment]
And for that the target image node's frame needs to be correct when I start the transition so I can interpolate between the views frames

**Comment by EviluS** [comment]
@fruitcoder Would you like to PM me in Slack and discuss the issue? (my nick is `gpetrov` there)

**Comment by fruitcoder** [comment]
Sure

**Comment by fruitcoder** [comment]
Since the original question was answered thanks to @EviluS I will close the issue and eventually open a new one which targets the questions that came up during the discussion.
