### ISSUE TITLE
Rotating ASDKgram Causes Crash

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#3038]
You have to first scroll down a few photos, and then rotate.

Reported by @ay8s on Slack.

**Comment by appleguy** [comment]
If I read the thread correctly, this is the crash:

![](https://files.slack.com/files-pri/T0V4MUTCK-F47CFMS5D/screen_shot_2017-02-16_at_10.55.51_am_720.png)
