### ISSUE TITLE
Loading Animated Image into ASNetworkImageNode causes crash

### ISSUE THREAD

**Issue by ay8s** [facebook/AsyncDisplayKit#3040]
Loading an animated image into an ASNetworkImageNode is causing an assertion as ASNetworkImageNode no longer excepts setting an image directly without setting the URL to nil first. coverImageCompleted: within ASImageNode+AnimatedImage is setting the image directly.

ASNetworkImageNode Assert: https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASNetworkImageNode.mm#L119

ASImageNode+AnimatedImage: https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASImageNode%2BAnimatedImage.mm#L94

**Comment by garrettmoon** [comment]
Thank you for reporting! Will address ASAP!

**Comment by ay8s** [comment]
Fixed with https://github.com/facebook/AsyncDisplayKit/commit/4e779eeed8b79e6d2c2b20ebef03431022725e25

**Comment by maicki** [comment]
Thanks @garrettmoon for addressing and @ay8s for reporting!
