### ISSUE TITLE
How could i add a  refreshing header for ASTableNode 

### ISSUE THREAD

**Issue by KKKiller** [facebook/AsyncDisplayKit#3043]
My project was use MJRefresh to refresh, when i use ASTableNode, how could  i add a  refreshing header for ASTableNode

**Comment by EviluS** [comment]
@KKKiller one option which I am using is to implement the following logic.
(Assuming you have a plain one sectioned table)

When your table reaches the top or the bottom you insert a new section at index `0` or `n + 1` (depending on the loading position) with one cell which will display the `Loading UI`. Once you are finished loading you delete that section. 

Another option is to add a `subnode` behind the table and only show it when the `update` criteria is met but with that approach you will have to deal with `table offset` manually.

Or you can always try other libraries like `MJRefresh` and see if they work with `AsyncDisplayKit`

**Comment by ay8s** [comment]
@KKKiller You should still be able to use MJRefresh. Not used it personally but looking at their samples you should be able to just tweak how you add it to use self.tableNode.view which gives you the UITableView.

For example their 1st example would become...
```
self.tableNode.view.header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
   //Call this Block When enter the refresh status automatically 
}];

// Set the callback（Once you enter the refresh status，then call the action of target，that is call [self loadNewData]）
self.tableNode.view.header = [MJRefreshNormalHeader headerWithRefreshingTarget:self refreshingAction:@selector(loadNewData)];

// Enter the refresh status immediately
[self.tableNode.view.header beginRefreshing];```
