### ISSUE TITLE
Truncat tapped doesn't work

### ISSUE THREAD

**Issue by buiminhhuy** [facebook/AsyncDisplayKit#3052]
I declare add-in in existed example 

`self.photoDescriptionLabel.attributedText = photoModel.attrStringForDescription(withSize: Constants.CellLayout.FontSize)

        self.photoDescriptionLabel.maximumNumberOfLines = 2

        let attr = [
            NSForegroundColorAttributeName : UIColor.blue,
            NSFontAttributeName: UIFont.systemFont(ofSize: Constants.CellLayout.FontSize)
        ]

        let attributedString = NSMutableAttributedString(string: " Read More...", attributes: attr)

        self.photoDescriptionLabel.truncationAttributedText = attributedString

        self.photoDescriptionLabel.delegate = self
        `
But when I handle this method, it doesn't work

`
extension PhotoTableNodeCell: ASTextNodeDelegate {

    func textNodeTappedTruncationToken(_ textNode: ASTextNode) {
        print("test click on truncat read more")
    }
}

`

**Comment by buiminhhuy** [comment]
to method textNodeTappedTruncationToken  work fine, I chit code by add this
`self. photoDescriptionLabel.addTarget(self, action: #selector(testClick), forControlEvents: .touchUpInside)`

**Comment by maicki** [comment]
@buiminhhuy You have to set `userInteractionEnabled` to `true` and change the declaration for the `ASTextNode` delegate method (in case you target Swift 2.3 and above):

```
self.photoDescriptionLabel.delegate = self
self.photoDescriptionLabel.userInteractionEnabled = true
```

```
func textNodeTappedTruncationToken(textNode: ASTextNode) {
    print("test click on truncat read more")
}
```

**Comment by buiminhhuy** [comment]
Work fine. Thanks @maicki
