### ISSUE TITLE
[ASPagerNode] Create an intelligent-preloading pager component

### ISSUE THREAD

**Issue by secretiverhyme** [facebook/AsyncDisplayKit#306]
This has been on the to-do list for a while — currently targeting AsyncDisplayKit 1.3.

ASPageNode would be a pure-node (not ASCollectionView or ASTableView-based) paging horizontal-scroll component, suitable for use in ASCellNode (see #133).

**Comment by nttravn** [comment]
Wait AsyncDisplayKit 1.3

**Comment by aaronschubert0** [comment]
@appleguy Woohoo 2.1 milestone! This is definitely one the top of my wish list. Let me know if you need any testing/feedback help.

**Comment by appleguy** [comment]
Finally getting around to closing out some of these older (resolved) open issues. :) ASPagerNode is available in the current build, thanks to Levi (#925)! @aaronschubert0 and others - please use it and file any potential issues you find / feedback you have!

**Comment by aaronschubert0** [comment]
@appleguy Was thinking we should close older issues just yesterday! You & @levi will be happy to know, we're using ASPagerNode extensively already :)
