### ISSUE TITLE
[ASRangeController] Union all rects to make only one call to layoutAttributesForElementsInRect:

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#3082]
UICollectionViewLayout overhead, especially creating layout attributes, has always been the most significant portion of ASRangeController's cost.  It is a much smaller cost than the many savings provided by the Collection, Table, and Pager — but their main thread footprint can contribute to frame drops on the slowest devices.

I realized this can be substantially reduced.  Instead of making 3 calls for Visible, Display, and Preload — we should union all these rects to create one large one.

- Obtain the scroll coordinates rect for each range. This depends only on bounds.origin (contentOffset) and bounds.size (viewport size), and the tuning parameters for each range.
- Union all of these rects and request the layoutAttributes for this one rect.
- With all the layoutAttributes in hand, iterate over each layoutAttribute (once).
- For each layoutAttribute, intersect its frame with ALL of the range rects, one at a time.
- For each rect it has a nonzero intersection with, add the attributes.indexPath to a set.

I think this change would largely have to be in ASCollectionLayoutController.  Although it would affect internal API, it should be a remarkably straightforward change for the magnitude of the win it can provide.  From my testing, this could save almost 10% of all time spent on the main thread.

**Comment by appleguy** [comment]
@maicki @Adlai-Holler @nguyenhuy, since every one of us has worked on ASRangeController, I'm curious for your very quick thoughts: does this seem possible, or am I missing something?

**Comment by Adlai-Holler** [comment]
LOL I implemented this over the weekend, I'll open a diff soon.

**Comment by appleguy** [comment]
@Adlai-Holler ha, awesome cleanup!  Massive velocity :).

I also ended up doing this the day after filing...not sure which change is more efficient, but let's compare notes.

**Comment by Adlai-Holler** [comment]
Resolved in #3102
