### ISSUE TITLE
Exception in ASGetElementInTwoDimensionalArray triggered by [ASTableView deselectRowAtIndexPath:animated:]

### ISSUE THREAD

**Issue by maicki** [facebook/AsyncDisplayKit#3085]
`examples/ASViewController` currently raises an exception in `ASGetElementInTwoDimensionalArray` triggered by a call from `[ASTableView deselectRowAtIndexPath:animated:]` in `viewWillAppear:`. 

[Console Log](https://github.com/facebook/AsyncDisplayKit/files/802539/exception.txt)

cc @Adlai-Holler

**Comment by Adlai-Holler** [comment]
Resolved in #3090
