### ISSUE TITLE
[ASCellNode initialize] crash

### ISSUE THREAD

**Issue by ArmandsB** [facebook/AsyncDisplayKit#3089]
Hello. I noticed that our app in some cases crashes at this line @ ASCellnode.mm (325):

```
+ (void)initialize
{
  [super initialize];
  if (ASSubclassOverridesSelector([ASCellNode class], self, @selector(cellNodeVisibilityEvent:inScrollView:withCellFrame:))) {
    if (__cellClassesForVisibilityNotifications == nil) {
      __cellClassesForVisibilityNotifications = [NSMutableSet set];
    }
    
    [__cellClassesForVisibilityNotifications addObject:self]; // This one
  }
  
}

```

Noticed, that `+ (void)initialize` is called in background thread and ASKIT are mutating static NSMutableSet variable **__cellClassesForVisibilityNotifications**, which is not thread safe.

I am not expert at multi-threading, but should not there be some kind of lock?

**Comment by Adlai-Holler** [comment]
Good call @ArmandsB ! I've modified the offending code!
