### ISSUE TITLE
[!] Unable to satisfy the following requirements:

### ISSUE THREAD

**Issue by codesourse** [facebook/AsyncDisplayKit#3110]
[!] Unable to satisfy the following requirements:

- `PINRemoteImage (= 3.0.0-beta.7)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `PINRemoteImage (= 3.0.0-beta.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by maicki** [comment]
@codesourse Hey, I don' really understand what you want to say with this issue? Could you please give us more details? Which version of ASDK are you using? Do you try to run an example project? etc.

**Comment by codesourse** [comment]
Thank you,I have solved it.It's cocoapods problem.

do 
sudo rm -fr ~/.cocoapods/repos/master

pod setup

sudo rm -fr ~/Library/Caches/CocoaPods/

**Comment by maicki** [comment]
@codesourse Great I will close this issue than.
