### ISSUE TITLE
swift 3 with ASButotnNode ?

### ISSUE THREAD

**Issue by iOSUser110** [facebook/AsyncDisplayKit#3126]
Can you provide this sample of socialAppLayout with swift 3 and use of ASButtonNode ?

**Comment by hannahmbanana** [comment]
@iOSUser110 - Have you checked out the ASButtonNode documentation? It should have swift snippets: http://asyncdisplaykit.org/docs/button-node.html

**Comment by maicki** [comment]
Hey @iOSUser110 as @hannahmbanana mentioned our documentation has all of the sample code in Swift too: http://asyncdisplaykit.org/docs/button-node.html

Furthermore here is a quick snippet how to initialize and add an `ASButtonNode` to another node:

```swift
let buttonNode = ASButtonNode()
buttonNode.setTitle("Some Title", withFont: nil, withColor: .blueColor(), forState: .Normal)
buttonNode.addTarget(self, action: #selector(TailLoadingCellNode.buttonPressed(_:)), forControlEvents: .TouchUpInside)
self.addSubnode(buttonNode)
```
