### ISSUE TITLE
Question: Is there a way to have a collection view in an ASDisplayNode?

### ISSUE THREAD

**Issue by annieso-ck** [facebook/AsyncDisplayKit#314]
I want to create a node that has a ASCollectionView inside along with other ASDisplayNode components. Is this possible?

**Comment by rnystrom** [comment]
This is definitely something we hear a lot (see #133). There are plans to support this eventually.

You might be able to manually embed by doing something like `[node.view addSubview:collectionView]`, but we've heard varying results on how that works.

**Comment by secretiverhyme** [comment]
You can also create a wrapper node…

```objective-c
ASDisplayNode *collectionNode = [[ASDisplayNode alloc] initWithViewBlock:UIView *^{
  return [[ASCollectionView alloc] init];
}];
```

…and cast its `.view` property to set its data source…

```objective-c
ASCollectionView *collectionView = (ASCollectionView *)collectionNode.view;
collectionView.asyncDataSource = self;
```

…but for the reasons described in #133, neither of these solutions work well, especially in ASCellNodes.  We hope to improve this soon!
