### ISSUE TITLE
How to set the subview superview multiplied?

### ISSUE THREAD

**Issue by aimobier** [facebook/AsyncDisplayKit#3141]
````
asyncdisplaykit 2.1
````

![cbca2f68-b91c-43d1-9bb9-81d1fbc5b07b](https://cloud.githubusercontent.com/assets/6121524/23601865/937597dc-0288-11e7-8d95-943968bec9ac.png)

How to make this layout? Is the child of the parent view 1/3?

**Comment by maicki** [comment]
Hey @aimobier we are using Github Issues for all bug tracking. If you are having difficulties using AsyncDisplayKit or have a question about usage, please ask a question in our Slack channel: http://asyncdisplaykit.org/slack.html Thanks!
