### ISSUE TITLE
UIActivityIndicatorView in cell of ASPagerNode disappears after first display (v2.2)

### ISSUE THREAD

**Issue by aaronash** [facebook/AsyncDisplayKit#3142]
I have an ASPagerNode with custom cells, with a `UIActivityIndicatorView` centered in each cell. When scrolling to the right, and the cell first loads, the spinner is visible. When scrolling to the left, back to cells that have already been displayed once, the spinner is gone.

Works initially:
![simulator screen shot mar 6 2017 15 12 13](https://cloud.githubusercontent.com/assets/163569/23611365/9701fc14-027f-11e7-9c02-7bed85486aee.png)
Then disappears! Magic trick:
![simulator screen shot mar 6 2017 15 12 15](https://cloud.githubusercontent.com/assets/163569/23611367/99f26a26-027f-11e7-9a80-944b7827a062.png)

Is this a usage error or a bug? When I replace the `UIActivityIndicatorView` with a normal `UIView` with a background color, the view remains visible as expected. I'm using ASDK version 2.2 from cocoapods.

Demo project: https://github.com/aaronash/ActivityIndicatorASDKPagerNode

Relevent node code:
```obj-c
@implementation FullscreenCellNode

- (id)init {
    self = [super init];
    if (self != nil) {
        
        self.spinnerNode = [[ASDisplayNode alloc] initWithViewBlock:^UIView * _Nonnull {
            UIActivityIndicatorView *spinner = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhiteLarge];
            [spinner sizeToFit];
            [spinner startAnimating];
            spinner.backgroundColor = [UIColor clearColor];
            NSLog(@"spinner: %@", spinner);
            return spinner;
            
            //it seems like this view doesn't disappear
//            UIView *purple = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
//            purple.backgroundColor = [UIColor purpleColor];
//            return purple;
        }];
        
        _spinnerNode.style.preferredSize = CGSizeMake(37, 37);
        
        self.backgroundColor = [UIColor orangeColor];
        self.automaticallyManagesSubnodes = true;
    }
    return self;
}

- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {
    return [ASCenterLayoutSpec centerLayoutSpecWithCenteringOptions:ASCenterLayoutSpecCenteringXY
                                                      sizingOptions:ASCenterLayoutSpecSizingOptionDefault
                                                              child:_spinnerNode];
}

@end
```

**Comment by EviluS** [comment]
@aaronash There is no error or bug. Try adding `[spinner setHidesWhenStopped:NO];` inside the `initWithViewBlock:` block and you will see that the `UIActivityIndicatorView` is there but not animating.

The solution is to adopt the `ASPagerDelegate` and implement `willDisplayItemWithNode:` and `didEndDisplayingItemWithNode:` methods. And inside these methods you call either `startAnimating` or `stopAnimating`. Make sure your interactions with the `UIActivityIndicatorView ` happen on the main thread.

**Comment by maicki** [comment]
Ok this is pretty interesting ...

The problem is that if a `UICollectionViewCell` is getting it's `prepareForReuse` call it calls `_removeAllAnimations`. This will remove the animation for the `UIActivityIndicatorView` as it's overwriting this method and `stopAnimating` is called. If the `UIActivityIndicatorView` has `hidesWhenStopped` set to `YES` as it's by default the `UIActivityIndicatorView` will just disappear. Otherwise if you set `hidesWhenStopped` to `NO` the view will stay but the animation is gone.

You have multiple solutions ...
1. For now what you can do is overwrite `didEnterVisibleState` and `startAnimating` the `UIActivityIndicatorView` again:

```objc
- (void)didEnterVisibleState
{
    [super didEnterVisibleState];

    // Find a better way as just casting ... but I think you get the idea
    [((UIActivityIndicatorView *)self.spinnerNode.view) startAnimating];
}
```

2. Described by @EviluS

**Comment by aaronash** [comment]
@EviluS @maicki Both of you answered this very well, thank you! I like the `didEnterVisibleState` method more for now, but glad to learn about the `ASPagerDelegate` also.

Closing issue. Thanks again.
