### ISSUE TITLE
subviews layout

### ISSUE THREAD

**Issue by CHENDONGY** [facebook/AsyncDisplayKit#3147]
* How to set layout the subview in ASViewController

* If the use of frame layout, the performance of any impact?

* If you use the Layout Specs layout, I need to use the methods in the ASViewController

**Comment by maicki** [comment]
Hey @CHENDONGY we are using Github Issues for all bug tracking. If you are having difficulties using AsyncDisplayKit or have a question about usage, please ask a question in our Slack channel: http://asyncdisplaykit.org/slack.html
