### ISSUE TITLE
[ASDisplayNode] Replace the working range window with manual display system.

### ISSUE THREAD

**Issue by rnystrom** [facebook/AsyncDisplayKit#315]
*Capturing enhancement discussions*

Create an enum for `ASDisplayNode` that captures the current state of a node in its lifecycle.

>blank slate -> data loaded (changing this calls -invalidateCalculatedSize, eg the attributed string or image property) -> measurement -> layout -> rendering -> all done

The node can react to what happens at each state change, and other mechanisms (such as ranges) can rely on the state and changes in order to perform certain actions.

Changes should be rolled out into phases:

- Create enum & flag on `ASDisplayNode` that is changed in appropriate methods. Flag reflects state in node lifecycle.
- React to state changes
- Wire up ranges and any other mechanisms that can piggy-back off changes
- Remove Core Animation hooks and instead rely on state changes

Any more thoughts?

**Comment by appleguy** [comment]
Important history / context is in https://github.com/facebook/AsyncDisplayKit/pull/371

**Comment by appleguy** [comment]
This is finally happening: #828

**Comment by appleguy** [comment]
This is completely implemented and has been used in the stable version of the framework for several months. Definitely a huge and very important improvement
