### ISSUE TITLE
ASMultiplexImageNode How to load gif

### ISSUE THREAD

**Issue by mydubhe** [facebook/AsyncDisplayKit#3150]
// - AsyncDisplayKit (2.0.1):
    - AsyncDisplayKit/PINRemoteImage (= 2.0.1)
  - AsyncDisplayKit/Core (2.0.1)
  - AsyncDisplayKit/PINRemoteImage (2.0.1):
    - AsyncDisplayKit/Core
    - PINRemoteImage/iOS (= 3.0.0-beta.7)
    - PINRemoteImage/PINCache
 - PINCache (3.0.1-beta.2):
    - PINCache/Arc-exception-safe (= 3.0.1-beta.2)
    - PINCache/Core (= 3.0.1-beta.2)
  - PINCache/Arc-exception-safe (3.0.1-beta.2):
    - PINCache/Core
  - PINCache/Core (3.0.1-beta.2)
  - PINRemoteImage/Core (3.0.0-beta.7)
  - PINRemoteImage/iOS (3.0.0-beta.7):
    - PINRemoteImage/Core
  - PINRemoteImage/PINCache (3.0.0-beta.7):
    - PINCache (= 3.0.1-beta.2)
    - PINRemoteImage/Core

self.imageURLs = @{@“original":@"http://wx3.sinaimg.cn/woriginal/6628711bgy1fdfmakys8og208w050b2e.gif”};,
ASMultiplexImageNode *imageNode = [[ASMultiplexImageNode alloc] initWithCache:nil downloader:[ASPINRemoteImageDownloader sharedDownloader]];
self.downloadsIntermediateImages = YES;
self.imageIdentifiers =@[@"original"];        
self.dataSource = self;
self.delegate = self;
[self.view addSubnode:imageNode];

#pragma mark ASMultiplexImageNodeDataSource
- (NSURL *)multiplexImageNode:(ASMultiplexImageNode *)imageNode URLForImageIdentifier:(ASImageIdentifier)imageIdentifier {
    return [NSURL URLWithString:self.imageURLs[imageIdentifier]];
}

**Comment by maicki** [comment]
Hey @mydubhe we are using Github Issues for all bug tracking. If you are having difficulties using AsyncDisplayKit or have a question about usage, please ask a question in our Slack channel: http://asyncdisplaykit.org/slack.html Thanks!
