### ISSUE TITLE
Bad rendering quality on simulated screen scale

### ISSUE THREAD

**Issue by 9you** [facebook/AsyncDisplayKit#3152]
I'm using ASDK version`2.2` to rewrite my app. Our app is an `iPhone-only` app. And when I try running my app on iPad Mini, parts which was re-written using ASDK output very low quality graphics. Please see attached images. I think there was some problem with screen scale. When I switch my app to `Universal`, everything render just fine. Please help!

![untitled-1](https://cloud.githubusercontent.com/assets/16769449/23745338/673c59d0-04ea-11e7-900d-45d080665cfd.png)

**Comment by Kaspik** [comment]
I think I quite don't understand. If app is iPhone only and you run it on iPad - yes, universal is correct.

But, why you are trying iPhone only app on iPad?

**Comment by maicki** [comment]
Hey @9you this is the default behavior as iPhone only apps are getting upscaled on an iPad. I will close this issue for now, for further questions please ask in your Slack channel: http://asyncdisplaykit.org/slack.html Thanks!
