### ISSUE TITLE
IGListKit updates causing collection node to flash instead of animating updates smoothly.

### ISSUE THREAD

**Issue by ay8s** [facebook/AsyncDisplayKit#3163]
With the latest ASDK from master when removing updates from a collectionNode via the listAdapter performUpdatesAnimated:completion: method I'm seeing some animate smoothly and others cause a flash of the whole collectionNode. In some cases the flash only occurs in cells after the one that was removed. 

Tried using ea09ad75eff676c3693fece49c1f9bbc705801a6 which is prior to the ASDataController refactor and I don't see the same behavior, I haven't however gone through and checked if that is definitely the root cause.

Definitely feels intermittent, did think it may have to do with how many items were in a collection however I've not found anything consistent.

**Comment by nguyenhuy** [comment]
@ay8s are you seeing flashes similar to [this](https://github.com/facebook/AsyncDisplayKit/issues/2536#issuecomment-285351461)? Please try disabling placeholders of all cell nodes.

**Comment by ay8s** [comment]
@nguyenhuy Exactly like that however when setting neverShowPlaceholders to YES on update nodes I seem to see the same behavior where some removals will animate with animation and others with a flash.

**Comment by nguyenhuy** [comment]
@ay8s I'd appreciate some more details. What updates (i.e removals or reloads) are issued to your collection view? One way to get this information is printing out the change set provided in `-ASDataController:updateWithChangeSet:`. I'm also interested in the `animated` BOOL of each change set.

On the other hand, if you could modify an example (e.g ASDKgram) to produce the same problem, I can jump on it and start debugging right away. Thanks!

**Comment by davitPiloyan93** [comment]
@nguyenhuy After Setting neverShowPlaceholders to YES doesn't work in collectionNode.
I have uploaded the demo video.
[Flashing-bug.mov.zip](https://github.com/facebook/AsyncDisplayKit/files/837983/Flashing-bug.mov.zip)
I reproduced this issue in simple example
[Flashing-Bug.zip](https://github.com/facebook/AsyncDisplayKit/files/837973/Flashing-Bug.zip)

**Comment by nguyenhuy** [comment]
@davitPiloyan93 Your flash is unrelated to the one described in this issue.  Your project is not using IGListKit and it is using ASDK 2.2 in which flashes caused by `reloadData` is a known issue.  That being said, the real reason your image nodes flicker is because you don't provide a default image /placeholder color and a fading duration.  Also your actual image is too big which takes a while for to be rendered off main and once that finished, the buffer is swapped immediately and that causes the flashing effect. You can simply eliminate it by these 2 lines:

```objective-c
self.imageNode.placeholderColor = [UIColor redColor];
self.imageNode.placeholderFadeDuration = 3.0;
```

Note that `self.neverShowPlaceholders = YES;` for your text node.

**Comment by ay8s** [comment]
Going to close this one down after updating to the latest master and clearing up a few things I think it may not be happening now.

Will reopen if I come across it again consistently and can provide more details.

**Comment by nguyenhuy** [comment]
Cool, thanks @ay8s!
