### ISSUE TITLE
Button nodes not displaying text, possibly now truncated with recent change

### ISSUE THREAD

**Issue by ay8s** [facebook/AsyncDisplayKit#3164]
With the latest commit 0540c863ca8d26e0aeb2c626ee1cb7391d6fc230 we're seeing that a couple of our ASButtonNode's are no longer showing text which previously displayed fine. Not sure if this is a truncation issue as spotted it mentioned in the notes or another issue introduced with that commit.

Previously: https://cl.ly/3d3O473w081G
Now: https://cl.ly/0f2s3F2T1M3A

**Comment by nguyenhuy** [comment]
@ay8s Sorry for the hassle! I've submitted a PR that should fix this. On the upside, imho, the button is a bit cleaner without the text :P
