### ISSUE TITLE
shouldRasterizeDescendants / frame issue

### ISSUE THREAD

**Issue by wockerwalker** [facebook/AsyncDisplayKit#318]
When creating an `ASDisplayNode` and setting `shouldRasterizeDescendants` to `YES`, any change to the node's origin (that is, any origin not equal to [0, 0]) seems to consequently inset the node's rasterized contents by the new origin's components. For example: when setting the node's frame to [10, 10, width, height] and setting the `backgroundColor` to red, the node displays with black 'margins' on top and left that are 10u each. The red background doesn't kick in until [10, 10] within the node itself.

**Comment by rnystrom** [comment]
It sounds like the node is opaque. Try changing `opaque = NO` and see if the issue still occurs. 

Also it sounds kind of odd that if the node is moved (e.g. changing the origin to {10, 10}) that there are still margins.

If you could provide a sample project with a reproduction I would be more than happy to check this out!

**Comment by wockerwalker** [comment]
Good call! The issue is resolved if I set `opaque = NO`. I would have expected that to resolve the black margin issue, but would have expected the frame to still be messed up (e.g. 'missing' the chunks where the margins used to be). Why does setting the `opaque` flag fix both issues?

**Comment by rnystrom** [comment]
Setting `opaque = NO` will be eventually passed through to the [drawing mechanics](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Private/ASDisplayNode%2BAsyncDisplay.mm#L181). If the backing store is set to be opaque, when drawing happens anything not covered by subnodes/views/layers/rastered content will be black.

**Comment by secretiverhyme** [comment]
The opacity triggering black backgrounds makes sense, but the offset issue is a bug I've seen reports of before.  This isn't super high-priority but we should look into this.

**Comment by appleguy** [comment]
This is now fixed by https://github.com/facebook/AsyncDisplayKit/pull/479.  Sorry for the long delay on this one.  Subtree precompositing has not been used by many folks outside of Facebook, and so this bug that didn't affect Paper's version of ASDK went unresolved for a while.  I'm starting to use precompositing in other projects and will make sure it doesn't regress.
