### ISSUE TITLE
Redefine views in a node?

### ISSUE THREAD

**Issue by simonyang81** [facebook/AsyncDisplayKit#3180]
Hello.
I am developing an iOS App based on AsyncDisplayKit. 
I want to use ASXXXNode with a custom UIView. 
I have noticed that a node has an UIView.
My question is can I redefine these views in a node class?

Thank You

**Comment by maicki** [comment]
@simonyang81 Hey, please look into the `- (instancetype)initWithViewBlock:(ASDisplayNodeViewBlock)viewBlock;` and similar initializer. The view block allows you to return a view that is used as a backing view of the node. Thanks!

If you have further questions please ask in our Slack channel: http://asyncdisplaykit.org/slack.html
