### ISSUE TITLE
UISwitch using ASDK

### ISSUE THREAD

**Issue by iOSUser110** [facebook/AsyncDisplayKit#3189]
Is there any way using which we can create UISwitch same like built in 
Any code snippet available for this ?

**Comment by abellee** [comment]
it seems there is no exact `UISwitch` replacement in `ASDK`.
but I think you definitely could use the `UISwitch` to do what you wanna do.
just add the `UISwitch` in `didLoad`,
everything will work as expect

**Comment by iOSUser110** [comment]
want to use UISwitch in ASCellNode

**Comment by abellee** [comment]
@iOSUser110 
you just need to add the `UISwitch` in the `didLoad`

**Comment by iOSUser110** [comment]
as ASCellNode provide only addSubnode 
and addSubnode accepts onlu Node from ASDK
it is not allowing to add UIView then how to do that ? please specify the code snippet for ASCellNode with ASTextNode and one UISwitch

**Comment by EviluS** [comment]
@iOSUser110 Check this issue (#2952) there is an example of how to add UIKit elements as nodes
