### ISSUE TITLE
[ASCollectionView] Animating & interacting to control scale of elements

### ISSUE THREAD

**Issue by jsleeuw** [facebook/AsyncDisplayKit#319]
I've been working with ASCollectionView and so far so good, but I'm now looking to have my ASCollectionView, or rather, the contents of my my ASCollectionView, scale in response to a pan gesture. The effect I'm trying to accomplish is very similar to that of pulling a  story into focus from Paper's feed.

I've yet to try this, but if I were to use UICollectionView it would seem that much of what I'm trying to accomplish could be handled via updates to the CollectionView's UICollectionViewLayout, which would eventually make their way down to the cells via applyLayoutAttributes:, allowing me to scale the content there. 

The apparent blocker for me here is this last bit. Is there a way to have my cells / nodes (that are not descendants of UICollectionReusableView) respond to UICollectionViewLayoutAttribute changes on the layout?

**Comment by secretiverhyme** [comment]
Hmm.  This could be implemented by forwarding `-applyLayoutAttributes:` from `_ASCollectionViewCell` to ASCellNode, if you need custom properties.  The docs say,

> You do not need to override this method to support the standard layout attributes of the UICollectionViewLayoutAttributes class. The collection view applies those attributes automatically.

If you're only messing with frame / bounds / center / size / transform3D / transform / alpha / zIndex / hidden, this should Just Work™.  I'll keep this issue open, but do let us know what your findings are!  =]

**Comment by jsleeuw** [comment]
I've decided to try and get the interactions sorted with ```UICollectionView``` -- figured I'll revisit ```ASCollectionView``` once I've got things sorted there. 

The approach I'm using, FYI, is to call ```startInteractiveTransitionToCollectionViewLayout:``` on my ```UICollectionView``` and handle the transition positioning etc. via the ```transitionProgress``` property on a custom ```UICollectionViewTransitionLayout```. But yeah, much of the messing is just being applied to frame(s) and alpha(s).  

Thanks for getting back to me on this, and I certainly will keep you posted on progress.

**Comment by colaho** [comment]
Hi jeleeuw, I am now facing the same issue as yours. Would you mind sharing your latest finding?

**Comment by jsleeuw** [comment]
@colaho We ran into so difficulties with the method used in my last post there (```UICollectionView``` & ```startInteractiveTransitionToCollectionViewLayout```). From what I recall, animating worked fine, but it broke down when we started trying to control the transition via gesture recognizer. 

With our current implementation much of the scaling work is done within a subclass of ```UICollectionViewCell``` via ```applyLayoutAttributes:layoutAttributes```. The cell is given (zoom) transition progress, and derives frame / layout properties from its knowledge of the start and end zoom sizes, etc.

We're not completely satisfied with the results however, so we've just recently started looking into this again.

**Comment by appleguy** [comment]
@jsleeuw Any more recent update?  There are a number of subtleties to what you're trying to accomplish — the most important is using a framework like Pop (or UIKit Dynamics, if you are very careful) to drive the motion.  This is the only way that you can smoothly integrate gesture input with animation (movement without gestures, either before or after a gesture).  Standard animations (CA / UIKit) are not interruptible and so attempting to influence them with gestures will only result in glitchy pain :).

**Comment by appleguy** [comment]
@jsleeuw @colaho - thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time it's been since this thread was active, I'm going to mark this issue as closed. If you are still having troubles, feel free to reopen it. 

If you haven't already, please join our ASDK Slack Channel (#1582). Several developers on there have recently been actively discussing similar collection scale transition interactions. 

I hope you have been able to use the framework!
