### ISSUE TITLE
Mixup with Built in controls and ASDK control

### ISSUE THREAD

**Issue by iOSUser110** [facebook/AsyncDisplayKit#3192]
can we add one control from ASDK and one control from built in SDK ?
Like i want to add ASTextNode and UISwitch in ASCellNode

self.addSubnode(textNode)

but to add UISwitch there is no addSubview 

then how to do that ?

**Comment by EviluS** [comment]
@iOSUser110 Check this issue (#2952) there is an example of how to add `UIKit` elements as `nodes`

**Comment by iOSUser110** [comment]
Thanks a lot..its working perfect. (y)
