### ISSUE TITLE
Flashes caused by reloadData

### ISSUE THREAD

**Issue by KKKiller** [facebook/AsyncDisplayKit#3195]
About this problem, I have try solution by adding
`
        self.neverShowPlaceholders =  @YES;
        self.imageNode.placeholderColor = [UIColor redColor];
        self.imageNode.placeholderFadeDuration = 3.0;
`
but the result is not really expected.
Is there any advice for me?
#I will give my demo here 
[Flashing-Bug.zip](https://github.com/facebook/AsyncDisplayKit/files/849749/Flashing-Bug.zip)
This issue is reffered from 3163
#3163  
Thanks very much #!

**Comment by maicki** [comment]
Hi @KKKiller, the result is expected as you use a network image node within your cell node, every time you use `reloadData` the `ASNetworkImageNode` fetches the image either from network or from the local cache. As this happens asynchronous this will result in kind of this flicker your observe.

I will close this issue if you have further questions how to use ASDK please join our Slack Channel: http://asyncdisplaykit.org/slack.html
