### ISSUE TITLE
RepoSeracher Example not working 

### ISSUE THREAD

**Issue by iOSUser110** [facebook/AsyncDisplayKit#3197]
![screen shot 2017-03-18 at 3 59 58 pm](https://cloud.githubusercontent.com/assets/2657399/24071267/ff39d1a8-0bf3-11e7-9fa4-a2b7da759c6e.png)
refer above screenshot

**Comment by maicki** [comment]
Hey @iOSUser110 if you have questions please join our Slack Channel: http://asyncdisplaykit.org/slack.html
