### ISSUE TITLE
Issues archiving when using ASDK as static library

### ISSUE THREAD

**Issue by wockerwalker** [facebook/AsyncDisplayKit#320]
I'm unable to successfully archive when using ASDK as a static library per instructions in the QuickStart guide. I get a lot of <AsyncDisplayKit/....h> file not found errors. I tried messing with the `alwaysSearchUsersPaths`, `skipInstall` and `headerSearchPaths` flags; while I was able to successfully archive (and eliminate the file not found errors), it generated a Generic Xcode Archive instead of an iOS App Archive. That's as far as I've been able to get.

Also - I've used Cocoapods to manage ASDK integration up until this point but switched to manual import because I needed a few of the features currently found on `master` but not in the 1.1.1 release accessible via Cocoapods (namely the `nodeForRow` method). Is there a way to grab the latest and greatest on master through Cocoapods so I can forego the headache of manual import?

**Comment by JoeMatt** [comment]
pod 'AsyncDisplayKit', :head

Should pull in the newest code from master on each 'pod install'

**Comment by wockerwalker** [comment]
Thanks!!

**Comment by secretiverhyme** [comment]
Bingo.  Thanks @JoeMatt :)

**Comment by JoeMatt** [comment]
Actually minor correction, only the first 'pod install' will pull from head. Subsequent updates need to be done explicitly via,

pod update 'AsyncDisplayKit'
