### ISSUE TITLE
A problem of ASImageNode on iOS 8.1.x

### ISSUE THREAD

**Issue by Luis-X** [facebook/AsyncDisplayKit#3202]
Hello, sometimes, We use this method crash on iOS 8.1.x, our project AsyncDisplayKit version is 2.0.2, We think that is a problem of ASImageNode and other iOS system is perfect, can you check this problem?
```
- (void)addBottomToolBarNode{
    
    ASImageNode *imageNode = [SJUIKit nodeImageNodeAddNode:self ClipsToBounds:NO ContentMode:UIViewContentModeScaleToFill];
    [imageNode setImage:[UIImage imageNamed:@"home_main_cell_bottom_bg.png"]];
    _bottomToolBarNode = imageNode;
    
}

+ (ASImageNode *)nodeImageNodeAddNode:(ASDisplayNode *)addNode ClipsToBounds:(BOOL)clipsToBounds ContentMode:(UIViewContentMode)contentMode{
    
    ASImageNode *imageNode = [ASImageNode new];
    imageNode.clipsToBounds = clipsToBounds;
    imageNode.contentMode = contentMode;
    [addNode addSubnode:imageNode];
    return imageNode;
    
}
```

**Comment by maicki** [comment]
@Luis-X Hey, can you please post a crash log in here? Thanks!

**Comment by Luis-X** [comment]
<img width="779" alt="f85a5a35-38ad-4ab9-8d68-f1b86004efa6" src="https://cloud.githubusercontent.com/assets/12946846/24434669/9d18f0f8-1463-11e7-832b-252259c292c3.png">
<img width="949" alt="4d7a9d2b-63ec-466e-928a-bf715ad995f1" src="https://cloud.githubusercontent.com/assets/12946846/24434678/a4cc4d7c-1463-11e7-9590-185528f700fa.png">

**Comment by zjmdp** [comment]
`[UIImage imageNamed:]` is not thread safe in before iOS 9.

**Comment by Luis-X** [comment]
How can i fix it?

**Comment by zjmdp** [comment]
@Luis-X Taking the adoption of versions below iOS 9 into account,  I do nothing about the crash. Of course, you can put the related code in `-didLoad` which runs on main thread or use `imageWithContentsOfFile:` instead of `-imageNamed`.

**Comment by Luis-X** [comment]
OK, Thank you very much! O(∩_∩)O~

**Comment by maicki** [comment]
Hey @Luis-X, @zjmdp, it seems like this issue is fixed. I will close this for now. Thanks all!
