### ISSUE TITLE
MinimumLineSpacing / minimumInterItemSpacing not honoured 

### ISSUE THREAD

**Issue by hansoln** [facebook/AsyncDisplayKit#3204]
When using ASDK together with IGListKit,  we are not able to control the space between items in an ASCollectionNode. 
According to the documentation, setting the minimumLineSpacing / minimumInterItemSpacing properties on a IGListSectionController should influence the spacing of items in the collection view.

This does not seem to work, after setting these properties to positive values, the space between items is still zero. 

This can be reproduced by modifying the RepoSearcher example project:

```
diff --git a/examples_extra/RepoSearcher/RepoSearcher/LabelSectionController.swift b/examples_extra/RepoSearcher/RepoSearcher/LabelSectionController.swift
index 040634c..08aa9fc 100644
--- a/examples_extra/RepoSearcher/RepoSearcher/LabelSectionController.swift
+++ b/examples_extra/RepoSearcher/RepoSearcher/LabelSectionController.swift
@@ -13,10 +13,17 @@ import IGListKit
 final class LabelSectionController: IGListSectionController, IGListSectionType, ASSectionController {
     var object: String?
 
+    override init() {
+        super.init()
+        minimumLineSpacing = 10
+        minimumInteritemSpacing = 10
+    }
+
     func nodeBlockForItem(at index: Int) -> ASCellNodeBlock {
         let text = object ?? ""
         return {
             let node = ASTextCellNode()
+            node.backgroundColor = .red
             node.text = text
             return node
         }
```

Would expect to see some white space between the labels (now with red backgrounds), but the items are laid out with no space in between.

**Comment by Adlai-Holler** [comment]
These spacings are only for items _within that section_. It looks like your section controller only manages one item for the entire section, so those values are ignored.

You should instead set `inset` on the section controller, so that the entire section has an inset. Feel free to reopen if needed. Cheers!

**Comment by hansoln** [comment]
Well, that makes a lot of sense! Thanks for helping me out!
