### ISSUE TITLE
ASDisplayNode Shadow not working

### ISSUE THREAD

**Issue by vksid** [facebook/AsyncDisplayKit#3229]
Hello Guys, I want a Shadow line on bottom of ASDisplayNode

Here's is my code

```      
            sectionNodeContainer = ASDisplayNode()
            self.sectionNodeContainer.shadowOffset = CGSize(width: 0, height: CGFloat(1) / UIScreen.main.scale)
            self.sectionNodeContainer.shadowRadius = 0
            self.sectionNodeContainer.shadowColor = UIColor.black.cgColor
            self.sectionNodeContainer.shadowOpacity = 0.25
```

When I use this code, I'm observing shadow in Subnodes of sectionNodeContainer.

**Comment by maicki** [comment]
Hey @vksid, the core team can't field questions like this unfortunately. There's a ton of smart people helping one another apply Texture in the `#general` channel of the [Texture slack team](http://texturegroup.org/slack.html) or ask your question on [StackOverflow](http://stackoverflow.com). Thanks!
