### ISSUE TITLE
Page Not Found http://huginn.cn/docs/requirements.md

### ISSUE THREAD

**Issue by B44ST** [facebook/AsyncDisplayKit#3230]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack

// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// AsyncDisplayKit version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

**Comment by maicki** [comment]
Hey @B44ST I don't think that is a page on our site. Thanks!
