### ISSUE TITLE
ASVideoNode inside UITableViewCell

### ISSUE THREAD

**Issue by barisBr** [facebook/AsyncDisplayKit#3234]
Hello I am trying to implement ASVideoNode inside UITableViewCells but I can't achive that without memory overflow is there any memory efficient way to implement this ?

**Comment by nguyenhuy** [comment]
hi @barisBr, could you bring your question to our [Slack channel](asyncdisplaykit.org/slack) with more details, like how are you setting up the video nodes? Are you using it inside an ASTableNode (recommended), or are you managing them yourself (not recommended). Thanks!
