### ISSUE TITLE
ASDK with IGListKit and embedded collection nodes

### ISSUE THREAD

**Issue by js** [facebook/AsyncDisplayKit#3240]
Been using AsyncDisplayKit for a while and was able to clean up a lot things when IGListKit support was introduced. Nicely done!

I ran into an issue when I wanted to use the "embedded" section controllers in IGListKit, in the IGLK [sample project](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/HorizontalSectionController.swift#L40) they set connection the embedded cells collectionview to the section controllers own IGListAdapter using -setCollectionView: and as far as I understand we have to use -setASDKCollectionNode: when we have a ASCollectionNode (as opposed to settings the collectionNode.view on the list adapter).

So I thought business as usual and did this:
```swift
extension FloorSectionController: ASSectionController {
    func nodeBlockForItem(at index: Int) -> ASCellNodeBlock {
        return {
            let cell = FloorCellNode()
            self.adapter.setASDKCollectionNode(cell.collectionNode)
            return cell
        }
    }
```

_except that_ -setASDKCollectionNode: asserts the main thread using `ASDisplayNodeAssertMainThread()` so I seem to be in a catch-22 situation of sorts here.

How can use an collection node thats embedded in a cell node and connect it to be list adapter?

**Comment by Adlai-Holler** [comment]
Good catch @js! We could possibly remove this assertion in the future after an audit of the thread-safety, but for the time being, you can call `onDidLoad:` on the cell node, to make the association when the cell node's view is loaded. This will run on the main thread, but it has the benefit of avoiding the work entirely if the node's view never gets loaded (say, you never scroll down to it.) My Swift is a little rusty, but something like this should work for you:

```swift
let cell = FloorCellNode()
cell.onDidLoad { (cell: FloorCellNode) in
    self.adapter.setASDKCollectionNode(cell.collectionNode)
}
```

How's that do?

**Comment by js** [comment]
Yeah that did the trick, thanks!

What's the recommend way to handle cell sizing in cases like this, if I want an embedded horizontal collectionview that's as tall as its tallest cell?
Right now I'm creating all the child cells in the FloorSectionController and finding the max height using `layoutThatFits()` but that feels like wrong way since ASDK usually takes care of sizing things according to the layout spec, but I'm not quite sure how to approach it, any hints?

**Comment by Adlai-Holler** [comment]
@js That's a tricky problem to solve – in very simple cases, the best thing to do is what you're doing, go ahead and measure the cell nodes and get the max height, then configure your collection view to follow that. If you have a lot of nodes, or you're feeling ambitious, you can run a first layout pass where your collection view assumes some estimated height, say `(375, 500)`, and then it calls `waitUntilAllUpdatesAreCommitted` immediately after (say, in `layoutDidFinish` or `viewDidLayoutSubviews`) and then run through the cell nodes that we generated & measured and get the maximum height, and set it as `collectionNode.style.height` and call `-setNeedsLayout` to run another layout pass and that'll get it the height it needs.

You should also reach out on our Slack channel #general where people are helping each other with stuff like that all day.
