### ISSUE TITLE
ASIGListSectionControllerMethods not found in Swift project

### ISSUE THREAD

**Issue by chika-kasymov** [facebook/AsyncDisplayKit#3250]
I tried to install AsyncDisplayKit this way:

```
pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :branch => 'master'
pod 'AsyncDisplayKit/IGListKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :branch => 'master'
```

But **Xcode** shows errors like `Use of unresolved identifier 'ASIGListSectionControllerMethods'`. 

Maybe this happens because of this flag `IG_LIST_KIT` in **.h** file:
```
#if IG_LIST_KIT
#import <AsyncDisplayKit/IGListAdapter+AsyncDisplayKit.h>
#import <AsyncDisplayKit/AsyncDisplayKit+IGListKitMethods.h>
#endif
```

**Update 1**:
Example project **RepoSearcher** in **examples_extra** which is also using Swift have the same errors.

**Update 2**:
After deleting `IG_LIST_KIT` flags everything worked as expected. Will wait for your response how to handle this without manual manipulation.

**Comment by spronin** [comment]
In the meanwhile you can just use this:
```
func sizeForItem(at index: Int) -> CGSize {
    return .zero
}
    
func cellForItem(at index: Int) -> UICollectionViewCell {
    return collectionContext! .dequeueReusableCell(of: _ASCollectionViewCell.self,                                  for: self, at: index)
}
```

**Comment by chika-kasymov** [comment]
OK, thanks! It's not a big problem for now, but if something in that methods will change I will forget about this line :)
