### ISSUE TITLE
Crash IndexPath._unconditionallyBridgeFromObjectiveC 

### ISSUE THREAD

**Issue by muukii** [facebook/AsyncDisplayKit#3251]
This crash was caused on ASCollectionNode.
Reproduce steps are unstable.

Env:
Swift 3.1, Xcode 8.3.1
Commit: 873ae64cecbc8bee840e25d86bfb167012cbbbe9

<img width="785" alt="screen shot 2017-04-10 at 16 09 25" src="https://cloud.githubusercontent.com/assets/1888355/24849735/18899438-1e08-11e7-825f-73a4782d81b8.png">

<img width="655" alt="screen shot 2017-04-10 at 16 09 44" src="https://cloud.githubusercontent.com/assets/1888355/24849750/26acdad4-1e08-11e7-9476-b46af7ab3779.png">

**Comment by muukii** [comment]
Sorry, I've fixed it.
Some code was moved `didLoad` to `init` on CellNode.

**Comment by newbdez33** [comment]
@muukii I'm facing the same issue. crash randomly. How did you fixed it?
