### ISSUE TITLE
How can I go about adding a gradient background to ASButtonNode or ASDisplayNode?

### ISSUE THREAD

**Issue by Shivam101** [facebook/AsyncDisplayKit#3253]
Hello,
Given an array of `UIColor` objects and a `CGFloat` angle, how can I go about implementing a gradient background for ASButtonNode or ASDisplayNode? 
Would I have to create a separate node and add it as a subnode? How should I go about doing that?

Thanks!

**Comment by EviluS** [comment]
@Shivam101 The ways I can think of are:

**Comment by Shivam101** [comment]
I solved it for ASButtonNode, by setting the gradient as the `backgroundImage` property. 
For ASDisplayNode, using the first way suggested by @EviluS worked!
