### ISSUE TITLE
New version after v1.1.1 in Cocoa pods for latest code

### ISSUE THREAD

**Issue by NareshKalakuntla** [facebook/AsyncDisplayKit#326]
Hi, 
 Am using the ASKit with pods v1.1.1. But found that not all the latest ASTableview methods are integrated in this version like inserting & deleting. They are already done and i can see it in the latest code base. Can you please let us know when can we expect a new version in the pods with all updated code for ASTableview.

**Comment by smeis** [comment]
Those methods have been added after the latest stable version.

Use pod 'AsyncDisplayKit', :head to pull in the latest code from the master branch.

**Comment by NareshKalakuntla** [comment]
@smeis:  Thanks for the suggestion. This worked for me.
But this might make my app unstable if there are any undetected and major bugs. Also, I have to do the testing for this framework also :(

**Comment by secretiverhyme** [comment]
We have a few remaining major features inbound (check out the [pull requests](https://github.com/facebook/AsyncDisplayKit/pulls) page).  Once they've landed, we'll release an ASDK 1.2 beta; the stable 1.2 release should follow not long after.
