### ISSUE TITLE
ASTextNode inconsistent text size calculation

### ISSUE THREAD

**Issue by nivanchikov** [facebook/AsyncDisplayKit#327]
Hi,

I've had some problems with measuring text sizes with ASTextNode, the resulting calculated size is actually bigger than expected.

Here's my setup for title / subtitle labels (they're marked as gray and white in the screenshot below).
```
node.layerBacked = YES;
node.attributedString = text;
node.maximumLineCount = 2;
node.truncationMode = NSLineBreakByTruncatingTail;
```

However, if I fetch node size via `frameForTextRange`, the resulting frame is correct:

```
- (CGSize) calculateSizeThatFits: (CGSize) constrainedSize
{
	CGFloat width = constrainedSize.width - 100.0f;

	CGSize tSize = [_titleLabel measure: CGSizeMake(width, CGFLOAT_MAX)];

	CGSize tAlternativeSize = [_titleLabel frameForTextRange: NSMakeRange(0, _titleLabel.attributedString.length)].size;

	NSLog(@"%@ - %f / %f", _titleLabel.attributedString.string, tSize.height, tAlternativeSize.height);

//  Last - 35.000000 / 18.000000 (measure: / frameForTextRange:)
//  Weather - 35.000000 / 18.000000 
}
```

I've noticed that issue mostly happens for nodes which actual number of lines after calculation is smaller or equal to `maximumLineCount`.

![img_0314](https://cloud.githubusercontent.com/assets/1830010/6348255/ab0d7e5a-bc26-11e4-854d-245a207c2044.PNG)

**Comment by secretiverhyme** [comment]
Thanks for the report!  cc @ocrickard

**Comment by ocrickard** [comment]
What happens if you don't use NSLineBreakByTruncatingTail?

**Comment by secretiverhyme** [comment]
cc #261

**Comment by nivanchikov** [comment]
@ocrickard thanks for your response, here's an updated screenshot where I commented out 
`node.truncationMode = NSLineBreakByTruncatingTail;`, but kept `maximumLineCount`. 

![ios simulator screen shot feb 25 2015 00 45 16](https://cloud.githubusercontent.com/assets/1830010/6361119/2c80c80a-bc88-11e4-823b-edd7d4f7ec7a.png)

**Comment by appleguy** [comment]
@nivanchikov I am fairly confident this is resolved in the latest Version of the framework, but please let me know if you were still seeing it. I apologize we never got a clear answer for you here in a timely manner… Please do report any other issues you see, however, as there're many more contributors actively watching the project today then there were at this time!
