### ISSUE TITLE
How to create a drop shadow on ASCellNode

### ISSUE THREAD

**Issue by Shivam101** [facebook/AsyncDisplayKit#3277]
Hello,
I am looking to add a drop shadow to an ASCellNode which I have used in a table view. 
I have tried using something like this - 

```
self.layer.shadowColor = [UIColor blackColor].CGColor;
self.layer.shadowRadius = 6.0;
self.layer.shadowOpacity = 1.0;
self.layer.shadowOffset = CGSizeMake(0, 0);
```

in the `didLoad()` method of the cellNode, but it doesn't seem to have had any effect. How can I go about implementing this? 

Thanks!

P.S. - Adding a drop shadow to the table view itself did work, but adds a shadow to ALL cells. I only need it to be visible on certain types of cells.

**Comment by maicki** [comment]
Hey @Shivam101  the core team can't field questions like this unfortunately. There's a ton of smart people helping one another apply Texture in the #general channel of the [Texture slack team](http://texturegroup.org/slack.html).
