### ISSUE TITLE
Identifying influential nodes in complex networks

### ISSUE THREAD

**Issue by pari1370** [facebook/AsyncDisplayKit#3281]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack

// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// AsyncDisplayKit version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

**Comment by maicki** [comment]
@pari1370 Hey I don't really understand what are you are trying to say in here therefore I will close. Thanks!
