### ISSUE TITLE
ASdimension working need more explanation or some examples 

### ISSUE THREAD

**Issue by iOSUser110** [facebook/AsyncDisplayKit#3283]
_________    ___________   __________   ___________
I want to develop UI As above 4 lines ,
Each occupy 1/4 th of space and height = 2 ,
and i can change color of each line.
How to make use of ASDimension in tableview

**Comment by maicki** [comment]
Hey @iOSUser110 , the core team can't field questions like this unfortunately. There's a ton of smart people helping one another apply Texture in the `#general` channel of the [Texture slack team](http://texturegroup.org/slack.html) or ask your question on [StackOverflow](http://stackoverflow.com) with the `#textureios` label. Thanks!
