### ISSUE TITLE
GIFs not cached

### ISSUE THREAD

**Issue by harri121** [facebook/AsyncDisplayKit#3301]
I am using ASNetworkImageNode to display remote GIFs. The GIFs are not cached but downloaded everytime they are displayed. Not animated images are cached properly.
Am I missing something? Do I have to write a custom cache to cache GIFs?

**Comment by nguyenhuy** [comment]
@harri121 Please move over to [Texture](http://github.com/texturegroup/Texture) as this repository is no longer maintained.

**Comment by harri121** [comment]
Alright, moved the issue to Texture. Thanks
