### ISSUE TITLE
Change maximumNumberOfLines  from 5 to 0, The text is stretched.

### ISSUE THREAD

**Issue by peak77** [facebook/AsyncDisplayKit#3309]
Change maximumNumberOfLines  from 5 to 0, The text is stretched.
the vedio: [http://132.232.41.183:8080/TappedTruncation/tMovie.mp4](url)
the project:[https://github.com/peakerWu/TappedTruncation](url)
Texture version 2.7

**Comment by ay8s** [comment]
Please file any Texture issues over at https://github.com/texturegroup/texture

**Comment by peak77** [comment]
@ay8s OK
