### ISSUE TITLE
Full screen button doesn't appear on ASVideoPlayerNode

### ISSUE THREAD

**Issue by rahulvyas** [facebook/AsyncDisplayKit#3311]
I have copied code from ASDKTube sample for video player in Cell. I have tried to add a fullscreen button along with progress bar. What wrong I'm doing ?

- (NSArray *)controlsForControlBar:(NSDictionary* )availableControls
{
  NSMutableArray *controls = [[NSMutableArray alloc] init];

  if (availableControls[ @(ASVideoPlayerNodeControlTypePlaybackButton) ]) {
      [controls addObject:availableControls[ @(ASVideoPlayerNodeControlTypePlaybackButton) ]];
  }

  if (availableControls[ @(ASVideoPlayerNodeControlTypeElapsedText) ]) {
      [controls addObject:availableControls[ @(ASVideoPlayerNodeControlTypeElapsedText) ]];
  }

  if (availableControls[ @(ASVideoPlayerNodeControlTypeScrubber) ]) {
      [controls addObject:availableControls[ @(ASVideoPlayerNodeControlTypeScrubber) ]];
  }

  if (availableControls[ @(ASVideoPlayerNodeControlTypeDurationText) ]) {
      [controls addObject:availableControls[ @(ASVideoPlayerNodeControlTypeDurationText) ]];
  }
  if (availableControls[ @(ASVideoPlayerNodeControlTypeFullScreenButton) ]) {
      [controls addObject:availableControls[ @(ASVideoPlayerNodeControlTypeFullScreenButton) ]];
  }

  return controls;
}

I have even supplied Full screen button image in data source method.
Why Fullscreen button doesn't appear on ASVideoPlayerNode from the above code ?

**Comment by ay8s** [comment]
Please keep all Texture related issues over at https://github.com/TextureGroup/Texture, it's unlikely to be answered in this archive repo.

**Comment by rahulvyas** [comment]
Yeah thanks,
I am closing this issue
