### ISSUE TITLE
Dictionary Parsing Problem

### ISSUE THREAD

**Issue by SaluBhayo-zz** [facebook/AsyncDisplayKit#3312]
ASDefaultPlaybackButtonType creating problem stating this error "Expected method to read dictionary element not found on object of type 'id<NSObject>'". I am unable to build my project

for Further details please check screen shot
(https://user-images.githubusercontent.com/12893784/45950503-7ede1880-c019-11e8-95e5-d5eb25d86b77.png)

Using AsyncDisplayKit (2.2.1)

**Comment by ay8s** [comment]
Please check out https://github.com/TextureGroup/Texture. AsyncDisplayKit was renamed and this repo is no longer updated.
