### ISSUE TITLE
Warnings in base project

### ISSUE THREAD

**Issue by rnystrom** [facebook/AsyncDisplayKit#332]
```
/Users/rnystrom/iOS/AsyncDisplayKit/AsyncDisplayKitTests/ASTableViewTests.m:33:17: Method 'tableViewLockDataSource:' in protocol 'ASTableViewDataSource' not implemented
/Users/rnystrom/iOS/AsyncDisplayKit/AsyncDisplayKitTests/ASTableViewTests.m:33:17: Method 'tableViewUnlockDataSource:' in protocol 'ASTableViewDataSource' not implemented
```

Grr warnings. Need to add blank methods or make methods optional.

**Comment by secretiverhyme** [comment]
While you're at it, want to enable `-Werror` on the test target?

**Comment by cfcommando** [comment]
There are no uses of `-tableViewLockDataSource:` or its counterpart in the example projects, no tests covering it, and the provided example project contains the above warnings.

There are 12 warnings in my project, two of which are unavoidable limitations of CocoaPods; these are the other ten, and I'd prefer not to use empty implementations before I understand their proper usage.

@tanliboy - Can we _please_ have a concrete example of how these methods are intended to be implemented? Or can we make them optional until there is documentation explaining how they should be implemented?

Thanks.

**Comment by cfcommando** [comment]
Apparently there is one example present in Kittens, which I missed because I was looking for usages in the workspace rather than the whole repository. My apologies.

I do think that the methods would greatly benefit from additional context, so I hope that we can still address that.

**Comment by secretiverhyme** [comment]
(Let's keep discussion about this API change on #338.)
