### ISSUE TITLE
Only flow layouts are currently supported in collection view

### ISSUE THREAD

**Issue by prudencioj** [facebook/AsyncDisplayKit#335]
Hi guys,

I was trying to use AsyncDisplayKit in a collection view, with a custom layout, but I've faced this assert:

"Only flow layouts are currently supported"

Are you working in enabling this in a near future?

Thanks.

**Comment by RCacheaux** [comment]
This is something I've tinkered with. I have a fork that enables custom layouts, I could take a crack at getting it in a PR-able state. Thoughts?

**Comment by prudencioj** [comment]
I was just looking at your example http://www.raywenderlich.com/86365/asyncdisplaykit-tutorial-achieving-60-fps-scrolling
And I noticed you are using a custom layout. Can I you provide a link for your fork?

Thanks

**Comment by RCacheaux** [comment]
Just pushed out a preliminary PR, https://github.com/facebook/AsyncDisplayKit/pull/336

**Comment by prudencioj** [comment]
Great job RCacheaux!

**Comment by appleguy** [comment]
So thrilled this was fixed.
