### ISSUE TITLE
UIWebView wrapper node

### ISSUE THREAD

**Issue by lordhighbonky** [facebook/AsyncDisplayKit#342]
Hey guys...I am trying to figure out how to wrap a UIWebView with an ASDisplayNode but apart from calling:

    ASDisplay *node =   [[ASDisplayNode alloc] initWithViewClass:[UIWebView class]];

I am at a complete loss on how to actually load html data into the UIWebView and there is no documentation or examples on what to do after calling initWithViewClass. Any help would be appreciated.

**Comment by lxcid** [comment]
Try the latest `head`, there's a more flexible solution:

`[[ASDisplayNode alloc] initWithViewBlock:<#^UIView *(void)viewBlock#>]`

**Comment by lordhighbonky** [comment]
Yep, that did it. Thanks a ton!
