### ISSUE TITLE
Implement ASButtonNode

### ISSUE THREAD

**Issue by rnystrom** [facebook/AsyncDisplayKit#343]
We'd love to create an ASButtonNode that mimics UIButton.

- Inherit from `ASControlNode`
- Create `ASControlState` for Normal, Selected, Highlighted, and Disabled
- Provide control state background image
- Provide control state attributed text
- Provide control state background color
- Provide control state icon (e.g. accessory)
- Layout supporting text only, text + icon, and icon only
- Flex-box style layout with icons and text
- Change text/background/image based on state changes
- Change state based on touch down/up/cancel

**Comment by RuiAAPeres** [comment]
This would be a great addition.

**Comment by appleguy** [comment]
@RuiAAPeres I met a great developer at NSSpain who said they had already written a powerful ASButtonNode and wanted to share it with the community soon, but very unfortunately, I didn't get his contact information.  We'll see if one pops up!

**Comment by Adlai-Holler** [comment]
I think #800 handles this.

**Comment by RuiAAPeres** [comment]
Ah awesome!

**Comment by appleguy** [comment]
This has been working well!
