### ISSUE TITLE
UIScrollViewDelegate targetContentOffset question

### ISSUE THREAD

**Issue by ProjectDent** [facebook/AsyncDisplayKit#345]
I want to override the deceleration of a scroll view, to have it finish at a specific point (this point changes, but for simplicity I've put it here as `CGPoint(x: 0, y: 100)`. I started off with this code, which achieved that:

    func scrollViewWillBeginDecelerating(scrollView: UIScrollView) {
        self.collectionView.setContentOffset(CGPointMake(0, 100), animated: true)
    }

The problem then is that the resulting animation apparently starts with 0 velocity, ie what you might expect with `UIViewAnimationOptions.CurveEaseInOut`.

So I replace it with my own animation to that point:

    UIView.animateWithDuration(
        0.3,
        delay: 0,
        options: UIViewAnimationOptions.CurveEaseOut,
        animations: {
            () -> Void in
            self.collectionView.setContentOffset(CGPointMake(0, 100), animated: false)
        }, completion: nil)

Now the animation works as expected, but the nodes which will be off screen at the end of the animation immediately disappear as the animation begins.

**Comment by secretiverhyme** [comment]
UIScrollViewDelegate supports this directly -- you don't need to muck about with custom animations.  Try the `-scrollViewWillEndDragging:withVelocity:targetContentOffset:` delegate method.  The `targetContentOffset` parameter is an `inout` pointer; you can read its value, transform it (e.g. round up to the next cell's origin), and write the new value back, and the scroll view will naturally change its deceleration target.  =]

**Comment by ProjectDent** [comment]
This takes me a step closer, but the problem now is that the velocity comes from that velocity value, so where I might want it to animate at a high speed to the content offset upon the user letting go, it actually travels with 0 velocity.

So I could set the targetContentOffset to the current contentOffset and move the above code into scrollViewWillEndDragging, which speeds it up and gives me the animation I want, but then I get the issue I reported above.

**Comment by piyush23dez** [comment]
i have tried setting targetcontentOffset with my own custom positions but the animation gets slow at end position.
    
 var scrollRect:CGRect = scrollView.frame;
scrollRect.origin.y = self.top or self.middle or self.bottom
 targetContentOffset.memory = scrollRect.origin


i also tried putting the above code in UIView animation block but it animates the same, can you please help for the same.

**Comment by appleguy** [comment]
@ProjectDent @piyush23dez - thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time it has been since this thread was active, I'm going to mark this issue as closed. A ton of work has been done on the framework in the last year, in particular, the range controller has been rewritten which could plausibly fix the type of issue you describe.  

Please file a new issue or talk to us on ASDK's Slack Channel (#1582) if this is still an issue for you.
