### ISSUE TITLE
[ASCollectionView] nodeForItemAtIndexPath: as method equivalent to cellForItemAtIndexPath:

### ISSUE THREAD

**Issue by ProjectDent** [facebook/AsyncDisplayKit#346]
When my data source reloads some data about an item, I'd like to update my ASCollectionView to use a new item as input for that aspect of the item, without needing to reload all of the data.

I'd keep a cache of the nodes, but I don't want to mishandle them in case of memory issues.

**Comment by secretiverhyme** [comment]
cc @tanliboy

**Comment by rnystrom** [comment]
Love this idea!

**Comment by JohnnyTseng** [comment]
@ProjectDent  I am currently facing same issue now, Just tried to add notification observer to every ASCellNode subclass, and post notification in ViewController when data is updated, it works but I am wondering if there will be any potential problems using this solution.

Do you have any ideas or can you share your solution for updating data?
Thank you!

**Comment by appleguy** [comment]
@ProjectDent this feature was added quite awhile ago. I'm going to close out this issue, but feel free to open another if you have any problems using it. I hope you have been able to use the framework!
