### ISSUE TITLE
Enabling shouldRasterizeDescendants causes incorrect node rendering

### ISSUE THREAD

**Issue by nguyenhuy** [facebook/AsyncDisplayKit#357]
My collection view looks like this when `shouldRasterizeDescendants` is disabled on each `MessageCellNode`: 
![ios simulator screen shot 06 mar 2015 5 16 51 pm](https://cloud.githubusercontent.com/assets/587874/6527656/1f6d4aea-c425-11e4-92e7-089e592c77ec.png)

And when `shouldRasterizeDescendants` is enabled:
![ios simulator screen shot 06 mar 2015 5 16 18 pm](https://cloud.githubusercontent.com/assets/587874/6527671/3d198b30-c425-11e4-89e6-3873d7d58594.png)

I'm not sure what did I do wrong and how to fix it. Please help :)

Sample code can be found here: https://github.com/nguyenhuy/AsyncMessagesViewController/commit/467ee2046fe3877505baac75d64652f4821067fe

**Comment by rnystrom** [comment]
@nguyenhuy What happens when you set `cell.opaque = NO`?

**Comment by nguyenhuy** [comment]
@rnystrom: the whole cell [turns white](https://dl.dropboxusercontent.com/u/10896666/AMVC_1.png) when `cell.opaque` is disabled.

After taking a closer look, it seems like the problem is caused by `ASImageNode`. [Here](https://dl.dropboxusercontent.com/u/10896666/AMVC_2.png) is what the cell looks like when I enable `shouldRasterizeDescendants` on image nodes only.

**Comment by bensarz** [comment]
@rnystrom I get the exact same problem here, using 1.1.1 at the moment. Any updates on this issue?

**Comment by appleguy** [comment]
@nguyenhuy I tried to run your code locally, but it isn't building.  I'm not familiar with Swift, so could you check out the errors and update your repo if necessary?

We recently landed a fix for subtree precompositing.  You also should check that you have backgroundColor set to something specific, like whiteColor, because clearColor will default to black.  We should have a better default in ASDK, and I'm tracking that improvement.

Thanks for your contributions & reports!
![screen shot 2015-06-14 at 4 17 57 pm](https://cloud.githubusercontent.com/assets/565251/8150906/30ba374c-12b1-11e5-92f5-2abef20e9ea3.png)

**Comment by nguyenhuy** [comment]
@appleguy I'm sorry about the errors, definitely caused by Swift 1.2 breaking changes. I have just had a local copy that works with Swift 1.2 and ASDK 1.2.1 (haven't updated the repo because I prefer to declare 1.2.1 in Podfile, but it's not available on CocoaPods yet). 

The problem still occurs on ASDK 1.2.1 though. Background colors are rendered properly, but node contents are not. I will investigate this issue in the next few days.

**Comment by appleguy** [comment]
Punting to 1.3 as 1.2.2 is going out now.  @nguyenhuy I would love to hear if you figure out the nature of the bug, even if you're not sure the right way to fix it.

**Comment by nguyenhuy** [comment]
@appleguy My time for ASDK has been dedicated to the Box Model. With the
coming beta version, hopefully I will have time to update my library to use
the box model, simplify nodes and eventually make it easier to debug this
issue. I will keep you up-to-date.

**Comment by kos9kus** [comment]
Hello guys, 
I have a familiar situation like this.
![Uploading Screen Shot 2015-07-29 at 15.39.10.png…](ScreenShot)
Into one of custom cells a incorrect rendering happens with black background after scrolling. It applies to ASImageNode

**Comment by appleguy** [comment]
@kos9kus @bensarz this bug is very old - fortunately this issue was fixed quite some time ago, but I forgot about the task.  Feel free to use 1.9.3 or ASDK master and you should definitely be up and running!  File any other issues you encounter, and thanks a lot for reporting this.
