### ISSUE TITLE
[ASCollectionView] Obtaining references of visibleNodes in 1.1.1

### ISSUE THREAD

**Issue by barfoon** [facebook/AsyncDisplayKit#366]
What is the best way to get a reference to each visible node in a ASCollectionView instance in 1.1.1? `visibleNodes` and `nodeForItemAtIndexPath` no longer seem to be available.

Thanks,

**Comment by secretiverhyme** [comment]
These methods were added in #260 and haven't yet been released.  You can apply that patch to your local version of AsyncDisplayKit, or change your Podfile to point directly at the `master` branch if you want to run bleeding-edge code.

**Comment by macistador** [comment]
As `visibleNodes` and `nodeForItemAtIndexPath` are now available this issue may be closed

**Comment by appleguy** [comment]
See above comment. :)
