### ISSUE TITLE
ASNetworkImageNode Incorrect display node thread affinity

### ISSUE THREAD

**Issue by aldenks** [facebook/AsyncDisplayKit#368]
I am running into the thread affinity assert failure while using an ASNetworkImageNode in an ASCellNode. The image node is allocated on the main thread in the cell's init method, then when I call `-measure:` on the image node in my cell's `-calculateSizeThatFits:`, I see the assert failure. 

Looking at the assert condition (`!viewNode || ASDisplayNodeThreadIsMain() || !(viewNode).nodeLoaded`) it makes sense that it would fail -- we're not on the main thread and the node is loaded, but I'm confused because I thought measure was usually called off the main thread.

Am I not allowed to use network image nodes like this? Is this a bug?

Thanks! This is really cool project.

I am on iOS simulator 8.1 and Xcode Version 6.1.1 (6A2008a).
Stack trace:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Incorrect display node thread affinity'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b115f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010adaebb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010b115d9a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010936d5df -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   MyApp                              0x0000000108bab92b -[ASDisplayNode __measure:] + 315
	5   MyApp                              0x0000000108bab78f -[ASDisplayNode measure:] + 95
	6   MyApp                              0x0000000108b2e6c0 -[MyCustomCellNode calculateSizeThatFits:] + 128
	7   MyApp                              0x0000000108baba88 -[ASDisplayNode __measure:] + 664
	8   MyApp                              0x0000000108bab78f -[ASDisplayNode measure:] + 95
	9   MyApp                              0x0000000108b8af9c __66-[ASDataController _insertNodes:atIndexPaths:withAnimationOption:]_block_invoke_2 + 332
	10  CoreFoundation                      0x000000010b061156 __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 70
	11  CoreFoundation                      0x000000010b06108c -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 284
	12  MyApp                              0x0000000108b8adc9 __66-[ASDataController _insertNodes:atIndexPaths:withAnimationOption:]_block_invoke189 + 169
	13  libdispatch.dylib                   0x000000010bd12ba6 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x000000010bd307f4 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000010bd1b15d _dispatch_root_queue_drain + 1097
	16  libdispatch.dylib                   0x000000010bd1c5d9 _dispatch_worker_thread3 + 111
	17  libsystem_pthread.dylib             0x000000010c0b4637 _pthread_wqthread + 729
	18  libsystem_pthread.dylib             0x000000010c0b240d start_wqthread + 13
```

**Comment by secretiverhyme** [comment]
ASNetworkImageNodes definitely work in ASCellNodes — check out the Kittens project in the `examples/` directory for an example.  What does your ASCellNode implementation look like?  Are you accessing the image node's view before measuring it?

**Comment by aldenks** [comment]
I was accessing the nodes _layer_ before calling `measure:` (to set `masksToBounds` in my init method). Thank you, moving that call later fixed the crash.

**Comment by secretiverhyme** [comment]
Because of the UIViewBridge, you can set view / layer properties on the node without actually loading the node's backing view / layer.  Try just setting

```objective-c
node.clipsToBounds = YES;
```

directly and you should be set!  =]

**Comment by aldenks** [comment]
ah right! thank you
