### ISSUE TITLE
Flickering and performance problems of layerBacked ASDisplayNodes

### ISSUE THREAD

**Issue by Jercik** [facebook/AsyncDisplayKit#37]
Setting "layerBacked" value to YES is recommended for performance, but I've found that in certain situations it causes ASDisplayNodes to flicker and perform additional (and unnecessary) drawing.

Here you can see flickering when presenting and dismissing view controller:
![out](https://cloud.githubusercontent.com/assets/154902/4583905/38a1cc6e-4ff6-11e4-8592-11a2c29a6196.gif)

Only difference between two nodes is layerBacked property set to YES on right one.

I'm using long emoji string to make drawing more expensive so flickering effect is visible on simulator. On devices effect can be observed also with strings that are much less expensive to draw.

Same effect and can be observed with ASImageNode.

I can provide example project if necessary.

**Comment by Cabus** [comment]
I'm seeing this effect with version 1.9. Especially during push and pop in a UINavigationController.
However, it happens regardless of 'layerBacked'.
I tried setting 'displaySuspended'. (false in 'didExitHierarchy'. true in 'willEnterHierarchy') but that didn't help. My node contained an ASImageNode and 2 ASTextNodes. Any further solutions for this?

**Comment by CodeEagle** [comment]
still get blink when pop back
