### ISSUE TITLE
The use of UIApplication is forbidden in App Extensions

### ISSUE THREAD

**Issue by bensarz** [facebook/AsyncDisplayKit#376]
> ASControlNode.m:354:29: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

> ASControlNode.m:356:29: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

We've been using ADK in our custom keyboard. It works fine and we want to continue to use it, however, the latest version of Xcode pointed out this error.
Can you find another solution to this instead of using `UIApplication`?

**Comment by rnystrom** [comment]
This is fixed in #264 but that won't come out until 1.2. Feel free to checkout master and use that if the 1.2 release (beta coming *very* soon) is blocking you.

Thanks for the report!

**Comment by secretiverhyme** [comment]
#264 is a self-contained patch, so you can also apply it directly to your local version of AsyncDisplayKit.  =]
