### ISSUE TITLE
How to use `defaultImage` of `ASNetworkImageNode` since `imageNamed:`is not thread safe?

### ISSUE THREAD

**Issue by yufenglv** [facebook/AsyncDisplayKit#384]
How to use `defaultImage` of `ASNetworkImageNode` since `imageNamed:`is not thread safe?
Looking forward to your answer! Thanks ~

**Comment by secretiverhyme** [comment]
IIRC `+[UIImage imageNamed:]` (which has cacheing) is thread-safe unless used with asset catalogues, though that of course may change in future iOS releases.  I believe `+[UIImage imageWithContentsOfFile:]` (which doesn't have cacheing) is thread-safe.  It might be worth building a thread-safe cacheing UIImage loader for ASDK, but in the meantime, you may want to stick with `+imageWithContentsOfFile:`.

**Comment by rnystrom** [comment]
Yup, `+ imageWithContentsOfFile:` is thread safe, so you should be ok using that.

**Comment by yufenglv** [comment]
Thanks for your answer !
Yes,  I  also considered `+ imageWithContentsOfFile `, but since I didn't release `ASNetworkImageNode`, the image will not be release, there will be many copies of the `defaultImage` in memory I think. I am right?
