### ISSUE TITLE
AVPlayerLayer support

### ISSUE THREAD

**Issue by tspecht** [facebook/AsyncDisplayKit#386]
Hey guys,

I just started looking into using AsyncDisplayKit for my app. I have a lot of AVPlayerLayer objects flying around and need to repeatedly change their associated AVPlayer's item. I already looked around if there is support for this use case in AsyncDisplayKit and haven't found any. Therefore I started looking into building my own custom node to handle the change in a async way but was struggling with the implementation. Where would you guys start building that?

**Comment by secretiverhyme** [comment]
AsyncDisplayKit doesn't yet ship with a video node (#255), but pull requests are always welcome!

Can you clarify what you mean by "changing AVPlayer items asynchronously"?  Are you thinking of a reuse queue for AVPlayerLayers, so when a video node enters the working range, it grabs one and updates its AVPlayerItem?

**Comment by tspecht** [comment]
@secretiverhyme yes that was exactly what I was up to. Unfortunately that seems kinda hard due to AVFoundation seemingly having quite some limitations on background usage ...

**Comment by TaoNhan** [comment]
@tspecht Hi there, did you find any alternatives in order to real time manipulate AVMutableCompositions ? I am working on a similar project and I'm not happy with the workarounds I've developed

**Comment by appleguy** [comment]
This is an interesting subject, to be sure — but the main limitation is Apple's public API.  There are actually private APIs that allow various modes of background usage of AVPlayerLayer, but we would not be able to publish an AsyncDisplayKit component that uses these.

**Comment by richardtop** [comment]
@appleguy could you give a few links about private API? Thanks in advance.
