### ISSUE TITLE
[ASImageNode] placeholderColor property doesn't actually do anything

### ISSUE THREAD

**Issue by secretiverhyme** [facebook/AsyncDisplayKit#392]
We should either remove this property or implement proper placeholder support on ASImageNode.  (We could also make it an alias for `backgroundColor`, but that'd be cheesy.)

If we're going to implement placeholder support, we should look at #347 for both ASNetworkImageNode and ASMultiplexImageNode, perhaps replacing `defaultImage` with a new `placeholderImage` property.

**Comment by secretiverhyme** [comment]
Since placeholder images are likely to be reused assets, it would be wasteful to decode them and create potentially hundreds of identical backing stores at `-measure:` time.  It'd also be silly to block the main thread on synchronously rendering placeholder images while we wait for the real images to load.  Any objections to just removing this property?

**Comment by appleguy** [comment]
I am going to file a task in our internal bug tracker, Ship, to remove the placeholderColor property. For the large majority of developers, using background color is an equivalent and efficient solution. And for others creating a subclass that implements .placeholderImage can support anything from a 1px stretchable to emulate this behavior or a full size placeholder.
