### ISSUE TITLE
Crash when using ASTableView in a UITableViewController

### ISSUE THREAD

**Issue by arik-so** [facebook/AsyncDisplayKit#395]
When creating a UITableViewController in the storyboard and setting the TableView's class to ASTableView, the code crashes when loading the view controller with the following error:

```
*** Assertion failure in -[ASTableView setDataSource:], Pods/AsyncDisplayKit/AsyncDisplayKit/ASTableView.mm:146
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'ASTableView uses asyncDataSource, not UITableView's dataSource property.'
```

Naturally, it is clear to me that the crash is deliberate to warn users from setting the ASTableView's delegate and dataSource properties rather than their async counterparts. However, using TableViews in UITableViewControllers grants a lot of huge advantages which would otherwise require a lot of effort to achieve with simple UIViewControllers, especially when trying to maintain compatibility across multiple iOS versions. Additionally, in this instance, these assignments happen automatically.

It would therefore be grand if there was a way of somehow coupling an ASTableView with a UITableViewController.

**Comment by arik-so** [comment]
Perhaps one solution would be if you made an ASTableViewController that inherits the UITableViewController but doesn't set the delegate and dataSource properties?

**Comment by secretiverhyme** [comment]
> When creating a UITableViewController in the storyboard and setting the TableView's class to ASTableView, the code crashes when loading the view controller with the following error:

Storyboards are inadvisable in apps complex enough to benefit from AsyncDisplayKit; [here are a few reasons why](https://www.facebook.com/groups/551597518288687/permalink/719963538118750/?comment_id=720275868087517&offset=0&total_comments=11).  You can create ASTableViews in Interface Builder, but you'll still have to implement your ASCellNodes in code.

> However, using TableViews in UITableViewControllers grants a lot of huge advantages which would otherwise require a lot of effort to achieve with simple UIViewControllers, especially when trying to maintain compatibility across multiple iOS versions.

Can you elaborate on these advantages?  UITableViewController is itself a simplistic UIViewController subclass — you can implement it yourself in a couple hundred lines of code.  Are you noticing specific problems with ASTableView?

**Comment by arik-so** [comment]
Thank you very much for the storyboard comment. As to the advantages granted by letting a tableview be managed by a UITableViewController instead of a simple UIViewController, I was mostly referring to the content inset related ones.

When using a UIViewController and adding a UITableView or a subclass as the 0-index-subview, activating the automaticallyAdjustsScrollViewInsets property, optionally alongside with extendedLayoutIncludesOpaqueBars, adjusts the table view to have proper content insets depending on the orientation, navigation bars, tab bars, and other toolbars. At least it does that on iOS 8, but unfortunately, this function is extremely buggy on iOS 7.

Furthermore, when using keyboards or input accessory views, or both keyboards and input accessory views, their height is not added to the bottom offset, which requires extensive workarounds with didStartEditing-methods or keyboard notification listeners.

When the tableview is managed by a UITableViewController, however, all these problems are almost magically solved, and there is a certain guarantee of both backward and forward compatibility. This is pretty much the main reason why I was asking whether you would be offering an ASTableViewController or something of the sort in order to embed an ASTableView.

**Comment by appleguy** [comment]
@arik-so thanks for your thoughts on this.  It's definitely the case that ASTableView is not directly compatible with UITableViewController, if the latter sets the dataSource property instead of asyncDataSource (which it sounds like it does do).

We strongly recommend against using Interface Builder (for many reasons, it is not allowed for production implementation at Facebook, Instagram, Pinterest, and the overwhelming majority of the apps that come with iOS).  However, recently there was initWithCoder: support added to ASTableView so you can technically create the table itself from Interface Builder.  This is pretty much unsupported though.

I'd love to see a diff from the community to figure out a good way to support UITableViewController, which could be as simple as creating an ASTableViewController which intercepts and works around the small areas of incompatibility.
