### ISSUE TITLE
New Pod Version

### ISSUE THREAD

**Issue by Morgan-Kennedy** [facebook/AsyncDisplayKit#400]
Could we please have a new tag update in cocoapods? (maybe 1.1.2)

I really would like one of the new updates in my app (specifically the one that allows ASCollectionView to use a non-flowlayout.

Thanks

**Comment by bssayeda** [comment]
You don't necessarily need a new version of the pod.  Instead what you can do in your Podfile is

pod 'AsyncDisplayKit', :head

This will force Cocoapods to pull the latest and greatest from Github.  This will put you on the bleeding edge so beware of that if you start seeing build failures.  There is also a way to point to a specific commit in the Podfile which you can find here: http://guides.cocoapods.org/syntax/podfile.html

**Comment by markmark1** [comment]
Cool trying it with the example that was breaking with same urls
