### ISSUE TITLE
[ASTableView] Programatic cell selection

### ISSUE THREAD

**Issue by aldenks** [facebook/AsyncDisplayKit#401]
It doesn't seem to be possible to programmatically select cells in ASTableViews. There isn't a `selected` property on ASCellNodes and when I call `selectRowAtIndexPath:animated:scrollPosition:` the selection seems to be cleared/forgotten soon after.

Is this possible?

**Comment by hannahmbanana** [comment]
@aldenks - FYI a boolean selected property was added to ASCellNode in PR #745. 

I modified the VerticalWithinHorizontalScrolling example app to check the functionality of selectRowAtIndexPath:animated:scrollPosition: and it worked as expected for me with no unexpected clearing. I realize it's been a year, so you're probably long past this issue, but if you are still having this issue or any others, please let the community know!

**Comment by aldenks** [comment]
Thank you!

**Comment by appleguy** [comment]
@aldenks sorry for the long delay on this one! Selection was implemented around October of last year, a few months after you post this. Please do feel free to post more issues, or email me directly, with additional questions or bug reports. Hope you have found some utility or interest in the framework!
