### ISSUE TITLE
Unable to call invalidateCalculatedSize using Swift

### ISSUE THREAD

**Issue by ProjectDent** [facebook/AsyncDisplayKit#408]
This is a weird issue. In Objective-C, I'm able to call `[self invalidateCalculatedSize]` on any subclass of ASDisplayNode. In Swift, attempting to call `self.invalidateCalculatedSize` just shows it to be a non-existent method.

**Comment by nguyenhuy** [comment]
AFAIK, methods in `ASDisplayNode+Subclasses.h` are only meant to be called internally. Thus it's not imported in `ASDisplayNode.h` but in `ASDisplayNode.m`.

However, if you are writing a custom node yourself in Swift, you can add this line to your bridging header:
```#import <AsyncDisplayKit/ASDisplayNode+Subclasses.h>```
