### ISSUE TITLE
[ASCollectionView] reloadCellAtIndexPath repositions all dependent cells as if it's empty, for a split second

### ISSUE THREAD

**Issue by ProjectDent** [facebook/AsyncDisplayKit#410]
Upon calling `reloadCellAtIndexPath:`, all cells surrounding the cell which rely on it's size and position, jump into a position as if it's not there, and then resume their original position after a split second. Whether or not `displaysAsynchronously` is enabled on the ASCellNode doesn't make a difference to this behaviour.

**Comment by chicherin** [comment]
I think this is because reloadCell implemented by deleting the current cell, and adding a new one.
```
  dispatch_async([ASDataController sizingQueue], ^{
    [self syncUpdateDataWithBlock:^{
      DELETE_NODES(_nodes, indexPaths);
    }];

    [self _batchInsertNodes:nodes atIndexPaths:indexPaths];
  });
```
 Guys is it possible to somehow make reloadItemsAtIndexPaths without insert / delete?

**Comment by adly-holler** [comment]
:+1: Love this framework, want to use it in production if this gets ironed out

**Comment by appleguy** [comment]
@adly-holler — thanks for pinging the issue.  I still need to re-read all recent tasks now that some of the main development for ASDK 2.0 is about to launch.

I think this is probably still an issue, although I know there were some changes that could have addressed it, so definitely give it a shot against master if you are using 1.2.3.

The resolution will likely be as simple as wrapping the internal delete + insert with a batch update call.

**Comment by appleguy** [comment]
@ProjectDent @chicherin @Adlai-Holler: This is still an important issue to resolve. The implementation work shouldn't be too challenging, but we don't currently have anyone to look into it. Any volunteers? :)

Merging with #698 which has more details.
