### ISSUE TITLE
new version Can't find the method 

### ISSUE THREAD

**Issue by ReizSoon** [facebook/AsyncDisplayKit#413]
I has been updated to the latest version pod 'AsyncDisplayKit','~>1.1.1'
but Can't find the method - (instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style asyncDataFetching:(BOOL)asyncDataFetchingEnabled; In ASTableView.h
How can I solve this problem？

**Comment by nguyenhuy** [comment]
`pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git', :commit => '3c822fe698'`
