### ISSUE TITLE
 New issue Table and collection view "didSelectRowAt" delegate methods don't work with touchesBegan/Ended/Cancelled overrides

### ISSUE THREAD

**Issue by ReizSoon** [facebook/AsyncDisplayKit#414]
If you override touch methods on a custom ASCellNode subclass, you will not be able to receive cell selection events:

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
or

- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath;

I have already corrected the code below
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event
{
    [super touchesBegan:touches withEvent:event];
    if (_node.methodOverrides & ASDisplayNodeMethodOverrideTouchesBegan) {
        [_node touchesBegan:touches withEvent:event];
    }
}

**Comment by maicki** [comment]
@ReizSoon @appleguy This issue should be already fixed with one of the latest versions. Furthermore if you overwrite the touch method on a custom ASCellNode there is now a warning to call super.

@appleguy I think we can close that

**Comment by appleguy** [comment]
@ReizSoon: Thanks for contributing to the ASDK community by reporting this bug! 

If you are able to, please check out the latest version of master and confirm that this issue is resolved for you. If you are still having troubles, feel free to reopen this.
