### ISSUE TITLE
ASTableView edit mode crash

### ISSUE THREAD

**Issue by yufenglv** [facebook/AsyncDisplayKit#415]
When use UITableView in edit mode, we should set delegate to nil in `-(void)dealloc` ,or it will crash when release the controller. But when using ASTableView ,it cannot work since `setDelegate` is overwrited. 
![2015-04-03 11 38 50](https://cloud.githubusercontent.com/assets/1837609/6977711/0a9d1df2-d9f6-11e4-9c48-3c65d717af1e.png)

**Comment by appleguy** [comment]
@yufenglv, thanks for reporting this and my apologies for the delay in getting back.

Did you close this because the issue was resolved?  I know we recently merged a diff that I believe will address this, but I just wanted to make sure that was the solution.  Thanks!

**Comment by yufenglv** [comment]
@appleguy  This issue is not caused by ASDK, and I always set delegate to nil in `-(void)dealloc` to avoid crashing on iOS7 and above. Since `setDelegate` is overwritten in ASDK, it doesn't work now.

At last, I add `[self setEdgesForExtendedLayout:UIRectEdgeNone];` to `-(void)viewDidLoad` will prevent `UIScrollView`send message to the controller which is released. And I not sure if it's a bug of iOS7 and above.

**Comment by appleguy** [comment]
Thanks for the background.  I'm nearly certain this issue was fixed at the framework level (indeed, working around the Apple bug) in ASDK 1.2.  Let us know if you have another issue!
