### ISSUE TITLE
Runloop work distribution

### ISSUE THREAD

**Issue by ianolito** [facebook/AsyncDisplayKit#42]
In the NSLondon video, Scott talks about runloop work distribution. Unless I’m missing something here, this optimization does not seem to be implemented right now. I was wondering if you were still planning on adding this feature to the framework.

I understand this strategy applies to expensive operations that have to run on the main thread, such as creating views and adding them to the hierarchy. What about the opposite operations (removing from hierarchy and deallocating views)? Does those benefit from being distributed as well?

**Comment by swain666** [comment]
1

**Comment by shLuckySeven** [comment]
wow!nice
