### ISSUE TITLE
How to implement UIControlState

### ISSUE THREAD

**Issue by kocyigityunus** [facebook/AsyncDisplayKit#422]
i couldn't figure out how to implement states like UIControlStateHighlighted or UIControlStateSelected.

i saw events like ASControlNodeEventTouchDown, ASControlNodeEventTouchCancel but i couldn't figure out how to use that in my subviews. 

i am not sure this is the right place for this but stackoverflow tag is very inactive and there is nothing about it in examples. if you provide information about this i can add an example about states to project.

**Comment by kocyigityunus** [comment]
https://gist.github.com/kocyigityunus/0af6dbe65344a33e7c73

**Comment by appleguy** [comment]
@kocyigityunus, it might be easier if you share what you're trying to accomplish in the app.  I assume you saw ASControlNode?  Note that ASImageNode is an ASControlNode (I believe ASTextNode is as well), so you can use these control features in subclasses of those as well.

Sorry for the delay getting back to you here.  Please do open a new task (or post in our google group) if I can help further!
