### ISSUE TITLE
Impossible to set the initial content offset of an ASCollectionView?

### ISSUE THREAD

**Issue by adremeaux** [facebook/AsyncDisplayKit#438]
I'm trying to make an ASCollectionView with 100 nodes, and start in the middle. I've tried everything I can think of for settings the collectionView.contentOffset, including before setting the data source, after setting the data source, after its been added to the view, even trying to intercept the first call to willDisplayNodeForItemAtIndexPath to force it into position. Nothing works. Is this possible to do with ASCollectionView?

**Comment by blessingLopes** [comment]
Try this:
``` 
dispatch_async(dispatch_get_main_queue(), {
			self.collectionView.contentOffset = CGPointMake(0, 110) })
```
or the animated version:
```
dispatch_async(dispatch_get_main_queue(), {
			self.collectionView.setContentOffset(CGPointMake(0, 110), animated: true) })
``` 
I don't think this is a AsyncDisplaykit thing. I tried a couple different ways to set the contenOffset and the same quirks came up in both the UiCollectionView and the ASCollectionView.  I wish i could explain the reason why this only seems to work on the main thread but i'm not really sure... maybe someone out there can offer some light. Hope this will help :)
Cheers.

**Comment by eanagel** [comment]
You might take a look at my Pull request for `ASTableView`, #405. I had the same problem, which you would typically solve by calling `reloadData` then positioning without animation. The problem is that reloadData is actually an asynchronous task in ADK, so I added a completion block that fires once the datasource is initialized. You can position yourself in the completion block.

**Comment by adremeaux** [comment]
Would reloadDataWithCompletion then be called right after instantiation?

**Comment by eanagel** [comment]
Yes - We pull our data asynchronously on `viewDidLoad`, then when that completes we call `reloadDataWithCompletion:` and when that completes *then* we can move to any point in the dataSource.

**Comment by adremeaux** [comment]
OK, I've finally had a chance to get back to this, this is great eanagal, way better/faster than the main thread method, which I think was only "working" by virtue of it being enqueued to the end of the main queue, considering that the method I was calling it from was already in the main thread. 

When I'm using an ASCollectionView with range tuning, what methods are called on the cell (or in the delegate) when a cell comes into range, and then when it exits the range? I cannot find any documentation on this. I'm trying with layout() and didExitHeirarchy(), and it seems to be a bit of a superset of what I'm looking for. It is called on nodes coming into/exiting the range, but they are both also called seemingly randomly on cells that are long since out of range. Is there a proper way to do this?

**Comment by eanagel** [comment]
Ahh yes this is just coming clear to me as well. The hooks I've started using are `fetchRemoteData` and `clearRemoteData`. They are called when the cells come into (or leave) the prefetch range. It's a great place to start fetching remote images. For a great example take a look at the `ASNetworkImageNode` implementation.

By the way, I'm far for an expert here - so if anyone has a better solution, please chime in ;)

**Comment by adremeaux** [comment]
These methods are working swimmingly, much more consistent than the layout/didExitHierarchy setup. In combination with the reloadDataWithCompletion: for content offset, fetchRemoteData does get called on the first couple cells before the range is set (and clearRemoteData never called on those cells), however I've solved that by simply disallowing the content load of a cell via delegate until the contentOffset is set. Thanks so much!
