### ISSUE TITLE
How to add a UIView on ASDisplayNode?

### ISSUE THREAD

**Issue by yiqin** [facebook/AsyncDisplayKit#442]
I know how to add a ASDisplayNode on a UIView. But how to add a UIView on ASDisplayNode? 

For exmaple, in a ASCellNode, I use    "view.addSubview(scrollView)"

then, I got this error

*** Assertion failure in -[AppStore.ImageSetTableViewCell __measure:], /Users/yiqin/Desktop/yiqin-MPCS51032-2015-Spring-Assignment-2/Pods/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:446
2015-05-04 01:00:31.851 AppStore[5001:1356676] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Incorrect display node thread affinity'
*** First throw call stack:
(0x184c282d8 0x19644c0e4 0x184c28198 0x185adced4 0x100201e88 0x100201d1c 0x1001e49e0 0x184b23ef4 0x184b1a854 0x1001e4864 0x100b20fd4 0x100b20f94 0x100b2eb54 0x100b30248 0x196c7d22c 0x196c7cef0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Tobi3112** [comment]
Are you adding it on the main thread ? 

  // self.view isn't a node, so we can only use it on the main thread
  dispatch_async(dispatch_get_main_queue(), ^{
    [self.view addSubview:node.view];
  });

**Comment by yiqin** [comment]
@Tobi3112 Thanks. The addSubview should be in layout() method.

**Comment by appleguy** [comment]
This is an ideal question for one of our groups — either the Paper Engineering Community or AsyncDisplayKit Google Group :).  Happy to help!

Just as with UIKit, you should not modify the hierarchy in -layout / -layoutSubviews if you can avoid it.  Doing so will cause another layout pass.

Use the -didLoad method to add UIViews, UIGestureRecognizers, etc.  It is always called on the main thread.

Please watch my talk at Mobile Central Europe (search that with AsyncDisplayKit on YouTube) and you'll learn many of these things, and more!

**Comment by vandana26V** [comment]
Can anyone provide the code to get the ASDisplayNode from UITableViewCell.
