### ISSUE TITLE
Expose UIView like methods to know when a node moved in/removed from a superNode

### ISSUE THREAD

**Issue by mohpor** [facebook/AsyncDisplayKit#447]
I have been implementing a custom control using `ASTextNode` that needed to be in the center of its super node. I wanted to center it first when it got added to the super node but I guess there isn't any methods to override for that!

If I was going to accomplish the same thing using `UILabel`, I would've override `-(void)didMoveToSuperview;` and do what I wanted to do.

Am I missing something? Isn't it a legit request?  is `- (void)willEnterHierarchy` a good start?

**Comment by appleguy** [comment]
When something is added to the hierarchy, it may be the case that its supernode is not properly sized / positioned.  Is there any reason not to do the positioning in -layout?

That said, -willEnterHierarchy is a great way to do this.  If you wanted to do this yourself, remember that CALayer does not offer a direct equivalent to the UIView notifications.  AsyncDisplayKit automatically bridges this for you, but the behavior is not identical between view and layer-backed nodes.  It should work as you intend for nearly all cases, though.

Please let me know if you have any further questions, either by re-opening this task or a new one (or posting in one of our discussion groups).  Thanks @mohpor!

**Comment by mohpor** [comment]
you're right @appleguy, laying out views must be done there, of course I didn't consider `-layout` I don't know how it got away from me. Thanks for your feedback, appreciate it.
