### ISSUE TITLE
layout() not being called for ASCellNode subclass, when scrolling through an ASCollectionView

### ISSUE THREAD

**Issue by cbreed28** [facebook/AsyncDisplayKit#448]
I am using an ```ASCollectionView``` to display custom ```ASCellNode``` subclasses. In my ```ASCellNode``` subclass I override ```-calculateSizeThatFits:``` and ```-layout```. My custom cell consists of an image node and another custom subnode. Inside of ```-calculateSizeThatFits:``` for the cell subclass I am calling ```-measure:``` on my one custom subnode and returning a valid size. What I am seeing after calling ```-reloadData``` on my collection view is:

1. ```-calculateSizeThatFits:``` is getting called on all ( say 6 ) of my cells, all of which return the correct size that I want
2. ```layout()``` will be called for the first 2 visible cells, and everything works great. 
3. When cells 3-6 scroll onto the screen, the ASCollectionView is creating the UICollectionViewCell (_ASCollectionViewCell ) class, and adding my ASCellNode's view hierarchy too it, creating a UICollectionViewCell of the appropriate size on screen, however, ASCellNode for cell's 3-6 do not receive a ```-layout()``` call, which is causing all of my subnodes to have a bounds of CGRectZero. So essentially I am left with a bunch of blank cell in my Collection View.

I feel like I am missing a step somewhere but I can't say for sure. Any thoughts / suggestions?

**Comment by cbreed28** [comment]
I've been debugging this issue for awhile, looking through the ADK code base. I noticed that the ASCellNode's view was not getting laid out if the ASRangeController would add the ASCellNode to the working range before node's view received a -layoutSubview call.  So I needed a place to force a layout on the node's view to make sure that the -layoutSubviews call would be made before each cell was put on the screen. I modified the delegate hooks in side of ASCollectionView.mm to be as follows: 
```
- (void)collectionView:(UICollectionView *)collectionView willDisplayCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath
{
  [_rangeController visibleNodeIndexPathsDidChangeWithScrollDirection:self.scrollDirection];
    
  ASCellNode * node = [_dataController nodeAtIndexPath:indexPath];
  [node.view setNeedsLayout];
  
  if ([_asyncDelegate respondsToSelector:@selector(collectionView:willDisplayNodeForItemAtIndexPath:)]) {
    [_asyncDelegate collectionView:self willDisplayNodeForItemAtIndexPath:indexPath];
  }
}
```

Not sure if this violates any of the asynchronous layout properties of the node, but it seems to fix my issue by ensuring that the node's view receives a -layoutSubviews before being made visible.

**Comment by appleguy** [comment]
@cbreed28 Thanks for reporting this — I really would like to understand the base cause in your case, because this does not occur in example projects.

Are you still able to reproduce this on ASDK master or v1.2?  Would you be able to share some of your code that reproduces the issue?  Even if not a full project, some snippets could prove useful for me attempting to reproduce locally.

**Comment by cbreed28** [comment]
@appleguy Thanks for the response! Give me a day or so and I'll get an example project together that hopefully shows what I am seeing.

**Comment by oks** [comment]
I'm experiencing the same issue, when I layouting a lot of composite cells. 
Every cell consist from more that 10 subnodes, and they are subnodes too. 
Very hard to reproduce this issue, very inconsistent.

**Comment by oks** [comment]
btw - ASTableView has the same problem

**Comment by appleguy** [comment]
@cbreed28: @oks: I'm sorry that you experienced this issue. Thank you for reporting it! At this point, these layout methods should be very stable and have been tested extensively. If you are still using AsyncDisplayKit, please upgrade to the 1.9.8 release. Let me know if you run into any issues and I will investigate them promptly!

**Comment by altairdeark** [comment]
Why is it closed?
Same problem even on v2.4, appears only on 9 iOS

**Comment by appleguy** [comment]
@altairdeark Please see the README.md page - this entire project / repository is closed. The project is now at texturegroup.org - you can re-file the same issue there and we'd be happy to discuss :)

**Comment by appleguy** [comment]
Feel free to provide a screenshot of your code or copy / paste the core implementation. Make sure you have not left out any calls to -super. It's also possible that how you are using the methods is not quite right; you may need to implement a method like -calculatedLayoutDidChange instead.

**Comment by appleguy** [comment]
Scroll down below the files to see the prominent notification of the new project location:

https://github.com/facebookarchive/AsyncDisplayKit
