### ISSUE TITLE
ASImageNodeRoundBorderModificationBlock not working correctly

### ISSUE THREAD

**Issue by NataliaTs** [facebook/AsyncDisplayKit#450]
borderWidth isn't working in ASImageNodeRoundBorderModificationBlock. Border is always 1px width.
Changing line
`CGContextSetLineWidth(UIGraphicsGetCurrentContext(), borderWidth);`
to
`roundOutline.lineWidth = borderWidth;`
solves the problem.

**Comment by appleguy** [comment]
Fixed, thank you!
