### ISSUE TITLE
Inserting new nodes at top without animation.

### ISSUE THREAD

**Issue by NareshKalakuntla** [facebook/AsyncDisplayKit#452]
I am using ASTableview (AsyncDisplayKit v1.1.1) to show feed in my app. 
I will check with my server if there are any new feeds available and wanted to add these latest feed at the top of all the nodes. I do this using **insertRowsAtIndexPaths:withRowAnimation:** instead of **reloadData:** on table view.
When I do this my table automatically scrolls to top or first node automatically.

Can you please help me in adding new nodes without scrolling to the top position and effecting the user scroll. Just like the Facebook app, even if we are scrolling, the scroll position of the table is not effected and the new posts are added at the top.

**Comment by appleguy** [comment]
Hi @NareshKalakuntla — I just merged a diff that should prevent animation when you use the "None" animation option.  There was previously a bug with this.  Could you try building your project against master (change the Cocoapod spec) and let me know if you still see the issue?  We'll try to roll a new stable release of ASDK soon that includes these improvements.

**Comment by appleguy** [comment]
There's a specific diff to resolve this, so without hearing back, I think we're set here.  Please do reopen if you see the issue again.
