### ISSUE TITLE
Investigate completeness of visible row tracking.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#458]
See discussion in https://github.com/facebook/AsyncDisplayKit/pull/430.  Is there a way to avoid this manual tracking entirely, and is it certain that a single pending indexPath is sufficient for all cases?

**Comment by appleguy** [comment]
@eanagel as it turns out, this can cause a very severe wedging of ASLayoutController...it's possible for the pending index to be disjoint from the other indices in a way that makes for an unsolvable set of constraints for the flow layout controller, which causes it to live-lock and burn as much memory and CPU as is available :(.

Do you have a reproduction case for the original issue?  I do fortunately have a reproduction case for the live-lock issue.

Here's some example output alongside the screenshot:

(lldb) p _scrollDirection
(ASScrollDirection) $0 = 4
(lldb) po visibleNodePaths
<__NSArrayI 0x7fc1c2f9a2d0>(
<NSIndexPath: 0xc000000000220056> {length = 2, path = 1 - 68},
<NSIndexPath: 0xc000000000228056> {length = 2, path = 1 - 69},
<NSIndexPath: 0xc000000000230056> {length = 2, path = 1 - 70},
<NSIndexPath: 0xc000000000038116> {length = 2, path = 4 - 7}
)


(lldb) po _delegate
<ASTableView: 0x7fc1ba815c00; baseClass = UITableView; frame = (0 0; 100 500); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x7fc1b9632dc0>; layer = <CALayer: 0x7fc1b962fe70>; contentOffset: {0, 36343}; contentSize: {100, 172800}>

(lldb) po [_delegate indexPathsForVisibleRows]
<__NSArrayM 0x7fc1bb16a380>(
<NSIndexPath: 0xc000000000220056> {length = 2, path = 1 - 68},
<NSIndexPath: 0xc000000000228056> {length = 2, path = 1 - 69},
<NSIndexPath: 0xc000000000230056> {length = 2, path = 1 - 70}
)

![screen shot 2015-06-21 at 4 56 55 pm](https://cloud.githubusercontent.com/assets/565251/8273962/0ad7ef7e-1838-11e5-8a8b-56bc64abc1db.png)

**Comment by eanagel** [comment]
Uh Oh. Yes I can reproduce this pretty easily by adding a new cell then programmatically scrolling it into view. There is come code that helps avoid this problem when the **user** is scrolling by detecting the scroll direction. This value isn't set currently when scrolling programmatically. Maybe setting this correctly is an alternative way of solving the problem and avoiding nasty deadlock issues.

Alternatively, we could ensure the items are contiguous. Let me investigate.

**Comment by appleguy** [comment]
I think I fixed this with my tracking set.  It probably has horrible overhead, but I believe it eliminated these orphaned pending indices.  I think what was happening is that multiple rows were coming in and overwriting the pending variable without a matching clearing of the variable occurring before it was overwritten again, and then it would just be stuck after that point.

Check out the NSMutableSet in https://github.com/facebook/AsyncDisplayKit/pull/496/files

Thanks @eanagel for discovering the original issue here, as adding the set was super easy in comparison!  Hopefully we can find a way to remove it someday soon, perhaps by discovering an alternative means to drive the working range instead of listening to these methods now that we know they aren't 100% consistent.

**Comment by eanagel** [comment]
This is pretty close to my first attempt, see #427. I ended up closing it and going with the second approach because it turns out UITableView does not always make matching willDisplayCell:/didEndDisplayingCell: calls. There are edge cases where the didEndDisplayingCell: is not called (seems like reload or scrolling w/o animations?) You can paste in my debug code and you'll get warnings when your results vary too far from UITV's idea of visibleCells. In that case I ended up with a stale range of cells in addition to the actual visible ones. I don't think the additional set magic you have will stop that from happing, will it?

Why can't anything be simple ;)
