### ISSUE TITLE
Fetch and add to ASTableView when you scroll to bottom

### ISSUE THREAD

**Issue by joshg47** [facebook/AsyncDisplayKit#463]
Hey I was wondering what is the best way to have ASTableView fetch data and add rows when you are scrolling (like how Twitter and Facebook do it). Right now it's hard to achieve because there's a delay between adding the rows and how long it takes for the table view to refresh, which causes my implementation to crash. Any input would be appreciated! Thanks!

**Comment by levi** [comment]
Have you considered using the `tableView:willBeginBatchFetchWithContext:` delegate method invoked when an ASTableView is at the end of its data? More info here: https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTableView.h#L205

**Comment by appleguy** [comment]
@joshg47 feel free to post a new task with details on your implementation — it sounds like you may need a slight refactoring to support asynchronous layout.  This should not be too difficult to achieve, and I'm happy to help.  The built-in batch loading support should allow you to write less code than you would have to without ASDK.
