### ISSUE TITLE
How to use AsyncDisplayKit without CocoaPods or creating workspace ?

### ISSUE THREAD

**Issue by jjjjjeffrey** [facebook/AsyncDisplayKit#467]
i drag AsyncDisplayKit directory in my project, it were always wrong when i build it, there are many .h file not found, the code that is like this: #import<AsyncDisplayKit/ASDisplayNode.h>, is there any way to solve this problem without using CocoaPods or creating workspace?

**Comment by appleguy** [comment]
@jjjjjeffrey this isn't directly supported, but I believe you will be unblocked by this: https://github.com/facebook/AsyncDisplayKit/pull/449

I hope to land that as soon as the author (or Carthage-knowledgable folks) weigh in on the naming of the target.  But, it should provide you a way to at least build an ASDK static library that you could manually link in.

**Comment by appleguy** [comment]
Discussion is still going on in the PR.  Hoping we have a solution on master / in a release in a couple weeks.  Feel free to check out a branch from that PR, which should be a good short-term solution if you don't want to use Pods (it's not that bad of a tool, really! :) )

**Comment by appleguy** [comment]
@jjjjjeffrey the Carthage support has been merged.  Please let me know if it doesn't suit your purposes.  Also note that you can build the AsyncDisplayKit library and include the binary manually in your project as well, although I encourage you to look here for updates on a regular basis; 1.2.2 is coming out today and will be really great :)

**Comment by markmark1** [comment]
What's Carthage support ?

**Comment by markmark1** [comment]
How does asdk fit with component kit




Are there are any best practices

Is there a way to choose any pointers appreciated
