### ISSUE TITLE
Inserting ASCollectionView Into UIScrollView

### ISSUE THREAD

**Issue by bennettl** [facebook/AsyncDisplayKit#474]
Hello,

I'm trying to establish this view hierarchy:

UIView
-- UIScrolView
----UILabel
----UILabel
---- Other UI Views
---- ASCollectionVIew (Pin at bottom)

Is this possible? I tried added ASCollectionView as a subview of UIScrollview and using autolayout to pin ASCollectionView to the bottom of UIScrollView, but it doesn't seem to work.

**Comment by appleguy** [comment]
I'd love to help — just add some further details here!

It is definitely possible to put an ASCollectionView in a UIScrollView.  I would not recommend using Autolayout (frankly, for anything, but especially for something like "pin to bottom" — I'm not aware of auto layout being capable of dynamic repositioning like that).  Try using scrollViewDidScroll: to set the frame of the ASCollectionView if you need to move it while scrolling is going on.

If your goal is to keep it in one place on the screen (like the bottom of the screen, while the content scrolls) can't you just put the ASCollectionView at the same level of the UIScrollView—like a direct subview of the UIView in your example?  Could you share a screenshot or even just a hand-drawn sketch of what you're trying to do?

Last question is if your ASCollectionView will scroll horizontally, or vertically.  What you've described seems to make the most sense if the collection scrolled horizontally — this is a common use case that we're looking at in the Pinterest app, for example — but I just want to make sure.  Vertical scrolling can be made to work too, but might be confusing to the user or require some attention to the gesture handling.

**Comment by macistador** [comment]
@appleguy As nothing new popped-up, maybe this issue should be closed ?

**Comment by appleguy** [comment]
@bennettl - thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time it’s been since this thread was active, I’m going to mark this issue as closed. If you are still having troubles, feel free to reopen it. I hope you have been able to use the framework!

**Comment by appleguy** [comment]
closing issue
