### ISSUE TITLE
Placing ASCollectionView with Autolayout

### ISSUE THREAD

**Issue by bennettl** [facebook/AsyncDisplayKit#475]
Is it possible to position my ASCollectionView via autolayout? When I create the constraints, I recieved the message

2015-06-08 11:50:05.763 TapitureV3[63263:23751156] negative or zero item sizes are not supported in the flow layout

**Comment by appleguy** [comment]
Hey @bennettl, thanks for the question.  It should certainly be possible to place the collection view itself using auto layout.  I searched AsyncDisplayKit for the string you included here, and it doesn't appear to exist.  Do you know if this log is coming from UIKit (UICollectionViewFlowLayout itself) or some code in your app?

It does seem like a reasonable thing to assert that item sizes are not negative, although sometimes being zero-sized for a brief moment is OK.

Let me know if you are able to share any of your setup code (e.g. where you are setting constraints) for us to look at together.

**Comment by appleguy** [comment]
Please reopen if you're able to add any specifics to the issue!
