### ISSUE TITLE
Implement ASStackNode

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#477]
This was useful in Paper, but never implemented in an OSS-quality way.  Without waiting for iOS 9's UIStackView (and being stuck with main threaded layout), we could easily provide vertical and horizontal stacking with such a node.

**Comment by markmark1** [comment]
That'll be great Scott

**Comment by nguyenhuy** [comment]
I don't want to brag about my PR #468 too much, but it happens to include
[a stack layout](
https://github.com/facebook/AsyncDisplayKit/pull/468/files#diff-f52e889555f498a5e617f0e17b8b34d4)
(and some snapshot test cases). Not sure if we should split that
ridiculously huge PR and cherry pick the stack node. Anyway, let me know if
there is anything I can help :)

**Comment by lxcid** [comment]
This would be so awesome and immediately make this better than componentkit imo.

**Comment by levi** [comment]
We have been experimenting with some sort of flexbox node in our own app. I'm not too familiar with your fork, @nguyenhuy, but I'd love to see an ASStackNode with an API very similar to Apple's new stack view. There's some sort of appeal making a polyfill on top of a newer API those without ASDK can only experiment in isolation right now.

@appleguy, were you planning on building this? If not, I'd love to take a crack at contributing something very similar to UIStackView.

**Comment by appleguy** [comment]
Thanks everyone for the interest, it's super great to see it :).  Folks at Pinterest are also interested in having this component.

@levi, feel free to take a pass at it.  Just let me know if plans change and you won't have a chance to do so.  I have some more pressing ASDK issues (finalizing and launching 1.2.1 among a few other things), but if we don't have this component in ~2 weeks, I'll build it.

**Comment by levi** [comment]
@appleguy things got backed up on my end. Won't be able to move forward with an implementation in the next 2 weeks. Thanks for the heads up.

**Comment by appleguy** [comment]
This has effectively been achieved in #468.  It is not a dedicated node, but indeed I think the model in that patch makes even more sense, as it prevents the creation of any additional layers / views that would otherwise exist soley as an artifact of the layout heuristics.  The ASLayoutSpec / ASLayout approach is able to flatten those logical layouts into a minimized hierarchy.
