### ISSUE TITLE
[ASCollectionView] Scroll to end

### ISSUE THREAD

**Issue by ajk198** [facebook/AsyncDisplayKit#487]
Hi,

I'm using ASCollectionView to display a horizontal list of images. When newly added items go off screen, I need to automatically scroll to show the new item.

I can't seem to find a way to do this currently with ASCollectionView since inserting is async, I'm not able to scroll to the new item until after that item has been added into the view and there doesn't seem to be anyway to get a callback once the item has been added.

Thanks,
ajk

**Comment by nguyenhuy** [comment]
Yes, currently updating methods don't have callback. I agree that having a completion callback would be very useful. @appleguy may have a better opinion about whether or not supporting this feature is a good idea.

For the time being, I guess a possible workaround is to use [`-performBatchUpdates:`](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASCollectionView.mm#L286), which does accept a completion block. There may be runtime overhead, but it should not be significant.

**Comment by ajk198** [comment]
@nguyenhuy I'll give that a shot! Also great work on the flexbox integration, it looks great.

**Comment by nguyenhuy** [comment]
Thanks, @ajk198 :)

**Comment by macistador** [comment]
Hi @nguyenhuy ! As nothing new popped-up, maybe this issue should be closed ?

**Comment by nguyenhuy** [comment]
Yes, it should be closed. I don't have the user permission though :)

**Comment by macistador** [comment]
Ok, just helping to clean the issue stack as I am reading :)

**Comment by nguyenhuy** [comment]
Yes, every help is appreciated. Thanks!

**Comment by appleguy** [comment]
@ajk198 - thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time it’s been since this thread was active, I’m going to mark this issue as closed. If you are still having troubles, feel free to reopen it. I hope you have been able to use the framework!
