### ISSUE TITLE
ASFlowLayoutController.mm deadlock (Stuck in while loop)

### ISSUE THREAD

**Issue by SRandazzo** [facebook/AsyncDisplayKit#530]
First want to say thanks for this great library, have been getting familiar and am loving it.

I've seen there has been a lot of work recently on ASTableView, specifically stress testing to address some known issues, so this may not be valid. If you can point me towards a commit i'd love to see if that resolves my issue, which is as follows:

At random intervals, I am experiencing a deadlock in `ASFlowLayoutController.mm`, line 191, in the `while` loop. I can pause to catch the loop and step through, but it looks like the condition is just never being met. 

I've posted two screenshots of where i caught this infinite loop, as well as the values of startIter and endIter. 

I am doing some rapid updates to the tableview, calling reloadData, or reloadItemAtIndexPath frequently

![screen shot 2015-06-29 at 4 55 03 pm](https://cloud.githubusercontent.com/assets/307819/8418239/d57fb458-1e7f-11e5-90ee-381841b2d38f.png)
![screen shot 2015-06-29 at 4 55 42 pm](https://cloud.githubusercontent.com/assets/307819/8418242/d7ed1ce4-1e7f-11e5-8752-81928c72c6b6.png)

Thanks Facebook + @appleguy !

**Comment by appleguy** [comment]
@SRandazzo Yes, this is a known issue and is a P0 / top priority for myself and a couple others.  I'm gunning to get through the work-week so I can finalize a fix to this issue on the weekend, if folks like @RCacheaux aren't able to fix it before I have the opportunity.  This is in fact the only thing holding up landing my other PR that overhauls ASDataController and substantially improves its robustness, such that it passes the rather rigorous ASTableViewStressTest :).

If you have any chance to debug this and submit a patch, go wild!  Not to worry, though, I hope to have a fix up by the end of Saturday.

**Comment by appleguy** [comment]
@SRandazzo — thanks again for reporting this, and I'm really honored to hear that the framework has been useful for you :).

Please do try again on the latest master, as I just landed a stack of extensive changes to this area.  I simply can't be certain if it resolves your particular issue, but I have good reason to believe it will, as my testing has not yet found a deadlock / livelock / crasher in this code.  That said, my testing is continuing; tomorrow I'll push the ASCollectionView test, and will improve the tests after the automatic layout (box model) diff lands.

**Comment by appleguy** [comment]
Closing this out to finalize the 1.2.2 milestone, since I'm pretty confident it is resolved.  Please do re-file if you still see an issue.
