### ISSUE TITLE
ASTableView not updating the ASTextCellNode via ReactiveCocoa

### ISSUE THREAD

**Issue by GreyEcologist** [facebook/AsyncDisplayKit#537]
I have a specific example where I want to update the table rows without having to reload the table or the rows by instead using reactiveCocoa, but I'm just not able to so far. I have ASTextCellNode which text should update itself every 10 seconds, and I can see in the logs that inside the doNext statement, the value for the text is being changed every ten seconds, but the table displaying the node is not reflecting the change   More generally, how do you make the ASTableView re-render and update the visible rows? ( I tried measure: but that didn't work either).

in my init():

```
self.tableView = ASTableView(frame: CGRectMake(0 , 60, 300, 400), style: UITableViewStyle.Plain, asyncDataFetching: true)
...
self.tableView.asyncDataSource = self
self.tableView.asyncDelegate = self
```

and inside nodeForRowAtIndexPath():

```
var node = ASTextCellNode()
        node.text = "Celeb"
        nodeVM.updateNodeModelSignal  // recurring RACSignal returning every 10 seconds
            .doNext { (object: AnyObject!) -> Void in
                node.text = node.text + " \(nodeVM.currentScore!)"
            }
            .subscribeNext({ (object: AnyObject!) -> Void in
                },
                error: { (error: NSError!) -> Void in
            })
       return node
```

**Comment by RuiAAPeres** [comment]
> More generally, how do you make the ASTableView re-render and update the visible rows? ( I tried measure: but that didn't work either).

The cheapest way would be to [reload](https://github.com/facebook/AsyncDisplayKit/blob/c8518c7fa6304f99db84b5480afce8f0b6ddb66e/AsyncDisplayKit/ASTableView.h#L207) the specific cell. But I would advise reading [this](https://github.com/facebook/AsyncDisplayKit/issues/600#issuecomment-129499491) from @nguyenhuy's

**Comment by appleguy** [comment]
@GreyEcologist I'd never heard of an attempt to use ASDK with Reactive Cocoa, but would be very curious if you have findings or ideas for how the two could be more cleanly integrated :).  It may well be possible to do easily, or it might be pretty incompatible.

**Comment by RuiAAPeres** [comment]
@appleguy I have been working on my current project with RAC quit extensively. Being AsyncDisplayKit a library with performance/speed in mind, RAC's overhead could potentially jeopardise that. I guess for bits that are not performance sensitive it could perfectly work. 

The main advantage I can see from using something like RAC, would be a more declarative API, that could be indeed interesting. I had this idea for a while, and was [implemented successfully by others](http://blog.scottlogic.com/2014/05/11/reactivecocoa-tableview-binding.html), would be a declarative way of implementing an `UITableView`'s dataSource delegate methods.
