### ISSUE TITLE
ASDataController does not call begin/end Updates delegate methods in correct order

### ISSUE THREAD

**Issue by eanagel** [facebook/AsyncDisplayKit#564]
Currently `ASDataControlle`r calls` -dataControllerBeginUpdates:` and `-dataControllerEndUpdates:completion`: directly on the main thread while calls to perform edits (such as` -dataController:didInsertNodes:atIndexPaths:withAnimationOptions:`) are routed through the editingTransactionQueue first. This results in the begin and end updates calls being made immediately followed by the editing delegate calls.

UITableView, for instance will ultimately see calls such as:

 - beginUpdates
 - endUpdates
 - insertRows:...

**Comment by AgeOfMobile** [comment]
I second this. After upgrade to 1.2.2 from 1.2, I faced a lot of problems if I use [ASCollectionView performBatchUpdates:complete. The "complete" block is called before edit methods (insert/reload/deleteRows...) completed.

**Comment by eanagel** [comment]
Resolved by #575, closing
