### ISSUE TITLE
Incorrect display node thread affinity

### ISSUE THREAD

**Issue by l4u** [facebook/AsyncDisplayKit#57]
'Incorrect display node thread affinity' when ASTableView is used with a UIPageViewController

https://github.com/l4u/AsyncDisplayKit_ASTableView_bug_with_UIPageViewController

To reproduce, swipe for 1 or more pages.

**Comment by phatmann** [comment]
@megakode, if you can confirm that this issue is the cause of your crash, we should either re-open this issue or you should file a new one.

**Comment by secretiverhyme** [comment]
We haven't seen any reports of this particular crash recently, but please do file a new issue if they recur.  The thread-affinity API is something we've been wanting to remove for a while, and it's on our radar for AsyncDisplayKit 1.2 — subscribe to #134 if you'd like to follow along.
