### ISSUE TITLE
ASCollectionView no longer animates insertion/deletion of cells

### ISSUE THREAD

**Issue by levi** [facebook/AsyncDisplayKit#576]
The latest updates to 1.2.2 have disabled insertion/deletion animations in `ASCollectionView` when invoked inside the `performBatchUpdates` method.

I have not tested the same behavior in ASTableView, however.

**Comment by appleguy** [comment]
@eanagel has been working in this code with me.  We're about to publish 1.2.3, either today or tomorrow, which may resolve your issue; it does have an animated: property on the batch update call.

**Comment by levi** [comment]
Confirmed that this is indeed fixed in 1.2.3.
