### ISSUE TITLE
[ASDisplayNode] Keepalive reference for layer-backed nodes

### ISSUE THREAD

**Issue by ianolito** [facebook/AsyncDisplayKit#58]
_ASDisplayView implements a keepalive reference to its node so that it stays alive as long as the view is in the hierarchy. This is what makes the [example shown here](http://asyncdisplaykit.org/) work, nothing else retains the node.

However, this mechanism is not implemented for layer-backed nodes, and I don't see an easy way to do it. As far as I know, CALayer does not have a direct equivalent to `-[UIView willMoveToSuperview:]`. There is the onOrderIn event but it is only sent when the layer enters a visible hierarchy. This is too late in our case.

Since converting to layer-backed nodes is said to be "as simple as" setting a boolean, I guess this limitation should be documented if a solution cannot be found.

**Comment by appleguy** [comment]
Even with extensive use of layer-backed nodes, I really haven't been hitting this issue.  You should have at least one other thing retaining the node - at the minimum, a subnode array.  This is one reason why ASCellNode refuses to be layer-backed, and neither can collection/table/pagernode or ASViewController.

That said, I will move this issue to our new tracker, primarily to openly document the subtle behavior differences that come with layer backing and also as a place holder for a future investigation of possible improvements in this area.
