### ISSUE TITLE
ASTableView can't pick cell in editing model

### ISSUE THREAD

**Issue by drinking** [facebook/AsyncDisplayKit#580]
I wan't to pick multiple rows in editing model, but the cell can't be selected.

    - (UITableViewCellEditingStyle)tableView:(UITableView *)tableView editingStyleForRowAtIndexPath:(NSIndexPath *)indexPath {
        return UITableViewCellEditingStyleDelete | UITableViewCellEditingStyleInsert;
    }

**Comment by appleguy** [comment]
@drinking We've added editing support to examples/Kittens; there are some minor visual glitches as elements resize if you scroll around after entering edit mode, but aside from this, it seems to work well.

I'd love to help with any issues you're encountering if you can provide some more details.  Feel free to file an issue with a video and explain some of the debugging you've tried (e.g. are you sure that your implementation of the cell is not capturing touch events?)
