### ISSUE TITLE
collectionView supplementary view crashes with version 1.2.3

### ISSUE THREAD

**Issue by wieseljonas** [facebook/AsyncDisplayKit#588]
Works fine with 1.2.2.

With 1.2.3 I get an error like so

   'UICollectionView is planned to support supplementary views by September 2015. You can work around this issue by using standard items.'

This is how I add the supplementary view:

this in 'viewDidLoad'

    let headerlayout = UICollectionViewFlowLayout()
        headerlayout.headerReferenceSize = CGSizeMake(self.view.frame.size.width, 238)
        collectionView.collectionViewLayout = headerlayout
        
        /* Register the header's nib */
        collectionView.registerNib(UINib(nibName: "ProfileHeaderView", bundle: nil), forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "ProfileHeaderView")

and this in the 'viewForSupplementaryElementOfKind'

    func collectionView(collectionView: UICollectionView!, viewForSupplementaryElementOfKind kind: String!, atIndexPath indexPath: NSIndexPath!) -> UICollectionReusableView! {
        if kind == UICollectionElementKindSectionHeader {
            let headerView = collectionView.dequeueReusableSupplementaryViewOfKind(kind,
                withReuseIdentifier:"ProfileHeaderView", forIndexPath: indexPath) as! ProfileHeaderView
            return headerView
            
        } else {
            return UICollectionReusableView()
        }
        
    }

**Comment by appleguy** [comment]
@wieseljonas Thanks for reporting this.  I'm interested to hear that supplementary views have been working in your app with prior versions, as they have never been properly supported.

Have you seen any crashes in your app prior to this assertion being added in 1.2.3?  I'd be happy to remove it if it turns out there are some use cases that are working properly, even though other uses cases (especially those that edit the collection contents, such as loading more from the network) are not.

I do hope to properly implement supplementary view support in the next 2-4 weeks, and will roll a 1.2.4 that either removes this exception or adds proper support.

**Comment by wieseljonas** [comment]
@appleguy Thanks frou your reply. No I didn't notice any issues prior to 1.2.3. I reverted to 1.2.2 for the moment.

I do manage to add network content to the supplementary view under 1.2.2.

Please not don't use a `ASNode` for these supplementary views but a classic `UICollectionReusableView`

**Comment by levi** [comment]
We've been using supplementary views in our collection view pre 1.2.3. Our initial issues were with width rendering if the (vertically scrolling) collection view's cells have a left/right section inset. We worked our way around this problem by providing cell inset support to ASCollectionView internally. We've noticed larger issues when trying to reload supplementary views individually, which we avoided by providing a flat list of various node types to the collection view.

**Comment by appleguy** [comment]
@wieseljonas thanks for the input.  We're planning to use regular reusable views for supplementary views.  @levi offered to look at this soon — whether he can do it or I do, 1.2.4 should include it :).  I think 1.2.2 for now is a reasonable workaround.

**Comment by tettoffensive** [comment]
@appleguy It looks like this is still not going to be supported in this next beta? Is that correct?

**Comment by levi** [comment]
@wieseljonas, @tettoffensive I recently landed support into master. You should be good to go on using supplementary views out of the box with flow layouts. Please feel free to open a new issue if you run into any problems or have feedback.

**Comment by appleguy** [comment]
Thanks @levi !  The amount of effort that went into that iteration is genuinely an inspirational example of OSS being successful.  I'm going to call it out in a TechCrunch interview this Friday as a leading indication of the community momentum that has been brought to this project by caring and generous developers like yourself.

@wieseljonas, @tettoffensive likewise, I appreciate you engaging with the community and look forward to hearing about how the Supplementary support works.  Please open new Issues if you find even a small bug.

**Comment by wieseljonas** [comment]
Thank you guys I will test it right now! Great job @levi

**Comment by wieseljonas** [comment]
Just tried it works like a charm!

**Comment by wieseljonas** [comment]
Actually I went I bit quickly. I get this issue with my setup

`'could not dequeue a view of kind: UICollectionElementKindSectionHeader with identifier _ASCollectionSupplementaryView_UICollectionElementKindSectionHeader - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'`

Does it mean I have to use `collectionView.registerSupplementaryNodeOfKind()`. Is it possible to use a simple `UICollectionReusableView `?

**Comment by levi** [comment]
Jonas, you're correct in that you have to call `collectionView.registerSupplementaryNodeOfKind(UICollectionElementKindSectionHeader)`. This will register a backing reusable view that ASCollectionView will use to insert the `ASCellNode`s you provide in the data source method `collectionView:nodeForSupplementaryElementOfKind:atIndexPath:`. This way you'll get all the added benefits of off-main queue rendering that collection view items have had for a while.

**Comment by appleguy** [comment]
Thanks for diving in with the fix!  @levi, can you think of any way to add our own assertion or exception that delivers this advice, as it would be an easy thing to miss when adopting ASCollectionView using a layout that has supplementary elements?

**Comment by wieseljonas** [comment]
My question is the following. Is there a way to use a normal `UICollectionReusableView `. The reason is the following. I have a complex header for my collection which would not benefit from being 'ASNode'

**Comment by appleguy** [comment]
@wieseljonas my apologies for missing this comment — please feel free to open new tasks in the future for anything that is closed, especially if you don't ping a user directly!

You can accomplish that pretty easily, although it may not be exactly what you want.  Use the node initializer -initWithViewBlock: and you can create your standard view header in-place.

This might actually work with -[ASCellNode initWithViewBlock:] directly, although I'm not confident on that.  ASCellNode definitely doesn't support layer-backing (so you couldn't use -initWithLayerBlock:), but it should probably work with the view version.  If it doesn't, it should be trivial to create an ASCellNode subclass.

If you do have to create the ASCellNode subclass, then you can get away without wrapping the views at all.  In that case, simply allocate them in the -didLoad method of the ASCellNode subclass, and add them as a subview of self.view.  Make sure to lay them out in the -layout method (called in the same situation as -layoutSubviews), probably just setting the containing view's frame to self.view.bounds.

**Comment by wieseljonas** [comment]
@appleguy Sorry for my late reply. Thanks for the thorough answer. I still haven't decided how to best manage my use case. My supplementaryView is complexe and need a lot of updating after being displayed and I'm not sure having a `ASCellNode` is the best option. What's your opinion on this?
