### ISSUE TITLE
ASStackLayoutSpec ASTextNode with nil string returning non-zero height

### ISSUE THREAD

**Issue by SRandazzo** [facebook/AsyncDisplayKit#606]
Hi ASDK!

I have an implementation question about using `ASStackLayoutSpec` in a vertical context

I'm stacking a few `ASTextNode`s, and was expecting that if one of the text node's attributedText was nil, the height should calculate as zero, resulting in a "stack" with no spaces in between elements.

Instead, the label is returning a width of zero, but height of 14, leaving a 14 px gap in between my resulting layout

Was wondering if this was expected or not?

using the latest master

Thanks!

<img width="88" alt="screen shot 2015-08-12 at 8 49 58 pm" src="https://cloud.githubusercontent.com/assets/307819/9240394/b60196f6-4133-11e5-8e48-4afc8e08cebf.png">

**Comment by SRandazzo** [comment]
I should add that when you switch the layout to `Horizontal`, it lays out as I would expect, since the size for the label is calculated to be `{ 0, 14 }`

<img width="208" alt="screen shot 2015-08-12 at 9 38 57 pm" src="https://cloud.githubusercontent.com/assets/307819/9240941/a35041e0-413a-11e5-8463-446671d3691d.png">

**Comment by appleguy** [comment]
@SRandazzo — this is a curious finding.  I would expect this in a way, in that the height is presumably determined by font size (you could test this by changing the font size.  However, that seems more like an implementation detail than really the correct behavior for this case.

It would be an easy thing to fix, particularly for a nil string (even a @"" empty string might be more plausibly nonzero height, but that's harder to decide!)  Could you run a quick test with UILabel and see what its sizeToFit does with a nil string, with an explicit font set?  I assume it is 0, 0.

Feel free to submit a diff to check for a zero-length string (which would catch nil, too) in the size/layout methods of ASTextNode.  If you don't have a chance to do this, that's fine; I'll make sure it gets into an upcoming release.

**Comment by SRandazzo** [comment]
@appleguy Thanks!

 Threw this into a playground to test what `sizeToFit` does on a label with an empty string text

The result is that calling sizeToFit on a UILabel with an empty strings results in CGSizeZero

<img width="870" alt="screen shot 2015-08-13 at 2 44 59 pm" src="https://cloud.githubusercontent.com/assets/307819/9258510/f106a7f0-41c9-11e5-8add-497e8370af2d.png">

**Comment by SRandazzo** [comment]
I have also pull requested a fix that addresses this on the render level, see the PR for details! Thanks!

**Comment by appleguy** [comment]
I think this is fixed thanks to your patch — appreciate the clear report & followup :)
