### ISSUE TITLE
ASTableViewStressTest example crashes

### ISSUE THREAD

**Issue by fox3013** [facebook/AsyncDisplayKit#612]
Hi,

I'm not quite sure why this happens but it turns out the ASTableViewStressTest crashes at once after launching.  It seems that the "layer" object in the callback function is not a CALayer. Please see the crash log and snapshot of the all exception breakpoint below.

<img width="1440" alt="screen shot 2015-08-17 at 2 14 32 pm" src="https://cloud.githubusercontent.com/assets/5937011/9299043/52b4ccfc-44ea-11e5-9a19-7afe48f82320.png">

2015-08-17 14:12:21.771 Sample[66170:9084233] -[__NSCFType sublayers]: unrecognized selector sent to instance 0x7f9eee1de7a0
2015-08-17 14:17:01.073 Sample[66170:9084233] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType sublayers]: unrecognized selector sent to instance 0x7f9eee1de7a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c67bc65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010c314bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010c6830ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010c5d913c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010c5d8cd8 _CF_forwarding_prep_0 + 120
	5   Sample                              0x000000010ba8e502 _ZL31_recursivelySetDisplaySuspendedP13ASDisplayNodeP7CALayerb + 690
	6   Sample                              0x000000010ba8e23f -[ASDisplayNode recursivelySetDisplaySuspended:] + 47
	7   Sample                              0x000000010babee80 -[ASRangeHandlerRender node:enteredRangeOfType:] + 800
	8   Sample                              0x000000010babbf95 __48-[ASRangeController updateVisibleNodeIndexPaths]_block_invoke81 + 101
	9   CoreFoundation                      0x000000010c5b1f22 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 114
	10  CoreFoundation                      0x000000010c5b167c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 300
	11  Sample                              0x000000010babbc12 -[ASRangeController updateVisibleNodeIndexPaths] + 2866
	12  Foundation                          0x000000010bec71e5 __NSFireDelayedPerform + 387
	13  CoreFoundation                      0x000000010c5e3174 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	14  CoreFoundation                      0x000000010c5e2d35 __CFRunLoopDoTimer + 1045
	15  CoreFoundation                      0x000000010c5a4d3d __CFRunLoopRun + 1901
	16  CoreFoundation                      0x000000010c5a4366 CFRunLoopRunSpecific + 470
	17  Foundation                          0x000000010becaf92 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 275
	18  Foundation                          0x000000010bf0a731 -[NSRunLoop(NSRunLoop) runUntilDate:] + 78
	19  Sample                              0x000000010ba3b4e8 -[ViewController thrashTableView] + 1896
	20  Sample                              0x000000010ba3a7d8 -[ViewController viewDidAppear:] + 88
	21  UIKit                               0x000000010d263fb1 -[UIViewController _setViewAppearState:isAnimating:] + 567
	22  UIKit                               0x000000010d264afb -[UIViewController _executeAfterAppearanceBlock] + 52
	23  UIKit                               0x000000010d1535ec _applyBlockToCFArrayCopiedToStack + 314
	24  UIKit                               0x000000010d153485 _afterCACommitHandler + 564
	25  CoreFoundation                      0x000000010c5aeca7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	26  CoreFoundation                      0x000000010c5aec00 __CFRunLoopDoObservers + 368
	27  CoreFoundation                      0x000000010c5a4a33 __CFRunLoopRun + 1123
	28  CoreFoundation                      0x000000010c5a4366 CFRunLoopRunSpecific + 470
	29  GraphicsServices                    0x00000001108e4a3e GSEventRunModal + 161
	30  UIKit                               0x000000010d12f8c0 UIApplicationMain + 1282
	31  Sample                              0x000000010ba3be8f main + 111
	32  libdyld.dylib                       0x000000010e564145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by FelixYin66** [comment]
you should found that [NSCFType sublayers]: unrecognized selector sent to instance 0x7f9eee1de7a0,that mean NSCFType don't have function

**Comment by fox3013** [comment]
@FelixYin66 
Exactly, but this is the original example code in the master branch. And that's why I was reporting here.

**Comment by nguyenhuy** [comment]
Thank you for reporting this, @FelixYin66 and @fox3013. Based on the stack trace, I guess the crash is caused by the recent change in #607. 

@appleguy must have a good idea on how it occurs and be able to fix it when time permits. Meanwhile, if you have time to investigate more and fix it, it will be very appreciated :)

**Comment by appleguy** [comment]
@FelixYin66, @fox3013 - thank you for the report, and I apologize for the month long delay.

I've fixed the stress test.  There was a 24hr period where my working range optimization had broken some behavior, but then a longer period where a simple issue with the setDataSource: method was blocking the test app from starting its intensive thrashing routine.  The actual mechanics of the test using the table, in the way that apps rely on, should have been working correctly throughout.

In addition, a couple weeks ago I did successfully re-land the working range optimization.  It's now significantly more efficient to transition things between the offscreen "preloading" area and the onscreen cells, reducing this cost to a nearly negligible level.  This was the original cause for the breakage that you ran into here, so I'm glad to have that important change completed.

Please don't hesitate to report any other issues you encounter, and email me directly at asyncdisplaykit@gmail.com if you have any questions / comments about the framework!
