### ISSUE TITLE
ASTableView, when reloadData to refresh the tableView, it causes splash screen

### ISSUE THREAD

**Issue by nannanIT** [facebook/AsyncDisplayKit#616]
I use ASTableView and ASTableViewCell, the cell contains texts, buttons, images(fetch from network, i have image cache). Everything is ok but when i reloadData to refresh the tableView(pull down to refresh
), it causes splash screen, it does't work smoothly, which is bad for the user experience. I have tried many ways to optimize it, but no one comes to be satisfied. Even though i can add some animations to cover the splash, it is not the best solution I think.
So, anyone else meet this problem and can anyone help me? thank you very much...

**Comment by nguyenhuy** [comment]
As explained in #600, reloadData is expensive and you probably know that :) For a "pull to refresh", most of the time, the data set is not completely new, i.e some objects are inserted or removed, but the rest are untouched. Sometimes there is even no change at all (happens frequently to a FB addict like me :P).

That's said, assume that you are completely sure reloadData is what you want, there are some tricks that can be used to hide the splash screen effect. I guess the easiest one is to show a snapshot view of the entire table view on top of it. After reloading, you can just remove the snapshot view, with a nice fade out animation. The code looks like this:

```objective-c
- (void)reloadData
{
  UIView *snapshot = [_tableView snapshotViewAfterScreenUpdates:NO];
  [self.view insertSubview:snapshot aboveSubview:_tableView];
  
  [_tableView beginUpdates];
  [_tableView reloadData];
  [_tableView endUpdatesAnimated:NO completion:^(BOOL completed) {
    [UIView animateWithDuration:1 animations:^{
      snapshot.alpha = 0;
    } completion:^(BOOL finished) {
      [snapshot removeFromSuperview];
    }];
  }];
}
```

And the result can be found [here](https://www.dropbox.com/s/r8g455r4493nnv5/ASDK-reloadData.mov?dl=0).

**Comment by ryanfitz** [comment]
Instead of calling `reloadData`, I would insert, remove and move rows around as needed. For example when a user pulls to refresh, simply add the new rows at the top and move the existing rows down. I have a working [solution](https://github.com/ryanfitz/AsyncDisplayKitHeaderNodeExample/blob/master/AsyncDisplayKitHeaderNodeExample/ASTableViewManager.swift). This works well in my app, which supports both pull to refresh and infinite scroll.

With that said, @nguyenhuy solution is extremely clever

**Comment by nguyenhuy** [comment]
Yeap, definitely should do minimum amount of work and avoid reloadData at all cost. Thank you, @ryanfitz :sunglasses:

**Comment by nannanIT** [comment]
@nguyenhuy @ryanfitz thank you for your reply, I think I should avoid using reloadData as much as possible. And @nguyenhuy your tricks are really helpful, gorgeous, many thanks...

**Comment by nguyenhuy** [comment]
Glad it helps, @nannanIT :)

**Comment by appleguy** [comment]
@nannanIT Hope this was helpful; thanks for asking the question.  We'd love to hear more from you if you encounter any new challenges!
