### ISSUE TITLE
ASCollection/TableView nodeForRowAtIndexPath not safe when using begin/endUpdates

### ISSUE THREAD

**Issue by eanagel** [facebook/AsyncDisplayKit#619]
I've encountered this when inserting & removing lots of rows (infinite scroll). Taking the indexPath from `-didEndDisplayingNodeForIndexPath:` and using it to attempt to get the Node with `-nodeForRowAtIndexPath:` could cause a crash because the indexPath is no longer valid when didEndDisplayingNode is called. I haven't debugged this yet, but I did want to capture it.

**Comment by eanagel** [comment]
Ok, here is another clue. I have also seen this crash when inspecting visibleIndexPaths along these lines:

    for (NSIndexPath *indexPath in self.tableView.indexPathsForVisibleRows)  {
        ASCellNode *cell = [self.tableView nodeForRowAtIndexPath:indexPath];
        ...
    }

Seems like this should never cause a problem, correct @appleguy?

**Comment by eanagel** [comment]
Ok I think I understand the problem here. Each change we ultimately push to UIViewController happens in a separate run loop (beginUpdates, insert, delete, endUpdates in separate blocks, for instance), so it is possible to do things on the main thread while we are in the middle of a begin/end updates block. When this is true, UITableView sees the original state, but we are updating _completedNodes as we go so it sees the updated state. Therefore, index paths that appear valid according to UITableView may be invalid (or wrong) when using nodeForRowAtIndexPath: This means it's not safe to get the node for an indexPath while this is happening, which I have several use cases for.

I think the ultimate solution would be to make sure all changes are committed to UITableView in a single runloop (beginUpdates/insert/delete/endUpdates in a single block) This would require some possibly significant refactoring of ASDataController to accomplish. My work around was is to keep a flag indicating I'm in begin/end updates and defer anything that might ultimately rely on _completedNodes. (Which is not a pretty picture, btw.)

@appleguy I'm a little nervous about touching this code, maybe we can chat about an approach to fix this?

**Comment by appleguy** [comment]
Thanks for debugging.  Would it be a solution to pass the node itself in the didEnd callback?

Could you describe a few of your use cases for accessing the node in didEnd, so I can improve my mental model of the scenarios that need to be supported?  I think I can recreate it from your description, but if you can copy/paste in a comment here a small diff to the Kittens app that triggers the crash, that would help.

I'm about to be off the grid for ~10 days (Burning Man!), but will actually be working on ASDK for several full days.  My primary focus will be in other areas as there are certain blockers for Pinterest, but it would be nice to provide a workaround here.

I do think a better long-term solution would be moving to some "id <ASDataModel>" - based pattern, where initialization / fetching of nodes is asynchronous anyway.  If you had to use a completion block to fetch a node, it would allow us to easily wrap up any active transaction before returning.  We may actually be able to do that without the larger cleanup / refactor, just making nodeForRowAtIndexPath:withCompletion:.  I also welcome you to add private APIs for your own use (I'll merge them upstream) until we have the more robust improvements desired here; there's a lot of reason to build out the full vision of data model-based API, and the Pinterest use cases mean this will be a high priority for me later in the year.

**Comment by ryanfitz** [comment]
I've run into similar issues as @eanagel when attempting to call `nodeForRowAtIndexPath`. This call is the number one crash report I'm getting in my app. 

My usecase for using `didEndDisplayingNodeForIndexPath` was to fade out a specific area within a CellNode when no longer on screen and then fade it back in when it displays again. I was able to fix this by overriding `clearContents` on the cell node and handling the logic there. For me this feels like a cleaner solution than using `didEndDisplayingNodeForIndexPath` and haven't run into any issues with it.

However, I do have another case where data related to the tableview (but not required for rendering the tableview) is fetched in the background. Once that data is fetched I attempt to loop over the current rows and update the rows if needed. Here the call to `nodeForRowAtIndexPath` is causing a large number of crash reports.

Id vote for adding a new api of `nodeForRowAtIndexPath:withCompletion` where if no node exists for the given indexPath it returns nil / NSError and does not throw an exception.

**Comment by eanagel** [comment]
*Note: I'm referring to `ASTableView` here but we have the same issue with `ASCollectionView`. So you can do a mental search/replace in there ;)*

The root issue is actually a serious one. Basically, it is not currently safe to call `nodeForRowAtIndexPath:` when you are using `begin/endUpdates`. This is because we currently commit changes to our internal state (`_editingNodes` in `ASDataController`) atomically when we send changes to `UITableView`. This works fine when you are doing a simple change, but when you are using begin/end updates, `UITableView` **batches** the changes while we are making them take effect **immediately** for our internal data structures. Since endUpdates is asynchronous and we update UITableView over several run loop iterations, it's possible to make calls when `_editingNodes` view of the world != `UITableView`'s view of the world.

So code like this:

    [_tableView beginUpdates];
    [_tableView deleteRowsAtIndexPaths:deletes withRowAnimation:UITableViewRowAnimationFade];
    [_tableView insertRowsAtIndexPaths:inserts withRowAnimation:UITableViewRowAnimationFade];
    [_tableView endUpdates];

Starts processing in the background. Eventually UITableView sees the following:

    Run Loop A: [tv beginUpdates];
    Run Loop B: [tv deleteRowsAtIndexPaths:deletes withRowAnimationFade];
    Run Loop B: (update _editingNodes to reflect deletes)
    Run Loop C: [tv insertRowsAtIndexPaths:inserts withRowAnimation:UITableViewRowAnimationFade];
    Run Loop C: (update _editingNodes to reflect inserts)
    Run Loop D: [tv endUpdates];

Any attempts to index into `_editingNodes` between (or during) run loop B and run loop D could either cause a crash or return invalid data. This causes issues you need to get a node using `nodeForRowAtIndexPath:` if you happen to be in UITableView's begin/update cycle. This could also potentially cause problems any time we internally get a node from `_editingNodes`, so the issue could be bigger than just this call.

Use cases for making calls to `nodeForRowAtIndexPath:` are many. Here are some I've come across:

 - Changing state of nodes as they become displayed or stop being displayed.
 - Indexing nodes to update them somehow or position them.
 - Setting the selected state of a node in response to `will/didSelectRowAtIndexPath:`
 - A common use case for me is scanning visible cells as they are scrolled to do some internal book keeping. 
 - Any of the other numerous `UITableView` methods that rely on `NSIndexPath`

Returning the node directly in `willDisplay/didEndDisplayingNode` doesn't really solve the problem because (without making additional changes) we can't reliably figure out the node for a given indexPath internally for the same reasons that `nodeForRowAtIndexPath:` fails (`_editingNodes` != `UITableView` state)

The typical use for `UITableView` is do make and commit all changes in a single run loop. IMO, that would be the ideal solution here. If all the `UITableView` updates above happen in a single run loop, we should avoid this problem. Alternatively, we could leave the basic structure in place but batch the updates to `_editingNodes` until after the `UITableView` `endUpdates` call, mirroring the way `UITableView` works.

**Comment by smyrgl** [comment]
Yeah this is a rather serious issue for myself as well.  I make atomic changes to my datastore before the ```beginUpdates()``` call and then cycle through a set of pre-computed updates within the batch block like so:

```
            if updates.insertedItems.count > 0 {
                var indexPaths = [NSIndexPath]()
                for item in updates.insertedItems {
                    let newIndexPath = newModel.indexPathForItem(item)!
                    logDebug("Inserting item  at index path \(newIndexPath)")
                    indexPaths.append(newIndexPath)
                }
                indexPaths.sortInPlace({ (lhs, rhs) -> Bool in
                    if lhs.section < rhs.section { return true }
                    if lhs.section > rhs.section { return false }
                    if lhs.row <= rhs.row { return true }
                    return false
                })
                self.insertRowsAtIndexPaths(indexPaths, withRowAnimation: rowAnimation)
            }
```
Basically I do this for all of the insert, delete, move, updates for rows and sections.

You'll notice the sorting...as I was debugging this problem I noticed a bunch of crashes like this:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSMutableArray removeObjectsAtIndexes:]: index 2 in index set beyond bounds [0 .. 0]'

Last Exception Backtrace:
0   CoreFoundation                       0x000000018386c22c __exceptionPreprocess + 132
1   libobjc.A.dylib                      0x00000001955400e4 objc_exception_throw + 56
2   CoreFoundation                       0x00000001837ccaf0 -[NSMutableArray removeObjectsAtIndexes:] + 616
3   AsyncDisplayKit                      0x0000000100a01080 __ASDeleteElementsInMultidimensionalArrayAtIndexPaths_block_invoke (ASMultidimensionalArrayUtils.mm:93)
4   AsyncDisplayKit                      0x0000000100a00d6c ASRecursivelyUpdateMultidimensionalArrayAtIndexPaths(NSMutableArray*, NSArray const*, unsigned long&, NSIndexPath*, unsigned long, void (NSMutableArray*, NSIndexSet*, unsigned long) block_pointer) (ASMultidimensionalArrayUtils.mm:37)
5   AsyncDisplayKit                      0x0000000100a00c04 ASRecursivelyUpdateMultidimensionalArrayAtIndexPaths(NSMutableArray*, NSArray const*, unsigned long&, NSIndexPath*, unsigned long, void (NSMutableArray*, NSIndexSet*, unsigned long) block_pointer) (ASMultidimensionalArrayUtils.mm:26)
6   AsyncDisplayKit                      0x0000000100a00fd8 ASDeleteElementsInMultidimensionalArrayAtIndexPaths (ASMultidimensionalArrayUtils.mm:92)
7   AsyncDisplayKit                      0x00000001009e1d58 -[ASDataController _deleteNodesAtIndexPaths:withAnimationOptions:] (ASDataController.mm:173)
```
The sorting helps but it is not a real solution because these updates are not truly batch.  In the UITableView world this sort of thing is fine because as long as you follow the rules of making sure your datastore reflects the changes before you call ```beginUpdates()``` and then make sure all the changes are done before ```endUpdates()``` is called it makes sure of the consistency.  One of the problems with AsyncDisplayKit is that it is wrapping APIs to make it as similar as possible to the UIKit class it is trying to be a stand-in for but some of them such as this one don't behave the same way and there isn't a lot of clarity to be gained in the header documentation.

By the way, I did perform a bunch of concurrency control on these updates so they aren't just firing willy nilly.  I have a dispatch group which locks out any changes from being processed until the completion block in ```endUpdatesAnimated:``` fires and I've done some very careful checking to make sure there aren't concurrent changes going on.  That was actually my first thought as I assumed that the beginUpdates/endUpdates calls functioned the same as UITableView--on the bright side I got a lot more clarity into how ASTableView works.  

I'm working on trying to graft batch update capability into ASDataController--we will see how successful that is.  But all this mucking around with indexPaths makes me think you are right on about the table view owning more of the backing data objects which could then be moved, invalidated, etc then you wouldn't have to worry about this update API to being with.  This project https://github.com/wtmoose/TLIndexPathTools does something similar (although in that case its a more decoupled layer) but I think it provides an idea of how the paradigm of feeding data to a table view could go.
