### ISSUE TITLE
Crash upon alloc/init of ASTableView after upgrade from 1.2.1 to 1.2.3

### ISSUE THREAD

**Issue by asolakhyan** [facebook/AsyncDisplayKit#624]
Hi,

Just upgraded to 1.2.3 from 1.2.1 and experiencing a crash upon executing the following line of code:
self.tableView = [[ASTableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain asyncDataFetching:YES];

Debugger points out to _OBJC_SUPPORTED_INLINE_REFCNT_WITH_DEALLOC2MAIN in ASDealloc2MainObject.

@implementation ASDealloc2MainObject

#if !__has_feature(objc_arc)
_OBJC_SUPPORTED_INLINE_REFCNT_WITH_DEALLOC2MAIN(_retainCount);
#endif

@end

BTW, version 1.2.2 also crashes in the similar pattern. 
Have you encountered anything like this?

Thanks.

**Comment by appleguy** [comment]
@asolakhyan ak, my apologies for missing this task.  I think it pushed below the fold to the second page just before I saw it...

I have not gotten any other reports of this issue, even with 1.2.3.  However, could you please try again with 1.9.1?  If you experience any issues - whether this one or another - please reopen this issue or file a new one.  I definitely want to know about it and ensure any blockers are resolved for you (although I understand if the delay means you're no longer looking at ASDK!)
