### ISSUE TITLE
ASStackLayoutSpec is not found in latest 1.2.3 of CocoaPods

### ISSUE THREAD

**Issue by xiaomaogong** [facebook/AsyncDisplayKit#625]
I want to use the ASStackLayoutSpec in my project , but i found that the ASStackLayoutSpec is not in the latest version of CocoaPods , any idea how to solve this?

**Comment by SRandazzo** [comment]
In your podfile, you can point to a branch or commit by doing the following:

Points to master:
`pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git', :branch => 'master'`

Points to latest commit on master:
`pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git', :commit => '38eae3ab77ffc7f80c820f609c657ff1c3b9aa66'`

**Comment by xiaomaogong** [comment]
Thanks , its working now.
