### ISSUE TITLE
Selecting an item after adding ASCollectionView to view crashes.

### ISSUE THREAD

**Issue by connor** [facebook/AsyncDisplayKit#638]
I've noticed an inconsistency in behavior with ASCollectionView and UICollectionView and wasn't sure about the best way to get around the crash, so am posting here.

I've put together an isolated use case app example [here](https://github.com/connor/ASDKCollectionViewErrorExample). Toggle the `USE_ASDK` bool in the `AppDelegate`.

I've also noticed this behavior when just *accessing* the cell at a given index path after adding the view to the parent view. That crash was due to `ASDataController`'s `_completedNodes` being empty (or, rather, not containing a node at the specified path).

So, my question is – what is the recommended way to get around this?

**Comment by levi** [comment]
Hey Connor, I left the same note as a pull request on your repo, but I'll post it here too for reference:
> When a collection view is instantiated and its `layoutSubviews` method is called, it will automatically call `reloadData` to initialize the data within the collection. Problem is ASDK loads collection view cells off the main thread, delegating the bulk of the work to the `ASDataController` to notify the collection view to reload specific sections and items when the nodes in `_editingNodes` transition into the `_completedNodes` collection. Thus you won't have any data until the data controller is completely done with its initial rendering of the cells in your data source. The most straight forward way to work around this is the `reloadDataWithCompletion:` method which will give you a callback to do any work once the reloadData is done in the data controller.
It's not a completely obvious solution at first glance and @eanagel has brought up a good note in #587 about possible ways to make handling callbacks fired from the data controller clearer. Feel free to leave some feedback on that thread if you have ideas on how to improve the experience of dealing with async rendering.

**Comment by connor** [comment]
👍 thank you!
