### ISSUE TITLE
Update Podspec to support 0.38.2 and later

### ISSUE THREAD

**Issue by Mazyod** [facebook/AsyncDisplayKit#659]
Something to do with do with setting `user_target_xcconfig`.

Related Facebook project: https://github.com/facebook/pop/issues/264
Related Cocoapods discussion: https://github.com/CocoaPods/CocoaPods/issues/3813#issuecomment-127218342

**Comment by appleguy** [comment]
@Mazyod thanks for the links!  I'd love to support this properly, but haven't had time to look into it.

Do you know how to make the change?  After I'm done with the presentation at NSSpain tomorrow, I'll try to look into this, but it may take a few weeks (sad I know - considering it would probably only take half an hour or less...)

**Comment by Mazyod** [comment]
Thanks for fast reply @appleguy! Unfortunately, my cocoapods-fu is severely lacking, and I've moved the library to a submodule for now .. So, not a pressing issue, but more and more users are moving to swift, and it will probably be an important change.

Will report back if I figure it out myself.

Have fun at NS:es: !

**Comment by Mazyod** [comment]
@appleguy a developer at pop resolved the issue, you can see his change for reference. Yup, would probably take less than 2 mins:

https://github.com/facebook/pop/commit/b1b1ca2c5da35548357fe1b3aa901d7e5094532f

**Comment by appleguy** [comment]
We will get this landed in the next few days.  Thanks again for the reminder!

**Comment by Mazyod** [comment]
Thanks for taking care of this! Probably need a pod spec update to make it count ;)
