### ISSUE TITLE
How to add a ASCollectionView header

### ISSUE THREAD

**Issue by duxinfeng** [facebook/AsyncDisplayKit#669]
Hi,I added a header in the following manner，but crash

error info:
*** Assertion failure in -[ASCollectionView setAsyncDataSource:]
AsyncDisplayKit/AsyncDisplayKit/ASCollectionView.mm:224

```
 _collectionView = [[ASCollectionView alloc] initWithFrame:CGRectZero collectionViewLayout:layout asyncDataFetching:YES];
    _collectionView.asyncDataSource = self;
    _collectionView.asyncDelegate = self;
    [_collectionView registerClass:[ToolsHeader class] forSupplementaryViewOfKind:UICollectionElementKindSectionHeader withReuseIdentifier:@"header"];
```
```
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
{
    ToolsHeader *header = [_collectionView dequeueReusableSupplementaryViewOfKind:kind withReuseIdentifier:@"header" forIndexPath:indexPath];
    header.title.text = @"ABCD";
    return header;
}
```
Thank you for your answer！

**Comment by appleguy** [comment]
Supplementary views aren't supported by ASCollectionView right now; there was an assertion added for this a while back that I believe is still in 1.2.3 and Master (if you have 1.2.2, it may not be there).

@levi has been working on implementing support for supplementary views, but also has a full-time job.  Levi, are there any updates in terms of the strategy and path from here to having support?

**Comment by levi** [comment]
@appleguy, @duxinfeng: I have a pretty clear picture as where to head with adding supplementary view support for flow layouts. I'm currently sketching out additions to ASDataController specific to ASCollectionView. I'm planning to have a roughed-out data controller implementation in a couple of days and will put up a WIP pull request to begin community feedback and iteration.

**Comment by appleguy** [comment]
Really great, thanks @levi for the update!  Can't wait to see, don't hesitate to share something super early even if the initial diff doesn't actually work with a real UI.  I'm very interested to start considering what would be necessary to go from that to a solution that supports non-flow layouts too (may not be feasible though, as we've discussed some...)
