### ISSUE TITLE
Disable or customize sliding row animation

### ISSUE THREAD

**Issue by rainypixels** [facebook/AsyncDisplayKit#67]
![rowanimation](https://cloud.githubusercontent.com/assets/780433/4727446/8a7b36ae-596c-11e4-8250-a1ede4aa86f7.gif)

I was under the impression that #30 fixed this issue, but I'm still seeing the row animation cells sliding down when they're first loaded. I played around with swapping out the animations in [-[ASTableView rangeController:didSizeNodesWithIndexPaths:]](https://github.com/facebook/AsyncDisplayKit/blob/c61b1c294ceb857eddc4dfd6dab000b9e8d4ac9a/AsyncDisplayKit/ASTableView.m#L346-364), but it doesn't seem to have an effect for row insertion (section insertion animation type changes are reflected, however).

**Comment by jerrylu0522** [comment]
Me too

**Comment by zboralski** [comment]
Still isn't fixed
