### ISSUE TITLE
insertRowsAtIndexPaths and deleteRowsAtIndexPaths after makes next row invisible

### ISSUE THREAD

**Issue by vitalybaev** [facebook/AsyncDisplayKit#686]
I use github master branch of ASDK

See image to understand this behaviour. We have some info, that can be hidden or not.

![asyncdisplaykit_issue](https://cloud.githubusercontent.com/assets/724423/10096005/c7c77fe4-6376-11e5-8330-8e9feb6e384a.png)

1) Original state, let's insert rows
2) Rows inserted, (transparent blue area) - OK
3) Delete this rows - next cell node is white (transparent red area)
4) Insert rows again - still OK
5) Delete it again - next row seems to be OK

and it can be repeated.

Row, that makes white is just ASCellNode with ASTextNode with ASInsetLayoutSpec

Using ```tableView.insertRowsAtIndexPaths(indexPathUpdates, withRowAnimation: UITableViewRowAnimation.Automatic)``` and ```tableView.deleteRowsAtIndexPaths(indexPathUpdates, withRowAnimation: UITableViewRowAnimation.Automatic)``` to show and hide rows

Thanks

**Comment by appleguy** [comment]
@vitalybaev thank you for reporting this.  I'm super late in replying to this as it was from that crazy time around NSSpain!

Can you please test the latest master to confirm this is fixed?  I'd do that if there were a test project — sure, this is not that hard to build a project for, but look how many tasks there are in ASDK!

After fully understanding the conditions that lead to the other bug, I'm pretty confident this is fixed.  If it's not, it will be a high priority for me as I'm working in ASRangeController.

In the event that it is easy for you to publish the part of the project that reproduces this, please do as it would make for a nice test case for my ongoing development work.  We should probably create a directory (or just keep adding to examples/) for this kind of test project, similar to ASTableViewStressTest, which is primarily intended for ASDK developers.

**Comment by appleguy** [comment]
Thankfully I still believe this is fixed.  Appreciate the report, once again, and let me know if you see this or another problem.
