### ISSUE TITLE
ASCollectionView change ItemSize

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#690]
I try to change flowLayout itemSize but nothing change!
```layout.itemSize = CGSizeMake(375, 250);```

Im using default ASCollectionView sample.

also ```- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath```
doesn't called!

I can't change specific item size dynamically!
any idea?

**Comment by appleguy** [comment]
@hashemp206 — thanks for asking.  With ASDK, item sizes are typically controlled by the ASDisplayNodes themselves (or ASCellNodes in this case).  There is a .preferredFrameSize property that you can set on certain elements, like ASImageNode, where they may not have a very clear size to calculate for themselves.

I hadn't considered this feature of the collection view layout, and will think about a way to detect and better document it (like printing a log to the console reminding people that layout size is driven by the elements).  There may also be a way to hook this up if the UICollectionView is notified of any changes to itemSize.

Note that one of the advantages of ASTableView and ASCollectionView is that they eliminate one of the two data source methods — cellForRow/Item: and sizeForRow/Item: are collapsed into just nodeForRow/Item:.

Let me know if you have any difficulty here!  Usually creating an ASCellNode subclass is best, and from there you can override either:

- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize;
- (ASLayout *)calculateLayoutThatFits:(ASSizeRange)constrainedSize;

Documentation here:
http://asyncdisplaykit.org/appledoc/Categories/ASDisplayNode+Subclassing.html#//api/name/layoutSpecThatFits:
http://asyncdisplaykit.org/appledoc/Categories/ASDisplayNode+Subclassing.html#//api/name/calculateLayoutThatFits:

**Comment by hashemp206** [comment]
thanks for quick answer.
but above methods aren't in ```AsynDisplayKit``` even documentation was not found!

I also want to change cell height based on selection. I have implemented this scenario with UICollectionView but I encounter cell flickering!
http://stackoverflow.com/questions/32812203/uicollectionview-expanding-cell/ 

so Im trying to implement this with ```AsyncDisplayKit``` but no success!

**Comment by nguyenhuy** [comment]
Which version are you using? Above methods are part of the new layout system in v2.0 Beta and is available on master. If you are using the latest CocoaPods release (v1.2.3), you won't find them. You can easily switch to v2.0 Beta and it is quite stable.

Once you let your cell nodes to calculate their own size (and layout), dynamic sizing is actually very easy. We have a working example in Kittens example. The implementation can be found [here](https://github.com/facebook/AsyncDisplayKit/blob/master/examples/Kittens/Sample/ViewController.m#L118) and [here](https://github.com/facebook/AsyncDisplayKit/blob/master/examples/Kittens/Sample/KittenNode.mm). Let us know if there is anything else we can help!

**Comment by hashemp206** [comment]
how can I install beta version with cocoa pods?
```pod 'AsyncDisplayKit', '~> 2.0'```
but doesn't work!

**Comment by SRandazzo** [comment]
You can point directly to the latest commit, or to master/head
`pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git', :commit => 'c824644'`
`pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git', :branch => 'master'

**Comment by hashemp206** [comment]
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by SRandazzo** [comment]
@hashemp206 
may need to try https (we probbaly have our keys setup differently)

Can you try 
`pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :branch => 'master'

**Comment by appleguy** [comment]
Sorry for the inconvenience — I should have mentioned that you would need to be on master.  My aim is to release a new version soon, but I wanted to finish a few changes first (such as my PR that is currently up).  Just let us know if you have any difficulty getting master installed.

**Comment by hashemp206** [comment]
thanks again all you friends for quick responses!
you have devoted a lot of time to develop this brilliant library! but that has lack of good tutorial! I have read ```RayWenderlich``` tutorial. this lib is not a wrapper around UIKit. we need to think asynchronously please provide more dedicated tutorial! 
it seems you have introduced a new layout engine in lack of AutoLayout! I don't know how to use ASLayout! please provide some tutorial! or some useful links to let me understand most of its mumbo jumbos!

I have done a sample following kitten sample app:
```
- (CGSize)calculateSizeThatFits:(CGSize)constrainedSize
{
  return _selected ? CGSizeMake(375, 300) : CGSizeMake(375, 200);
}

- (void)toggleSize
{
  _selected = !_selected;
  [self setNeedsLayout];
}
```
```
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
  if (self.previousContentOffset.y == 0) {
    self.previousContentOffset = _collectionView.contentOffset;
  }
  [_collectionView performBatchAnimated:YES updates:^()
   {
     HACell*node = (HACell *)[_collectionView nodeForItemAtIndexPath:indexPath];
     [UIView animateWithDuration:0.3 animations:^()
      {
         [node toggleSize];
      }];

//change content offset
 if (!node.selected) {
       [_collectionView setContentOffset:self.previousContentOffset animated:YES];
       self.previousContentOffset = CGPointZero;
     }
     else
     {
       [_collectionView setContentOffset:CGPointMake(0, CGRectGetMinY(node.frame)) animated:YES];
     }
     
   }completion:nil];
}

```

I could change cell size but see the gif below. you see top and bottom cell flicker! why?

 thats because of I change contentOffset. I need to reposition cell to its initial place. 


![collectionview expand](https://cloud.githubusercontent.com/assets/3206748/10145215/a75be88e-662e-11e5-99b3-9581bc91a58c.gif)

**Comment by appleguy** [comment]
@hashemp206 thanks for giving it a close look, and for the compliments!  Indeed, asyncdisplaykit.org has documentation only for the 1.x features, as 2.0 is still in Beta.

I recently gave a talk that describes some of the new features in enough depth that it should help you start using them.  Sadly, I was rushed in preparing for the talk, and made for a pretty bad speaker.  I suggest you skip in by at least 10 minutes after I started speaking more understandably :-P

https://vimeo.com/140409084

**Comment by appleguy** [comment]
Thanks for including the gif BTW.  However, it's hard to tell what is going on because there is no content in the cells.  Can you add some subviews to the cells, to help show what is happening?

Also, as with normal UICollectionView / UITableView, the right way to animate their size changing is to call -invalidateCalculatedLayout on the cell (which you can get from nodeForItemAtIndexPath:), and then call reloadRowAtIndexPath: / reloadItemAtIndexPath:.  Check the Kittens app sample (examples/Kittens), but I'm pretty sure it does this (right @nguyenhuy ?).

By doing that, you should be able to have the new values in -calculateSizeThatFits: and it should be taken into account even without calling -setNeedsLayout in your toggle method.  Basically calling toggle could set an instance variable like _height, that is used by the -calculateSizeThatFits method, and also call -invalidateCalculatedLayout.  Then your code that is calling -toggleSize (from the UICollectionView didSelect method) could just call the reloadItem: method.

UICollectionView / UITableView have never been very good about handling resizing items / rows, and sadly AsyncDisplayKit doesn't make it any easier, but it should work (and with very few lines of code) if approached the right way.  The only difference from UIKit is that the size is normally specified from within the node and you need to call -invalidateCalculatedLayout.  The other aspects, including the need to call -reloadItem/Row and to return the new size when UIKit asks for it as a result of calling that method, are the same.

**Comment by appleguy** [comment]
Now that I have a slightly better understanding of what you're trying to do, learning about ASLayout / ASLayoutSpec is not the most critical thing for you.  The problem you show should be possible to address with the standard 1.x API, which uses -calculateSizeThatFits: and -layout.  The newer APIs are easier and more flexible for more sophisticated cases found in normal apps rather just a test app — they combine the two methods into a single one, where you can choose EITHER -calculateLayoutThatFits: OR -layoutSpecThatFits.  As described in the talk video, any one of the three approaches is valid, although with the master / 2.0 version of ASDK we are starting to standardize on the latter two methods.

**Comment by nguyenhuy** [comment]
@appleguy Well the Kitten app uses -setNeedsLayout and an empty transaction to achieve size changing actually. Your way works as well, but it's a bit more complicated because to ASDataController, reload means destroy the old node and load a new one. So you need to keep track of the selected index path(s) and, in -nodeForRowAtIndexPath, toggle the new node's state. [Here](https://github.com/nguyenhuy/AsyncDisplayKit/commit/2a81ea6fe805f52ac6dbc0cc8b047b3bd4b79516) is a working implementation of this approach. I think this approach is a bit faster if you want to change many cells at the same time, since ASDataController reloads them asynchronously.

@hashemp206 I can't really see which view flickers in your GIF (I haven't seen any smooth GIF animation actually).
- If you use -setNeedsLayout, I think you have everything (like the node's view/layer, its old and new size, etc) to make a very smooth size transition with Core Animation. For example, [here](https://github.com/nguyenhuy/AsyncDisplayKit/commit/4aa921ecec9e668df9b4b501b1c6b589f2486c72), I use fade in and fade out animations to slowly hide the old size and show the new one. [The result looks quite good](https://www.dropbox.com/s/0elnpyuq1663evo/ASDK-AnimatedKittenNode.mov?dl=0). You can of course animate however you want using the same principle.
- If you use Scott's approach, you can rely on UITableViewCellAnimation, like [this](https://github.com/nguyenhuy/AsyncDisplayKit/commit/2a81ea6fe805f52ac6dbc0cc8b047b3bd4b79516#diff-aa81a054912280c7666bbf98546f208eR128).

**Comment by hashemp206** [comment]
Thanks again for your details answer. It'll be my honor to see you friends one day.
*1 UTableView ```beginUpdate``` , ```endUpdate``` works differently from UICollectionView ```perfomBatchUpdates:completion:``` this bug I see in UICollectionView doesn't occur in UITableView
*2 I can not override default UICollectionView ```perfomBatchUpdates:completion:``` animation! it is always 0.3 sec and linear!  so my custom animation won't work seamlessly.

my goal of this animation is perform a seamless cell expand and collapse animation to user can see more of item details.
![goal](https://github.com/szk-atmosphere/SAParallaxViewControllerSwift/blob/master/SampleImage/open_sample.gif)

gif update to see the result flicker:
![collectionview expand](https://cloud.githubusercontent.com/assets/3206748/10169275/3b6bcee6-66dd-11e5-8181-ff79bfb5e64b.gif)

**Comment by nguyenhuy** [comment]
Can you post a sample project?

**Comment by hashemp206** [comment]
a sample:
https://www.dropbox.com/s/qfnfvm871wvuer9/ASCollectionView.zip?dl=0

**Comment by nguyenhuy** [comment]
OK, the trick is to animate size changing of the cell's view together with UICollectionView's repositioning of other cells, hence the magic 300ms duration. The code looks like this:

```
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
  HACell*node = (HACell *)[_collectionView nodeForItemAtIndexPath:indexPath];
  [UIView animateWithDuration:0.3 animations:^(){
    [node toggleSize];
    [_collectionView performBatchUpdates:^{} completion:nil];
  }];
}
```

Note that I didn't include your content-offset-related code. I think it neither causes the flickering mentioned above, nor scrolls the collection view at all. To scroll the collection view, you can use `-scrollToItemAtIndexPath:atScrollPosition:animated` and maybe `-scrollRectToVisible:animated:`. They both have a built-in animation.

**Comment by nguyenhuy** [comment]
@hashemp206 It was fun playing around with your requirements. I managed to mimic the expand and collapse animations. I don't use `-setContentOffset:animated` because it doesn't take effect when selecting first visible cells (contentOffset <= screen height). Here is the code:

```objective-c
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
  HACell*node = (HACell *)[_collectionView nodeForItemAtIndexPath:indexPath];

  [UIView animateWithDuration:0.3 animations:^(){
    [node toggleSize];
    [_collectionView performBatchUpdates:^(){} completion:nil];
  }];
  
  if (node.selected) {
    // Calculate _deltaY. It is an instance variable of type CGFloat
    UICollectionViewLayoutAttributes *attributes = [_collectionView layoutAttributesForItemAtIndexPath:indexPath];
    _deltaY = _collectionView.bounds.origin.y - attributes.bounds.origin.y;

    [_collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:UICollectionViewScrollPositionTop animated:YES];

    _collectionView.scrollEnabled = NO;
  } else {
    _collectionView.scrollEnabled = YES;

    CGRect visibleRect = _collectionView.bounds;
    visibleRect.origin.y = _deltaY;
    _deltaY = 0;

    // [_collectionView scrollRectToVisible:visibleRect animated:YES] (somehow???) causes the previous cell to flicker (previous cell is laid out and rendered *after* the animation).
    // This is a workaround
    [UIView animateWithDuration:0.3 animations:^{
      [_collectionView scrollRectToVisible:visibleRect animated:NO];
    }];
  }
}
```

**Comment by hashemp206** [comment]
So here is what I have right now:
now I can animate my cells with custom animation and duration. a lot more functionality than UICollection view default animation.

![collectionview expand 2 13 54 pm 2](https://cloud.githubusercontent.com/assets/3206748/10281383/f9b52260-6b80-11e5-9ca5-35633ae729e5.gif)

I have used a custom animation transition. in case anyone wondered how I did that:
```
//
//  CellExpandAnimator.m
//  FoodIran
//
//  Created by Hashem on 9/29/15.
//  Copyright (c) 2015 Hashem Aboonajmi. All rights reserved.
//

#import "CellExpandAnimator.h"
#import "RestMenuPageView.h"
#import "MenuItemCell.h"

@interface CellExpandAnimator ()
@property (strong, nonatomic) NSArray           *visibleCells;
@property (strong, nonatomic) MenuItemCell      *selectedCell;
@property (strong, nonatomic) NSMutableArray    *cellInitialPositions;
@property (strong, nonatomic) UIView            *containerView;
@property (strong, nonatomic) UIView            *fromView;
@property (strong, nonatomic) UIView            *toView;

@property (nonatomic, assign) CGPoint selectedCellInitialPosition;

@end
@implementation CellExpandAnimator
- (MenuItemCell *)selectedCell
{
    if (!_selectedCell) {
        [self.visibleCells enumerateObjectsUsingBlock:^(MenuItemCell *cell, NSUInteger idx, BOOL *stop) {
            if (cell.selected) {
                _selectedCell = cell;
                *stop = YES;
            }
        }];
    }
    
    return _selectedCell;
}

- (instancetype)initWithVisibleCells:(NSArray *)visibleCells
{
    if (self = [super init]) {
        _visibleCells = visibleCells;
        _cellInitialPositions = [NSMutableArray new];
    }
    return self;
}
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning>)transitionContext;
{
    return fMenuItemAnimationDuration;
}
- (void)animateTransition:(id <UIViewControllerContextTransitioning>)transitionContext
{
    _fromView = [transitionContext viewControllerForKey:UITransitionContextFromViewControllerKey].view;
    _toView = [transitionContext viewControllerForKey:UITransitionContextToViewControllerKey].view;
    _containerView = transitionContext.containerView;
    self.selectedCell.alpha = 0;
    
    if (self.isPresenting) {
        //_toView backgroundColor should be selectedCell backgroundColor
        _toView.backgroundColor = self.selectedCell.backgroundColor;
       // we add toView where selectedCell is. so imagin when selced cell is below flexible header, toView should be below RestMenuPageView flexibleHeader.
        [_fromView insertSubview:_toView belowSubview:[(RestMenuPageView *)_fromView restFlexibleHeader]];
        //initial frame
        CGRect initialToViewFrame = [[self.selectedCell.view superview] convertRect:self.selectedCell.frame toView:_containerView];
        _toView.frame = initialToViewFrame;
        [UIView animateWithDuration:[self transitionDuration:transitionContext] delay:0 usingSpringWithDamping:0.7 initialSpringVelocity:0.7 options:UIViewAnimationOptionCurveEaseOut animations:^()
         {
             [self ExpandSelectedCell];
         }completion:^(BOOL finished) {
             [_containerView addSubview:_toView];
             [self completeTransition:YES transitionContext:transitionContext];
         }];
    }
    else
    {
        // we add toView where selectedCell is. so imagin when selced cell is below flexible header, toView should be below RestMenuPageView flexibleHeader.
        [_toView insertSubview:_fromView belowSubview:[(RestMenuPageView *)_toView restFlexibleHeader]];
        
        [UIView animateWithDuration:[self transitionDuration:transitionContext] delay:0 usingSpringWithDamping:0.7 initialSpringVelocity:0.7 options:UIViewAnimationOptionCurveEaseOut animations:^()
         {
             [self collapseSelectedCell];
         }completion:^(BOOL finished) {
             [self completeTransition:YES transitionContext:transitionContext];
             //clear cell initial positions
             [self.cellInitialPositions removeAllObjects];
         }];
    }
    
    CGPoint selectedCellFinalPosition = self.selectedCell.frame.origin;
    CGFloat totalDistance = (selectedCellFinalPosition.y - self.selectedCellInitialPosition.y);
    
    [[NSNotificationCenter defaultCenter] postNotificationName:fAnimatingMenuItemStarted object:@[@(totalDistance),@(self.presenting)]];
}

- (void)completeTransition:(BOOL)complete transitionContext:(id <UIViewControllerContextTransitioning>)transitionContext
{
    [transitionContext completeTransition:complete];
    if (complete) {
        
        [[NSNotificationCenter defaultCenter] postNotificationName:fAnimatingMenuItemFinished object:nil];
        
        self.selectedCell.shouldRasterizeDescendants = YES;
        self.selectedCell.alpha = 1;
    }
}

- (void)ExpandSelectedCell
{
    __block CGFloat yPositionSelectedCell = [[self.selectedCell.view superview] convertPoint:self.selectedCell.frame.origin toView:_containerView].y;
    self.selectedCellInitialPosition = self.selectedCell.frame.origin;
    
    CGFloat containerHeight = _containerView.height;
    CGFloat distanceToTop = yPositionSelectedCell;
    CGFloat distanceToBottom = containerHeight - (yPositionSelectedCell+self.selectedCell.view.height);
    for (MenuItemCell*cell in self.visibleCells) {
        
        [self.cellInitialPositions addObject:[NSValue valueWithCGPoint:cell.frame.origin]];
        CGPoint cellOrigin = [cell.view.superview convertPoint:cell.frame.origin toView:_containerView];
        
        //if cell is selected
        if (cell.selected) {
            cell.view.y = cell.view.y - distanceToTop;
            cell.view.height = containerHeight;
            [cell setNeedsLayout];
            //final toView frame
            self.toView.frame = [cell.view.superview convertRect:cell.frame toView:self.containerView];
        }
        //if cell is above of selectedCell
        else if (cellOrigin.y<yPositionSelectedCell)
        {
            cell.view.y -= distanceToTop;
        }
        //cell is below of selectedCell
        else
        {
            cell.view.y += distanceToBottom;
        }
    }
}

- (void)collapseSelectedCell
{
    self.selectedCellInitialPosition = self.selectedCell.frame.origin;
    //resetting expanded cell to its initial frame
    [self.visibleCells enumerateObjectsUsingBlock:^(MenuItemCell *cell, NSUInteger idx, BOOL *stop) {
        //assignin any none selected cell size to selected cell
        //so selected cell height reset to its initial height
        if (cell != self.selectedCell) {
            self.selectedCell.frame = cell.frame;
            [self.selectedCell toggleSize];
            *stop = YES;
        }
    }];
    
    [self.visibleCells enumerateObjectsUsingBlock:^(MenuItemCell *cell, NSUInteger idx, BOOL *stop) {
        CGPoint initialPosition = [self.cellInitialPositions[idx] CGPointValue];
        cell.view.x = initialPosition.x;
        cell.view.y = initialPosition.y;
        
    }];
    
    //from view final frame should be selectedCell final frame
    self.fromView.frame = [self.selectedCell.view.superview convertRect:self.selectedCell.frame toView:self.containerView];
    
   
}

@end
```

**Comment by nguyenhuy** [comment]
It looks great! Thanks for sharing, @hashemp206. And you are right, View Controller Transitioning is a better solution in this case. Cheers!
