### ISSUE TITLE
ASCollectionView was crashed when ASCollectionView reloaded many times

### ISSUE THREAD

**Issue by tuantavan** [facebook/AsyncDisplayKit#696]
Hi all,
    I'm using version 1.2.3. I have message chat screen (used ASCollectionView). 
The app is often crashed. I think the cause is the ASCollectionView reloaded many times. 
I thinks when ASCollectionView is destroying/generating, ASDatacontroller is trying to get an object at index which is beyond bounds. 

I checked on Crashlytic & saw the  detail report as below.
I searched around to find solution, but I hadn't had solution until now.

Could you suggest me a solution, please?

Thanks so much for your helping!
Regards,

Here is error detail on Crashlytic : 
--------------------------------------------------------------------------------------
Fatal Exception: NSRangeException
*** -[__NSArrayM objectAtIndex:]: index 109 beyond bounds [0 .. 108]
 raw   0	CoreFoundation	
__exceptionPreprocess   2	CoreFoundation	
-[__NSArrayM removeObjectAtIndex:]
3   SpotHot	
ASDataController.mm line 595
-[ASDataController nodeAtIndexPath:]
4   SpotHot	
ASCollectionView.mm line 367
-[ASCollectionView collectionView:cellForItemAtIndexPath:]
5   UIKit	
-[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:]
6   UIKit	
-[UICollectionView _updateVisibleCellsNow:]
7   UIKit	
-[UICollectionView layoutSubviews]
8   UIKit	
-[UIView(CALayerDelegate) layoutSublayersOfLayer:]
9   QuartzCore	
-[CALayer layoutSublayers]
10   QuartzCore	
CA::Layer::layout_if_needed(CA::Transaction*)
11   QuartzCore	
CA::Layer::layout_and_display_if_needed(CA::Transaction*)
12   QuartzCore	
CA::Context::commit_transaction(CA::Transaction*)
13   QuartzCore	
CA::Transaction::commit()
14   QuartzCore	
CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
15   IOMobileFramebuffer	
IOMobileFramebufferVsyncNotifyFunc   16   IOKit	
IODispatchCalloutFromCFMessage   17	CoreFoundation	
__CFMachPortPerform   24	UIKit	
UIApplicationMain   25 
SpotHot	
main.m line 15   main   26 libdyld.dylib	
start

**Comment by nguyenhuy** [comment]
It looks like the collection view tried to access nodes while ASDataController was reloading them. There is a recent change on master that fixes this issue. Could you switch to master and try it out?

**Comment by tuantavan** [comment]
@nguyenhuy : thanks aHuy a lot. I'm trying this solution.

**Comment by appleguy** [comment]
@tuantavan do let us know your results!  I think the master branch will resolve your issues, but if it does not, it is very important & useful to us to hear from you about it.  If the issue is resolved, go ahead and close out this task — I'm tracking with high priority getting a new stable release of ASDK cut so everyone has the improvements, but for the time being am recommending people use master.

If the crash IS still occurring with master, I'd actually love to adopt your testing strategy into our main line unit tests to keep running this stress test even after we fix the issue.  Note examples/ASTableViewStressTest is a good place to add this kind of stuff if you're interested in helping us improve the rigor of our testing, hugely valuable to the project right now!

**Comment by tuantavan** [comment]
Hi @appleguy , @nguyenhuy ,
   Sorry for late response to you. I applied the source code of master  branch. It's more stable than version 1.2.3. However, on iOS 9 (iOS9.0.1 & 9.0.2) it is still crashed. on iOS8 it is more stable than iOS9. 
Please take a look on crash log : https://docs.google.com/document/d/1KsJbhIK8KttaB2rqsmaaB65aRH6pRAQGP4Gh3QDnXx8/edit?usp=sharing

+ Video of reproduce it : https://youtu.be/PqH72FaydS4

In this video, it was crashed at 0:23" (iPhone 6, iOS 9.0.2). At this time, when I clicked on BACK button, I just deleted all Items of ASCollectionView (deleteItemsAtIndexPaths).

Thanks so much for your helping!

**Comment by nguyenhuy** [comment]
@tuantavan Thanks for the video and stack trace. I have a couple of questions: 
- The most important question is, why do you delete all items upon navigating back? I suppose the nodes are automatically cleaned up afterward, no?
- If you have a very good reason to do so, are you sure the index paths are all correct? One way to check this is to switch to -deleteSections and see if the crash still occurs. If it does then it's legitimately a bug in ASDK.
- How do you perform the batch? Do you call any other edit commands in the same batch?
- Can you share a code snippet, or better yet, a sample project that reproduces the crash?

**Comment by tuantavan** [comment]
hi a @nguyenhuy,
    Thanks for your GREAT questions, I re-checked my source code. In the old version, when I used [collection reloadData], there had some issues. That was the reason why I deleted items by indexPaths.

Now, As your suggestion, I use [collection reloadData] instead of deleting items by indexPaths. I works well now ( It hasn't had crash until now - I'm still testing now). 

hi @appleguy, as @nguyenhuy 's suggestions (questions), I change my code & it works well now (master branch).

@nguyenhuy , @appleguy  : Thanks a lot again!

I close this ticket now.

**Comment by nguyenhuy** [comment]
@tuantavan: I'm glad that your app is more stable now. I'm still very curious about your use case and the root cause of your crash (i.e., were the indexPaths in fact invalid? And if so, how did that happen in the first place?). It would be great if you can share more information because we may come up with some improvements in the framework itself.

**Comment by tuantavan** [comment]
Hi a @nguyenhuy ,
     I'd like to show my snippet old source code that it crashed many times. (sorry, I don't have permission to share full source code).

Here is flow that app was crashed.

1. User goes to chat screen to chat with his/her friend XXX (sure, he saw history messages).
  + MessageViewController.m --> viewDidAppear --> bindData --> setMessages (MessageDataSource.m ) : 

2. User goes back
  + MessageViewController.m --> goBack --> deleteAllMessages(MessageDataSource.m )
 
3.  User goes to chat with another friend YYY.
 + MessageViewController.m --> viewDidAppear --> bindData --> setMessages (MessageDataSource.m ) : 

==> If user goes with fast speed ( as my video demo), It seems that while the datasource is generating/deleting items, another request to generate/delete items come up..... So it is out of bounds of Array (messages).

Hope the snippet source code is clear for you.
Thanks so much for your helping!

Source code : 
============================================================
1. MessageViewController.m

- (void)bindData {
    NSLog(@"MessageVC bindData _reloadMessages : %d", _reloadMessages);
    if (_reloadMessages) {
        _reloadMessages = NO;
        NSString *partnerInfo = [NSString stringWithFormat:@"%@, %ld",
                                                       self.match.partner.fullname,
                                                       (long) [self.match.partner.dob ageFromDOB]];
        [self setNavigationTitle:partnerInfo];

        NSMutableArray *messages = [NSMutableArray arrayWithArray:self.match.messages];
        __weak SPHMessagesViewController *weakSelf = self;
        _collectionView.alpha = 0;
        __weak ASCollectionView *weakCollectionView = _collectionView;

        [_dataSource setMessages:messages to:_collectionView completion:^{

            [weakSelf scrollToLatestMessage:NO];
            [UIView animateWithDuration:0.5 animations:^{
                 weakCollectionView.alpha = 1;
            }];
        }];
    }
}

- (void)goBack {
    [self resetInputText];

    _typingParams.value = @(NO);
    _typingParams.match = self.match;
    [self.matchService updateStatus:_typingParams
                      completeBlock:^(SPHMatch *match, NSError *error) {
    }];

    [self lockDataSource];
    [_dataSource deleteAllMessages:_collectionView completion:^{
        [self unlockDataSource];
        _match = nil;
        [self.navigationController popViewControllerAnimated:YES];
    }];
}

===============================================================
2. MessageDataSource.m

- (void)deleteAllMessages:(__weak ASCollectionView *)collectionView
               completion:(void (^)())completeBlock  {
    DDLogDebug(@"deleteAllMessages begining... : ");
    SPHAsyncOperation *operation = [[SPHAsyncOperation alloc] initWithBlock:
                                    ^(AsyncOperationCompletionBlock asyncCompletionBlock) {

            NSInteger numberOfMessages = [collectionView numberOfItemsInSection:0];
            NSMutableArray *deleteIndexPaths = [NSMutableArray array];
            for (int i = 0; i < numberOfMessages; i++) {
                [deleteIndexPaths addObject:[NSIndexPath indexPathForItem:i inSection:0]];
            }

            [collectionView performBatchUpdates:^{
                if (deleteIndexPaths.count > 0) {
                    [collectionView deleteItemsAtIndexPaths:deleteIndexPaths];
                    [_listOfMessages removeAllObjects];
                }
            } completion:^(BOOL finished) {
                DDLogDebug(@"deleteAllMessages completion : ");
                if (completeBlock) completeBlock();

                if (asyncCompletionBlock) asyncCompletionBlock();
            }];
    }];

    [_serialOperationQueue addOperation:operation];
}

- (void)setMessages:(NSArray *)messages to:(__weak ASCollectionView *)collectionView
         completion:(void (^)())completeBlock {
    SPHAsyncOperation *operation = [[SPHAsyncOperation alloc]
                              initWithBlock:^(AsyncOperationCompletionBlock asyncCompletionBlock) {
        NSInteger start = [collectionView numberOfSections] > 0 ?
                                  [collectionView numberOfItemsInSection:0] : 0;
        NSInteger numberOfMessages = messages.count;
        NSMutableArray *deleteIndexPaths = [NSMutableArray array];
        if (start > numberOfMessages) {
            for (NSInteger i = messages.count; i < start; i++) {
                [deleteIndexPaths addObject:[NSIndexPath indexPathForItem:i inSection:0]];
            }
        }
        NSMutableArray *reloadIndexPaths = [NSMutableArray array];
        NSInteger reloadMessages = start > numberOfMessages ? numberOfMessages : start;
        if (reloadMessages < _listOfMessages.count) {
            for (int i = 0; i < reloadMessages; i++) {
                SPHMessage *oldMessage = _listOfMessages[i];
                if (i < messages.count) {
                    SPHMessage *newMessage = messages[i];
                    if ([oldMessage.id isEqualToString:newMessage.id]) continue;
                }
                [reloadIndexPaths addObject:[NSIndexPath indexPathForItem:i inSection:0]];
            }
        }
        [_listOfMessages setArray:messages];
        NSMutableArray *insertIndexPaths = [NSMutableArray array];
        for (NSInteger i = start; i < numberOfMessages; i++) {
            [insertIndexPaths addObject:[NSIndexPath indexPathForItem:i inSection:0]];
        }
        [collectionView performBatchAnimated:NO updates:^{
            if (deleteIndexPaths.count > 0) {
                [collectionView deleteItemsAtIndexPaths:deleteIndexPaths];
            }
            if (reloadIndexPaths.count > 0) {
                [collectionView reloadItemsAtIndexPaths:reloadIndexPaths];
            }
            if (insertIndexPaths.count > 0) {
                [collectionView insertItemsAtIndexPaths:insertIndexPaths];
            }
        } completion:^(BOOL finished) {
            if (completeBlock) completeBlock();
            if (asyncCompletionBlock) asyncCompletionBlock();
        }];
    }];
    [_serialOperationQueue addOperation:operation];
}

**Comment by nguyenhuy** [comment]
Thanks for the code snippet, @tuantavan. Although it's hard to debug this kind of problem without a running project, I believe it's not very hard to run into data inconsistency with your old code and the old version of ASDataController. It looks like you're in fact trying to reuse the messages view controller, its collection view and therefore the underlying ASDataController. Coupling that with a (also reused) data source which manages its own (async???) operation queue, and you have a design that is  pretty tricky to get right. I hope you have very good reason(s) for these decisions. Anyway, feel free to report new issues, we are happy to help :)
