### ISSUE TITLE
Intermittent Crash in ASDataController

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#707]
I've got an ASCollectionView in a cell of an ASTableView, and sometimes when that collection view loads its initial data I get an assertion failure in ASDataController. The data controller attempts to access `ASDisplayNode.calculatedSize` on the default-priority dispatch queue so it fails the node thread affinity assertion.

I _believe_ this is the chain of events:
- UICollectionView calls reloadData to load initial data
- That calls ASDataController.reloadDataWithAnimationOptions:completion: on the main thread
- Which dispatches `_layoutNodes:atIndexPaths:withAnimationOptions:` on the editing transaction queue
- Which listens for all the constrained sizes on the default-priority global queue and then updates the frame there. 

Shouldn't that last `dispatch_group_async` probably target the main queue? Can we ever safely measure and `setFrame:` all these cell nodes in the background?

<img width="2473" alt="screen shot 2015-10-05 at 11 05 28 am" src="https://cloud.githubusercontent.com/assets/2466893/10289063/5e10d5fe-6b51-11e5-9b0c-5b83cbc545f1.png">
<img width="2473" alt="screen shot 2015-10-05 at 11 05 55 am" src="https://cloud.githubusercontent.com/assets/2466893/10289073/66ea06a0-6b51-11e5-8763-2379fff4ba76.png">
<img width="2473" alt="screen shot 2015-10-05 at 11 05 50 am" src="https://cloud.githubusercontent.com/assets/2466893/10289075/68a34b32-6b51-11e5-9c3e-906152b7c4d9.png">

**Comment by Adlai-Holler** [comment]
Note: Simply changing that dispatch_group_async callback results in a deadlock, because in `reloadDataWithAnimationOptions:`, the data controller waits on the main thread for the editing queue to finish all operations which will never happen if the dispatch_group is waiting for the main thread to become available.

**Comment by appleguy** [comment]
cc @levi, @eanagel, @nguyenhuy

**Comment by Adlai-Holler** [comment]
The method `nodeForRowAtindexPath:` method specifies that nodes should not be reused. Does that mean I should never return the same node twice from this method, or that the node I return should not have been previously associated with a different row? I'm currently reusing nodes in the former sense, my data source has an array of nodes and I update them and notify ASTableView when I insert/delete them.

This crash could be caused because data controller presumes that it's safe to measure the node in the background because it's never been measured before.

**Comment by appleguy** [comment]
@Adlai-Holler yes, you should definitely not reuse nodes in the latter sense (between rows).  I think a trivial change is needed (which someone volunteered to do in a discussion recently, but I think was not completed) to support returning a previously-used node if you deleted it and then want to insert it again.  Namely, the layout code should check isNodeLoaded and perform measurement on the main thread for any of those nodes, dispatching the others to the background (still only notifying the UIKit class when contiguous batches of them are done).  Should be very straightforward if you're interested in making that change.

**Comment by Adlai-Holler** [comment]
@appleguy Good to know. I'd be glad to make the change but I've hit a deadlock. Since the main queue waits for the editing transaction queue to drain before each edit command, it's unsafe to dispatch synchronously onto main from the editing transaction queue, which is where _layoutNodes is required to be done.

**Comment by appleguy** [comment]
@Adlai-Holler of course.  I think you'll need to iterate over the nodes before they are running in the background to first catch any that have been loaded previously, to do their measurement there.  Definitely agree there are subtleties involved, may even need some kind of property on cellNode like .needsMeasurement?  Keep in mind that @levi  has a big open PR in this area and we may want to wait for that to land, although your change would probably be the easier one to rebase onto his.
