### ISSUE TITLE
it throws an error on ipad/iphone simulator

### ISSUE THREAD

**Issue by vikas4goyal** [facebook/AsyncDisplayKit#720]
it throws an error on ipad/iphone simulator ? 

Assertion failure in -[ASDisplayNode _displayBlockWithAsynchronous:isCancelledBlock:rasterizing:], /Users/maheshgupta/testDevelopment/moebeldeapp/Pods/AsyncDisplayKit/AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm:178
2015-10-05 18:20:37.664 Presenting view controllers on detached view controllers is discouraged <ProductViewController: 0x7a63dfa0>.
2015-10-05 18:20:42.459 moebel.de[5164:854926] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid contents scale'
*** First throw call stack:
(
	0   CoreFoundation                      0x01b0fa94 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x015d0e02 objc_exception_throw + 50
	2   CoreFoundation                      0x01b0f92a +[NSException raise:format:arguments:] + 138
	3   Foundation                          0x012503e6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
	4   moebel.de                           0x0012f39d -[ASDisplayNode(AsyncDisplay) _displayBlockWithAsynchronous:isCancelledBlock:rasterizing:] + 1869
	5   moebel.de                           0x00130e47 -[ASDisplayNode(AsyncDisplay) displayAsyncLayer:asynchronously:] + 1655
	6   moebel.de                           0x001ae9cf __27-[_ASDisplayLayer display:]_block_invoke + 95
	7   moebel.de                           0x001af000 -[_ASDisplayLayer _performBlockWithAsyncDelegate:] + 160
	8   moebel.de                           0x001ae91c -[_ASDisplayLayer display:] + 140
	9   moebel.de                           0x001ae86f -[_ASDisplayLayer display] + 527
	10  QuartzCore                          0x0263a078 _ZN2CA5Layer17display_if_neededEPNS_11TransactionE + 326
	11  QuartzCore                          0x0263a0fe _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 38
	12  QuartzCore                          0x0262cc2b _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 317
	13  QuartzCore                          0x02660c23 _ZN2CA11Transaction6commitEv + 589
	14  QuartzCore                          0x026614d6 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
	15  CoreFoundation                      0x01a2977e CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION + 30
	16  CoreFoundation                      0x01a296de __CFRunLoopDoObservers + 398
	17  CoreFoundation                      0x01a1f05c __CFRunLoopRun + 1340
	18  CoreFoundation                      0x01a1e866 CFRunLoopRunSpecific + 470
	19  CoreFoundation                      0x01a1e67b CFRunLoopRunInMode + 123
	20  GraphicsServices                    0x04bb1664 GSEventRunModal + 192
	21  GraphicsServices                    0x04bb14a1 GSEventRun + 104
	22  UIKit                               0x02830cc1 UIApplicationMain + 160
	23  moebel.de                           0x000d60ea main + 138
	24  libdyld.dylib                       0x04316a21 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by vikas4goyal** [comment]
this error randomly occurred and after error when i run it again. it runs perfectly

**Comment by richardoti** [comment]
Could you provide some code samples which cause the crash? I think, the initialization flow and `viewDidLoad` of `presenting` and `presented` ViewControllers may help.

**Comment by appleguy** [comment]
@vikas4goyal I echo @richardoti — anyone who provides a runnable sample project here will get help very promptly, usually within hours, to debug almost any problem with their code!

I looked at this assertion for you.  It is:
    ASDisplayNodeAssert(self.contentsScaleForDisplay != 0.0, @"Invalid contents scale");

Does your code have any reference to contentsScaleForDisplay, if you do a full text search of the project?  I have never seen this issue reported, so it initially seems like it would be an issue where you set this property to 0.  Unlike some other areas where you can set 0 and expect it to automatically use the screen scale, that's not the case for this property.

**Comment by vikas4goyal** [comment]
This is parent Class:
//
//  AsyncCollectionCell.m

#import "AsyncCollectionCell.h"
#import "NSOperationQueueCache.h"

@interface AsyncCollectionCell ()
@property(strong,nonatomic)ASDisplayNode* containerNode;
@property(strong,nonatomic)CALayer* placeholderlayer;
@property(strong,nonatomic)NSOperation* nodeConstructionOperation;
@end

@implementation AsyncCollectionCell

- (instancetype)init
{
    self = [super init];
    if (self) {
        [self setup];
    }
    return self;
}
- (instancetype)initWithCoder:(NSCoder *)coder
{
    self = [super initWithCoder:coder];
    if (self) {
        [self setup];
    }
    return self;
}

-(void)setup{
    self.placeholderlayer =[CALayer layer];
   self. placeholderlayer.backgroundColor=[UIColor colorWithWhite:0.95 alpha:1.0].CGColor;
   self. placeholderlayer.contentsScale=[UIScreen mainScreen].scale;
    [self.contentView.layer addSublayer:self.placeholderlayer];
}

-(void)prepareForReuse{
    [super prepareForReuse];
    [self.containerNode recursivelySetDisplaySuspended:YES];
    [self.containerNode.layer removeFromSuperlayer];
    self.containerNode=nil;
    if (self.nodeConstructionOperation) {
        [self.nodeConstructionOperation cancel];
        self.nodeConstructionOperation=nil;
    }
}
-(void)layoutSubviews{
    [super layoutSubviews];
    [CATransaction begin];
    [CATransaction setValue:(id)kCFBooleanTrue forKey:kCATransactionDisableActions];
    [self.placeholderlayer setFrame:self.bounds];
    [CATransaction commit];
    
    if (self.containerNode) {
        self.containerNode.frame = self.bounds;
    }
    [self layoutSubNodes:NO];
}
-(void)setData:(id)dataObject{
    if(self.nodeConstructionOperation){
        [self.nodeConstructionOperation cancel];
        self.nodeConstructionOperation=nil;
    }
    NSBlockOperation* newNodeConstructionOpration =[self createNodeConstructionOperation:dataObject];
    self.nodeConstructionOperation =newNodeConstructionOpration;
    NSOperationQueue* commonQueue =[NSOperationQueueCache cacheOperationQueue:NSStringFromClass(self.class)];
    [commonQueue addOperation:newNodeConstructionOpration];
}

#pragma mark funtion for implement in subclass
-(void)configureNode:(id)data containerNode:(ASDisplayNode*)containerNode{
    //should be implement in subclasses
}
-(void)layoutSubNodes:(BOOL)calculate{
    //should be implement in subclasses
}
#pragma mark private
-(NSBlockOperation*)createNodeConstructionOperation:(id)data{
    NSBlockOperation* blockOperation=[NSBlockOperation blockOperationWithBlock:^{
        if ([blockOperation isCancelled]) {
            return ;
        }
        ASDisplayNode* containerNode=[[ASDisplayNode alloc] init];
        containerNode.layerBacked=YES;
        containerNode.shouldRasterizeDescendants=YES;
        containerNode.contentsScale=[UIScreen mainScreen].scale;
        containerNode.backgroundColor=[UIColor colorWithWhite:0.95 alpha:1.0];
        containerNode.frame=self.bounds;
        [self configureNode:data containerNode:containerNode];
        [self layoutSubNodes:YES];
        dispatch_async(dispatch_get_main_queue(), ^{
            if ([blockOperation isCancelled]) {
                return ;
            }
            if (containerNode.displaySuspended) {
                return;
            }
            [self.contentView.layer addSublayer:containerNode.layer];
            [containerNode setNeedsDisplay];
            self.containerNode=containerNode;
        });
    }];
    return blockOperation;
}

@end







//This is Child Class:
//
//  AsyncProductCell.m
//

#import "AsyncProductCell.h"
#import "Skinning.h"
#import "NSAttributedString+Extra.h"
#import "ProductCellModel.h"
#import "NSString+ParserAndFormatter.h"
#import "Color.h"
#import "Font.h"
#import "Image.h"

#define TEXT_MARGIN 5.0
#define CENTER_MARGIN 25.0


@interface AsyncProductCell ()
@property(strong, nonatomic) CALayer *placeholderLayer;
@property(strong, nonatomic) CALayer *contentLayer;
@property(weak,nonatomic)id<SDWebImageOperation> imageDownloadOperation;

@end

@implementation AsyncProductCell

- (void)prepareForReuse {
    [self stopImageDownload];
    [super prepareForReuse];
    self.productOrgPriceNode = nil;
    self.productNameNode = nil;
    self.productFinalPriceNode = nil;
    self.imageNode = nil;
    self.productFlagNode=nil;
}
- (void)configureNode:(id)dataObject containerNode:(ASDisplayNode *)containerNode {
    if (![dataObject isKindOfClass:[ProductCellModel class]]) {
        return;
    }
    ProductCellModel *product = (ProductCellModel *)dataObject;
    self.product = product;
    
    // container node
    containerNode.borderWidth = 1;
    containerNode.borderColor = [Skinning color].BorderColor.CGColor;
    
    // productImage
    self.imageNode = [[ASImageNode alloc] init];
    self.imageNode.image = [[Skinning image] placeholderProductListing];
    self.imageNode.contentMode = UIViewContentModeScaleAspectFill;
    self.imageNode.layerBacked = YES;
    [self startImageDownload:[product imageUrl]];
    [containerNode addSubnode:self.imageNode];
    
    // textBackgroundNode
    self.textBackgroundNode = [[ASDisplayNode alloc] init];
    self.textBackgroundNode.layerBacked = YES;
    self.textBackgroundNode.backgroundColor = [UIColor whiteColor];
    [containerNode addSubnode:self.textBackgroundNode];
    
    // productNameNode
    self.productNameNode = [[ASTextNode alloc] init];
    self.productNameNode.layerBacked = YES;
    self.productNameNode.maximumLineCount = 2;
    self.productNameNode.truncationMode = NSLineBreakByTruncatingTail;
    self.productNameNode.backgroundColor = [UIColor whiteColor];
    NSString *string = [[product title] as_removeTrailingErroneousCharacters];
    self.productNameNode.attributedString =
    [NSAttributedString hyphenatedAttributedString:string
                                              font:[Skinning font].Subhead
                                         textColor:[Skinning color].BlackColor];
    //    self.productNameNode.attributedString =[NSAttributedString hyphenatedAttributedString:@""]
    [self.textBackgroundNode addSubnode:self.productNameNode];
    
    // final price label
    self.productFinalPriceNode = [[ASTextNode alloc] init];
    self.productFinalPriceNode.layerBacked = YES;
    self.productFinalPriceNode.backgroundColor = [UIColor whiteColor];
    self.productFinalPriceNode.attributedString =
    [NSAttributedString attributedString:[product finalPrice]
                                    font:[Skinning font].SubheadMedium
                               textColor:[product finalPriceColor]];
    [self.textBackgroundNode addSubnode:self.productFinalPriceNode];
    
    // org price label
    if ([product showOriginalPrice]) {
        self.productOrgPriceNode = [[ASTextNode alloc] init];
        self.productOrgPriceNode.layerBacked = YES;
        self.productOrgPriceNode.backgroundColor = [UIColor whiteColor];
        self.productOrgPriceNode.maximumLineCount = 1;
        
        self.productOrgPriceNode.attributedString =
        [NSAttributedString strikeThroughAttributedString:[product orignalPrice]
                                                     font:[Skinning font].Caption1
                                                textColor:[Skinning color].LightGray];
        [self.textBackgroundNode addSubnode:self.productOrgPriceNode];
    }
    if ([product showInfoFlag]) {
        self.productFlagNode =[[ASTextNode alloc] init];
        self.productFlagNode.layerBacked=YES;
        self.productFlagNode.backgroundColor=[Skinning color].RedColor;
        self.productFlagNode.attributedString=[NSAttributedString centeredAttributedString:[product infoFlagText] font:[Skinning font].SubheadMedium textColor:[UIColor whiteColor]];
        
        [containerNode addSubnode:self.productFlagNode];
        
    }
}

- (void)layoutSubNodes:(BOOL)calculate {
    if (!(self.imageNode && self.productNameNode)) {
        return;
    }
    CGSize boundSize = self.bounds.size;
    // image node
    self.imageNode.frame = CGRectMake(0, 0, self.bounds.size.width, boundSize.width);
    
    // textBackgroundNode
    //self.textBackgroundNode.backgroundColor = [UIColor clearColor];
    self.textBackgroundNode.frame = CGRectMake(0, self.imageNode.frame.size.height, boundSize.width,
                                               boundSize.height - self.imageNode.frame.size.height);
    
    // product name label
    CGSize productNameSize =
    calculate ? [self.productNameNode measure:boundSize] : self.productNameNode.calculatedSize;
    self.productNameNode.frame =
    CGRectMake(TEXT_MARGIN, 10, boundSize.width - (TEXT_MARGIN * 2), productNameSize.height);
    
    // product finalprice
    CGSize finalpriceSize = calculate ? [self.productFinalPriceNode measure:boundSize]
    : [self.productFinalPriceNode calculatedSize];
    
    self.productFinalPriceNode.frame =
    CGRectMake((boundSize.width - finalpriceSize.width - TEXT_MARGIN)/2 + CENTER_MARGIN,
               self.textBackgroundNode.frame.size.height - finalpriceSize.height - CENTER_MARGIN+10,
               finalpriceSize.width, finalpriceSize.height);
    
    // product org price
    if (self.productOrgPriceNode) {
        CGSize orgPriceNodeSize = calculate ? [self.productOrgPriceNode measure:boundSize]
        : [self.productOrgPriceNode calculatedSize];
        
        self.productOrgPriceNode.frame =
        CGRectMake((self.productFinalPriceNode.frame.origin.x - orgPriceNodeSize.width - TEXT_MARGIN),
                   self.productFinalPriceNode.frame.origin.y + 2 , orgPriceNodeSize.width,
                   orgPriceNodeSize.height);
    }
    if (self.productFlagNode) {
//        CGSize flagSize=calculate?[self.productFlagNode measure:boundSize]:[self.productFlagNode calculatedSize];
        self.productFlagNode.frame=CGRectMake(0, 20, 50, 20);
    }
}

- (void)startImageDownload:(NSString *)url {
    NSURL *imageURL = [NSURL URLWithString:url];
    SDWebImageManager* manager =[SDWebImageManager sharedManager];
    SDWebImageOptions options =SDWebImageLowPriority;
    self.imageDownloadOperation=[manager downloadImageWithURL:imageURL options:options progress:^(NSInteger receivedSize, NSInteger expectedSize) {
        
    } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
        if (!error&&finished) {
            [self.imageNode setImage:image];
            self.product.image=image;
            self.imageDownloadOperation =nil;
        }
    }];
}
- (void)stopImageDownload {
    if (self.imageDownloadOperation) {
        [self.imageDownloadOperation cancel];
        self.imageDownloadOperation =nil;
    }
}

@end
we are using AsyncDisplayKit to create Collection Cell. AsyncCollectionCell is parent cell and AsyncProductCell is child which extend AsyncCollectionCell. 

we  have done full text search in our project for "contentsScaleForDisplay" and didn't find any reference in  our code base.
  
    [cell setData:<data model object>];
this is initial call to bind data with CollectionCell

**Comment by appleguy** [comment]
@vikas4goyal ok, thanks, this was useful.  It looks like this is related to rasterization.

Can you confirm that if you remove any calls to setShouldRasterizeDescendants:YES, that your code runs and works as expected?

Could you try leaving on rasterization, but removing the various calls you have to setContentsScale:?

It would be particularly useful to have a running sample project.  From the code above I can't immediately tell if your cell class is an ASCellNode or something else.  If it's an ASCellNode, note that -layoutSubviews will never be called (same for all nodes — manual layout should use the -layout method)

**Comment by appleguy** [comment]
@vikas4goyal any other updates on this?  Was the issue resolved or did you get a chance to test the things I asked?  Sorry for the back-and-forth, but in cases where sample code can't be provided, it's important to have a few rounds for debugging.

**Comment by vikas4goyal** [comment]
@appleguy  hi, sorry for late relpy.

**Comment by vikas4goyal** [comment]
@appleguy  hi sorry for late reply. i have created an sample project. but its not giving any error. i have added/used same classes which i am using in my original project
sample project is commited on github:
link:  https://github.com/vikas4goyal/sample-project

please check if you found any mistake.
basically only AsyncCollectionCell and AsyncProductCell are using AsyncDisplayKit.

**Comment by appleguy** [comment]
@vikas4goyal cool, thanks for the sample project!  I'm glad to say that it works perfectly for me.  I am running the project against the latest AsyncDisplayKit 1.9, which if you point cocoa pods to the github repository or specify 1.9, it should be linked up properly after calling "pod install" (if Xcode is closed).  Note your Podfile appears to have the "curly quotes" in it, which can mess up Cocoapods (it looks like the latest version detects this and is able to work around it).

Please definitely reopen this task or file another issue if you run into any problems, whether it is a completely new one, or unable to get past this one (if so, please let me know if you can run examples/Kittens after doing pod install in that directory)  Cheers!

**Comment by appleguy** [comment]
@vikas4goyal - this is using iOS 9.1 and an iPhone 6s simulator.
<img width="379" alt="screen shot 2015-11-07 at 9 15 55 pm" src="https://cloud.githubusercontent.com/assets/565251/11018921/c7547a54-8594-11e5-957f-859b607bbc15.png">
