### ISSUE TITLE
Latest master build - didSelectRowAtIndexPath: (TableView & CollectionView) not forwarded to ASTableView

### ISSUE THREAD

**Issue by aphylotus** [facebook/AsyncDisplayKit#721]
Hi,

  updated to the latest master, and noticed that the didSelectRowAtIndexPath is no longer forwarded to the ASTableView or CollectionView, which are created as such:

  tableView = [[ASTableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain asyncDataFetching:YES];
  tableView.asyncDataSource = self;
  tableView.asyncDelegate = self;

  cells are created, so the cellNodeForIndexPath: call is executed. Rolling back to a master a few days ago makes the function being called again, by identical sourcecode

  Any Idea where it may come from, the delegate points to the _ASTableViewProxy

  Thanks,

  Tom

**Comment by appleguy** [comment]
@aphylotus thanks for reporting this issue.  It is most likely a regression caused by my recent change...

**Comment by appleguy** [comment]
Working on a fix in https://github.com/facebook/AsyncDisplayKit/pull/724

**Comment by appleguy** [comment]
@aphylotus I went ahead and reverted my change entirely, so this should be resolved.  Please do file another task and ping me if you notice this again.  Thanks a bunch for the quick report.

**Comment by robmontesinos** [comment]
didSelectRowAtIndexPath stopped working.

I updated via cocoa pods to 1.9 via:
pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git', :branch => 'master'

console reads: Using AsyncDisplayKit (1.9)

Is there something I am doing wrong with cocoa pods?

```ObjectiveC
- (ASTableView *)tableView {
    if (!_tableView) {
        self.tableView = [[ASTableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain asyncDataFetching:YES];
        self.tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
        self.tableView.asyncDataSource = self;
        self.tableView.asyncDelegate = self;
    }
    return _tableView;
}

**Comment by robmontesinos** [comment]
It looks like didSelectRowAtIndexPath is working on an ASCellNode that does not have any links in the attributedString

**Comment by robmontesinos** [comment]
OK, it seems that an ASTextNode with a link is not allowing touches to pass through to the parent ASCellNode. Tapping certain parts of the cell triggers didSelectRowAtIndexPath but tapping on the text node while avoiding the link does nothing.

**Comment by robmontesinos** [comment]
OK, mystery solved - setting the ASTextNode with links 'passthroughNonlinkTouches' to YES did the trick
```ObjectiveC
/**
 @abstract if YES will not intercept touches for non-link areas of the text. Default is NO.
 */
@property (nonatomic, assign) BOOL passthroughNonlinkTouches;
