### ISSUE TITLE
ASTableView reloadData effect presentViewController can not work

### ISSUE THREAD

**Issue by JiesonWu** [facebook/AsyncDisplayKit#728]
platform:iOS 9.0.2 device:iPhone 6

```
- (void) viewWillAppear: (BOOL) animated
{
    [super viewWillAppear:animated];
     [self.tableNode reloadData];
}

- (void)showNewVC:(id)sender
   NewViewController *vc1 = [[NewViewController alloc] init];
    UINavigationController *nav1 = [[UINavigationController alloc] initWithRootViewController:vc1];
    [self presentViewController:nav1 animated:YES completion:NULL];
}

```
1. First time, the  code  [self presentViewController:nav1 animated:YES completion:NULL]; can be work;

2. when the  NewViewController (vc1) dismisssed,  the  [self.tableNode reloadData]; call again, call the 
function showNewVC: the  code [self presentViewController:nav1 animated:YES completion:NULL]; can not work. the current view controller function - (void) viewDidDisappear: (BOOL) animated called. the current view controller ' view is not disappear, and the NewViewController is not be presented.

**Comment by appleguy** [comment]
@JiesonWu Thank you for reporting this — it is important to understand what is going on here.  However, I don't yet have a guess for how it would be possible for ASDK to affect the code you're referring to, which is almost entirely related to unmodified UIViewController calls.  ASDK does not have any tight integrations with view controller presentation, for example.

I got the general impression of your description, but it doesn't give enough detail to figure out the problem.  Would you be able to upload a test project (either to GitHub, or even a .zip file to Dropbox)?  If so, myself or others in the community will work quickly to help you debug it.

**Comment by appleguy** [comment]
@JiesonWu Are you able to provide any other information here?  If you were able to resolve the issue and it doesn't look like an ASDK bug, please close out the issue.  Thanks for trying out the framework and I hope to be able to help with any other questions you have!

**Comment by appleguy** [comment]
@JiesonWu would love to help you get this working.  Please open a new task if you can provide more information.
