### ISSUE TITLE
Why we have not a Gitter

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#729]
Hi guys! Where can i find chat community about facebook products for take a help from guru? And ask stupid questions ^_^

**Comment by richardoti** [comment]
Here is Paper Engineering Community on Facebook:
https://www.facebook.com/groups/551597518288687/

**Comment by bimawa** [comment]
:( only facebook group?

**Comment by richardoti** [comment]
There is a Google group as well, but I don't know, where is it.

**Comment by bimawa** [comment]
ok thx!

**Comment by appleguy** [comment]
@bimawa I haven't heard of Gitter before — is it a developer forum of some kind?  Always interested in looking at ways we can help the community support for a framework like this one.

Feel free to post an issue here any time.  There is indeed a Google Group called AsyncDisplayKit too.

**Comment by bimawa** [comment]
@appleguy Yes its similar IRC or Slack but with related with github project like our ADK. Its chat more than forum. But it ,rly, ugly and better nothing with IRC functionality :)

**Comment by appleguy** [comment]
That sounds really great!  Would Slack be as useful?  Since I use Slack for work, that would be easier for me to keep up with.

I definitely feel like some of these issues would be quicker to solve with realtime chat.

**Comment by bimawa** [comment]
on ReactFlux we have >7000 user in community and Slack can't support all us :) And guys from ReactJS created this page for choice similar variants: github.com/reactiflux/volunteers/issues/25. but for our ADK slack will be better with IRC proxy. i love IRC more ^_^
