### ISSUE TITLE
ASCellNode selected/highlighted background color

### ISSUE THREAD

**Issue by vitalybaev** [facebook/AsyncDisplayKit#744]
In my project I need to set custom selected/highlighted background color for ASCellNode, because standart UITableViewCell's gray color isn't good.

The easiest way to do this IMHO is adding selected and highlighted properties to ASCellNode and update them in _ASTableViewCell for it's ASCellNode.

So now we can overwrite setters in ASCellNode or use didSet in Swift.

Is it acceptable for ASDK? I also can create PR for that if it needed.

Thank you!

**Comment by vitalybaev** [comment]
Pull Request done #745
Sorry, if my code isn't acceptable for AsyncDisplayKit

**Comment by appleguy** [comment]
@vitalybaev thanks a lot for implementing this!
