### ISSUE TITLE
TableView jump and blinked

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#748]
Guys help pls. I created TableView with dynamic infinity loader. And use this code:
```objective-c
 [[[self.viewModel willBeginBatchFetch] deliverOnMainThread] subscribeNext:^(NSArray *indexPaths) {
        [tableView insertRowsAtIndexPaths:indexPaths withRowAnimation:UITableViewRowAnimationFade];
        [context completeBatchFetching:YES];
    }];
```
but when i sroll my table and it receive a new data all reloaded or similar. This [video](https://mega.nz/#!0MBWmQBD!VWI3Y1-hcPpv15mAF7OdwhC6rPyhGPgWBzeIZvqDxcs) what i get. I do all like in Kitten example. But mb something wrong in cells? MB Cells very hard?

**Comment by appleguy** [comment]
@bimawa a few questions:

- What framework are you using?  What is deliverOnMainThread and subscribeNext:?  This seems like an unusual pattern, maybe reactive cocoa or something?  It may not be a compatible / advisable way to drive ASDK, but I simply don't know as there is very little information here.

- Have you tried using the built-in batch fetching calls of ASTableView?  If so, what features did they lack that made them not fit your needs?

**Comment by bimawa** [comment]
@appleguy i spen all day for understand whats i do srong. And its not related with tableVIew or BatchFetching or (yes) reactive cocoa. It's cool. I create new Table View and use myself cells and catch same behavior. 
>Have you tried using the built-in batch fetching calls of ASTableView?
Yes i do. 
>If so, what features did they lack that made them not fit your needs?
hmm i go research that..  
ok Scott thx for advice.

**Comment by bimawa** [comment]
I close this issue i think i do something wrong.

**Comment by bimawa** [comment]
@appleguy  Can't understand what's wrong. the problem is that when loading new data in `- (void)tableView:(ASTableView *)tableView willBeginBatchFetchWithContext:(ASBatchContext *)context
` and inserted to `tableView`

**Comment by bimawa** [comment]
@appleguy  Can't understand what's wrong. the problem is that when loading new data in 
```
- (void)tableView:(ASTableView *)tableView willBeginBatchFetchWithContext:(ASBatchContext *)context
``` 
and inserted to `tableView` indexPaths it reloaded scroll. similar behavior observed and kitten example. And I noticed that this happens when you insert elements into a table while scrolling continues. Now i try insert indexPaths when scrolling is stop. And report what happened.

**Comment by bimawa** [comment]
Yes better, but not perfect.

**Comment by lunajing** [comment]
@bimawa I do not understand, how you solve this?

**Comment by bimawa** [comment]
@lunajing i'm did't see that anymore on v. 1.9.90
