### ISSUE TITLE
Periodic test failure: check for number of relayouts is sometimes 0 instead of 1.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#758]
This is a better problem to have than multiple relayouts...but it's unusual and a bit concerning that the failure seems to happen only on some runs.

@nguyenhuy here is one of the most recent failures: https://travis-ci.org/facebook/AsyncDisplayKit/jobs/86258557

Failures:
  0) -[ASTableViewTests testRelayoutAllRowsWithNonZeroSizeInitially] (AsyncDisplayKitTests.xctest)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━���━━━
/Users/travis/build/facebook/AsyncDisplayKit/AsyncDisplayKitTests/ASTableViewTests.m:283: ((node.numberOfLayoutsOnMainThread) equal to (1)) failed: ("0") is not equal to ("1"):
280       for (int row = 0; row < NumberOfRowsPerSection; row++) {
281         NSIndexPath *indexPath = [NSIndexPath indexPathForRow:row inSection:section];
282         ASTestTextCellNode *node = (ASTestTextCellNode *)[tableView nodeForRowAtIndexPath:indexPath];
283         XCTAssertEqual(node.numberOfLayoutsOnMainThread, 1);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
284         XCTAssertEqual(node.constrainedSizeForCalculatedLayout.max.width, newSize.width);
285       }
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  1) -[ASTableViewTests testRelayoutAllRowsWithZeroSizeInitially] (AsyncDisplayKitTests.xctest)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
/Users/travis/build/facebook/AsyncDisplayKit/AsyncDisplayKitTests/ASTableViewTests.m:283: ((node.numberOfLayoutsOnMainThread) equal to (1)) failed: ("0") is not equal to ("1"):
280       for (int row = 0; row < NumberOfRowsPerSection; row++) {
281         NSIndexPath *indexPath = [NSIndexPath indexPathForRow:row inSection:section];
282         ASTestTextCellNode *node = (ASTestTextCellNode *)[tableView nodeForRowAtIndexPath:indexPath];
283         XCTAssertEqual(node.numberOfLayoutsOnMainThread, 1);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
284         XCTAssertEqual(node.constrainedSizeForCalculatedLayout.max.width, newSize.width);
285       }
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
** TEST FAILED: 210 passed, 2 failed, 0 errored, 212 total ** (57595 ms)

**Comment by nguyenhuy** [comment]
Yeah, those unstable tests bother me immensely. This issue tops my todo list now :)

**Comment by appleguy** [comment]
Thanks so much, @nguyenhuy !
