### ISSUE TITLE
[ASRangeController] Support preloading across wrapping of content in circular collection

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#769]
So here is we have:
I have implemented a cyclic ASCollectionView which you can have an infinite cyclic scrolling based on a tutorial:[Building a Infinitely-Scrolling Gallery With a UICollectionView](http://adoptioncurve.net/archives/2013/07/building-a-circular-gallery-with-a-uicollectionview)

We have a horizontal ASCollectionView which its cells contain an inner ASCollectionView
so when I scroll leading Cells gets layout in advance. but from the first cell when I scroll backward because last cell has not yet layout, I see a flicker because at the moment cell is lay outing itself.
![scroll](https://cloud.githubusercontent.com/assets/3206748/10710931/a6ad51f8-7a78-11e5-86d7-198e2477a75c.gif)

I have also tried to set ASRangeController tuning parameters. but nothing changed!
```objective-c
[_collectionView setTuningParameters:(ASRangeTuningParameters){
        .leadingBufferScreenfuls = 7.0f, // seven screenfuls in the direction of scroll
        .trailingBufferScreenfuls = 1.0f // one-half screenful in the other direction
    } forRangeType:ASLayoutRangeTypePreload];
```

here is the sample app:
https://dl.dropboxusercontent.com/u/45698608/HorizontalCollectionView.zip

**Comment by appleguy** [comment]
@hashemp206 Thanks, this is a very creative use of ASCollectionView — I may want to use a similar technique to implement ASPagerNode.  It should definitely work given that it does with UICollectionView, but no one had encountered this yet.

I may be able to look at this tomorrow, but realistically I will probably not get too deep.  @levi & @nguyenhuy, you have both already donated a lot of time to the community in these components, so I don't want you to feel like you need to do everything in these classes — but if you have any immediate thoughts on what about ASRangeController is incompatible with this, we should be able to fix it at Pinterest.

**Comment by hashemp206** [comment]
@appleguy any chance to solve issue? is there any way layout all horizontal cell in advance so this jerky backward flicker won't appear?!

**Comment by appleguy** [comment]
@hashemp206 - sorry for the delay!  Have you tried enabling .neverShowPlaceholders on your ASCellNode?  This may actually be enough to fix the user-visible issue (the flicker), but will come at the cost of a slight stutter (less bad than UIKit alone would cause on every swipe event, though).

Let me know if that works, or also if it doesn't work.  #828 is just one indication of it, but I am working in ASRangeController in a number of ways right now.  The only problem is that the weekend is the only part of the week where I can make real progress (workday is meetings, work night is reading / replying to the emails I got during the meetings, weekend is catchup at home / emails I didn't get to / then all remaining time on AsyncDisplayKit).

So I'm hoping we can work together to find a workaround for you, as although a real fix in the framework will definitely be available in the future, with the holidays coming up it could take a couple months.

**Comment by hashemp206** [comment]
thanks for your replay. your are a great and productive man.
 I tried again using 
``` objective-c
[_collectionView setTuningParameters:(ASRangeTuningParameters){
        .leadingBufferScreenfuls = self.dataArray.count, // initially layout all cells in the direction of scroll
        .trailingBufferScreenfuls = 1.0f // one-half screenful in the other direction
    } forRangeType:ASLayoutRangeTypeRender];```

will cause all the cells to be get layout. now works well for circular scrolling. but needs to be tuned. if app has a lot of cells, it takes time to last cell in the queue gets layout. so there should be a way when user is is defining circular collectionView, a few first cells and and a few of last cells gets layout. not all one hundred cells!

**Comment by appleguy** [comment]
@hashemp206 no idea why this was closed?!  As far as I know, supporting this would require at least several tweaks to ASRangeController, so we definitely should not close it - unless you know something I'm not realizing?

**Comment by hashemp206** [comment]
my temporarily solution means loading all the cells in advanced would fix the problem! but it was a hack not a solution! OK. so it seem better to be open. 
Im trying to a create a custom UIControl using AsyncDisplayKit. actually I did that! but there was some cases ```AsyncDisplayKit``` wouldn't act correctly! and I couldn't find a clear and fast solution!
I try to submit a sample app and will explain the desired behavior!

**Comment by appleguy** [comment]
@hashemp206 - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.
