### ISSUE TITLE
[Example Project Kittens] Kittens app cell separators have visual jitter when scrolling.

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#775]
I have read your ASDK ppt. there are 3 ways to perform layout with ASDK. How to use the third way automatic layout?

**Comment by appleguy** [comment]
@wy19901227 did you watch the NSSpain tech talk?  It does give an overview of the system.  We're working on additional documentation and sample apps.

You can also look at the KittenNode implementation in examples/Kittens, which defines a -layoutSpecThatFits: method.  There are other projects that have example code too, like if you're using swift, @nguyenhuy's AsyncMessagesViewController project has some pretty sophisticated layout specs.

**Comment by wy19901227** [comment]
oh,I honw.In your examplse/Kittens.you said : KittenNode has its own separator.and can set the separator's height?  when I scroll the tableview the separator's height will change .
the 0.5px 
![6754d972-417f-4494-b4f8-b0fa27110a2c](https://cloud.githubusercontent.com/assets/8086633/10748830/e8c78e78-7c9e-11e5-8399-670aceb56fa8.png)
the 1.0px
![34b5fecf-58fd-45fc-8c2b-fe6a8b7ecdf9](https://cloud.githubusercontent.com/assets/8086633/10748836/fabc524e-7c9e-11e5-9edc-5f292d99211e.png)

**Comment by appleguy** [comment]
@wy19901227 What simulator are you using?  Is it running at a scaled-down size?  Check the menus in the simulator.

I can test it locally but I'm pretty sure this doesn't happen on a device or unscaled simulator.

**Comment by appleguy** [comment]
@wy19901227 I'm sorry I doubted your finding.  You're correct, something weird is going on here.

I'm going to rename your task to track this.  We'll get it fixed soon.  I can probably look at it tomorrow.  @nguyenhuy you may be curious to observe this phenomenon - since you have worked on the Kittens app - very strange!

**Comment by appleguy** [comment]
If you have any other questions on automatic layout, please create new issues to ask them; we welcome the questions.  Sorry there isn't any broader documentation available today, but I'll prominently announce it when there is some.

**Comment by wy19901227** [comment]
I found it on my iPhone 6. 

In examples/Kittens, although you set the launchImage by name them Default.png. But it doesn't work on xcode7.So I found cell separators have visual jitter when scrolling. When I set the launchImage right,It become ok, or I cann't differentiate the separators changed.

**Comment by maicki** [comment]
We added a ton of new documentation for layout now:
- http://asyncdisplaykit.org/docs/automatic-layout-containers.html
- http://asyncdisplaykit.org/docs/layout-api-sizing.html

The 1px problem in the Kitten project is nothing we can do about. We use the common way to create a 1px divider:

```Objc
CGFloat pixelHeight = 1.0 / [[UIScreen mainScreen] scale];
```

iPhone 6 and iPhone 6s screens is rendered in a bigger size and than down sampled.

I will close this issue for now as. Please reopen if you don't think it is resolved. Thank you!
