### ISSUE TITLE
Is support iOS 6？

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#778]

**Comment by appleguy** [comment]
@wy19901227 Sorry, unfortunately not :(.  I believe this is explicitly stated in the documentation / info pages (it might be on asyncdisplaykit.org if it isn't on the GitHub).

That said, if you wanted to fork the project it probably would not take much work to get it building for iOS 6.  I originally developed this and had it running when iOS 4.x was still common enough to support, and tested it on an iPhone 3G.  You would have to cut out / put version gating around some features but if you were doing it in a personal fork you could get it working pretty fast I'd think.
