### ISSUE TITLE
indexPathForNode method has disappeared

### ISSUE THREAD

**Issue by joamafer** [facebook/AsyncDisplayKit#779]
/**
 * Similar to -indexPathForCell:.
 *
 * @param cellNode a cellNode part of the table view
 *
 * @returns an indexPath for this cellNode
 */
- (NSIndexPath *)indexPathForNode:(ASCellNode *)cellNode;

I no longer can find this method in ASTableView.h

**Comment by vitalybaev** [comment]
@joamafer Which version of AsyncDisplayKit you are using? I checked the master branch and ```indexPathForNode``` still exists.

This is screenshot with AsyncDisplayKit installed with CocoaPods with :git :master

<img width="472" alt="2015-10-27 18 35 04" src="https://cloud.githubusercontent.com/assets/724423/10763094/b2836fc2-7cd9-11e5-91aa-ca2e45abef11.png">

**Comment by vitalybaev** [comment]
@joamafer Oh, I checked the history of ```ASTableView.h``` and found this method in commit https://github.com/facebook/AsyncDisplayKit/commit/d09888f9c235b502143042c9b017a214cabb1fa3
So, you can use the latest master branch of AsyncDisplayKit with the following line in your ```Podfile```:
```
pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :branch => 'master'
```

**Comment by appleguy** [comment]
@joamafer Thanks for asking the question — @vitalybaev is correct, this is supported in master and will be in all future releases.  I'm planning to release AsyncDisplayKit 1.9 later this week, which will be a stable version that includes this API.

@joamafer please reopen (or open a new issue) if you have any other question!
