### ISSUE TITLE
How to use automatic Layout?

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#785]
Hi @appleguy ,In  useing ASDK, I used automatic Layout,It's very cool. But when I update the layout,I found I must write the logic in the layoutSpecThatFits: method by set a BOOL property, For exzample,When I want to hidden a ImageView,I should write the Logic in setting the layoutSpe's children to make sure the ImageView is in the layoutSpe's childrenarray or not.
It's OK but If can offer a property of node,when I set this property ,It will change it's layout in the layoutSpe?

**Comment by wy19901227** [comment]
In exzamples/kitten,I udate the kittenNode like this
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
  _imageNode.preferredFrameSize = _isImageEnlarged ? CGSizeMake(2.0 * kImageSize, 2.0 * kImageSize) : CGSizeMake(kImageSize, kImageSize);
  _textNode.flexShrink = YES;
  
  ASStackLayoutSpec *stackSpec = [[ASStackLayoutSpec alloc] init];
  stackSpec.direction = ASStackLayoutDirectionHorizontal;
  stackSpec.spacing = kInnerPadding;
  if (_isHidden) {
    [stackSpec setChildren:@[_textNode]];
  }
  else
  [stackSpec setChildren:!_swappedTextAndImage ? @[ _imageNode, _textNode] : @[_textNode, _imageNode]];
 // [stackSpec setChildren:@[_textNode]];
  ASInsetLayoutSpec *insetSpec = [[ASInsetLayoutSpec alloc] init];
  insetSpec.insets = UIEdgeInsetsMake(kOuterPadding, kOuterPadding, kOuterPadding, kOuterPadding);
  insetSpec.child = stackSpec;
  return insetSpec;
}

but it works not well.

**Comment by vitalybaev** [comment]
@wy19901227 your problem is the same as mine #718 
You had to fire ```[_tableView beginUpdates]``` and ```[_tableView endUpdates]``` when change node's layout. It can be done via delegates. Theres is sample project, showing this https://github.com/vitalybaev/ASDK-NodeHeightChangeExample

**Comment by wy19901227** [comment]
yeah.,thanks.

发自我的 iPhone

**Comment by nguyenhuy** [comment]
Another way is to call the new -relayoutNodeAtIndexPath, which triggers setNeedsLayout on the node (so you dont need to) and calls the table view to relayout with animation.

@vitalybaev: I promised to notify you onvc this API is available but have forgotten until now, sorry :)

**Comment by vitalybaev** [comment]
@nguyenhuy Oh, I missed API changes, thanks for your work!

**Comment by wy19901227** [comment]
In the new exzamples/kitten,when use  -relayoutNodeAtIndexPath method ,there is a bug in the divider of  
the node,the divider's color will be write.

**Comment by wy19901227** [comment]
why In your demo pod 'AsyncDisplayKit', is 1.9,but I write a podfile is 1.2.3,how become 1.9?

**Comment by nguyenhuy** [comment]
@wy19901227 Thanks for reporting the divider problems (here and #775), I will investigate them later this week. 

Regarding the pod version, looks like v1.9 hasn't been pushed to CocoaPods repo (cc @appleguy). For the moment, you can edit your Podfile to use the release tag
```
pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git', :tag => '1.9'
```

**Comment by wy19901227** [comment]
Not success.
![30c1e057-ab83-4426-b6f3-6097854ce978](https://cloud.githubusercontent.com/assets/8086633/10836794/c2889d2e-7eec-11e5-834c-f3e08067e845.png)

**Comment by nguyenhuy** [comment]
Try to use the HTTPS URL of the repo then :)

**Comment by appleguy** [comment]
@wy19901227 sorry, yeah, 1.9 had not been fully released until just yesterday (that was intentional because it wasn't ready yet).

It should work to specify just

pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git'

Please let us know if you have any trouble getting it set up.  I'm going to close out this task until we have more specific questions, but open another one any time!
