### ISSUE TITLE
animationsEnabled not getting set back to yes?

### ISSUE THREAD

**Issue by tettoffensive** [facebook/AsyncDisplayKit#788]
We are seeing an issue where after playing with the app for a while animations aren't working properly and someone suggested `[UIView animationsEnabled:NO]` not getting set back to YES. I've searched our project and have found that the only place where that happens is in the ASCollectionView and ASTableView.

Not sure if this is actually the case, but am going to start investigating. Could it be possible that these aren't getting set back properly?

**Comment by levi** [comment]
@tettoffensive could you give more context into what kind of animations exactly are not working properly?

**Comment by tettoffensive** [comment]
Seems to be various animations throughout the app that are using UIView animations like:
```
UIView *view = [self.loader viewWithTag:1];
    CGAffineTransform orig = view.transform;
    
    [UIView animateWithDuration:0.5f delay:0 options:UIViewAnimationOptionCurveLinear animations:^{
        [view setTransform:CGAffineTransformRotate(orig, M_PI_2)];
    }completion:^(BOOL finished){
        if (finished) {
            [self rotateLoaderView];
        }
    }];
```

**Comment by Adlai-Holler** [comment]
I've got a client app where the animations randomly go missing. Could be related to this.

**Comment by levi** [comment]
I've seen this happening in our production app since updating to master, also.

**Comment by tettoffensive** [comment]
Ah, good to know. I'm under some deadlines so don't have time to dive in deep today. but wanted to get it out there just in case others have seen it

**Comment by Adlai-Holler** [comment]
@tettoffensive Could you try #789 and see if it resolves the issue?

**Comment by tettoffensive** [comment]
@Adlai-Holler  I *think* this is solving the issue. Though the problem only showed up very rarely. I'll reopen if i see it again.
