### ISSUE TITLE
How to build a UIBUtton with ASDK？

### ISSUE THREAD

**Issue by wy19901227** [facebook/AsyncDisplayKit#810]
The button has image and title, and When taped it's image will be high,How to build?

**Comment by vitalybaev** [comment]
@wy19901227 take a look at the new ASButtonNode https://github.com/facebook/AsyncDisplayKit/pull/800
It's available at master branch and has similar API.
To highlight you can override setter setHighlighted

**Comment by appleguy** [comment]
Yep!! Also, less efficient but works to use initWithViewBlock: and create a UIButton to return in the block.

**Comment by wy19901227** [comment]
tks.can you offer a demo to build a difficult cell .hehe

发自我的 iPhone

> 在 2015年11月3日，14:38，appleguy <notifications@github.com> 写道：
> 
> Yep!! Also, less efficient but works to use initWithViewBlock: and create a UIButton to return in the block.
> 
> Sent from my iPhone
>

**Comment by appleguy** [comment]
@wy19901227 I also committed ASButtomNode recently.  Let me know if you want to add any features to it and feel free to submit a diff!

**Comment by wy19901227** [comment]
What I mean is Can you offer a cell demo, the cell has many component,Just like Button, view, or some textLabel which can be linked.So I can learn it and use to my project.
