### ISSUE TITLE
Insert rows without scroll on top

### ISSUE THREAD

**Issue by topa51** [facebook/AsyncDisplayKit#811]
Hi,
How can I insert items on the top of TableView without scroll animation.
Is there any callback in ASDisplayKit that will be call when insert action will finish?

**Comment by nguyenhuy** [comment]
> How can I insert items on the top of TableView without scroll animation.

I don't think ASTableView automatically scroll to top after insertions. Are you sure the behaviour is not caused by your code?

> Is there any callback in ASDisplayKit that will be call when insert action will finish?

You can use `ASTableView -endUpdatesAnimated:completion:`.

**Comment by lappp9** [comment]
hey @nguyenhuy, is there an example of using -endUpdatesAnimated?

I have the opposite problem where i'm wanting to scroll to the bottom of the table view after the cells have loaded and i can't quite figure out how to do that other than using the following, which seems clearly wrong.  

`self.performSelector("scrollToBottom", withObject: nil, afterDelay: 0.25)`

```
func scrollToBottom() {
        if messages.count > 0 {
            self.tableView.scrollToRowAtIndexPath(NSIndexPath(forRow: self.messages.count - 1, inSection: 0), atScrollPosition: .None, animated: true)
        }
    }
```

**Comment by vitalybaev** [comment]
@lappp9 in Objective-C it looks like this:

```
[_tableView beginUpdates];
[_tableView insertRowsAtIndexPaths:indexPaths withRowAnimation:UITableViewRowAnimationNone];
[_tableView endUpdatesAnimated:NO completion:(void (^)(BOOL)) ^{

    //Insert finished

}];
```

**Comment by lappp9** [comment]
Ah that makes sense, thanks!

**Comment by appleguy** [comment]
@lappp9 thanks for filing this — I'm not 100% clear if there is an API improvement we can make here, but would be very interested to hear from you if you have any suggestion for how we could have made this more clear.  Whether comments in the header, different API names, etc.  Documentation is a no-brainer, and that one's on us...some good progress is actually being made, but it will still be a couple months before we have more robust docs published.

Please open a new issue with any other issues, whether suggestions or questions!
