### ISSUE TITLE
[Question] Top and bottom separator surounding content using ASLayoutSpec

### ISSUE THREAD

**Issue by KieranLafferty** [facebook/AsyncDisplayKit#817]
Having a bit of an issue figuring out a particular layout spec. Trying to use a stack view to position top/bottom separator views which should always be 1pt height with flexible width. Hoping someone can take a 
    
    ASLayoutSpec *topSeparatorSpec = [[ASLayoutSpec alloc] init];
    topSeparatorSpec.child = _topSeparator;
    topSeparatorSpec.sizeRange = ASRelativeSizeRangeMakeWithExactRelativeDimensions(
        ASRelativeDimensionMakeWithPercent(1.0),
        ASRelativeDimensionMakeWithPoints(1.0)
    );
    
    ASLayoutSpec *bottomSeparatorSpec = [[ASLayoutSpec alloc] init];
    bottomSeparatorSpec.child = _bottomSeparator;
    bottomSeparatorSpec.sizeRange = ASRelativeSizeRangeMakeWithExactRelativeDimensions(
        ASRelativeDimensionMakeWithPercent(1.0),
        ASRelativeDimensionMakeWithPoints(1.0)
    );
    
    ASStackLayoutSpec *contentVStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                spacing:0
                                                                         justifyContent:ASStackLayoutJustifyContentStart
                                                                             alignItems:ASStackLayoutAlignItemsStretch
                                                                               children:@[
                                                                                          [ASInsetLayoutSpec insetLayoutSpecWithInsets:_topSeparatorInsets child:topSeparatorSpec],
                                                                                          [ASInsetLayoutSpec insetLayoutSpecWithInsets:_contentInsets child:contentHStackSpec],
                                                                                          [ASInsetLayoutSpec insetLayoutSpecWithInsets:_bottomSeparatorInsets child:bottomSeparatorSpec],
                                                                                          ]];
    return contentVStack;

**Comment by vitalybaev** [comment]
@KieranLafferty could you try adding sizeRange directly to separator node, then wrap it with ASStaticLayoutSpec and adding this static specs to your stack

**Comment by nguyenhuy** [comment]
That should work. Thanks, @vitalybaev :+1: 

We probably should update the documentation of options in ASStaticLayoutable to make it clear that they are only considered inside an ASStaticLayoutSpec.

**Comment by vitalybaev** [comment]
@nguyenhuy also I can provide some more complex example than Kittens, which shows such common things in cells layout.

**Comment by nguyenhuy** [comment]
That would be tremendously useful. Please do :)

**Comment by KieranLafferty** [comment]
Thanks so much that worked! I just have one minor issue left after updating the layout with your recommendation. Now, the view always takes up the full width in ASSizeRange. Previously, it would dynamically size the width based on the content but after adding the separators it now always takes on maxSize

    // Bottom separator layout spec
    ASRelativeSize maxSeparatorSize = ASRelativeSizeMake(
        ASRelativeDimensionMakeWithPercent(1.0),
        ASRelativeDimensionMakeWithPoints(1.0 / [UIScreen mainScreen].scale)
    );
    _topSeparator.sizeRange = ASRelativeSizeRangeMakeWithExactRelativeSize(maxSeparatorSize);
    ASLayoutSpec *insetTopSeparatorSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:_topSeparatorInsets
                                                                                 child:[ASStaticLayoutSpec staticLayoutSpecWithChildren:@[_topSeparator]]];
    
    _bottomSeparator.sizeRange = ASRelativeSizeRangeMakeWithExactRelativeSize(maxSeparatorSize);
    ASLayoutSpec *insetBottomSeparatorSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:_bottomSeparatorInsets
                                                                                    child:[ASStaticLayoutSpec staticLayoutSpecWithChildren:@[_bottomSeparator]]];
   
    // Inset the content by the content insets and allow it to grow to fill it's area
    ASLayoutSpec *insetContentSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:_contentInsets child:contentHStackSpec];
    insetContentSpec.flexGrow = YES;
    
    // Stack the separators around the content
    ASStackLayoutSpec *itemViewVStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                spacing:0
                                                                         justifyContent:ASStackLayoutJustifyContentStart
                                                                             alignItems:ASStackLayoutAlignItemsStart
                                                                               children:@[
                                                                                          insetTopSeparatorSpec,
                                                                                          insetContentSpec,
                                                                                          insetBottomSeparatorSpec
                                                                                          ]];
    return itemViewVStack;

Note: if I remove the insetTopSeparatorSpec and insetBottomSeparatorSpec from the stack layout it will resize dynamically. Or, if i simply return the insetContentSpec it also resizes dynamically. See below for example

    ASStackLayoutSpec *itemViewVStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                spacing:0
                                                                         justifyContent:ASStackLayoutJustifyContentStart
                                                                             alignItems:ASStackLayoutAlignItemsStart
                                                                               children:@[
                                                                                          insetContentSpec,
                                                                                          ]];
    return itemViewVStack;

And

    return insetContentSpec;

Perform dynamic width adjustment

**Comment by KieranLafferty** [comment]
Just as an update, tried setting the sizeRange of insetBottomSeparatorSpec/insetTopSeparatorSpec to be (0%, 0%) -> (100%, 100%) with no luck either

**Comment by vitalybaev** [comment]
@KieranLafferty oh, I get it. It's because you set exactly sizeRange for separators to 100% width. So separator can't be < 100%.
If you want separator to be flexible width, you had to set size range with min and max sizes. For example

_topSeparator.sizeRange = ASRelativeSizeRangeMake(minSeparatorSize, maxSeparatorSize)

**Comment by vitalybaev** [comment]
@nguyenhuy #823 look at this example and tell me, what you are think

**Comment by appleguy** [comment]
Thanks so much for helping here, @vitalybaev!  It's really wonderful to have you in the community.

@KieranLafferty likewise, thanks for bringing us this question.  It's a good use case for us to better document and use in examples, as the solution is not immediately clear.  @rcancro & @garrettmoon, could you include this or something conceptually similar in our documentation effort?  Setting the fixed 1px/1pt height along with the width flexibility consideration is a useful building block for layout specs.

**Comment by appleguy** [comment]
@hannahmbanana: could you add this to our 2.0 documentation to-do list? Thanks!
