### ISSUE TITLE
Having problem displaying ASButtonNode

### ISSUE THREAD

**Issue by robmontesinos** [facebook/AsyncDisplayKit#824]
I have a ViewController with several ASTextNodes, an AsImageNode and an ASButtonNode. The button node does not accept an image or text. I get just a blank button. Any thoughts to what I'm doing wrong?

```ObjectiveC
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
        self.donateButtonNode = [[ASButtonNode alloc] init];
        
        CGFloat buttonWidth = 150.0;
        self.donateButtonNode.frame = CGRectMake((self.view.bounds.size.width / 2) - (buttonWidth / 2), 296.0, buttonWidth, 44.0);
        self.donateButtonNode.backgroundColor = FlatBlue;
        self.donateButtonNode.cornerRadius = 6.0;
        self.donateButtonNode.clipsToBounds = YES;
        
        NSAttributedString *attributedDonate = [[NSAttributedString alloc] initWithString:@"PayPal Link"
                                                                               attributes:@{NSForegroundColorAttributeName:FlatWhite, NSFontAttributeName: [UIFont fontWithName:self.theme.fontTextLight size:15.0]}];
        
        [self.donateButtonNode setAttributedTitle:attributedDonate forState:ASButtonStateNormal];
        [self.donateButtonNode setImage:[UIImage imageNamed:kImagesPayPalLogo] forState:ASButtonStateNormal];
        
        [self.donateButtonNode addTarget:self action:@selector(donateButtonPressed:) forControlEvents:ASControlNodeEventTouchUpInside];

        dispatch_async(dispatch_get_main_queue(), ^{
            [self.view addSubview:self.donateButtonNode.view];
        });
    });

**Comment by robmontesinos** [comment]
I converted the ASButtonNode into an ASImageNode and it worked well enough for my needs. ASButtonNode appears to not be working? Any ideas of what I did wrong?

**Comment by appleguy** [comment]
Are you calling -measureWithSizeRange: on any of the things you're adding?

I recommend you use an ASViewController, and make sure to set its node property (-initWithNode may be the only way right now, later changes will probably make it a writable property like UIViewController).  It calls -measure: for you in -viewDidLoad.

Make sure to assemble your node hierarchy, then call -measureWithSizeRange: on it if you aren't using an ASCellNode or ASViewController as the container, and then you should be able to insert its view (of course make sure it is positioned in -viewWillLayoutSubviews or similar).

**Comment by appleguy** [comment]
@robmontesinos feel free to comment on your result and do reopen the task if that's not the solution for you.
