### ISSUE TITLE
[Layout] Questions on how to equally divide space between three elements (ASDK 1.9)

### ISSUE THREAD

**Issue by logicsb** [facebook/AsyncDisplayKit#835]
We are using AsyncDisplayKit to speed up rendering our feed (tableview) IOS. 
However, we can’t figure out how to fix the layout as bellow… 
We have three objects in line (fullname, place, image). We want to have a fixed width and height for each one, however the textfield always automatically fit to the text length. 
We have noticed this is happening after upgrade to version 1.9 of the ASDK (see figure bellow). 
Our code is this…

Example code:  
```
fullname.preferredFrameSize = CGSizeMake(100, 100) // doesn't work / nothing happens
```

![screen shot 2015-11-10 at 2 17 08 pm](https://cloud.githubusercontent.com/assets/1790860/11077978/0f4161fe-87ea-11e5-9591-4125681a6d46.png)

**Comment by appleguy** [comment]
@logicsb Thanks for the question!  Could you share more details on how your layout is implemented?  Are you using -calculateSizeThatFits: and -layout, or have you adopted -layoutSpecThatFits: ?

I'm concerned that you saw any layout change with 1.9 if you have NOT yet adopted ASLayoutSpecs.  Can you confirm / screenshot what happens before and after if you switch your project between 1.2.3 & 1.9?  (Naturally it's pretty quick to specify a certain version for cocoapods and to switch between).

If you are using ASLayoutSpec, take a look at ASStaticLayoutSpec.  If you could draw (with colored boxes or anything else, really rough) the look you're trying to achieve, I didn't quite understand what you mean by having a fixed size for each thing.  If you didn't mean a static layout, you may want to use a horizontal ASStackLayoutSpec and set the .flexBasis of each item, using an ASRelativeDimension of 0.33 (33 percent).

**Comment by logicsb** [comment]
Hi @appleguy thanks for answer. I'm using layoutSpecThatFits and the previous working version are 1.8 because the version 1.2.3 via pod file don't have ASLayoutSpec implemented. About the layouts i'm using ASStackLayoutSpec with direction horizontal to make the texts inline. The solution with ASRelativeDimension has solved my problem. Thanks
