### ISSUE TITLE
[ASTextNode] CGContextFillRects crash from setting flexBasis

### ISSUE THREAD

**Issue by logicsb** [facebook/AsyncDisplayKit#839]
Hi folks,

I'm using ASRelativeDimension in the -layoutSpecThatFits to determine size of the an ASTextNode. but this code is causing this error:
GContextFillRects: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

```
        self.label.flexBasis = ASRelativeDimension(type: .Percent, value: 1.0) // <- this cause the error
        let specLabel:ASStackLayoutSpec = ASStackLayoutSpec()
        specLabel.direction = .Vertical
        specLabel.alignItems = .Center
        specLabel.justifyContent = .Start
        specLabel.alignSelf = .Stretch
        specLabel.setChildren([self.label])
```

Another question, how i can use UIPageControl with the ASDIsplayNode and ASScrollNode ?

Thanks.

**Comment by appleguy** [comment]
@logicsb what layout are you trying to achieve?  Suggestions / questions:

- Can you try setting flexShrink = YES and deleting your flexBasis line?  Does that do what you want?  This weekend I'm planning to release 1.9.2 and make flexShrink = YES the default for ASTextNode.
- Can you add this code to any of our example/ directory projects and see if you can make it reproduce?  I would love to debug the crash.
- Please provide the crashing backtrace / any other console logs that are generated.
- To use UIPageControl, you have two options:
-- Create a simple ASDisplayNode wrapper using [[ASDisplayNode alloc] initWithViewBlock: [provide a block that creates and returns a UIPageControl]]
-- Simply create the UIPageControl directly in the -didLoad method of a node.  Simply do [node addSubview:pageControl], which is equivalent to [node.view addSubview:pageControl].  It's important to do this in -didLoad if you go this route, as that is called on the main thread once the view is created; in init for the node, you should never call into UIKit directly.  If you go this route, you will need a manual -layout method - but you can call super (and still use layoutSpecThatFits!), positioning just the page control in the -layout method.

The benefit of wrapping in the node is that you can more easily handle the page control before the nodes have loaded, including use the -layoutSpecThatFits method to position it.

**Comment by logicsb** [comment]
Hi @appleguy.

Using flexShrink = true I get this result. This result is not what I expect since the gray label bellow the image has to match with the image width. They are in the same ASStackLayoutSpec with direction Vertical 

App Image
![captura de tela 2015-11-12 as 17 49 48](https://cloud.githubusercontent.com/assets/1790860/11137558/ee84b300-899f-11e5-8ce3-3b58f3a53fa2.png)

Code Image
![captura de tela 2015-11-12 as 17 51 01](https://cloud.githubusercontent.com/assets/1790860/11137561/02382436-89a0-11e5-9a9e-a9b63aae1735.png)

Using label.flexBasis = ASRelativeDimension(type:.Percent, value: 1.0) results the crash bellow

Code Image
![captura de tela 2015-11-12 as 17 56 09](https://cloud.githubusercontent.com/assets/1790860/11137681/566eb4f6-89a1-11e5-958a-2ed5eaa178c3.png)

Crash Image
![captura de tela 2015-11-12 as 17 55 03](https://cloud.githubusercontent.com/assets/1790860/11137675/45222dd6-89a1-11e5-8003-fd80711e3fea.png)

I tried to reproduce this error in the example code but there it works.

Thanks

**Comment by Adlai-Holler** [comment]
@logicsb Hi! Sorry for the delayed response here, hope you've had a good year! 😅 

Does this still occur on the latest ASDK?

**Comment by maicki** [comment]
@logicsb Hey! I will close this issue for now. Please reopen if the issue still occurs on latest ASDK version. Thanks!
