### ISSUE TITLE
[Question] Proper usage of ASTableView

### ISSUE THREAD

**Issue by hoangson1989** [facebook/AsyncDisplayKit#841]
Hi Guy,

I'm refactoring my project with ASDisplayKit and i has a problem with memory.
i'm using a UITableView with some reuse uitableviewcell .In UITableViewCell,before setup new UI,i'll remove all old ASDisplayNode and create new ones.But The memory's coming up until app crash?

Please help !

**Comment by appleguy** [comment]
@hoangson1989 Would love to help you fix it, shouldn't be difficult.

What version of AsyncDisplayKit are you using?  Can you send a screenshot and a dump of the view or node hierarchy?  Of course, a test project is ideal, as I'll personally debug any issues you're seeing if you are able to share one.

**Comment by hoangson1989** [comment]
Hi appleguy,

Thanks for your reply.
I've create a test project for you :  https://www.dropbox.com/s/jdp4rpwuagxtgnp/TestAsync.zip?dl=0.

**Comment by appleguy** [comment]
@hoangson1989 thanks so much!  I can't currently get the project to build.  Any suggestions?

ld: warning: directory not found for option '-L/Users/scottg/code/TestAsync/build/Debug-iphoneos'
ld: library not found for -lAsyncDisplayKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by appleguy** [comment]
@hoangson1989 I see in your project you are using .xib files, and there is also a UITableView.

Neither Interface Builder, nor UITableView itself, are supported with AsyncDisplayKit.  You must use ASTableView, and avoid using Interface Builder.  Feel free to check out a few of my talks which discuss these details.

https://www.youtube.com/watch?v=RY_X7l1g79Q
https://www.youtube.com/watch?v=ZPL4Nse76oY

Let me know if you have any other questions, but I'll close this task soon if you can confirm your test project isn't making use of ASTableView (there would be no way for it to call -clearContents or even trigger cells to render before they're onscreen, which will definitely affect memory usage and cause visual flashing onscreen if you are using UITableView alone).

**Comment by appleguy** [comment]
@hoangson1989 please reopen this task if you have any other questions on this issue - and open a new one for any other questions!  Would love to help.
