### ISSUE TITLE
-fetchData after collectionView reloadDataImmediately not called

### ISSUE THREAD

**Issue by smiLLe** [facebook/AsyncDisplayKit#845]
Hey guys,

i have an ASCellNode where i load an image from the network in -fetchData and display it in ASImageNode afterwards. At some time, when my datasource has been updated (array including some models) i call -reloadDataImmediately on the ASCV but unfortunately -fetchData isn't called anymore and no images are going to be downloaded. This is also the case with -reloadData.

My thought was to load images in -fetchData but it is obviously wrong. Where is the right place to load this kind of data? -didLoad?

Thanks :)

**Comment by appleguy** [comment]
Hey @smiLLe - really good question.  This is a very reasonable implementation you've described, so don't worry that it's "obviously wrong!"  Really, the framework is not behaving ideally for you in this case.

For one thing, have you tried ASNetworkImageNode?  Does that not behave as you expect when you set the URL?

Separately though, it's funny that a /very/ similar question has come up just hours before yours.  I'm going to merge this task into that one, as I think the right framework response is going to be tracked by that task.  Please feel free to continue the discussion on that task, or reopen this one if you think your use case is sufficiently different.  I'd also love to discuss any other challenges you've had with ASDK in additional GitHub Issues, so file away!

https://github.com/facebook/AsyncDisplayKit/issues/844
