### ISSUE TITLE
How use LayoutSpec for specific task

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#855]
Hi all!
I have intresting task for CollectionView Header. I want to add ASNetworkImageNode with width as screen and height as loaded Image. ContentMode must be UIViewContentModeScaleAspectFit. Can i make this task with LayoutSpec, or no? 
![untitled](https://cloud.githubusercontent.com/assets/1393809/11207063/cdba46ba-8d34-11e5-8e41-d88316a7b610.png)

**Comment by smiLLe** [comment]
try wrapping your ASNetworkImageNode into an ASRatioLayoutSpec

**Comment by bimawa** [comment]
@smiLLe thx for advice, i go try it )

**Comment by bimawa** [comment]
@smiLLe  Yes it what i need. Thx a lot

**Comment by bimawa** [comment]
@smiLLe  i have another trouble, mb u can help me.
Now my HeaderSection View Height dependence at ImageNode height, and in Header View i have 2 addition ASLayoutSpec (like at image)  
![untitled](https://cloud.githubusercontent.com/assets/1393809/11209724/c5c22472-8d44-11e5-8042-e7ecefe333fa.png)
How, if i can, set ImageNode height priority highest then i receive in receiver `constrainedSize` constraints, of method `- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize`? And i now must get new size of HeaderView and update all collectionView?

**Comment by bimawa** [comment]
I understand how Rate works its not what i want unfortunately :(

**Comment by nguyenhuy** [comment]
Does wrapping the image node and 2 other specs inside a vertical stack work for you?

**Comment by nguyenhuy** [comment]
@smiLLe Thanks for suggesting ratio spec. It is indeed the ideal solution I think.

**Comment by bimawa** [comment]
@nguyenhuy Yes I do. Ratio rly help for save proportion for imageNode. But i need a little bit  else. If Image horizontale, as on screenshot, i want get maximum heigh for node, depend of width screen.
![1447764903901](https://cloud.githubusercontent.com/assets/1393809/11212014/167b5ff4-8d55-11e5-8e62-86cec20a2c4e.jpg)
And if Image Verticale pref. it must scale by width screen. And offset other LayoutSpec down by hight
(Example without RatioSpec)
![1447766116587](https://cloud.githubusercontent.com/assets/1393809/11212398/6174093c-8d57-11e5-9dcc-b99d9a3c5d82.jpg)

I'm experiment with it
```
    ASStackLayoutSpec *asImageStackLayoutSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:0
                                                                                 justifyContent:ASStackLayoutJustifyContentCenter alignItems:ASStackLayoutAlignItemsStretch
                                                                                       children:@[self.headerImageNode]];
    //endregion


    ASStackLayoutSpec *verticalElementCoreStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:0
                                                                                   justifyContent:ASStackLayoutJustifyContentCenter alignItems:ASStackLayoutAlignItemsStart
                                                                                         children:@[asImageStackLayoutSpec, self.textNodeOne, self.testNode]];

    return verticalElementCoreStack;
}
```

**Comment by bimawa** [comment]
If i will be use Masonry my solution looks like so:

```objective-c
 self.headerImageNode.contentMode        = UIViewContentModeScaleAspectFit;
        [self.headerImageNode setContentHuggingPriority:UILayoutPriorityFittingSizeLevel forAxis:UILayoutConstraintAxisHorizontal];
        [self.headerImageNode setContentHuggingPriority:UILayoutPriorityRequired forAxis:UILayoutConstraintAxisVertical];
        [self.headerImageNode setContentCompressionResistancePriority:UILayoutPriorityFittingSizeLevel forAxis:UILayoutConstraintAxisHorizontal];
        [self.headerImageNode setContentCompressionResistancePriority:UILayoutPriorityRequired forAxis:UILayoutConstraintAxisVertical];
        [self.headerImageNode makeConstraints:^(MASConstraintMaker *make) {
            make.width.equalTo(contentView);
        }];
        [self.textNodeOne makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(contentView);
            make.left.equalTo(contentView);
            make.top.equalTo(self.headerImageNode.bottom);
        }];
        [self.testNode makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(contentView);
            make.left.equalTo(contentView);
            make.top.equalTo(self.textNodeOne.bottom);
        }];
```

**Comment by nguyenhuy** [comment]
Well if the image is loaded, you just need to set the *image* ratio to the ratio spec, rather than a ratio of 1. There is an example for this use case in SocialAppLayout ([here](https://github.com/facebook/AsyncDisplayKit/blob/b295eda4b16098124b0ae7295f40fd89e894606b/examples/SocialAppLayout/Sample/PostNode.m#L207)).

**Comment by bimawa** [comment]
@nguyenhuy  Wow new example hmm.. I skiped it.
Ok i added Ratio formula, now i must re layout after image loaded. I set delegate for catching `- (void)imageNode:(ASNetworkImageNode *)imageNode didLoadImage:(UIImage *)image` , but how reload Header with better way?

**Comment by bimawa** [comment]
MU HA H AH HAHAHAHAHAA I DID IT!!!!!!
@nguyenhuy  and @smiLLe Guys Than you very much!!!! I Love U ALL!!!!! 
```objective-c
- (void)imageNode:(ASNetworkImageNode *)imageNode didLoadImage:(UIImage *)image
{
    [self setNeedsLayout];
}
```

THX For makeing life of iOS developers easier !!!! THX FOR ADK Its a best way for layouting for iOS today.

**Comment by nguyenhuy** [comment]
Yes, you just need to trigger a relayout in once the image is loaded, by calling `setNeedsLayout` on the cell node. After a relayout, the cell node will automatically notify the containing collection view to update. If you want to animate the change, simply wrap that line inside an animation block (sample in KittensNode).

In case you don't (easily) have access to the cell node (say your view controller is the image delegate), calling `imageNode setNeedsLayout` will work just fine. The image node simply forward the relayout request to its parent (i.e the cell node).

**Comment by bimawa** [comment]
@nguyenhuy Cool thx a lot for advice!

**Comment by nguyenhuy** [comment]
And it's great to have you in the community. Feel free to open new issues for questions and feedbacks :)

**Comment by bimawa** [comment]
Special thanks to fast feedback!
