### ISSUE TITLE
[ASTextNode] Usage of .additionalTruncationMessage is not clear / documented.

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#865]
I create textNode
```Objective-c


self.descriptionTextNode                  = [[ASTextNode alloc] init];
self.descriptionTextNode.maximumLineCount = 3;
self.descriptionTextNode.truncationMode = NSLineBreakByTruncatingTail;
self.descriptionTextNode.attributedString = [[NSAttributedString alloc] initWithString:@"More text Emitters walk from futures like ordinary planets.The twisted mermaid technically pulls the c-beam.Sonic showers resist with advice at the conscious center!Rudely, indeed, interstellar courage!I fight this adventure, it's called evil collision course.string"
                                                                                    attributes:[self p_descriptionAttributes]];
self.descriptionTextNode.additionalTruncationMessage = [[NSAttributedString alloc] initWithString:@"TruncationText dsfdfs a fad sd asdfasfasf "
                                                                                              attributes:[self p_descriptionAttributes]];
        [self addSubnode:self.descriptionTextNode];
```

And what i must do for see `additionalTruncationMessage` ?

**Comment by appleguy** [comment]
@bimawa - hi again!  Thanks for asking...although sadly I have never personally used this API.  It was used it Paper very extensively, and is a useful feature, but it's not well documented.

You might try studying the implementation for any clues, and setting some breakpoints where the string is accessed / used to figure out what is happening to it.

Most importantly — can you try the latest master build?  It has a MAJOR change to the text rendering system that may resolve any bug you're encountering here.  It is equally possible that there isn't exactly a bug, but the API has some kind of unintuitive behavior and needs something else set or configured to work properly.

Let me know what happens when you try master.

**Comment by bimawa** [comment]
>can you try the latest master build?

Now  i use 1.9.1. because of  with a bug in 1.9.2 in NetworkImage. And waiting 1.9.3 )

>Let me know what happens when you try master.

Ok @appleguy

**Comment by yury** [comment]
@bimawa can you test with #1110. With this code it should work

```obj-c
self.descriptionTextNode                  = [[ASTextNode alloc] init];
self.descriptionTextNode.maximumLineCount = 3;
self.descriptionTextNode.additionalTruncationMessage = [[NSAttributedString alloc] initWithString:@"TruncationText dsfdfs a fad sd asdfasfasf "
                                                                                              attributes:[self p_descriptionAttributes]];
self.descriptionTextNode.attributedString = [[NSAttributedString alloc] initWithString:@"More text Emitters walk from futures like ordinary planets.The twisted mermaid technically pulls the c-beam.Sonic showers resist with advice at the conscious center!Rudely, indeed, interstellar courage!I fight this adventure, it's called evil collision course.string"
                                                                                    attributes:[self p_descriptionAttributes]];

[self addSubnode:self.descriptionTextNode];
```

**Comment by bimawa** [comment]
@yury Cool thx a lot i see that later.

**Comment by appleguy** [comment]
I didn't realize this was a bug / there was a test case - @bimawa don't close too early, thanks so much for reporting this!  Certainly reopening until we can get a confirmed fix.

**Comment by appleguy** [comment]
@bimawa please test!  email me with any issues - or add a test case in a PR, would really love to see it!  asyncdisplaykit@gmail.com

**Comment by bimawa** [comment]
@appleguy ok Thanks a lot !
