### ISSUE TITLE
[ASLayoutSpec] ASCenterLayoutSpec inside of a ASTableViewCell

### ISSUE THREAD

**Issue by frankenthumbs** [facebook/AsyncDisplayKit#867]
Hey guys,

I'm having some issues getting ASCenterLayoutSpec to work inside of an ASCellNode. What i want to happen is center the `someHorizontalStack` in the middle of a cell that has a height of 100.

```
private let CellHeight: CGFloat = 100
...
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec! {
    ...
    let center = ASCenterLayoutSpec(centeringOptions: .Y, sizingOptions: .Default, child: someHorizontalStack)
    center.sizeRange = ASRelativeSizeRange(
        min: ASRelativeSize(width: ASRelativeDimension(type: .Percent, value: 0), height: ASRelativeDimension(type: .Points, value: CellHeight)),
        max: ASRelativeSize(width: ASRelativeDimension(type: .Percent, value: 1), height: ASRelativeDimension(type: .Points, value: CellHeight))
    )
    return center
}
```

**Comment by appleguy** [comment]
The bug may actually lie in how you set up the stack, or configured its contents.  You may need to use flexGrow or flexShrink on the stack or the stack items.  Could you share the full implementation of at least the layoutSpecThatFits method, and also provide a screenshot of what it is resulting in?  A test project would be the gold standard to help us find a solution quickly, but I think this issue can likely be solved with a bigger snippet that shows at least layout and ideally also node allocation / setup.

cc @nguyenhuy, @levi who know Swift better than I do as well :).

**Comment by nguyenhuy** [comment]
sizeRange of an object is considered only if it is a child of an ASStaticLayoutSpec. Below code should work:

```swift
let center = ASCenterLayoutSpec(centeringOptions: .Y, sizingOptions: .Default, child: someHorizontalStack)
center.sizeRange = ASRelativeSizeRangeMakeWithExactRelativeSize(
    ASRelativeSizeMake(ASRelativeDimensionMake(.Percent, 1), 
    ASRelativeDimension(type: .Points, value: CellHeight))
)
return ASStaticLayoutSpec(children: [center])
```

Also, in order for your horizontal stack to grow and fill the table width, you probably want your center spec to fill the entire horizontal space, hence an exact size range is used.

**Comment by nguyenhuy** [comment]
Btw, enforcing an exact height for all table view cells is a valid use case that can be better supported with a new -constrainedHeightForNodeAtIndexPath API (#759).

**Comment by appleguy** [comment]
@frankenthumbs - thank you for contributing to the AsyncDisplayKit community by asking your question in this forum. I hope we were able to answer your question. 

Due to the length of time it’s been since this thread was active, I’m going to mark this issue as closed. If you are still having troubles, feel free to reopen it and we will help you as quickly as possible. Additionally, we should have some better ASLayoutSpec documentation coming out soon with the launch of ASDK 2.0.
