### ISSUE TITLE
[ASNetworkImageNode] URL loading error callback / delegate API

### ISSUE THREAD

**Issue by robmontesinos** [facebook/AsyncDisplayKit#880]
I have a situation where a user changes their profile image and the default image remains displayed. This is good. What would be better is if there was a failure block on setURL so that we could requery the server for updated profile image url and reset the image. Is this possible?

I see ASBasicImageDownloader but that seems to be queue-based. I'd like the ASCellNode to check for error in url request and act accordingly. I am considering implementing AFNetworking into the ASCellNode to accomplish this task - I'm wondering if I missed something in ASDK. Thank you

**Comment by appleguy** [comment]
@robmontesinos Hey, thanks for bringing this up.  Could you share a bit more information about the condition you're aiming to detect?  Does the server give an HTTP 404 or some other error when you access the other URL?

In general, it would be best for the app to be able to detect and adjust to this condition without relying simply on the URL request.  There are many reasons a URL request can fail, and of course it takes a full round trip time to figure out what has happened.

I'd suggest, for example, if the user changes their profile picture then immediately trigger a query of the server for any "current user" objects or other loaded data to get updated URLs - before the URLs are actually needed to be displayed.  A key reason for this is that the code which knows how to find the right URL, if the current one fails, is at a higher level in the architecture of the app than just the lowly image node.  The image node should not understand the true "source" of the image or how it would go about requesting an updated data model directly from the server.

All that said, yes it is probably fairly straightforward to add a callback to an image node delegate (I think Multiplex already has a  delegate or datasource API; Network might also) which reports any loading errors to the owner of the node.  This I think would be a reasonable step even if you don't use it for the purpose described, which I'd recommend avoiding.  The main consideration is whether the ASImageDownloader protocol is actually the best place to support this kind of thing.  For example, ASBasicImageDownloader could provide the error callback directly.  If it were added to the protocol itself, then it would require all downloaders to support passing the errors to the node just so the node could pass them to an /optional/ delegate method...and we don't want that.

You may want to use this AsyncDisplayKit-integrated version of SDWebImage: https://github.com/ide/WebASDKImageManager

Pinterest is also currently working on some special custom integrations between PINRemoteImage and AsyncDisplayKit, but this won't be available for a few months and we haven't thought about an error API outside the framework.

@Adlai-Holler has done work throughout the image nodes, and may have thoughts on it!

**Comment by robmontesinos** [comment]
Thanks for getting back to me @appleguy. I have a list of twitter users where I persist their image URL's in Core Data. If the user changes an image, Twitter gives back a bad url message and the place holder image remains. The reason I use Core Data is to limit the API calls since Twitter counts them (I think it's 180 per hour) so I update twitter user particulars (followers and images, etc.) lazily as needed.

I wound up solving this by using NSURLConnection and a mutable request (asynchronous) for HEAD which returns status 200 -> do nothing else fetch new URL's from Twitter and reload the ASNetworkImageNode. I used kind of a hack and wait 2 seconds to check URL and I also use a flag to ignore this step if the image downloaded successfully. It was also easier to have the node check itself and add the Twitter request as an operation to the main operation queue. It's not elegant but it works fine. 

I didn't think it would be a big deal to implement completion and failure blocks similar to AFNetworking. I'll take a look at WebASDKImageManager - I used it elsewhere for image caching but I didn't look at it closely for completion blocks. Thanks for the heads up!!

**Comment by Adlai-Holler** [comment]
@robmontesinos Cool, glad it's up and running. If you want to refactor your solution, `ASMultiplexImageNode` will do very well for you here, and give you an error callback plus some other great functionality. 

To use URLs directly with multiplex image nodes, create a pass-through data source like this one:

```swift
/// An image data source that vends NSURLs as image identifiers.
final class MultiplexDataSource: NSObject, ASMultiplexImageNodeDataSource {
	static let shared = MultiplexDataSource()

	func multiplexImageNode(imageNode: ASMultiplexImageNode, URLForImageIdentifier imageIdentifier: ASImageIdentifier) -> NSURL? {
		return imageIdentifier as? NSURL
	}

	// TODO: implement multiplexImageNode(:, imageForImageIdentifier:) and attempt to read from shared image cache
}
```

Then create a delegate like:

```swift
final class MultiplexImageDelegate: NSObject, ASMultiplexImageNodeDelegate {
	static let shared = MultiplexImageDelegate()

	func multiplexImageNode(imageNode: ASMultiplexImageNode, didFinishDownloadingImageWithIdentifier imageIdentifier: ASImageIdentifier, error: NSError?) {
		if let error = error {
			// Error handling code.
		}
	}
}
```

Then create your nodes like:

```swift
let node = ASMultiplexImageNode(cache: nil, downloader: ASBasicImageDownloader.sharedImageDownloader())
node.dataSource = MultiplexDataSource.shared
node.delegate = MultiplexImageDelegate.shared
node.imageIdentifiers = [ myImageURL ]
```

**Comment by robmontesinos** [comment]
Thank you @Adlai-Holler !! I'll give it a look - my solution is working but am not crazy about it - I'll swing around to in a few days and let you know how it turned out. Gracias again!!

**Comment by Adlai-Holler** [comment]
Sweet, happy to do it!

**Comment by hannahmbanana** [comment]
Closing this issue because it appears that @Adlai-Holler's provided a solution to the issue.
