### ISSUE TITLE
[ASCellNode] Verify implementation of manual de-selection.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#892]
See commentary in:

https://github.com/facebook/AsyncDisplayKit/pull/837

**Comment by appleguy** [comment]
cc @levi, @vitalybaev

**Comment by hashemp206** [comment]
@appleguy  thanks for trying to fix the bug, bug still exists! and another bug created!
here is how I select cells.
``` objective-c
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
    HAMenuItemCell *cell = (HAMenuItemCell *)[self.collectionView nodeForItemAtIndexPath:indexPath];
    if (cell.selected) {
        cell.selected = NO;
    }
    else
        cell.selected = YES;
}
``` 
then when I scroll down or up without selected cell being disappeared, setSelected:Yes gets called multiple times! 
[sample app](https://db.tt/gszgJZUV)


and here is the new bug:
![cell selection](https://cloud.githubusercontent.com/assets/3206748/11455736/716554a2-9682-11e5-8096-d5768da897cf.gif)

**Comment by levi** [comment]
@hashemp206 try depending on the default behavior of the `selected` property of `ASCellNode` automatically being set by the selection behavior of UICollectionView. Setting `cell.selected = YES` is where you multiple call issue is coming from.

**Comment by levi** [comment]
@hannahbannana this is something that I think fell through the cracks last year. Could you take a look when you have a spare moment?

**Comment by levi** [comment]
Oops, @hannahmbanana

**Comment by hannahmbanana** [comment]
There is definitely an issue with `setSelected:` getting called multiple times here even after excluding the aforementioned manual cell selection code. I interpret the UIKit documentation as saying that they don't do anything in -prepareForReuse, however it appears that UICollectionViewCells have their selected and highlighted states reset when preparing for reuse. I'm not sure of the idea way to resolve this without multiple calls being made, but I'll take a deeper look tomorrow.

**Comment by hannahmbanana** [comment]
Related: #860

**Comment by levi** [comment]
@hannahmbanana thanks for looking into this. I recall testing this behavior on a vanilla UICollectionView and multiple call were being made. Definitely double check that when diagnosing this. Thanks!

**Comment by hannahmbanana** [comment]
@hashemp206: I apologize that it took us a few months to get around to investigating this incorrect behavior. PR #1815 should fix this issue! If you are still using the framework, try it out and let us know if it works for you.
