### ISSUE TITLE
ASDisplayNode transform scale issue

### ISSUE THREAD

**Issue by doguhanokumus** [facebook/AsyncDisplayKit#899]
Hey guys,

I'm trying play around with ASDK, which is pretty awesome so far, but after the 1.9.2 update I started to get an error when I wanted to change a node's scale.

I use pop for animations, and the problem is triggered by using the following code inside a custom pop animation

    POPLayerSetScaleXY(self.layer, CGPointMake(x, x))

and the error is

    'NSInternalInconsistencyException', reason: '-[ASDisplayNode setFrame:] - self.transform
     must be identity in order to set the frame property

I believe the changes in the layout function is causing this, but I don't know how to approach now. another question for me ofc is, have I been doing this scaling wrong the whole time?

**Comment by doguhanokumus** [comment]
ok this issue is no longer happening after the recent updates to the master branch.

**Comment by appleguy** [comment]
@doguhanokumus - hey, thank you for the report!  Indeed, we encountered this problem at Pinterest almost immediately after updating to 1.9.2.  I apologize for shipping the release with this problem, which was of course not known at the time.

Feel free to point at master for the next few days.  I'm planning a 1.9.3 release to launch this weekend and it will include the fix.

**Comment by doguhanokumus** [comment]
@appleguy I do have one more question regarding this. Now the scale animation is running correctly, parent's layout function is called at each step of animation. Is this the desired behavior? Right now my node hierarchy is simple but I wonder if it'll be expensive to use such animations in more complex nodes.
