### ISSUE TITLE
App randomly freezes without providing crashlog when using ASTableView and ASCollectionView at the same time

### ISSUE THREAD

**Issue by jakubheglas** [facebook/AsyncDisplayKit#902]
I don't really know what information can I provide other than the brief construction description, since app can crash without providing us with any information.

*Symptoms of freezing:*
- when connected to debugger, app performs flawlessly
- when launched on it's own, rarely ASTableView loads without content (although cells are counted properly, even imagenode's border is visible) -- wasn't this resolved in last release?
- when that happens, making any interaction like tapping a button FREEZES the app without notice. It doesn't even crash, it just freezes and stays there
- BONUS: when using autolayout, ASCollectionView doesn't even render, so I have to set frame manually instead.

*Construction and resolution:*
- app consists of ASTableView and ASCollectionView, while user can switch between those (they are not visible at the same time)
- they are created programatically, mostly using autolayout
- I was able to minimize occurrence of these freezes by removing all code that animates alpha on table/collectionview (or their wrapper) and by moving their creation to viewDidAppear. That is incredibly weird but works most of the time.
- Also, when NOT creating ASCollectionView at all, 
- however, sometimes the app freezes occasionally when resuming app

EXAMPLE
- How it should look like: http://cl.ly/dxpz/ok.mov
- How it actually looks (app freezes immediately after tapping Title): http://cl.ly/dxeF/bug.mov
- How it looks when content doesn't render on app launch: http://cl.ly/dyuq/IMG_2876.jpg

Asyncdisplaykit performs really well when it works, but those times when it doesnt it's really inconvenient and terrible experience for user, that I'm thinking of dropping my work on this and going forward with standard approach, which is a bummer. 

I wish I could use asyncdisplaykit on regular basis, but finding combinations that work and doesn't work is real productivity issue.

**Comment by jakubheglas** [comment]
I have updated original post with videos

**Comment by aaronschubert0** [comment]
@jakubheglas Could you post some code of the method that calls this interaction? A freeze usually points to something blocking the main thread for a long time.

**Comment by jakubheglas** [comment]
@aaronschubert0 that's the thing, I'm currently working _only_ on the UI, there's no heavy logic. 

I have also blamed myself for adding `reloadData` for when orientation changes which did occur in viewDidLayoutSubviews, but I have fixed that one too, still no luck. Please note currently app does NOT change orientation yet.

I'll post a bit of how Tableview and Collectionviews are made, let me know if there's something I'm missing, but as you can see, code is very simple:

```
- (void)viewDidAppear:(BOOL)animated {
  [super viewDidAppear:animated];
  
  // Putting creation here greatly reduces chance of faulty behavior, yet it still occurs sometimes
  if (self.tableView == nil) {
    [self createTableView];
  }
  if (self.photoGridCollectionView == nil) {
    [self createCollectionView];
  }
}

- (void)viewDidLayoutSubviews {
  [super viewDidLayoutSubviews];
  self.tableView.frame = CGRectMake(0, 0,
                                    self.tableWrapper.bounds.size.width,
                                    self.tableWrapper.bounds.size.height);
  self.photoGridCollectionView.frame = CGRectMake(0, 0,
                                                  self.collectionWrapper.bounds.size.width,
                                                  self.collectionWrapper.bounds.size.height - 8);
}

- (void)createTableView {
  self.tableView = [[ASTableView alloc] initWithFrame:CGRectMake(0, 0, 320, 320) style:UITableViewStylePlain asyncDataFetching:YES]; // CGRectZero may lead to crash
  self.tableView.asyncDataSource = self;
  self.tableView.asyncDelegate = self;
  self.tableView.backgroundColor = [UIColor clearColor];
  self.tableView.alwaysBounceVertical = YES;
  self.tableView.showsVerticalScrollIndicator = NO;
  self.tableView.separatorInset = UIEdgeInsetsMake(0, 48, 0, 0);
  [self.tableWrapper addSubview:self.tableView];
  self.tableView.tableFooterView = [[UIView alloc] initWithFrame:CGRectZero];
  self.tableBackground.backgroundColor = [UIColor baseDayBrown];
  
  // Refresh control for tableView
  self.refreshControl = [[UIRefreshControl alloc] init];
  self.refreshControl.backgroundColor = [UIColor clearColor];
  self.refreshControl.tintColor = [UIColor colorWithWhite:1 alpha:0.54];
  [self.refreshControl addTarget:self action:@selector(refreshData) forControlEvents:UIControlEventValueChanged];
  
  // This little hack allows proper setting of refreshControl property and fixes broken inset on headers
  UITableViewController *tableViewController = [[UITableViewController alloc] init];
  tableViewController.tableView = self.tableView;
  tableViewController.refreshControl = self.refreshControl;
}

- (void)createCollectionView {
  // TODO: add refresh control to collectionview somehow
  UICollectionViewFlowLayout *layout = [[UICollectionViewFlowLayout alloc] init];
  self.photoGridCollectionView = [[ASCollectionView alloc] initWithFrame:CGRectMake(0, 0, 320, 320) collectionViewLayout:layout asyncDataFetching:YES]; // CGRectZero may lead to crash
  self.photoGridCollectionView.asyncDataSource = self;
  self.photoGridCollectionView.asyncDelegate = self;
  self.photoGridCollectionView.backgroundColor = [UIColor clearColor];
  self.photoGridCollectionView.alwaysBounceVertical = YES;
  self.photoGridCollectionView.showsVerticalScrollIndicator = NO;
  [self.collectionWrapper addSubview:self.photoGridCollectionView];
}
```

**Comment by aaronschubert0** [comment]
Thanks @jakubheglas could you post the code that is called when you tap on "Timeline". Since that is where the root issue will most likely be.

**Comment by jakubheglas** [comment]
@aaronschubert0 I'm afraid the freeze occurs in more situations (for example when switching to the collectionview). All these have constraint and transform updates in common. Let me post both methods below.

Also, I'm updating original post with what it looks like when app launches and the content doesnt show up, it's a third example in the list. When that happens, you can be sure the app will freeze on interaction.

```
- (IBAction)calendarButtonTap:(id)sender {
  [self highlightTimelineButton:NO sender:sender];
  [self toggleCalendarWithScale:YES];
}

- (void)toggleCalendarWithScale:(BOOL)scale {
  [self updateTimelineTitleWithDate:self.calendar.currentPage show:!self.isCalendarActive];
  
  // Show Calendar
  if (!self.isCalendarActive) {
    self.tableWrapperTopConstraint.active = NO;
    self.tableWrapperTopCalendarConstraint.active = YES;
    
    if (scale) {
      self.calendar.transform = CGAffineTransformMakeScale(0.9, 0.9);
    }
    [UIView animateWithDuration:0.4 delay:0 usingSpringWithDamping:0.85 initialSpringVelocity:1 options:UIViewAnimationOptionCurveEaseOut animations:^{
      if (scale) {
        self.calendar.transform = CGAffineTransformIdentity;
      }
      self.calendar.alpha = 1;
      [self.view layoutIfNeeded];
    } completion:NULL];
    self.timelineArrow.transform = CGAffineTransformMakeRotation(DEGREES_TO_RADIANS(180));
    
    // Hide Calendar
  } else {
    self.tableWrapperTopCalendarConstraint.active = NO;
    self.tableWrapperTopConstraint.active = YES;
    
    if (scale) {
      self.calendar.transform = CGAffineTransformIdentity;
    }
    [UIView animateWithDuration:0.4 delay:0 usingSpringWithDamping:0.85 initialSpringVelocity:1 options:UIViewAnimationOptionCurveEaseOut animations:^{
      if (scale) {
        self.calendar.transform = CGAffineTransformMakeScale(0.9, 0.9);
      }
      self.calendar.alpha = 0;
      [self.view layoutIfNeeded];
    } completion:^(BOOL finished) {
      if (scale) {
        self.calendar.transform = CGAffineTransformIdentity;
      }
    }];
    self.timelineArrow.transform = CGAffineTransformIdentity;
  }
  
  // Save calendar visibility status
  self.isCalendarActive = !self.isCalendarActive;
}
```

```
- (IBAction)tableSwitchTap:(id)sender {
  [self highlightTimelineButton:NO sender:sender];
  
  // Stop scrolling
  [self.tableView setContentOffset:self.tableView.contentOffset animated:NO];
  [self.photoGridCollectionView setContentOffset:self.photoGridCollectionView.contentOffset animated:NO];
  
  // Show Photo Grid
  if (!self.isPhotoGridActive) {
    self.tableSwitchIcon.image = [UIImage imageNamed:@"IconTimeline"];
    
    self.collectionWrapper.transform = CGAffineTransformMakeTranslation(0, 50);
    self.collectionWrapper.alpha = 1;
    
    [self.tableWrapper setEasingFunction:easeOutExpo forKeyPath:@"transform"];
    [self.tableBackground setEasingFunction:easeOutExpo forKeyPath:@"transform"];
    [self.collectionWrapper setEasingFunction:easeOutExpo forKeyPath:@"transform"];
    
    [UIView animateWithDuration:0.5 animations:^{
      self.tableWrapper.transform = CGAffineTransformMakeTranslation(0, self.tableWrapper.frame.size.height);
      self.tableBackground.transform = CGAffineTransformMakeTranslation(0, self.tableBackground.frame.size.height);
      self.collectionWrapper.transform = CGAffineTransformIdentity;

    } completion:^(BOOL finished) {
      self.tableWrapper.alpha = 0;
      self.tableBackground.alpha = 0;
      [self.tableWrapper removeEasingFunctionForKeyPath:@"transform"];
      [self.tableBackground removeEasingFunctionForKeyPath:@"transform"];
      [self.collectionWrapper removeEasingFunctionForKeyPath:@"transform"];
    }];
    
  // Hide Photo Grid
  } else {
    self.tableSwitchIcon.image = [UIImage imageNamed:@"IconPhotoGrid"];
    
    self.tableWrapper.alpha = 1;
    self.tableBackground.alpha = 1;
    self.tableWrapper.transform = CGAffineTransformMakeTranslation(0, self.tableWrapper.frame.size.height);
    self.tableBackground.transform = CGAffineTransformMakeTranslation(0, self.tableBackground.frame.size.height);
    
    [self.tableWrapper setEasingFunction:easeOutExpo forKeyPath:@"transform"];
    [self.tableBackground setEasingFunction:easeOutExpo forKeyPath:@"transform"];
    [self.collectionWrapper setEasingFunction:easeOutExpo forKeyPath:@"transform"];
    
    [UIView animateWithDuration:0.5 animations:^{
      self.tableWrapper.transform = CGAffineTransformIdentity;
      self.tableBackground.transform = CGAffineTransformIdentity;
      self.collectionWrapper.transform = CGAffineTransformMakeTranslation(0, 50);
      self.collectionWrapper.alpha = 0;
      
    } completion:^(BOOL finished) {
      [self.tableWrapper removeEasingFunctionForKeyPath:@"transform"];
      [self.tableBackground removeEasingFunctionForKeyPath:@"transform"];
      [self.collectionWrapper removeEasingFunctionForKeyPath:@"transform"];
    }];
  }
  
  // Save calendar visibility status
  self.isPhotoGridActive = !self.isPhotoGridActive;
}


```

**Comment by appleguy** [comment]
What is the backtrace?  Is the "freeze" a deadlock?

**Comment by jakubheglas** [comment]
Thing is, app almost never freeze (happened maybe once) when connected to debugger, so it happens mainly when testing "on-the-go". Oh, and when it actually does, it doesn't throw anything into log.

**Comment by appleguy** [comment]
@jakubheglas when that happens, can you suspend the app (just hit the home button) and wait for the crash log to be generated?  If the app is deadlocked, when iOS will kill it once it doesn't respond to the shutdown callbacks for ~10 seconds.  It will then generate a crash log with full backtrace of every thread, which should show us any threads that are deadlocked.

I'm going to read your code in more detail shortly; thank you for posting it to help us investigate!!  I haven't heard of a deadlock reported in ASDK from a user of the stable branch in a long time...in fact, I can't /ever/ recall one report of this type of issue...so I am very eager to figure it out.  Despite being very tough to catch in the act, it is likely an easy fix / diagnosis once we have that crash log pulled from the device.

**Comment by appleguy** [comment]
@jakubheglas LOL well look at that, another user has just today reported a deadlock!  https://github.com/facebook/AsyncDisplayKit/issues/900

Are you using rasterization at all?  (shouldRasterizeDescendants)

**Comment by jakubheglas** [comment]
@appleguy So I did my best to "freeze" the app while being attached to debugger, hit the home button and waited and waited.. and no crashlog. I am not using rasterization anywhere so far.

Now the fun part — when I was typing it, I tried to open the app, left it where it was and then the screen went out. After I picked it again to unlock it, I can see lockscreen with animated unlock prompt and everything, but it doesnt respond to my taps and swipes, AT ALL. So I've killed the app using Xcode and now I had a black screen. To fix this I had to longpress power button to invoke shutdown prompt and dismissed it, then I was back on home screen.

No I don't use jailbreak :))) So..what the what??

**Comment by appleguy** [comment]
@jakubheglas ah, no need to attach the debugger.  Have you looked at saved crashlogs using the Xcode device organizer window?

**Comment by appleguy** [comment]
@jakubheglas - let's track this in the slightly-earlier-filed #900, because I am nearly certain that is the same issue (a third person has reported it).  It would be great if you are able to get the crashlog from pulling it off the device - detailed instructions for this are on the web if you haven't had a need to do it before, which is true for many developers.

As always, but especially for this issue, /thank you/ for taking the time to report it and bring details to the community!!
