### ISSUE TITLE
ASTextNode in ASCollectionNode

### ISSUE THREAD

**Issue by Eke** [facebook/AsyncDisplayKit#909]
First of all, thanks for creating AsyncDisplayKit, it boosted my development a lot.

I Have `ASCollectionNode` placed inside of `ASTableView` (See Screenshot bellow), everything is working fine except `ASTextNode`. Grey background is  `ASTableView`, red `ASCollectionNode`, green each cell of `ASCollectionNode`. `ASTextNode` forces collection cell to grow,but i want text to truncate and become two lines when it reaches cover end.

![screen shot 2015-12-03 at 7 32 03 pm](https://cloud.githubusercontent.com/assets/817489/11564821/a2c801c8-99f4-11e5-9ec5-7deb774ac86a.png)

I want text to truncate and become two lines when it reaches cover end.

`ASTextNode` creation code:
```
_titleNode = [[ASTextNode alloc] init];
_titleNode.attributedString = [[NSAttributedString alloc] initWithString:movie.movie_title attributes:[MVUIHelper movieSectionMainTitleTextStyle]];
_titleNode.maximumLineCount = 2;
_titleNode.layerBacked = YES;
[self addSubnode:_titleNode];
```

Code for `layoutSpecThatFits:`
```
_mediaNode.preferredFrameSize = CGSizeMake(145.0, 235.0);
    _titleNode.flexShrink = YES;
    _titleSubNode.flexShrink = YES;
    
    ASStackLayoutSpec *coverSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                            spacing:0.0 justifyContent:ASStackLayoutJustifyContentStart
                                         alignItems:ASStackLayoutAlignItemsStart
                                           children:@[_mediaNode]];
    
    ASStackLayoutSpec *titlesSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                           spacing:5.0 justifyContent:ASStackLayoutJustifyContentStart
                                                                        alignItems:ASStackLayoutAlignItemsStart
                                                                          children:@[_titleNode,_titleSubNode]];
    titlesSpec.alignSelf    = ASStackLayoutAlignSelfStretch;
    titlesSpec.flexShrink   = YES;
    

    ASInsetLayoutSpec *titleInsetSpec = [[ASInsetLayoutSpec alloc] init];
    titleInsetSpec.insets = UIEdgeInsetsMake(0, 0, 0, 0);
    titleInsetSpec.child = titlesSpec;
    titleInsetSpec.flexShrink = YES;
    titleInsetSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    
    
    ASInsetLayoutSpec *coverInsets = [[ASInsetLayoutSpec alloc] init];
    coverInsets.insets = UIEdgeInsetsMake(0, 0, 0, 0);
    coverInsets.child = coverSpec;
    coverInsets.flexShrink = YES;
    coverInsets.alignSelf = ASStackLayoutAlignSelfStretch;
    
    
    NSMutableArray *mainStackContent = [[NSMutableArray alloc] init];
    [mainStackContent addObject:coverInsets];
    [mainStackContent addObject:titlesSpec];
    
    ASStackLayoutSpec *contentSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                             spacing:8.0 justifyContent:ASStackLayoutJustifyContentStart
                                                                          alignItems:ASStackLayoutAlignItemsStart
                                                                            children:mainStackContent];
    contentSpec.flexShrink = YES;
    
    return [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(0, 0, 0, 0) child:contentSpec];
```

sorry for my bad english.

**Comment by nguyenhuy** [comment]
Definitely need to set a fixed constrained width for your collection cell nodes. They also seem to have the same height as well, right?

```objective-c
- (ASSizeRange)collectionView:(ASCollectionView *)collectionView constrainedSizeForNodeAtIndexPath:(NSIndexPath *)indexPath
{
  return ASSizeRangeMake(CGSizeMake(145.0, 300.0), CGSizeMake(145.0, 300.0));
}
```

Some improvements:
- Should set a ratio to `_mediaNode`, by wrapping it inside a ASRatioSpec, even if the ratio is `235.0 / 145.0`. That way, changing your constrained width will cause the image to be sized correctly.
- Your layout is actually not so complicated and I reckon it can be achieved using only one vertical stack (`contentSpec`):
  - `coverSpec` vertical stack is unnecessary. `_mediaNode` can be a direct child of `coverInsets`.
  - `titlesSpec` vertical stack is also unnecessary. For extra spacing between cover and title (5px?), you can set a bottom value to `coverInsets`.
- Some inset specs with zero values can be removed.
- Set `ASStackLayoutAlignItemsStart` to `alignItems` of the only vertical stack. Then there is no need to set `alignSelf` to its children.
- **Only** _titleNode is flexible (can shrink and grow).

Let me know if this helps.

**Comment by nguyenhuy** [comment]
I made an assumption that you want all sub titles (`_titleSubNode`) of multiple cell nodes to be perfectly aligned. 

If that assumption is wrong, then you don't need a fixed constrained height and `_titleNode` doesn't need to have `flexGrow` enabled.

If the assumption is indeed correct, then collection cell nodes must have the same fixed constrained height. If you don't want to hardcode it, then you can calculate it at run time, by creating a dummy collection node with long enough strings and then calling measuring on the node yourselves. The operation should be cheap enough and can in fact be done off the main thread. It can even be done while the table cell node (that wraps your ASCollectionNode) is being measured.

**Comment by Eke** [comment]
@nguyenhuy , thanks a lot ! everything workes perfectly, you saved my day.

**Comment by appleguy** [comment]
@Eke I am going to take a guess at that writing script - is it Georgian?!  Promise I didn't look at any references, so I could be wildly wrong.  I am very interested in the languages of the world, and it was actually a top consideration of mine in developing AsyncDisplayKit...because more complex scripts like the CJK languages, Thai, Hebrew, Mongolian, Arabic, etc often take 10 times the CPU power to size or render!

Did you have any other questions for us at the moment?  Please file another task any time.

**Comment by Eke** [comment]
@appleguy Yes, it is Georgian. 
AsyncDisplayKit have very big boost to my dashboard, it is 3 or 4 times faster right now.

At this moment i don't have any questions, but i think there will be a lot as i am thinking to move my whole ui to AsyncDisplayKit :smile: 

I found only one problem, maybe it is my mistake or i didn't get the meaning of `ASTextNode` placeholder right, but when i write : 
`````
    _titleNode.placeholderEnabled = YES;
    _titleNode.placeholderColor = [UIColor redColor];
    _titleNode.placeholderFadeDuration = 60.0;
    _titleNode.placeholderInsets = UIEdgeInsetsMake(3.0, 3.0, 3.0, 3.0);
`````

I get something like this: 
![test](https://cloud.githubusercontent.com/assets/817489/11571028/c46d5ade-9a13-11e5-9508-4b389187aab9.png)

You can see text visible in background of placeholder.Maybe is Georgian text causing this, or just me? :smile:

**Comment by levi** [comment]
@Eke setting `placeholderFadeDuration` to 60 will make the animation fade over 60 seconds. I would recommend setting it to 0.4 or 0.2. Moreover, the `placeholderInsets` is the issue you're facing. Simply leave it at the default value of `UIEdgeInsetsZero`.

**Comment by appleguy** [comment]
@Eke hmm, very interesting!  The behavior looks correct EXCEPT of course the fact that it is not removing the placeholder upon the completion of the text rendering.

[edit] - ha @levi is certainly right.  Start by disabling the fade entirely.  That feature is not perfectly reliable and is a bit expensive from a performance perspective because it performs the fades even for things that are offscreen a bit.  It will actually be very simple to improve it using the new ASInterfaceState parameter (we can simply check if the interfaceState is Visible before initiating the fade), but it doesn't work that way today.  I am sure you'd be able to make that change if you are interested in keeping the fade.
