### ISSUE TITLE
ASNetworkImageNode won't display placeHolder image

### ISSUE THREAD

**Issue by hashemp206** [facebook/AsyncDisplayKit#916]
so here it is:

ASDK 1.9.1
```objective-c
_imageNode = [[ASNetworkImageNode alloc] initWithCache:[HAImageCache sharedInstance] downloader:[ASBasicImageDownloader sharedImageDownloader]];
_imageNode.image = [UIImage imageNamed:@"placeHolder"];
.
.
.
_imageNode.URL = [NSURL URLWithString:urlString];
 _imageNode.placeholderEnabled = YES;
 _imageNode.placeholderFadeDuration = 1;
```

if I don't assign imageNode.Url, placeHolder will appear!!!!

so what's the problem?

**Comment by appleguy** [comment]
Fortunately, it's a simple problem - just set .placeholderImage instead of .image :).  This way, the placeholderImage will be shown again if the image scrolls out of view and comes back more quickly than it can be re-decoded (or re-fetched, if necessary).

Note you can also set the .backgroundColor as the best way to use a solid color as the placeholder.

**Comment by appleguy** [comment]
cc @hashemp206 (just to make sure you are notified).  Please reopen the task if you see any behavior problems with this fix!

**Comment by hashemp206** [comment]
thanks for response. 
I just set ```_imageNode.defaultImage``` as a placeHolder.
ASNetworkImageNode also has an inherited property property named ```placeholderColor```. which doesn't work! 

another note is defaultImage won't fade as network image arrives! I want new image set with fade effect.

**Comment by fatuhoku** [comment]
@hashemp206 I've also not managed to get images to fade in by `placeholderColor` only.

I've opened #1442 to track this.

**Comment by aliasnoa** [comment]
@fatuhoku How did you do a placeholder color?  This isn't working:

postImage.placeholderEnabled = true
        postImage.placeholderColor = UIColor.brownColor()
        postImage.placeholderFadeDuration = 0.1

What else do I have to do?

**Comment by hashemp206** [comment]
@aliasnoa what you need to do is subclass `ASNetworkImageNode` and override `placeholderImage` method:
then you can return any default image or create image with colors via built in methods

```swift
override func placeholderImage() -> UIImage? {
         return UIImage.as_resizableRoundedImage(withCornerRadius: 0, cornerColor: UIColor.clear, fill: UIColor(colorLiteralRed: 239/255.0, green: 242/255.0, blue: 246/255.0, alpha: 1))
    }
```

**Comment by aliasnoa** [comment]
@hashemp206 Wow Thanks man! Finally got my images to fade in.  Been trying to do this for so long!
