### ISSUE TITLE
[CALayer thread safety] Pitfalls / techniques with -renderInContext:

### ISSUE THREAD

**Issue by vizlabxt** [facebook/AsyncDisplayKit#920]
Hi, @appleguy :

I've been recently reading the source code of ASDK, It's really awesome! 

My question is : have you considered using CALayer's API: 

`- (void)renderInContext:(CGContextRef)ctx;"`?

Here is some sudo code:

```c

   dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        
        UIGraphicsBeginImageContext(CGSizeMake(100, 100));
        
        CGContextRef context = UIGraphicsGetCurrentContext();
        
        [self.headIcon.layer renderInContext:context];
        UIImage* image = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
        
        dispatch_async(dispatch_get_main_queue(), ^{
            UIView* someOtherView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
            someOtherView.layer.contents = (__bridge  id)image.CGImage;
            [self.view addSubview:someOtherView];
        });
    });

```

This way I can still use UIKit objects and get layer's snapshot on the background thread.

Is there any thread-safety reason or other problems with this method?

**Comment by aaronschubert0** [comment]
@vizlabxt Is this not possible, once the node has loaded, i.e is on the main thread?

**Comment by vizlabxt** [comment]
@aaronschubert0 I'm not talking about ASDisplayNode here. I'm thinking if I can get a snapshot from a normal UIKit object in the background thread, I don't have to use ASDK to achieve the asynchronous rendering. As @appleguy says, the CoreAnimation is designed for main thread only. However, the `   [self.headIcon.layer renderInContext:context];` can be executed safely in background thread.

**Comment by appleguy** [comment]
@vizlabxt it is not safe to call that method on a background thread, especially with UIView objects' .layers in the hierarchy...

**Comment by appleguy** [comment]
Additionally, renderInContext: is very inefficient.  Suggest using shouldRasterizeDescendants, but indeed that cannot rasterize non-node content.

**Comment by appleguy** [comment]
(I'm happy to share more details / thoughts here when I have a bit more time, just in meetings at the moment.  Even though your app will not crash immediately when you call this on renderInContext:, it will crash sometimes, and it is not safe to call that method in the background so you should not ship an app that relies on it).

**Comment by vizlabxt** [comment]
@appleguy thanks! 

The code above works just fine, but I'm not sure if that's just a coincidence. Really curious about how Core Animation work under the hood . Wish you could share some thoughts on this topic if you have time !

**Comment by appleguy** [comment]
@vizlabxt - I'm sorry I'm really behind on replying to this. :) I'm quite busy trying to get ASDK 2.0 ready, but if you have any specific questions about Core Animation, feel free to email me directly at asyncdisplaykit@gmail.com. I'm typically able to reply more quickly. 

I’m going to mark this issue as closed. Thanks for submitting your question! I hope you have been able to use the framework!
