### ISSUE TITLE
[Animation Tips] Walkthrough on animation features for ASCellNode.

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#921]
Guys do we have example for animate showing CellNode? Now its blinked.

**Comment by appleguy** [comment]
Are you using -reloadData?  Try using beginUpdates & endUpdates.  There are a variety of animation features and it should certainly be able to do what you need.

@bimawa if you could include a screen capture video (QuickTime Player can do this - go to the File menu and create a screen recording), and also share a few lines of your implementation for where you're triggering the reload, and explain the animation you would like — we can definitely get you set up!

**Comment by bimawa** [comment]
@appleguy No its not reloadData its when cells show from cash and bring to mainThred. When i scroll CollectionView or tableView. I just need advice what i must observe where cell is calculated and showed on scrollView? Now i use delegate `imageNodeDidFinishDecoding` and paste animation block in it. But its not cool solution if my CellNode haven't a image.

**Comment by Adlai-Holler** [comment]
@bimawa Maybe `tableView:willDisplayNodeForRowAtIndexPath:` will help? I haven't tried this personally, but something like this might work:

```swift
func tableView(tableView: ASTableView, willDisplayNodeForRowAtIndexPath indexPath: NSIndexPath) {
    // Get the node now, in case its index path changes while we wait for it to be in the table.
    guard let node = tableView.nodeForRowAtIndexPath(indexPath) else { return }

    // Dispatch async to wait for the node to truly get displayed.
    dispatch_async(dispatch_get_main_queue()) {
        // At this point, view for `node` is almost certainly in the table view.
    }
}
```

**Comment by bimawa** [comment]
@Adlai-Holler nop not help, and i think its a bad practics, couse CellNode calculated in background, and showing only if end it. I'm still researching....

**Comment by bimawa** [comment]
I found something. I think we must override this method `- (void)displayDidFinish` but they not called..
strange behavior i need more skills. 
I found this method successful called in `ASDisplayNode` class:

```objc
- (void)didDisplayAsyncLayer:(_ASDisplayLayer *)layer
{
  // Subclass hook.
  [self displayDidFinish];
}
```

but my CellNode inherited class not call my overrated method:

```objc
- (void)displayDidFinish
{
    [super displayDidFinish];

    [UIView animateWithDuration:5 animations:^{
        self.alpha = 1;
    }];
}
```

Its a bug or feature?
I need help guys...

**Comment by hannahmbanana** [comment]
@bimawa: again, I am very sorry it took so long to answer this! Were you able to figure this one out?

**Comment by appleguy** [comment]
There is a new method in the latest version called -displayStateDidChange:  I'm not sure what the full context is here but you might find this useful.

**Comment by bimawa** [comment]
Guys, i'm solved it with another way, but i get `displayStateDidChange` in mean, ty . I'll close this issue.
