### ISSUE TITLE
[ASDisplayNode] Seeking information on thread affinity / setting properties on background threads.

### ISSUE THREAD

**Issue by vikas4goyal** [facebook/AsyncDisplayKit#934]
some time application crash. please check attached snapshot.
it shows error on  _bridge_prologue in set frame. can anyone tell why it occured or at least tell me which  condition failed or common scenario  on which this happens so i can check it.
i am using AsyncDisplayKit version 1.9.2
Thanks, :)

![screen shot 2015-12-11 at 4 54 20 pm](https://cloud.githubusercontent.com/assets/2899898/11742943/b624fa38-a029-11e5-9800-07ea4a607aa5.png)

**Comment by appleguy** [comment]
@vikas4goyal Thanks for reporting!  This is expected behavior if you set UIView or CALayer-backed properties on a node **on a background thread** after it is loaded (isNodeLoaded).

Said another way: if you have accessed the .view or .layer property of a node, as happens if it is visible onscreen, after that point you **cannot set UIView / CALayer properties on a background thread**.

For the vast majority of apps / architectures, this isn't a problem to avoid.  If you are wondering how to achieve a certain effect or implementation and aren't sure how to do it, let's discuss the details here!

**Comment by vikas4goyal** [comment]
So if i set image property of ASImageNode then it will load the view ?? or we can only load the node via access .view or .layer property

**Comment by appleguy** [comment]
@vikas4goyal - great question! Also sorry for the delay, it's been a busy few months. 

Nearly all properties required by the framework are thread safe and do not create the underlying view object. The only exceptions are special wrapper nodes, such as ASEditableTextNode and ASMapNode, which provide a property for their special view type, but of course these are still direct access to the views. 

That said, the behavior has been significantly upgraded and we now support completely thread safe property writing from background threads, even to view and layer bridged properties. 

You still must not use the view or layer itself, or set properties on it directly from background threads. But if you do so through the node properties, these will be automatically transactionalized and applied on the main thread in an efficient manner. As always, you can set these properties even before the node loads and it will not trigger creation of the view. But the new behavior is that you can still set these bridge properties in the background even after the view or layer has been loaded. 

All that said, it is still not possible to synchronously read the value of a bridged property from a background thread after the view or layer has loaded. 

So for example, setting the attributedString of an ASTextNode from a background thread is always safe and will never trigger the node to load. 

If you are curious about how this behavior works, look into ASPendingStateController and _ASPendingState. 

Feel free to reopen the issue if you have questions about any of this. I'd be happy to answer them.
