### ISSUE TITLE
Adding any value for NSUnderlineStyleAttributeName causes NSParagraphStyle lineSpacing to be ignored

### ISSUE THREAD

**Issue by bsmith11** [facebook/AsyncDisplayKit#940]
Using `ASTextNode`, adding any value for `NSUnderlineStyleAttributeName` causes the `lineSpacing` value to be ignored in `NSParagraphStyleAttributeName` value objects. I have tested this using `UILabel` and it works correctly. Using ADK 1.9.3. Example:

```objc
NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
paragraphStyle.lineSpacing = 10.0f;
NSDictionary *attributes = @{NSForegroundColorAttributeName:[UIColor blackColor],
                             NSFontAttributeName:[UIFont systemFontOfSize:14.0f],
                             NSParagraphStyleAttributeName:paragraphStyle};
NSMutableAttributedString *mutableAttributedString = [[NSMutableAttributedString alloc] initWithString:@"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                                                                                            attributes:attributes];

[mutableAttributedString addAttribute:NSUnderlineStyleAttributeName 
                                value:@(NSUnderlineStyleSingle)
                                range:NSMakeRange(10, 10)];

self.textNode.attributedString = mutableAttributedString;
```

<img width="375" alt="screen shot 2015-12-14 at 12 46 12 pm" src="https://cloud.githubusercontent.com/assets/7103810/11788839/f6e77e2c-a260-11e5-832e-79962a884ec5.png">

<img width="376" alt="screen shot 2015-12-14 at 12 47 27 pm" src="https://cloud.githubusercontent.com/assets/7103810/11788845/fe63f6b2-a260-11e5-84da-18f5c5bf0b28.png">

**Comment by samhsiung** [comment]
might be an issue with `ASCleanseAttributedStringOfCoreTextAttributes` in `ASTextKitCoreTextAdditions`  which scrubs unsupported CoreText attributes.

**Comment by bsmith11** [comment]
That's definitely it, I just did some testing to confirm. I'm already removing/converting CoreText attributes prior to this, so I know that I don't have any in the attributes. So it looks like `kCTUnderlineStyleAttributeName` has the same value as `NSUnderlineStyleAttributeName`. This triggers the `ASAttributeWithNameIsUnsupportedCoreTextAttribute` method to return YES. This causes `NSAttributedStringAttributesForCoreTextAttributes` to be called which tries to cleanse my attributes of CoreText attributes. Same as underline, `kCTParagraphStyleAttributeName` has the same value as `NSParagraphStyleAttributeName`, which triggers the conversion method `paragraphStyleWithCTParagraphStyle` to pass in my `NSParagraphStyle` object casted as a `CTParagraphStyleRef`. Since its not actually the CoreText version, my custom values don't get transferred to the newly created `NSParagraphStyle`.

Seems like we could fix it by adding an additional check in `NSAttributedStringAttributesForCoreTextAttributes` to see if the paragraph style is actually a `CTParagraphStyleRef`. If that sounds good, I'll open a PR with the fix.

**Comment by appleguy** [comment]
@bsmith11 thanks a lot for BOTH the report - and the fix!  Really, even just the report was a great contribution to us.  Hope to see you around!  (if you're in SF, feel free to come visit the new Pinterest building if you're curious)
