### ISSUE TITLE
[Question] ASEditableTextNode as a child of layer-backed nodes.

### ISSUE THREAD

**Issue by bimawa** [facebook/AsyncDisplayKit#953]
Guys i made custom `ASCellNode` and try add two `ASEditableTextNode's`, after that i catch exception on  `ASDisplayNode (UIViewBridge):215`. Its related with `Does not support layer backing.` or it's a bug? 
p.s. i use LyoutSpec

**Comment by appleguy** [comment]
@bimawa Could you please share some additional information?  I can't quite tell what your issue is yet.

- What is the exact, full exception message that is shown?
- What is the exact line number that it is referencing, and what version / commit of the framework are you using?  I looked at line 215 in my local copy, but it has no assertion or exception there.  Please try using the latest master build, or using 1.9.3 is fine too.
- Note that ASEditableTextNode is one of the only nodes that requires being view-backed.  This means you cannot add it to a supernode that is layer-backed.  ASCellNode is the other node that can't be layer-backed.  You didn't add enough information for me to tell what you've set up, but if you have a subnode of the ASCellNode that is marked as layerBacked = YES, and then are adding the editable node to that, that's your bug.  Just remove the layerBacked = YES for any supernode of the editable text node.

**Comment by bimawa** [comment]
@appleguy

>What is the exact, full exception message that is shown?

`Uncaught exception: CALayer position contains NaN: [nan 19.75]`
Method `- (void)__setSafeFrame:(CGRect)rect` try setup a frame with next data: `rect = (origin = (x = 0, y = 0), size = (width = 0, height = 0))` on line ` _layer.position = position;`
If i use ASLayoutSpec!

>of the framework are you using?

last version 1.9.3 from cocoapods

> Just remove the layerBacked = YES

its a ASCellNode. It does what I need set layerBacked to NO for ASCellNode, ASTableNode too?

piece of my code with error:
bellow class is inherit ASCellNode

```objc
@interface TCTrendsFilterPriceCellNode () <ASEditableTextNodeDelegate>
@property (nonatomic, strong) ASEditableTextNode *fromPriceTextNode;
@property (nonatomic, strong) ASEditableTextNode *toPriceTextNode;
@end

@implementation TCTrendsFilterPriceCellNode
{

}


- (id)init
{
    self = [super init];
    if (self)
    {
        self.fromPriceTextNode                           = [[ASEditableTextNode alloc] init];
        self.fromPriceTextNode.placeholderEnabled        = YES;
        self.fromPriceTextNode.attributedPlaceholderText = [[NSAttributedString alloc] initWithString:@"от 500" attributes:[self p_placeholderAttributes]];
        self.fromPriceTextNode.returnKeyType             = UIReturnKeyDone;
        self.fromPriceTextNode.delegate                  = self;
        self.fromPriceTextNode.textView.keyboardType     = UIKeyboardTypeDecimalPad;
        self.fromPriceTextNode.cornerRadius              = 3;
        self.fromPriceTextNode.textContainerInset        = UIEdgeInsetsMake(8, 16, 8, 16);
        self.fromPriceTextNode.borderColor               = [UIColor tc_coolGreyColor].CGColor;
        self.fromPriceTextNode.borderWidth               = 1;
        [self addSubnode:self.fromPriceTextNode];

        self.toPriceTextNode                           = [[ASEditableTextNode alloc] init];
        self.toPriceTextNode.placeholderEnabled        = YES;
        self.toPriceTextNode.attributedPlaceholderText = [[NSAttributedString alloc] initWithString:@"до 5000" attributes:[self p_placeholderAttributes]];
        self.fromPriceTextNode.returnKeyType           = UIReturnKeyDone;
        self.fromPriceTextNode.delegate                = self;
        self.fromPriceTextNode.textView.keyboardType   = UIKeyboardTypeDecimalPad;
        self.toPriceTextNode.textContainerInset        = UIEdgeInsetsMake(8, 16, 8, 16);
        self.toPriceTextNode.cornerRadius              = 3;
        self.toPriceTextNode.borderColor               = [UIColor tc_coolGreyColor].CGColor;
        self.toPriceTextNode.borderWidth               = 1;
        [self addSubnode:self.toPriceTextNode];
    }

    return self;
}

//It's commented worked code now
/*- (CGSize)calculateSizeThatFits:(CGSize)constrainedSize
{
    CGSize  selfSize       = CGSizeMake([[UIScreen mainScreen] bounds].size.width, 50); //`constrainedSize` contained strange value on this step i override it with hardcoded.
    CGFloat textInputSizes = (CGFloat) (selfSize.width * 0.402667);
    CGFloat separatorSizes = (selfSize.width - (textInputSizes * 2)) / 3;

    self.fromPriceTextNode.frame = CGRectMake(separatorSizes, 10, textInputSizes, 36);
    self.toPriceTextNode.frame   = CGRectMake(self.fromPriceTextNode.frame.origin.x + self.fromPriceTextNode.frame.size.width + separatorSizes, 10, textInputSizes, 36);

    return selfSize;
}*/

//This method trow exception
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    self.preferredFrameSize = CGSizeMake(constrainedSize.max.width, 60);
    ASStackLayoutSpec *asStackLayoutSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:24
                                                                            justifyContent:ASStackLayoutJustifyContentCenter alignItems:ASStackLayoutAlignItemsStretch
                                                                                  children:@[self.fromPriceTextNode, self.toPriceTextNode]];
    ASInsetLayoutSpec *insetLayoutSpec   = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(10, 24, 10, 24) child:asStackLayoutSpec];

    return insetLayoutSpec;
}
```

**Comment by hannahmbanana** [comment]
@bimawa: sorry we are _really_ behind on answering this. Were you able resolve this issue? If not, I would be happy to help. 

One thing that I notice in your code is that you are accessing the ASEditableTextNode's `.textView`s before the text node's view is created (BAD).  In the ASEditableTextNode.h file there is the following warning:

```
/**
  @abstract Access to underlying UITextView for more configuration options.
  @warning This property should only be used on the main thread and should not be accessed before the editable text node's view is created.
 */
@property (nonatomic, readonly, strong) UITextView *textView;
```

I would recommend that you move a lot of this code to the `didLoad:` method. Check out this documentation for more info on the common ovverride methods for ASDK subclassing: http://asyncdisplaykit.org/docs/subclassing.html

**Comment by appleguy** [comment]
Closing this thread. Let's continue the conversation over in the PR (#1715)!

**Comment by bimawa** [comment]
@hannahmbanana yea ty worked.

**Comment by hannahmbanana** [comment]
@bimawa: Fantastic! Feel free to open another Issue if you run into any other problems.

**Comment by bimawa** [comment]
Of cause :) Hanna!                                                                                                                                                                                                                                                                                                                                         Best regards, Maxim Bunkov, iOS Developer of ZenMall.                                                                                                                                                                                                                 From: Hannah TroisiSent: пятница, 17 июня 2016 г., 21:07To: facebook/AsyncDisplayKitReply To: facebook/AsyncDisplayKitCc: Maxim Bunkov; MentionSubject: Re: [facebook/AsyncDisplayKit] [Question] ASEditableTextNode as a child of layer-backed nodes. (#953)@bimawa: Fantastic! Feel free to open another Issue if you run into any other problems.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
