### ISSUE TITLE
Custom ASNodeView background is black

### ISSUE THREAD

**Issue by galfaroth** [facebook/AsyncDisplayKit#96]
Hi, I'm using
- (void)drawRect:(CGRect)bounds
  withParameters:(NSDictionary *)parameters
     isCancelled:(asdisplaynode_iscancelled_block_t)isCancelledBlock
  isRasterizing:(BOOL)isRasterizing{

But can't get rid of black background. How to do it?

Using this:
// clear the backing store, but only if we're not rasterising into another layer
  if (!isRasterizing) {
    [[UIColor whiteColor] set];
    UIRectFill(bounds);
  }

Makes it white, but I want it to be opaque.

**Comment by debug29** [comment]
It my be nice to put that in documentation of AsyncdisplayKit
