### ISSUE TITLE
[Question] Nested vertical collection node inside a vertical collection node

### ISSUE THREAD

**Issue by KieranLafferty** [facebook/AsyncDisplayKit#965]
Hey again, 

Running into a bit of a chicken and egg problem whereby I am trying to nest a collection node inside of another collection node (both vertical) as follows

	     ___________________________
	    |        outter CV          |
	    |    ___________________    |
	    |   |                   |   |
	    |   |                   |   |
	    |   |                   |   |
	    |   |                   |   |
	    |   |                   |   |
	    |   |     cell1         |   |
	    |   |                   |   |
	    |   |      (CV)         |   |
	    |   |                   |   |
	    |   |                   |   |
	    |   | __________________|   |
	    |                           |
	    |                           |
	    |    ___________________    |
	    |   |                   |   |
	    |   |     cell2         |   |
	    |   |                   |   |
	    |   |      (CV)         |   |
	    |   |                   |   |
	    |   |                   |   |
	    |   | __________________|   |
	    |                           |		

The issue is that I am unable to get a correct layout/sizing info for cell1/cell2 because in order to calculate I must first assign the asyncDataSource which causes the view to lazy load in (via collectionNode.view.asyncDataSource = ...) which causes a thread affinity assertion on layout. 

In my most ideal scenario I would like to be able to add a collection node to an ASCellNode and then simply use a layout spec to make the cell the full height of the embedded collection node.

Are there any future plans to add the collection node asyncdatasource/delegate to the collection node itself to allow sizing to be calculated before the view has been loaded?

**Comment by KieranLafferty** [comment]
Thanks again for taking the time with my questions! :)

**Comment by appleguy** [comment]
Yes, absolutely!

I believe this is possible today by using an ASStaticLayoutSpec to position the internal collection.  Static is very powerful if you look at all the options related to relative sizes etc.

I am actually currently working on the ability to size collections and tables asynchronously.  If you use a non-flow layout this will likely require implementing a new method in the LayoutInspecting protocol, but it will work out of the box for tables and flow layouts.

This will also introduce a new powerful capability… The ability to synchronously block on the concurrent measurement of just enough content to fill the visible area, allowing UIKit-identical behavior with excellent performance (strictly minimized main thread time).  I need this capability for several places in the Pinterest app, so although it may take a few more weeks for me to finish developing and testing it, it is coming one way or the other!

Do you have a test project, or could you spend a bit of time modifying one of our existing projects, such as the vertical within a horizontal example app?  Having a reduced test case would make it much easier to ensure the functionality does not regress and is tested on every build, as well as demonstrated both to you and the broader community in documentation and so forth.

**Comment by KieranLafferty** [comment]
Yea sure I'll whip something up now. Whats the best way to share it with you?

**Comment by KieranLafferty** [comment]
Added a demo project that fails due to thread affinity. 

https://github.com/facebook/AsyncDisplayKit/pull/966

**Comment by appleguy** [comment]
@KieranLafferty sorry for the lag - this is now radically better in the current version.

I suggest you use ASStackLayoutSpecs for the "inner collection views" - you can even make each item in the stacks or stack of stacks if a grid, be an ASCellNode as there is no restriction on using ASCellNodes inside one another or even outside of tables / collections.

Email me for a Slack invite, would love to discuss your use cases more!
