### ISSUE TITLE
[Examples] ASCollectionView sample app view controller pushes showing UIKit error.

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#970]
Ran on iOS 9 / Swift 2.

The VC pushing behaviour of the example simply doesn't work at all.

**Comment by appleguy** [comment]
@fatuhoku Thank you for report.  Can you give some more details, such as a copy-paste version of the error output, or screenshots of what occurs?

I have been using this example app today to do testing, and it worked fine for me.  It's not a pretty app - it really is meant for testing more than being useful reference code - but it definitely shouldn't have a bug like you mentioned here.  In my testing, I confirmed that the memory behavior is working as expected (pushing many copies of the view, then backing out of them one at a time to ensure that all the memory is released), and didn't notice an issue there - but I also wasn't looking specifically at console output.

**Comment by appleguy** [comment]
Sorry, I'd need to know which example app you're talking about.  Let me know if you have enough details to fix this.

**Comment by fatuhoku** [comment]
Sorry for not responding for a while. @appleguy I'll reopen this if I run into it again.
