### ISSUE TITLE
Do you have a slack or IRC group?

### ISSUE THREAD

**Issue by chrene** [facebook/AsyncDisplayKit#972]
Hi :)

I really like the framework, but I think it lags some guides to get started with 2.0. 
Do you have a slack channel or IRC where you can ask questions?

**Comment by nguyenhuy** [comment]
Thank you for trying out ASDK and welcome to the community! We use neither Slack nor IRC currently. The same matter has been discussed in #729 couple of months ago. I agree that such channel will be useful and not sure why we haven't created it yet. cc @appleguy :P

**Comment by chrene** [comment]
@nguyenhuy that's a shame :/

The question I have is how you can make dynamically sized table nodes.
The following image is how I would like the cells to be rendered

![](http://i.imgur.com/BV1icGY.png)

```swift
  override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec! {
    postNode.flexGrow = true

    let vStack = ASStackLayoutSpec.verticalStackLayoutSpec()
    vStack.spacing = 8
    vStack.flexGrow = true
    vStack.setChildren([titleNode, postNode])

    return ASInsetLayoutSpec(insets: UIEdgeInsets(top: 0, left: 16, bottom: 0, right: 16), child: vStack)
  }
``` 

Result:

![](http://i.imgur.com/b9r59Ek.png)

**Comment by nguyenhuy** [comment]
You can wrap text nodes inside new ASInsetLayoutSpecs, then use those inset specs as children of the stack spec. You can do this because both ASDisplayNode and ASLayoutSpec are subclasses of ASLayoutable, and ASLayoutSpecs accepts ASLayoutable child/children.

**Comment by nguyenhuy** [comment]
BTW, I think you don't need to enable the flexGrow property of these objects at all. Or maybe you have reasons to do so but I don't know :)

**Comment by chrene** [comment]
@nguyenhuy hmm I don't see how that resolves the problem? Just tried with this code and it gives the exact same output. It seems like the cells doesn't know that it should resize it self or something:

```swift
    let insetTitle = ASInsetLayoutSpec(insets: UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0), child: titleNode)
    let insetPost = ASInsetLayoutSpec(insets: UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0), child: postNode)
    let vStack = ASStackLayoutSpec.verticalStackLayoutSpec()
    vStack.setChildren([insetTitle, insetPost])
    vStack.spacing = 8
//    vStack.flexGrow = true // with or without this 
    return ASInsetLayoutSpec(insets: UIEdgeInsets(top: 8, left: 8, bottom: 8, right: 8), child: vStack)
```

**Comment by nguyenhuy** [comment]
Oh, I misread your question. You don't need even new inset specs. Sorry!

After setting a new text, you need to call `cellNode.setNeedsLayout` and things should just work. Example code (with and without animation) can be found [here](https://github.com/facebook/AsyncDisplayKit/blob/master/examples/Kittens/Sample/KittenNode.mm#L185).

**Comment by chrene** [comment]
I tried, but there's no difference :(

```swift
  convenience init(joke: Joke) {
    self.init()
    self.joke = joke
    titleNode = ASTextNode()
    titleNode.attributedString = NSAttributedString(string: joke.title, attributes: TextStyles.titleStyle)
    addSubnode(titleNode)

    postNode = ASTextNode()
    postNode.attributedString = NSAttributedString(string: joke.joke, attributes: TextStyles.jokeStyle)
    addSubnode(postNode)

    // Update layout after setting text
    titleNode.setNeedsLayout()
    postNode.setNeedsLayout()
  }

  override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec! {
    let vStack = ASStackLayoutSpec.verticalStackLayoutSpec()
    vStack.flexGrow = true
    vStack.spacing = 8
    vStack.setChildren([titleNode, postNode])

    return ASInsetLayoutSpec(insets: UIEdgeInsets(top: 8, left: 8, bottom: 8, right: 8), child: vStack)
  }
```

**Comment by nguyenhuy** [comment]
Are you using ASCollectionView?

**Comment by chrene** [comment]
No, I'm using the `ASTableView`
`let tableView = ASTableView(frame: .zero, style: .Plain, asyncDataFetching: true)`

**Comment by nguyenhuy** [comment]
Then your code looks right to me. The [KittenNode](https://github.com/facebook/AsyncDisplayKit/blob/master/examples/Kittens/Sample/KittenNode.mm) in Kittens sample is also a self-sizing table cell node and it works fine. Can you try to post a sample project, I will debug it as soon as available.

**Comment by chrene** [comment]
Let me spare you the time. It seems to be working after I ditched Carthage and used pods instead on the master branch. Maybe Carthage didn't overwrite the old version of framework I used before I switched to the master branch and thus was didn't get the changes or maybe it's just not compatible with carthage. Nevertheless. It works as expected now :) Thanks for your help :)

**Comment by nguyenhuy** [comment]
haha, happy to help (though I didn't help much). I should have asked you what version of ASDK you were using. IIRC, we do support Carthage. If it is Carthage to blame, we actually need to fix it :)

BTW, please remove the unnecessary `setNeedsLayout` calls in `init`, they can turn out to be expensive. Cheers!

**Comment by fatuhoku** [comment]
**I took the initiative to create a Slack group over here**:

https://asyncdisplaykit.slack.com

@nguyenhuy @appleguy @chrene  please feel free to join and chat about ASDK and add any relevant people! I feel like ASDK is really missing its support network.

**Comment by lappp9** [comment]
Nice! Mind if I snag an invite @fatuhoku?

**Comment by nguyenhuy** [comment]
@fatuhoku Invitation please :)

**Comment by appleguy** [comment]
@fatuhoku can you invite me and add me as an administrator? That's funny, it was only two days ago that I tried to create the Slack Channel under that name and was very surprised to find it taken!  At the moment I am now using asyncdisplaykitorg ... But would like to use the name that you have set up :)

Invite me at asyncdisplaykit@gmail.com, and please also send me an email directly in case the invitation gets filtered as spam

**Comment by Krisiacik** [comment]
@fatuhoku  Can you send me an invite too please?

**Comment by fatuhoku** [comment]
Gladly :) just a few moments...

**Comment by nguyenhuy** [comment]
@fatuhoku mine is allforone1511 at gmail

Yes, we should figure out a way to automate the invite system.

**Comment by bimawa** [comment]
Guys pls create IRC channel and made a link to Slack.. I'm just Hate last :(

**Comment by appleguy** [comment]
@bimawa IRC isn't great with sharing images, videos, code snippets, etc that the ASDK community loves to use :)

If you email me at asyncdisplaykit@gmail.com, we'll get you on Slack within a few hours!

**Comment by bimawa** [comment]
@appleguy Hi Scott! Yea i'm in slack, ty for that. Just my Slack have 10 team groups, and its hard load my mac. I try move to IRC for all messagers with bots and BitlBee support.  And images its not trouble for  irc. I'm just open it in my browse in one click. Maybe its possible to connect IRC channel to our Slack? Just for ugly guys like me :)
