### ISSUE TITLE
[Fixed in 1.9.4] ASTextKitRenderer construction on main thread.

### ISSUE THREAD

**Issue by knopp** [facebook/AsyncDisplayKit#974]
We're hitting UIKit limitations pretty hard after iOS 9 update so I thought I'd give AsyncDisplayKit a try. But even with simple collection view where cells have 3 labels the frames are occasionally dropped during scrolling (on iPad Air 2). 

Profiling shows that ASTextNode _renderer is called on main thread and is taking a lot of CPU time. What am I missing here? I though the whole point of AsyncDisplayKit is to move as much processing from main thread as possible, and yet I can see [ASTextKitTailTruncater _truncate] taking 14.1% running time.
```
Running Time	Self (ms)		Symbol Name
1828.0ms   31.4%	0.0	 	          CA::Transaction::commit()
1771.0ms   30.4%	0.0	 	           CA::Context::commit_transaction(CA::Transaction*)
1614.0ms   27.7%	0.0	 	            CA::Layer::layout_and_display_if_needed(CA::Transaction*)
1466.0ms   25.1%	0.0	 	             CA::Layer::display_if_needed(CA::Transaction*)
1461.0ms   25.1%	0.0	 	              -[_ASDisplayLayer display]
1457.0ms   25.0%	1.0	 	               -[_ASDisplayLayer display:]
1456.0ms   25.0%	0.0	 	                -[_ASDisplayLayer _performBlockWithAsyncDelegate:]
1454.0ms   24.9%	0.0	 	                 __27-[_ASDisplayLayer display:]_block_invoke
1453.0ms   24.9%	0.0	 	                  -[ASDisplayNode(AsyncDisplay) displayAsyncLayer:asynchronously:]
1269.0ms   21.8%	0.0	 	                   -[ASDisplayNode(AsyncDisplay) _displayBlockWithAsynchronous:isCancelledBlock:rasterizing:]
1250.0ms   21.4%	0.0	 	                    -[ASDisplayNode(AsyncDisplay) drawParameters]
1246.0ms   21.4%	1.0	 	                     -[ASTextNode drawParametersForAsyncLayer:]
1215.0ms   20.8%	0.0	 	                      -[ASTextNode shadowPadding]
1215.0ms   20.8%	2.0	 	                       -[ASTextNode _renderer]
1203.0ms   20.6%	0.0	 	                        -[ASTextKitRenderer initWithTextKitAttributes:constrainedSize:]
827.0ms   14.2%	0.0	 	                         -[ASTextKitTailTruncater initWithContext:truncationAttributedString:avoidTailTruncationSet:constrainedSize:]
823.0ms   14.1%	2.0	 	                          -[ASTextKitTailTruncater _truncate]

346.0ms    5.9%	0.0	 	                         -[ASTextKitContext initWithAttributedString:lineBreakMode:maximumNumberOfLines:exclusionPaths:constrainedSize:layoutManagerFactory:]
```

**Comment by knopp** [comment]
So, I did a quick hack to remove renderer instantiation from draw parameters (and to delay it until actual rendering) and I don't see any frames being dropped anymore. Is there any reason why the renderer is currently initialized on main thread or is it just something that has slipped under the radar?

**Comment by knopp** [comment]
Patch to illustrate what I did (against 1.9.3)

https://gist.github.com/knopp/a8d5f243801b71451530

**Comment by appleguy** [comment]
@knopp This is fixed in master / 1.9.4.  Sorry I haven't pushed out the release yet!  Can you please test your app against master and a) confirm this issue is completely fixed in your use case, and b) let me know if you see any other problems?

Note that no fix will be able to avoid this cost IF you execute manual layout, and set the text to a size different than the calculatedLayout's size.  If you are using -layoutSpecThatFits: and not also overriding -layout, then this should never be able to happen.

**Comment by knopp** [comment]
Sorry, there's absolutely no difference in current master. The stack trace in profiler is completely identical, and brief look at the code also confirms, that [ASTextNode drawParametersForAsyncLayer:] still instantiate ASTextKitRenderer in main thread, even if actual rendering and layout is done in background.

Can you maybe be more specific about the fix? You can see that [ASTextKitTailTruncater _truncate] is still taking 14.1% CPU time, which seems quite a lot on main thread to just construct draw parameters (the renderer is not actually used until drawRect:withParameters).

Stack trace from current master:
```
Running Time	Self (ms)		Symbol Name
1025.0ms   30.1%	0.0	 	          CA::Transaction::commit()
998.0ms   29.3%	0.0	 	           CA::Context::commit_transaction(CA::Transaction*)
918.0ms   27.0%	0.0	 	            CA::Layer::layout_and_display_if_needed(CA::Transaction*)
856.0ms   25.2%	0.0	 	             CA::Layer::display_if_needed(CA::Transaction*)
855.0ms   25.1%	0.0	 	              -[_ASDisplayLayer display]
848.0ms   24.9%	0.0	 	               -[_ASDisplayLayer display:]
848.0ms   24.9%	1.0	 	                -[_ASDisplayLayer _performBlockWithAsyncDelegate:]
846.0ms   24.9%	0.0	 	                 __27-[_ASDisplayLayer display:]_block_invoke
845.0ms   24.8%	0.0	 	                  -[ASDisplayNode(AsyncDisplay) displayAsyncLayer:asynchronously:]
726.0ms   21.3%	0.0	 	                   -[ASDisplayNode(AsyncDisplay) _displayBlockWithAsynchronous:isCancelledBlock:rasterizing:]
712.0ms   20.9%	0.0	 	                    -[ASDisplayNode(AsyncDisplay) drawParameters]
711.0ms   20.9%	0.0	 	                     -[ASTextNode drawParametersForAsyncLayer:]
692.0ms   20.3%	0.0	 	                      -[ASTextNode shadowPadding]
692.0ms   20.3%	0.0	 	                       -[ASTextNode _renderer]
686.0ms   20.2%	1.0	 	                        -[ASTextKitRenderer initWithTextKitAttributes:constrainedSize:]
481.0ms   14.1%	0.0	 	                         -[ASTextKitTailTruncater initWithContext:truncationAttributedString:avoidTailTruncationSet:constrainedSize:]
475.0ms   13.9%	0.0	 	                          -[ASTextKitTailTruncater _truncate]
185.0ms    5.4%	0.0	 	                         -[ASTextKitContext initWithAttributedString:lineBreakMode:maximumNumberOfLines:exclusionPaths:constrainedSize:layoutManagerFactory:]
```

**Comment by knopp** [comment]
Since I'm seeing exact same behavior with current master I took the liberty to remove [Fixed] from title.  With a trivial case of three text nodes per collectionview node [ASTextKitTailTruncater _truncate] takes 14% on main thread during scrolling (and that is on iPad Air 2), I don't think that's supposed to happen.

**Comment by knopp** [comment]
Looks like 99fbc97bdaecd2f99009b9734ba0f8f2b665632b took care of this.
