### ISSUE TITLE
[ASCollectionView] -reloadDataImmediately loses content offset.

### ISSUE THREAD

**Issue by knopp** [facebook/AsyncDisplayKit#975]
For some reason it doesn't set _superIsPendingDataLoad, which means sections/nodes are redundantly removed / added from the data controller before [super reloadData] is called.

**Comment by appleguy** [comment]
@knopp Interesting.  This method, as implemented, is intended to be the heaviest hammer available to reload anything that could have changed - including the layout of the cells, although it will be cached if it hasn't changed.  What's your use case, and is it possible that a new method like "reload visible" or something else would satisfy your use case?  Is it not feasible for you to add / remove items directly?

**Comment by knopp** [comment]
I'm not sure I understand your reply. Current implementation looks like this

```objectivec
- (void)reloadDataImmediately
{
  ASDisplayNodeAssertMainThread();
  [_dataController reloadDataImmediatelyWithAnimationOptions:kASCollectionViewAnimationNone];
  [super reloadData];
}
```

All I did is add one line
```objectivec
- (void)reloadDataImmediately
{
  ASDisplayNodeAssertMainThread();
  _superIsPendingDataLoad = YES;
  [_dataController reloadDataImmediatelyWithAnimationOptions:kASCollectionViewAnimationNone];
  [super reloadData];
}
```

Given that you call reloadData anyway, I don't see any reason to insert/remove section on table view beforehand. It just seems redundant and doing that also loses content offset.

**Comment by appleguy** [comment]
@knopp Thanks for clarifying that you'd tried that fix.  Have you been running with it for a while, and it seems solid?  I can submit the PR if so, or feel free to do so as well.

Indeed my original reply was unclear, written hastily.  Sorry about that!

**Comment by knopp** [comment]
Yes, I've been running with this for a while. It performs better (there is no redundant row removal/insertion) and it solves the problem with content offset. I'll do pull request later.

**Comment by knopp** [comment]
@appleguy, done https://github.com/facebook/AsyncDisplayKit/pull/1072
