### ISSUE TITLE
What is a ASRelativeSizeRangeMake? Why is it useful?

### ISSUE THREAD

**Issue by fatuhoku** [facebook/AsyncDisplayKit#981]
Can someone please explain what `RelativeSizeRange` is vs. `SizeRange`, and how you're supposed to translate between the two? I can't make sense of it just reading the source code. For instance, here's a snippet taken from `examples/SocialAppLayout`:

```objc
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize {
    
    ASStackLayoutSpec *mainStack = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:6.0 justifyContent:ASStackLayoutJustifyContentStart alignItems:ASStackLayoutAlignItemsCenter children:@[_iconNode, _countNode]];
    
    // set sizeRange to make width fixed to 60
    mainStack.sizeRange = ASRelativeSizeRangeMake(ASRelativeSizeMake(
                                                                     ASRelativeDimensionMakeWithPoints(60.0),
                                                                     ASRelativeDimensionMakeWithPoints(0.0)
                                                                     ), ASRelativeSizeMake(
                                                                                           ASRelativeDimensionMakeWithPoints(60.0),
                                                                                           ASRelativeDimensionMakeWithPoints(40.0)
                                                                                           ));
    return [ASStaticLayoutSpec staticLayoutSpecWithChildren:@[mainStack]];
    
}
```

What if I don't know what the maximum size is? What do I put in the upper bound for the sizeRange then?

Thanks.

**Comment by knopp** [comment]
You can use ASRelativeDimensionMakeWithPercent(1) for full parent size

**Comment by stowy** [comment]
Nodes that specify the size range need to be wrapped in an `ASStaticLayoutSpec` as per the above example. On the static layout spec you can also specify the exact position of the layout (`layoutPosition` property).

As knopp pointed out above, you can use the `ASRelativeDimensionMakeWithPercent` version to specify the size relative to parent in a range of 0 to 1.

**Comment by appleguy** [comment]
@fatuhoku sometimes you want to use CGFLOAT_MAX or the ...Unconstrained constant provided in ASDimension.

Feel free to inquire about any specific layout you're aiming to build. Otherwise, it is difficult to give specific advice on the right approach. All of these things are in Great need of clear documentation, and we have many issues tracking very specific parts of that need, including simplification and examples around preferredFrameSize and sizeRange.

See: issue 73 and others in Ship.

**Comment by fatuhoku** [comment]
@appleguy okay thanks, I ended up not needing to use it. Will ask specific questions instead :D
