### ISSUE TITLE
[ASMapNode] Add support for setting MKMapSnapshotOptions objects.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#988]
I didn't realize until now all the options that MKMapSnapshotOptions provides - wow!

I'm pretty sure we can treat this object as thread safe, so it may actually be ideal to just change the region property into the MKMapSnapshotOptions object (I had not realized this is how the snapshotter itself gets the region until converting some Pinterest code to use ASMapNode, and then noticed it would be an even more convenient conversion if it just took the same object).

**Comment by appleguy** [comment]
cc @aaronschubert0

**Comment by aaronschubert0** [comment]
@appleguy Awesome find! I agree, let's just replace the region property with a `MKMapSnapshotOptions ` 'options' property. Will be straightforward to implement that. Main thing is to apply it to the MKMapView when that is activated. Easy win for the new year.
