### ISSUE TITLE
[ASDisplayNode] When using UIViewController directly, ensure contents is not cleared during nav push.

### ISSUE THREAD

**Issue by tuyuan2012** [facebook/AsyncDisplayKit#991]
When a controller pushes to another controller, the ASNetworkImageNode which is added to a view calls 'willMoveToWindow' method.

The imageNode will call __exitHierarchy so that the its image is clear. When the controller pops out. The imageNode will call enterHierarchy so that its image is display. But it will flash in case of re-display..

The git url of this case is https://github.com/tuyuan2012/LearnASDNode. You can feel the description in the case.

**Comment by appleguy** [comment]
@tuyuan2012 thanks for the test project!  I'm generally aware of this issue, but it's hard to prevent in all cases that people handle nodes — still it is a valid concern and I will double down my efforts to try to make this less likely to happen for users not aware of being careful not to trigger this.  Using something like ASViewController, ASTableView, ASCollectionView should avoid this - but it should really work intuitively / automatically in as many cases as are technically possible.
